### PR TITLE
Show special permissions license descriptions when they exist.

### LINKED ISSUE #6326: allow display of custom licenses in Kolibri
### Observed behavior

from @kollivier 

> Videos with special permissions just say to contact the author, but I think on Studio we can add the actual license text

### Expected behavior

kolibri users should see actual license text

### User-facing consequences

unclear license

### Context

0.13.0

### PR DESCRIPTION
**Pull request by rtibbles**
### Summary
* Shows special permissions license descriptions when they exist instead of translations of the generic text

### Reviewer guidance
Can you set a special permissions license description on Studio and have it rendered in Kolibri?

### References
Fixes #6326 

After:
Screenshot from 2020-05-04 16-12-01

----

### Contributor Checklist

PR process:

- [ ] PR has the correct target branch and milestone
- [ ] PR has 'needs review' or 'work-in-progress' label
- [ ] If PR is ready for review, a reviewer has been added. (Don't use 'Assignees')
- [ ] If this is an important user-facing change, PR or related issue has a 'changelog' label
- [ ] If this includes an internal dependency change, a link to the diff is provided

Testing:

- [ ] Contributor has fully tested the PR manually
- [ ] If there are any front-end changes, before/after screenshots are included
- [ ] Critical user journeys are covered by Gherkin stories
- [ ] Critical and brittle code paths are covered by unit tests

### Reviewer Checklist

- Automated test coverage is satisfactory
- PR is fully functional
- PR has been tested for [accessibility regressions](http://kolibri-dev.readthedocs.io/en/develop/manual_testing.html#accessibility-a11y-testing)
- External dependency files were updated if necessary (`yarn` and `pip`)
- Documentation is updated
- Contributor is in AUTHORS.md

### CODE REVIEW

File: kolibri/core/assets/src/utils/licenseTranslations.js [hunk 1]
```diff
@@ -236,6 +236,13 @@ export function licenseLongName(leUtilsLicenseName) {
 
 // Translated license descriptions, aimed at creators of the content
 export function licenseDescriptionForCreator(leUtilsLicenseName, leUtilsLicenseDescription) {
```
Comment (jonboiser) [inline kolibri/core/assets/src/utils/licenseTranslations.js:238]: Where in Kolibri do you view this "creator" version? I'm assuming the "consumer" version is what's on the Content Page.

Comment (jonboiser) [reply kolibri/core/assets/src/utils/licenseTranslations.js:238]: actually, this doesn't look like function is used anywhere in the code

Comment (rtibbles) [reply kolibri/core/assets/src/utils/licenseTranslations.js:238]: Yeah, I grepped for it and found no references. I thought it best to just make sure the implementation was parallel. I assume this was included in a forward looking way to offline content creation license application.

**Review by jonboiser — APPROVED** [review]
