### PR TITLE
Exclude surveys from quizzes resource selection

### LINKED ISSUE #13631: Exclude surveys from quiz resource import
## Observed behaviour

> Going on the assumption that we do want users to be able to add free response questions in quizzes too, at this time it is possible to add them to a quiz, but it's not possible to save afterwards, with a ``400 Bad Request`` error.
> 
> Image
> 
>   

 _Originally posted by @radinamatic in [#13599](https://github.com/learningequality/kolibri/issues/13599#issuecomment-3133126758)_

## Expected behaviour

Because survey questions have no 'correct' answer, and in some cases have a 'correct answer' chosen at random for the sake of having one, we should not allow them to be included in quizzes.

## Solution

Exclude survey exercises from quiz resource selection in both backend and frontend.

### Backend Changes

**File:** `kolibri/core/content/api.py`

In the `descendants_assessments` action (line 931-952), exclude surveys from the assessment count:

```python
from le_utils.constants import modalities

@action(detail=False)
def descendants_assessments(self, request):
    ids = self.request.query_params.get("ids", None)
    if not ids:
        return Response([])
    queryset = self.filter_queryset(self.get_queryset())
    data = list(
        queryset.annotate(
            num_assessments=SQSum(
                models.ContentNode.objects.filter(
                    tree_id=OuterRef("tree_id"),
                    lft__gte=OuterRef("lft"),
                    lft__lt=OuterRef("rght"),
                    kind=content_kinds.EXERCISE,
                    available=True,
                )
                .exclude(modality=modalities.SURVEY)  # Add this line
                .values_list(
                    "assessmentmetadata__number_of_assessments", flat=True
                ),
                field="number_of_assessments",
            )
        ).values("id", "num_assessments")
    )
    return Response(data)
```

This ensures topic descendant counts exclude surveys, so the UI shows accurate counts of selectable resources.

### Frontend Changes

**File:** `kolibri/plugins/coach/assets/src/views/quizzes/CreateExamPage/sidePanels/QuizResourceSelection/index.vue`

**1. Add a filter function (around line 396, before `isPracticeQuiz`):**
```javascript
const isNotSurvey = item =>
  get(item, ['options', 'modality'], false) !== 'SURVEY';
```

**2. Update the `useResourceSelection` configuration:**

**Bookmarks annotator (line 414):**
```javascript
bookmarks: {
  filters: { kind: ContentNodeKinds.EXERCISE },
  annotator: results => results.filter(isNotSurvey).filter(isPracticeQuiz),
},
```

**Search (add annotator at line 446):**
```javascript
search: {
  filters: {
    kind: ContentNodeKinds.EXERCISE,
    contains_quiz: selectPracticeQuiz ? true : null,
  },
  annotator: results => results.filter(isNotSurvey),
},
```

### Benefits

- Backend: Topic descendant counts accurately reflect selectable resources (excluding surveys)
- Frontend: Surveys are excluded from all quiz resource selection methods (bookmarks, topic tree, search)
- Prevents 400 Bad Request error when trying to save quizzes with survey questions
- Clear UX - incompatible resources are not shown as options

🤖 This issue was updated with resolution details by Claude Code, under supervision, review and final edits by @rtibbles 🤖

### PR DESCRIPTION
**Pull request by AlexVelezLl**
## Summary
* Exclude surveys from quizzes resource selection
* yarn.lock file is updated since I forgot to run `yarn install` on https://github.com/learningequality/kolibri/pull/14042

https://github.com/user-attachments/assets/85a9e06b-9d7f-4630-8cb4-de19e281807e

## References
Closes #13631

## Reviewer guidance
* Import surveys from Kolibri QA Channels.
* Go to coach > quizzes > new quiz > Add resources
* Look for survey resources, and notice that no surveys are displayed.

### CODE REVIEW

**Review by rtibbles — COMMENTED** [review]
Code changes make sense, manual QA checks out for me locally. This is ready for QA review.

**Comment by pcenov** [comment]
Hi @AlexVelezLl - I confirm that now a folder containing surveys is no longer being displayed in the the `Add questions to 'Section N'` side panel but if I click the `Search` button and search for an actual `survey` it still shows up in the search results and the questions can still be selected:

https://github.com/user-attachments/assets/25ffdfed-b7b6-45c3-8a47-ba1cc1031a69

You can replicate this by importing the following test channel: `rasif-rasot`

Note that if I select the `Select quiz` option from the `New quiz` drop-down, then searching for surveys doesn't return any surveys so the above scenario is handled there:

https://github.com/user-attachments/assets/f7c34eb5-f8fa-4460-beda-b275a926ba7b

File: packages/kolibri-common/composables/useBaseSearch.js [hunk 1]
```diff
@@ -282,6 +283,14 @@ export default function useBaseSearch({
     return getParams;
   }
 
+  const getResults = data => {
```
Comment (rtibbles) [inline packages/kolibri-common/composables/useBaseSearch.js]: I am sure this works - but my instinct would have been to enhance the API endpoint to allow us to exclude specific modalities from the search instead, and do this entirely via API query parameters - any advantages to doing it this way instead?

Comment (AlexVelezLl) [reply packages/kolibri-common/composables/useBaseSearch.js]: Implemented in https://github.com/learningequality/kolibri/pull/14050/commits/f452c28ca5afcc5b247c001e4b5b77baea3acc5d!

File: kolibri/core/content/api.py [hunk 2]
```diff
@@ -433,6 +433,10 @@ class CharInFilter(BaseInFilter, CharFilter):
     pass
 
 
+class ChoiceInFilter(BaseInFilter, ChoiceFilter):
```
Comment (rtibbles) [inline kolibri/core/content/api.py:436]: That's the way to do it!

File: kolibri/core/content/api.py [hunk 3]
```diff
@@ -490,6 +494,9 @@ class ContentNodeFilter(FilterSet):
     authors = CharFilter(method="filter_by_authors")
     tags = CharFilter(method="filter_by_tags")
     descendant_of = UUIDFilter(method="filter_descendant_of")
+    exclude_modalities = ChoiceInFilter(
+        field_name="modality", choices=modalities.choices, exclude=True
```
Comment (rtibbles) [inline kolibri/core/content/api.py:498]: Configuration beats manually coding!

File: kolibri/plugins/coach/frontend/views/quizzes/CreateExamPage/sidePanels/QuizResourceSelection/index.vue [hunk 4]
```diff
@@ -443,6 +455,7 @@
           filters: {
             kind: ContentNodeKinds.EXERCISE,
             contains_quiz: selectPracticeQuiz ? true : null,
+            exclude_modalities: Modalities.SURVEY,
```
Comment (rtibbles) [inline kolibri/plugins/coach/frontend/views/quizzes/CreateExamPage/sidePanels/QuizResourceSelection/index.vue:458]: Excellent!

**Review by rtibbles — COMMENTED** [review]
This looks good for a final round of QA to me!

**Review by pcenov — APPROVED** [review]
Thanks @AlexVelezLl - LGTM!
