### PR TITLE
Do not delete `?next` query param when redirected from AuthMessage to SignInPage

### LINKED ISSUE #7896: ?next URL param is lost if going from AuthMessage to SignInPage/Select Facility
### Observed behavior
In incognito mode:

Step 1: Go to https://kolibri-beta.learningequality.org/en/coach/#/0ca0280c91ccb9a880d922914226557f/plan/lessons/a7666d7f39eb34f13965ffa2e443bdee

Screen Shot 2021-03-19 at 3 12 44 PM

Step 2: Click the "Sign in to Kolibri" link

The link is good, and has the `?next` query param

https://kolibri-beta.learningequality.org/en/user/#/signin?next=https%3A%2F%2Fkolibri-beta.learningequality.org%2Fen%2Fcoach%2F%23%2F0ca0280c91ccb9a880d922914226557f%2Fplan%2Flessons%2Fa7666d7f39eb34f13965ffa2e443bdee

Step 3: End up at https://kolibri-beta.learningequality.org/en/user/#/facilities

And the `?next` param is lost 

Step 4: Pick a facility, sign-in, etc. but you won't get redirected to where you were trying to go in Step 1.

### Expected behavior

The `?next` is saved and you are redirected back to that URL after signing in.

### Errors and logs

…

### Steps to reproduce

…

### Context

…

### PR DESCRIPTION
**Pull request by apurva-modi**
Passed the param next to the route whereToNext

…

Step 1: Open the link in incognito mode.
Go to https://kolibri-beta.learningequality.org/en/coach/#/0ca0280c91ccb9a880d922914226557f/plan/lessons/a7666d7f39eb34f13965ffa2e443bdee 

or 

http://127.0.0.1:8000/en/coach/#/cf75dbe3de5a09a2fc9e45702cd6a84e/plan/lessons/0a41af5b21df81371f45d8f05596b3a3

Step 2: Open use the same link to and open it in normal mode.
and you will see something like 

http://127.0.0.1:8000/en/user/#/signin?next=http%3A%2F%2F127.0.0.1%3A8000%2Fen%2Fcoach%2F%23%2Fcf75dbe3de5a09a2fc9e45702cd6a84e%2Fplan%2Flessons%2F0a41af5b21df81371f45d8f05596b3a3

where `?next` param is preserved.

Step 3: Pick a facility, sign-in, etc. and it will redirect you to the STEP 1's resource.

…

### References
FIx for #7896
…

----

### Contributor Checklist

PR process:

- [x] PR has the correct target branch and milestone
- [ ] PR has 'needs review' or 'work-in-progress' label
- [x] If PR is ready for review, a reviewer has been added. (Don't use 'Assignees')
- [ ] If this is an important user-facing change, PR or related issue has a 'changelog' label
- [ ] If this includes an internal dependency change, a link to the diff is provided

Testing:

- [x] Contributor has fully tested the PR manually
- [ ] If there are any front-end changes, before/after screenshots are included
- [ ] Critical user journeys are covered by Gherkin stories
- [ ] Critical and brittle code paths are covered by unit tests

### CODE REVIEW

File: kolibri/plugins/user/assets/src/routes.js [hunk 1]
```diff
@@ -52,6 +52,9 @@ export default [
         if (store.getters.facilities.length > 1 && !store.state.facilityId) {
           // Go to FacilitySelect with whereToNext => SignUpPage
           const whereToNext = router.getRoute(ComponentMap.SIGN_IN);
+          if ((to.query || {}).next) {
```
Comment (jonboiser) [inline kolibri/plugins/user/assets/src/routes.js]:
```suggestion
          if (to.query.next) {
```

I'm pretty sure `to.query` is always defined. Did you get errors if you leave out the default `{}`?

File: kolibri/plugins/user/assets/src/routes.js [hunk 2]
```diff
@@ -52,6 +52,9 @@ export default [
         if (store.getters.facilities.length > 1 && !store.state.facilityId) {
           // Go to FacilitySelect with whereToNext => SignUpPage
           const whereToNext = router.getRoute(ComponentMap.SIGN_IN);
+          if (to.query.next) {
+            whereToNext.query.next = to.query.next;
+          }
```
Comment (jonboiser) [inline kolibri/plugins/user/assets/src/routes.js:58]: This needs to go into the `query` of `route` below. When I get redirected, I just go to this URL, with no `?next` param

http://localhost:8000/en/user/#/facilities

```
          const route = {
            ...router.getRoute(ComponentMap.FACILITY_SELECT),
            params: { whereToNext },
			query: { to.query.next } (only if to.query.next is provided)
          };
```

Comment (jonboiser) [reply kolibri/plugins/user/assets/src/routes.js:57]: Did you create a second facility when you were testing this? If you have more than 1 facility, you will go to the `/facilities` route instead of the `/sign-in` route. Run this command in a second terminal to create a new facility (replace `user:pass` with your own credentials).

```
curl -X "POST" "http://localhost:8000/api/auth/facility/" \
     -H 'Content-Type: application/json; charset=utf-8' \
     -u 'user:pass' \
     -d $'{
  "name": "Second Facility"
}'

```

**Review by jonboiser — CHANGES_REQUESTED** [review]
The `next` param needs to go to the `query` to fix missing `next` param on the `/facilities` route. When testing, you were only looking at the `/sign-in` route, which was not broken previously.

**Comment by apurva-modi** [comment]
> The `next` param needs to go to the `query` to fix missing `next` param on the `/facilities` route. When testing, you were only looking at the `/sign-in` route, which was not broken previously.

The whereToNext contains the information on where to be routed after the facility selection. So even though the facility selection page does not have the next param, the route after facility selection will have. 

Do you want me to change it so that even the facility selection page has the next param?

**Comment by jonboiser** [comment]
> Do you want me to change it so that even the facility selection page has the next param?

Yes, that's the only way you'll get redirected back to the link in Step 1. The sequence of URLS needs to be

1. http://127.0.0.1:8000/en/coach/#/cf75dbe3de5a09a2fc9e45702cd6a84e/plan/lessons/0a41af5b21df81371f45d8f05596b3a3
2. http://127.0.0.1:8000/en/user/#/facilities?next=[encoded URL in Step 1]
3. Pick a Facility
3. http://127.0.0.1:8000/en/user/#/signin?next=[encoded URL in Step 1]
4. Provide credentials
5. Get authenticated, and be redirected to the URL in Step 1

**Comment by apurva-modi** [comment]
> > Do you want me to change it so that even the facility selection page has the next param?
> 
> Yes, that's the only way you'll get redirected back to the link in Step 1. The sequence of URLS needs to be
> 
> 1. http://127.0.0.1:8000/en/coach/#/cf75dbe3de5a09a2fc9e45702cd6a84e/plan/lessons/0a41af5b21df81371f45d8f05596b3a3
> 2. [http://127.0.0.1:8000/en/user/#/facilities?next=[encoded](http://127.0.0.1:8000/en/user/#/facilities?next=%5Bencoded) URL in Step 1]
> 3. Pick a Facility
> 4. [http://127.0.0.1:8000/en/user/#/signin?next=[encoded](http://127.0.0.1:8000/en/user/#/signin?next=%5Bencoded) URL in Step 1]
> 5. Provide credentials
> 6. Get authenticated, and be redirected to the URL in Step 1

I have made the changes as per your suggestions. Please review.

File: kolibri/plugins/user/assets/src/views/FacilitySelect.vue [hunk 3]
```diff
@@ -106,10 +106,14 @@
     },
     methods: {
       setFacility(facilityId) {
+        let whereToNext = { ...this.whereToNext };
```
Comment (jonboiser) [inline kolibri/plugins/user/assets/src/views/FacilitySelect.vue]: You can make this a const, since it's not reassigned 
```suggestion
        const whereToNext = { ...this.whereToNext };
```

File: kolibri/plugins/user/assets/src/views/SignInPage/index.vue [hunk 4]
```diff
@@ -211,7 +211,11 @@
       backToFacilitySelectionRoute() {
         const facilityRoute = this.$router.getRoute(ComponentMap.FACILITY_SELECT);
         const whereToNext = this.$router.getRoute(ComponentMap.SIGN_IN);
-        return { ...facilityRoute, params: { whereToNext } };
+        let query = {};
+        if (this.nextParam) {
+          query = { next: this.nextParam };
+        }
+        return { ...facilityRoute, params: { whereToNext }, query: query };
```
Comment (jonboiser) [inline kolibri/plugins/user/assets/src/views/SignInPage/index.vue]: Use object key shorthand here
```suggestion
        return { ...facilityRoute, params: { whereToNext }, query };
```

File: kolibri/plugins/user/assets/src/routes.js [hunk 5]
```diff
@@ -52,9 +52,14 @@ export default [
...
           // Go to FacilitySelect with whereToNext => SignUpPage
           const whereToNext = router.getRoute(ComponentMap.SIGN_IN);
+          let query = {};
+          if (to.query.next) {
+            query = { next: to.query.next };
+          }
           const route = {
             ...router.getRoute(ComponentMap.FACILITY_SELECT),
             params: { whereToNext },
+            query: query,
```
Comment (jonboiser) [inline kolibri/plugins/user/assets/src/routes.js]:
```suggestion
            query,
```

**Review by jonboiser — APPROVED** [review]
Looks good!
