### PR TITLE
Fix up reactivity and display issues for remote libraries on LibraryPage and ExploreLibrariesPage

### LINKED ISSUE #11379: Other libraries - Incorrect number of channels
## Observed behavior
See the attached video - the correct number of channels is 2 while it shows 134.

## Expected behavior
Correctly displayed number of channels on the device.

## Steps to reproduce the issue
1. Install the latest build from https://github.com/learningequality/kolibri/pull/11177
2. Go to the Library and observe the number of channels on the other devices that are available.

## More information

https://github.com/learningequality/kolibri/assets/79847249/fad5374d-1510-4f0b-948a-eb3f918df86b

## Usage Details
Kolibri 0.16beta6
Ubuntu - Chrome, Firefox

### LINKED ISSUE #11410: Library page only displays a single network device at a time
## Observed behavior
Something very odd is happening in the Library page, where it is failing to reactively update the displayed network devices as it loads the channels

## Expected behavior
All available network devices with channels should be displayed in some shape or form

## User-facing consequences
Bad experience

### LINKED ISSUE #11439: LOD - Library - Incorrectly positioned 'Explore' button
## Observed behavior
On a LOD the 'Explore' button is positioned incorrectly - see the video.

## Expected behavior
To be further discussed.

## Steps to reproduce the issue
1. Install the latest build from https://github.com/learningequality/kolibri/pull/11419 and setup a learn-only device.
2. Go to the Library page and observe the 'Other libraries' section when there are multiple other libraries.

## More information

https://github.com/learningequality/kolibri/assets/79847249/6b37eb81-c1bc-458c-8a7a-11d68de19310

## Usage Details
Kolibri 0.16beta6
Ubuntu - Chrome, Firefox

### LINKED ISSUE #11440: Library - Kolibri Library - Incorrect number of channels
## Observed behavior

The value for the number of channels in the text "4 channels | Internet connection needed to browse and download resources" should be the total number of available channels in that library and not the number of channels displayed at the current view of the Library page.

## Steps to reproduce the issue
1. Install the latest build from https://github.com/learningequality/kolibri/pull/11419 and setup Full facility.
2. Go to the Library page and observe the number of channels displayed under the Kolibri Library heading.

## More information

https://github.com/learningequality/kolibri/assets/79847249/72facfcf-3a57-40fd-8b27-fd5aabef9d33

## Usage Details
Kolibri 0.16beta6
Ubuntu - Chrome, Firefox

### PR DESCRIPTION
**Pull request by rtibbles**
## Summary
* Consolidates all 'devices with channels' logic into the useDevices composable
* Adds extra function usable in a setup function to set up monitoring to keep channel fetching up to date with changes in the available network devices
* Fixes references to total_count that are no longer valid
* Makes display of channels to spec, ensuring that the LibraryPage and ExploreLibrariesPage doesn't display more than 1/2 rows of cards respectively for each library.
* Adds transitions for lists of devices, to ensure that we get a slightly smoother rendering experience as devices pop in and out (can be improved, but is a little less jarring)
* Now that we are continually polling for devices, removes the refresh buttons on the LibraryPage
* Separates out other libraries section of LibraryPage into a separate component to prevent unnecessary polling
* Recreates the PinnedDevice model and simplifies the backend to give consistent UUID representations
* Consolidates all frontend pinned device logic in the usePinnedDevices composable and shares it between LibraryPage and ExploreLibrariesPage

## References
Fixes #11379 (discussed this with @thanksameeelian and will be leaning on her investigations into this for thorough review)
Fixes #11410
Fixes #11439
Fixes #11440

## Reviewer guidance
Ensure that all libraries that should appear, do appear on the LibraryPage and ExploreLibrariesPage, ensure that the rendering of channels within libraries conforms to the spec.

Ensure that pinning and unpinning devices works as expected, and that pinned and unpinned devices display properly on both the LibraryPage and ExploreLibrariesPage.

----

## Testing checklist

- [x] Contributor has fully tested the PR manually
- [ ] If there are any front-end changes, before/after screenshots are included
- [ ] Critical user journeys are covered by Gherkin stories
- [ ] Critical and brittle code paths are covered by unit tests

## PR process

- [x] PR has the correct target branch and milestone
- [x] PR has 'needs review' or 'work-in-progress' label
- [x] If PR is ready for review, a reviewer has been added. (Don't use 'Assignees')
- [ ] If this is an important user-facing change, PR or related issue has a 'changelog' label
- [ ] If this includes an internal dependency change, a link to the diff is provided

## Reviewer checklist

- Automated test coverage is satisfactory
- PR is fully functional
- PR has been tested for [accessibility regressions](http://kolibri-dev.readthedocs.io/en/develop/manual_testing.html#accessibility-a11y-testing)
- External dependency files were updated if necessary (`yarn` and `pip`)
- Documentation is updated
- Contributor is in AUTHORS.md

### CODE REVIEW

**Review by thanksameeelian — COMMENTED** [review]
i think almost all of the behavior i'd noted before has been handled! 

i noticed i do spend a couple seconds with an `Other libraries` header with just empty space below it, before the page refreshes and i'm able to see available libraries in that space. i was curious whether it might be appropriate to include a "no content" placeholder card or not render the header when there aren't other libraries to display, but for me at least it is a pretty short wait before the expected content appears. 

https://github.com/learningequality/kolibri/assets/43046460/0f982142-ea60-4937-a5e5-1786efeac677


this PR fixes the main issue at hand - an inaccurate count of channels on cards beneath the "Other libraries" header, with channels sometimes attributed to the incorrect library once the content is explored (e.g. `marcella's mbp` library header displayed, but all channels/content listed below belonging to studio) - to me these issues appear resolved. i also couldn't replicate the 0 channels / No connection display or the specific perpetual loading & other small bugginess i'd seen earlier within explore libraries! 

the one thing i did notice was some perpetual loading behavior in explore libraries that is a little different from what i noticed/reported before - i was able to trigger a perpetually loading top bar when i was in explore libraries and applied search/content filters to the displayed channels - what i noticed/tested out showed that clicking on any activity or combo of activities triggered the loading state, as well as selecting any of the "show resources" checkboxes, but may extend a little beyond that


https://github.com/learningequality/kolibri/assets/43046460/b97831a9-853b-4b21-b48f-b04cfad78def

i included the slightly odd beginning of this video because that's where i ended up the first time i tried this flow and followed the same steps as i do later on in the video to exit out of the selected filters - i was unable to replicate this when i repeated the process but thought the bugginess may be worth capturing in case it is seen again in other testing

**Comment by rtibbles** [comment]
> i noticed i do spend a couple seconds with an Other libraries header with just empty space below it, before the page refreshes and i'm able to see available libraries in that space.

I do think having a loading state here before any libraries are populated would probably be best.

> i was able to trigger a perpetually loading top bar when i was in explore libraries and applied search/content filters to the displayed channels

I suspect that this is an interaction with the code that is running in `setup` now in the LibraryPage, which is used for exploring a specific library within the ExploreLibrariesPage. Will attempt to replicate to confirm.

**Comment by rtibbles** [comment]
Both of these should be fixed - the perpetual loader was actually caused by the fact that we were setting the core loading state to true in the handler (which is executed on _every_ route navigation event to the library page) but we were only clearing it when `showLibrary` is run, which only happens when the deviceId changes or the component is recreated. Have cleaned it up by moving control of the core loading state into the component.

**Comment by thanksameeelian** [comment]
> Both of these should be fixed - the perpetual loader was actually caused by the fact that we were setting the core loading state to true in the handler (which is executed on _every_ route navigation event to the library page) but we were only clearing it when `showLibrary` is run, which only happens when the deviceId changes or the component is recreated. Have cleaned it up by moving control of the core loading state into the component.

yes, i can confirm both these appear to be fixed now! i wasn't able to replicate most of the previous smaller bugs i'd seen or  the bugs in the referenced github issues. 

i ended up noticing something a little odd that might reflect a mismatch in the way pinned devices are understood on the `Library` vs `Explore Libraries` pages (or might reflect my own ignorance about expected behavior) - the `Test` library i have pinned, which displays topmost & as pinned in `Library`, doesn't appear to be pinned once viewed in `Explore Libraries` > `All libraries`.

Screen Shot 2023-10-17 at 4 28 03 PM

Screen Shot 2023-10-17 at 4 28 27 PM

when, on a dreadful whim, i clicked the pin icon for `Test` on that page (to see if it would unpin it in the `Library` view) and ended up in a scenario where i found it impossible to pin anything new and was met with errors...but it appears it did toggle the pinned/unpinned state overall as `Test` is no longer under the `Pinned` header on `Library` and that header isn't rendered entirely. i also noticed that in this case, i was again seeing the connection problem string -- `Internet connection needed to browse and download resources` for Kolibri Library, but was perfectly able to browse resources and drilled down to opening PDFs, etc. by the end of my testing around, the `Test` library seemed to have genuinely gone offline, but i was also unable to pin marcella's library as seen in the screen recording below, at least based on what is displayed in the UI. 


https://github.com/learningequality/kolibri/assets/43046460/60abeca2-817e-411e-8d43-4a97e989cafe

i wasn't sure if it was possible this was a localized problem particular to something in my setup or could be related to all the libraries i was trying to pin getting coincidentally taken offline during my testing, but the behavior gave me pause and i'm interested to see if others are able to replicate it.

**Comment by rtibbles** [comment]
OK, @thanksameeelian - I think the pinned devices should all be working as intended now - there were some serious issues with it, that had somehow escaped our notice up until now.

File: kolibri/plugins/learn/assets/src/views/LibraryPage/OtherLibraries.vue [hunk 1]
```diff
@@ -0,0 +1,178 @@
...
+      data-test="pinned-label"
+    >
+      {{ injectedtr('pinned') }}
+    </h2>
+    <PinnedNetworkResources
+      v-if="pinnedDevicesExist"
+      data-test="pinned-resources"
+      :devices="pinnedDevices"
+      :deviceChannelsMap="deviceChannelsMap"
+      :channelsToDisplay="cardsPerRow * 2 - 1"
```
Comment (akolson) [inline kolibri/plugins/learn/assets/src/views/LibraryPage/OtherLibraries.vue]: It feels very abstract what `cardsPerRow * 2 - 1` is doing. It might be a better idea to implement a computed property with a good descriptive name/comment instead?

**Comment by pcenov** [comment]
Hi @rtibbles and @thanksameeelian, here are my observations based on testing mainly real world scenarios on a setup of several devices and VMs.

1. LOD: Other libraries > View all - There are no libraries being displayed at `/learn/#/explore_libraries?prevName=LIBRARY`:

https://github.com/learningequality/kolibri/assets/79847249/bb0623b7-2a86-492f-980e-40e626b58918

2. Full facility - Disappearing 'More' section resulting in missing 'View all' card, so that if I have pinned a device and there are no other devices I can no longer unpin it. The same is valid if I have pinned all the available devices:

https://github.com/learningequality/kolibri/assets/79847249/53d66fcf-9244-4b6a-9980-79069ea81957

3. If I pin a LOD and then stop the device it remains visible in the Other libraries section for a period of time which can be quite confusing:

https://github.com/learningequality/kolibri/assets/79847249/6988092b-0aa3-4d7a-b9d9-0424fc58786a

4. In some cases I am seeing only the 'More' label with a bunch of `TypeError: Cannot read properties of undefined (reading 'length')` errors. I'm not able to reliably replicate this behavior but it did occur several times so I'm mentioning it here.




Ubuntu Server logs: [logs.zip](https://github.com/learningequality/kolibri/files/13030598/logs.zip)

File: kolibri/plugins/learn/assets/src/views/LibraryPage/OtherLibraries.vue (hunk 1 above)
Comment (rtibbles) [reply kolibri/plugins/learn/assets/src/views/LibraryPage/OtherLibraries.vue]: Can do!

**Comment by rtibbles** [comment]
Thanks @pcenov, I am confident that I have fixed 1 and 2 - I think 3 should be fixed, but I am not completely sure, and I could not replicate 4, and am at a loss as to where to add a defensive check to stop it from happening.

Any further leads gratefully received!

File: kolibri/plugins/learn/assets/src/views/LibraryPage/OtherLibraries.vue (hunk 1 above)
Comment (rtibbles) [reply kolibri/plugins/learn/assets/src/views/LibraryPage/OtherLibraries.vue]: Updated!

**Review by akolson — COMMENTED** [review]
On a code level(and with some manual testing), the changes look correct to me and checkout with the PR summary. Once @pcenov is happy, we should be good to go :)

**Review by pcenov — APPROVED** [review]
I confirm that the issues reported by me are fixed now. I was able to identify the following issues which I will mention here but which I can report separately as well if deemed valid but out of scope for this PR:

1. There's no clear indication that I've lost my connection - the Kolibri Library appears available but clicking on a resource just brings me back to the Library page:

https://github.com/learningequality/kolibri/assets/79847249/94a34eb1-1d7d-4e32-9a2a-435560d2a183

2. For a LOD in mobile view we are showing only one of the available devices (in Figma there are 3):

https://github.com/learningequality/kolibri/assets/79847249/7c91afae-0a4b-49cb-ac82-348fc0523c67

3. The 'Pinned' text disappears when I've pinned all libraries (also in some other cases but I don't have replication steps):

https://github.com/learningequality/kolibri/assets/79847249/8007dd89-c223-4da4-b326-7774a7d474a0

4. The 'Recent' section can get quite long - a 'View more' link is shown in Figma when there are more than 3 cards:

https://github.com/learningequality/kolibri/assets/79847249/fc799e16-3115-412c-a621-607094da736e

**Comment by rtibbles** [comment]
Thanks @pcenov I'll fix up 2,3, and 4 in this PR, as they are small changes to responsiveness and will bring us better aligned to spec!

1 can be filed as a follow up.

**Comment by rtibbles** [comment]
Hi @pcenov - I consulted with @jtamiace and we made some updates to address the issues you raised here, but in doing so have deviated somewhat from the spec (and in other ways hewed closer to it). Other things were simply unspecified.

Important changes:
* When there are three or fewer libraries, they are all displayed in full regardless of whether they are pinned or unpinned.
* For any user that can browse Kolibri Studio, it should always be first in the ordering.
* To accommodate the 'three or fewer libraries' preventing navigation to the Explore Libraries page, the libraries listed on the Library Page can now be pinned and unpinned in the same way as the Explore Libraries Page.
* In doing this, the way to 'explore' a specific library has been aligned with the button used in the Explore Libraries Page, rather than the card that was previously being used.
* In addition, the same now happens for exploring all the unpinned devices when they appear in a card form (i.e. when there are more than 3 devices total, and there are unpinned devices).
* All channel listings on both the Library Page and the Explore Library Page should now display a minimum of three cards, regardless of window breakpoint.
* On the Library Page, displayed channels will show at least 2 full rows of cards.
* On the Explore Libraries Page, displayed channels will show at least 1 full row of cards.
* If there are channels available to fill the rows, they should be filled.

I didn't address the 'recent' section getting long here, but I think the other part of 4 should be covered by the updates here.

For other reviewers, this is ready for code review.

**Comment by pcenov** [comment]
Hi @rtibbles, looks great and works as described in my local network! I've reported separately and linked the new issues I was able to identify plus the issues from my previous comment that are still unresolved.

**Comment by rtibbles** [comment]
This now also fixes #11439 

Screenshot from 2023-10-20 12-19-08

And #11440 

Screenshot from 2023-10-20 12-03-52

**Review by marcellamaki — APPROVED** [review]
After final code review, and walk through with @rtibbles, this seems good to go!
