### PR TITLE
Fixes for IE11 and Firefox-specific bugs in 0.13.0

### LINKED ISSUE #6443: Select resources text broken on IE11
### Observed behavior
Select resources text did not display the full length on IE11 browser.

### Expected behavior

…

### User-facing consequences

…

### Errors and logs
Screen Shot 2020-01-08 at 11 59 20 AM

### Steps to reproduce

…

### Context

Tell us about your environment, including:
 * Kolibri version: 0.13.0
 * Operating system: Windows 7
 * Browser: IE11

### LINKED ISSUE #6444: Setup wizard step bug on IE11
### Observed behavior
Setup wizard automatically proceed from step 6 to 7 when I open and close the `Usage and privacy` Modal

### Expected behavior
Setup wizard must stay on step 6 when I open and close the `Usage and privacy` Modal

### User-facing consequences

…

### Errors and logs
temp

### Steps to reproduce

…

### Context

Tell us about your environment, including:
 * Kolibri version: 0.13.0
 * Operating system: Windows 7
 * Browser: IE11

### LINKED ISSUE #6455: Edit channel order display issue on IE11
### Observed behavior
Channel name padding display half when I drag and rearrange the channel list.

### Expected behavior

…

### User-facing consequences

…

### Errors and logs
temp

### Steps to reproduce

…

### Context

Tell us about your environment, including:
 * Kolibri version: 0.13.0
 * Operating system: Windows 7
 * Browser: IE11

### LINKED ISSUE #6496: On Firefox, username on CoreMenu has a blank space to its right
### Observed behavior

There's an extra blank space next to the user name (or covering it completely). Might be related to the overflow-x rule, since removing it will also remove the space.

https://github.com/learningequality/kolibri/blob/a1e53e541bfd8f0b4c55ef2d8faf2222039a6ab6/kolibri/core/assets/src/views/AppBar.vue#L221

Some screenshots:

username : 'jb'
Screen Shot 2020-01-24 at 1 46 33 PM
username : 'jonathanboiserjonathanboiser'
Screen Shot 2020-01-24 at 1 43 51 PM

### Expected behavior

No white block next to the username
### Context
 Kolibri at a1e53e541bfd8f0b4c55ef2d8faf2222039a6ab6

Also observed on kolibribeta.learningequality.org

Firefox 72

### PR DESCRIPTION
**Pull request by jonboiser**
### Summary

1. Fixes #6455 by having DragHandle render function return a single div.

Before

IMG_1040

After

IMG_1039

2. Fixes #6443 by giving the Card a min-width in the column with the "Select Resources" button

Before
Screen Shot 2020-01-30 at 3 06 53 PM

After

Screen Shot 2020-01-30 at 2 58 35 PM

3. Fixes #6496 by giving the username section an overflow-y rule

Before
Screen Shot 2020-01-24 at 1 43 51 PM

After

Screen Shot 2020-01-30 at 2 59 23 PM

4. Fixes #6444 by replacing the KModal default submit button with one that will not cause a form-submit event.

Before: See issue for video

After: After filling in form and pressing the "Close button" on the privacy modal, you will not be taken to the next step (7) in setup wizard

5. Fixes issue in IE11, where the scrollbar would be hidden, but not un-hidden after opening a modal.

### Reviewer guidance

All the issues except for Number 3 involve using IE11, so check that the issue is fixed in IE11 and doesn't any problems in other browsers (Firefox and Chromium).

Number 3 is easy to check in Firefox

### References

…

----

### Contributor Checklist

PR process:

- [x] PR has the correct target branch and milestone
- [x] PR has 'needs review' or 'work-in-progress' label
- [x] If PR is ready for review, a reviewer has been added. (Don't use 'Assignees')
- [x] If this is an important user-facing change, PR or related issue has a 'changelog' label
- [ ] If this includes an internal dependency change, a link to the diff is provided

Testing:

- [ ] Contributor has fully tested the PR manually
- [ ] If there are any front-end changes, before/after screenshots are included
- [ ] Critical user journeys are covered by Gherkin stories
- [ ] Critical and brittle code paths are covered by unit tests

### Reviewer Checklist

- Automated test coverage is satisfactory
- PR is fully functional
- PR has been tested for [accessibility regressions](http://kolibri-dev.readthedocs.io/en/develop/manual_testing.html#accessibility-a11y-testing)
- External dependency files were updated if necessary (`yarn` and `pip`)
- Documentation is updated
- Contributor is in AUTHORS.md

### CODE REVIEW

File: kolibri/plugins/device/assets/src/views/ManageContentPage/ChannelPanel/WithImportDetails.vue [hunk 1]
```diff
@@ -232,6 +232,8 @@
   .col-3 {
     display: flex;
     align-items: center;
+    justify-content: flex-end;
```
Comment (nucleogenesis) [inline kolibri/plugins/device/assets/src/views/ManageContentPage/ChannelPanel/WithImportDetails.vue:235]: FWIW I did this: https://github.com/learningequality/kolibri/pull/6507 - I found the issue and fixed it and didn't see the open issue assigned to @jonboiser by adding `flex-grow: 1` to the sibling element.

Comment (indirectlylit) [reply kolibri/plugins/device/assets/src/views/ManageContentPage/ChannelPanel/WithImportDetails.vue:235]: Just flagging for posterity that usually we don't "allow" flexbox in Kolibri, but we made a decision to leave it here because we were in a rush for 0.13 and @jonboiser found it faster to build it this way than using `KGrid`, which is inline-block-based. I've heard similar feedback that flexbox is faster and simpler to use than `KGrid` from at least two other devs.

I've been planning on trying to re-implement this responsive UI using `KGrid` as an experiment just to compare the diff.

**Review by DXCanas — APPROVED** [review]
Confirmed working via browserstack and native IE11 on Windows 10.

File: kolibri/core/assets/src/views/PrivacyInfoModal.vue [hunk 2]
```diff
@@ -48,6 +46,17 @@
...
     </section>
+    <template v-slot:actions>
+      <!--
+        Need to inject a button without type="submit" attribute
+        so it doesn't force a submit event in the SetupWizard SuperuserCredentialsForm
+      -->
+      <KButton
+        :text="coreString('closeAction')"
+        primary
+        @click="$emit('submit')"
```
Comment (DXCanas) [inline kolibri/core/assets/src/views/PrivacyInfoModal.vue:57]: Guess IE doesn't handle forms-within-forms?

**Review by DXCanas — APPROVED** [review]
Tested in all changes in IE11 on Windows 10. Confirmed working
