### PR TITLE
Android and UI responsive updates

### LINKED ISSUE #8722: Android App - Learn UI responsive design issues
## Observed behavior
When I am using the android app in a mobile phone with a smaller screen size I'm observing a number of Learn UI responsive design issues. Note that when the search filters are opened in a smaller mobile device the user has no way of closing the filter view as there's no outside area to tap on.

## Expected behavior
All pages should be optimized for mobile devices.

## Steps to reproduce the issue
1. Install the Android [build](https://buildkite.com/learningequality/kolibri-android-installer/builds/3163) on a mobile device.
2. Interact with the app.

## Screenshots

1 | 2 | 3
--- | --- | ---
 |  | 

## Usage Details
 - OS: Android 11
 - Device: Samsung Galaxy Note 10 Lite

### PR DESCRIPTION
**Pull request by marcellamaki**
## Summary

Updates to Android UI mobile responsiveness issues (pt. 1) 
Perseus renderer issues are documented/addressed in a separate issue. 

## References

| Issue | Screenshot  |
|---|---|
| Improves layout and usability of quiz renderer on mobile |  Screen Shot 2021-12-03 at 11 31 03 AM |
| Reverts toolbar spacing/stacking changes  | Screen Shot 2021-12-03 at 11 31 39 AM |
| Fixes side panel screen fit and alignment regressions  |  Screen Shot 2021-12-03 at 11 33 02 AM |
| Fixes mobile single-card view  | Screen Shot 2021-12-03 at 11 33 32 AM |
| Adds mobile breadcrumbs in topic browsing | Screen Shot 2021-12-03 at 11 34 22 AM |

## Reviewer guidance

Fixes #8722 aside from the completion modal spacing, which I cannot yet wrap my head around, and will file a follow up PR for as soon as I sort it out. 

I have done browser dev tools and browserstack testing, but since I don't have a physical android device, some of these fixes are educated guesses that _appear_ to be working. Please be patient with me @radinamatic and @pcenov if there are still some tweaks to be made 😄 

----

## Testing checklist

- [ ] Contributor has fully tested the PR manually
- [ ] If there are any front-end changes, before/after screenshots are included
- [ ] Critical user journeys are covered by Gherkin stories
- [ ] Critical and brittle code paths are covered by unit tests

## PR process

- [ ] PR has the correct target branch and milestone
- [ ] PR has 'needs review' or 'work-in-progress' label
- [ ] If PR is ready for review, a reviewer has been added. (Don't use 'Assignees')
- [ ] If this is an important user-facing change, PR or related issue has a 'changelog' label
- [ ] If this includes an internal dependency change, a link to the diff is provided

## Reviewer checklist

- Automated test coverage is satisfactory
- PR is fully functional
- PR has been tested for [accessibility regressions](http://kolibri-dev.readthedocs.io/en/develop/manual_testing.html#accessibility-a11y-testing)
- External dependency files were updated if necessary (`yarn` and `pip`)
- Documentation is updated
- Contributor is in AUTHORS.md

### CODE REVIEW

**Comment by pcenov** [comment]
Hi @marcellamaki, I had a chance to take a look at this one today and I'm happy to report that all fixes are as described above - tested on a couple of real Android devices - Samsung S7, Android 8 and Samsung Note 10 Lite, Android 11.

**Comment by radinamatic** [comment]
As @pcenov mentioned, all the cases that you list in the description are confirmed as fixed on my side too. 

I have 2 questions, let me know if it makes more sense to open separate issues:

comment | screenshot
--- | ---
When reviewing quiz results, selecting questions from the dropdown reloads the page, and pushes the selector almost outside the view each time. Is there a way to reload the page keeping the drop-down selector on the top of the page? | kviz
When using the keyword search, the search sidebar stays open (and it occupies the full screen), and the user needs to figure our they must close it to actually see the results. Can we make so the sidebar closes by default to display the results (or lack thereof) immediately? | search-modal

File: kolibri/core/assets/src/views/ExamReport/index.vue [hunk 1]
```diff
@@ -176,6 +186,7 @@
     },
     methods: {
       handleNavigateToQuestion(questionNumber) {
+        console.log(questionNumber);
```
Comment (indirectlylit) [inline kolibri/core/assets/src/views/ExamReport/index.vue]: `console.log` snuck in. It's odd that the linter didn't complain.

File: kolibri/core/assets/src/views/AttemptLogList.vue [hunk 2]
```diff
@@ -5,9 +5,21 @@
       {{ $tr('answerHistoryLabel') }}
     </h3>
 
+    <KSelect
+      v-if="isMobile"
+      class="history-select"
+      :value="selected"
+      label=""
```
Comment (indirectlylit) [inline kolibri/core/assets/src/views/AttemptLogList.vue]: since the label is blank, could possibly use [aria-labelledby](https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/ARIA_Techniques/Using_the_aria-labelledby_attribute) and point it at the `h3` above

File: kolibri/core/assets/src/views/ExamReport/index.vue (hunk 1 above)
Comment (rtibbles) [reply kolibri/core/assets/src/views/ExamReport/index.vue]: At some point in the relatively near past (~1 year) our linter seemed to stop caring about console.log - I don't know why yet, but I don't like it.

File: kolibri/core/assets/src/views/AttemptLogList.vue (hunk 2 above)
Comment (radinamatic) [reply kolibri/core/assets/src/views/AttemptLogList.vue]: [Select element must have an accessible name](https://dequeuniversity.com/rules/axe/4.2/select-name)

File: kolibri/core/assets/src/views/ExamReport/PageStatus.vue [hunk 3]
```diff
@@ -10,6 +10,17 @@
         <h1 class="title">
           <KLabeledIcon icon="person" :label="userName" />
         </h1>
+        <div v-if="windowIsSmall" class="completion-status">
```
Comment (rtibbles) [inline kolibri/core/assets/src/views/ExamReport/PageStatus.vue:13]: This component is deleted in #8807 - so I may want some help from you to resolve the inevitable merge conflict and ensure these mobile responsiveness changes are preserved.

**Review by rtibbles — APPROVED** [review]
Code checks out, comments addressed, manual QA is A-OK.

**Comment by rtibbles** [comment]
@radinamatic let's open follow up issues for the things you mentioned.

**Comment by rtibbles** [comment]
@marcellamaki opened a follow up issue specifically for the completion modal here: https://github.com/learningequality/kolibri/issues/8816
