### PR TITLE
Perseus final fixes

### LINKED ISSUE #12322: Errors in perseus renderer from possibly mismatched answer state
when answering the questions in a quiz it seems that the focus is not in the input field so that the selected value from the keyboard is not entered in the field. But even if I manually input it sometimes it just disappears when I revisit the question:

https://github.com/learningequality/kolibri/assets/79847249/55dc7acf-d412-4bfd-accf-34de915cf470

Here's the error in the console:
[browser-console-error.log](https://github.com/user-attachments/files/15903277/browser-console-error.log)

_Originally posted by @pcenov in https://github.com/learningequality/kolibri/issues/9759#issuecomment-2179033123_

### LINKED ISSUE #12375: On first load, Perseus renderer does not restore answer state
When I go to Coach > Reports > Lesson > Difficult questions I am not seeing the incorrect answers of the learner:

https://github.com/learningequality/kolibri/assets/79847249/1bef017a-4f36-4fc5-979a-dc8930475e0e

If that's not caused by the changes made here, I can file a follow-up issue.

_Originally posted by @pcenov in https://github.com/learningequality/kolibri/issues/12372#issuecomment-2194926171_

### PR DESCRIPTION
**Pull request by rtibbles**
## Summary
* Does flyby fix of core logging module to allow multiple arguments to be sent to each logging method
* Prevents restoring of slightly mangled state by santizing question keys before restoration
* Fixes previously unnoticed issue whereby an initial refresh of the page would not restore the answer on first page load

## References
Fixes #12322
Fixes #12375

## Reviewer guidance
Use the database from referenced issue and see that the quiz responses are properly restored for all questions with no errors logged in the console.
While on the quiz page, refresh the page, and see that the answer gets properly filled in on page refresh.

----

## Testing checklist

- [ ] Contributor has fully tested the PR manually
- [ ] If there are any front-end changes, before/after screenshots are included
- [ ] Critical user journeys are covered by Gherkin stories
- [ ] Critical and brittle code paths are covered by unit tests

## PR process

- [ ] PR has the correct target branch and milestone
- [ ] PR has 'needs review' or 'work-in-progress' label
- [ ] If PR is ready for review, a reviewer has been added. (Don't use 'Assignees')
- [ ] If this is an important user-facing change, PR or related issue has a 'changelog' label
- [ ] If this includes an internal dependency change, a link to the diff is provided

## Reviewer checklist

- Automated test coverage is satisfactory
- PR is fully functional
- PR has been tested for [accessibility regressions](http://kolibri-dev.readthedocs.io/en/develop/manual_testing.html#accessibility-a11y-testing)
- External dependency files were updated if necessary (`yarn` and `pip`)
- Documentation is updated
- Contributor is in AUTHORS.md

### CODE REVIEW

File: kolibri/plugins/perseus_viewer/assets/src/views/PerseusRendererIndex.vue [hunk 1]
```diff
@@ -537,8 +537,20 @@
...
+          // it seems it is possible for us to have a serialized state with keys
+          // that do not correspond to any widgets. We need to sanitize the state
+          // before restoring it.
+          const sanitizedQuestions = {};
+          for (const key of widgetIds) {
+            if (answerState.question[key]) {
+              sanitizedQuestions[key] = answerState.question[key];
+            }
+          }
+          answerState.question = sanitizedQuestions;
```
Comment (marcellamaki) [inline kolibri/plugins/perseus_viewer/assets/src/views/PerseusRendererIndex.vue]: I'm not sure if this is a nit or confusion - why is `question` (singular) now set to `sanitizedQuestions` (object, and presumably plural). I get at a high level what's happening here - clear out anything that's not a match between the answerState questions and the widgetIds. But I don't understand really what this replacement object is. (Maybe that's a bit besides the point)

File: kolibri/core/assets/src/logging.js [hunk 2]
```diff
@@ -14,8 +14,8 @@ class Logger {
       const name = methodName.toLowerCase();
       const logFunction = this.logger[name];
       if (logFunction) {
-        this[name] = param => {
-          return this.logger[name](param);
+        this[name] = (...params) => {
```
Comment (marcellamaki) [inline kolibri/core/assets/src/logging.js:17]: This being a flyby, does that mean it's somehow connected to the perseus stuff (or more apparent with it?), or unrelated?

**Review by marcellamaki — COMMENTED** [review]
I have a couple of comprehension questions but no real concerns, although I will leave manual QA to Peter :)

File: kolibri/plugins/perseus_viewer/assets/src/views/PerseusRendererIndex.vue (hunk 1 above)
Comment (rtibbles) [reply kolibri/plugins/perseus_viewer/assets/src/views/PerseusRendererIndex.vue]: I can update it to 'santizedQuestion' to avoid the slight confusion here, although I think the fault lies with Perseus for calling this 'question' when it can indeed be multiple prompts at once.

File: kolibri/core/assets/src/logging.js (hunk 2 above)
Comment (rtibbles) [reply kolibri/core/assets/src/logging.js:17]: I pass our logging library to Perseus so that we log errors consistently from it - however, for some the errors I was most interested in here, it was passing multiple arguments, so I needed to make this update to debug more effectively.

**Comment by pcenov** [comment]
Hi @rtibbles, while fully regression testing I noticed just the following onscreen keyboard related issues:

1. When I use several hints the keyboard gets displayed at the bottom of the screen which results in poor UX as the user has to scroll down and up. This is most noticeable in the Android app:

https://github.com/learningequality/kolibri/assets/79847249/9e25231a-a2cd-45a4-8736-8011b3f2ac26

2. When viewing the lesson/report in less than about 800px, then the keyboard pops up when I move to the next question, or want to see the correct answer:

https://github.com/learningequality/kolibri/assets/79847249/1bfc9f98-c79c-44c0-b124-8dc4edf5889d

Also I am not sure whether the issue described in https://github.com/learningequality/kolibri/issues/12322 sis fully fixed as I would expect that if the keyboard is present on screen then the input focus should be within the input field, which is still not the case:


https://github.com/learningequality/kolibri/assets/79847249/268b9ff5-7486-4d1e-82c7-0cc7b65384b6

[LogsAndDB.zip](https://github.com/user-attachments/files/16032328/LogsAndDB.zip)

**Comment by rtibbles** [comment]
More troubling is you are still seeing the console errors that my fix was meant to prevent, I still haven't replicated these without your database directly, so I feel like I am missing something in the steps to replication here.

**Comment by pcenov** [comment]
Hi @rtibbles - let me knows which scenario you can't replicate and I will try to add additional steps.

**Comment by rtibbles** [comment]
Hi @pcenov - the third video, I see the errors still occurring in the console as you switch between items, that's the scenario I am unable to replicate.

**Comment by pcenov** [comment]
Hi @rtibbles my suspicion is that this is happening because in this quiz we have a mixture of questions requiring user input and a multiple select question.  I was able to replicate this with the exact same quiz so here's the DB and logs in case you can make use of it:
[LogsAndDB.zip](https://github.com/user-attachments/files/16054878/LogsAndDB.zip)
I'll test it again tomorrow with other quizzes.

**Comment by rtibbles** [comment]
Hi @pcenov, I was finally able to replicate the errors those last errors you were seeing, and I think I have resolved them all now.

To fix 1) I have changed the positioning of the keypad, so that it will now overlay any question content, rather than being pushed down. There didn't seem to be a happy medium between showing the content and having the keypad overlay, so I have gone with this.

For 2 - the keypad should no longer display on reports at all.

For 3 - the keypad should now dismiss when changing questions (I noticed it was persisting even when the next question did not have a numeric input).

**Comment by pcenov** [comment]
Hi @rtibbles,

Unfortunately 1 is still not fixed - the keyboard is still showing throughout Coach > Reports and Coach > Lesson > Resources:

https://github.com/learningequality/kolibri/assets/79847249/ff01d68a-e2e6-4570-b69b-764f37a88154

Also perhaps and if possible we should have the keyboard always displayed at the bottom in the way you've currently implemented it when the exercise is part of a Lesson or viewed in the Library. Otherwise it's pretty bad when completing an assigned quiz, as it almost always covers the exercise:

https://github.com/learningequality/kolibri/assets/79847249/2a987424-6e5a-4e83-98d7-7680994a4737

Here's how it looks in the Library page:

https://github.com/learningequality/kolibri/assets/79847249/831ac005-25eb-438c-a575-a7337089eaa2

Also it should be possible to scroll the contents of the page while the keyboard is displayed.

[Logs.zip](https://github.com/user-attachments/files/16067615/Logs.zip)

**Comment by rtibbles** [comment]
Hi @pcenov, I walked this through with @marcellamaki, and the most robust solution we could come up with is to default to the built in behaviour of perseus, for the keypad to attach to the bottom of the screen. I have updated the positioning of the element, so that it should always overlay any other element on the screen.

This does mean that while the keypad is open, the exercise bar and quiz navigation bar are obscured, but it was the only way to make it behave consistently across all contexts.

The display of the keypad when viewing reports should now also be fixed.

**Review by pcenov — APPROVED** [review]
Hi @rtibbles - I confirm that now the keypad is positioned at the bottom of the page as specified in your comment and that the user has to manually close it in order to click any of the buttons in the navigation bar.
The display of the keypad when viewing reports is also fixed.

**Review by marcellamaki — APPROVED** [review]
The last couple of commits look good as code changes, and manual QA approves ✅
