### PR TITLE
Remove edit channel order in case of single channel

### LINKED ISSUE #6558: disable 'edit channel order' when there's only one channel
### Observed behavior

| main page | reorder page |
|--|--|
| image | |

### Expected behavior

option to reorder should be disabled

### User-facing consequences

slightly strange UX for single-channel view

### Steps to reproduce

Have one channel and reorder

### Context

0.13.1 beta 2

### PR DESCRIPTION
**Pull request by Tlazypanda**
### Summary
Edit channel order option is not visible in the dropdown incase there is a single channel.Fixes #6558 

## GIF :-
ezgif com-video-to-gif

### Contributor Checklist
PR process:

- [x] PR has the correct target branch and milestone
- [x] PR has 'needs review' or 'work-in-progress' label
- [x] If PR is ready for review, a reviewer has been added. (Don't use 'Assignees')
- [ ] If this is an important user-facing change, PR or related issue has a 'changelog' label
- [ ] If this includes an internal dependency change, a link to the diff is provided

Testing:

- [x] Contributor has fully tested the PR manually
- [x] If there are any front-end changes, before/after screenshots are included
- [ ] Critical user journeys are covered by Gherkin stories
- [ ] Critical and brittle code paths are covered by unit tests

### Reviewer Checklist

- Automated test coverage is satisfactory
- PR is fully functional
- PR has been tested for [accessibility regressions](http://kolibri-dev.readthedocs.io/en/develop/manual_testing.html#accessibility-a11y-testing)
- External dependency files were updated if necessary (`yarn` and `pip`)
- Documentation is updated
- Contributor is in AUTHORS.md

### CODE REVIEW

**Comment by Tlazypanda** [comment]
@kollivier @radinamatic @divad12 kindly review Thanks :v:

**Comment by Tlazypanda** [comment]
@radinamatic @kollivier also is there any slack/gitter/zulip channel for contributors to join and discuss?

**Comment by radinamatic** [comment]
Looking good for me when checked out locally!

one channel | two channels
------------ | -------------
Selection_368 | Selection_369

One comment about the **Contributor checklist** items: do not just check them in bulk, here for example the labels and milestone are still missing :wink: 

I'm going to approve, but @kollivier @indirectlylit may have other code-related comments to add.

**Review by radinamatic — APPROVED** [review]
LGTM! :+1:

File: kolibri/plugins/device/assets/src/views/ManageContentPage/index.vue [hunk 1]
```diff
@@ -136,11 +136,18 @@
...
+            { label: this.$tr('exportChannels'), value: 'EXPORT' },
+            { label: this.$tr('deleteChannels'), value: 'DELETE' },
+            { label: this.$tr('editChannelOrder'), value: 'REARRANGE' },
+          ];
+        } else {
+          return [
+            { label: this.$tr('exportChannels'), value: 'EXPORT' },
+            { label: this.$tr('deleteChannels'), value: 'DELETE' },
+          ];
+        }
```
Comment (indirectlylit) [inline kolibri/plugins/device/assets/src/views/ManageContentPage/index.vue]: A small nuance is that the expected behavior described in #6558 was "option to reorder should be disabled". (We generally prefer to disable rather than hide UI elements to make the experience more predictable.)

This is not tested, but you should be able to do something like:

```js
        return [
          { label: this.$tr('exportChannels'), value: 'EXPORT' },
          { label: this.$tr('deleteChannels'), value: 'DELETE' },
          {
            label: this.$tr('editChannelOrder'),
            value: 'REARRANGE',
            disabled: this.installedChannelsWithResources.length === 1,
          },
        ];
```

(looks like the button is hidden entirely for zero channels, which perhaps goes against the guidance above but that may have been an intentional decision)

**Review by indirectlylit — DISMISSED** [review]
thanks for the PR!

Let's disable rather than hide the option though. Also, feel free to add yourself to the [authors file](https://github.com/learningequality/kolibri/blob/develop/AUTHORS.md)

**Comment by indirectlylit** [comment]
@Tlazypanda 

> is there any slack/gitter/zulip channel for contributors to join and discuss?

We have an IRC-slack bridge to our developer Slack room here: https://webchat.freenode.net/#kolibri

Alternatively, feel free to email me your info to `devon` at our domain name and I'll invite you directly to the Slack channel.

Thanks for the contributions!

**Comment by Tlazypanda** [comment]
@indirectlylit have made the changes.Can you kindly review again? Thanks 😊

**Review by indirectlylit — APPROVED** [review]
tested and looks good!

image
