### PR TITLE
Attempting to view exercise Attempt Log as anonymous user crashes

### LINKED ISSUE #3054: Attempting to view Exercise Attempt Log as anonymous user crashes
### Observed behavior

This link goes to an Exercise Attempt Log report

http://localhost:8000/coach/#/df6308209356328f726a09aa9bd323b7/learners/d9a4adf2231fc91938e63aa5505eff92/5d132ba360b54b2ba9df169ffaa43ccb/item/8a2b54ca68734c088c6937eb98b7edf5/6/0

But if the user is not logged in, this page simply errors out and you see the flapping bird loading screen.

Somewhere in the loading page logic, there is a request for a Facility User, but it returns with a 403, causing the page load to fail.

Going to other higher-level report pages like the

http://localhost:8000/coach/#/df6308209356328f726a09aa9bd323b7/learners
http://localhost:8000/coach/#/df6308209356328f726a09aa9bd323b7/learners/d9a4adf2231fc91938e63aa5505eff92

Does show generic "red error" box and explain that user should log in.

### Expected behavior

A page saying like "You must be logged in as a Coach," for the Exercise Attempt Log page.

### User-facing consequences

An un-handled error.

### Steps to reproduce

1. In the Coach page, click "Learners" to see reports for all Learners
1. Click through the UI and get to an Exercise progress report.
1. Save the URL
1. Log out
1. Visit the URL as an anonymous user.

### PR DESCRIPTION
**Pull request by mrpau-richard**
### Summary
I use the `handleApiError ` to catch api error at the learner page.

### References
This fixes #3054 

### Contributor Checklist

- [x] Contributor has fully tested the PR manually
- [x] PR has the correct target branch and milestone
- [x] PR has 'needs review' or 'work-in-progress' label
- [ ] If PR is ready for review, a reviewer has been added. (Don't use 'Assignees')
- [ ] If there are any front-end changes, before/after screenshots are included
- [ ] If this is an important user-facing change, PR or related issue has a 'changelog' label

### Reviewer Checklist

- [ ] Automated test coverage is satisfactory
- [ ] Reviewer has fully tested the PR manually
- [ ] PR has been tested for [accessibility regressions](http://kolibri-dev.readthedocs.io/en/develop/manual_testing.html#accessibility-a11y-testing)
- [ ] External dependencies files were updated (`yarn` and `pip`)
- [ ] Documentation is updated
- [ ] Link to diff of internal dependency change is included
- [ ] CHANGELOG.rst is updated for high-level changes
- [ ] Contributor is in AUTHORS.rst

### CODE REVIEW

**Comment by jonboiser** [comment]
@mrpau-richard I think using `handleApiError` and showing that red error box is less than ideal. In #3054 I recommended using the `auth-message` component to give the user better information as to why the page is not available (e.g. they're not logged in as a Coach).

**Comment by mrpau-richard** [comment]
@jonboiser I use `handleError` with an argument empty string to all coach under routes, so it will not display the red error box.

**Comment by jonboiser** [comment]
i'm not sure if it's the best approach to hide all errors, because the anonymous user is a single case (400 error code), but there might be other errors that the user might need to read.

**Comment by mrpau-richard** [comment]
@jonboiser I filter those status codes errors that related in the authentication issue to hide it and just display the `auth-message`.

File: kolibri/core/assets/src/state/actions.js [hunk 1]
```diff
@@ -162,7 +162,10 @@ function _channelListState(data) {
  */
 
 function handleError(store, errorString) {
-  store.dispatch('CORE_SET_ERROR', errorString);
+  const authErrorCodes = [401, 403, 407];
+  if (errorCodes.indexOf(errorString.status.code) < 0) {
+    store.dispatch('CORE_SET_ERROR', errorString);
+  }
```
Comment (jonboiser) [inline kolibri/core/assets/src/state/actions.js]: putting this logic here might have some unintended consequences for other parts of the app, since it's used in a lot of other places. do you think you can put this only in the spaces needed to fix the original issue (e.g. coach tools)?

**Comment by mrpau-richard** [comment]
@jonboiser I included the `404 not found error` at the filter list. This is to prevent the page crashes if the user data deleted or not available.

File: kolibri/core/assets/src/state/actions.js [hunk 2]
```diff
@@ -174,6 +171,15 @@ function handleApiError(store, errorObject) {
   handleError(store, JSON.stringify(errorObject, null, '\t'));
 }
 
+function handleCoachPageError(store, errorObject) {
```
Comment (jonboiser) [inline kolibri/core/assets/src/state/actions.js]: Could you move this to the coach plugin, since it probably won't be used in the rest of the app.

You could use `Array.prototype.includes` to simplify the condition to be

```diff
-authErrorCodes.indexOf(errorObject.status.code) < 0
+authErrorCodes.includes(errorObject.status.code)
```

**Comment by mrpau-richard** [comment]
@jonboiser I removed the `404 if statement` at the `showExamReportPage`, because the `handleCoachPageError` already handle the 404 status code.

File: kolibri/plugins/coach/assets/src/state/actions/exam.js [hunk 3]
```diff
@@ -531,12 +531,7 @@ export function showExamReportPage(store, classId, examId) {
       );
     },
     error => {
-      if (error.status.code === 404) {
```
Comment (jonboiser) [inline kolibri/plugins/coach/assets/src/state/actions/exam.js]: Don't remove this logic. The idea is if a user goes to a URL like http://localhost:8000/coach/#/32d137eae73e5e4c59b4f3f90b9acdf9/exams/notarealexam123123, then the user will be redirected back to the Exams List Page.

**Comment by mrpau-richard** [comment]
I already restored the 404 if statement showExamReportPage @jonboiser

**Comment by indirectlylit** [comment]
remember to set the milestone!
