### PR TITLE
Fixes filters not displayed  on the  imported exercises from QA channel

### LINKED ISSUE #12890: 0.18 - Library - The filters are not displayed if I have imported exercises
## Observed behavior

When I import only the exercises from the QA Channel (nakav-mafak) and go to the Library page then the filter panel is not displayed at all. This is happening in all supported browsers.

https://github.com/user-attachments/assets/f4848053-14e6-4b67-9b0c-af3668fc2fd9

## Expected behavior

Fully functional filters.

## Steps to reproduce the issue

1. Install [Kolibri 0.18.0 alpha0](https://github.com/learningequality/kolibri/releases/tag/v0.18.0-alpha0)
2. Import only the exercises from the QA channel
3. Go to the Library page

## Logs

[logs-db.zip](https://github.com/user-attachments/files/17937326/logs-db.zip)

## Usage Details
[Kolibri 0.18.0 alpha0](https://github.com/learningequality/kolibri/releases/tag/v0.18.0-alpha0)
Ubuntu 22  - Chrome

### PR DESCRIPTION
**Pull request by AllanOXDi**
## Summary
This PR  fixes filters  not displaying if exercise  is imported 

### Before 

https://github.com/user-attachments/assets/deed4ec9-6a4c-46a7-b1ad-f3576aa55b2d

#### After 

https://github.com/user-attachments/assets/368958ff-0a51-4576-ba69-d8d3b053ca95

## References

closes #12890

## Reviewer guidance

Import  the exercises from the QA Channel (nakav-mafak) and go to the Library page then the filter panel.

### CODE REVIEW

**Review by pcenov — APPROVED** [review]
Thanks @AllanOXDi - I confirm that the filters are working correctly now!

File: packages/kolibri-common/components/SearchFiltersPanel/index.vue [hunk 1]
```diff
@@ -21,94 +21,93 @@
       v-if="windowIsLarge || !currentCategory"
       :class="windowIsLarge ? '' : 'drawer-panel'"
     >
-      <div v-if="Object.keys(availableLibraryCategories).length">
```
Comment (rtibbles) [inline packages/kolibri-common/components/SearchFiltersPanel/index.vue:24]: It seems this check is not being persisted anywhere.

If you look at the original PR where this was moved, it originally was used to wrap the section containing the categories, so that if no categories are in the local library, the section does not get displayed at all.

File: packages/kolibri-common/components/SearchFiltersPanel/index.vue [hunk 2]
```diff
@@ -21,94 +21,93 @@
...
+          {{ $tr('keywords') }}
+        </h2>
+        <SearchBox
+          key="channel-search"
+          ref="searchBox"
+          :placeholder="coreString('findSomethingToLearn')"
+          :value="value.keywords || ''"
+          @change="val => $emit('input', { ...value, keywords: val })"
+        />
+        <h2 class="section title">
```
Comment (rtibbles) [inline packages/kolibri-common/components/SearchFiltersPanel/index.vue]: This `<h2>` and the next `<div>` should be wrapped in another div that is conditionalized using `v-if="Object.keys(availableLibraryCategories).length"`.

**Review by rtibbles — CHANGES_REQUESTED** [review]
Just one minor thing to completely fix the regression.

File: packages/kolibri-common/components/SearchFiltersPanel/index.vue (hunk 2 above)
Comment (AllanOXDi) [reply packages/kolibri-common/components/SearchFiltersPanel/index.vue]: got it

Comment (AllanOXDi) [reply packages/kolibri-common/components/SearchFiltersPanel/index.vue]: I think I was wrong

Comment (rtibbles) [reply packages/kolibri-common/components/SearchFiltersPanel/index.vue]: Break what? The issue was that the condition was being applied to the entire filters panel previously, so when you were importing resources that had no categories set on them, that was causing the reported issue (that they happened to be exercises was a red herring, I think). Restoring the condition to its correct place _just_ wrapping the categories title and div will restore the previous behaviour.

Comment (AllanOXDi) [reply packages/kolibri-common/components/SearchFiltersPanel/index.vue]: No- I was wrapping it wrongly . It's all good now.

File: packages/kolibri-common/components/SearchFiltersPanel/index.vue [hunk 3]
```diff
@@ -61,54 +61,55 @@
               @click="handleCategory(key)"
             />
           </div>
+        </div>
+        <div
```
Comment (rtibbles) [inline packages/kolibri-common/components/SearchFiltersPanel/index.vue]: Ah, sorry - this div needs to be inside too, as we don't need to show the `uncategorized` button when there are no categories, because then, by definition, everything is uncategorized!

Comment (AllanOXDi) [reply packages/kolibri-common/components/SearchFiltersPanel/index.vue]: Fixed!

**Review by rtibbles — APPROVED** [review]
Working as expected now!
