### PR TITLE
Deviceowner creation fixes and updates

### LINKED ISSUE #1488: Unable to create username with "." in the name on device owner page.
## Summary

When creating an account on the device owner page with a username containing a ".", the system is unresponsive.

## System information

*Please specify the Kolibri version you were using and your operating system!*

 - Version: 0.3.1b2-6
 - Operating system: Windows?
 - Browser: [Can update as I have more information next week]

## Traceback or relevant snippet from server.log or browser console

```
INSERT TRACEBACK, LOG MESSAGES ETC. HERE
```

## How to reproduce

Create a new device account with a username containing a "." (period)

## Screenshots

This issue took place during the UNICEF training in Greece. I don't have screenshots at this time but can work to reproduce if useful.

## Real-life consequences (anything community should be aware of, for instance how it affects your deployment)

It would be helpful to have a meaningful warning or provide guidance on what characters cannot be included in a username.

### PR DESCRIPTION
**Pull request by DXCanas**
## Summary

A facelift with beefier validation

## Issues addressed
fixes #1488 

## Screenshots (if appropriate)

quickdemoforsetup

### CODE REVIEW

File: kolibri/plugins/setup_wizard/assets/src/views/index.vue [hunk 1]
```diff
@@ -1,33 +1,74 @@
...
+        <section class="setup-owner">
+
+          <header>
+            <h2 class="title">{{ $tr('deviceOwnerSectionHeader') }}</h2>
+            <p class="description">{{ $tr('deviceOwnerDescription') }}</p>
+          </header>
+
+
+          <core-textbox
+          @focus="firstUsernameFieldVisit || visitUsername()"
```
Comment (christianmemije) [inline kolibri/plugins/setup_wizard/assets/src/views/index.vue]: Indentation.

File: kolibri/plugins/setup_wizard/assets/src/views/index.vue [hunk 2]
```diff
@@ -1,33 +1,74 @@
...
+          :invalid="!!passwordError"
+          type="password"
+          v-model="passwordConfirm"
+          :required="true"
+          :label="$tr('confirmPasswordInputLabel')"/>
+
+        </section>
+        <section class="setup-facility">
+
+          <header>
```
Comment (christianmemije) [inline kolibri/plugins/setup_wizard/assets/src/views/index.vue:57]: That markup. :raised_hands:

File: kolibri/plugins/setup_wizard/assets/src/views/index.vue [hunk 3]
```diff
@@ -42,33 +83,82 @@
...
+      'ui-alert': require('keen-ui/src/UiAlert'),
+    },
+    computed: {
+      firstUsernameFieldVisit() {
+        return this.usernameError === null;
+      },
+      usernameFieldPopulated() {
+        return !!this.username;
+      },
+      usernameValidityCheck() {
```
Comment (christianmemije) [inline kolibri/plugins/setup_wizard/assets/src/views/index.vue:136]: The username has to be alphanum and max 30 chars. https://github.com/learningequality/kolibri/blob/develop/kolibri/auth/models.py#L190

I added this check to the user-create-modal.
https://github.com/learningequality/kolibri/blob/develop/kolibri/plugins/management/assets/src/views/user-page/user-create-modal.vue#L124

Comment (christianmemije) [reply kolibri/plugins/setup_wizard/assets/src/views/index.vue:136]: Also, Facility name has a max length of 100 chars
https://github.com/learningequality/kolibri/blob/086038a5e7529c8c402593cd9d1a8322e1385971/kolibri/auth/models.py#L622

File: kolibri/plugins/setup_wizard/assets/src/views/index.vue [hunk 4]
```diff
@@ -1,33 +1,74 @@
...
-        <br>
-        <br>
-        <div class="btn-wrapper">
-          <button class="create-btn" type="button" @click="createBoth">{{ $tr('getStarted') }}</button>
-        </div>
-      </div>
-      <br>
+
+
+      <form @submit.prevent="submitSetupForm" novalidate class="container">
```
Comment (DXCanas) [inline kolibri/plugins/setup_wizard/assets/src/views/index.vue:8]: Added `novalidate` so that native error styling wouldn't interfere with the global error message I've set up for empty fields. I'm iffy on this, so I'll revert that commit if you all think it's a bad idea.

File: kolibri/plugins/setup_wizard/assets/src/views/index.vue [hunk 5]
```diff
@@ -42,33 +83,82 @@
...
+        return this.passwordFieldsMatch &&
+          this.usernameValidityCheck &&
+          this.allFieldsPopulated;
+      },
+    },
     methods: {
-      createBoth() {
-        if (this.username && this.password && this.facility
-          && this.password === this.confirm_password) {
+      submitSetupForm() {
```
Comment (christianmemije) [inline kolibri/plugins/setup_wizard/assets/src/views/index.vue:166]: But `createBoth` was such a great function name... jk

File: kolibri/plugins/setup_wizard/assets/src/views/index.vue (hunk 1 above)
Comment (DXCanas) [reply kolibri/plugins/setup_wizard/assets/src/views/index.vue]: The autoindent in atom is killing me

File: kolibri/plugins/setup_wizard/assets/src/views/index.vue (hunk 3 above)
Comment (DXCanas) [reply kolibri/plugins/setup_wizard/assets/src/views/index.vue:136]: Thanks. Will get on this tomorrow.

**Comment by christianmemije** [comment]
Improved validation

127 0 0 1-8000-setup_wizard-

File: kolibri/plugins/setup_wizard/assets/src/views/index.vue (hunk 3 above)
Comment (rtibbles) [reply kolibri/plugins/setup_wizard/assets/src/views/index.vue:136]: Hrm, the backend validation message is actually inaccurate, as the regex here will allow underscore, for example. No need to fix now, but it is slightly misleading to the user (but in a restrictive way, so it won't make them enter an illegal username).
