### PR TITLE
Ensure quiz report visibility is updated correctly after a quiz has been closed

### LINKED ISSUE #13111: Quiz report unavailable when learner checks clicks assigned quiz card right after quiz has been closed
## Observed behavior

When a quiz is assigned to a learner, if the learner is viewing the assigned quizzes immediately after a quiz has been closed, clicking the quiz card displays the report as if it can be previewed, but the learner only sees the modal that says the quiz report will be available soon. Navigating away to another plugin and returning resolves the problem. 

https://github.com/user-attachments/assets/57109369-ba9a-4769-913a-afa41906f098

Also, in some a cases, there is a brief flash of the Quiz report coming soon modal, before the report actually loads.

## Expected behavior

When the learner is viewing the assigned quizzes immediately after a quiz has been closed, clicking the quiz card should displays the quiz report.

## Steps to reproduce

1. Assign a quiz to a learner with the quiz report visibility selection “After coach ends the quiz”.
2. In a separate browser, signed into the learner account, complete the quiz, then leave the homepage with the view of the assigned quizzes displayed open.
3. In the browser that the coach is signed into, close the quiz.
4. Once the learner’s quiz card updates to reflect that the quiz report can be viewed, click the quiz card. The learner will see the modal indicating that the quiz report will be available soon.

## Context
* Kolibri version: 0.18
* Operating system: all
* Browser: all

### PR DESCRIPTION
**Pull request by LianaHarris360**
## Summary

This pull request adds `UseLearnerResources` to `LearnExamReportViewer` to retrieve the most up-to-date active quiz fields so that when the quiz card updates on the homepage to reflect an available report, the learner can view the quiz report as intended.

This pull request also ensures that the modal informing the user that the quiz report is unavailable does not appear prematurely while the quiz report is loading.

Before:

https://github.com/user-attachments/assets/31cb5892-367b-4b85-ad18-1d5c230a87b7

After:

https://github.com/user-attachments/assets/7c760ed5-4790-4699-8582-56093a493992

## References

Fixes #13111 

## Reviewer guidance

1. Assign a quiz to a learner with the quiz report visibility selection “After coach ends the quiz”.
2. In a separate browser, signed into the learner account, complete the quiz, then leave the homepage with the view of the assigned quizzes displayed open.
3. In the browser that the coach is signed into, close the quiz.
4. Once the learner’s quiz card updates to reflect that the quiz report can be viewed, click the quiz card. The quiz report should be shown.

### CODE REVIEW

**Comment by LianaHarris360** [comment]
Tagging for QA review @radinamatic @pcenov

File: kolibri/plugins/learn/assets/src/views/LearnExamReportViewer.vue [hunk 1]
```diff
@@ -96,8 +98,12 @@
         };
       },
       reportVisible() {
+        const quiz = this.activeClassesQuizzes.find(q => q.id === this.exam.id) || this.exam;
```
Comment (rtibbles) [inline kolibri/plugins/learn/assets/src/views/LearnExamReportViewer.vue:101]: This feels a little hacky - because of the semi-dependency on the maybe loaded, maybe not activeClassesQuizzes (which is only initialized if you have been on the home page).

But it also works in spite of my best attempt to break it - so it will do for now, until we can better align the loading of `this.exam` to be better aligned with what's in `this.activeClassesQuizzes`.

**Review by rtibbles — COMMENTED** [review]
I think it would be good to write up a technical debt follow up issue for better consolidating the data fetching here - but the current solution works!

We also chatted on Slack about an issue with the learner quiz endpoint data not defaulting `null` to `true` for the visibility after submission.
Screenshot from 2025-03-06 12-37-21

File: kolibri/plugins/learn/assets/src/views/LearnExamReportViewer.vue (hunk 1 above)
Comment (LianaHarris360) [reply kolibri/plugins/learn/assets/src/views/LearnExamReportViewer.vue:101]: I agree this is a bit hacky. Since the exam is cached and loaded from the state, initially I tried to remove this caching, but the exam's archive field still would not update to true when it should have. I could open an issue for the loading to be refactored so that it hopefully doesn't get lost!

Comment (rtibbles) [reply kolibri/plugins/learn/assets/src/views/LearnExamReportViewer.vue:101]: Please do! Can add it as a sub-issue of https://github.com/learningequality/kolibri/issues/11722 as the refactor should probably involve removing the use of vuex and shifting to using a composable!

**Review by rtibbles — COMMENTED** [review]
Code changes look good to me. Just needs QA approval.

**Review by pcenov — APPROVED** [review]
Thanks @LianaHarris360 - works fine now.
