### PR TITLE
Clear failed facility import tasks when restarting Setup Wizard

### LINKED ISSUE #7693: Setup Wizard blocks facility-import setup if first attempt fails
### Observed behavior

Here are failure cases where the Setup Wizard doesn't properly clean up the Task queue, which leads to some bugs.

**Scenario 1: Import fails, then press "Start Over"**

1. Went to "Import facility" in Setup Wizard
1. Used kolibri-beta as the peer server and selected "Hack Session School". The import failed with a 500 error (not sure why)
1. I press "Start Over", which takes me to the very beginning of the Setup Wizard
1. I then go to the "Import facility" section again and attempt to import "ZukVillage".
1. In the console, the facility import succeeds, but the UI acts as if it failed because it is still looking at the failed task in the queue. This means, the user cannot continue on with the rest of the setup wizard.

Tasks queue with two tasks
image

**Scenario 2: Import fails, then user shuts off server**

^^^ This also will happen if the user just turns off the server after the first failure.

### Expected behavior

1. When the user clicks "Start over", the failed tasks is removed from the queue. 
1. When the user shuts down the server and restarts it, the failed tasks are removed from the queue

### User-facing consequences

The user will need to do a workaround, where they will have to delete the `job_storage.sqlite3` file from their home directory before they can try to import another facility.

### Errors and logs

…

### Steps to reproduce

…

### Context

…

### PR DESCRIPTION
**Pull request by jonboiser**
### Summary

1. In `LoadingTaskPage`, I add a call to the `cleartasks` endpoint when the "Start Over" button is clicked. This should ensure that the tasks queue is cleared when the user is returned to the beginning of the setup wizard.
2. In `kolibri/plugins/setup_wizard/assets/src/app.js`, I make the same call to the `cleartasks` endpoint when the user (re)starts the Kolibri server. This should ensure that the tasks queue is cleared if the user stops the server with Ctrl-C _before_ clicking "Start Over".
3. Adds tests for the core behavior in `LoadingTaskPage`
4. Fixes a bug where the polling would never be turned off after leaving the `LoadingTaskPage`
5. Adds a missing `KButtonGroup` wrapper

### Reviewer guidance

[See this video](https://drive.google.com/file/d/1egsr_ZGXXENkATZ3AJAfXPw2J-Qkiu2A/view?usp=sharing) on how to use the setup wizard. Try to see if you can cause a problem where the setup wizard gets stuck like in #7693. (Direct message me for credentials you can use at timestamp `0:33` of the video)

In the video, I import facilities from kolibri-beta.learningequality.org. The three current facilities have these useful properties:

* Demo Facility has _a lot_ of data, so you can cancel an import task and start over
* ZukVillage is small and, at the moment, facility import tasks always succed
* Hack Session School _always_ fails to import in my testing.

To get to the Setup Wizard, your server must be "unprovisioned" (otherwise you will just see the Login Page when you start the server). 

The easiest way to "deprovision" a device is to delete (or move) your existing `KOLIBRI_HOME` folder to another location, then run `kolibri manage migrate`, then run the devserver.  

### References

Fixes #7693 

----

### Contributor Checklist

PR process:

- [x] PR has the correct target branch and milestone
- [X] PR has 'needs review' or 'work-in-progress' label
- [ x If PR is ready for review, a reviewer has been added. (Don't use 'Assignees')
- [ ] If this is an important user-facing change, PR or related issue has a 'changelog' label
- [ ] If this includes an internal dependency change, a link to the diff is provided

Testing:

- [ ] Contributor has fully tested the PR manually
- [ ] If there are any front-end changes, before/after screenshots are included
- [ ] Critical user journeys are covered by Gherkin stories
- [ ] Critical and brittle code paths are covered by unit tests

### Reviewer Checklist

- Automated test coverage is satisfactory
- PR is fully functional
- PR has been tested for [accessibility regressions](http://kolibri-dev.readthedocs.io/en/develop/manual_testing.html#accessibility-a11y-testing)
- External dependency files were updated if necessary (`yarn` and `pip`)
- Documentation is updated
- Contributor is in AUTHORS.md

### CODE REVIEW

**Comment by pcenov** [comment]
Hi @jonboiser, 
We tested this together with @radinamatic by importing facilities from kolibri-beta.learningequality.org and we can confirm that when the user clicks "Start over", the failed tasks are removed from the queue and that when the user shuts down the server and restarts it, the failed tasks are removed from the queue. 
We were not able to get into a scenario where the setup wizard gets stuck like in #7693.

For referrence I’m attaching screenshots and logs of the errors we observed when the import fails.

LEDev21 (start)  Running  - Oracle VM VirtualBox_038
LEDev21 (start)  Running  - Oracle VM VirtualBox_039
LEDev21 (start)  Running  - Oracle VM VirtualBox_040
LEDev21 (start)  Running  - Oracle VM VirtualBox_041

[logs.zip](https://github.com/learningequality/kolibri/files/6171869/logs.zip)

**Comment by jonboiser** [comment]
Those backend logs look expected, so I think the frontend should be solid as long the requests to cancel/clear tasks are being done at the right times.

File: kolibri/plugins/setup_wizard/assets/src/app.js [hunk 1]
```diff
@@ -16,6 +20,8 @@ class OnboardingApp extends KolibriApp {
   }
   ready() {
     return super.ready().then(() => {
+      logging.info('Clearning facility tasks created in previous sessions...');
```
Comment (sairina) [inline kolibri/plugins/setup_wizard/assets/src/app.js]:
```suggestion
      logging.info('Clearing facility tasks created in previous sessions...');
```

**Review by sairina — APPROVED** [review]
There's just a minor typo (just for logging purposes). Otherwise LGTM!
