### PR TITLE
Fix setup wizard selection of network devices for sign up or import

### LINKED ISSUE #11496: In the Setup Wizard Facilities are filtered by the 'learners can create account' facility setting
## Observed behavior
When attempting to import a learner from a facility in the setup wizard to create an LOD, facilities that do not have the 'learners can create account' setting are filtered from display.

## Expected behavior
An LOD learner should still be able to be imported from and merge into a facility, if the 'allow learners to create account' setting is not enabled - but they should not be offered the option to create an account on the facility if they do so, they can only import an existing account from the facility.

## User-facing consequences
Confusion as to why they cannot import their account!

## Steps to reproduce
Create a facility, ensure that the 'allow learner to create account' facility setting is turned off.
Setup another Kolibri and attempt to import a single learner from the full facility - the facility will not be listed.

## Context
Kolibri 0.16.0-beta7

### PR DESCRIPTION
**Pull request by bjester**
## Summary

- Reverts prior change that implemented filtering on whether a learner can signup
- Implements, through refactoring, method for flexible filtering of facilities which is now supported through the selection form

### With learner sign up disabled
| Join | Import |
| --- | --- |
| Screenshot from 2023-11-08 12-23-04 | Screenshot from 2023-11-08 12-22-53 | 

### With learner signup enabled
| Join | Import |
| --- | --- |
| Screenshot from 2023-11-08 12-41-28 |  Screenshot from 2023-11-08 12-41-39 |

## References

Fixes: https://github.com/learningequality/kolibri/issues/11496

## Reviewer guidance

Tested the signup flow and channel import

----

## Testing checklist

- [x] Contributor has fully tested the PR manually
- [ ] If there are any front-end changes, before/after screenshots are included
- [ ] Critical user journeys are covered by Gherkin stories
- [x] Critical and brittle code paths are covered by unit tests

## PR process

- [x] PR has the correct target branch and milestone
- [x] PR has 'needs review' or 'work-in-progress' label
- [x] If PR is ready for review, a reviewer has been added. (Don't use 'Assignees')
- [ ] If this is an important user-facing change, PR or related issue has a 'changelog' label
- [ ] If this includes an internal dependency change, a link to the diff is provided

## Reviewer checklist

- Automated test coverage is satisfactory
- PR is fully functional
- PR has been tested for [accessibility regressions](http://kolibri-dev.readthedocs.io/en/develop/manual_testing.html#accessibility-a11y-testing)
- External dependency files were updated if necessary (`yarn` and `pip`)
- Documentation is updated
- Contributor is in AUTHORS.md

### CODE REVIEW

File: kolibri/core/assets/src/views/sync/SelectDeviceModalGroup/api.js [hunk 1]
```diff
@@ -24,13 +25,20 @@ export function fetchDevices(params = {}) {
...
  * @param {NetworkLocation} device
+ * @param {FacilityFilter} facility
  * @return {Promise<boolean>}
  */
-export function facilityIsAvailableAtDevice(facilityId, device) {
+export function deviceHasMatchingFacility(device, facility) {
+  // TODO: ideally we could pass along the filters directly to the API
   return NetworkLocationResource.fetchFacilities(device.id).then(({ facilities }) => {
-    return Boolean(facilities.find(({ id }) => id === facilityId));
+    return Boolean(facilities.find(matches(facility)));
```
Comment (nucleogenesis) [inline kolibri/core/assets/src/views/sync/SelectDeviceModalGroup/api.js:41]: This is so neat I had to go try it out in the console. Love learning something new about the many magical lodash tools

File: kolibri/core/assets/src/views/sync/SelectDeviceModalGroup/useDevices.js [hunk 2]
```diff
@@ -129,51 +143,83 @@ function useDevicesWithFilter(apiParams, filterFunction) {
...
+function useAsyncDeviceFilter(filterFunction) {
+  const memoized = useMemoize(filterFunction, { getKey: device => device.id });
 
-  return useDevicesWithFilter({}, filterDevices);
+  return async function deviceFilter(device) {
+    try {
+      return await memoized(device);
+    } catch (e) {
+      // If not 404 clear cache to try again on next poll
+      if (e?.response?.status !== 404) {
```
Comment (nucleogenesis) [inline kolibri/core/assets/src/views/sync/SelectDeviceModalGroup/useDevices.js]: We can't use the [optional chaining operator](https://caniuse.com/mdn-javascript_operators_optional_chaining) until a future release after we lose IE11 support. [We're deprecating it soon though](https://github.com/learningequality/kolibri/pull/10739). 

We've used `_.get(e, 'response.status')` elsewhere in Kolibri to a similar effect in the mean time.

File: kolibri/core/assets/src/views/sync/SelectDeviceModalGroup/useDevices.js [hunk 3]
```diff
@@ -129,51 +143,83 @@ function useDevicesWithFilter(apiParams, filterFunction) {
...
+
+  if (learner_can_sign_up !== null) {
+    filters.learner_can_sign_up = learner_can_sign_up;
+  }
+
+  if (Object.keys(filters).length === 0) {
+    return () => Promise.resolve(true);
+  }
+
+  return useAsyncDeviceFilter(function deviceFacilityFilter(device) {
```
Comment (nucleogenesis) [inline kolibri/core/assets/src/views/sync/SelectDeviceModalGroup/useDevices.js:193]: Does the parameter passed to `useAsyncDeviceFilter` have to be named or could it be an anonymous function?

File: kolibri/core/assets/src/views/sync/SelectDeviceModalGroup/useDevices.js [hunk 4]
```diff
@@ -129,51 +143,83 @@ function useDevicesWithFilter(apiParams, filterFunction) {
...
- * Filters devices to those that are not SoUDs/LOD, since SoUD/LOD sync to full-facility devices
- * @return {{
- *  devices: Ref<NetworkLocation[]>, hasFetched: Ref<bool>, isFetching: Ref<bool>,
- *  filterFailed: Ref<bool>, forceFetch: (function(): Promise<void>)
- * }}
+ * Produces a function that resolves with a boolean if Kolibri version is at least the specified
+ * @param {number} major
+ * @param {number} minor
+ * @param {number} patch
+ * @return {function(NetworkLocation): Promise<boolean>}
```
Comment (nucleogenesis) [inline kolibri/core/assets/src/views/sync/SelectDeviceModalGroup/useDevices.js:218]: This is a beautiful improvement <3

**Review by nucleogenesis — CHANGES_REQUESTED** [review]
The only blocking change request is the use of the conditional chaining operator.

Overall, this is a massive improvement. Every place there is a change, the result is more readable and easier to follow/understand. I really love this overall and I think that `useDevices` and the filtering business would be a great thing to present & discuss with the team if you'd be up for it.

File: kolibri/core/assets/src/views/sync/SelectDeviceModalGroup/useDevices.js (hunk 3 above)
Comment (nucleogenesis) [reply kolibri/core/assets/src/views/sync/SelectDeviceModalGroup/useDevices.js:193]: Mostly asking because when I see something named, especially as specifically as `deviceFacilityFilter` I kind of expect it to be something that I need to know about elsewhere or later but it seems like this could just as well be called `filterFn` or nothing at all -- although I could totally be missing something elsewhere?

File: kolibri/core/assets/src/views/sync/SelectDeviceModalGroup/useDevices.js (hunk 4 above)
Comment (nucleogenesis) [reply kolibri/core/assets/src/views/sync/SelectDeviceModalGroup/useDevices.js:218]: I wish it showed the full diff so it was obvious here what it looked like before lol this is really so much nicer a way to do what we need to do here.

File: kolibri/core/assets/src/views/sync/SelectDeviceModalGroup/useDevices.js (hunk 2 above)
Comment (bjester) [reply kolibri/core/assets/src/views/sync/SelectDeviceModalGroup/useDevices.js]: Ah I thought this would get babelified. Will update

File: kolibri/core/assets/src/views/sync/SelectDeviceModalGroup/useDevices.js (hunk 3 above)
Comment (bjester) [reply kolibri/core/assets/src/views/sync/SelectDeviceModalGroup/useDevices.js:193]: It doesn't have to be named. Although, there is a benefit when reading error stack traces, because anonymous functions would of course be anonymous and indistinguishable from other anonymous.

File: kolibri/core/assets/src/views/sync/SelectDeviceModalGroup/useDevices.js (hunk 4 above)
Comment (bjester) [reply kolibri/core/assets/src/views/sync/SelectDeviceModalGroup/useDevices.js:218]: Yeah by making the filters (filter functions) more like object entities, it disconnects the 'inheritance' structure that was in use before and makes it more flexible

**Review by nucleogenesis — APPROVED** [review]
Requested changes have been made. Thanks for this Blaine!

**Review by akolson — APPROVED** [review]
Changes look correct to me and code is understandable. Thanks @bjester
