### PR TITLE
Scheduled syncing updates

### LINKED ISSUE #10490: Allow scheduled  sync task to be updated when it has been edited.
## Observed behavior
Currently, when a user edits a scheduled sync task, a new task is created instead of updating the existing one. This creates confusion.

## Expected behavior

When a user edits a scheduled sync task, the changes should be applied to the existing task instead of creating a new task.

## User-facing consequences

This issue affects users who create and manage scheduled sync tasks. By allowing tasks to be updated when edited, users will have a more streamlined experience as they manage their tasks more efficiently.

## Context
It is a follow up issue from sync schedule work #9786

### PR DESCRIPTION
**Pull request by rtibbles**
## Summary
* Updates the scheduled syncing code to use the updated backend from #10724 to:
  * Update enqueue arguments
  * Delete scheduled tasks
* Also updates a lot of frontend logic to repopulate the data for the EditDeviceSyncSchedule component to allow properly editing the task based on existing enqueue arguments
* Updates handling of date times in the frontend to better display and internationalize using vue-intl utilities
* Updates the SyncFacilityModalGroup component to include handling of registration to KDP to avoid replicating logic across three different parts of the app
* Integrates the updated SyncFacilityModalGroup into ManageSyncSchedule to leverage facility specific filtering and syncing to KDP
* Adds support for syncing to KDP within the Sync schedule components

## References
Fixes [#10490](https://github.com/learningequality/kolibri/issues/10490)

## Reviewer guidance
Schedule, edit, and delete scheduled syncs using the UI in both the Device plugin and the Facilities plugin.

[Screencast from 05-24-2023 05:12:25 PM.webm](https://github.com/learningequality/kolibri/assets/1680573/e118a66f-30c3-44b0-80bd-da362cb5df4e)

----

## Testing checklist

- [x] Contributor has fully tested the PR manually
- [x] If there are any front-end changes, before/after screenshots are included
- [ ] Critical user journeys are covered by Gherkin stories
- [ ] Critical and brittle code paths are covered by unit tests

## PR process

- [x] PR has the correct target branch and milestone
- [x] PR has 'needs review' or 'work-in-progress' label
- [x] If PR is ready for review, a reviewer has been added. (Don't use 'Assignees')
- [ ] If this is an important user-facing change, PR or related issue has a 'changelog' label
- [ ] If this includes an internal dependency change, a link to the diff is provided

## Reviewer checklist

- Automated test coverage is satisfactory
- PR is fully functional
- PR has been tested for [accessibility regressions](http://kolibri-dev.readthedocs.io/en/develop/manual_testing.html#accessibility-a11y-testing)
- External dependency files were updated if necessary (`yarn` and `pip`)
- Documentation is updated
- Contributor is in AUTHORS.md

### CODE REVIEW

File: kolibri/plugins/device/assets/src/views/FacilitiesPage/facilityTasksQueue.js [hunk 1]
```diff
@@ -43,8 +43,13 @@ export default {
   computed: {
     facilityIsSyncing() {
       return function isSyncing(facility) {
-        const syncTasks = this.facilityTasks.filter(t => isSyncTask(t) && !t.clearable);
-        return Boolean(syncTasks.find(task => taskFacilityMatch(task, facility)));
+        const activeSyncTasks = this.facilityTasks.filter(
+          t =>
+            isSyncTask(t) &&
+            ((t.repeat !== null && !t.clearable) ||
```
Comment (AllanOXDi) [inline kolibri/plugins/device/assets/src/views/FacilitiesPage/facilityTasksQueue.js]: None blocking comment: I am wondering if we could introduce intermediate variables with descriptive names to improve code readability. Something like 
```
 const isSync = isSyncTask(task);
  const isRepeatableNonClearable = task.repeat !== null && !task.clearable;
```

So that instead of using a complex logical expression, the return statement in the `filter()` method utilizes the intermediate variable

File: packages/kolibri-common/components/SyncSchedule/EditDeviceSyncSchedule.vue
Comment (AllanOXDi) [inline packages/kolibri-common/components/SyncSchedule/EditDeviceSyncSchedule.vue:1]: I am wondering why whenever I try to edit task scheduled for an  hour it become inactive?

Uploading Screen Recording 2023-05-25 at 15.19.00.mov…

Comment (rtibbles) [reply packages/kolibri-common/components/SyncSchedule/EditDeviceSyncSchedule.vue:1]: This is because the tasks scheduled on the hour immediately sync - and because of backend complexities, we can't edit currently running tasks. I think this could probably use some user experience improvements, but also wasn't quite sure the best way to manage it without string updates too.

**Review by AllanOXDi — DISMISSED** [review]

File: kolibri/core/assets/src/views/sync/ConfirmationRegisterModal.vue [hunk 2]
```diff
@@ -90,6 +99,13 @@
             }
           });
       },
+      cancel() {
+        if (this.alreadyRegistered && this.successOnAlreadyRegistered) {
```
Comment (LianaHarris360) [inline kolibri/core/assets/src/views/sync/ConfirmationRegisterModal.vue:103]: If a facility tries to re-register to a project they are already registered to, should there be a check to see if it is already registered with the project before submission, which would change this data prop `alreadyRegistered` to true? Or is this line only meant to catch the error if the facility is found to already be registered?

I'm asking because the parts where `alreadyRegistered` is used in the template are never really shown and could be removed. I manipulated the data in Vue.js devtools to see this view.

Screenshot 2023-05-25 at 3 46 48 PM

Comment (rtibbles) [reply kolibri/core/assets/src/views/sync/ConfirmationRegisterModal.vue:103]: This is only meant to catch the case where there is an error with registration due to the facility already being registered to KDP.

In the case where we are directly doing a registration action by using the `Register` option from the dot menu, this emits a 'cancel' event. In the case that I am using it here, I wanted it to instead emit a success event in this case, as it is fine to carry on and try to sync to KDP because it is already registered, so this logic is intended to be handling that.

File: kolibri/plugins/device/assets/src/views/FacilitiesPage/facilityTasksQueue.js (hunk 1 above)
Comment (rtibbles) [reply kolibri/plugins/device/assets/src/views/FacilitiesPage/facilityTasksQueue.js]: Yes, I think this functional style can be a bit hard to read and intermediary variables can help. I mostly didn't do that because it was like that when I got here! I'll leave for now, but I think worth thinking about when we do further reworking of the frontend task handling (which I have some overall ideas on how we can migrate to a dedicated composable).

**Comment by pcenov** [comment]
Hi @rtibbles here are some minor issues I was able to identify while testing the scheduled syncing:

1. When a sync is happening while one is at the Facilities page, the 'Last synced' value doesn't update unless I manually refresh the page:

https://github.com/learningequality/kolibri/assets/79847249/49dcd1df-1c8d-45b7-b9e7-7520753fe19f

2. The status of a KDP schedule is always displayed as 'Not connected' and there's always an error in the console which states: Cannot read properties of undefined (reading 'device name')



3. For some reason there are 2 tasks in the task manager which always show as incomplete (I'll let you know if I find specific steps to replicate that one):

**Comment by rtibbles** [comment]
Thanks Peter - I think issue 1 is an existing issue, so let's file that as a follow up.

For issue 2, I'll hide the connection status for KDP, and we can update that when we have better connection tracking for KDP once https://github.com/learningequality/kolibri/issues/10431 is resolved.

For issue 3, I'll tweak to make this less weird.

**Comment by rtibbles** [comment]
2 should now be fixed:
Screenshot from 2023-05-30 13-20-27

3 should now be better:
Screenshot from 2023-05-30 13-17-54

**Comment by pcenov** [comment]
@rtibbles I confirm that 2 and 3 are fixed now and have filed a follow-up issue for 1 here: https://github.com/learningequality/kolibri/issues/10759

I also noticed that if I lose my internet connection or I stop the server for a facility for which I have scheduled a sync, the line in the table completely disappears instead of seeing the 'Not connected' status:

https://github.com/learningequality/kolibri/assets/79847249/825543cb-af5f-497c-a873-95a4b936d1a6

A somewhat similar issue can be observed at Facility > Data > Manage sync schedule where after editing the schedule the entry disappears:

https://github.com/learningequality/kolibri/assets/79847249/4e589d20-79e0-48dc-bc3a-b508325ea145

**Comment by rtibbles** [comment]
Thanks @pcenov - that's a good catch, I'll update to fix this.

**Comment by rtibbles** [comment]
I think this should now be fixed.

Screenshot from 2023-06-01 12-04-54

**Comment by pcenov** [comment]
Hi @rtibbles, I confirm that now if I stop the server of a facility for which I have a scheduled sync that is reflected correctly in the status which changes first to 'Not connected' and then back to 'Connected' once I've restarted the server. However if I turn off my wi-fi and then turn it on, the status remains 'Not connected' until I manually restart the server.

https://github.com/learningequality/kolibri/assets/79847249/8970811a-eab2-49f7-9eeb-9461f2475de0

Also this issue is still not fixed:

"A somewhat similar issue can be observed at Facility > Data > Manage sync schedule where after editing the schedule the entry disappears:"

https://github.com/learningequality/kolibri/assets/79847249/4e589d20-79e0-48dc-bc3a-b508325ea145

Lastly, one new very minor issue which we've missed so far - the 'Frequency' drop-down is incorrectly labeled 'Frequence'

I can of course file those as separate issues if you wish.

**Comment by rtibbles** [comment]
> Lastly, one new very minor issue which we've missed so far - the 'Frequency' drop-down is incorrectly labeled 'Frequence'

This will need to be a separate issue, as we don't have the string to update this, I believe.

**Comment by rtibbles** [comment]
> However if I turn off my wi-fi and then turn it on, the status remains 'Not connected' until I manually restart the server.

I think this should be filed as a follow up issue too - seems to be an issue with the connection status being properly updated when the network adapter state changes, so this is rather outside the remit of this PR!

**Comment by rtibbles** [comment]
> "A somewhat similar issue can be observed at Facility > Data > Manage sync schedule where after editing the schedule the entry disappears:"

I had foolishly assumed that the previous issue that I fixed and this issue had the same root cause, I'll investigate further now.

**Comment by rtibbles** [comment]
@pcenov this issue:
> "A somewhat similar issue can be observed at Facility > Data > Manage sync schedule where after editing the schedule the entry disappears:"

Was actually an issue with any navigation back from the sync edit page or the listing of all syncs page. Now all navigation actions should be working including:
* Creating a new sync
* Editing an existing sync
* Deleting a sync
* Pressing the X button when editing a sync
* Cancelling a sync edit
* Going back from the listing of syncs (should return to the correct Data page for the chosen facility)

**Comment by pcenov** [comment]
Thanks @rtibbles for further investigating and fixing it properly. No new issues observed while regression testing today, LGTM!

**Review by radinamatic — APPROVED** [review]
Manual QA passed, good to go! 👏🏽 💯 :shipit:
