### PR TITLE
Use fuse.js to filter and rank users by `username` and `full_name` fields in `PaginatedListContainer`

### LINKED ISSUE #7131: exact word matches should display first in user search
### Observed behavior

My username is 'd' and my full name is 'd'. In order to find the user I need to page through multiple pages

### Expected behavior

exact word matches should display first in all user searches (e.g. class assignment, device permission, facility user list, etc)

### User-facing consequences

harder to find users in a large facility

### Steps to reproduce

search for users in a large facility

### Context

0.14.0 beta 3

### PR DESCRIPTION
**Pull request by jonboiser**
### Summary

1. Reimplements and renames the `filterAndSortUsers` (at `kolibri.utils.filterUsersByNames`) utility using `fuse.js` library. 
2. Removes duplicated code across different Kolibri plugins and move the filtering logic into `PaginatedListContainer`
3. Change the textbox filter in `PaginatedListContainer` such that the textbox is refocused after the user clears is by clicking the "X" button

### Reviewer guidance

1. Based on how fuse.js is configured, #7131 is resolved because it will give exact matches between the filter's input and a user's full name or username the top rank in the results.
2. Non-exact matches will also be ranked and filtered within the configured threshold of "0.1", which is intended to not be forgiving of large difference between the filter and the users' names.

### References

Fixes #7131

----

### Contributor Checklist

PR process:

- [x] PR has the correct target branch and milestone
- [x] PR has 'needs review' or 'work-in-progress' label
- [x] If PR is ready for review, a reviewer has been added. (Don't use 'Assignees')
- [x] If this is an important user-facing change, PR or related issue has a 'changelog' label
- [ ] If this includes an internal dependency change, a link to the diff is provided

Testing:

- [ ] Contributor has fully tested the PR manually
- [ ] If there are any front-end changes, before/after screenshots are included
- [ ] Critical user journeys are covered by Gherkin stories
- [ ] Critical and brittle code paths are covered by unit tests

### Reviewer Checklist

- Automated test coverage is satisfactory
- PR is fully functional
- PR has been tested for [accessibility regressions](http://kolibri-dev.readthedocs.io/en/develop/manual_testing.html#accessibility-a11y-testing)
- External dependency files were updated if necessary (`yarn` and `pip`)
- Documentation is updated
- Contributor is in AUTHORS.md

### CODE REVIEW

File: kolibri/core/assets/src/core-app/apiSpec.js [hunk 1]
```diff
@@ -191,24 +192,25 @@ export default {
...
-    UserType,
-    shuffled,
-    bytesForHumans,
-    branding,
     scriptLoader,
+    serverClock,
+    shuffled,
     sortLanguages,
+    UserType,
+    validators,
```
Comment (nucleogenesis) [inline kolibri/core/assets/src/core-app/apiSpec.js:214]: Just gotta say I love that you sorted this list.

**Review by nucleogenesis — APPROVED** [review]
Tested and it worked perfectly. Great work!
