### PR TITLE
Fix survey and practice quiz submission

### LINKED ISSUE #10860: Unable to submit surveys
## Observed behavior
When testing surveys, @radinamatic noticed that there are significant errors in the console during the interaction of the survey, but most critically, that the survey does not submit at the end. I was able to reproduce this and I think it's related to the changes of the `finish` event in https://github.com/learningequality/kolibri/pull/10747/

## Errors and logs

Screenshot 2023-06-16 at 9 16 38 AM

## Expected behavior
User should be able to submit surveys, even if they are a feature currently only used in certain scenarios.

## Steps to reproduce
Choose a survey from the QA channel. Complete it. Note the errors in the console while filling out your answers. When you get to the "submit" step, note that the survey does not submit but stays on the screen with the modal open. 

## Context
latest develop

### PR DESCRIPTION
**Pull request by rtibbles**
## Summary
* Fixes regression for survey and practice quiz regression by ensuring a promise is always returned
* Fixes survey and practice quiz reports for anonymous users with a minimal fix to prevent errors - does not display actual reports, because userId is required to load the relevant data

## References
Fixes #10860 

## Reviewer guidance
Can surveys and reviews be submitted without errors in the console? Do they properly redirect after?

Do anonymous users submit quizzes and surveys without errors in the console? Do they see this (for surveys):
Screenshot from 2023-06-16 11-19-54

----

## Testing checklist

- [ ] Contributor has fully tested the PR manually
- [ ] If there are any front-end changes, before/after screenshots are included
- [ ] Critical user journeys are covered by Gherkin stories
- [ ] Critical and brittle code paths are covered by unit tests

## PR process

- [ ] PR has the correct target branch and milestone
- [ ] PR has 'needs review' or 'work-in-progress' label
- [ ] If PR is ready for review, a reviewer has been added. (Don't use 'Assignees')
- [ ] If this is an important user-facing change, PR or related issue has a 'changelog' label
- [ ] If this includes an internal dependency change, a link to the diff is provided

## Reviewer checklist

- Automated test coverage is satisfactory
- PR is fully functional
- PR has been tested for [accessibility regressions](http://kolibri-dev.readthedocs.io/en/develop/manual_testing.html#accessibility-a11y-testing)
- External dependency files were updated if necessary (`yarn` and `pip`)
- Documentation is updated
- Contributor is in AUTHORS.md

### CODE REVIEW

**Comment by radinamatic** [comment]
Both practice quizzes and surveys can now be submitted with the proper redirect, included when not signed in, but there are still errors in the console, plus some occasional loading errors.

https://github.com/learningequality/kolibri/assets/1457929/2070981e-61b0-458d-a291-901350da7e3e


https://github.com/learningequality/kolibri/assets/1457929/5890bd7f-e9df-4a5e-9708-f0e4d491e3d7

**Comment by rtibbles** [comment]
These issues should now be fixed - would also be good to verify that taking hints works as intended in exercises.

**Comment by pcenov** [comment]
Hi @rtibbles there is something seriously wrong with the latest build here - the channel import is not working and also navigating to any other plugin besides Device.

https://github.com/learningequality/kolibri/assets/79847249/af25eb60-7354-47eb-8187-090e445b6bac

[logs.zip](https://github.com/learningequality/kolibri/files/11800484/logs.zip)

**Comment by rtibbles** [comment]
This issue was in develop, and should now be fixed - I've rebased the PR, so hopefully testing is now unhindered!

**Comment by pcenov** [comment]
Hi @rtibbles, there aren't any errors in the console after submitting a survey or a practice quiz in the latest build.
Noticed the following issues:
1. Hints are not displayed in the practice quizzes:

https://github.com/learningequality/kolibri/assets/79847249/143cc5bf-d74a-463d-bafa-b873b98f40e8

2. Every time I resubmit a survey or a practice quiz I see the +500 points success message and the points are added to the previously earned ones:

https://github.com/learningequality/kolibri/assets/79847249/048debd6-722e-4f58-803f-60144eb51930

**Comment by rtibbles** [comment]
> Hints are not displayed in the practice quizzes

This is intentional - hints should only be displayed on exercises.

> Every time I resubmit a survey or a practice quiz I see the +500 points success message and the points are added to the previously earned ones:

This is not intentional! I can fix this.

**Comment by rtibbles** [comment]
> > Every time I resubmit a survey or a practice quiz I see the +500 points success message and the points are added to the previously earned ones:

> This is not intentional! I can fix this.

I have instead updated the points calculation to be consistent with this behaviour - so these points updates should persist across page loads.

**Comment by pcenov** [comment]
@radinamatic Yes, I confirm the points updates persist across page loads.

**Review by radinamatic — APPROVED** [review]
Manual QA passed, good to go! 🎉 💯 :shipit:

File: kolibri/plugins/learn/assets/src/views/ExamPage/index.vue [hunk 1]
```diff
@@ -349,11 +349,7 @@
     },
     watch: {
       attemptLogItemValue(newVal, oldVal) {
-        // HACK: manually dismiss the perseus renderer message when moving
-        // to a different item (fixes #3853)
-        if (newVal !== oldVal && this.$refs.contentRenderer) {
-          this.$refs.contentRenderer.$refs.contentView.dismissMessage &&
-            this.$refs.contentRenderer.$refs.contentView.dismissMessage();
```
Comment (marcellamaki) [inline kolibri/plugins/learn/assets/src/views/ExamPage/index.vue:356]: how can all of this get deleted? is it because the logic about the content renderer existing is now elsewhere?

**Review by marcellamaki — APPROVED** [review]
Just one non-blocking (curiosity) question about some of the content renderer logic that was removed that I couldn't quite figure out how it worked. Otherwise the code read through makes sense, and manual QA says 🆗 ✅

File: kolibri/plugins/learn/assets/src/views/ExamPage/index.vue (hunk 1 above)
Comment (rtibbles) [reply kolibri/plugins/learn/assets/src/views/ExamPage/index.vue:356]: This was implemented a long time ago in the perseus renderer, so this is old, superfluous code.

See here where it's dismissed when rendered https://github.com/learningequality/kolibri/blob/develop/kolibri/plugins/perseus_viewer/assets/src/views/PerseusRendererIndex.vue#L279 (also lots of other calls to `dismissMessage` when other user interaction has happened).
