### PR TITLE
Fix show more of top level resources

### LINKED ISSUE #9553: Fix missing "show more" in resources not in folders
## Observed behavior
`show more` is completely missing from the top level resources in the Folder/TopicsContent view of kolibri. Therefore, a maximum of 4 resources are displayed (the "preview" amount), no matter how many there are

## Expected behavior
user should be able to access all resources 

## User-facing consequences
Confusing, and users are unable to access content

## Steps to reproduce
Navigate to a folder where there are more than 4 resources at the top level (not nested within other folders)

## Context
Kolibri develop

### PR DESCRIPTION
**Pull request by marcellamaki**
## Summary

Updates the "resource" display logic to be more distinct from topics and search results logic and to have separate management of display.

## References
Fixes #9553 

## Reviewer guidance

Not-logged in and logged-in views: 

not-logged-in

https://user-images.githubusercontent.com/17235236/177994588-f7633e8d-7444-460b-84b9-8329a63d7ebb.mp4

**QUESTIONS**

1. Is this too "simple" of a fix, i.e. should it be more complex to potentially allow for more incremented "view more" display? (such as appending 10 more at a time, rather than just all?) 

2. Is this too different from some of the composable setup?

3. Have I accidentally broken anything else?

## Testing checklist

- [ ] Contributor has fully tested the PR manually
- [ ] If there are any front-end changes, before/after screenshots are included
- [ ] Critical user journeys are covered by Gherkin stories
- [ ] Critical and brittle code paths are covered by unit tests

## PR process

- [ ] PR has the correct target branch and milestone
- [ ] PR has 'needs review' or 'work-in-progress' label
- [ ] If PR is ready for review, a reviewer has been added. (Don't use 'Assignees')
- [ ] If this is an important user-facing change, PR or related issue has a 'changelog' label
- [ ] If this includes an internal dependency change, a link to the diff is provided

## Reviewer checklist

- Automated test coverage is satisfactory
- PR is fully functional
- PR has been tested for [accessibility regressions](http://kolibri-dev.readthedocs.io/en/develop/manual_testing.html#accessibility-a11y-testing)
- External dependency files were updated if necessary (`yarn` and `pip`)
- Documentation is updated
- Contributor is in AUTHORS.md

### CODE REVIEW

File: kolibri/plugins/learn/assets/src/views/TopicsPage.vue [hunk 1]
```diff
@@ -185,25 +185,23 @@
...
             <HybridLearningCardGrid
               v-if="resources.length"
-              :contents="resources"
+              :contents="resourcesDisplayed"
               :numCols="numCols"
               :genContentLink="genContentLink"
               cardViewStyle="card"
               @toggleInfoPanel="toggleInfoPanel"
             />
-            <div v-if="topicMore" class="end-button-block">
```
Comment (rtibbles) [inline kolibri/plugins/learn/assets/src/views/TopicsPage.vue:197]: Deleting this completely means that if there are sufficient resources in the top level of the topic to necessitate server side pagination, we will now never be able to load them.

We need both this button and the other button.

File: kolibri/plugins/learn/assets/src/views/TopicsPage.vue [hunk 2]
```diff
@@ -527,12 +526,23 @@
...
-          return resources;
+        return this.contents.filter(content => content.kind !== ContentNodeKinds.TOPIC);
+      },
+      resourcesDisplayed() {
+        // if no folders are shown at this level, show more resources to fill the space
+        if (this.topics.length == 0 && !this.showMoreResources) {
+          return this.resources.slice(0, this.childrenToDisplay * 2);
+          // if there are topics, and the user has not clicked show more
+          // default to just the preview number
+        } else if (this.topics.length > 0 && !this.showMoreResources) {
```
Comment (rtibbles) [inline kolibri/plugins/learn/assets/src/views/TopicsPage.vue]: Not sure why we needed to add this condition? Seems fine to just show all the loaded resources in this case.

File: kolibri/plugins/learn/assets/src/views/TopicsPage.vue [hunk 3]
```diff
@@ -527,12 +526,23 @@
...
+          return this.resources.slice(0, this.childrenToDisplay);
+          // otherwise display all resources
+        } else {
+          return this.resources;
```
Comment (rtibbles) [inline kolibri/plugins/learn/assets/src/views/TopicsPage.vue:545]: Stylistic nit - I prefer to return at the end of the function, rather than in a redundant `else` statement.

File: kolibri/plugins/learn/assets/src/views/TopicsPage.vue [hunk 4]
```diff
@@ -527,12 +536,21 @@
...
+        // if no folders are shown at this level, show more resources to fill the space
+        if (!this.showMoreResources) {
+          displayed = this.resources.slice(0, this.childrenToDisplay);
+          // otherwise display all resources
+        } else {
+          displayed = this.resources;
         }
-        return resources.slice(0, this.childrenToDisplay);
+        return displayed;
+      },
```
Comment (rtibbles) [inline kolibri/plugins/learn/assets/src/views/TopicsPage.vue]: This is missing the topics length check now, and the comments are somewhat misleading.

Maybe something like this? (using a return early pattern to avoid having to assign a variable):
```
      resourcesDisplayed() {
        // if no folders are shown at this level, show more resources to fill the space
        // or if the user has explicitly requested to show more resources
        if (!this.topics.length || this.showMoreResources) {
          return this.resources;
        } 
        return this.resources.slice(0, this.childrenToDisplay);
```

**Review by rtibbles — DISMISSED** [review]
One other regression to fix here.

**Comment by radinamatic** [comment]
> Is this too "simple" of a fix, i.e. should it be more complex to potentially allow for more incremented "view more" display? (such as appending 10 more at a time, rather than just all?)

Ideally yes, but might not be a blocker at this point.

> Have I accidentally broken anything else?

Browsed this and other channels, nothing jumped out at me 🙂 

Signed-in learner (Firefox) and guest (Chrome)

Ubuntu18 04 (start)  Running  - Oracle VM VirtualBox_002


Signed-in admin (Firefox) and guest (Chrome)

Ubuntu18 04 (start)  Running  - Oracle VM VirtualBox_003

**Review by radinamatic — APPROVED** [review]
LGTM! 💯 :shipit:
