### PR TITLE
Better handling of disconnected errors for API calls

### LINKED ISSUE #10930: Remote browsing - Missing connection error message
## Observed behavior
Clicking on a resource or a channel from Kolibri Library when internet connection is lost or the server is stopped results in a ‘Sorry! Something went wrong! error

## Expected behavior
Connection errors should be handled gracefully

## Steps to reproduce the issue
1. Install the latest develop build
2. Navigate to Library > Explore libraries
3. Stop the device's internet connection or stop the server of the device that you are exploring and click on a resource in the channel

## Usage Details
Kolibri 0.16alfa17
Windows 10, Ubuntu - Chrome

### PR DESCRIPTION
**Pull request by rtibbles**
## Summary
* Replaces all uses of the `handleError` action that was being inadvertently used for API errors with `handleApiError`
* When a disconnected state is detected, if the global loading state is currently true, then record that and force a page refresh on reconnection
* Clean up error clearing

## References
Fixes #10930

## Reviewer guidance
Browse a channel.
In the dev tools use network throttling to set as disconnected.
Attempt to navigate into a topic.
Confirm that no API error page appears.
Turn off network throttling.
Confirm on reconnect that the page refreshes.

----

## Testing checklist

- [ ] Contributor has fully tested the PR manually
- [ ] If there are any front-end changes, before/after screenshots are included
- [ ] Critical user journeys are covered by Gherkin stories
- [ ] Critical and brittle code paths are covered by unit tests

## PR process

- [ ] PR has the correct target branch and milestone
- [ ] PR has 'needs review' or 'work-in-progress' label
- [ ] If PR is ready for review, a reviewer has been added. (Don't use 'Assignees')
- [ ] If this is an important user-facing change, PR or related issue has a 'changelog' label
- [ ] If this includes an internal dependency change, a link to the diff is provided

## Reviewer checklist

- Automated test coverage is satisfactory
- PR is fully functional
- PR has been tested for [accessibility regressions](http://kolibri-dev.readthedocs.io/en/develop/manual_testing.html#accessibility-a11y-testing)
- External dependency files were updated if necessary (`yarn` and `pip`)
- Documentation is updated
- Contributor is in AUTHORS.md

### CODE REVIEW

File: kolibri/core/assets/src/heartbeat.js [hunk 1]
```diff
@@ -225,6 +225,7 @@ export class HeartBeat {
     if (store.getters.connected) {
       // We have not already registered that we have been disconnected
       store.commit('CORE_SET_CONNECTED', false);
+      store.commit('CORE_SET_DISCONNECTED_WHILE_LOADING', store.state.core.loading);
```
Comment (nucleogenesis) [inline kolibri/core/assets/src/heartbeat.js]: I'm not sure that this will catch all of the necessary loading states since the shift toward more localized loading states for the loading of content. I think this is why maybe I encountered the following:

- Go to library
- Throttle to Offline
- Go to a piece of content
- Unthrottle
- No page reload - no content loaded

Looking at `kolibri/plugins/learn/assets/src/modules/topicsTree/handlers.js`, though, maybe it's just because the component never ended up loading -- or perhaps because the `_loadTopicsContentStore` doesn't set page loading to true in this particular case.

**Review by nucleogenesis — CHANGES_REQUESTED** [review]
The testing scenario you mentioned worked as expected but I ran into a relatively minor instance of where it didn't work well. Overall once the test passes on the heartbeat should be good

**Review by MisRob — APPROVED** [review]
Thanks, @rtibbles.

When I saw https://github.com/learningequality/kolibri/issues/10930, I was wondering if there's really a need to be changing the behavior, because I'd actually expect being taken to an error page after clicking something in the disconnected state/overlay and generally speaking, I consider letting people reload the page themselves a good practice when compared to doing it automatically (to prevent losing work in progress or just because it's quite intrusive and unexpected UX). In this particular case, because there is the check ensuring it happens only during and shortly after the loading phase, it seems to be safe to do, and when testing, I had an impression it improves the experience (definitely better then being stuck in the empty loading page).

I agree with @nucleogenesis that this won't address local loading states, but I think it's questionable if that's actually needed and what's expected UX.

Overall, I think it'd be best to clarify our expectations towards global vs loading (including errors) UX in general as lately there were more discussions about that.

**Comment by rtibbles** [comment]
Thanks @MisRob and @nucleogenesis - I think that there is a slightly different approach we can take here that avoids hard coding the core loading state into the issue and makes it a slightly less global behaviour.

My thought is that instead of reading the core loading state in the heartbeat, instead we add an argument to `handleApiError` - this argument would gate whether a disconnection error should prompt the reload or not.

I think my instinct would still be to a) apply this to almost every place that `handleApiError` is used, and b) still do the autoreload behaviour for now, although I agree with @MisRob that being able to nuance this behaviour and require user input in some cases is important.

**Comment by MisRob** [comment]
> My thought is that instead of reading the core loading state in the heartbeat, instead we add an argument to handleApiError - this argument would gate whether a disconnection error should prompt the reload or not.

I think that's a really good idea. Another benefit would be that it would let developers know about the option to who could then consider whether it's suitable on the case by case basis.

**Comment by rtibbles** [comment]
OK, I've updated with the above changes. I only used the new flag in cases where the error handling was clearly for page loading.

However, because of the updated signature, I did have to update it everywhere for that.

To confirm I had caught every instance, I searched the codebase with this regex: `handleApiError', [^{]`

File: kolibri/plugins/coach/assets/src/composables/useGroups.js [hunk 2]
```diff
@@ -54,12 +54,17 @@ export function useGroups() {
                 store.dispatch('clearError');
               }
             },
-            error => (shouldResolve() ? store.dispatch('handleError', error) : null)
+            error =>
+              shouldResolve()
+                ? store.dispatch('handleApiError', { error, reloadOnReconnect: true })
```
Comment (MisRob) [inline kolibri/plugins/coach/assets/src/composables/useGroups.js:59]: Very nice

**Review by MisRob — APPROVED** [review]
Thanks for taking the time to do the latest updates, @rtibbles, even when not all of the feedback was blocking and I guess that replacing all action calls may be somewhat burdensome. I didn't review in detail every place and decision to use/not to use the page reload, but rather focused on the overall approach and implementation which is looking great.

**Review by nucleogenesis — APPROVED** [review]
Updates look great to me - I haven't tested manually but overall looks like a great approach and provides us a simple path to take to fix any places that were missed that ought to reload that don't. Thanks Richard!
