### PR TITLE
Remove PDF Render Errors

### LINKED ISSUE #3309: Various errors when exiting a Exercises and PDFs in a Lesson
Getting different errors which seem to be due to quirks of the individual content renderers.

To reproduce:

1. Create, active, assign a Lesson with a PDF doc and/or Perseus Exercise
1. Go to the Lesson and view the Resource
1. Hit the "<-" button on the top bar
1. In the console, observe the Error.

This does not seem to mess with logging or affect any part of the User Experience, but does point to some code issues.

Don't see this error with HTML5 apps or videos. Couldn't find a channel with just MP3 audio.

## Exiting an exercise

Get this error
```
{request: {…}, url: "/api/attemptlog/?1520367692407=1520367692407", raw: XMLHttpRequest, status: {…}, headers: {…}, …}
entity
:
end_timestamp
:
["This field may not be null."]
__proto__
:
Object
```

## Exiting a PDF

```
[Vue warn]: Error in event handler for "updateProgress": "TypeError: Cannot read property 'channel_id' of undefined"

found in

---> <ContentRender> at kolibri/core/assets/src/views/content-renderer/index.vue
       <LearnContent> at kolibri/plugins/learn/assets/src/views/content-page/index.vue
         <LessonResourceViewer> at kolibri/plugins/learn/assets/src/views/classes/LessonResourceViewer.vue
           <AppBody> at kolibri/core/assets/src/views/app-body/index.vue
             <CoreBasePage> at kolibri/core/assets/src/views/core-base.vue
               <Root>
```

### PR DESCRIPTION
**Pull request by DXCanas**
### Summary

Described the problem in more depth [here](https://github.com/learningequality/kolibri/issues/3309#issuecomment-378115653)

Basically, reordered the page assignments until after promises return for all classroom pages.

### Reviewer guidance

...
Not really satisfied with the fix, but it works reliably. If anyone has ideas regarding how to ensure that the previous page is destroyed before the next one starts loading, I'd love to hear them.

### References

Fixes #3309 

----

### Contributor Checklist

- [x] Contributor has fully tested the PR manually
- [x] PR has the correct target branch and milestone
- [x] PR has 'needs review' or 'work-in-progress' label
- [x] If PR is ready for review, a reviewer has been added. (Don't use 'Assignees')
- [x] If there are any front-end changes, before/after screenshots are included
- [x] If this is an important user-facing change, PR or related issue has a 'changelog' label

### Reviewer Checklist

- [ ] Automated test coverage is satisfactory
- [ ] Reviewer has fully tested the PR manually
- [ ] PR has been tested for [accessibility regressions](http://kolibri-dev.readthedocs.io/en/develop/manual_testing.html#accessibility-a11y-testing)
- [ ] External dependencies files were updated (`yarn` and `pip`)
- [ ] Documentation is updated
- [ ] Link to diff of internal dependency change is included
- [ ] CHANGELOG.rst is updated for high-level changes
- [ ] Contributor is in AUTHORS.rst

### CODE REVIEW

File: kolibri/plugins/learn/assets/src/state/actions/classesActions.js [hunk 1]
```diff
@@ -99,17 +103,18 @@ export function showLessonPlaylist(store, { lessonId }) {
...
-      currentLesson: {},
-      // To match expected shape for content-page
-      content: {},
-    },
-  });
+  store.dispatch('CORE_SET_PAGE_LOADING', true);
   return LearnerLessonResource.getModel(lessonId)
     .fetch({}, true)
     ._promise.then(lesson => {
+      preparePage(store, {
```
Comment (jonboiser) [inline kolibri/plugins/learn/assets/src/state/actions/classesActions.js]: isn't this the only action where moving `preparePage` is absolutely necessary, based on your analysis?

Comment (DXCanas) [reply kolibri/plugins/learn/assets/src/state/actions/classesActions.js]: It might actually be the only place it isn't. The issue of the state being assigned too early becomes apparent at any point _after_ `content-page` is mounted.

**Comment by DXCanas** [comment]
@jonboiser for clarification: Does this go on release or develop? I rebased because I saw excess commits.

**Comment by jonboiser** [comment]
@DXCanas If you can, rebase on release. If not, we can merge it to develop, then cherry pick to release 9

**Comment by jonboiser** [comment]
We need to check if this also fixes the logging issues with Exercises before considering #3309 closed.
