### PR TITLE
10440 fix

### LINKED ISSUE #10440: Users should be able to easily identify which exercises are practice quizzes vs. regular exercises
## Observed behavior
Noted by Francis in the Alpha-8 bug bash: 

"After signing is as a learner, many folders appeared and I couldn't tell which has the practice exercise. Is is possible to have like a thumbnail that would show that this is the latest practice quiz?"

## Context
Kolibri 0.16.0-alpha8

### PR DESCRIPTION
**Pull request by Wck-iipi**
## Summary

Fixes #10440 by altering LearningActivityDuration. This uses assessmentmetadata to compare if it is practice quiz. 

## References

Fixes #10440 

## Reviewer guidance

The editing is mainly done in `LearningActivityDuration` component. These changes are shown where `CardThumbnail` component exist, i.e. 
1. Learn->Library->Recent (If you have recently done a quiz)
2. Wherever quiz exists inside a channel.
3. Learn->Bookmarks (If you have bookmarked a quiz)
Kindly check whether the labels work as intended in above locations and are responsive. 

----

## Testing checklist

- [ ] Contributor has fully tested the PR manually
- [ ] If there are any front-end changes, before/after screenshots are included
- [ ] Critical user journeys are covered by Gherkin stories
- [ ] Critical and brittle code paths are covered by unit tests

## PR process

- [ ] PR has the correct target branch and milestone
- [ ] PR has 'needs review' or 'work-in-progress' label
- [ ] If PR is ready for review, a reviewer has been added. (Don't use 'Assignees')
- [ ] If this is an important user-facing change, PR or related issue has a 'changelog' label
- [ ] If this includes an internal dependency change, a link to the diff is provided

## Reviewer checklist

- Automated test coverage is satisfactory
- PR is fully functional
- PR has been tested for [accessibility regressions](http://kolibri-dev.readthedocs.io/en/develop/manual_testing.html#accessibility-a11y-testing)
- External dependency files were updated if necessary (`yarn` and `pip`)
- Documentation is updated
- Contributor is in AUTHORS.md

### CODE REVIEW

**Comment by MisRob** [comment]
Hi @Wck-iipi, thank you for your contribution. Could you please add the reviewer guidance? This will help a reviewer and especially our QA team as they will know where to navigate as a user and what places to check to confirm the fix and test for regressions. It doesn't need to be extremely detailed, just a couple of bullet points to give direction will do.

**Comment by Wck-iipi** [comment]
@MisRob Thanks for responding. Is above reviewer guidance sufficient or should I add more?

**Comment by MisRob** [comment]
@Wck-iipi Yes, that's very helpful, thank you

File: kolibri/plugins/learn/assets/src/composables/useLearningActivities.js [hunk 1]
```diff
@@ -132,6 +132,38 @@ export default function useLearningActivities(contentNode) {
       : coreStrings.$tr('longActivity');
   });
 
+  /**
+   * @returns {String} Returns the translated exercise type(Practice Quiz or other)
+   */
+  const exerciseDescription = computed(() => {
+    const isPracticeQuiz = lodashGet(contentNode, ['options', 'modality'], false) === 'QUIZ';
+    const options_mastery_model = lodashGet(
```
Comment (rtibbles) [inline kolibri/plugins/learn/assets/src/composables/useLearningActivities.js]: Don't need to read the mastery model from the options, only need the modality above. Reading this twice is liable to cause confusion - you can rely on the assessment metadata as canonical.

Apologies if my suggestion for using the 'options' confused this, but I meant only for the modality, not for anything else!

Comment (Wck-iipi) [reply kolibri/plugins/learn/assets/src/composables/useLearningActivities.js]: @rtibbles Thank you for guiding me. I have removed options_mastery_model completely. I have another question, should I also make same changes to `ContentNodeThumbnail`, which is shown when 'i' is clicked for more information so that `Practice quiz` or `Get x correct` is seen in `ContentNodeThumbnail`.
image

Comment (rtibbles) [reply kolibri/plugins/learn/assets/src/composables/useLearningActivities.js]: I think this is fine for now - we can create a follow up issue for this is if needed.

**Review by rtibbles — COMMENTED** [review]
This looks like the right change - a quick QA verification, and we can merge!

**Comment by pcenov** [comment]
@radinamatic the labels are displayed correctly as specified. No issues observed while manually testing.

**Review by radinamatic — APPROVED** [review]
Manual QA passed, good to go! 💯 :shipit:

**Comment by rtibbles** [comment]
Thanks for your contribution @Wck-iipi !
