### PR TITLE
Fix learning activity label style on bookmarks cards

### LINKED ISSUE #8725: Bookmark Card - Metadata misalignments
## Observed behavior

These likely have some padding/margin applied that makes sense at larger sizes but not when reflowed for a smaller screen.

Follows up from #8708 

image

## Expected behavior

Text aligns on the left.

## User-facing consequences

It looks off.

### PR DESCRIPTION
**Pull request by MisRob**
## Summary

Fixes learning activity labels on cards on the bookmarks page so that learning activity label, icon, and duration show on one line as specced [in Figma designs](https://www.figma.com/file/uiZuCIqh2KYvBUfbCiJyyA/Hybrid-Learning?node-id=130%3A11706). For that purpose, `condensed` prop has been added to `LearningActivityLabel` component.

| Before | After |
| -------- | ------- |
| Screenshot from 2021-12-02 11-05-22 | Screenshot from 2021-12-02 11-04-57 |

## References

Closes #8725

## Reviewer guidance

Check cards on the bookmarks page for various resolutions, learning activities, content kinds, and their durations.

## Testing checklist

- [x] Contributor has fully tested the PR manually
- [x] If there are any front-end changes, before/after screenshots are included
- [ ] Critical user journeys are covered by Gherkin stories
- [ ] Critical and brittle code paths are covered by unit tests

## PR process

- [x] PR has the correct target branch and milestone
- [x] PR has 'needs review' or 'work-in-progress' label
- [x] If PR is ready for review, a reviewer has been added. (Don't use 'Assignees')
- [ ] If this is an important user-facing change, PR or related issue has a 'changelog' label
- [ ] If this includes an internal dependency change, a link to the diff is provided

## Reviewer checklist

- Automated test coverage is satisfactory
- PR is fully functional
- PR has been tested for [accessibility regressions](http://kolibri-dev.readthedocs.io/en/develop/manual_testing.html#accessibility-a11y-testing)
- External dependency files were updated if necessary (`yarn` and `pip`)
- Documentation is updated
- Contributor is in AUTHORS.md

### CODE REVIEW

File: kolibri/plugins/learn/assets/src/views/HybridLearningContentCardListView.vue [hunk 1]
```diff
@@ -32,7 +32,11 @@
           class="metadata-info"
           :style="{ color: $themePalette.grey.v_700 }"
         >
-          <LearningActivityLabel :contentNode="content" class="learning-activity-label" />
+          <LearningActivityLabel
+            :contentNode="content"
+            labelAfter
```
Comment (jredrejo) [inline kolibri/plugins/learn/assets/src/views/HybridLearningContentCardListView.vue:37]: for consistency in the code, would you  mind to change https://github.com/learningequality/kolibri/blob/release-v0.15.x/kolibri/plugins/learn/assets/src/views/HybridLearningContentCard/index.vue#L22 to use the same syntax?

**Review by jredrejo — APPROVED** [review]
Code looks good and testing it, it really looks good to me!

**Review by nucleogenesis — APPROVED** [review]
LGTM!

File: kolibri/plugins/learn/assets/src/views/HybridLearningContentCardListView.vue (hunk 1 above)
Comment (MisRob) [reply kolibri/plugins/learn/assets/src/views/HybridLearningContentCardListView.vue:37]: Thanks, @jredrejo. I'm sorry for the late reply. I checked how we use Boolean props elsewhere, and it seems that across the whole codebase, we use explicit `true` value for many other boolean props, so even if I removed Boolean value from your reference, we'd still have many other places (just search for  `="true"` ) so it wouldn't probably help much overall with consistency. I don't feel strongly opinionated about these two syntaxes. Did you consider syntax without the Boolean value confusing? I could also use explicit `:labelAfter="true"` instead.

Comment (jredrejo) [reply kolibri/plugins/learn/assets/src/views/HybridLearningContentCardListView.vue:37]: Specs don't have a favourite setting, https://html.spec.whatwg.org/multipage/common-microsyntaxes.html#boolean-attribute. From a personal point, I prefer the presence/absence of the attribute to reflect its value. It looks more ellegant and readable for me, but it's a completely personal preference.
In any case, I think it's important to have consistency in the code. For this attribute we're using it only in one more place, so whatever is decided is good for me is it's the same in both parts.

Comment (MisRob) [reply kolibri/plugins/learn/assets/src/views/HybridLearningContentCardListView.vue:37]: Thanks. I appreciate its simplicity too. On the other hand, the advantage of having it explicitly defined might be that it's clear that it's one of Vue's `prop`s.

In any case, I'd say it's a matter of all Boolean attributes rather than this one specific attribute, and since we mostly use explicit syntax across the whole codebase, I think I'll use that.  I'm going to sneak the update in one of my next PRs.

Comment (MisRob) [reply kolibri/plugins/learn/assets/src/views/HybridLearningContentCardListView.vue:37]: Addressed here https://github.com/learningequality/kolibri/pull/8891
