### PR TITLE
MyDownloads bug fixes

### LINKED ISSUE #11026: "Select All" checkbox in MyDownloadsPage can be checked with no selectable items
## Observed behavior
Reported by @nucleogenesis during the beta0 bug bash

> when all items in the table are disabled, the “Select all” checkbox is not disabled, so I can still manage to select everything using that checkbox — noting it, but if the rows weren’t disabled, then this is behaving as intended beside the fact that clicking “Remove Selected” does nothing 

https://www.notion.so/learningequality/Cannot-remove-item-I-selected-to-download-on-My-Downloads-page-7e87f388f8a74df4a6263f0bfd6f884a?pvs=4

## Errors and logs
Screenshot 2023-07-27 at 4 28 17 PM

## Expected behavior
"Select all" should only be enabled if one or more items are selectable

## User-facing consequences
Confusion, mis-selecting items

## Steps to reproduce
Initiate a download and navigate to the "My Downloads" page

## Context
beta0

### LINKED ISSUE #11044: "Remove selected" does not work as expected
## Observed behavior
As reported by @nucleogenesis in the beta0 bug bash
> Even when downloads table is interactable, the “Remove selected” does nothing

## Errors and logs
```
500 error DELETE /api/content/contentrequest/0
```

## Expected behavior
List of selected items should all be removed

## User-facing consequences
User cannot delete multiple 

## Steps to reproduce
Download several items. Select multiple, and use the "delete selected" to remove them

## Context
v0.16.0beta0

### PR DESCRIPTION
**Pull request by marcellamaki**
## Summary
This PR generally: 
Cleans up/improves reactivity on the frontend 
Fixes broken remove download functionality 

## References
Fixes [#11026](https://github.com/learningequality/kolibri/issues/11026)
Fixes [#11044](https://github.com/learningequality/kolibri/issues/11044)

https://github.com/learningequality/kolibri/assets/17235236/bf41fd4c-3fec-4bc6-817a-da438a6f2805

## Reviewer guidance

1. Import a LOD from an existing facility
2. Import resources from that facility over the "local network"
3. Sort and filter requests
4. Remove requests - removing a single or a selection on download items should work 

there will be a follow up PR on Monday that manages: 
- polling for status updates on the downloads 
- error handling for errors when the source device is no longer on the network
- ensure that the "download" icon is properly reactive both on the content cards and within the content renderer (still inconsistent)

## Testing checklist

- [ ] Contributor has fully tested the PR manually
- [ ] If there are any front-end changes, before/after screenshots are included
- [ ] Critical user journeys are covered by Gherkin stories
- [ ] Critical and brittle code paths are covered by unit tests

## PR process

- [ ] PR has the correct target branch and milestone
- [ ] PR has 'needs review' or 'work-in-progress' label
- [ ] If PR is ready for review, a reviewer has been added. (Don't use 'Assignees')
- [ ] If this is an important user-facing change, PR or related issue has a 'changelog' label
- [ ] If this includes an internal dependency change, a link to the diff is provided

## Reviewer checklist

- Automated test coverage is satisfactory
- PR is fully functional
- PR has been tested for [accessibility regressions](http://kolibri-dev.readthedocs.io/en/develop/manual_testing.html#accessibility-a11y-testing)
- External dependency files were updated if necessary (`yarn` and `pip`)
- Documentation is updated
- Contributor is in AUTHORS.md

### CODE REVIEW

File: kolibri/plugins/learn/assets/src/my_downloads/views/DownloadsList/index.vue [hunk 1]
```diff
@@ -68,7 +68,7 @@
                   v-else
                   :text="coreString('viewAction')"
                   appearance="flat-button"
-                  :href="genExternalContentURLBackLinkCurrentPage(download)"
+                  :href="genExternalContentURLBackLinkCurrentPage(download.id)"
```
Comment (rtibbles) [inline kolibri/plugins/learn/assets/src/my_downloads/views/DownloadsList/index.vue]: Is it `download.id` or `download.contentnode_id`?

File: kolibri/plugins/learn/assets/src/my_downloads/views/DownloadsList/index.vue [hunk 2]
```diff
@@ -128,25 +131,70 @@
...
+      const totalPageNumber = ref(0);
+      const store = getCurrentInstance().proxy.$store;
+      const query = computed(() => get(route).query);
+      const route = computed(() => store.state.route);
+      const sort = computed(() => query.value.sort);
+      const pageSizeNumber = computed(() => Number(query.value.page_size || 25));
+      const activityType = computed(() => query.value.activity || 'all');
+      const downloads = ref([]);
+      const sortedFilteredDownloads = () => {
+        let downloadsToDisplay = [];
```
Comment (rtibbles) [inline kolibri/plugins/learn/assets/src/my_downloads/views/DownloadsList/index.vue:144]: Couldn't you just initialize this as `let downloadsToDisplay = Object.values(downloadRequestMap || {});`?

File: kolibri/plugins/learn/assets/src/my_downloads/views/DownloadsList/index.vue [hunk 3]
```diff
@@ -128,25 +131,70 @@
...
+                break;
+              case 'largest':
+                downloadsToDisplay.sort((a, b) => b.metadata.file_size - a.metadata.file_size);
+                break;
+              default:
+                // If no valid sort option provided, return unsorted array
+                break;
+            }
+          }
+          if (activityType) {
```
Comment (rtibbles) [inline kolibri/plugins/learn/assets/src/my_downloads/views/DownloadsList/index.vue]: If we filter by activityType first, then potentially, we won't have to sort as many things (not a huge deal).

File: kolibri/plugins/learn/assets/src/my_downloads/views/DownloadsList/index.vue [hunk 4]
```diff
@@ -128,25 +131,70 @@
...
+                download.metadata.learning_activities.includes(activityType.value)
+              );
+            }
+          }
+        }
+        set(totalPageNumber, Math.ceil(downloadsToDisplay.length / pageSizeNumber.value));
+        set(downloads, downloadsToDisplay);
+      };
+      sortedFilteredDownloads();
+      watch(route, () => {
```
Comment (rtibbles) [inline kolibri/plugins/learn/assets/src/my_downloads/views/DownloadsList/index.vue:184]: Rather than doing an explicit watch here, we could just initialize `downloads` as a computed value that returns the results of the `sortedFilteredDownloads` function.

`totalPageNumber` can then also be a computed value based on the `downloads` computed value.

File: kolibri/plugins/learn/assets/src/my_downloads/views/MyDownloads.vue [hunk 5]
```diff
@@ -178,8 +143,12 @@
       removeResources(resources) {
         if (resources.length === 1) {
           this.removeDownloadRequest(resources[0]);
+          Vue.delete(this.downloadRequestMap.value, resources[0].id);
```
Comment (rtibbles) [inline kolibri/plugins/learn/assets/src/my_downloads/views/MyDownloads.vue]: I do think it would be better to keep this removal in the composable `removeDownloadRequest` function.

Also, `downloadRequestMap` is a reactive, so its value is referenced directly, not via a `.value` property.

**Review by rtibbles — COMMENTED** [review]
Some things that could be cleaned up, at least one thing that looks incorrect to me.

File: kolibri/plugins/learn/assets/src/my_downloads/views/MyDownloads.vue (hunk 5 above)
Comment (marcellamaki) [reply kolibri/plugins/learn/assets/src/my_downloads/views/MyDownloads.vue]: I think I must be doing something wrong with the reactivity/setup here then, because when I keep it in the composable, it just doesn't work. Not only in the "the page doesn't rerender as expected" sense, but `Vue.delete()` seems to not do anything. logging the value before and after it is the same - nothing is deleted. 

I can see a couple of places where we are using in in mutations, but I couldn't find another place where we are using it in a composable to reference.

File: kolibri/plugins/learn/assets/src/my_downloads/views/DownloadsList/index.vue (hunk 2 above)
Comment (marcellamaki) [reply kolibri/plugins/learn/assets/src/my_downloads/views/DownloadsList/index.vue:144]: I fixed this, but I think after the other changes we made, this was what was causing the duplicate key error that we talked about on slack, so I reverted it

**Review by rtibbles — APPROVED** [review]
Main feedback addressed - additional cleanup and tweaks can happen in follow up.

**Comment by rtibbles** [comment]
Test failure is due to a flaky test from another PR. Merging, will resolve elsewhere.
