### PR TITLE
Fixes Bulk User Creation Failed prop console error

### LINKED ISSUE #13696: [Bulk User Creation]: Failed prop console error
❌ **This issue is not open for contribution. Visit <a href="https://learningequality.org/contributing-to-our-open-code-base/" target="_blank">Contributing guidelines</a>** to learn about the contributing process and how to find suitable issues.

## Description

Reported by @AllanOXDi 

#### Resolve the console errors

During the bulk creation of users:

Image

### PR DESCRIPTION
**Pull request by AllanOXDi**
## Summary
This PR fixes the console errors  when creating a new user
closes [#13696](https://github.com/learningequality/kolibri/issues/13696)

## References
[#13696](https://github.com/learningequality/kolibri/issues/13696)

###Before
Screenshot 2025-10-14 at 20 45 38

###After
Screenshot 2025-10-14 at 20 45 04

## Reviewer guidance
1. Navigate to facility > Users > New User
2. Observe the console

### CODE REVIEW

**Comment by pcenov** [comment]
Thanks @AllanOXDi - LGTM, the only remaining visible console errors are:



If these are not in scope for this PR, then it should be good to go!

File: kolibri/plugins/facility/assets/src/views/users/common/CloseConfirmationGuard.vue [hunk 1]
```diff
@@ -90,7 +90,7 @@
         if (props.hasUnsavedChanges && !closeConfirmationToRoute.value) {
           isConfirmationModalOpen.value = true;
           closeConfirmationToRoute.value = to;
-          next(false);
+          return;
```
Comment (nucleogenesis) [inline kolibri/plugins/facility/assets/src/views/users/common/CloseConfirmationGuard.vue]: Not a blocker. What console errors did this fix?

**Review by nucleogenesis — CHANGES_REQUESTED** [review]
I'm seeing the textColor error - why was it reverted? 

Otherwise the changes look okay - just want to clarify the scope before we merge.

**Comment by AllanOXDi** [comment]
> I'm seeing the textColor error - why was it reverted?
> 
> Otherwise the changes look okay - just want to clarify the scope before we merge.

Here was the slack conversation
https://learningequality.slack.com/archives/CB37UM23A/p1760540636649449

File: kolibri/plugins/facility/assets/src/views/users/common/CloseConfirmationGuard.vue (hunk 1 above)
Comment (AlexVelezLl) [reply kolibri/plugins/facility/assets/src/views/users/common/CloseConfirmationGuard.vue]: The intention of hook is to prevent the route navigation, and the correct way to do this is by calling next(false) https://v3.router.vuejs.org/guide/advanced/navigation-guards.html#in-component-guards. So this change should be reverted.

File: kolibri/plugins/facility/assets/src/views/users/sidePanels/UserCreate/ClassesSelect.vue
Comment (AlexVelezLl) [inline kolibri/plugins/facility/assets/src/views/users/sidePanels/UserCreate/ClassesSelect.vue:1]: The `selectedOption` here is not doing anything, its just a `ref` property that is initially set to `{}` but never changes. The previous `selectValue` property is the correct value that should be passed here, as this handles the select all behaviour https://github.com/AllanOXDi/kolibri/blob/45135e4a7b987684c34223770d01244e2138c314/kolibri/plugins/facility/assets/src/views/users/sidePanels/UserCreate/ClassesSelect.vue#L63.

This update is causing regressions when on the select all checkbox:

Before this PR:

https://github.com/user-attachments/assets/ad5d87cc-c15b-411d-800b-ab6d665e9fef

After this PR:

https://github.com/user-attachments/assets/27c3f6f7-d38a-402e-8459-1debaf8c7c95

**Review by AlexVelezLl — CHANGES_REQUESTED** [review]
Just found a couple of regressions. I feel the error in the KSelect value should be solved by updating the handler of the `selectValue` computed property.

File: kolibri/plugins/facility/assets/src/views/users/sidePanels/UserCreate/ClassesSelect.vue
Comment (AllanOXDi) [reply kolibri/plugins/facility/assets/src/views/users/sidePanels/UserCreate/ClassesSelect.vue:1]: @AlexVelezLl  I think this could be addressed from the KSelect by allowing the value prop accept either Array or Object. I have just made a fix to it on this PR.
https://github.com/learningequality/kolibri-design-system/pull/1150

Comment (AlexVelezLl) [reply kolibri/plugins/facility/assets/src/views/users/sidePanels/UserCreate/ClassesSelect.vue:1]: Hey @AllanOXDi. Yes! It seems that having KSelect support an array value should mute the error logs here; Jus commented on the PR a minor nitpick before merging the PR. However, the `selectedOption` change should be reverted here as well!

Comment (AllanOXDi) [reply kolibri/plugins/facility/assets/src/views/users/sidePanels/UserCreate/ClassesSelect.vue:1]: I think we could just close this PR after - once we fixed from KSelect itself

Comment (AlexVelezLl) [reply kolibri/plugins/facility/assets/src/views/users/sidePanels/UserCreate/ClassesSelect.vue:1]: I mean, we still have the addition of the missing return of the `showErrorWarning` ref 😄.

Comment (AllanOXDi) [reply kolibri/plugins/facility/assets/src/views/users/sidePanels/UserCreate/ClassesSelect.vue:1]: Resolved

**Review by AlexVelezLl — APPROVED** [review]
Thanks a lot @AllanOXDi!!
