### PR TITLE
Fix login and signup redirects

### LINKED ISSUE #7488: Users are not being redirected to desired page after authenticating
### Observed behavior

When trying to view a page like https://kolibri-beta.learningequality.org/en/device/#/permissions without being signed-in, you will see a page with a link to the sign-in page that also has this `redirect` parameter e.g.

https://kolibri-beta.learningequality.org/en/user/?redirect=https%3A%2F%2Fkolibri-beta.learningequality.org%2Fen%2Fdevice%2F%23%2Fpermissions#/signin

That `redirect` parameter is supposed to take you back to the page you wanted (e.g. the Permissions page). Instead it seems to take you to the default landing page for your user type (e.g. with a superuser account I end up on the Device > Channels page).

### Expected behavior

After signing in, I am taken to the page I wanted go to and see it (if I have permissions to see it).

### User-facing consequences

…

### Errors and logs

…

### Steps to reproduce

…

### Context

0.14.3

### PR DESCRIPTION
**Pull request by rtibbles**
### Summary
* Standardizes 'next' GET parameter for redirects
* Ensures that 'next' parameter is used for redirecting when signing up
* Ensures that 'next' parameter is persisted when the signup flow changes steps
* Ensures that the 'next' parameter is always passed into kolibriLogin action

### Reviewer guidance
- Access a page you are not authorized to view while not logged in
- Follow the AuthMessage link to login and ensure you return to the right page
- Sign up for an account with a `next` parameter set to an external site like `https://www.google.com`
- Ensure that after sign up you are redirected to the external site

### References
Fixes #7488

----

### Contributor Checklist

PR process:

- [ ] PR has the correct target branch and milestone
- [ ] PR has 'needs review' or 'work-in-progress' label
- [ ] If PR is ready for review, a reviewer has been added. (Don't use 'Assignees')
- [ ] If this is an important user-facing change, PR or related issue has a 'changelog' label
- [ ] If this includes an internal dependency change, a link to the diff is provided

Testing:

- [ ] Contributor has fully tested the PR manually
- [ ] If there are any front-end changes, before/after screenshots are included
- [ ] Critical user journeys are covered by Gherkin stories
- [ ] Critical and brittle code paths are covered by unit tests

### Reviewer Checklist

- Automated test coverage is satisfactory
- PR is fully functional
- PR has been tested for [accessibility regressions](http://kolibri-dev.readthedocs.io/en/develop/manual_testing.html#accessibility-a11y-testing)
- External dependency files were updated if necessary (`yarn` and `pip`)
- Documentation is updated
- Contributor is in AUTHORS.md

### CODE REVIEW

**Comment by jonboiser** [comment]
The URL is still getting rearranged: 

```
http://localhost:8000/en/user/?next=http%3A%2F%2Flocalhost%3A8000%2Fen%2Fdevice%2F%23%2Ffacilities#/signin
```

But the redirect works when e.g. trying to view `device > facilities` as a guest user.

File: kolibri/plugins/user/assets/src/views/SignInPage/index.vue [hunk 1]
```diff
@@ -503,11 +501,8 @@
           facility: this.selectedFacility.id,
         };
 
-        if (plugin_data.oidcProviderEnabled) {
+        if (this.nextParam) {
```
Comment (jonboiser) [inline kolibri/plugins/user/assets/src/views/SignInPage/index.vue:504]: How does work now with the `plugin_data.oidcProviderEnabled` flag removed? Does the plugin have code that will add the `?next` param?

Comment (rtibbles) [reply kolibri/plugins/user/assets/src/views/SignInPage/index.vue:504]: No, it just meant that the redirect would only work if the plugin was enabled.

As this is standardizing us on using `next` for all redirects, there's no need to conditionalize it any more.

**Review by jonboiser — APPROVED** [review]
Looks good! Tested the not-authenticated scenario + the new account scenario with `?next="https%3A%2F%2Fwww.google.com"`

**Comment by jredrejo** [comment]
Tested with OICD (between two different kolibri servers, one in the provider role and the other as client) and works fine

Peek 12-12-2020 18-21
