### PR TITLE
filter SoUD devices when scanning the network to import new facilities

### LINKED ISSUE #8276: Single user syncing - Getting a 403 error when attempting to Sync with a learner-only device as a Super admin
## Observed behavior
As a super admin I have the ability to manually sync facilities. However when I attempt to sync with a learner-only device I'm getting a 403 error without any explicit information what is going on.

## Expected behavior
The expected behavior is not clear and should be further discussed.

## Steps to reproduce the issue
1. Install this [build](https://buildkite.com/learningequality/kolibri-windows/builds/1586#97b40f19-5fb4-4cd7-888e-69531fedca75) on 2 devices, set up an admin device and import a learn-only device.
2. As a super admin go to Device>Facilities and click the Sync button next to your facility
3. Select the learner-only device and attempt to sync with it (note that syncing with a fully imported facility is functioning correctly)

## Logs
[logs.zip](https://github.com/learningequality/kolibri/files/6975925/logs.zip)

## Usage Details
 - OS: Windows 10, Ubuntu
 - Browser: Chrome

### PR DESCRIPTION
**Pull request by jredrejo**
## Summary
When a superuser tries to import new facilities, subsets of users devices should not be shown nor found in the list of available devices to look for new facilites

## References
Closes: #8276 

## Reviewer guidance
1.  Setup a subset of users device (a.k.a. learn only device) a
2. Setup another kolibri server, both in your network

Before this PR:

- superuser of the kolibri server will see the SoUD when scanning facilities to import

After this PR:

 - superuser of the kolibri server will NOT see the SoUD when scanning facilities to import

## Testing checklist

- [x] Contributor has fully tested the PR manually
- [ ] If there are any front-end changes, before/after screenshots are included
- [ ] Critical user journeys are covered by Gherkin stories
- [ ] Critical and brittle code paths are covered by unit tests

## PR process

- [x] PR has the correct target branch and milestone
- [x] PR has 'needs review' or 'work-in-progress' label
- [x] If PR is ready for review, a reviewer has been added. (Don't use 'Assignees')
- [ ] If this is an important user-facing change, PR or related issue has a 'changelog' label
- [ ] If this includes an internal dependency change, a link to the diff is provided

## Reviewer checklist

- Automated test coverage is satisfactory
- PR is fully functional
- PR has been tested for [accessibility regressions](http://kolibri-dev.readthedocs.io/en/develop/manual_testing.html#accessibility-a11y-testing)
- External dependency files were updated if necessary (`yarn` and `pip`)
- Documentation is updated
- Contributor is in AUTHORS.md

### CODE REVIEW

File: kolibri/core/assets/src/views/sync/SelectAddressModalGroup/api.js [hunk 1]
```diff
@@ -48,26 +48,28 @@ function fetchAddressesForLOD(LocationResource = NetworkLocationResource) {
 }
 
 function fetchAddressesWithChannel(withChannelId = '', LocationResource = NetworkLocationResource) {
-  return LocationResource.fetchCollection({ force: true }).then(locations => {
```
Comment (rtibbles) [inline kolibri/core/assets/src/views/sync/SelectAddressModalGroup/api.js]: Do we need to do this filtering for channel import? It's only facility syncing that is problematic here.

File: kolibri/core/discovery/api.py [hunk 2]
```diff
@@ -16,6 +16,16 @@ class NetworkLocationViewSet(viewsets.ModelViewSet):
     serializer_class = NetworkLocationSerializer
     queryset = NetworkLocation.objects.all()
 
+    def filter_queryset(self, queryset):
```
Comment (rtibbles) [inline kolibri/core/discovery/api.py]: Could also use a FilterSet here with just `subset_of_users_device` as the only field.

**Review by rtibbles — COMMENTED** [review]
A couple of questions.

File: kolibri/core/assets/src/views/sync/SelectAddressModalGroup/api.js (hunk 1 above)
Comment (jredrejo) [reply kolibri/core/assets/src/views/sync/SelectAddressModalGroup/api.js]: I thought we would prefer  not to use them for any sync work, but if you think it's fine to import from them, no problem. I've removed it

File: kolibri/core/discovery/api.py (hunk 2 above)
Comment (jredrejo) [reply kolibri/core/discovery/api.py]: oh, I should have thought of that, much simpler, of course. Done

File: kolibri/core/assets/src/views/sync/SelectAddressModalGroup/api.js (hunk 1 above)
Comment (rtibbles) [reply kolibri/core/assets/src/views/sync/SelectAddressModalGroup/api.js]: Yeah, I just think of situations where there are only other SoUD devices on a network but you still want to get content peer to peer.

File: kolibri/core/discovery/api.py [hunk 3]
```diff
@@ -15,6 +16,10 @@ class NetworkLocationViewSet(viewsets.ModelViewSet):
     permission_classes = [NetworkLocationPermissions | NotProvisionedHasPermission]
     serializer_class = NetworkLocationSerializer
     queryset = NetworkLocation.objects.all()
+    filter_backends = [DjangoFilterBackend]
+    filterset_fields = [
```
Comment (rtibbles) [inline kolibri/core/discovery/api.py:20]: And I had forgotten that for fields only filtering you can just do this instead of even defining a `FilterSet`!

**Review by rtibbles — APPROVED** [review]
