### PR TITLE
Fix pagination user tables

### LINKED ISSUE #9448: Learners not available to enroll in the class
## Observed behavior
Encountered while testing #9446, according to @rtibbles most probably a regression from the recent pagination work.

Facility has 3 new learners, but none seem available to be enrolled in the class:

enroll-issue

## Errors and logs
…

## Expected behavior
Visible list of learners to enroll.

## User-facing consequences
…

## Steps to reproduce
Create learner(s) and try to enroll them in a class.

## Context
 * Kolibri version: 0.15.x branch, EXE asset from #9446  
 * Operating system: Windows 10
 * Browser: all

### PR DESCRIPTION
**Pull request by marcellamaki**
## Summary
Updates `handler.js` for the class enrollment user management, and simplifies the vue components to better match the updates in the FacilityUsers page. Now learners should be accurately displaying in the user table for enrollment in a class.

## References
Fixes #9448
learners

## Reviewer guidance

Is the pagination working as expected with > 30 users? 

Also... am I supposed to be filtering out anyone not exclusively a learner? Truly cannot remember.... I think coaches and admins can still be added to classes

----

## Testing checklist

- [ ] Contributor has fully tested the PR manually
- [ ] If there are any front-end changes, before/after screenshots are included
- [ ] Critical user journeys are covered by Gherkin stories
- [ ] Critical and brittle code paths are covered by unit tests

## PR process

- [ ] PR has the correct target branch and milestone
- [ ] PR has 'needs review' or 'work-in-progress' label
- [ ] If PR is ready for review, a reviewer has been added. (Don't use 'Assignees')
- [ ] If this is an important user-facing change, PR or related issue has a 'changelog' label
- [ ] If this includes an internal dependency change, a link to the diff is provided

## Reviewer checklist

- Automated test coverage is satisfactory
- PR is fully functional
- PR has been tested for [accessibility regressions](http://kolibri-dev.readthedocs.io/en/develop/manual_testing.html#accessibility-a11y-testing)
- External dependency files were updated if necessary (`yarn` and `pip`)
- Documentation is updated
- Contributor is in AUTHORS.md

### CODE REVIEW

File: kolibri/plugins/facility/assets/src/modules/classAssignMembers/handlers.js [hunk 1]
```diff
@@ -34,7 +33,7 @@ export function showLearnerClassEnrollmentPage(store, toRoute) {
     ([facilityUsers, classroom, classUsers]) => {
       store.commit('classAssignMembers/SET_STATE', {
         facilityUsers: facilityUsers.results.map(_userState),
-        classUsers: classUsers.results.map(_userState),
+        classUsers: classUsers.results,
```
Comment (rtibbles) [inline kolibri/plugins/facility/assets/src/modules/classAssignMembers/handlers.js]: Without pagination parameters passed to the fetchCollection, I think `classUsers` will just be the results directly, rather than having a results attribute?

Also, why are we removing the userState mapping?

**Review by rtibbles — COMMENTED** [review]
Seems to make sense from an initial read through - one question though.

File: kolibri/plugins/facility/assets/src/modules/classAssignMembers/handlers.js (hunk 1 above)
Comment (marcellamaki) [reply kolibri/plugins/facility/assets/src/modules/classAssignMembers/handlers.js]: I don't really know why... originally I had both the pagination parameters and the userState, to follow the same pattern, and I kept getting a 404 error that said ID: NOT FOUND. Removing both was the only way that the results were the correct array.

**Comment by radinamatic** [comment]
30< Learners are back! 🥳 

Tested on Chrome & Firefox on Windows 10



And yes, filtering is only in play when assigning coaches, anybody can be a learner 🙂

**Review by radinamatic — APPROVED** [review]
LGTM! 👍🏽 :shipit:

File: kolibri/plugins/facility/assets/src/modules/classAssignMembers/handlers.js (hunk 1 above)
Comment (rtibbles) [reply kolibri/plugins/facility/assets/src/modules/classAssignMembers/handlers.js]: Soo..... the reason this doesn't matter is that we are already excluding non-class members from the original fetch, so there is no reason to even do this fetch any more, it's dead code.

**Review by rtibbles — APPROVED** [review]

**Comment by radinamatic** [comment]
Re-tested on Win 10 after the last commits by @rtibbles, 30< learner pagination still looking good, let's merge for the bugbash tomorrow!
