### PR TITLE
Fixes the deletion of super admin by admin user.

### LINKED ISSUE #13635: Users table - Improve UX when a selected user cannot be deleted
❌ **This issue is not open for contribution. Visit <a href="https://learningequality.org/contributing-to-our-open-code-base/" target="_blank">Contributing guidelines</a>** to learn about the contributing process and how to find suitable issues.

1. A user of type 'admin' is able to delete a user of type 'super admin'. This is probably caused by some other changes and should be reported separately?

https://github.com/user-attachments/assets/a8cae150-66cd-4dcf-90c9-313c7d6a0b00

2. When I am at 'New users' the 'Delete selection' button is enabled, along with the other buttons. Is it in scope of this PR for this button to be disabled here the same as it is at the 'Users' table?

https://github.com/user-attachments/assets/0df34445-7d73-4c6e-a601-9a67ca6378b0

5. If I have selected multiple users for removal and one of the selected users is the one that I am currently signed in with then the 'Delete selection' icon remains disabled and it's not clear at all why it's disabled.

_Originally posted by @pcenov in https://github.com/learningequality/kolibri/issues/13600#issuecomment-3168146095_

### PR DESCRIPTION
**Pull request by AllanOXDi**
## Summary
This Pr fixes several usability and consistency issues related to the user management page. where user of type 'admin' is able to delete a user of type 'super admin' and the new user page  the 'Delete selection' button is enabled, along with the other buttons
## References
Fixes  #13635

## Reviewer guidance
 Navigate to user management page > Select one or more users. As an Admin or Superuser, select yourself along with other users. or log in as admin and try to delete super admin.
 Try creating new user and perform the same action above

### CODE REVIEW

**Comment by pcenov** [comment]
Hi @AllanOXDi - LGTM, the only issue I noticed is with the tooltip of the "Remove selected users" icon which now reads `function() {[native code]}` - but if that is not caused by changes made here then all is good.

File: packages/kolibri-common/strings/bulkUserManagementStrings.js [hunk 1]
```diff
@@ -127,6 +127,11 @@ export const bulkUserManagementStrings = createTranslator('BulkUserManagementStr
     message: 'Remove selected users',
     context: 'Label for bulk-action button that will allow user to delete selected users',
   },
+  canNotdeletSelfTooltip: {
+    message: 'You cannot delete your self.',
```
Comment (nucleogenesis) [inline packages/kolibri-common/strings/bulkUserManagementStrings.js]: "your self" should be "yourself" here

File: packages/kolibri-common/strings/bulkUserManagementStrings.js [hunk 2]
```diff
@@ -127,6 +127,11 @@ export const bulkUserManagementStrings = createTranslator('BulkUserManagementStr
     message: 'Remove selected users',
     context: 'Label for bulk-action button that will allow user to delete selected users',
   },
+  canNotdeletSelfTooltip: {
```
Comment (nucleogenesis) [inline packages/kolibri-common/strings/bulkUserManagementStrings.js]: Update this to `cannotDeleteSelfTooltip` for readability please

File: kolibri/plugins/facility/assets/src/views/users/UsersRootPage/index.vue [hunk 3]
```diff
@@ -263,6 +289,12 @@
           });
         }
       },
+      deleteSelectionTooltip() {
```
Comment (nucleogenesis) [inline kolibri/plugins/facility/assets/src/views/users/UsersRootPage/index.vue]: This should move to `computed` - this is what's causing the issue @pcenov noted

File: kolibri/plugins/facility/assets/src/views/users/NewUsersPage.vue [hunk 4]
```diff
@@ -216,8 +224,68 @@
...
+      },
+      hasSelectedSuperusers() {
+        if (!this.hasSelectedUsers || !this.facilityUsers) return false;
+
+        return this.facilityUsers
+          .filter(user => this.selectedUsers.has(user.id))
+          .some(user => {
+            const isSuperuser =
+              user.kind === UserKinds.SUPERUSER ||
+              user.kind === 'superuser' ||
```
Comment (nucleogenesis) [inline kolibri/plugins/facility/assets/src/views/users/NewUsersPage.vue]: Did you run into an issue that a `user.kind` could be something other than the value of `UserKinds.SUPERUSER`?

**Review by nucleogenesis — DISMISSED** [review]
I think I see what caused Peter's reported issue and noted a couple typos. 

Code looks good overall - the way you laid out the boolean computed properties reads really well!

**Review by nucleogenesis — COMMENTED** [review]
Code changes look good to me & my feedback has been addressed. @pcenov can you give this another spin?

**Review by pcenov — APPROVED** [review]
LGTM now!
