### PR TITLE
Restart zeroconf after setup

### LINKED ISSUE #8344: Provisioning learn-only device in setup wizard doesn't resync until restart
## Observed behavior

1. Start a fresh instance of Kolibri
2. Go through the Advanced setup wizard, selecting "learn-only" device
3. Authenticate with the remote server using the learner credentials
4. Finish setup
5. Observe the Kolibri instance does not resync with the server
6. Restart Kolibri
7. Observe the Kolibri instance does resync with the server

## Errors and logs

N/A

## Expected behavior

Kolibri always makes recurring requests to sync with the server when provisioned as a SoUD

## User-facing consequences

Broken expectation that SoUD make recurring syncs with the server

## Context

Latest Kolibri `release-v0.15.x`
Ubuntu 20.04
Chrome

### PR DESCRIPTION
**Pull request by jredrejo**
## Summary

Create a new endpoint + an api resource to restart zerconf when the setup wizard ends after syncing one or more users in a SoUD

## References
Closes: #8344 
Depends on #8367 been merged

## Reviewer guidance
Create a new Kolibri device provisioning it importing users from another device.
Before this PR users were not synced unless the server is restarted. After this pr, syncing processes will start as soon as the setup is finished

## Testing checklist

- [x] Contributor has fully tested the PR manually
- [ ] If there are any front-end changes, before/after screenshots are included
- [ ] Critical user journeys are covered by Gherkin stories
- [ ] Critical and brittle code paths are covered by unit tests

## PR process

- [x] PR has the correct target branch and milestone
- [x] PR has 'needs review' or 'work-in-progress' label
- [ ] If PR is ready for review, a reviewer has been added. (Don't use 'Assignees')
- [ ] If this is an important user-facing change, PR or related issue has a 'changelog' label
- [ ] If this includes an internal dependency change, a link to the diff is provided

## Reviewer checklist

- Automated test coverage is satisfactory
- PR is fully functional
- PR has been tested for [accessibility regressions](http://kolibri-dev.readthedocs.io/en/develop/manual_testing.html#accessibility-a11y-testing)
- External dependency files were updated if necessary (`yarn` and `pip`)
- Documentation is updated
- Contributor is in AUTHORS.md

### CODE REVIEW

**Comment by indirectlylit** [comment]
will test once #8367 is resolved

File: kolibri/plugins/setup_wizard/assets/src/api.js [hunk 1]
```diff
@@ -58,3 +60,16 @@ export const SetupSoUDTasksResource = new Resource({
...
+
+export const FinishSoUDSyncingResource = new Resource({
+  name: 'restartzeroconf',
+  namespace: 'kolibri.plugins.setup_wizard',
+  finish() {
+    const welcomeDimissalKey = 'DEVICE_WELCOME_MODAL_DISMISSED';
+    const device_url = urls['kolibri:kolibri.plugins.device:device_management'];
+    window.sessionStorage.setItem(welcomeDimissalKey, false);
+    this.postListEndpoint('restart');
+    redirectBrowser(device_url());
```
Comment (rtibbles) [inline kolibri/plugins/setup_wizard/assets/src/api.js]: In case `device_url` is `undefined`, we should change this to:
```suggestion
    redirectBrowser(device_url ? device_url(): null);
```

Comment (jredrejo) [reply kolibri/plugins/setup_wizard/assets/src/api.js]: @rtibbles  maybe this is a naive question, but how could `device_url` be null? are there any case where we are not loading the `device` plugin?

Comment (rtibbles) [reply kolibri/plugins/setup_wizard/assets/src/api.js]: If a user has disabled the device plugin then this would be null. In general, I have preferred to enforce any coupling between our plugins to be loose, so that one does not cause errors because another is disabled.

Comment (jredrejo) [reply kolibri/plugins/setup_wizard/assets/src/api.js]: ok, I never thought this would be an use case but, as usual, you're right. Done.

But... another naive question, shouldn't we add this guard to https://github.com/learningequality/kolibri/blob/release-v0.15.x/kolibri/core/assets/src/core-app/urls.js#L14 ? or making it fail is being used in the code?

Comment (rtibbles) [reply kolibri/plugins/setup_wizard/assets/src/api.js]: I would like to add a guard that just returned a function for every URL, so that we could always invoke the function, and just return defined in that case, but the best way to achieve that would be with an [ES6 Proxy](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Proxy) object, which is not available on IE11 and not polyfillable.

The function you are pointing to there is only used by the URL functions defined in our Javascript, rather than the JS generated by Django-js-reverse (we could in theory hack that template to do this, but it felt like a lot of work!).

File: kolibri/plugins/setup_wizard/api.py [hunk 2]
```diff
@@ -173,3 +173,26 @@ class SetupWizardSoUDTaskView(TasksViewSet):
...
+    """
+    An utility endpoint to restart zeroconf after setup is finished
+    in case this is a SoUD
+    """
+
+    permission_classes = [HasPermissionDuringSetup | HasPermissionDuringLODSetup]
+
+    @decorators.action(methods=["post"], detail=False)
+    def restart(self, request):
+        import logging
```
Comment (rtibbles) [inline kolibri/plugins/setup_wizard/api.py:188]: Any reason not to do these imports and logging configuration in module scope?

**Review by rtibbles — COMMENTED** [review]
The code changes here look good, one query, but nothing that blocks merging.

Have not tested manually.

File: kolibri/plugins/setup_wizard/api.py (hunk 2 above)
Comment (jredrejo) [reply kolibri/plugins/setup_wizard/api.py:188]: just to avoid doing the import if the wizard does the other two kinds of setup instead of the SoUD provisioning

**Review by indirectlylit — APPROVED** [review]
confirmed that after this change, the devices begin auto-syncing after import
