### PR TITLE
Setup Wizard UX and Bug Fixes (wrong facility preset, "stuck" import tasks, saving superuser credentials)

### LINKED ISSUE #7303: Setup Wizard -> Personal -- Creates the facility as "nonformal" - should be "informal"
### Observed behavior

I created a new KOLIBRI_HOME and went through the setup wizard and selected "Personal" to test the Sign In Page work I'm doing for the Personal version.

When I got through with the Setup Wizard, it was created as `nonformal` rather than `informal`. I checked in Vuex and the database and it was created incorrectly.

### Expected behavior

In Setup Wizard:

Personal -> creates an `informal` facility
Advanced -> gives user the option to create a `formal` or `nonformal` facility

### User-facing consequences

Features we have for "Personal" devices/facilities will not be displayed properly.

### Context

0.14-beta9
Debian 10
Chrome

### PR DESCRIPTION
**Pull request by jonboiser**
### Summary

Some updates to the Setup Wizard

1. Fixes faulty polling logic when displaying FacilityImport task progress
1. "remembers" the the super user/admin credentials provided at the beginning of the facility import flow at the end when creating a device super admin. 
1. Fixes a bug where the `facility.dataset.preset` value was not being saved. Fixed in REST and CLI interfaces for device provisioning

### Reviewer guidance

1. Is it still possible to get "stuck" in the facility import step?
1. Once a device is provisioned, does the UI reflect the preset + settings you chose?
1. Is it possible to put the Device Superadmin credentials step in a bad state in terms of the "remembered" credentials from the previous step (providing facility/superuser credentials prior to importing from a peer)

### References

Fixes #7303 

### Contributor Checklist

PR process:

- [x] PR has the correct target branch and milestone
- [x] PR has 'needs review' or 'work-in-progress' label
- [x] If PR is ready for review, a reviewer has been added. (Don't use 'Assignees')
- [ ] If this is an important user-facing change, PR or related issue has a 'changelog' label
- [ ] If this includes an internal dependency change, a link to the diff is provided

Testing:

- [ ] Contributor has fully tested the PR manually
- [ ] If there are any front-end changes, before/after screenshots are included
- [ ] Critical user journeys are covered by Gherkin stories
- [ ] Critical and brittle code paths are covered by unit tests

### Reviewer Checklist

- Automated test coverage is satisfactory
- PR is fully functional
- PR has been tested for [accessibility regressions](http://kolibri-dev.readthedocs.io/en/develop/manual_testing.html#accessibility-a11y-testing)
- External dependency files were updated if necessary (`yarn` and `pip`)
- Documentation is updated
- Contributor is in AUTHORS.md

### CODE REVIEW

File: kolibri/plugins/setup_wizard/assets/src/views/importFacility/LoadingTaskPage.vue [hunk 1]
```diff
@@ -74,21 +74,18 @@
...
     methods: {
-      startPolling() {
+      pollTask() {
         SetupTasksResource.fetchCollection({ force: true }).then(tasks => {
           this.loadingTask = {
             ...tasks[0],
             facility_name: this.facilityName,
           };
         });
-        if (this.loadingTask.status) {
```
Comment (jonboiser) [inline kolibri/plugins/setup_wizard/assets/src/views/importFacility/LoadingTaskPage.vue:87]: This was the wrong condition, it should have said something like "If status is completed/canceled/failed". Just removing it here, and letting this page poll the endpoint unconditionally.

File: kolibri/plugins/setup_wizard/assets/src/views/importFacility/SelectFacilityForm.vue [hunk 2]
```diff
@@ -143,7 +143,12 @@
         const $credentialsForm = this.$refs.credentialsForm;
         if ($credentialsForm) {
           // The form makes the call to the startpeerfacilityimport endpoint
-          return $credentialsForm.startImport();
+          return $credentialsForm.startImport().then(() => {
```
Comment (nucleogenesis) [inline kolibri/plugins/setup_wizard/assets/src/views/importFacility/SelectFacilityForm.vue]: At this point `POST http://localhost:8000/api/tasks/facilitytasks/startpeerfacilityimport/` returns 401 when I pass bad credentials:

`{"detail":"401 Client Error: Unauthorized for url: https://kolibri-beta.learningequality.org/api/morango/v1/certificates/"}`

Then it just gets stuck and I have to refresh the page.

screenshot-localhost_8000-2020 07 21-12_13_33

File: kolibri/plugins/setup_wizard/assets/src/views/importFacility/SelectSuperAdminAccountForm.vue [hunk 3]
```diff
@@ -138,6 +145,9 @@
         this.shouldValidate = false;
         if (this.$refs.password) {
           this.$refs.password.resetAndFocus();
+          if (this.selected.label === this.facility.username) {
```
Comment (nucleogenesis) [inline kolibri/plugins/setup_wizard/assets/src/views/importFacility/SelectSuperAdminAccountForm.vue]: I'm guessing that this is whereabouts this issue would be found in the code.

I get here and the username is defaulted to the username I used in the first place (`learningequality`) to start import and the password was autofilled.

If I go from `learningequality` (I'm testing using the beta server) to `micah` and then go back to `learningequality` - the password field is still filled with the `learningequality` password.

But - if you go:

`learningequality` -> `Create new super admin` -> `learningequality` --- then the password is no longer filled out. If I then go from there to `micah` and back to `learningequality` then the password is filled again.

Seems that this `resetFormAndRefocus()` method isn't being called whenever you switch away from the Create a new super admin form.

**Review by nucleogenesis — CHANGES_REQUESTED** [review]
A few bugs are noted in comments elsewhere and here are a couple more I found:

---

There is a weird bug in the general flow in that a user can create multiple facilities within the Setup Wizard and never even know that's what they're doing.

Definitely an edge case but it isn't hard to run into it:

- Import a facility in the Advanced Setup.
- Get to the page for "sign in as super admin" of the setup wizard.
- Refresh your page, close your browser tab by mistake, etc... you start from the beginning of the Setup Wizard now.
- Go back through and import the same facility - or a new one - and it will be imported as well!

If I'm redirected to "Step 1" of Setup Wizard I (as a user) assume that I am starting from scratch. 

Also, once you get through importing your additional facilit(y/ies) through the setup wizard and log in as the super admin properly - the last page (Responsibilities...) doesn't work when you click "Next".

```
500 ERROR:
MultipleObjectsReturned at /setup_wizard/api/facilityimport/provisiondevice/
get() returned more than one Facility -- it returned 2!

Request Method: POST
Request URL: http://localhost:8000/setup_wizard/api/facilityimport/provisiondevice/
```

---

You are unable to click the "Cancel" button during import for the import task. If this is intentional, I'd suggest hiding it.

---

I also was not able to use my browser's back button once I got to the "Enter super admin credentials" after importing. 

I don't like the idea of hijacking someone's expected browser functionality. I think that if we don't want someone to be able to click back then we should hit them with a browser confirm dialog saying whatever bad things might happen.

Ideally, they won't have bad things happen if they click it, though. They should basically just be taken to the previous meaningful step where they can make a decision about how to setup their device.

This may involve, to some degree, caching or otherwise not committing imported data to the DB until the whole process is completed - finding an alternative to this may also help avoid the issue I listed at the top of this comment.

Not sure what of the above fits into the scope of this PR or our expectations for 0.14, but if they cannot be addressed now let me know and I'll make some Github issues for them.

File: kolibri/plugins/setup_wizard/assets/src/views/importFacility/SelectFacilityForm.vue (hunk 2 above)
Comment (jonboiser) [reply kolibri/plugins/setup_wizard/assets/src/views/importFacility/SelectFacilityForm.vue]: Cool, I found what was causing this 👍

**Comment by jonboiser** [comment]
@nucleogenesis I made this issue #7333  to capture your larger comment. I think it's an okay defect to have for now because it's pretty edge-casey plus easy to undo using the new facility management functionality.

> You are unable to click the "Cancel" button during import for the import task. If this is intentional, I'd suggest hiding it.

This one I'm not sure about. The "cancel" button should be triggering a cancel task API call. In my experience the import happens too fast that either it finishes or passes the point of no return before I click it.

**Comment by jonboiser** [comment]
@nucleogenesis I added fixes for

1. Handling bad credentials at the pre-import authorization step
1. Handling the transition between "create new..." and the saved admin credentials
