### PR TITLE
Fix: Show search & setting buttons at channel level in quiz resource selection

### LINKED ISSUE #13144: Ensure that the search and questions setting buttons are available at channel level
## Observed behavior
There is no way to search, change question settings, or see how many questions you can add at the channel level in quizzes if there are no bookmarks

## Expected behavior
Users should be able to update their question settings, and initiate a search, at the channel level

## Errors and logs

Image

### PR DESCRIPTION
**Pull request by nucleogenesis**
## Summary

Uses `QuizResourceSelectionHeader` on the resource selection side panel's index (aka channels listing page) to display the filters & search buttons. 

## References

Fixes #13144 

## Reviewer guidance

You should see Settings & Search filters at the top of the page listing the channels. They should work as expected.

### CODE REVIEW

**Comment by pcenov** [comment]
Hi @nucleogenesis - could you have a look while the build assets are not generated?

**Comment by radinamatic** [comment]
Re-run triggered, should be good to go now ([only APK is still building](https://github.com/learningequality/kolibri/actions/runs/13823380688?pr=13198)) @pcenov 🙂

**Comment by pcenov** [comment]
Hi @nucleogenesis - unfortunately now if I have bookmarked resources then the "Settings" and "Search" buttons are duplicated:

double

File: kolibri/plugins/coach/assets/src/views/quizzes/CreateExamPage/sidePanels/QuizResourceSelection/index.vue [hunk 1]
```diff
@@ -19,6 +19,25 @@
       </div>
     </template>
     <template #default="{ isScrolled }">
+      <QuizResourceSelectionHeader
```
Comment (AlexVelezLl) [inline kolibri/plugins/coach/assets/src/views/quizzes/CreateExamPage/sidePanels/QuizResourceSelection/index.vue]: Hi @nucleogenesis! I think this should be solved in the context of the [SelectionIndex](https://github.com/nucleogenesis/kolibri/blob/140cd1c6b7f702cd4d6538a9d002217630dec835/kolibri/plugins/coach/assets/src/views/common/resourceSelection/subPages/SelectionIndex.vue#L7) component, there we already have the buttons and the search button handler, the only thing is that we dont show them when bookmarksCount === 0.

Adding this here makes that when we have bookmarks we see these buttons duplicated

image

And this issue also happens with lessons too, so it should be fixed there too. Fixing this in the SelectionIndex component should fix it for both of them because we use this component for lessons and quizzes :open_hands: .

**Review by AlexVelezLl — CHANGES_REQUESTED** [review]

File: kolibri/plugins/coach/assets/src/views/quizzes/CreateExamPage/sidePanels/QuizResourceSelection/index.vue (hunk 1 above)
Comment (AlexVelezLl) [reply kolibri/plugins/coach/assets/src/views/quizzes/CreateExamPage/sidePanels/QuizResourceSelection/index.vue]: Whoops, seems like @pcenov and I were reviewing it at the same time :laughing:

Comment (pcenov) [reply kolibri/plugins/coach/assets/src/views/quizzes/CreateExamPage/sidePanels/QuizResourceSelection/index.vue]: We are doubling down on everything! 😄

Comment (nucleogenesis) [reply kolibri/plugins/coach/assets/src/views/quizzes/CreateExamPage/sidePanels/QuizResourceSelection/index.vue]: Thanks both!

**Comment by nucleogenesis** [comment]
@pcenov @AlexVelezLl 

I fixed a small bug I caused in #13060 and also have found a much simpler solution to the issue.

Please test both Lesson & Quiz selection, with and without having a bookmark.

File: kolibri/plugins/coach/assets/src/views/common/resourceSelection/subPages/SelectionIndex.vue [hunk 2]
```diff
@@ -1,6 +1,12 @@
 <template>
 
   <div>
+    <QuizResourceSelectionHeader
+      v-if="target === SelectionTarget.QUIZ && !settings.selectPracticeQuiz"
+      class="mb-24"
+      :settings="settings"
+      @searchClick="onSearchClick"
+    />
     <div
```
Comment (AlexVelezLl) [inline kolibri/plugins/coach/assets/src/views/common/resourceSelection/subPages/SelectionIndex.vue:12]: We will also need to take out these headers to fix it in lessons and for practice quizzes too :open_hands:

https://github.com/nucleogenesis/kolibri/blob/d497f89cec0ebf7776ba4b5d32ebc403885314bd/kolibri/plugins/coach/assets/src/views/common/resourceSelection/subPages/SelectionIndex.vue#L14-L37

And I guess in lessons we should render this string conditionally only if we have bookmarks https://github.com/nucleogenesis/kolibri/blob/d497f89cec0ebf7776ba4b5d32ebc403885314bd/kolibri/plugins/coach/assets/src/views/common/resourceSelection/subPages/SelectionIndex.vue#L19

Comment (nucleogenesis) [reply kolibri/plugins/coach/assets/src/views/common/resourceSelection/subPages/SelectionIndex.vue:12]: @AlexVelezLl just pushed a fix for these two, thanks a ton Alex!

**Comment by nucleogenesis** [comment]
@pcenov @AlexVelezLl this should be ready for re-review if the checks pass

**Comment by pcenov** [comment]
Hi @nucleogenesis - if I don't have any bookmarks then when I try to select a practice quiz the "Search" button is missing:

https://github.com/user-attachments/assets/9421a517-e84e-4a5c-ab36-82574bdb5584

The rest is looking good!

**Review by AlexVelezLl — APPROVED** [review]
Code changes looks good to me :)

**Comment by rtibbles** [comment]
@pcenov if you can confirm the final fix here, that would be great!

**Review by pcenov — APPROVED** [review]
LGTM now! Thanks Jacob!
