### PR TITLE
LessonResourceSelection: Add margin to bottom controls when isAppContext & touch device

### LINKED ISSUE #13172: Manage lesson resources - The "Save & finish" is not displayed in the Android app
## Observed behavior

In the Android app the "Save & finish" is not displayed in both horizontal and portrait mode:

android

## Expected behavior

The "Save & finish" button should be visible

## Steps to reproduce the issue

1. Install the  build from https://github.com/learningequality/kolibri/pull/13167
2. Navigate to Class > Lessons > Lesson and click "Manage resources" and attempt to add new resources to the lesson.

## Usage Details
Windows 11, Ubuntu 22  - Chrome, Firefox

### PR DESCRIPTION
**Pull request by nucleogenesis**
## Summary

Ensures Save & Finish is visible on Android by adding padding when isAppContext and isTouchDevice (aka, when the BottomNavigationBar is present).

From the commit message:

> In Quiz this is not necessary because QuizCreation is in its own immersive page when the user is selecting resources, so the BottomNavigationBar is not present. However, in Lessons, the base Lesson page is not an immersive page, so the app-mode-specific menu is still visible, causing the side panel's bottom controls to be hidden behind the menu. Rather than fiddling w/ z-indexes or trying to conditionally hide that menu, this just puts the Save & Finish button in a visible place

## References

Fixes #13172 

## Reviewer guidance

In the app context, can you see Save & Finish in lesson resource selection? Can you view all resources in the cards list during:

- Channel resource navigation
- Bookmarks
- Search results (incl View More btn)

Additionally, does it look correct in _not_ app context?

### CODE REVIEW

File: kolibri/plugins/coach/assets/src/views/lessons/LessonSummaryPage/sidePanels/LessonResourceSelection/index.vue [hunk 1]
```diff
@@ -54,7 +54,12 @@
       v-if="$route.name !== PageNames.LESSON_SELECT_RESOURCES_SEARCH"
       #bottomNavigation
     >
-      <div class="bottom-nav-container">
+      <div
+        class="bottom-nav-container"
+        :style="{
+          marginBottom: isAppContextAndTouchDevice ? '56px' : '0px',
```
Comment (AlexVelezLl) [inline kolibri/plugins/coach/assets/src/views/lessons/LessonSummaryPage/sidePanels/LessonResourceSelection/index.vue:60]: Defenitely non blocking, and speaking from ignorance, could this condition to render the botton menu change, for any reason, in the future? If so, I think remember to update also this specific component in this specific context will be a little hard. Just wondering if should we have something like a `showAppNavView` variable inside the `useUser` perhaps? To control the exact conditions to render the app nav, and replace them in the [AppBarPage](https://github.com/AlexVelezLl/kolibri/blob/c19e4d547c4198b405e7cc6449fb22af7b9a9dca/packages/kolibri/components/pages/AppBarPage/index.vue#L135) too, and ensuring that if they change in the future, all places that depends on it will be updated accordingly.

If this condition is something we dont foresee can change, and this is over-engineering :sweat_smile:, i think its okay then.

**Review by AlexVelezLl — APPROVED** [review]
Code-wise looks good to me! Just a little question

File: kolibri/plugins/coach/assets/src/views/lessons/LessonSummaryPage/sidePanels/LessonResourceSelection/index.vue (hunk 1 above)
Comment (nucleogenesis) [reply kolibri/plugins/coach/assets/src/views/lessons/LessonSummaryPage/sidePanels/LessonResourceSelection/index.vue:60]: Having it available in useUser would be nice to have - I think it'd be useful in a few others places too. I think it might be a good follow-up tech-debt issue to consolidate the conditionals that ask "is app context && is touch device" into useUser, then update wherever we're using it to get that info from useUser.

Comment (AlexVelezLl) [reply kolibri/plugins/coach/assets/src/views/lessons/LessonSummaryPage/sidePanels/LessonResourceSelection/index.vue:60]: Sounds good! <3

Comment (rtibbles) [reply kolibri/plugins/coach/assets/src/views/lessons/LessonSummaryPage/sidePanels/LessonResourceSelection/index.vue:60]: I think I'd probably prefer it to be somewhere other than `useUser` (even if it depends on useUser) as it's not about the _user_ per se - and yes, we had a similar concern when this was first implemented, so doing something to consolidate it would be helpful.

**Comment by radinamatic** [comment]
APK asset tested on Android 12 phone: `Save & Finish` button is fully visible, together with all resources in the cards while navigating channels, bookmarks and search results (including the `View more` button) for lesson resource management.
 
Channel browse | Bookmarks browse | Search result browse
-- | -- | --
 |  | 

Resource cards in this view could definitely benefit from a different, smaller format, but that's a topic for another PR.

Let's wait for @pcenov to confirm the fix in the non-app context, and we can approve and merge! 👍🏽

**Review by pcenov — APPROVED** [review]
LGTM as well!
