### PR TITLE
Simplify i18n download paths

### LINKED ISSUE #8245: Backend strings not in the expected folder when running 'make i18n-upload' command
## Observed behavior

Branch: `release-v0.15.x`
Running `make i18n-upload...` command extracts all front- and back-end strings, but the `django.po` file is not being uploaded to Crowdin. 
cc @rtibbles 

## Errors and logs
…

## Expected behavior
`django.po` should be available on Crowdin for translation

## User-facing consequences
…

## Steps to reproduce
…

## Context
 * Kolibri version `release-v0.15.x`
 * Operating system -
 * Browser -

### PR DESCRIPTION
**Pull request by rtibbles**
## Summary
* Removes the creation of separate crowdin language coded folders at download
* Downloads all files to a temporary directory and then immediately copies all files to the relevant Django locale dir
* Adds CSV files in the locale dir to the git ignore to prevent them being committed
* Updates all JS utilities to read from locale dirs

## References
Fixes #8245 

## Reviewer guidance
Does downloading strings and then:
a) Making message files
b) Syncing context

All work?

----

## Testing checklist

- [x] Contributor has fully tested the PR manually
- [ ] If there are any front-end changes, before/after screenshots are included
- [ ] Critical user journeys are covered by Gherkin stories
- [ ] Critical and brittle code paths are covered by unit tests

## PR process

- [x] PR has the correct target branch and milestone
- [x] PR has 'needs review' or 'work-in-progress' label
- [x] If PR is ready for review, a reviewer has been added. (Don't use 'Assignees')
- [ ] If this is an important user-facing change, PR or related issue has a 'changelog' label
- [ ] If this includes an internal dependency change, a link to the diff is provided

## Reviewer checklist

- Automated test coverage is satisfactory
- PR is fully functional
- PR has been tested for [accessibility regressions](http://kolibri-dev.readthedocs.io/en/develop/manual_testing.html#accessibility-a11y-testing)
- External dependency files were updated if necessary (`yarn` and `pip`)
- Documentation is updated
- Contributor is in AUTHORS.md

### CODE REVIEW

File: packages/kolibri-tools/lib/i18n/utils.js [hunk 1]
```diff
@@ -16,8 +16,13 @@ function writeSourceToFile(filePath, fileSource) {
 
 // Compile all of the defined strings & context from the CSVs that have been downloaded
 // from Crowdin.
-function parseCSVDefinitions(dir, subDir = '**') {
-  return glob.sync(path.join(dir, 'CSV_FILES', subDir, '*.csv')).reduce((acc, filePath) => {
+function parseCSVDefinitions(dir, intlLangCode) {
```
Comment (indirectlylit) [inline packages/kolibri-tools/lib/i18n/utils.js]: if `intlLangCode` is optional, maybe set default to `null`

```suggestion
function parseCSVDefinitions(dir, intlLangCode = null) {
```

File: packages/kolibri-tools/lib/i18n/crowdin.py [hunk 2]
```diff
@@ -301,32 +295,34 @@ def download_translations(branch, project, key, login, locale_data_folder):
...
-    # delete previous files
-    _wipe_translations(locale_data_folder)
-
     DOWNLOAD_URL = CROWDIN_API_URL.format(
         proj=project,
         key=key,
         username=login,
         cmd="download/all.zip",
-        params="&branch={branch}&language={language}",
+        params="&branch={branch}".format(branch=branch),
```
Comment (indirectlylit) [inline packages/kolibri-tools/lib/i18n/crowdin.py:303]: This will download about 10 extra languages. However, this might actually be faster than doing a couple dozen queries individually so maybe a net performance win?

**Review by indirectlylit — APPROVED** [review]
haven't tested but code looks good. one small suggestion

File: packages/kolibri-tools/lib/i18n/crowdin.py (hunk 2 above)
Comment (rtibbles) [reply packages/kolibri-tools/lib/i18n/crowdin.py:303]: Also, when I looked at the zip files being downloaded, they didn't seem to be language specific - they all contained all the languages.

Comment (indirectlylit) [reply packages/kolibri-tools/lib/i18n/crowdin.py:303]: brilliant

**Comment by radinamatic** [comment]
I run the `make i18n-download...` and all the ES translations from 4 days ago seem to be present in the Spanish UI on my dev server, even the just recently updated context 💯 

LEDev2104 (start)  Running  - Oracle VM VirtualBox_006

I believe we decided to keep the line `--CONTEXT--` on Crowdin, to offer the translators some separation between the string context and the `domain.id` line, to improve the readability and usefulness of the string description.

**Review by radinamatic — APPROVED** [review]
All works! 🎉 
(downloading translated strings & context, `makemessages`, and displaying the localized UI 🙂)

Let's just have the `--CONTEXT--` bit back on Crowdin, and we're good to go!

**Comment by rtibbles** [comment]
Fixing `--CONTEXT--` in a follow up as not directly related to the changes here!
