### PR TITLE
User menu focus fixes

### LINKED ISSUE #5845: User menu button has no visual in-focus indicator
### Observed behavior
[Discovered](https://github.com/learningequality/kolibri/pull/5839#issuecomment-517759637) while testing #5839:

> in Firefox there is a slight button color change when the user menu button receives focus, but no border/outline (**issue 1a**), and on the next <kbd>Tab</kbd> press the inner text label receives focus (**issue 1b** - there's no need for the label to be focusable).

> In Chrome the text label does not seem focusable, but the user menu button has no visual focus indicator whatsoever (**issue 1c**).

### Expected behavior
Consistent styling for buttons when in focus.

### User-facing consequences
Not knowing where the current focus is.

### Errors and logs
…

### Steps to reproduce
Use the <kbd>Tab</kbd> key to focus user menu button.

### Context
 * Kolibri version: 0.13.0.dev
 * Operating system: all
 * Browser: Chrome & FF

### PR DESCRIPTION
**Pull request by bjester**
### Summary

Small fixes to ensure focus outline appears on elements of user menu.

user-menu-cropped

### Reviewer guidance

1) Log into Kolibri
2) Click on app bar in the top middle
3) Press <kbd>Tab</kbd>
4) Observe user menu button is outlined
5) Press <kbd>Enter</kbd>
6) User menu should open
7) Press <kbd>Tab</kbd> to cycle through the menu
8) Observe "Change Language" can be focused

### References

Resolves https://github.com/learningequality/kolibri/issues/5845 and https://github.com/learningequality/kolibri/issues/6006

----

### Contributor Checklist

PR process:

- [X] PR has the correct target branch and milestone
- [X] PR has 'needs review' or 'work-in-progress' label
- [X] If PR is ready for review, a reviewer has been added. (Don't use 'Assignees')
- [ ] If this is an important user-facing change, PR or related issue has a 'changelog' label
- [ ] If this includes an internal dependency change, a link to the diff is provided

Testing:

- [X] Contributor has fully tested the PR manually
- [X] If there are any front-end changes, before/after screenshots are included
- [ ] Critical user journeys are covered by Gherkin stories
- [ ] Critical and brittle code paths are covered by unit tests

### Reviewer Checklist

- Automated test coverage is satisfactory
- PR is fully functional
- PR has been tested for [accessibility regressions](http://kolibri-dev.readthedocs.io/en/develop/manual_testing.html#accessibility-a11y-testing)
- External dependency files were updated if necessary (`yarn` and `pip`)
- Documentation is updated
- Contributor is in AUTHORS.md

### CODE REVIEW

File: kolibri/core/assets/src/views/CoreMenu/CoreMenuOption.vue [hunk 1]
```diff
@@ -13,6 +13,7 @@
       class="core-menu-option"
       role="menuitem"
       :class="$computedClass(optionStyle)"
+      :tabindex="link ? false : '0'"
```
Comment (indirectlylit) [inline kolibri/core/assets/src/views/CoreMenu/CoreMenuOption.vue:16]: Exactly the same behavior, but maybe slightly easier to understand the intent?

```suggestion
      :tabindex="link ? null : '0'"
```

**Review by indirectlylit — APPROVED** [review]
works well!

opened minor follow-up issue here: https://github.com/learningequality/kolibri/issues/6043
