### PR TITLE
Layout changes for the ContentPage in Learn pages

### LINKED ISSUE #3664: Use immersive page in content-page within Learn
### Observed behavior

Not using immersive page in content-page within Learn

### Expected behavior

Use immersive page in content-page within Learn

### User-facing consequences

Not the best use of space.

### LINKED ISSUE #4706: Fixes to resource pages
### Observed behavior
Some outstanding issues with the current exercises page that we need to address:
- Severe lack of screen estate affording the user to interact with the exercise. The presence of top-nav/breadcrumbs/and previously the learn tabs all push down elements and components that correspond to the exercise question (including answer input areas and answer choice selections). 
- Reliance on including navigational elements ever-present on every page. This is valuable usability for the act and intention of navigation to/from various places (e.g. channels tab, import) but shouldn't be present in its current form within pages that stress primary purpose to be heads down focus and engagement (content pages). 
- Legibility of the page suffers. Text everywhere, lack of a clear direction

### Expected behavior and projected improvements
- More clean space to work with
- Standardize on the top-nav style (we already have this applied to lesson resource pages)
- Clear differentiation between "Question area" and "answer areas" (big)

### Design changes
- Top-nav swap
- Eliminate redundancy of title-ception (option 2 ideal)
- Maintain breadcrumb affordance via showing "location", e.g the name of parent topic. Or "From" 
- Eliminate current forms of breadcrumbs
- Add "In-progress" "Completed" labels near the appropriate icon

### Specs and mockup
topnav comparisons

### PR DESCRIPTION
**Pull request by jonboiser**
### Summary

1. Implements layout changes for ContentPage (where you view videos, exercises, etc.), per #4706 

Screen Shot 2019-03-12 at 12 11 31 PM

### Reviewer guidance

1. Verify that parent topic links only appear when browsing content
1. Verify that parent topic links do not appear when viewing a lesson resource
1. Check on the link for the back arrow "<-" as make sure it behaves as described in #4706 for all of the different situations

### References

Fixes #4706 
Fixes #3664 

…

----

### Contributor Checklist

PR process:

- [ ] PR has the correct target branch and milestone
- [ ] PR has 'needs review' or 'work-in-progress' label
- [ ] If PR is ready for review, a reviewer has been added. (Don't use 'Assignees')
- [ ] If this is an important user-facing change, PR or related issue has a 'changelog' label
- [ ] If this includes an internal dependency change, a link to the diff is provided

Testing:

- [ ] Contributor has fully tested the PR manually
- [ ] If there are any front-end changes, before/after screenshots are included
- [ ] Critical user journeys are covered by Gherkin stories
- [ ] Critical and brittle code paths are covered by unit tests

### Reviewer Checklist

- Automated test coverage is satisfactory
- PR is fully functional
- PR has been tested for [accessibility regressions](http://kolibri-dev.readthedocs.io/en/develop/manual_testing.html#accessibility-a11y-testing)
- External dependency files were updated if necessary (`yarn` and `pip`)
- Documentation is updated
- Contributor is in AUTHORS.rst

### CODE REVIEW

File: kolibri/plugins/learn/assets/src/views/ContentPage.vue [hunk 1]
```diff
@@ -327,6 +357,12 @@
 
 <style lang="scss" scoped>
 
+  .folder-svg {
+    margin-right: 8px;
+    margin-bottom: -2px;
+    vertical-align: bottom;
+  }
```
Comment (indirectlylit) [inline kolibri/plugins/learn/assets/src/views/ContentPage.vue]: let's use the `KLabeledIcon` component here to avoid adding special-case layout styling.

If desired, we could can add a new prop to handle tooltips which would be valuable in other places also

File: kolibri/core/assets/src/views/icons/KLabeledIcon.vue [hunk 2]
```diff
@@ -1,22 +1,33 @@
 <template>
 
   <span class="labeled-icon-wrapper">
-    <div class="icon">
+    <div ref="icon" class="icon">
```
Comment (indirectlylit) [inline kolibri/core/assets/src/views/icons/KLabeledIcon.vue]: cc @khangmach -

Currently the tooltip and 'up' link feel a bit awkward:

* they're below the header rather than above
* the icon and link look visually distinct, and only the link is clickable but only the icon has the tooltip
* the phrase "Resource is located in this topic" will be challenging for young learners to understand

> image

For reference, below is how we've started doing 'up' links in coach tools, which looks more clear and doesn't need a tooltip. I feel like we should just use this pattern rather than introducing a new one:

> image


The other thing we should probably do is be consistent about when we use type icons. For example here's the parent topic view:

> image

Should we be bringing back type icons in headers? (We could right-align the 'progress' icon if this would be desirable)

**Review by indirectlylit — COMMENTED** [review]
Hooray! Moving to the full-screen is awesome.

My only concern is with 'up' links, as described below

File: kolibri/core/assets/src/views/icons/KLabeledIcon.vue (hunk 2 above)
Comment (indirectlylit) [reply kolibri/core/assets/src/views/icons/KLabeledIcon.vue]: i.e. something like:

| topic view | content view |
|--|--|
| image | image |

* parent back links always above header, always purple clickable
* in-progress icons top-right in both cards and pages
* type icons top-left in both cards and pages

Comment (indirectlylit) [reply kolibri/core/assets/src/views/icons/KLabeledIcon.vue]: final question: should we be wrapping the content in a `KPageContainer`? They still look a little naked with the grey background:

> image

Comment (jonboiser) [reply kolibri/core/assets/src/views/icons/KLabeledIcon.vue]: There's a separate issue for the KPageContainer here #5242. There are multiple pages where it's not used as well, so it would be nice if it were all fixed in one patch.

Comment (jonboiser) [reply kolibri/core/assets/src/views/icons/KLabeledIcon.vue]: Same with the header+icon pairings in #5119. Should try to fix this holistically.

Comment (indirectlylit) [reply kolibri/core/assets/src/views/icons/KLabeledIcon.vue]: ooooh, @jonboiser just brought up a great point.

I _think_ we'd decided to start going with the convention that in full-screen windows, we'd do:

* × [current thing]
* ← [parent thing]

In other words, back buttons are labeled by what you're going back to, and close buttons are labeling the thing you're about to close. Is that right @khangmach?

In that case, everything becomes much simpler:

> image

Comment (khangmach) [reply kolibri/core/assets/src/views/icons/KLabeledIcon.vue]: @indirectlylit Yes we can just use the implementation above and just have the parent name in the topnav. Also, is the gold star floating right an updated implementation? Haven't seen that yet

Comment (jonboiser) [reply kolibri/core/assets/src/views/icons/KLabeledIcon.vue]: The only changes I'm going to make are to

1. Make the label to the "<-" the parent topic name (if in browse mode)
1. Make the label to the "<-" the lesson name (if in lesson mode)
1. Remove the topic back link.

Moving icons around is a broader design system issue that should maybe be addressed in #5119

Comment (indirectlylit) [reply kolibri/core/assets/src/views/icons/KLabeledIcon.vue]: > Also, is the gold star floating right an updated implementation? 

that was a recommendation to mirror the layout of content cards:

image

and also to be a bit more similar to coach reports, which put the progress info in a separate column rather than inline with the title

File: kolibri/core/assets/src/views/icons/KLabeledIcon.vue [hunk 3]
```diff
@@ -1,22 +1,33 @@
...
     <div class="label">
       <slot></slot>
     </div>
+    <KTooltip
+      v-if="tooltipText"
+      reference="icon"
+      :refs="$refs"
+    >
+      {{ tooltipText }}
+    </KTooltip>
```
Comment (indirectlylit) [inline kolibri/core/assets/src/views/icons/KLabeledIcon.vue]: new tooltip prop is now unused

let's remove this until we have a concrete need for it. Then we can decide whether it's appropriate to have the tooltip on just the icon versus on the entire labeled icon

**Review by indirectlylit — APPROVED** [review]
this looks great!

one more small change requested and then feel free to merge
