### PR TITLE
Fix slow-closing submit modal

### LINKED ISSUE #8893: Completion modal after the practice quiz in a lesson is too short
## Observed behavior
Currently flashes for just a fraction of the second before the practice quiz report appears. Tested on learn-only Android app, while server is on Ubuntu 18.04.

completion-modal-flash

## Errors and logs
…

## Expected behavior
Completion modal should remain opened, until learner decides to either move on with the lesson or view the report.

[Slack discussion around the need for `Move on` button](https://learningequality.slack.com/archives/C02JTHE8EV9/p1639160750037300) in the practice quiz report.

## User-facing consequences
Inconsistent flow between resources in a lesson.

## Steps to reproduce
Complete a practice quiz in a lesson that has other resources lined up after the quiz.

## Context
 * Kolibri version: 0.16 `develop`
 * Operating system: Ubuntu 18.04, Android 8.0
 * Browser: - 

cc @rtibbles @sairina

### PR DESCRIPTION
**Pull request by sairina**
## Summary
1. Fixes infinite loop error in `CompletionModal`
2. Fixes "submit" modal not disappearing after `CompletionModal` is closed by adding `force` and `immediate` to the `QuizRenderer` when saving the exam attempt log and closing the submit modal for `updateContentSession`

What you should see now:

## References
Fixes #8893 - in particular, this error: https://github.com/learningequality/kolibri/issues/8893#issuecomment-994130168

## Reviewer guidance
1. Sign in as learner (open console in browser)
2. Find a practice quiz that has other resources lined up after the practice quiz
3. Take and submit the practice quiz
4. Immediate click on the "x" on the upper right hand corner to close the `CompletionModal`
5. You should not see any RangeErrors in the console and you should not see the practice quiz submit modal at all

----

## Testing checklist

- [x] Contributor has fully tested the PR manually
- [x] If there are any front-end changes, before/after screenshots are included
- [ ] Critical and brittle code paths are covered by unit tests

## PR process

- [ ] PR has the correct target branch and milestone
- [ ] PR has 'needs review' or 'work-in-progress' label
- [ ] If PR is ready for review, a reviewer has been added. (Don't use 'Assignees')
- [ ] If this is an important user-facing change, PR or related issue has a 'changelog' label
- [ ] If this includes an internal dependency change, a link to the diff is provided

## Reviewer checklist

- Automated test coverage is satisfactory
- PR is fully functional
- PR has been tested for [accessibility regressions](http://kolibri-dev.readthedocs.io/en/develop/manual_testing.html#accessibility-a11y-testing)
- External dependency files were updated if necessary (`yarn` and `pip`)
- Documentation is updated
- Contributor is in AUTHORS.md

### CODE REVIEW

File: kolibri/plugins/learn/assets/src/composables/useProgressTracking.js [hunk 1]
```diff
@@ -379,9 +379,9 @@ export default function useProgressTracking(store) {
         Math.min(threeDecimalPlaceRoundup(get(progress_state) + progressDelta), 1)
       );
     }
-    if (get(progress_state) >= 1) {
-      set(complete, true);
-    }
+    // if (get(progress_state) >= 1) {
```
Comment (MisRob) [inline kolibri/plugins/learn/assets/src/composables/useProgressTracking.js]: Was pushing this update intentional?

Comment (sairina) [reply kolibri/plugins/learn/assets/src/composables/useProgressTracking.js]: It wasn't! Thank you for catching.

**Review by MisRob — APPROVED** [review]
Thank you, @sairina. Code changes look good to me and manual testing passes.
