### PR TITLE
building out framework for quiz editor updates and string stubs - round 1

### LINKED ISSUE #4627: Number of questions in the exam.
### Observed behavior
Coach need to enter the number of questions in the exam. When coach use ^ and v arrow to increase/decrease the number of questions. It must stop increasing the number at 50 and stop decreasing the number at 0.

### Expected behavior
It must stop increasing and decreasing the number at 50 and at 0.

### Steps to reproduce
1. Login with Coach.
2. Create the exam.
3. Use downarrow and uparrow to to increase or decrease the number of the question in exam.

### Context
 * Kolibri version : Kolibri 0.11.0
 * Operating system : ubuntu 14.04
 * Browser  : Chrome

### PR DESCRIPTION
**Pull request by indirectlylit**
### 0.12.x string stubs

* Round 1: #4632 (this one)
* Round 2: #4642
* Round 3: #4651
* Round 4 final: #4662

### Summary

* adding lots of strings, should be enough for the quiz editor
* beginning refactor of quiz editor UI
* prototyping with drag/drop library
* sets min, max, and default values on the number of exam items (fixes #4627)

### Reviewer guidance

We need to get this strings in, so nothing is working perfectly; however things are somewhat operational.

### References

figma mockups: https://www.figma.com/file/EMkEnaIiyWXJZsXZmzueueOI/Re-arranging-quiz-questions%2Fquiz-types?node-id=0%3A1

----

### Contributor Checklist

PR process:

- [x] PR has the correct target branch and milestone
- [x] PR has 'needs review' or 'work-in-progress' label
- [x] If PR is ready for review, a reviewer has been added. (Don't use 'Assignees')
- [ ] If this is an important user-facing change, PR or related issue has a 'changelog' label
- [ ] If this includes an internal dependency change, a link to the diff is provided

Testing:

- [ ] Contributor has fully tested the PR manually
- [ ] If there are any front-end changes, before/after screenshots are included
- [ ] Gherkin stories have been updated
- [ ] Unit tests have been updated

### Reviewer Checklist

- Automated test coverage is satisfactory
- PR is fully functional
- PR has been tested for [accessibility regressions](http://kolibri-dev.readthedocs.io/en/develop/manual_testing.html#accessibility-a11y-testing)
- External dependency files were updated if necessary (`yarn` and `pip`)
- Documentation is updated
- Contributor is in AUTHORS.rst

### CODE REVIEW

**Comment by indirectlylit** [comment]
@DXCanas mind looking at this one?

**Comment by DXCanas** [comment]
I know you mentioned it's only semifunctional, so I'm just posting these for posterity:
Are these bars supposed to be blue?
blue top bar
image


Log Errors on Resource list table
log errors

Keyboard press-enter-to-submit on quiz creation doesn't work

Prop mismatch error when clicking on "preview" button for a question:
image

LInks turn blue after submitting "new quiz" form
image

File: kolibri/plugins/coach/assets/src/views/exams/CreateExamPage/index.vue [hunk 1]
```diff
@@ -192,7 +196,7 @@
     data() {
       return {
         examTitle: '',
-        examNumberOfQuestions: '',
+        examNumberOfQuestions: 10,
```
Comment (DXCanas) [inline kolibri/plugins/coach/assets/src/views/exams/CreateExamPage/index.vue:199]: Just verifying that this default is intentional?

File: kolibri/plugins/coach/assets/src/views/exams/CreateExamPage/index.vue [hunk 2]
```diff
@@ -574,14 +595,17 @@
...
+      continueProcess() {
         this.previewOrSubmissionAttempt = true;
         if (this.formIsInvalid) {
           this.focusOnInvalidField();
         } else {
           this.setExamsModal(ExamModals.PREVIEW_NEW_EXAM);
         }
       },
+      goBack() {
+        this.setExamsModal(null);
```
Comment (DXCanas) [inline kolibri/plugins/coach/assets/src/views/exams/CreateExamPage/index.vue:607]: hrm :thinking:

**Comment by indirectlylit** [comment]
Thanks -

Yeah any styling-related bugs and console errors are in `develop` right now due to the dynamic styling updates. Many relate to https://github.com/learningequality/kolibri/issues/4646

File: kolibri/plugins/coach/assets/src/views/exams/CreateExamPage/CreateExamPreview.vue [hunk 3]
```diff
@@ -0,0 +1,333 @@
...
+      exercise: 'Exercise { num }',
+      randomize: 'Give me a different set of questions',
+      questionOrder: 'Question order',
+      questions: 'Questions',
+      randomizedLabel: 'Randomized',
+      randomizedDescription:
+        'The questions in this quiz will be in a random order for each learner',
+      flexibleLabel: 'Flexible',
+      flexibleDescription:
+        'You can order the quiz questions however you want. All learners will see this version',
```
Comment (DXCanas) [inline kolibri/plugins/coach/assets/src/views/exams/CreateExamPage/CreateExamPreview.vue]: Seeing 2 different strings for this - just verifying that this is the right one?

File: kolibri/plugins/coach/assets/src/views/exams/CreateExamPage/index.vue [hunk 4]
```diff
@@ -32,12 +33,11 @@
       </UiAlert>
 
       <div class="buttons-container">
-        <KButton :text="$tr('preview')" @click="preview" />
         <KButton
-          :text="$tr('saveButtonlabel')"
+          :text="$tr('continueButtonlabel')"
```
Comment (DXCanas) [inline kolibri/plugins/coach/assets/src/views/exams/CreateExamPage/index.vue:37]: I tend towards these naming schemes because of some feedback I got from @carinediaz - that the context helps translators. @radinamatic have any ideas about this?

File: kolibri/plugins/coach/assets/src/views/exams/CreateExamPage/CreateExamPreview.vue [hunk 5]
```diff
@@ -0,0 +1,333 @@
+<template>
```
Comment (DXCanas) [inline kolibri/plugins/coach/assets/src/views/exams/CreateExamPage/CreateExamPreview.vue:1]: There's a "Preview exam" label on the app bar that seems to be missing? @indirectlylit

**Review by DXCanas — CHANGES_REQUESTED** [review]
Found a few missing(?) strings and some that need clarifying? 
image
image

image
image

File: kolibri/plugins/coach/assets/src/views/exams/CreateExamPage/index.vue (hunk 1 above)
Comment (indirectlylit) [reply kolibri/plugins/coach/assets/src/views/exams/CreateExamPage/index.vue:199]: yup, giving it a default value

File: kolibri/plugins/coach/assets/src/views/exams/CreateExamPage/CreateExamPreview.vue (hunk 3 above)
Comment (indirectlylit) [reply kolibri/plugins/coach/assets/src/views/exams/CreateExamPage/CreateExamPreview.vue]: updated with the latest from https://docs.google.com/document/d/1OqxXF3rQTAn-2p4SnZo0rsgL8OOlqMcsyK-yeILT6bg/edit#

File: kolibri/plugins/coach/assets/src/views/exams/CreateExamPage/CreateExamPreview.vue (hunk 5 above)
Comment (indirectlylit) [reply kolibri/plugins/coach/assets/src/views/exams/CreateExamPage/CreateExamPreview.vue:1]: I changed it to "Select questions". [Discussion here](https://docs.google.com/a/learningequality.org/document/d/1OqxXF3rQTAn-2p4SnZo0rsgL8OOlqMcsyK-yeILT6bg/edit?disco=AAAACd8Mr7Y) - we can switch in another PR if necessary.

**Comment by indirectlylit** [comment]
> image

Haven't done the reports - will do them in #4642

> image

These should be the same - see [audit doc](https://docs.google.com/document/d/1OqxXF3rQTAn-2p4SnZo0rsgL8OOlqMcsyK-yeILT6bg/edit)

**Comment by indirectlylit** [comment]
Thanks @DXCanas - I think I've addressed all your comments. Let me know

**Review by DXCanas — APPROVED** [review]
