### PR TITLE
User type: Super admin

### LINKED ISSUE #4211: changing the role of a user and saving doesn't close modal
### Observed behavior

reported by @jtamiace 

> I observed in 0.11 that:
> 
> 1. changing the role of another user
> 2. clicking save
> 
> doesn't close the modal when it should

### Expected behavior

modal should close

### User-facing consequences

confusion

### Errors and logs

unknown

### Steps to reproduce

see above

### Context

0.11

### PR DESCRIPTION
**Pull request by DXCanas**
### Summary

Addressing user admin updates in [this prototype](https://www.figma.com/file/KxjIhoBljRKy71SARf1h7dO0/0.11-superuser-clarification?node-id=182%3A0)
facility user list as regular facility admin
facility user list as regular facility admin
facility user list as super admin
facility user list as super admin
super admin editing self in user edit
super admin editing self in user edit
super admin editing other super admin in user edit
super admin editing other super admin in user edit
super admin editing self in device permissions
super admin editing self in device permissions
super admin editing other super admin in device permissions
super admin editing other super admin in device permissions
super admin device permissions view with tooltip
super admin profile view
super admin profile view
content-enabled admin profile view
content-enabled admin profile view
super admin user dropdown view
super admin user dropdown view
super admin stripping other super admin of superness
super admin stripping other super admin of superness
super admin stripping other super admin of superness WITH TOOLTIP

### Reviewer guidance

Used regex `(:\s['"].*superuser.*['"])` to find instances of superuser in `*.js` and `*.vue` files. Make sure I didn't miss any user-facing strings. Replaced most of them with new `DisplayUserType` component. Informing that with new `UserType` util.

There is no more "role" or "kind". Only "type.

Modified the `EditUserModal` a good amount. Probably in need of testing.

### References

- [Design Trello Card](https://trello.com/c/0mgXeeS5/196-clarify-super-admin-in-user-management-tab)
- Resolves #4211
----

### Contributor Checklist

- [x] Contributor has fully tested the PR manually
- [x] PR has the correct target branch and milestone
- [x] PR has 'needs review' or 'work-in-progress' label
- [x] If PR is ready for review, a reviewer has been added. (Don't use 'Assignees')
- [x] If there are any front-end changes, before/after screenshots are included
- [x] If this is an important user-facing change, PR or related issue has a 'changelog' label

### Reviewer Checklist

- [ ] Automated test coverage is satisfactory
- [ ] Reviewer has fully tested the PR manually
- [ ] PR has been tested for [accessibility regressions](http://kolibri-dev.readthedocs.io/en/develop/manual_testing.html#accessibility-a11y-testing)
- [ ] External dependencies files were updated (`yarn` and `pip`)
- [ ] Documentation is updated
- [ ] Link to diff of internal dependency change is included
- [ ] CHANGELOG.rst is updated for high-level changes
- [ ] Contributor is in AUTHORS.rst

### CODE REVIEW

**Comment by indirectlylit** [comment]
looks like all the proper nouns got made lower-case

File: kolibri/plugins/facility_management/assets/src/views/UserPage/EditUserModal.vue [hunk 1]
```diff
@@ -32,26 +32,43 @@
...
+        :userType="kind"
+        class="user-type"
       />
-      <KRadioButton
-        :label="$tr('facilityCoachLabel')"
-        :description="$tr('facilityCoachDescription')"
-        :value="false"
-        v-model="classCoachIsSelected"
+      <span class="super-admin-description">
+        Go to Device permissions to change this
```
Comment (indirectlylit) [inline kolibri/plugins/facility_management/assets/src/views/UserPage/EditUserModal.vue]: `$tr`

**Comment by indirectlylit** [comment]
actually .. looks like we're not consistent with capitalization anyway. @jtamiace @radinamatic  I think we decided to use proper nouns when referring to permissions and user types, right?

E.g.

> Make a new Coach user for the coach.

?

File: kolibri/plugins/device_management/assets/src/views/UserPermissionsPage/index.vue [hunk 2]
```diff
@@ -190,23 +233,29 @@
       goBack() {
         this.$router.push({ path: '/permissions' });
       },
+      UserType,
     },
     $trs: {
       cancelButton: 'Cancel',
       devicePermissions: 'Device permissions',
       devicePermissionsDetails: 'Can import and export content channels',
+      documentTitle: "{ name }'s Device Permissions",
```
Comment (christianmemije) [inline kolibri/plugins/device_management/assets/src/views/UserPermissionsPage/index.vue:232]: We should also use this string for the h1 or the app bar title?

File: kolibri/plugins/device_management/assets/src/views/UserPermissionsPage/index.vue [hunk 3]
```diff
@@ -221,12 +270,36 @@
...
+    width: 112px;
+  }
+
+  .super-admin-checkbox {
+    display: inline-table;
+  }
+
+  .checkbox-description {
+    // visual estimate, supposed to line up with checkbox label
+    margin: 0;
```
Comment (christianmemije) [inline kolibri/plugins/device_management/assets/src/views/UserPermissionsPage/index.vue]: Maybe this instead
```css
margin: 0px 0 0 50px;
padding: 0;
```

File: kolibri/plugins/device_management/assets/src/views/UserPermissionsPage/index.vue [hunk 4]
```diff
@@ -221,12 +270,36 @@
...
+      color: $core-text-disabled;
+    }
+  }
+
   .section {
     padding: 1em;
   }
 
   .permissions-icon {
-    padding-right: 8px;
```
Comment (christianmemije) [inline kolibri/plugins/device_management/assets/src/views/UserPermissionsPage/index.vue:229]: A left margin would be nice.

File: kolibri/plugins/facility_management/assets/src/views/UserPage/EditUserModal.vue (hunk 1 above)
Comment (christianmemije) [reply kolibri/plugins/facility_management/assets/src/views/UserPage/EditUserModal.vue]: Maybe link to this page too?

File: kolibri/plugins/facility_management/assets/src/views/UserTable.vue [hunk 5]
```diff
@@ -177,7 +179,15 @@
...
   .role-badge {
+    display: inline-block;
+    padding-right: 1em;
+    padding-left: 1em;
     margin-left: 8px;
+    font-size: small;
+    color: $core-bg-light;
+    white-space: nowrap;
+    background-color: $core-text-annotation;
+    border-radius: 0.5em;
```
Comment (christianmemije) [inline kolibri/plugins/facility_management/assets/src/views/UserTable.vue:190]: Let's increase the line-height and make to make the pill thiccer.

**Comment by christianmemije** [comment]
Looking good.

File: kolibri/plugins/device_management/assets/src/views/UserPermissionsPage/index.vue [hunk 6]
```diff
@@ -1,35 +1,66 @@
...
           </span>
         </h1>
-        <h3>{{ user.username }}</h3>
+
+        <table>
+          <tr>
+            <th scope="row">
+              {{ $tr('usernameLabel') }}
+            </th>
+            <td> {{ user.username }} </td>
```
Comment (indirectlylit) [inline kolibri/plugins/device_management/assets/src/views/UserPermissionsPage/index.vue]: Minor comment, but in general throughout the codebase we would write

```html
<td>{{ user.username }}</td>
```

rather than

```html
<td> {{ user.username }} </td>
```

In addition to codebase consistency, once in a while the extra whitespace actually has an unexpected style or layout impact.

The extra inline whitespace is a little harder to spot than the super obvious case above e.g.

```html
<th scope="row">
  {{ $tr('usernameLabel') }}
</th>
```

**Comment by jtamiace** [comment]
> I think we decided to use proper nouns when referring to permissions and user types, right?

When did this decision happen? I thought we didn't want to do this

File: kolibri/plugins/facility_management/assets/src/views/UserPage/EditUserModal.vue (hunk 1 above)
Comment (DXCanas) [reply kolibri/plugins/facility_management/assets/src/views/UserPage/EditUserModal.vue]: > Maybe link to this page too?

On the map, see: https://www.figma.com/file/KxjIhoBljRKy71SARf1h7dO0/0.11-superuser-clarification?node-id=0%3A1

File: kolibri/plugins/device_management/assets/src/views/UserPermissionsPage/index.vue (hunk 2 above)
Comment (DXCanas) [reply kolibri/plugins/device_management/assets/src/views/UserPermissionsPage/index.vue:232]: Hmm this wasn't specced in [the mocks](https://www.figma.com/file/KxjIhoBljRKy71SARf1h7dO0/0.11-superuser-clarification?node-id=0%3A1). Using this for either of those wouldn't match the spec.

File: kolibri/plugins/device_management/assets/src/views/UserPermissionsPage/index.vue (hunk 3 above)
Comment (DXCanas) [reply kolibri/plugins/device_management/assets/src/views/UserPermissionsPage/index.vue]: Is the benefit here that we're explicitly defining padding? (I got out of the habit of one-lined margin defs because stylint used to break using them lol).

File: kolibri/plugins/facility_management/assets/src/views/UserTable.vue (hunk 5 above)
Comment (DXCanas) [reply kolibri/plugins/facility_management/assets/src/views/UserTable.vue:190]: Not specced!!

**Comment by indirectlylit** [comment]
> When did this decision happen? I thought we didn't want to do this

I must be confused. let's make sure we all get on the same page later

File: kolibri/plugins/device_management/assets/src/views/UserPermissionsPage/index.vue (hunk 6 above)
Comment (DXCanas) [reply kolibri/plugins/device_management/assets/src/views/UserPermissionsPage/index.vue]: What would the ideal fix be for extra inline whitespace?

**Comment by DXCanas** [comment]
@indirectlylit @jtamiace 
Can we resolve this?
auth message

**Comment by indirectlylit** [comment]
@DXCanas please go with what ever @jtamiace  spec'd :)

if we have occasional inconsistencies in capitalization it's not the end of the world - this string audit is still a huge improvement

File: kolibri/plugins/device_management/assets/src/views/UserPermissionsPage/index.vue [hunk 7]
```diff
@@ -1,35 +1,56 @@
...
         />
-        <p>
-          <PermissionsIcon permissionType="SUPERUSER" class="permissions-icon" />
-          {{ $tr('makeSuperuserDetails') }}
-        </p>
-      </div>
+        <PermissionsIcon permissionType="SUPERUSER" class="permissions-icon" />
 
-      <hr>
+        <ul :class="['checkbox-description', {disabled: superuserDisabled}]">
```
Comment (indirectlylit) [inline kolibri/plugins/device_management/assets/src/views/UserPermissionsPage/index.vue]: for unconditionally applied classes, simply add them to a `class` attribute to be clear that they're static:

```html
<ul class="checkbox-description" :class="{disabled: superuserDisabled}">
```

File: kolibri/plugins/facility_management/assets/src/views/UserPage/EditUserModal.vue [hunk 8]
```diff
@@ -267,4 +308,19 @@
...
 
+  .super-admin-description,
+  .user-type.header,
+  .user-admin {
+    display: block;
+  }
+
+  .super-admin-description {
+    font-size: 12px;
+    color: $core-text-annotation;
```
Comment (indirectlylit) [inline kolibri/plugins/facility_management/assets/src/views/UserPage/EditUserModal.vue]: non-standard link styling

**Review by indirectlylit — APPROVED** [review]
looks good! left a couple comments and pushed changes to address them. Will merge when tests pass
