### PR TITLE
Fix change facility workflow

### LINKED ISSUE #12762: Learner redirected to 'Select/Change facility' again after signing in with the new credentials after the 'Merge account'
## Observed behavior
Discovered while testing https://github.com/learningequality/kolibri/pull/12761.

@rtibbles suggested that the error might be generated when trying to access the "login in as merged user" endpoint - probably a 403 error... 

## Errors and logs
…

## Expected behavior
More seamless experience after the merge: if the authentication is necessary, user should land on the Learn home page.

## User-facing consequences
Confusion, was the merge completed as requested, or not...? 

## Steps to reproduce
(1:48 in the video below)

https://github.com/user-attachments/assets/001d7622-ec88-4602-a209-fe0760842044

## Context

 * Kolibri version 0.17.3b0
 * Operating system: Windows 10
 * Browser: Firefox

### LINKED ISSUE #13097: Change learning facility - Getting an error when I press the "Continue" button
## Observed behavior
In [Kolibri 0.18 alpha1](https://github.com/learningequality/kolibri/releases/tag/v0.18.0-alpha1) it's not possible to change one's facility as the "Continue" button is not working:

Image

## Expected behavior

Fully functional change facility flow.

## Steps to reproduce the issue

1. Install the [Kolibri 0.18 alpha1](https://github.com/learningequality/kolibri/releases/tag/v0.18.0-alpha1) build
2. Go through the 'On my own' setup flow.
3. Go to Profile > Change and attempt to change the facility.

## Logs

[browser-console.log](https://github.com/user-attachments/files/18885797/browser-console.log)

[change-facility-logs.zip](https://github.com/user-attachments/files/18885739/change-facility-logs.zip)

## Usage Details
[Kolibri 0.18 alpha1](https://github.com/learningequality/kolibri/releases/tag/v0.18.0-alpha1)
Windows 11, Ubuntu 22  - Chrome, Firefox

### PR DESCRIPTION
**Pull request by AlexVelezLl**
## Summary

After the vue upgrade to vue 2.7, [this `state` computed property](https://github.com/AlexVelezLl/kolibri/blob/abcf8f619e5e18c3660bd5394cc1618949687814/kolibri/plugins/user_profile/assets/src/views/ChangeFacility/index.vue#L54) that was the context of the state machine provided by the `ChangeFacility` index component had a change: When we refer to this injected property from the setup method, we need to access it through the `.value` property, but when we access it through the options api we dont need the `.value` property anymore. This basically caused the entire change facility workflow to break.

In the course of that refactor I somehow fixed the underlying issue that was causing #12762 (that wasnt initially caused by the vue upgrade since it was reported before that).

https://github.com/user-attachments/assets/ab8e22c0-fdf6-4e4f-9d51-d383814b737d

## References
Closes #12762

## Reviewer guidance

1. Go through the 'On my own' setup flow.
2. Go to Profile > Change > Merge accounts
3. Go through the different paths for merging accounts
4. Check that the user is properly redirected after the account was merged.

###  Note

* I have manually checked all references to the `state` injected prop in the whole ChangeFacility folder, and validated that all references to it inside the `setup` method was being referenced with the `.value` property, and all the references outside the `setup` method was being referenced without the `.value` property. But a double check never hurts :)

### CODE REVIEW

**Comment by radinamatic** [comment]
Habemus facility change and account merging again, hallelujah!!! 🎉 🎉 🎉 

I also went through the LoD setup with account on server (import and new), just for kicks, and still all good 💯

**Review by radinamatic — APPROVED** [review]
LGTM! 💯 👏🏽 :shipit:

**Comment by marcellamaki** [comment]
@radinamatic does this mean that Alex's work here has fixed the (neglected) work in progress I had for one of the previous alpha releases, or that's still separately a problem? https://github.com/learningequality/kolibri/issues/13097

It seems the same root cause (composition api changes in the code syntax) but perhaps just he has actually found all of the places where the problems were

**Comment by radinamatic** [comment]
With this latest asset I was not experiencing the same as in https://github.com/learningequality/kolibri/issues/12762, so it should probably be closed together with https://github.com/learningequality/kolibri/issues/13097, and with the other PR that tried to fix this: https://github.com/learningequality/kolibri/pull/13122

File: kolibri/plugins/user_profile/assets/src/views/ChangeFacility/SelectFacility.vue [hunk 1]
```diff
@@ -248,7 +249,7 @@
         showAddAddressModal,
         facilityDisabled,
         handleAddedAddress,
-        to_continue,
+        toContinue,
       };
     },
     inject: ['changeFacilityService'],
```
Comment (rtibbles) [inline kolibri/plugins/user_profile/assets/src/views/ChangeFacility/SelectFacility.vue:255]: We could return the changeFacilityService from `setup` and not doubly inject - but not a blocker.

File: kolibri/plugins/user_profile/assets/src/views/ChangeFacility/MergeAccountDialog/index.vue [hunk 2]
```diff
@@ -156,9 +156,9 @@
         });
       }
 
+      const component = getCurrentInstance().proxy;
```
Comment (rtibbles) [inline kolibri/plugins/user_profile/assets/src/views/ChangeFacility/MergeAccountDialog/index.vue:159]: Just as an aside, I think this API is strongly discouraged by the Vue maintainers (even thought we do use it in lots of places) - that said, as I noted in @marcellamaki's [PR, the ref API in composables is awful](https://github.com/learningequality/kolibri/pull/13122#discussion_r1971935387), so I think this is OK.

**Review by rtibbles — APPROVED** [review]
Nothing but minor quibbles here, so let's merge!
