### PR TITLE
Performance Optimizations

### LINKED ISSUE #1461: viewing an exercise detail report logs activity for the exercise
Steps to reproduce:

* create a coach or admin account
* add yourself to a class
* interact with an exercise
* wait a bit
* look at your detail report for that exercise
* go up a level - note that the 'last activity' is incorrect

image

### LINKED ISSUE #1482: error and freeze in exam report: multiple timers
was browsing an exam detail report: http://192.237.248.135:8808/coach/#/448c7d75d493342a81edc36df4f34f35/fb51dae6df7545af8455aa3a0c32048d/exams/495eb64ef60a69b955ce8ae4769be9b2

Clicked two question two and then tried to click back to question 1, but can't:

image

image

### PR DESCRIPTION
**Pull request by rtibbles**
## Summary

Remove topic annotation.
Remove 'all content' from the Recommended home page, as pagination used is very inefficient on large channels.
Put cache tags around asset loading blocks in templates.
Removes the content tracking code from the content renderer (incidentally fixes #1461 and closes #1482).
On progress update, update attributes on content node to track the progress fraction on the client side, without having to refetch content node data from server.
Gets rid of the 'ancestor' field on the ContentNode serializer and replaces it with an ancestor detail route, and updates the frontend code that uses this to explicitly fetch the ancestors.
Adds db indexing for `content_id` field of ContentNode.

### CODE REVIEW

File: kolibri/plugins/learn/assets/src/state/actions.js [hunk 1]
```diff
@@ -25,6 +25,7 @@ const { now } = require('kolibri.utils.serverClock');
  */
 
 function _crumbState(ancestors) {
+  console.log(ancestors);
```
Comment (jamalex) [inline kolibri/plugins/learn/assets/src/state/actions.js]: Might be good to remove after, not a blocker

File: kolibri/plugins/learn/assets/src/views/exam-page/answer-indicator.vue [hunk 2]
```diff
@@ -0,0 +1,74 @@
+<template>
```
Comment (jamalex) [inline kolibri/plugins/learn/assets/src/views/exam-page/answer-indicator.vue]: Not clear to me how this fits in with performance tuning, but  seems OK.

Comment (rtibbles) [reply kolibri/plugins/learn/assets/src/views/exam-page/answer-indicator.vue]: Ugh, I thought this might have accidentally got committed. Will delete.
