### PR TITLE
Fix search in quiz workflows

### LINKED ISSUE #13212: Fix bugs in filters, selection, and content type in quizzes
1. The filters should be displayed as active only if there are exercises to which they apply. Currently I can select an active filter only to see "0 results":

https://github.com/user-attachments/assets/f05e3082-485e-47bb-a0e1-a93c79a2a379

2. Similarly when I search by keyword I am seeing folders with no available exercises and resources that are not exercises:

https://github.com/user-attachments/assets/3d39fbec-1d5d-40c3-8855-73e1bdbbb7e0

3. After searching by keyword or by applying a filter the title of the page changes to "Select a practice quiz":

https://github.com/user-attachments/assets/663a446e-9c40-4c22-b070-ba6aa92dc2b8

4. If I have already selected all questions within a folder and I search for the same folder it's not displayed as not selectable:

https://github.com/user-attachments/assets/17cdb280-9d4b-4642-9b12-bed3ec7a9119

_Originally posted by @pcenov in https://github.com/learningequality/kolibri/issues/13083#issuecomment-2717727105_

### PR DESCRIPTION
**Pull request by rtibbles**
## Summary
* Does a small refactor of useBaseSearch to do a fetch of available labels when the "filters" option has been set, parallel to the "descendant" option
* Adds a test to ensure this behaviour
* Deletes the old learn "useSearch" tests which were just an outdated duplicate of the useBaseSearch tests
* Restricts filters for search in the quiz workflow to just return exercises, and not folders - this is in line with previous behaviour, and avoids having to update the backend to handle filtering folders for whether they contain exercises or not
* Adds conditional rendering to the router-view in the CreateExamPage to prevent errors caused by trying to render the side panel before the quiz has initialized
* Uses created hook rather than mounted to set data to avoid passing invalid values as props to the KRadioButton component
* Passes through all necessary props to the UpdatedResourceSelection when used in SelectFromQuizSearchResults
* Adds conditional rendering for case when topic is null in SelectFromTopicTree to avoid console errors.

## References
Fixes #13212

## Reviewer guidance
Add questions to a quiz:
* When searching see that none of the presented filters will return "0 results" (1)
* When searching see that we only return exercises and not folders, with the result that no exerciseless folders are presented, nor are folders whose exercises have already been used up by the quiz shown as selectable (2, 4)

3 was fixed previously.

### CODE REVIEW

File: kolibri/plugins/coach/assets/src/views/quizzes/CreateExamPage/sidePanels/QuizResourceSelection/index.vue [hunk 1]
```diff
@@ -426,7 +426,7 @@
         },
         search: {
           filters: {
-            kind_in: [ContentNodeKinds.EXERCISE, ContentNodeKinds.TOPIC],
+            kind: ContentNodeKinds.EXERCISE,
```
Comment (AlexVelezLl) [inline kolibri/plugins/coach/assets/src/views/quizzes/CreateExamPage/sidePanels/QuizResourceSelection/index.vue:431]: Is this the desired behavior? In the quiz side panel figma specs we can see and browse search results folders https://www.figma.com/design/lVJt5ukOrxS9qay0rXy7GC/0.18-Coach-updates?node-id=2189-184132&t=SCJQdMgJhYMrDRmv-0.

Just checkin-in :sweat_smile:

When fetching quizzes for topicTree this also happens but the `annotateTopicsWithDescendantCounts` filters the folders that doesnt have any exercises inside.

**Review by AlexVelezLl — COMMENTED** [review]
Code changes looks good to me :) just a note to be aware of a difference with the figma specs

File: kolibri/plugins/coach/assets/src/views/quizzes/CreateExamPage/sidePanels/QuizResourceSelection/index.vue (hunk 1 above)
Comment (nucleogenesis) [reply kolibri/plugins/coach/assets/src/views/quizzes/CreateExamPage/sidePanels/QuizResourceSelection/index.vue:431]: Perhaps the [search](https://github.com/learningequality/kolibri/blob/47e46a18cf227d87df884e4940fe8f9a131d48b1/kolibri/plugins/coach/assets/src/composables/useResourceSelection.js#L26-L27) property in the useResourceSelection param object should also take in an annotator into which we could pass in that `annotateTopics...` function and call in the fetch function where needed?

Comment (rtibbles) [reply kolibri/plugins/coach/assets/src/views/quizzes/CreateExamPage/sidePanels/QuizResourceSelection/index.vue:431]: I had discussed this with @marcellamaki - the specs introduced a difference from the current search behaviour in 0.17 by adding the ability to see folders in the search results.

The alternative is to have to add some gnarly backend updates in order to be able to filter folders by whether they contain descendant exercises.

We can get away with not doing this for the topic tree navigation because of our "annotateTopics" trick which allows us to filter out folders that have no descendant assessments, however for search, this would allow us to still produce non-keyword searches that have zero results (which is another issue that was being fixed in the course of this work).

All in all, it seemed simpler to not change the previous behaviour in this respect.

Comment (nucleogenesis) [reply kolibri/plugins/coach/assets/src/views/quizzes/CreateExamPage/sidePanels/QuizResourceSelection/index.vue:431]: Thanks for that Richard. 

Noting I'll do manual QA today to give the  :heavy_check_mark:

**Review by nucleogenesis — DISMISSED** [review]
Manual testing looks good, code looks good overall! :shipit:

**Comment by pcenov** [comment]
Hi @rtibbles Observed just the following minor issue: if I've selected and added all questions from a folder to a section, then when I go back and make a search either by keyword or by applying a filter I am still seeing the folder as selectable. If I attempt to select it the "Add..." button remains disabled:

https://github.com/user-attachments/assets/de3b4e43-0585-4761-bf7e-2d2e36e21db0

Using the breadcrumb navigation results in seeing the correct state of the checkbox:

https://github.com/user-attachments/assets/e452de2a-0319-4849-bc49-0a41c2f0ffb7

**Comment by rtibbles** [comment]
Thanks @pcenov - will take a closer look.

**Comment by rtibbles** [comment]
@pcenov I think I've fixed this issue, plus possibly another unreported one like the appropriate messages being displayed on the cards in search ("x questions unused" had been missing from the search cards).

**Review by pcenov — APPROVED** [review]
LGTM now, no new issues observed while manually testing.

File: kolibri/plugins/coach/assets/src/views/common/resourceSelection/subPages/SelectFromTopicTree.vue [hunk 2]
```diff
@@ -1,6 +1,6 @@
 <template>
 
-  <div>
+  <div v-if="topic">
```
Comment (AlexVelezLl) [inline kolibri/plugins/coach/assets/src/views/common/resourceSelection/subPages/SelectFromTopicTree.vue:3]: Were we getting to this point with topic=null? In what case does it happen? In the setup method we have other references to topic assuming its always defined

Comment (rtibbles) [reply kolibri/plugins/coach/assets/src/views/common/resourceSelection/subPages/SelectFromTopicTree.vue:3]: Yes, on page refresh this can happen - I didn't observe any errors from the setup method though, only here. There's also the validation warning from the topic prop still extant, but that seemed valid.

**Comment by AlexVelezLl** [comment]
Code changes lgtm! Although there is another little difference we have in the quiz search workflow, When displaying the search results, we dont have the "settings" button.

Figma:
image

Implementation:
image

We have a [QuizResourceSelectionHeader](https://github.com/rtibbles/kolibri/blob/78a39da57397beaf9d23800e249610772446df4a/kolibri/plugins/coach/assets/src/views/common/resourceSelection/QuizResourceSelectionHeader.vue) that should be used here instead of the current implementation.

Apologies I did not catch this earlier. This can be done in a follow up if needed.

**Comment by rtibbles** [comment]
Yes, I am doing some other cleanup in https://github.com/learningequality/kolibri/issues/13240, I can fix this alongside that.

**Comment by AlexVelezLl** [comment]
Thanks @rtibbles! Sounds good!

File: kolibri/plugins/coach/assets/src/views/common/resourceSelection/subPages/SelectFromTopicTree.vue (hunk 2 above)
Comment (AlexVelezLl) [reply kolibri/plugins/coach/assets/src/views/common/resourceSelection/subPages/SelectFromTopicTree.vue:3]: Hmmm its weird, I have tried that case too and didnt find that error, in theory this component is not mounted yet when we do our first load and `loading = true`, and once `loading=false` the topic should be already defined. But well, an additional check never hurts. Perhaps there is a little frame where the component is mounted but we havent yet started to load the resources? :sweat_smile:, I think that would be it
