### PR TITLE
[ImmersivePage] Fix content padding

### LINKED ISSUE #9905: App bar overlaps main content
## Observed behavior
On some pages, the app bar is overlapping the main content, as flagged by Richard

image (16)

## Expected behavior
Normal spacing should exist

## Steps to reproduce
Investigate pages in various plugins - perhaps this is a problem with the immersive page? It also might be a KDS problem. Needs some investigation before remedying.

## Context
develop, latest KDS

### PR DESCRIPTION
**Pull request by AlexVelezLl**
## Summary

The main content padding-top of pages using ImmersivePage were being miscalculated because `ImmersivePage` could not detect the correct height of the appBar, this because `ImmersivePage`'s appbar (`ImmersiveToolbar`) had position: fixed, and its `clientHeight` was 0. So this PR delegates the element positioning to the `ScrollingHeader` component to help correctly calculate the height of the appBar on immersive pages.

**Before**
image

**After**
image

## References

Closes #9905

## Reviewer guidance

Go to any Immersive page like Add User in Facility section, or Manage Content in Device section, and check that the appbar doesn't overlap the main content.

## Testing checklist

- [x] Contributor has fully tested the PR manually
- [x] If there are any front-end changes, before/after screenshots are included
- [ ] Critical user journeys are covered by Gherkin stories
- [ ] Critical and brittle code paths are covered by unit tests

## PR process

- [x] PR has the correct target branch and milestone
- [x] PR has 'needs review' or 'work-in-progress' label
- [x] If PR is ready for review, a reviewer has been added. (Don't use 'Assignees')
- [ ] If this is an important user-facing change, PR or related issue has a 'changelog' label
- [ ] If this includes an internal dependency change, a link to the diff is provided

## Reviewer checklist

- Automated test coverage is satisfactory
- PR is fully functional
- PR has been tested for [accessibility regressions](http://kolibri-dev.readthedocs.io/en/develop/manual_testing.html#accessibility-a11y-testing)
- External dependency files were updated if necessary (`yarn` and `pip`)
- Documentation is updated
- Contributor is in AUTHORS.md

### CODE REVIEW

File: kolibri/core/assets/src/views/CorePage/ImmersivePage.vue [hunk 1]
```diff
@@ -1,32 +1,36 @@
...
-      :isFullscreen="primary"
-    />
-    <slot></slot>
-    <KLinearLoader
-      v-if="loading"
-      class="loader"
-      type="indeterminate"
-      :delay="false"
-    />
+  <div class="main">
```
Comment (AlexVelezLl) [inline kolibri/core/assets/src/views/CorePage/ImmersivePage.vue:3]: It also works just with: 
```Vue
  <div :style="wrapperStyles">
    <ScrollingHeader :scrollPosition="0">
      <ImmersiveToolbar
        ref="appBar"
        :appBarTitle="(!loading ? appBarTitle : '')"
        :route="route"
        :icon="icon"
        :isFullscreen="primary"
      />
      <KLinearLoader
        v-if="loading"
        type="indeterminate"
        :delay="false"
      />
    </ScrollingHeader>
    <slot></slot>
  </div>
```
But I added the `main` and `main-wrapper` classes for consistency with the `AppBarPage` component.

File: kolibri/core/assets/src/views/ImmersiveToolbar.vue [hunk 2]
```diff
@@ -8,11 +8,6 @@
       :showIcon="showIcon"
       :style="{
         height: topBarHeight + 'px',
-        position: 'fixed',
```
Comment (AlexVelezLl) [inline kolibri/core/assets/src/views/ImmersiveToolbar.vue:11]: I looked for places where this component was used, and it was only used in `ImmersivePage` and `CoreBase` and in both it would be wrapped by the `ScrollingHeader` component, so there should be no unintended changes.

**Comment by pcenov** [comment]
No issues observed @radinamatic LGTM!

**Review by radinamatic — APPROVED** [review]
Manual QA is looking good, if the code review passes too, we can merge this @marcellamaki! 💯 :shipit:

**Review by rtibbles — APPROVED** [review]
This looks like the right change, and should give consistent behaviour across the two page layouts.
