### PR TITLE
Design fixes

### LINKED ISSUE #8563: Hybrid Learning Library, Topics pages -- design alignment follow up to-dos
Topics Page 
- [x] Header - title alignment, better truncation, and overall spacing. 
- [x] Header - add text truncation for description 
- [x] Remove "channels" breadcrumb
- [x] Add "active" styles for folders and search tab 
- [x] Add "show more" option below trimmed channel resources 
- [x] Add "end folder view" 
- [x] Add header for folder topic above topic links
- [x] update footer: add progress, remove "more options" footer icon 
- [x] Remove breadcrumbs for search 
- [x] investigate and potentially fix breadcrumbs - some of the ordering seems incorrect
- [x] Fix "squished" view on limited search results
- [x] Remove thumbnail outline on topic thumbnail in header

Library page 
- [ ] change colors, and background color to tokens
- [x] Fix mobile card view that sometimes shows up as a grid with toggle, when should just be single card
- [x] Fix "squished" view on limited search results
- [x] Fix text overflow caused by shrinking page and long title
- [x] search: card spacing, and ensure toggle list/grid is visible 
- [ ] remove list/grid toggle if no content cards displayed

Classes page 
- [x] remove 'Library' breadcrumbs

Bookmarks page 
- [x] Card: Add text truncation to manage long description overflow and spacing issues 

Search panel
- [ ] Clear an activity or category by clicking on an active button
- [x] Fix spacing on side bar to ensure scroll to the bottom of the panel works, even on a limited folder list in the main content [ETA: this is actually because Marcella is so used to seeing the dev view, and it was not actually broken]
- [x] Activity buttons should appear on mobile

Cards 
- [ ] double-digit coach count overflows side of card
- [x] [Fix label ordering and alignment](https://github.com/learningequality/kolibri/pull/8708#pullrequestreview-808114144)

### PR DESCRIPTION
**Pull request by marcellamaki**
## Summary

Should fix the remaining issues in the P0 design follow ups, plus the channel thumbnail issue @rtibbles noted on Slack.

## References
Fixes #8563's remaining issues: 

- double-digit coach count overflows side of card
-Screen Shot 2021-12-03 at 5 18 18 PM

- Clear an activity or category by clicking on an active button
unclick-activity

- remove list/grid toggle if content cards displayed
Screen Shot 2021-12-03 at 5 21 32 PM

- change colors, and background color to tokens (Library page)

## Reviewer guidance

----

## Testing checklist

- [ ] Contributor has fully tested the PR manually
- [ ] If there are any front-end changes, before/after screenshots are included
- [ ] Critical user journeys are covered by Gherkin stories
- [ ] Critical and brittle code paths are covered by unit tests

## PR process

- [ ] PR has the correct target branch and milestone
- [ ] PR has 'needs review' or 'work-in-progress' label
- [ ] If PR is ready for review, a reviewer has been added. (Don't use 'Assignees')
- [ ] If this is an important user-facing change, PR or related issue has a 'changelog' label
- [ ] If this includes an internal dependency change, a link to the diff is provided

## Reviewer checklist

- Automated test coverage is satisfactory
- PR is fully functional
- PR has been tested for [accessibility regressions](http://kolibri-dev.readthedocs.io/en/develop/manual_testing.html#accessibility-a11y-testing)
- External dependency files were updated if necessary (`yarn` and `pip`)
- Documentation is updated
- Contributor is in AUTHORS.md

### CODE REVIEW

**Comment by sairina** [comment]
> double-digit coach count overflows side of card

This seems to be fixed, but single-digit coach count seems to be off. Should this be a separate issue, or can it be fixed here?

|multi-digit|single-digit|
|--|--|
|Screen Shot 2021-12-06 at 12 41 40 PM|Screen Shot 2021-12-06 at 12 41 58 PM|

File: kolibri/plugins/learn/assets/src/views/EmbeddedSidePanel/ActivityButtonsGroup.vue [hunk 1]
```diff
@@ -93,13 +93,22 @@
...
           },
         };
       },
+      activeStyles() {
+        return {
+          'background-color': 'rgb(235, 210, 235)',
+          border: '2px !important',
+          'border-color': ` ${this.$themeTokens.primary} !important`,
+          'border-style': 'solid !important',
+          'border-radius': '4px !important',
```
Comment (indirectlylit) [inline kolibri/plugins/learn/assets/src/views/EmbeddedSidePanel/ActivityButtonsGroup.vue:109]: The need to use `!important` implies that these buttons should perhaps not have been built based on `KButton`.

File: kolibri/plugins/learn/assets/src/views/HybridLearningContentCard/index.vue [hunk 2]
```diff
@@ -251,7 +253,7 @@
   }
 
   .coach-content-label {
-    max-width: 30px;
+    // max-width: 30px;
```
Comment (indirectlylit) [inline kolibri/plugins/learn/assets/src/views/HybridLearningContentCard/index.vue]: dead code

File: kolibri/plugins/learn/assets/src/views/EmbeddedSidePanel/index.vue [hunk 3]
```diff
@@ -271,7 +271,7 @@
           ':hover': {
             'background-color': 'rgb(235, 210, 235)',
             border: '2px',
-            'border-color': '#996189',
+            'border-color': `${this.$themeTokens.primary} !important`,
```
Comment (indirectlylit) [inline kolibri/plugins/learn/assets/src/views/EmbeddedSidePanel/index.vue:274]: another `!important`

**Review by indirectlylit — COMMENTED** [review]
Visually things look good.

For maintainability it may have been better to _not_ use `KButton` for these widgets, because they look and behave very differently from the component provided by KDS. It may have been easier to implement them from scratch using a basic HTML `<button>` component.

This appears to not be an isolated case, so I've opened a follow-up issue here: https://github.com/learningequality/kolibri/issues/8811

File: kolibri/plugins/learn/assets/src/views/EmbeddedSidePanel/index.vue [hunk 4]
```diff
@@ -316,13 +316,19 @@
       handleActivity(activity) {
         let learning_activities;
         if (activity) {
-          learning_activities = {
-            [activity]: true,
-          };
+          if (this.value.learning_activities[activity]) {
+            delete this.value.learning_activities[activity];
+            this.$emit('input', { learning_activities });
```
Comment (rtibbles) [inline kolibri/plugins/learn/assets/src/views/EmbeddedSidePanel/index.vue]: This needs `...this.value` otherwise it clears all active search terms, not just the learning activities - I think you've overcomplicated the diff here, and directly deleting from the value is not what we should do for the v-model compatibility.

This funcion should instead looking something like this:
```
      handleActivity(activity) {
        let learning_activities;
        if (activity || !this.value.learning_activities[activity]) {
          learning_activities = {
            [activity]: true,
          };
        } else {
          learning_activities = {};
        }
        this.$emit('input', { ...this.value, learning_activities });
      },
```

**Review by rtibbles — CHANGES_REQUESTED** [review]
This causes clicking an active learning activity to clear all currently selected search terms.

File: kolibri/plugins/learn/assets/src/views/EmbeddedSidePanel/index.vue (hunk 4 above)
Comment (marcellamaki) [reply kolibri/plugins/learn/assets/src/views/EmbeddedSidePanel/index.vue]: I originally had tried something like this, but it doesn't seem to work... I'll take another look now

Comment (rtibbles) [reply kolibri/plugins/learn/assets/src/views/EmbeddedSidePanel/index.vue]: OK - I did test it locally and confirmed that the current implementation did cause _all_ search terms to get cleared when a learning activity is deselected.

File: kolibri/plugins/learn/assets/src/views/EmbeddedSidePanel/index.vue [hunk 5]
```diff
@@ -315,19 +315,14 @@
...
-            learning_activities = {
-              [activity]: true,
-            };
-            this.$emit('input', { ...this.value, learning_activities });
-          }
-        } else {
+        if (this.value.learning_activities[activity]) {
           learning_activities = {};
           this.$emit('input', { ...this.value, learning_activities });
+        } else if (activity || !this.value.learning_activities[activity]) {
```
Comment (rtibbles) [inline kolibri/plugins/learn/assets/src/views/EmbeddedSidePanel/index.vue:321]: Could probably skip the `| |` here and leave out the final check because of the `else if`.

Comment (rtibbles) [inline kolibri/plugins/learn/assets/src/views/EmbeddedSidePanel/index.vue:321]: Could probably skip the `| |` here and leave out the final check because of the `else if`.

**Review by rtibbles — APPROVED** [review]
Now working as expected, code looks correct too.
