### PR TITLE
Manually blur text-link-style KButtons when they are clicked or enter-keyed

### LINKED ISSUE #5103: On (at least) one modal, dismissing with enter keypress causes it to come back
### Observed behavior

This was seen with the privacy modal, and is in other places now:

1. Facility > Class Details > Rename Class
1. Privacy link on sign-in page
1. Privacy link on sign-up page
1. Profile page, change password modal
1. "Change" status button for Lessons

It seems to be for the same reasons as #4973 (privacy modal), the "Edit" button maintains focus while the modal is on, so it gets "clicked" again when you dismiss the modal with an Enter keypress.

The common thing between these two cases is that the privacy link and rename use the text-link versions of the Button.

### Expected behavior

Text-type links do not have this side-effect when "clicked" by an enter-keypress

### Context

Kolibri 0.12 latest

### PR DESCRIPTION
**Pull request by jonboiser**
### Summary

Fixes #5103 and the root cause of #4973 by manually blurring the component when it is clicked or enter-keyed. This prevents the link/button from being re-clicked when the user dismisses/submits a modal by hitting Enter (but has the other, hopefully less noticeable side effect of removing focus from that link, so the user will need to refocus it if a keyboard-only user).

### Reviewer guidance

In #5103, there is a list of all the pages where there was a problem with dismissing a modal by keyboard. Go to all of them and test that

1. If you click the link and dismiss the modal with a keyboard, the modal does not re-appear
1. If you "click" the link via keyboard, it''s the same.

And, until you are satisfied, check that other k-button text links that do something other than open a modal still work properly (if they exist).
### References

----

### Contributor Checklist

PR process:

- [ ] PR has the correct target branch and milestone
- [ ] PR has 'needs review' or 'work-in-progress' label
- [ ] If PR is ready for review, a reviewer has been added. (Don't use 'Assignees')
- [ ] If this is an important user-facing change, PR or related issue has a 'changelog' label
- [ ] If this includes an internal dependency change, a link to the diff is provided

Testing:

- [ ] Contributor has fully tested the PR manually
- [ ] If there are any front-end changes, before/after screenshots are included
- [ ] Critical user journeys are covered by Gherkin stories
- [ ] Critical and brittle code paths are covered by unit tests

### Reviewer Checklist

- Automated test coverage is satisfactory
- PR is fully functional
- PR has been tested for [accessibility regressions](http://kolibri-dev.readthedocs.io/en/develop/manual_testing.html#accessibility-a11y-testing)
- External dependency files were updated if necessary (`yarn` and `pip`)
- Documentation is updated
- Contributor is in AUTHORS.rst

### CODE REVIEW

File: kolibri/core/assets/src/views/SideNav.vue [hunk 1]
```diff
@@ -201,9 +201,6 @@
       },
       handleClickPrivacyLink() {
         this.privacyModalVisible = true;
-        // HACK to fix https://github.com/learningequality/kolibri/issues/4973.
-        // For some reason, the button maintains focus even when the modal is opened.
```
Comment (indirectlylit) [inline kolibri/core/assets/src/views/SideNav.vue:205]: is this condition failing?

https://github.com/learningequality/kolibri/blob/develop/kolibri/core/assets/src/views/KModal.vue#L201

Comment (jonboiser) [reply kolibri/core/assets/src/views/SideNav.vue:205]: I'm not sure. But even if you put the focus on the modal but clicking or tabbing on to it, then close it, you still get the same behavior only when the modal-opening button is an anchor tag (so focus is actually in both places). Might be specific just to `<a>`.

Comment (jonboiser) [reply kolibri/core/assets/src/views/SideNav.vue]: Yeah, I just checked it and it does enter into the focusModal branch when you click them (and this is without this PR).

Comment (jonboiser) [reply kolibri/core/assets/src/views/SideNav.vue:205]: Yeah, I checked this with the Class Rename button, and it does not enter into the focusModal branch because, I guess the active element is still that link.

For the side-nav privacy link, it _does_ enter the focusModal branch because in that case the link was blurred in the hack we deleted here.

I tried removing the second condition so that focusModal gets called unconditionally, and we still get the same behavior.

**Review by indirectlylit — APPROVED** [review]
