### PR TITLE
Don't show the password input if the username is not correctly validated

### LINKED ISSUE #7093: username field is not required
### Observed behavior

can proceed with an empty username:

### Expected behavior

username should be required and have auto-focus

### User-facing consequences

confusion

### Context

0.14 beta 3

### PR DESCRIPTION
**Pull request by jredrejo**
### Summary
Password input text is not shown until the username is validated

### Reviewer guidance
Pressing next without adding an username (or using an invalid username) does not show the password input screen

### References
Closes #7093 

### Contributor Checklist

PR process:

- [x] PR has the correct target branch and milestone
- [x] PR has 'needs review' or 'work-in-progress' label
- [x] If PR is ready for review, a reviewer has been added. (Don't use 'Assignees')
- [ ] If this is an important user-facing change, PR or related issue has a 'changelog' label
- [ ] If this includes an internal dependency change, a link to the diff is provided

Testing:

- [ ] Contributor has fully tested the PR manually
- [ ] If there are any front-end changes, before/after screenshots are included
- [ ] Critical user journeys are covered by Gherkin stories
- [ ] Critical and brittle code paths are covered by unit tests

### Reviewer Checklist

- Automated test coverage is satisfactory
- PR is fully functional
- PR has been tested for [accessibility regressions](http://kolibri-dev.readthedocs.io/en/develop/manual_testing.html#accessibility-a11y-testing)
- External dependency files were updated if necessary (`yarn` and `pip`)
- Documentation is updated
- Contributor is in AUTHORS.md

### CODE REVIEW

File: kolibri/plugins/user/assets/src/views/SignInPage.vue [hunk 1]
```diff
@@ -296,7 +296,7 @@
         );
       },
       shouldShowPasswordForm() {
-        return Boolean(this.selectedListUser);
+        return Boolean(this.selectedListUser) && !this.usernameIsInvalid;
```
Comment (nucleogenesis) [inline kolibri/plugins/user/assets/src/views/SignInPage.vue:299]: If you click "next" before entering anything and then start typing, it transitions to the password form after 1 character because that's all it takes to make `username` valid.

I'd suggest also changing `setSelectedListUser` to not save the `selectedListUser` if there is no `username` given.

**Review by nucleogenesis — DISMISSED** [review]
Just the issue noted below:

File: kolibri/plugins/user/assets/src/views/SignInPage.vue (hunk 1 above)
Comment (jredrejo) [reply kolibri/plugins/user/assets/src/views/SignInPage.vue:299]: @nucleogenesis Done

**Review by indirectlylit — DISMISSED** [review]
We need to show some user feedback that the username field is required:

**Comment by radinamatic** [comment]
It used to be there on 0.13

Selection_651

**Comment by jredrejo** [comment]
> We need to show some user feedback that the username field is required:
> 
> 

@indirectlylit  done. I hadn't notice the issue because pressing Enter the validation error appeared. Now it appears when clicking on the next button too.

**Review by jonboiser — APPROVED** [review]
looks good to me!
