### PR TITLE
LearnerSummaryPage: Fix quiz/lesson report links

### LINKED ISSUE #13027: Broken links for assignments on learner's summary page
## Observed behavior
Encountered by [@ozer550 (Slack)](https://learningequality.slack.com/archives/C06ERFGFAMV/p1737659796259309). 

All assigned lessons have the same (broken) link http://127.0.0.1:8080/en/coach/#/, while assigned quizzed apparently do have more specific link, but clicking on it does nothing.

https://github.com/user-attachments/assets/167eceb4-57c6-41f4-b3d2-0a70ff65e8a5
 

## Errors and logs
None observed in the console.

## Expected behavior
Working links towards assignments.

## User-facing consequences
Coaches unable to open reports for learners' assignments.

## Steps to reproduce
…

## Context
 * Kolibri version: 0.18 (current develop)
 * Operating system: all
 * Browser: all

### PR DESCRIPTION
**Pull request by nucleogenesis**
## Summary

LessonSummaryPage was using the wrong page names when generating the links to the proper reports. This PR corrects them.

## References

Fixes #13027 

## Reviewer guidance

Click the links in `Coach -> Learners -> <Specific Learner Summary>` for Lessons and Quizzes, they should work.

### CODE REVIEW

**Comment by ozer550** [comment]
Hi @nucleogenesis! while testing I found this different behavior when clicking on the quiz links. 
If we try to open the links in a new tab it has a different behavior then doing it on the same page. 

https://github.com/user-attachments/assets/b63a8fc3-8bb6-4e9a-93f2-4d2b765050c4

File: kolibri/plugins/coach/assets/src/views/learners/LearnerSummaryPage/index.vue [hunk 1]
```diff
@@ -174,7 +170,10 @@
         return this.getLearnersForExam(quiz).includes(this.learner.id);
       },
       quizLink(quizId) {
-        return this.classRoute(PageNames.REPORTS_LEARNER_REPORT_QUIZ_PAGE_ROOT, { quizId });
+        return this.classRoute(PageNames.QUIZ_LEARNER_REPORT, { quizId });
+      },
```
Comment (AllanOXDi) [inline kolibri/plugins/coach/assets/src/views/learners/LearnerSummaryPage/index.vue:196]: I think the route definitions for this page is missing the `meta.titleParts. (https://github.com/learningequality/kolibri/blob/13027-broken-links-learner-summary-page/kolibri/plugins/coach/assets/src/composables/useCoreCoach.js#L46)` which might explain the failed page title. So,  you might  needs to check the route configuration for those specific pages (QUIZ_LEARNER_REPORT and LESSON_LEARNER_REPORT) and ensure their meta fields have titleParts defined.
Screenshot 2025-01-29 at 15 11 10

**Review by AllanOXDi — CHANGES_REQUESTED** [review]

File: kolibri/plugins/coach/assets/src/views/learners/LearnerSummaryPage/index.vue (hunk 1 above)
Comment (nucleogenesis) [reply kolibri/plugins/coach/assets/src/views/learners/LearnerSummaryPage/index.vue:196]: Looks like it was caused by the appBarTitle being set specifically rather than letting it use the title parts, should be good now.

Thanks @AllanOXDi !

**Comment by nucleogenesis** [comment]
I think that maybe we need to remove the GROUP_NAME from all (or at least some) of the titleParts in the report title.

This is causing the error when generating the page title - see the change in this [commit](https://github.com/learningequality/kolibri/pull/13037/commits/a85c02557be5f12f7c23422964d8d1e3a8ea835c) where I updated the params -- basically, I'd also need to pass a `groupId` param to get the title to generate w/out errors.

Putting the group name in the title appears to be vestigial from the previous UX where a coach could end up on reports through the Groups UI. 

Now the coach cannot get to a report in a group-specific context and users can be in multiple groups, so it seems irrelevant to the report page itself.

Thoughts @AllanOXDi @AlexVelezLl @marcellamaki ?

**Comment by AlexVelezLl** [comment]
Hmmm, I would suggest just one alternative is that we can validate if the param `groupId` is defined [here](https://github.com/learningequality/kolibri/blob/a85c02557be5f12f7c23422964d8d1e3a8ea835c/kolibri/plugins/coach/assets/src/composables/useCoreCoach.js#L54), because that param is optional, and it makes no sense that in the useCoreCoach we treat it as a required param. So even if `GROUP_NAME` is part of the titleParts, if params.groupId is not defined, then we can just skip it.

File: kolibri/plugins/coach/assets/src/views/learners/LearnerSummaryPage/index.vue [hunk 2]
```diff
@@ -190,7 +186,10 @@
         return this.getLearnersForExam(quiz).includes(this.learner.id);
       },
       quizLink(quizId) {
-        return this.classRoute(PageNames.REPORTS_LEARNER_REPORT_QUIZ_PAGE_ROOT, { quizId });
+        return this.classRoute(PageNames.QUIZ_LEARNER_REPORT, { quizId });
```
Comment (AlexVelezLl) [inline kolibri/plugins/coach/assets/src/views/learners/LearnerSummaryPage/index.vue]: Here this route is failing because we are not passing the questionId, interactionIndex and tryIndex params. Here it would be better to use the [QUIZ_LEARNER_PAGE_ROOT page](https://github.com/learningequality/kolibri/blob/a85c02557be5f12f7c23422964d8d1e3a8ea835c/kolibri/plugins/coach/assets/src/routes/examRoutes.js#L94) that the only thing that it does is that it redirects it to the `QUIZ_LEARNER_REPORT` page but defines default values for these params, so we dont need to do it here.

**Comment by radinamatic** [comment]
Looking good, no more broken links! 👍🏽 

Maybe connected to what is discussed above, I would point out that the presentation of the **lesson not visible** and **quiz not started** are visually different, that is, not consistent: clicking on the not started quiz appears as if there are no questions in it. We should at least add a string ``Quiz not started`` (we'll open a separate issue), to palliate a bit the blank page and make the quiz report more clear.

recording | screenshot
-- | --
https://github.com/user-attachments/assets/6db08d5a-fe08-4f9d-a8ec-696fd0ee6704 |

**Review by radinamatic — APPROVED** [review]
Broken links are no more, some follow up changes to come! 👍🏽 💯 :shipit:

**Review by AlexVelezLl — APPROVED** [review]
Code wise looks good to me aswell :)

**Review by AllanOXDi — APPROVED** [review]
LGTM!
