### PR TITLE
Return to resource list after adding/removing an item from a lesson/quiz

### LINKED ISSUE #6819: return to resource list after adding or removing an item from a lesson
### Observed behavior

After adding or removing a resource from a lesson, the user is shown a notification and stays on the same page

### Expected behavior

In almost every case after adding or removing a resource, the immediate next step is to return to the parent list. It is unlikely the user would wish to remain on the detail page after making a decision to add or remove, so we should simply navigate immediately to the parent page.

### User-facing consequences

Extra clicks required during lesson management.

This feedback was reported by a partner:

> image

### Steps to reproduce

add and remove resources from a lesson using the detail page

### Context

0.13.2

### LINKED ISSUE #7212: Consistent snackbar messages when a resource added/removed to/from a lesson/quiz
Would be nice to display same messages in snackbars to coaches after a resource added/removed to/from a lesson/quiz while planning a class. 

### Observed behavior

- Navigate to lesson (Coach -> Plan -> Lessons -> select a lesson/create a new lesson -> MANAGE RESOURCES) and quiz (Coach -> Plan -> Quizzes -> create a new quiz)
- Open a resource preview

For lessons we display _Added/Removed 1 resource to lesson_ while for quizzes it's _Added/Removed '[exercise name]'_:

| Lesson | Quiz |
| --------- | ------- |
lesson-resource-added | quiz-resource-added |
| lesson-resource-removed | quiz-resource-removed |

### Expected behavior

Add/remove snackbars have same labels for lessons and quizzes.

### User-facing consequences

Inconsistency.

### PR DESCRIPTION
**Pull request by MisRob**
### Summary

Redirect coaches to a list after adding or removing an item from a lesson/quiz when planning a class. Display snackbar on a list page.

| Lesson | Quiz |
| --------- | ------- |
lesson-resource-added | quiz-resource-added |
| lesson-resource-removed | quiz-resource-removed |

### Reviewer guidance

**Lesson**
- Coach -> Plan -> Lessons -> select a lesson/create a new lesson -> MANAGE RESOURCES -> open a resource preview
- Click ADD/REMOVE

**Quiz**
- Coach -> Plan -> Quizzes -> create a new quiz -> open a resource preview
- Click ADD/REMOVE

### References

Closes #6819
Opened #7212

----

### Contributor Checklist

PR process:

- [x] PR has the correct target branch and milestone
- [x] PR has 'needs review' or 'work-in-progress' label
- [ ] If PR is ready for review, a reviewer has been added. (Don't use 'Assignees')
- [ ] If this is an important user-facing change, PR or related issue has a 'changelog' label
- [ ] If this includes an internal dependency change, a link to the diff is provided

Testing:

- [ ] Contributor has fully tested the PR manually
- [ ] If there are any front-end changes, before/after screenshots are included
- [ ] Critical user journeys are covered by Gherkin stories
- [ ] Critical and brittle code paths are covered by unit tests

### Reviewer Checklist

- Automated test coverage is satisfactory
- PR is fully functional
- PR has been tested for [accessibility regressions](http://kolibri-dev.readthedocs.io/en/develop/manual_testing.html#accessibility-a11y-testing)
- External dependency files were updated if necessary (`yarn` and `pip`)
- Documentation is updated
- Contributor is in AUTHORS.md

### CODE REVIEW

**Comment by jonboiser** [comment]
We should prevent the Preview pages  changing in appearance before navigating back to the resource-list page (see GIF).

Could you

1. Remove the "Added" indicator from appearing
1. Prevent the button label from switching from "Add" <-> "Remove" before redirect happens
1. (Optionally) disable the button to discourage double-clicking the button (even though double-clicking does not appear to cause problems)


CleanShot 2020-06-29 at 11 11 33

File: kolibri/plugins/coach/assets/src/views/plan/PlanQuizPreviewPage.vue [hunk 1]
```diff
@@ -55,11 +58,15 @@
       ...mapActions('examCreation', ['addToSelectedExercises', 'removeFromSelectedExercises']),
       handleAddResource(content) {
         this.addToSelectedExercises([content]);
-        this.createSnackbar(this.$tr('added', { item: this.currentContentNode.title }));
+        this.$router.push(this.returnBackRoute).then(() => {
+          this.createSnackbar(this.$tr('added', { item: this.currentContentNode.title }));
```
Comment (jonboiser) [inline kolibri/plugins/coach/assets/src/views/plan/PlanQuizPreviewPage.vue]: You can fix #7212 at this line by adding the `commonCoreString` mixin (which provides a `showSnackbarNotification` method) to the component and replacing the line here

```suggestion
          this.showSnackbarNotification('resourcesAddedWithCount', { count: 1 });
```

File: kolibri/plugins/coach/assets/src/views/plan/PlanQuizPreviewPage.vue [hunk 2]
```diff
@@ -55,11 +58,15 @@
...
+        });
       },
       handleRemoveResource(content) {
         this.removeFromSelectedExercises([content]);
-        this.createSnackbar(this.$tr('removed', { item: this.currentContentNode.title }));
+        this.$router.push(this.returnBackRoute).then(() => {
+          this.createSnackbar(this.$tr('removed', { item: this.currentContentNode.title }));
```
Comment (jonboiser) [inline kolibri/plugins/coach/assets/src/views/plan/PlanQuizPreviewPage.vue]: Similarly,

```suggestion
          this.showSnackbarNotification('resourcesRemovedWithCount', { count: 1 });
```

**Comment by jonboiser** [comment]
I also added some suggestions for fixing #7212 inside some comments

**Comment by MisRob** [comment]
Hi JB, thank you. I've just pushed all updates.

Regarding "Added" indicator, although it's not rendered after "Add" button click anymore, it's still displayed on the preview page load - is it fine or do you want to remove it completely? I've tried both options and it seems that keeping indicator for this situation makes visually clear if it's added or not at first glance when compared to displaying "Remove" button only.

**Comment by MisRob** [comment]
Also added a commit to unify snackbar messages that closes #7212.

File: kolibri/plugins/coach/assets/src/views/plan/LessonContentPreviewPage/index.vue [hunk 3]
```diff
@@ -173,6 +190,11 @@
         );
       },
     },
+    watch: {
+      isSelected() {
```
Comment (MisRob) [inline kolibri/plugins/coach/assets/src/views/plan/LessonContentPreviewPage/index.vue:194]: This watcher is not currently used though I added it because I would expect that `disableSelectButton` will be appropriately reset on selection state change.

**Review by jonboiser — APPROVED** [review]
The changes look great, thanks!

**Comment by jonboiser** [comment]
@MisRob I found a bug where if you removed the only resource in a lesson from the preview page, it would be automatically re-added when navigating back to the resource list (due to the complicated autosaving logic we use). I added one more commit as a hack to fix this by committing the resource removal _before_ the navigation, but keeping the Preview page buttons and indicators saying "added" until the navigation occurs.
