### PR TITLE
Mask sensitive fields in error reports and console logging

### LINKED ISSUE #13977: Error reporting page/workflow can show back plaintext password in "debug info" text recommended for submitting with bug report
❌ **This issue is not open for contribution. Visit <a href="https://learningequality.org/contributing-to-our-open-code-base/" target="_blank">Contributing guidelines</a>** to learn about the contributing process and how to find suitable issues.

## Observed behavior
I was attempting to set up a new instance of Kolibri for exposing out to the public web. For this deployment I was using google cloud, but this ticket isn't about my setup failure. When I went through the first time setup wizard I entered my admin password, and as this is intended to be exposed publicly I put a decent password instead of some random insecure thing I might use in a local dev environment. The setup process then failed and I was presented with the "something went wrong" message with the option to send info back to Kolibri for debugging.

Concerningly the details I could view before sending the report included the password I had just entered in plaintext. Looking back at the error page I do see that there isn't a simple single-click "submit" action, just a pointer to open an issue on the community forum, but nevertheless this blob of JSON could be very easily copied by someone wanting to file a bug and provide the info that the can in the forums without noticing their password appears at the end.

```
   {
  "data": "\n<!doctype html>\n<html lang=\"en\">\n<head>\n  <title>Server Error (500)</title>\n</head>\n<body>\n  <h1>Server Error (500)</h1><p></p>\n</body>\n</html>\n",
  "status": 500,
  "statusText": "Internal Server Error",
  "headers": {
    "content-length": "145",
    "content-security-policy": "frame-src 'self' data: blob: http: https:; default-src 'self' data: blob:; script-src 'self' blob:; style-src 'self' data: blob: 'unsafe-inline'",
    "content-type": "text/html",
    "date": "Fri, 05 Dec 2025 18:12:51 GMT",
    "referrer-policy": "same-origin",
    "server": "Cheroot/10.0.1",
    "vary": "Cookie",
    "x-content-type-options": "nosniff",
    "x-frame-options": "DENY"
  },
  "config": {
    "transitional": {
      "silentJSONParsing": true,
      "forcedJSONParsing": true,
      "clarifyTimeoutError": false
    },
    "adapter": [
      "xhr",
      "http",
      "fetch"
    ],
    "transformRequest": [
      null
    ],
    "transformResponse": [
      null
    ],
    "timeout": 0,
    "xsrfCookieName": "kolibri_csrftoken",
    "xsrfHeaderName": "X-CSRFToken",
    "maxContentLength": -1,
    "maxBodyLength": -1,
    "env": {},
    "headers": {
      "Accept": "application/json, text/plain, */*",
      "Content-Type": "application/json",
      "X-Requested-With": "XMLHttpRequest"
    },
    "paramsSerializer": {},
    "data": "{\"facility\":\"eaf5780cf4af0cc7530e61c7aa76f5a2\",\"username\":\"admin\",\"password\":\"SHOULD_NOT_BE_HERE\",\"user_id\":\"4e31fc570814eca727487fe82dae5e3b\",\"active\":true,\"browser\":{\"name\":\"Chrome\",\"major\":\"142\",\"minor\":\"0\",\"patch\":\"0\"},\"os\":{\"name\":\"Linux\",\"major\":\"x86_64\"}}",
    "url": "/api/auth/session/",
    "method": "post",
    "allowAbsoluteUrls": true
```

## Errors and logs
I'll open up a separate issue about the actual server error message, this is a bug report about exposing sensitive info in debug logging/reporting

## Expected behavior
Form submissions need to have some kind of infrastructure that will mask out sensitive data like this before it is serialized anywhere, logs, messages back to users, etc.

## User-facing consequences
Potential exposure of sensitive information.

## Steps to reproduce
Induce a failure in the API called at the end of the setup wizard.
## Context

### PR DESCRIPTION
**Pull request by rtibbles**
## Summary
Passwords and other sensitive data were being exposed in plaintext in error report dialogs and console logs.
Added a sanitizeError utility that masks sensitive fields in axios error objects before they are displayed or logged.

## References
Fixes #13977

## Reviewer guidance
Add `raise Exception` in `kolibri/core/auth/api.py` just before `login` is called, this will cause a 500 error on what should be a successful login. You should see in the "help us by reporting this error" modal that the password is not set to `*********` instead of the actual password.

### CODE REVIEW

File: packages/kolibri/utils/sanitizeError.js [hunk 1]
```diff
@@ -0,0 +1,49 @@
...
+    message: error.message,
+    name: error.name,
+    code: error.code,
+  };
+
+  if (error.config) {
+    let data = error.config.data;
+    if (typeof data === 'string') {
+      try {
+        data = JSON.stringify(maskObject(JSON.parse(data), SENSITIVE_FIELDS));
```
Comment (nucleogenesis) [inline packages/kolibri/utils/sanitizeError.js]: Because sometimes we might be getting an already-stringified JSON blob as the value here so we parse it so we can sanitize it? Did you run into this particular case or is it preemptive?

**Review by nucleogenesis — DISMISSED** [review]
Triggered the error on signup and login and saw sanitized error output in both cases. All looks good to me - just left a non-blocking question about some of the code.

File: packages/kolibri/utils/sanitizeError.js (hunk 1 above)
Comment (rtibbles) [reply packages/kolibri/utils/sanitizeError.js]: Woops, I forgot to attach the screenshot 
Screenshot From 2025-12-08 16-32-41

You can see here that the data is actually always a string (from the fact that it's already escaped when printing). And I notice that actually, this is _only_ sanitizing in the case that the data is a string, which isn't great. I think we can tighten this up somewhat.

File: packages/kolibri/utils/sanitizeError.js [hunk 2]
```diff
@@ -0,0 +1,54 @@
+import pickBy from 'lodash/pickBy';
+
+const SENSITIVE_FIELDS = ['password', 'token', 'secret', 'apikey', 'api_key'];
+const SENSITIVE_HEADERS = ['authorization', 'x-api-key', 'x-auth-token'];
+const MASK = '********';
+
+function maskObject(obj, sensitiveKeys) {
+  if (!obj || typeof obj !== 'object') return obj;
```
Comment (nucleogenesis) [inline packages/kolibri/utils/sanitizeError.js:8]: I asked myself "what happens when it's not an obj" while reading `_handleData` and this is the perfect answer :+1:

File: packages/kolibri/utils/sanitizeError.js [hunk 3]
```diff
@@ -0,0 +1,54 @@
...
+  return Object.fromEntries(
+    Object.entries(obj).map(([k, v]) => [k, sensitiveKeys.includes(k.toLowerCase()) ? MASK : v]),
+  );
+}
+
+function _handleData(data) {
```
Comment (nucleogenesis) [inline packages/kolibri/utils/sanitizeError.js:14]: (non-blocking) Any particular reason to _ prefix this fn vs maskObject?

**Review by nucleogenesis — APPROVED** [review]
LGTM - just a nitpicky question about function naming conventions. Quickly tested it again locally successfully!

File: packages/kolibri/utils/sanitizeError.js (hunk 3 above)
Comment (rtibbles) [reply packages/kolibri/utils/sanitizeError.js:14]: I wrote this function, and Claude wrote maskObject - no, no real reason.
