### PR TITLE
Fixed Overlapping Add New Class Button

### LINKED ISSUE #2262: Classes page responsive issue
## Summary

* 'Add a new class' button is NOT responding properly. The button was overlapping with text, in the middle of the screen. 
* Originally reported in https://docs.google.com/spreadsheets/d/1tYf6KP0t2CYMQmu7wHsfT47KPbTW0A0-8o_cPpQmUbM/edit#gid=0&range=31:31
## System information

* 0.6
* http://35.185.84.118

## How to reproduce

1. Sign in and visit the classes page under Facility.

### PR DESCRIPTION
**Pull request by GCodeON**
# Checklist

- [ ] PR has the correct target milestone when it's merged
- [ ] Automated test coverage is satisfactory
- [ ] PR has been fully tested manually
- [X] Screenshots of any front-end changes are in the PR description
- [x] You've added yourself to AUTHORS.rst if you're not there

# Details

### Summary

Fixed Overlapping Add New Class Button in class page under Facility
Check responsiveness of add new class button in the the facility app
2017-10-19 01 02 36 pm

### Reviewer guidance

Check that the add new class button is responsive across different screen sizes and does not overlap with any copy

### References

* Fixes #2262

### CODE REVIEW

**Comment by GCodeON** [comment]
Used Responsive Window Sizes to invoke dynamic css classes
2017-10-19 05 49 27 pm

**Comment by rtibbles** [comment]
I just resolved the merge conflict, but git is still showing me that there is one. I am assuming it is just lying to me.

Be sure to pull in the changes from your branch if you do any further edits here!

File: kolibri/plugins/management/assets/src/views/manage-class-page/index.vue [hunk 1]
```diff
@@ -2,11 +2,14 @@
 
   <div>
 
-    <div class="header">
-      <h1>{{ $tr('allClasses') }}</h1>
+    <div 
+      class="header"
```
Comment (rtibbles) [inline kolibri/plugins/management/assets/src/views/manage-class-page/index.vue]: How will this class and the dynamic class interact?

If the intention is that the dynamic class overwrites the non-dynamic class, it might be better to do the following:

`:class="{ 'header-mobile': windowSize.breakpoint <= 0, 'header': windowSize.breakpoint > 0}"`

Comment (indirectlylit) [reply kolibri/plugins/management/assets/src/views/manage-class-page/index.vue]: You can also use multiple classes to increase the specificity and explicitness of your overrides. For example, I might do something like this:

```html
<template>
  <div class="message" :class="{'mobile': windowSize.breakpoint <= 1}">
    Hello World
  </div>
</template>

<style scoped>

  .message
    position: absolute;
    top: 0;
    left: 0;
    font-size: 18px

  /* higher specificity because both classes are mentioned */
  .message.mobile
    font-size: 14px

</style>
```

however it looks like in this case, adding `.header-mobile` doesn't actually do anything!

```stylus
  .header
    position: relative
    padding-right: 150px
    margin-bottom: 16px

  .header-mobile
    position: relative
```

**Comment by rtibbles** [comment]
Note that your checks are currently failing because of eslint errors:
```
/kolibri/kolibri/plugins/management/assets/src/views/manage-class-page/index.vue
--
  | 7:33  error  Multiple spaces found before 'windowSize'                             vue/no-multi-spaces
  | 12:39  error  Multiple spaces found before 'windowSize'                             vue/no-multi-spaces
  | 112:5   error  The "mixins" property should be above the "data" property on line 82  vue/order-in-components
```
Be sure to use `kolibri manage devserver --debug -- --webpack --lint` to show these during builds, and also make sure you have the `pre-commit` hooks installed to catch these when you commit code!

**Comment by rtibbles** [comment]
@GCodeON one more linting issue:
```
    /home/travis/build/learningequality/kolibri/kolibri/plugins/management/assets/src/views/manage-class-page/index.vue
      111:5  error  The "mixins" property should be above the "data" property on line 81  vue/order-in-components
```

**Comment by rtibbles** [comment]
Seems like Travis is never going to report a status for this. The commit before I resolved the merge conflict tested fine, so I am merging.
