### PR TITLE
Fix mis-match condition in replacement question array

### LINKED ISSUE #12304: EQM: Replacements count messaging weirdness
## Overview

As reported by @ozer550  on [Notion](https://www.notion.so/learningequality/when-we-replace-questions-the-select-fewer-question-to-continue-prompt-keeps-on-increasing-and-is--059b0df1c31d4c07afd67b8046ad13c6)

I replicated this by selecting a lot of questions, adding only 10. Then I went to replace all of them. On the replacements list, I clicked "select all" then started individually deselecting items in the list. The number of how many fewer I should select increased.

### LINKED ISSUE #12335: The replacements array is continually increasing rather than adding and removing
[Slack Message](https://learningequality.slack.com/archives/CB37UM23A/p1718906948517539?thread_ts=1718906821.059399&cid=CB37UM23A)

### PR DESCRIPTION
**Pull request by marcellamaki**
## Summary
Fixes #12335 

## Reviewer guidance
Are the proper number of replacements reflected in the replacement selection once you have added more than the current number of questions to swap?

https://github.com/learningequality/kolibri/assets/17235236/43185bb8-c66f-4da3-9a51-d2801f5f8fda

----

## Testing checklist

- [ ] Contributor has fully tested the PR manually
- [ ] If there are any front-end changes, before/after screenshots are included
- [ ] Critical user journeys are covered by Gherkin stories
- [ ] Critical and brittle code paths are covered by unit tests

## PR process

- [ ] PR has the correct target branch and milestone
- [ ] PR has 'needs review' or 'work-in-progress' label
- [ ] If PR is ready for review, a reviewer has been added. (Don't use 'Assignees')
- [ ] If this is an important user-facing change, PR or related issue has a 'changelog' label
- [ ] If this includes an internal dependency change, a link to the diff is provided

## Reviewer checklist

- Automated test coverage is satisfactory
- PR is fully functional
- PR has been tested for [accessibility regressions](http://kolibri-dev.readthedocs.io/en/develop/manual_testing.html#accessibility-a11y-testing)
- External dependency files were updated if necessary (`yarn` and `pip`)
- Documentation is updated
- Contributor is in AUTHORS.md

### CODE REVIEW

File: kolibri/plugins/coach/assets/src/views/plan/CreateExamPage/ReplaceQuestions.vue [hunk 1]
```diff
@@ -251,9 +251,11 @@
       }
 
       function toggleInReplacements(question) {
-        const replacementIds = replacements.value.map(q => q.id);
-        if (replacementIds.includes(question.item)) {
-          replacements.value = replacements.value.filter(q => q.item !== question.item);
+        const replacementIds = replacements.value.map(r => r.question_id);
```
Comment (rtibbles) [inline kolibri/plugins/coach/assets/src/views/plan/CreateExamPage/ReplaceQuestions.vue]: I think this is an over correction. I suspect just changing id to item on the first line would be sufficient here.

The issue with the change made here is that question_id is not guaranteed to be unique across exercises, so the item property (which is a compound of the exercise_id and question_id) guarantees that the correct item is being replaced.

The original issue was due to the id property being removed from the question objects in favour of the previously and more widely used item property.

**Review by rtibbles — CHANGES_REQUESTED** [review]
Probably appears to fix the change but might introduce another, very subtle, bug.

**Review by rtibbles — APPROVED** [review]
Code changes make sense, and the behavioural fix is confirmed.
