### PR TITLE
Remote content browsing final polish

### LINKED ISSUE #10448: Final Polish - Remote content browsing UI and ensuring full feature flow is to spec
## Observed behavior
While the remote content browsing work is nearly finished, with most issues closed, there should be a "once over" and stitching together of the entire feature flow, and ensuring the front end is [to spec](https://www.figma.com/file/MpCG7r5PULOCJsEvnTSti8/Android-Designs-2022?node-id=1904-19105&t=ywHecBxsNAJuJ3Ke-0), so we can ✅  this issue as complete.

```[tasklist]
### Tasks
- [x] Ensure that the Kolibri Library 'pin' is disabled and not clickable
- [x] Ensure that when there are no pinned devices, some unpinned devices are displayed rather than an empty section and a 'More' button
- [x] Ensure that when there are no pinned devices, we omit the 'More' header, which is superfluous.
- [ ] Ensure that guest users do not see "partial" information (i.e. headings that are empty or for page sections that they are not able to see; buttons associated with missing/irrelevant sections), etc.
```

### PR DESCRIPTION
**Pull request by akolson**
## Summary

This pr polishes the remote content browsing UI

## References

Resolves https://github.com/learningequality/kolibri/issues/10448

## Reviewer guidance

UI should respond as specified in the [mockups](https://www.figma.com/file/MpCG7r5PULOCJsEvnTSti8/Android-Designs-2022?node-id=194-2922)

----

## Testing checklist

- [ ] Contributor has fully tested the PR manually
- [ ] If there are any front-end changes, before/after screenshots are included
- [ ] Critical user journeys are covered by Gherkin stories
- [ ] Critical and brittle code paths are covered by unit tests

## PR process

- [x] PR has the correct target branch and milestone
- [x] PR has 'needs review' or 'work-in-progress' label
- [x] If PR is ready for review, a reviewer has been added. (Don't use 'Assignees')
- [ ] If this is an important user-facing change, PR or related issue has a 'changelog' label
- [ ] If this includes an internal dependency change, a link to the diff is provided

## Reviewer checklist

- Automated test coverage is satisfactory
- PR is fully functional
- PR has been tested for [accessibility regressions](http://kolibri-dev.readthedocs.io/en/develop/manual_testing.html#accessibility-a11y-testing)
- External dependency files were updated if necessary (`yarn` and `pip`)
- Documentation is updated
- Contributor is in AUTHORS.md

### CODE REVIEW

**Review by marcellamaki — COMMENTED** [review]
I've done a _very_ quick code read through and nothing sticks out - and some of the vue component clean up looks 💯 - nice job @akolson 

I also did some preliminary manual QA with pinned/ no pinned devices, as a guest user, and as a learner. So far looking good. 

I feel okay about merging this and getting some good testing/feedback in during the bug catch tomorrow if @rtibbles doesn't see anything blocking in the code.

File: kolibri/plugins/learn/assets/src/routes/index.js [hunk 1]
```diff
@@ -111,6 +111,7 @@ export default [
     props: route => {
       return {
         deviceId: route.params.deviceId,
+        goBackRoute: route.params.goBackRoute,
```
Comment (rtibbles) [inline kolibri/plugins/learn/assets/src/routes/index.js:114]: Hrm, this doesn't seem quite right to me. The `goBackRoute` prop of the LibraryPage is a route object, but route params are strings, so I don't quite see how this is meant to be working.

File: kolibri/plugins/learn/assets/src/views/ExploreLibrariesPage/index.vue [hunk 2]
```diff
@@ -158,40 +182,39 @@
...
-            })
-            .catch(() => {
-              this.setNetworkDeviceChannels(device, [], 0);
-            });
-        }
+          accumulator.push(this.fetchChannels({ baseurl }));
+          return accumulator;
+        }, []);
+
+        Promise.allSettled(fetchDevicesChannels).then(devicesChannels => {
```
Comment (rtibbles) [inline kolibri/plugins/learn/assets/src/views/ExploreLibrariesPage/index.vue:191]: There's no loading state in the page while this is happening, and because one of the devices was taking a very long time to respond, I was just looking at a blank Explore Libraries page with no indication what was happening.

I think this change to waiting until all the channel fetches have been resolved makes a worse user experience, because it means that seeing other libraries is limited by the loading speed of the slowest library to load.

File: kolibri/plugins/learn/assets/src/routes/index.js (hunk 1 above)
Comment (rtibbles) [reply kolibri/plugins/learn/assets/src/routes/index.js:114]: Ah, I see how this is kind of working - the underlying params object does get modified, but it doesn't get encoded in the URL. Unfortunately, it means if the page is refreshed the back link no longer works.

I think this is probably best handled in a similar way to the other back links in Learn, by encoding the name of the page in the query parameters.

Can add an additional function to this composable for creating the library page back links: https://github.com/learningequality/kolibri/blob/develop/kolibri/plugins/learn/assets/src/composables/useContentLink.js#L7

**Review by rtibbles — APPROVED** [review]
We can merge this as is, but we should revisit the back links (as they will be broken on page refresh), and the delayed loading/loading state of the Explore libraries page.

Plus we should come back and fix the skipped tests too.
