### PR TITLE
inline download button and timestamp text

### LINKED ISSUE #5798: adjust facility data download layout
### Observed behavior

There is space for the "Generated 3 months ago" timestamp text alongside the download button, but instead it displays below:

> image

### Expected behavior

The <kbd>Download</kbd> button, the timestamp text, and the 'generate' link should each individually be inline block elements in a single line. This will allow them to wrap like so:

> image

ref: https://learningequality.slack.com/archives/CAKK24483/p1563918143002700?thread_ts=1563917105.000600&cid=CAKK24483

### User-facing consequences

The timestamp text is not as obviously associated with the 'Download' button as it should be, leading to potential confusion about why 'generate' and 'download' are independent actions.

### Context

0.12.5

### PR DESCRIPTION
**Pull request by priyanka-choubey**
### Summary

The timestamp text is moved such that it is inline with the download button in session logs as well as in summary logs.

Fixes #5798
----

### Contributor Checklist

PR process:

- [X] PR has the correct target branch and milestone
- [x] PR has 'needs review' or 'work-in-progress' label
- [x] If PR is ready for review, a reviewer has been added. (Don't use 'Assignees')
- [x] If this is an important user-facing change, PR or related issue has a 'changelog' label
- [ ] If this includes an internal dependency change, a link to the diff is provided

Testing:

- [X] Contributor has fully tested the PR manually
- [X] If there are any front-end changes, before/after screenshots are included
- [ ] Critical user journeys are covered by Gherkin stories
- [ ] Critical and brittle code paths are covered by unit tests

### Reviewer Checklist

- Automated test coverage is satisfactory
- PR is fully functional
- PR has been tested for [accessibility regressions](http://kolibri-dev.readthedocs.io/en/develop/manual_testing.html#accessibility-a11y-testing)
- External dependency files were updated if necessary (`yarn` and `pip`)
- Documentation is updated
- Contributor is in AUTHORS.md

## Before
Screenshot from 2020-03-15 21-23-43
## After
Screenshot from 2020-03-15 21-19-16

### CODE REVIEW

**Comment by priyanka-choubey** [comment]
@indirectlylit @jonboiser @kollivier The changes have been made in both session logs as well as summary logs. kindly review. thanks

File: kolibri/plugins/facility/assets/src/views/DataPage/index.vue [hunk 1]
```diff
@@ -22,6 +22,8 @@
               class="download-button"
               @click="downloadSessionLog"
             />
+            <span v-if="noSessionLogs"> {{ $tr('noLogsYet') }} </span>
```
Comment (jonboiser) [inline kolibri/plugins/facility/assets/src/views/DataPage/index.vue]:
```suggestion
            <span v-if="noSessionLogs">{{ $tr('noLogsYet') }}</span>
```

For code style: remove the extra space inside the tags

File: kolibri/plugins/facility/assets/src/views/DataPage/index.vue [hunk 2]
```diff
@@ -30,8 +32,7 @@
             <DataPageTaskProgress />
           </p>
           <p v-else>
-            <span v-if="noSessionLogs"> {{ $tr('noLogsYet') }} </span>
-            <GeneratedElapsedTime v-else :date="sessionDateCreated" />
+
```
Comment (jonboiser) [inline kolibri/plugins/facility/assets/src/views/DataPage/index.vue:35]: Can remove this extra newline

File: kolibri/plugins/facility/assets/src/views/DataPage/index.vue [hunk 3]
```diff
@@ -53,6 +54,8 @@
               class="download-button"
               @click="downloadSummaryLog"
             />
+            <span v-if="noSummaryLogs"> {{ $tr('noLogsYet') }} </span>
```
Comment (jonboiser) [inline kolibri/plugins/facility/assets/src/views/DataPage/index.vue]:
```suggestion
            <span v-if="noSummaryLogs">{{ $tr('noLogsYet') }}</span>
```

**Comment by jonboiser** [comment]
@priyanka-choubey The code looks good, just added a few notes to clean up the code style in this Vue file.

Could you also double check that the layout of these pages look okay in a narrow browser (e.g. on a tablet or small phone). No need to post screenshots. Thanks!

**Comment by jonboiser** [comment]
I actually did find a small bug when creating a CSV file for the first time. The message will say

1. "No logs yet"
1. (After presssing button) "Generated 50 years ago"
1. "Generated moments ago"

Could you take a look to see if there is a way to fix the `v-if` guards to see if we can avoid the "generated 50 years ago" message?

To reset your system, you can go to your Kolibri Home folder and delete the CSV files from the `/log_export` folder.

File: kolibri/plugins/facility/assets/src/views/DataPage/index.vue (hunk 1 above)
Comment (indirectlylit) [reply kolibri/plugins/facility/assets/src/views/DataPage/index.vue]: Agreed, and not just for code style: sometimes extraneous whitespace causes confusing rendering bugs.

However, noted that this issue existed in the old code!

File: kolibri/plugins/facility/assets/src/views/DataPage/index.vue [hunk 4]
```diff
@@ -22,6 +22,8 @@
               class="download-button"
               @click="downloadSessionLog"
             />
+            <span v-if="noSessionLogs">{{ $tr('noLogsYet') }}</span>
+            <GeneratedElapsedTime v-else :date="sessionDateCreated" />
```
Comment (jonboiser) [inline kolibri/plugins/facility/assets/src/views/DataPage/index.vue]: See if this change works to prevent the "generated 50 years ago" bug

```suggestion
            <GeneratedElapsedTime v-else-if="sessionDateCreated" :date="sessionDateCreated" />
```

File: kolibri/plugins/facility/assets/src/views/DataPage/index.vue [hunk 5]
```diff
@@ -53,6 +54,8 @@
               class="download-button"
               @click="downloadSummaryLog"
             />
+            <span v-if="noSummaryLogs">{{ $tr('noLogsYet') }}</span>
+            <GeneratedElapsedTime v-else :date="summaryDateCreated" />
```
Comment (jonboiser) [inline kolibri/plugins/facility/assets/src/views/DataPage/index.vue]:
```suggestion
            <GeneratedElapsedTime v-else-if="summaryDateCreated" :date="summaryDateCreated" />
```

**Comment by priyanka-choubey** [comment]
@jonboiser @indirectlylit it seems to be working fine now. Kindly review
ezgif com-video-to-gif

**Review by jonboiser — APPROVED** [review]
Looks good!
