### PR TITLE
Fix client side 'server' time setting to prevent spooky interactions in the future

### LINKED ISSUE #5079: 'last activity' can be in the future
### Observed behavior

Noticed that the 'last activity' column very briefly said "in 3 seconds", indicating a negative value:

image

### Expected behavior

We should determine how it happened that the value went negative and prevent it.

One thing to be particularly careful of is that we're always comparing server time to server time, and never server time to client time because they could be very different. This bug might be due to that.

Let's also add a gherkin story that explicitly tests various parts of the app when the server and client times are different. (cc @radinamatic @mrpau-dev)

### User-facing consequences

If server and client times are very different, values in this column may be days or even years off

### Steps to reproduce

unknown, but possibly try changing your local computer time and then browsing the beta server (assuming the theory above is correct)

### Context

0.12.0 beta 6

### PR DESCRIPTION
**Pull request by rtibbles**
### Summary
We now set the 'server time' not at page load, but through the session object.
This meant that it was being updated more than once during a session.
Previously, we were using the performance timing API to calculate the start of the page load request, in order to give a time for diffing.
This meant that as time moved on in the client side without a page load, the diff became larger and larger, proportional to the length of time since page load.
This made time stamps in the future as a result.

### Reviewer guidance
Follow steps to reproduce here: https://github.com/learningequality/kolibri/issues/5079#issuecomment-468082659

See that this no longer occurs.

### References
Fixes #5079 

----

### Contributor Checklist

PR process:

- [x] PR has the correct target branch and milestone
- [x] PR has 'needs review' or 'work-in-progress' label
- [x] If PR is ready for review, a reviewer has been added. (Don't use 'Assignees')
- [ ] If this is an important user-facing change, PR or related issue has a 'changelog' label
- [ ] If this includes an internal dependency change, a link to the diff is provided

Testing:

- [x] Contributor has fully tested the PR manually
- [ ] If there are any front-end changes, before/after screenshots are included
- [ ] Critical user journeys are covered by Gherkin stories
- [x] Critical and brittle code paths are covered by unit tests

### Reviewer Checklist

- Automated test coverage is satisfactory
- PR is fully functional
- PR has been tested for [accessibility regressions](http://kolibri-dev.readthedocs.io/en/develop/manual_testing.html#accessibility-a11y-testing)
- External dependency files were updated if necessary (`yarn` and `pip`)
- Documentation is updated
- Contributor is in AUTHORS.rst

### CODE REVIEW

File: kolibri/core/assets/src/heartbeat.js [hunk 1]
```diff
@@ -153,6 +153,8 @@ export class HeartBeat {
         })
       );
     }
+    // Log the time at the start of the request for time diff setting.
+    const pollStart = new Date();
```
Comment (indirectlylit) [inline kolibri/core/assets/src/heartbeat.js]: suuuper minor but I've always found `new Date()` to be an obfuscated way of getting the current date and time. Could possibly standardize on `Date.now()`

**Review by indirectlylit — COMMENTED** [review]
hah time dilation

**Review by jonboiser — APPROVED** [review]
Manually tested Kolibri with and without this patch

without patch: last activity was quoted at 8 min in the future
with patch: last activity was quoted at ~10 sec in the future (might have been from the notification). after a refresh, last activity was in the past.

File: kolibri/core/assets/src/heartbeat.js (hunk 1 above)
Comment (rtibbles) [reply kolibri/core/assets/src/heartbeat.js]: Except that `Date.now()` returns the time in milliseconds since epoch, whereas `new Date()` returns a date object. Given how I end up using them in the calculation below, `Date.now()` would work, but I wouldn't necessarily want to standardize on it.

**Comment by indirectlylit** [comment]
> last activity was quoted at ~10 sec in the future (might have been from the notification)

I don't quite understand - why are we still seeing future times?
