### PR TITLE
Fix runtime error going to recommended 'view more' page

### LINKED ISSUE #2240: Recommended view more broken
## Summary

Recommended view more page is broken

## Version

0.6

## Error

```
recommended.js:83 Uncaught (in promise) TypeError: Cannot read property 'length' of undefined
```

## Error source

https://github.com/learningequality/kolibri/blob/9ae52f66977590f59ba0c641e97b9fda9e186b7f/kolibri/plugins/learn/assets/src/state/actions/recommended.js#L83

## How to reproduce

1. Go to Learn Recommended Page
2. Click on View More

### PR DESCRIPTION
**Pull request by jonboiser**
Probably fixes #2240 (manual tests works), but mainly guessing at what the original intention was.

### CODE REVIEW

File: kolibri/plugins/learn/assets/src/state/actions/recommended.js [hunk 1]
```diff
@@ -76,10 +68,10 @@ function _showRecSubpage(store, getContentPromise, pageName, windowTitleId, chan
     getContentPromise(state, channelId),
     setAndCheckChannels(store),
     // resolves to mapped content set because then resolves to its function's return value
-  ]).then(([content]) => _mapContentSet(content), error => error);
+  ]).then(([content, channels]) => [_mapContentSet(content), error => error, channels]);
```
Comment (rtibbles) [inline kolibri/plugins/learn/assets/src/state/actions/recommended.js]: The scope of the second array is wrong here, the error handling function should be outside of the array, and channels should be the second element.

Comment (jonboiser) [reply kolibri/plugins/learn/assets/src/state/actions/recommended.js]: Gotcha. I think the `error => error` can be dropped, since it defaults to identity function.

Comment (jonboiser) [reply kolibri/plugins/learn/assets/src/state/actions/recommended.js]: Amazingly, the bad array didn't seem to have an effect on the code, though. Apparently, a function has length `0`, and there is nothing in the pagePrep.then callback utilizing channels if length is not 0.

Comment (rtibbles) [reply kolibri/plugins/learn/assets/src/state/actions/recommended.js]: I would guess it is `undefined` rather than zero, but still falsy nevertheless!
