### PR TITLE
Fix Mismatch between coach Reports and generated CSV

### LINKED ISSUE #6642: Mismatch between coach Reports and generated CSV
### Observed behavior

1. On ReportsLessonExerciseLearnerListPage, if "view by groups" checkbox is toggled, ungrouped learners aren't in the report. The report should be the same regardless of view (ungrouped learners appear in the report even if "view by groups is checked")

Screenshot
Screen Shot 2020-03-09 at 4 05 45 PM

Exported CSV

```
"Group name","Name","Progress","Time spent","Last activity"
```

~2. ReportsQuizLearnerListPage - there is a subtile under "progress" saying e.g. "3 of 10 questions answered", which isn't on the CSV. Might be useful.~ Added some extra columns in this report (total/answered/correct questions)

Screen Shot 2020-03-12 at 1 20 38 PM

3. QuizReportsListPage (and others) - There's no "Total learners" field, just tallies for different statuses, whereas "Difficult Questions" on exam report does show tally for all learners.

4. Some numbers and percentages are being printed as strings e.g. `"50%"` and `"10"` instead of as numbers. Might not be auto-parsed correctly in some software.

### Expected behavior

…

### User-facing consequences

…

### Errors and logs

…

### Steps to reproduce

…

### Context

…

### PR DESCRIPTION
**Pull request by AlexVelezLl**
## Summary

Fix mismatch between coach Reports and generated CSV.

Fixes:

* Now `ReportsLessonExerciseLearnerListPage` and `ReportsLessonResourceLearnerListPage` show ungrouped learners if "view by groups" checkbox is toggled.
* Fix `ReportsLessonExerciseLearnerListPage` and `ReportsLessonResourceLearnerListPage` to show groups names if we download a report without checking "view by groups".
* Fix empty "last activity" column in `ReportsLessonExerciseLearnerListPage`, `ReportsGroupReportLessonExerciseLearnerListPage`, `ReportsGroupReportLessonResourceLearnerListPage`, `ReportsLessonResourceLearnerListPage`.
* New column "All Learners" in `ReportsQuizListPage` and `ReportsLessonListPage`.
* Fix time spent label not displaying correctly in `ReportsGroupReportLessonExerciseLearnerListPage`, `ReportsGroupReportLessonResourceLearnerListPage`, `ReportsLearnerReportLessonPage`, `ReportsLessonExerciseLearnerListPage`, `ReportsLessonLearnerBase`, `ReportsLessonResourceLearnerListPage`.

Things that have already been fixed in the past:

* ReportsQuizLearnerListPage already shows the columns total/answered/correct questions.
* No issues found in the option to export a quiz report as CSV.
* No issues found about Average score value not displaying correctly in groups reports.

## References

Closes #6642

## Reviewer guidance

…

----

## Testing checklist

- [x] Contributor has fully tested the PR manually
- [ ] If there are any front-end changes, before/after screenshots are included
- [ ] Critical user journeys are covered by Gherkin stories
- [ ] Critical and brittle code paths are covered by unit tests

## PR process

- [x] PR has the correct target branch and milestone
- [x] PR has 'needs review' or 'work-in-progress' label
- [ ] If PR is ready for review, a reviewer has been added. (Don't use 'Assignees')
- [ ] If this is an important user-facing change, PR or related issue has a 'changelog' label
- [ ] If this includes an internal dependency change, a link to the diff is provided

## Reviewer checklist

- PR is fully functional
- PR has been tested for [accessibility regressions](http://kolibri-dev.readthedocs.io/en/develop/manual_testing.html#accessibility-a11y-testing)
- External dependency files were updated if necessary (`yarn` and `pip`)
- Documentation is updated
- Contributor is in AUTHORS.md

### CODE REVIEW

**Comment by pcenov** [comment]
Thanks @AlexVelezLl - I confirm that the issues are addressed and fixed as specified above.
While regression testing I was also able to identify the following issues (I can create follow-up issues if they are not in scope for this PR):

1. In Coach > Reports > Lessons > "Lesson 1" > "Resource 1" when I export the report as CSV I see `CommonCoachStrings.timeSpentLabel` instead of the the Time spent label and also the `Last activity` value is displayed only for exercises while for any other type of resources such as PDF or video it's not:

last activity

2. For resources other than exercises if I have selected the 'View by groups' checkbox then when I export the report as CSV I don't see the ungrouped learners:

ungrouped learners

3. For all resources if I have not selected the 'View by groups' checkbox then when I export the report as CSV I don't see the name of the groups:

no-group-names

cc @radinamatic

**Comment by AlexVelezLl** [comment]
Thank you @pcenov! I have pushed new changes fixing these issues too.

**Review by pcenov — APPROVED** [review]
Thanks @AlexVelezLl - I confirm that the latest issues are fixed and there are no new issues after the regression testing - good to go!

File: kolibri/plugins/coach/assets/src/csv/fields.js [hunk 1]
```diff
@@ -216,10 +228,10 @@ export function tally() {
   ];
 }
 
-export function timeSpent(key, label = 'timeSpentLabel') {
+export function timeSpent(key, label = coreStrings.$tr('timeSpentLabel')) {
```
Comment (rtibbles) [inline kolibri/plugins/coach/assets/src/csv/fields.js]: I'd prefer to still invoke the $tr method in function scope rather than module scope (which it will for a default) - just in case there's a race condition here between i18n setup and execution of this module code.

It's possible that I am remembering a gotcha that I have since fixed, but out of abundance of caution let's keep the invocation in function scope for now.

**Comment by AlexVelezLl** [comment]
Thank you @rtibbles! I have pushed the required changes :open_hands:.

File: kolibri/plugins/coach/assets/src/views/reports/ReportsLessonExerciseLearnerListPage.vue [hunk 2]
```diff
@@ -271,8 +271,8 @@
           .reduce((entries, groupEntries) => entries.concat(groupEntries), []);
 
         if (this.ungroupedEntries.length) {
-          data.concat(
-            this.ungroupedEntries.map(entry => {
+          data.push(
```
Comment (nucleogenesis) [inline kolibri/plugins/coach/assets/src/views/reports/ReportsLessonExerciseLearnerListPage.vue:274]: I don't recall having seen using `arr.push(...someArray)` in place of `arr.concat(someArray)` before but _I like it_!

Comment (nucleogenesis) [reply kolibri/plugins/coach/assets/src/views/reports/ReportsLessonExerciseLearnerListPage.vue:274]: Did you make this change as a style change or do you know if this improves performance or something?

**Review by nucleogenesis — APPROVED** [review]
I see that @rtibbles feedback has been addressed, calling the i18n in the function scope and gave things a look myself. This all LGTM

File: kolibri/plugins/coach/assets/src/views/reports/ReportsLessonExerciseLearnerListPage.vue (hunk 2 above)
Comment (nucleogenesis) [reply kolibri/plugins/coach/assets/src/views/reports/ReportsLessonExerciseLearnerListPage.vue:274]: Playing with it a little bit I realize that the `push` version mutates the object itself whereas `concat` returns a whole new array so was the previous code an issue because of that?

Comment (AlexVelezLl) [reply kolibri/plugins/coach/assets/src/views/reports/ReportsLessonExerciseLearnerListPage.vue:274]: Yeees!! The error why ungrouped learners didnt appear in the report was because the `concat` method doesnt work in-place, and we werent reassigning the result, but as `data` was a constant, and we couldnt reassign I preferred to use the `push(...array)` instead of defining the constant as variable.

**Comment by AlexVelezLl** [comment]
Thank you @nucleogenesis and @pcenov!
