### PR TITLE
Reset selection after applying filter

### LINKED ISSUE #13868: Facility > Users - Any selected users remain selected even after having applied additional filters
❌ **This issue is not open for contribution. Visit <a href="https://learningequality.org/contributing-to-our-open-code-base/" target="_blank">Contributing guidelines</a>** to learn about the contributing process and how to find suitable issues.

## Observed behavior

A potentially confusing issue I noticed while testing https://github.com/learningequality/kolibri/pull/13865 but which is also extant in https://github.com/learningequality/kolibri/releases/tag/v0.19.0-beta1 is that if I select all the users and then apply a filter, all of the previously selected users remain selected.

https://github.com/user-attachments/assets/d951b976-dc8e-413a-9ece-e01b6af34ebb

## Expected behavior

This should be further discussed and specified but I would expect that after applying any additional filters, the users for which the filters do not apply should no longer be selected so that I can perform the available assign, enroll, remove and delete operations only on the filtered users.
 
## Steps to reproduce the issue

1. Install the build from https://github.com/learningequality/kolibri/releases/tag/v0.19.0-beta1
2. Go to Device > Users and select all of the available users.
3. Apply a filter and observe that the number of selected users remains the same.

## Usage Details
[﻿Kolibri 0.19.0b1](https://github.com/learningequality/kolibri/releases/tag/v0.19.0-beta1)
Windows 11, Ubuntu 22, Mac OS 15.5  - Chrome, Firefox

### PR DESCRIPTION
**Pull request by AllanOXDi**
## Summary
This PR fixes any selected users remain selected even after having applied additional filters
Closes [#13868](https://github.com/learningequality/kolibri/issues/13868)

## References
[#13868](https://github.com/learningequality/kolibri/issues/13868)
#### Before
https://private-user-images.githubusercontent.com/79847249/507123504-d951b976-dc8e-413a-9ece-e01b6af34ebb.mp4?jwt=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3NjI0NDMyODcsIm5iZiI6MTc2MjQ0Mjk4NywicGF0aCI6Ii83OTg0NzI0OS81MDcxMjM1MDQtZDk1MWI5NzYtZGM4ZS00MTNhLTllY2UtZTAxYjZhZjM0ZWJiLm1wND9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNTExMDYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjUxMTA2VDE1Mjk0N1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWQyZjVmZmY4NTRlZGJiOWI4NmE2OWI3ZGUwZDJhOWI1ZWY0M2Q4NjE1NDMyZDZiOGE4MGYwMDRiNmRmNmE5MWYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.s5zCGcz8aP-kzFDWPOEx9D-OoJvfAdSbYudZEFxHaMM

#### After

https://github.com/user-attachments/assets/d81560ac-abbe-4219-be31-950c77d4f333

## Reviewer guidance

2. Go to Device > Users and select all of the available users.
3. Apply a filter and observe that the number of selected users remains the same.

### CODE REVIEW

File: kolibri/plugins/facility/assets/src/views/users/UsersRootPage/index.vue [hunk 1]
```diff
@@ -279,6 +279,12 @@
         fetchClasses();
       });
 
+      watch([numAppliedFilters, searchTerm], (newValues, oldValues) => {
+        if (newValues[0] !== oldValues[0] || newValues[1] !== oldValues[1]) {
+          clearSelectedUsers();
+        }
+      });
```
Comment (nucleogenesis) [inline kolibri/plugins/facility/assets/src/views/users/UsersRootPage/index.vue]: The logic here looks good to me. However the behavior needs to also apply to the NewUserPage and UsersTrashPage components.

You could look at putting this logic into the [useUserManagement.js](https://github.com/learningequality/kolibri/blob/3938485b54e46975c17760d5734a40414316db7e/kolibri/plugins/facility/assets/src/composables/useUserManagement.js#L16) composable - looks like we have the `search` and `numAppliedFilters` and it also houses the list of `selectedUsers` - so might be able to feed 3 birds with 1 stone since the other user table pages use useUserManagement for these values.

**Review by nucleogenesis — CHANGES_REQUESTED** [review]
The logic works but the behavior change needs to be applied to all three users table variants. Left a suggestion for your consideration. Thanks @AllanOXDi !

File: kolibri/plugins/facility/assets/src/composables/useUserManagement.js [hunk 2]
```diff
@@ -33,6 +33,11 @@ export default function useUserManagement({
     classes,
   });
 
+  const clearSelectedUsers = () => {
+    selectedUsers.value.clear();
+    selectedUsers.value = new Set(selectedUsers.value);
```
Comment (nucleogenesis) [inline kolibri/plugins/facility/assets/src/composables/useUserManagement.js]: This feels odd - does calling `clear()` not update the value reactively? 

This seems like it's doing the same thing as `selectedUsers.value = new Set()`.

File: kolibri/plugins/facility/assets/src/composables/useUserManagement.js [hunk 3]
```diff
@@ -108,6 +113,15 @@ export default function useUserManagement({
     { immediate: true },
   );
 
+  watch([numAppliedFilters, search], (newValues, oldValues) => {
+    const [newNumFilters, newSearch] = newValues;
+    const [oldNumFilters, oldSearch] = oldValues;
+
+    if (newNumFilters !== oldNumFilters || newSearch !== oldSearch) {
```
Comment (nucleogenesis) [inline kolibri/plugins/facility/assets/src/composables/useUserManagement.js]: I like this change - it's more clear what is happening this way than before where it indexed into the arrays.

File: kolibri/plugins/facility/frontend/views/users/UsersRootPage/index.vue [hunk 4]
```diff
@@ -279,10 +278,6 @@
         fetchClasses();
       });
 
-      function clearSelectedUsers() {
-        selectedUsers.value = new Set();
-      }
-
```
Comment (nucleogenesis) [inline kolibri/plugins/facility/frontend/views/users/UsersRootPage/index.vue:285]: This is also present in the new user and trash pages and could likewise be removed in favor of your new `clearSelectedUsers` method returned from `useUserManagement`

File: kolibri/plugins/facility/assets/src/composables/useUserManagement.js (hunk 2 above)
Comment (AllanOXDi) [reply kolibri/plugins/facility/assets/src/composables/useUserManagement.js]: Doing this help us to clear the selection on the user page

**Review by nucleogenesis — CHANGES_REQUESTED** [review]
Just a question re: how you're clearing the selection.

The other thing that'd be great to get in is to use your new method in all three of the user table variants (+Trash page, +New users page)

File: kolibri/plugins/facility/frontend/views/users/UsersRootPage/index.vue (hunk 4 above)
Comment (AllanOXDi) [reply kolibri/plugins/facility/frontend/views/users/UsersRootPage/index.vue:285]: Got it!

File: kolibri/plugins/facility/assets/src/composables/useUserManagement.js (hunk 2 above)
Comment (nucleogenesis) [reply kolibri/plugins/facility/assets/src/composables/useUserManagement.js]: Did just setting `selectedUsers.value = new Set()` not work properly in this location?

Comment (AllanOXDi) [reply kolibri/plugins/facility/assets/src/composables/useUserManagement.js]: I misunderstood you earlier btw 🤦🏾‍♂️

**Review by nucleogenesis — APPROVED** [review]
Code changes look good to me & tested across New, Trash and normal Users pages successfully! Thanks for the quick turnaround @AllanOXDi

**Review by nucleogenesis — DISMISSED** [review]
Adding a blocking review as we are a bit uncertain on the desired behavior - perhaps this will be a good item to get user testing feedback on as well?

Also just want to avoid merging this in case we would rather target the release branch. (cc @marcellamaki @radinamatic )

**Comment by nucleogenesis** [comment]
Noting here that we've come to a decision to merge this experience. @tomiwaoLE has some early work on a revision to the table that would improve the table experience which we'll come back to when time/priorities align.

So - this needs to be rebased and probably a quick pass at some manual QA would be worthwhile to check for rebase-related regressions.

**Review by pcenov — APPROVED** [review]
Thanks @AllanOXDi - I confirm that after applying a filter or searching for a user the previously selected users are no longer selected.
