### PR TITLE
Fix fullscreen for Chrome 71

### LINKED ISSUE #4680: Full Screen Fails on Chromium  71 and Vivaldi
### Observed behavior
Using Chromium 71 or  Vivaldi 2.2.1388.34, the full screen button for BOOK resources  either does nothing or distorts.
Using Firefox there is no problem. It does not affect video resources such as Sikana

### User-facing consequences
Very difficult to read books…

### Errors and logs
1809eba4-bad0-4e8d-9011-645243368501

Distortion:
c58eef80-61b3-4cf4-bb84-9af8830cc31b

Browser Console

> default_frontend-0.11.0.js:33 Uncaught (in promise) TypeError: Failed to execute 'requestFullscreen' on 'Element': parameter 1 ('options') is not an object.
>     at Object.request (default_frontend-0.11.0.js:33)
>     at Object.toggle (default_frontend-0.11.0.js:33)
>     at a.enterFullScreen (default_frontend-0.11.0.js:218)
>     at a.toggleFullscreen (default_frontend-0.11.0.js:218)
>     at click (document_pdf_render_module-0.11.0.js:15)
>     at a.t (default_frontend-0.11.0.js:7)
>     at a.e.$emit (default_frontend-0.11.0.js:7)
>     at a.onClick (document_pdf_render_module-0.11.0.js:15)
>     at t (default_frontend-0.11.0.js:7)
>     at HTMLButtonElement.t._withTask.i._withTask (default_frontend-0.11.0.js:7)
> request @ default_frontend-0.11.0.js:33
> toggle @ default_frontend-0.11.0.js:33
> enterFullScreen @ default_frontend-0.11.0.js:218
> toggleFullscreen @ default_frontend-0.11.0.js:218
> click @ document_pdf_render_module-0.11.0.js:15
> t @ default_frontend-0.11.0.js:7
> e.$emit @ default_frontend-0.11.0.js:7
> onClick @ document_pdf_render_module-0.11.0.js:15
> t @ default_frontend-0.11.0.js:7
> t._withTask.i._withTask @ default_frontend-0.11.0.js:7
> 62XHR finished loading: PATCH "<URL>".
> 31XHR finished loading: GET "<URL>".
> default_frontend-0.11.0.js:207 [INFO: kolibri/core/assets/src/core-app/mediator.js] KolibriModule: html5_app_renderer_module registered
> default_frontend-0.11.0.js:231 XHR finished loading: POST "http://192.168.1.100:8087/api/logger/contentsessionlog/?1546596786456=1546596786456".
> (anonymous) @ default_frontend-0.11.0.js:231
> (anonymous) @ default_frontend-0.11.0.js:389
> i @ default_frontend-0.11.0.js:389
> d.promise @ default_frontend-0.11.0.js:27
> f.promise @ default_frontend-0.11.0.js:65
> (anonymous) @ default_frontend-0.11.0.js:231
> a @ default_frontend-0.11.0.js:153
> (anonymous) @ default_frontend-0.11.0.js:26
> (anonymous) @ default_frontend-0.11.0.js:389
> I @ default_frontend-0.11.0.js:389
> _.when @ default_frontend-0.11.0.js:389
> O.run @ default_frontend-0.11.0.js:389
> e._drain @ default_frontend-0.11.0.js:388
> drain @ default_frontend-0.11.0.js:388
> e.observe.characterData @ default_frontend-0.11.0.js:52
> characterData (async)
> (anonymous) @ default_frontend-0.11.0.js:52
> e.run @ default_frontend-0.11.0.js:388
> e.enqueue @ default_frontend-0.11.0.js:388
> b.when @ default_frontend-0.11.0.js:389
> m.chain @ default_frontend-0.11.0.js:389
> i.then @ default_frontend-0.11.0.js:389
> d @ default_frontend-0.11.0.js:27
> f @ default_frontend-0.11.0.js:65
> e @ default_frontend-0.11.0.js:26
> t.default @ default_frontend-0.11.0.js:33
> w.client @ default_frontend-0.11.0.js:1
> (anonymous) @ default_frontend-0.11.0.js:1
> Promise.then (async)
> (anonymous) @ default_frontend-0.11.0.js:1
> r @ default_frontend-0.11.0.js:13
> g.fetch @ default_frontend-0.11.0.js:1
> w.fetchCollection @ default_frontend-0.11.0.js:1
> I @ default_frontend-0.11.0.js:46
> (anonymous) @ default_frontend-0.11.0.js:13
> l.dispatch @ default_frontend-0.11.0.js:13
> dispatch @ default_frontend-0.11.0.js:13
> n.(anonymous function) @ default_frontend-0.11.0.js:13
> initSession @ learn_module-0.11.0.js:1
> updateRendererComponent @ default_frontend-0.11.0.js:46
> created @ default_frontend-0.11.0.js:46
> xt @ default_frontend-0.11.0.js:7
> e._init @ default_frontend-0.11.0.js:7
> a @ default_frontend-0.11.0.js:7
> (anonymous) @ default_frontend-0.11.0.js:7
> init @ default_frontend-0.11.0.js:7
> (anonymous) @ default_frontend-0.11.0.js:7
> f @ default_frontend-0.11.0.js:7
> d @ default_frontend-0.11.0.js:7
> f @ default_frontend-0.11.0.js:7
> (anonymous) @ default_frontend-0.11.0.js:7
> e._update @ default_frontend-0.11.0.js:7
> (anonymous) @ default_frontend-0.11.0.js:7
> Lt.get @ default_frontend-0.11.0.js:7
> Lt @ default_frontend-0.11.0.js:7
> e @ default_frontend-0.11.0.js:7
> fn.$mount @ default_frontend-0.11.0.js:7
> init @ default_frontend-0.11.0.js:7
> (anonymous) @ default_frontend-0.11.0.js:7
> f @ default_frontend-0.11.0.js:7
> d @ default_frontend-0.11.0.js:7
> f @ default_frontend-0.11.0.js:7
> d @ default_frontend-0.11.0.js:7
> f @ default_frontend-0.11.0.js:7
> (anonymous) @ default_frontend-0.11.0.js:7
> C @ default_frontend-0.11.0.js:7
> (anonymous) @ default_frontend-0.11.0.js:7
> e._update @ default_frontend-0.11.0.js:7
> (anonymous) @ default_frontend-0.11.0.js:7
> Lt.get @ default_frontend-0.11.0.js:7
> Lt.run @ default_frontend-0.11.0.js:7
> Nt @ default_frontend-0.11.0.js:7
> (anonymous) @ default_frontend-0.11.0.js:7
> We @ default_frontend-0.11.0.js:7
> Promise.then (async)
> Ge @ default_frontend-0.11.0.js:7
> Ze @ default_frontend-0.11.0.js:7
> (anonymous) @ default_frontend-0.11.0.js:7
> Lt.update @ default_frontend-0.11.0.js:7
> ue.notify @ default_frontend-0.11.0.js:7
> set @ default_frontend-0.11.0.js:7
> SET_STATE @ learn_module-0.11.0.js:1
> (anonymous) @ default_frontend-0.11.0.js:13
> (anonymous) @ default_frontend-0.11.0.js:13
> (anonymous) @ default_frontend-0.11.0.js:13
> l._withCommit @ default_frontend-0.11.0.js:13
> l.commit @ default_frontend-0.11.0.js:13
> commit @ default_frontend-0.11.0.js:13
> (anonymous) @ learn_module-0.11.0.js:1
> (anonymous) @ default_frontend-0.11.0.js:13
> Promise.then (async)
> r.only @ default_frontend-0.11.0.js:13
> (anonymous) @ learn_module-0.11.0.js:1
> handler @ learn_module-0.11.0.js:1
> ri._hook @ default_frontend-0.11.0.js:218
> p @ default_frontend-0.11.0.js:218
> r @ default_frontend-0.11.0.js:218
> r @ default_frontend-0.11.0.js:218
> we @ default_frontend-0.11.0.js:218
> Ee.confirmTransition @ default_frontend-0.11.0.js:218
> Ee.transitionTo @ default_frontend-0.11.0.js:218
> t.push @ default_frontend-0.11.0.js:218
> De.push @ default_frontend-0.11.0.js:218
> v @ default_frontend-0.11.0.js:218
> t @ default_frontend-0.11.0.js:7
> t._withTask.i._withTask @ default_frontend-0.11.0.js:7
> default_frontend-0.11.0.js:231 XHR finished loading: POST "http://192.168.1.100:8087/api/logger/contentsummarylog/?1546596786500=1546596786500".
> (anonymous) @ default_frontend-0.11.0.js:231
> (anonymous) @ default_frontend-0.11.0.js:389
> i @ default_frontend-0.11.0.js:389
> d.promise @ default_frontend-0.11.0.js:27
> f.promise @ default_frontend-0.11.0.js:65
> (anonymous) @ default_frontend-0.11.0.js:231
> a @ default_frontend-0.11.0.js:153
> (anonymous) @ default_frontend-0.11.0.js:26
> (anonymous) @ default_frontend-0.11.0.js:389
> I @ default_frontend-0.11.0.js:389
> _.when @ default_frontend-0.11.0.js:389
> O.run @ default_frontend-0.11.0.js:389
> e._drain @ default_frontend-0.11.0.js:388
> drain @ default_frontend-0.11.0.js:388
> e.observe.characterData @ default_frontend-0.11.0.js:52
> characterData (async)
> (anonymous) @ default_frontend-0.11.0.js:52
> e.run @ default_frontend-0.11.0.js:388
> e.enqueue @ default_frontend-0.11.0.js:388
> b.when @ default_frontend-0.11.0.js:389
> m.chain @ default_frontend-0.11.0.js:389
> i.then @ default_frontend-0.11.0.js:389
> d @ default_frontend-0.11.0.js:27
> f @ default_frontend-0.11.0.js:65
> e @ default_frontend-0.11.0.js:26
> t.default @ default_frontend-0.11.0.js:33
> w.client @ default_frontend-0.11.0.js:1
> (anonymous) @ default_frontend-0.11.0.js:1
> Promise.then (async)
> (anonymous) @ default_frontend-0.11.0.js:1
> r @ default_frontend-0.11.0.js:13
> v.save @ default_frontend-0.11.0.js:1
> w.saveModel @ default_frontend-0.11.0.js:1
> (anonymous) @ default_frontend-0.11.0.js:46
> Promise.then (async)
> r.then @ default_frontend-0.11.0.js:13
> (anonymous) @ default_frontend-0.11.0.js:46
> I @ default_frontend-0.11.0.js:46
> (anonymous) @ default_frontend-0.11.0.js:13
> l.dispatch @ default_frontend-0.11.0.js:13
> dispatch @ default_frontend-0.11.0.js:13
> n.(anonymous function) @ default_frontend-0.11.0.js:13
> initSession @ learn_module-0.11.0.js:1
> updateRendererComponent @ default_frontend-0.11.0.js:46
> created @ default_frontend-0.11.0.js:46
> xt @ default_frontend-0.11.0.js:7
> e._init @ default_frontend-0.11.0.js:7
> a @ default_frontend-0.11.0.js:7
> (anonymous) @ default_frontend-0.11.0.js:7
> init @ default_frontend-0.11.0.js:7
> (anonymous) @ default_frontend-0.11.0.js:7
> f @ default_frontend-0.11.0.js:7
> d @ default_frontend-0.11.0.js:7
> f @ default_frontend-0.11.0.js:7
> (anonymous) @ default_frontend-0.11.0.js:7
> e._update @ default_frontend-0.11.0.js:7
> (anonymous) @ default_frontend-0.11.0.js:7
> Lt.get @ default_frontend-0.11.0.js:7
> Lt @ default_frontend-0.11.0.js:7
> e @ default_frontend-0.11.0.js:7
> fn.$mount @ default_frontend-0.11.0.js:7
> init @ default_frontend-0.11.0.js:7
> (anonymous) @ default_frontend-0.11.0.js:7
> f @ default_frontend-0.11.0.js:7
> d @ default_frontend-0.11.0.js:7
> f @ default_frontend-0.11.0.js:7
> d @ default_frontend-0.11.0.js:7
> f @ default_frontend-0.11.0.js:7
> (anonymous) @ default_frontend-0.11.0.js:7
> C @ default_frontend-0.11.0.js:7
> (anonymous) @ default_frontend-0.11.0.js:7
> e._update @ default_frontend-0.11.0.js:7
> (anonymous) @ default_frontend-0.11.0.js:7
> Lt.get @ default_frontend-0.11.0.js:7
> Lt.run @ default_frontend-0.11.0.js:7
> Nt @ default_frontend-0.11.0.js:7
> (anonymous) @ default_frontend-0.11.0.js:7
> We @ default_frontend-0.11.0.js:7
> Promise.then (async)
> Ge @ default_frontend-0.11.0.js:7
> Ze @ default_frontend-0.11.0.js:7
> (anonymous) @ default_frontend-0.11.0.js:7
> Lt.update @ default_frontend-0.11.0.js:7
> ue.notify @ default_frontend-0.11.0.js:7
> set @ default_frontend-0.11.0.js:7
> SET_STATE @ learn_module-0.11.0.js:1
> (anonymous) @ default_frontend-0.11.0.js:13
> (anonymous) @ default_frontend-0.11.0.js:13
> (anonymous) @ default_frontend-0.11.0.js:13
> l._withCommit @ default_frontend-0.11.0.js:13
> l.commit @ default_frontend-0.11.0.js:13
> commit @ default_frontend-0.11.0.js:13
> (anonymous) @ learn_module-0.11.0.js:1
> (anonymous) @ default_frontend-0.11.0.js:13
> Promise.then (async)
> r.only @ default_frontend-0.11.0.js:13
> (anonymous) @ learn_module-0.11.0.js:1
> handler @ learn_module-0.11.0.js:1
> ri._hook @ default_frontend-0.11.0.js:218
> p @ default_frontend-0.11.0.js:218
> r @ default_frontend-0.11.0.js:218
> r @ default_frontend-0.11.0.js:218
> we @ default_frontend-0.11.0.js:218
> Ee.confirmTransition @ default_frontend-0.11.0.js:218
> Ee.transitionTo @ default_frontend-0.11.0.js:218
> t.push @ default_frontend-0.11.0.js:218
> De.push @ default_frontend-0.11.0.js:218
> v @ default_frontend-0.11.0.js:218
> t @ default_frontend-0.11.0.js:7
> t._withTask.i._withTask @ default_frontend-0.11.0.js:7
> default_frontend-0.11.0.js:33 Uncaught (in promise) TypeError: Failed to execute 'requestFullscreen' on 'Element': parameter 1 ('options') is not an object.
>     at Object.request (default_frontend-0.11.0.js:33)
>     at Object.toggle (default_frontend-0.11.0.js:33)
>     at a.enterFullScreen (default_frontend-0.11.0.js:218)
>     at a.toggleFullscreen (default_frontend-0.11.0.js:218)
>     at click (html5_app_renderer_module-0.11.0.js:1)
>     at a.t (default_frontend-0.11.0.js:7)
>     at a.e.$emit (default_frontend-0.11.0.js:7)
>     at a.onClick (html5_app_renderer_module-0.11.0.js:1)
>     at t (default_frontend-0.11.0.js:7)
>     at HTMLButtonElement.t._withTask.i._withTask (default_frontend-0.11.0.js:7)

### Context
Kolibri version 0.11
Linux
Chromium and Vivaldi
-->

…

### PR DESCRIPTION
**Pull request by rtibbles**
### Summary
Chrome 71 became picky about accepting `undefined` as the options parameter to `requestFullscreen`, the older version of screenfull we were using was doing that. The new version does not.
This remedies the error by upgrading screenfull.

Unfortunately, the version change changes the API of Screenfull to a Promise based one, so the toggling method had to be refactored to deal with the promises.

### Reviewer guidance
Does full screen toggling work on:
* PDFs
* Videos
* EPubs
By:
* Clicking a fullscreen icon
* Clicking a 'no full screen icon'
* Pressing escape
On:
* Chrome 71
* Firefox

### References
Fixes #4680

----

### Contributor Checklist

PR process:

- [x] PR has the correct target branch and milestone
- [x] PR has 'needs review' or 'work-in-progress' label
- [x] If PR is ready for review, a reviewer has been added. (Don't use 'Assignees')
- [x] If this is an important user-facing change, PR or related issue has a 'changelog' label
- [ ] If this includes an internal dependency change, a link to the diff is provided

Testing:

- [x] Contributor has fully tested the PR manually
- [ ] If there are any front-end changes, before/after screenshots are included
- [ ] Gherkin stories have been updated
- [ ] Unit tests have been updated

### Reviewer Checklist

- Automated test coverage is satisfactory
- PR is fully functional
- PR has been tested for [accessibility regressions](http://kolibri-dev.readthedocs.io/en/develop/manual_testing.html#accessibility-a11y-testing)
- External dependency files were updated if necessary (`yarn` and `pip`)
- Documentation is updated
- Contributor is in AUTHORS.rst

### CODE REVIEW

**Comment by ivanistheone** [comment]
Tested with Chrome 71 and Firefox 64 on mac:

  - HTML5app http://35.237.29.181/learn/#/topics/c/b728c0f4456446ae8d3cfa0260342a79
  - PDF http://35.237.29.181/learn/#/topics/c/48215b0a87d44bbd90c0347a0e965215
  - Video http://35.237.29.181/learn/#/topics/c/75552f2b4602478484043691818b90a1
  - ePub http://35.237.29.181/learn/#/topics/c/e80ed18185bb5de1b6720a4472ca21b2

Fullscreen works in all cases (using button and ESC key).

**Review by ivanistheone — APPROVED** [review]

File: kolibri/core/assets/src/views/CoreFullscreen.vue [hunk 1]
```diff
@@ -50,20 +51,20 @@
...
-        if (fullscreenApiIsSupported) {
-          ScreenFull.toggle(this.$refs.fullscreen);
-        }
-        this.isInFullscreen = false;
-      },
       toggleFullscreen() {
-        this.isInFullscreen ? this.exitFullscreen() : this.enterFullScreen();
+        if (!this.toggling) {
+          let fullScreenPromise;
+          this.toggling = true;
```
Comment (jamalex) [inline kolibri/core/assets/src/views/CoreFullscreen.vue:57]: Do we need an _actual_ mutex? :) I guess we wouldn't expect people to click *that* fast.

**Review by jamalex — COMMENTED** [review]
Don't feel qualified to fully approve, but don't see any issues pop out at me.

File: kolibri/core/assets/src/views/CoreFullscreen.vue (hunk 1 above)
Comment (rtibbles) [reply kolibri/core/assets/src/views/CoreFullscreen.vue:57]: Better safe than sorry.
