### PR TITLE
Finalize H5P Integration

### LINKED ISSUE #8927: Finalize H5P integration
- [ ] Disable time based progress tracking for H5P files in the HTML5 viewer
- [ ] Log all logged xAPI statements even when they fail validation, but mark them as such
- [ ] Add logic in the score calculation logic to handle invalid statements

### PR DESCRIPTION
**Pull request by rtibbles**
## Summary
-  Disable time based progress tracking for H5P files in the HTML5 viewer
-  Log all logged xAPI statements even when they fail validation, but mark them as such
-  Add logic in the score calculation logic to handle invalid statements and other statement handling logic
- Prevent H5P from returning statements that imply completion when they are only about subContentIds within the main content (seemingly contrary to the CMI5 spec https://github.com/AICC/CMI-5_Spec_Current/blob/quartz/cmi5_spec.md#verbs_completed)
- Clean up old mutation observer/resizing code that is no longer used but was causing an unreported error that was preventing data from being saved

## References
Fixes #8927

## Reviewer guidance
Engage with H5P content in the Kolibri QA channel.
Engage with the H5P node here: `birid-riziv`

Ensure in both instances that the content is not completed too soon at the very least (possible that it will never be marked as complete, but there's only so much we can do).

----

## Testing checklist

- [x] Contributor has fully tested the PR manually
- [ ] If there are any front-end changes, before/after screenshots are included
- [ ] Critical user journeys are covered by Gherkin stories
- [x] Critical and brittle code paths are covered by unit tests

## PR process

- [x] PR has the correct target branch and milestone
- [x] PR has 'needs review' or 'work-in-progress' label
- [x] If PR is ready for review, a reviewer has been added. (Don't use 'Assignees')
- [ ] If this is an important user-facing change, PR or related issue has a 'changelog' label
- [ ] If this includes an internal dependency change, a link to the diff is provided

## Reviewer checklist

- Automated test coverage is satisfactory
- PR is fully functional
- PR has been tested for [accessibility regressions](http://kolibri-dev.readthedocs.io/en/develop/manual_testing.html#accessibility-a11y-testing)
- External dependency files were updated if necessary (`yarn` and `pip`)
- Documentation is updated
- Contributor is in AUTHORS.md

### CODE REVIEW

File: packages/hashi/src/iframeClient.js [hunk 1]
```diff
@@ -81,21 +81,13 @@ export default class SandboxEnvironment {
         this.H5P.iframeInitialize(this.iframe.contentWindow);
         this.xAPI.iframeInitialize(this.iframe.contentWindow);
         patchIndexedDB(this.contentNamespace, this.iframe.contentWindow);
-        this.mutationObserver.observe(this.iframe.contentDocument, {
```
Comment (marcellamaki) [inline packages/hashi/src/iframeClient.js:84]: Is this functionality replaced with other code somewhere, or is it just obsolete?

**Review by marcellamaki — COMMENTED** [review]
So far the code read through looks good to me -- easy to follow even with my only rudimentary understanding of H5P. I'm not sure how to best do some manual QA on this so open to recommendations @radinamatic or @rtibbles if you have any. Once that checks out I will approve

File: packages/hashi/src/iframeClient.js (hunk 1 above)
Comment (rtibbles) [reply packages/hashi/src/iframeClient.js:84]: It was previously replaced in https://github.com/learningequality/kolibri/pull/8458, but these references to `mutationObserver` were missed.

**Comment by radinamatic** [comment]
Tested with Kolibri QA channel, `birid-riziv` and the main `piman-fapum`, no _premature_ completion modal appeared. 
As you mentioned, in many cases there was no way to achieve completion (which is a bit anticlimactic), but some do not even register progress, even when one goes through all the _motions_ (`Dialog cards`, for example). Not sure if that is due to a resource or Kolibri...? 🤔 

1 | 2
--- | ---
LEDev2111 (take)  Running  - Oracle VM VirtualBox_016 | LEDev2111 (take)  Running  - Oracle VM VirtualBox_015

**Review by radinamatic — APPROVED** [review]
For the stated PR scope, manual QA is passed! :shipit: 🙂

File: packages/hashi/src/iframeClient.js [hunk 2]
```diff
@@ -81,21 +81,14 @@ export default class SandboxEnvironment {
...
-          attributes: true,
-          childList: true,
-          subtree: true,
-        });
       } catch (e) {
+        console.debug(e);
```
Comment (nucleogenesis) [inline packages/hashi/src/iframeClient.js:85]: Is this committed intentionally?

**Comment by rtibbles** [comment]
Have confirmed with @radinamatic that this seems to be because the H5P content is not emitting any events at all on which we would judge progress.

File: packages/hashi/src/iframeClient.js (hunk 2 above)
Comment (rtibbles) [reply packages/hashi/src/iframeClient.js:85]: Yes - the reason one of the bugs I fixed in here went unnoticed for so long was because the error was silently swallowed.
