### PR TITLE
Fixes for exam behaviour and exam reports

### LINKED ISSUE #1246: After submitting the exam the learner is still allowed to start the exam.
## Summary
After submitting the exam the learner is still allowed to start the exam. Where as it should show the **Completed** and the learner should not be allowed to retake.

## System information

 - Version: Kolibri 0.4.0aplha2
 - Operating system: Ubuntu 14.04 LTS
 - Browser: Chrome browser and Firefox

## How to reproduce

1. Login as a learner
2. Start giving an exam.
3. Enter all the answers.
4. Click on submit exam.
5. Ideally the learner should be given completed exam status.

## Screenshots
Before Exam
before

mid

After Exam
after

### LINKED ISSUE #1343: On reviewing the previous questions after entering the answers, the answers disappear for exam.
## Summary
On reviewing the previous questions after entering their answers, the answers disappears for those questions that a user is reviewing.

## System information
 - Version: Kolibri 0.4.0alpha5
 - Operating system: Ubuntu 14.04 LTS
 - Browser: Chrome browser and Firefox

## How to reproduce

1. Login as learner.
2. Click on Exams tab and select any exam.
3. Attempt all questions.
4. Go back and start reviewing each questions.

**Actual results:**
 The answers starts disappearing and the question highlighter on the left also disappears as you continue to review.

**Expected results:**
The previous recorded answers should be present and the question highlighter should be purple.

## Screenshots
Attempted all the questions:
attempted all question answer_1

Start reviewing the questions from the beginning:
(The answers starts disappearing with the question highlighter) 
attempted all question answer_2

### LINKED ISSUE #1387: Exam report is not showing what the learner has attempted.
## Summary

Learner attempted all the questions in exam but showing most of the questions not attempted and some attempted in exam report when logged in as a Coach.

## System information

 - Version: Kolibri 0.4.0alpha6
 - Operating system: Ubuntu 14.04 LTS
 - Browser: Chrome browser and Firefox

## How to reproduce

1. Login as a Coach.
2. Click on Coach.
3. Select the class.
4. Click on Exams tab.
5. Select the View report in down arrow of Exam which learner has given.
6. Click on User.

## Screenshots

Coach user Exam report:

### LINKED ISSUE #1389: when coach user views not started learners exam report page hangs.
## Summary
When Coach user is viewing report of exam of user who do not started exam yet, then page hangs.

## System information

 - Version: Kolibri 0.4.0alpha6
 - Operating system: Ubuntu 14.04 LTS
 - Browser: Chrome browser and Firefox

## How to reproduce

1. Login as a Coach.
2. Click on Coach.
3. Select the class.
4. Click on Exams tab.
5. Select the View report in down arrow of Exam which learner has given.
6. Click on User who has not attempted the exam yet.

### LINKED ISSUE #1392: Show question content for not attempted questions on learner exam report.
## Summary
Show question content for not attempted questions on learner exam report.

## System information

 - Version: Kolibri 0.4.0alpha6
 - Operating system: Ubuntu 14.04 LTS
 - Browser: Chrome browser and Firefox

## How to reproduce
1. Login as a Coach.
2. Click on Coach.
3. Then select Exams tab.
4. View a report of exam.
5. Click on learner who has attempted the exam.

## Screenshots
not showing the question content for
question content

### LINKED ISSUE #1393: Show different colors for not attempted and Wrong answers of the questions in exam report.
## Summary
In Coach exam report, not showing different colors for not attempted and wrong answers questions, so it will be easy to understand.

## System information

 - Version: Kolibri 0.4.0alpha6
 - Operating system: Ubuntu 14.04 LTS
 - Browser: Chrome browser and Firefox

## How to reproduce

1. Login as a Coach.
2. Click on Coach.
3. Then select Exams tab.
4. View a report of exam.
5. Click on learner who has attempted the exam.

## Screenshots
Wrong answer 
attempted wrongquestion

Not attempted questions
not showing the question content for

### PR DESCRIPTION
**Pull request by rtibbles**
## Summary

Fixes #1246 - This was being caused by caching in the UserExamResource, fixed by clearing the cache as soon as any data is set to the server on the individual exam page.

Fixes #1343 - underlying cause was that the same server side model was being updated for each question, so only one question was being recorded on an exam.

Fixes #1387 - the same underlying cause as #1343 was responsible for this.

Fixes #1389 - was attempt to access `completion_timestamp` of exam log, when user had not started, the exam log was undefined. Fixes this, but also disables the link to the detail report page, as it is superfluous for users who have not started the exam yet.

Fixes #1392 - conditionally renders the content renderer without an answer if an attempt has not been made.

Fixes #1393 - marks unattempted questions with a grey incorrect sign if a question has not been attempted by the learner.

### CODE REVIEW

File: kolibri/plugins/coach/assets/src/views/attempt-log-list/index.vue [hunk 1]
```diff
@@ -13,7 +13,13 @@
           }"
         >
             <mat-svg
-              v-if="attemptLog.correct"
+              v-if="attemptLog.noattempt"
+              class="item svg-item svg-noattempt"
+              category="navigation"
```
Comment (DXCanas) [inline kolibri/plugins/coach/assets/src/views/attempt-log-list/index.vue:18]: nice

File: kolibri/plugins/learn/assets/src/state/actions.js [hunk 2]
```diff
@@ -679,37 +683,40 @@ function setAndSaveCurrentExamAttemptLog(store, contentId, itemId, currentAttemp
...
-    const questionsAnswered = calcQuestionsAnswered(store.state.examAttemptLogs);
-    store.dispatch('SET_QUESTIONS_ANSWERED', questionsAnswered);
-    const examAttemptLogCollection = ExamAttemptLogResource.getCollection({
-      user: store.state.core.session.user_id,
-      exam: store.state.pageState.exam.id,
-    });
-    // Add this attempt log to the Collection for future caching.
-    examAttemptLogCollection.set(examAttemptLogModel);
-  });
+  return promise.then((newExamAttemptLog) =>
```
Comment (DXCanas) [inline kolibri/plugins/learn/assets/src/state/actions.js:698]: Did we have to do this beause of the conditional promise issue?

File: kolibri/plugins/learn/assets/src/state/actions.js [hunk 3]
```diff
@@ -679,37 +683,40 @@ function setAndSaveCurrentExamAttemptLog(store, contentId, itemId, currentAttemp
     content_id: contentId,
     item: itemId,
   });
-  // If the above findModel returned no matching model, then we can do
-  // getModel to get the new model instead.
-  if (!examAttemptLogModel) {
```
Comment (DXCanas) [inline kolibri/plugins/learn/assets/src/state/actions.js:684]: Did we get rid of this because of the resource layer's aggressive caching?

Comment (rtibbles) [reply kolibri/plugins/learn/assets/src/state/actions.js:684]: It sprang from the fact that I had elsewhere implemented caching for models *without* ids - which previously we did not do - in order to fix an issue where we were saving multiple copies of the same resource, because instead of fetching the same Model, we were just creating new Models over and over again when no id had been set yet.

Here, the issue was that I was getting the model, by the undefined id, and hence still getting a model that was cached - so by directly calling `createModel` I ensure that we get a new model, rather than one that might (later, due to a resolved promise) have an id set later.

File: kolibri/plugins/learn/assets/src/state/actions.js (hunk 2 above)
Comment (rtibbles) [reply kolibri/plugins/learn/assets/src/state/actions.js:698]: No, it's because to properly chain Promises, each lambda passed into `then` should return a Promise, as per: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Promise/then#Chaining

Comment (DXCanas) [reply kolibri/plugins/learn/assets/src/state/actions.js:698]: Ah. So `then` just wasn't resolving to what we wanted at all. Got it.
