### PR TITLE
Fix user in change facility

### LINKED ISSUE #9791: Change facility - Misleading message after an attempt to create a user with an existing username
## Observed behavior
The message which is displayed is 'User ‘user’ already exists in ‘TARGET’ is not a learner. Please choose a different username.'

## Expected behavior
The text should be further specified and that should be reflected in Figma as I wasn't able to find it there.

## Steps to reproduce the issue
1. Install the following build: https://buildkite.com/organizations/learningequality/pipelines/kolibri-debian/builds/5203/jobs/0183fbda-239d-4c8c-8201-420d48d92d2c/artifacts/0184090a-8e30-43f9-af55-d55929fe454a
2. Modify the DB as specified in https://github.com/learningequality/kolibri/pull/9760
3. Create a learner account and sign in as the learner
4. Go to Profile and click the Change button
5. Select the target learning facility and press Continue
6. At the next screen select the 'Create new account' option
7. Fill in the username of an existing user.

## Usage Details
Windows 10, Ubuntu - Chrome

### PR DESCRIPTION
**Pull request by jredrejo**
## Summary
This PR solves several problems that have raised when testing the merge facility flow:
- The one described at #9791 was caused when the target facility requires a password for the user. Previous design didn't have this scenario in mind.  This has required changes in the state machine to add a new state and a new form for the user to enter it.
- Some changes in the facility model were breaking Morango Sync
- Some changes in the auth tasks required one more parameter to validate
- New wording for one of the strings

New window for the user to set a password if needed:
image

## References
Closes: #9791 

## Reviewer guidance
The steps @pcenov  described in #9791 to reproduce the issue can be used here to test it

## Testing checklist

- [x] Contributor has fully tested the PR manually
- [x] If there are any front-end changes, before/after screenshots are included
- [x] Critical user journeys are covered by Gherkin stories
- [x] Critical and brittle code paths are covered by unit tests

## PR process

- [ ] PR has the correct target branch and milestone
- [ ] PR has 'needs review' or 'work-in-progress' label
- [ ] If PR is ready for review, a reviewer has been added. (Don't use 'Assignees')
- [ ] If this is an important user-facing change, PR or related issue has a 'changelog' label
- [ ] If this includes an internal dependency change, a link to the diff is provided

## Reviewer checklist

- Automated test coverage is satisfactory
- PR is fully functional
- PR has been tested for [accessibility regressions](http://kolibri-dev.readthedocs.io/en/develop/manual_testing.html#accessibility-a11y-testing)
- External dependency files were updated if necessary (`yarn` and `pip`)
- Documentation is updated
- Contributor is in AUTHORS.md

### CODE REVIEW

File: kolibri/plugins/user_profile/assets/src/views/ChangeFacility/CreatePassword.vue [hunk 1]
```diff
@@ -0,0 +1,132 @@
...
+      handleContinue() {
+        this.isFormSubmitted = true;
+        if (this.isPasswordValid) {
+          this.sendContinue();
+        } else {
+          this.$refs.passwordTextbox.focus();
+        }
+      },
+      sendContinue() {
+        console.log({
```
Comment (bjester) [inline kolibri/plugins/user_profile/assets/src/views/ChangeFacility/CreatePassword.vue]: This doesn't seem like something we want to keep.

File: kolibri/core/device/models.py [hunk 2]
```diff
@@ -80,15 +80,16 @@ def app_is_enabled():
...
     "properties": {
         "allow_download_on_mettered_connection": {"type": "boolean"},
         "enable_automatic_download": {"type": "boolean"},
-        "allow_learner_download_resources": {"type": "boolean"},
-        "set_limit_for_autodownload": {"type": "boolean"},
-        "limit_for_autodownload": {"type": "integer"},
+        "allow_learner_download_resources": {"type": "boolean", "optional": True},
+        "set_limit_for_autodownload": {"type": "boolean", "optional": True},
+        "limit_for_autodownload": {"type": "integer", "optional": True},
     },
```
Comment (bjester) [inline kolibri/core/device/models.py:93]: :+1:

**Review by bjester — CHANGES_REQUESTED** [review]
Please remove the `console.log`, primarily because it's logging credentials.

**Comment by bjester** [comment]
@radinamatic @pcenov my requested change is a code-only change, so please test if possible.

File: kolibri/core/device/models.py [hunk 3]
```diff
@@ -80,15 +80,16 @@ def app_is_enabled():
     return interface.enabled
 
 
+# '"optional":True' is obsolete but needed while we keep using an
+# old json_schema_validator version compatible with python 2.7
```
Comment (bjester) [inline kolibri/core/device/models.py:84]: Maybe also expand and mention that this needs to be backwards compatible? I'm thinking it would be a good thing given I'm guessing your migration here will stop Django wanting to create more migrations for schema changes?

File: kolibri/core/auth/models.py [hunk 4]
```diff
@@ -81,13 +81,14 @@
 
 logger = logging.getLogger(__name__)
 
+# '"optional":True' is obsolete but needed while we keep using an
+# old json_schema_validator version compatible with python 2.7
```
Comment (bjester) [inline kolibri/core/auth/models.py]: Maybe also expand and mention that this needs to be backwards compatible? I'm thinking it would be a good thing given I'm guessing your migration here will stop Django wanting to create more migrations for schema changes?

File: kolibri/plugins/user_profile/assets/src/views/ChangeFacility/CreatePassword.vue (hunk 1 above)
Comment (jredrejo) [reply kolibri/plugins/user_profile/assets/src/views/ChangeFacility/CreatePassword.vue]: yep, thanks, that's what review are for. Removed!

File: kolibri/core/auth/models.py (hunk 4 above)
Comment (jredrejo) [reply kolibri/core/auth/models.py]: Yep, I had hesitated to do it, but it's good to avoid the same problem again. Expanded

**Review by bjester — APPROVED** [review]
Code looks good :100:

**Comment by pcenov** [comment]
Hi @jredrejo, I confirm that the issue described in https://github.com/learningequality/kolibri/issues/9791 is fixed now.
The displayed messages are:
`‘User’ already exists in ‘TARGET’ and ‘User’ is not a learner. Please choose a different username.`
`‘User’ already exists in ‘TARGET’. Please choose a different username.`

While regression testing your latest changes I was also able to identify the following issues:
1. After changing the learning facility the Full name, Gender, Birth year and Identifier values are lost:

https://user-images.githubusercontent.com/79847249/223739882-41354a73-3109-46c1-bdfb-a765f2cc827d.mp4

2. If the import process gets interrupted it seems that we are still importing the user to the target facility but that's not immediately clear and the option 'Change learning facility' remains visible until I sign out:

https://user-images.githubusercontent.com/79847249/223750826-575d2afa-9b22-458c-917e-ed568deb8582.mp4

**Comment by jredrejo** [comment]
thanks @pcenov 
about the  Full name, Gender, Birth year and Identifier values, I also  noticed it, but it was not a problme in they syncing but in the profile page, it's not showing them (they appear if you edit the user though). I'll create a follow up issue
