### PR TITLE
long title button overlap resolved

### LINKED ISSUE #11086: Long content titles cause issues with learning activity bar buttons
## Observed behavior

When a resource title is very long, it causes the top bar activity buttons to wrap and stack awkwardly.

Screenshot from 2023-08-10 08-09-19

## Expected behavior

The buttons container does not try to shrink, but remains a consistent size and forces the title to be further truncated in order for everything to fit. It should possibly turn into the meatball menu earlier with a long title.
## User-facing consequences

Buttons may not be easily actionable and could cause confusion

## Steps to reproduce

1) Download a resource with a long title
2) View the resource in Kolibri
3) Shrink the viewport until the condition occurs

## Context

Kolibri 0.16

### PR DESCRIPTION
**Pull request by GarvitSinghal47**
Fixes #11086 

## Summary

changes the default old breakpoint for the numBarActions to more suitable one.
also added a filter of text truncation on long title for different breakpoint  to prevent button issue as the size of the text content increases.

After :

[Transcripts - MIT Blossoms.webm](https://github.com/learningequality/kolibri/assets/82756460/aa0c0571-9200-4f99-bd12-c2e661d948ac)

…

## References

…

## Reviewer guidance

…

----

## Testing checklist

- [ ] Contributor has fully tested the PR manually
- [ ] If there are any front-end changes, before/after screenshots are included
- [ ] Critical user journeys are covered by Gherkin stories
- [ ] Critical and brittle code paths are covered by unit tests

## PR process

- [ ] PR has the correct target branch and milestone
- [ ] PR has 'needs review' or 'work-in-progress' label
- [ ] If PR is ready for review, a reviewer has been added. (Don't use 'Assignees')
- [ ] If this is an important user-facing change, PR or related issue has a 'changelog' label
- [ ] If this includes an internal dependency change, a link to the diff is provided

## Reviewer checklist

- Automated test coverage is satisfactory
- PR is fully functional
- PR has been tested for [accessibility regressions](http://kolibri-dev.readthedocs.io/en/develop/manual_testing.html#accessibility-a11y-testing)
- External dependency files were updated if necessary (`yarn` and `pip`)
- Documentation is updated
- Contributor is in AUTHORS.md

### CODE REVIEW

File: kolibri/plugins/learn/assets/src/views/LearningActivityBar.vue [hunk 1]
```diff
@@ -419,9 +434,9 @@
       },
       numBarActions() {
         let maxSize = 1;
-        if (this.windowBreakpoint === 1) {
+        if (this.windowBreakpoint === 1 || this.windowBreakpoint === 2) {
```
Comment (LianaHarris360) [inline kolibri/plugins/learn/assets/src/views/LearningActivityBar.vue:437]: This if statement could instead check if `this.windowBreakpoint` is less than or equal to 2 as a small refactor.

File: kolibri/plugins/learn/assets/src/views/LearningActivityBar.vue [hunk 2]
```diff
@@ -15,7 +15,13 @@
...
         </template>
         <TextTruncatorCss
-          :text="resourceTitle"
+          v-if="windowBreakpoint <= 3"
+          :text="resourceTitle | truncateText(50)"
+          :maxLines="1"
+        />
+        <TextTruncatorCss
+          v-else
+          :text="resourceTitle | truncateText(70)"
```
Comment (LianaHarris360) [inline kolibri/plugins/learn/assets/src/views/LearningActivityBar.vue:24]: More out of curiosity, I'm wondering how the numbers 50 and 70 decided on? In the included picture, the `windowBreakpoint` is 6, this title has two more characters to display, and seems like it should fit, but it is truncated instead.
Screenshot 2023-08-30 at 2 05 31 PM

**Review by LianaHarris360 — COMMENTED** [review]
Hi @GarvitSinghal47, thank you so much for working on this. It looks good, I just had a few comments to add in. Also, in the above References section, if you add in the line `Fixes #11086`, once this pull request is merged, it will automatically close that issue!

**Comment by MisRob** [comment]
I'd like to add that tests from `kolibri/plugins/learn/assets/test/views/learning-activity-bar.spec.js` are failing and will need to be fixed/adjusted

**Comment by LianaHarris360** [comment]
Thanks for catching that @MisRob. Looks like a problem with `value.length` being undefined within the filter `truncateText`
```
console.error
      TypeError: Cannot read properties of undefined (reading 'length')
          at truncateText (/home/runner/work/kolibri/kolibri/kolibri/plugins/learn/assets/src/views/LearningActivityBar.vue:4519:19)
```

More info about Kolibri tests can be found [here](https://kolibri-dev.readthedocs.io/en/develop/getting_started.html#automated-testing:~:text=127.0.0.1%3A8888/.-,Automated%20testing,-%C2%B6).

File: kolibri/plugins/learn/assets/src/views/LearningActivityBar.vue (hunk 2 above)
Comment (GarvitSinghal47) [reply kolibri/plugins/learn/assets/src/views/LearningActivityBar.vue:24]: i have just added by manually  applying it by decreasing the size of window to various breakpoints for large screen when it is greater than 2 breakpoint means till 3 to 6 i have make 70.

it will show good in case of 6 breakpoint but when we take it to 3 or 4 any size of text above or about 75  can create problem of button overlap again.

we can also change it for breakpoint 5 and 6 as well seperately like about 80 to 85 (a it will be safe) but the inital thinking of mine is to cover approx 50-60 % of the header by title in case of breakpoint 5 and 6 .

File: kolibri/plugins/learn/assets/src/views/LearningActivityBar.vue (hunk 1 above)
Comment (GarvitSinghal47) [reply kolibri/plugins/learn/assets/src/views/LearningActivityBar.vue:437]: Ah that will not work as when the size of breakpoint will go less than 1 we want to show only one icon the refactor you are saying will make two icon to show in that case but originally intended was 1 .

we can change it to get value greater than equal to 1 or less than equal to 2 but i think that will not be of any use.

Comment (LianaHarris360) [reply kolibri/plugins/learn/assets/src/views/LearningActivityBar.vue:437]: Okay, I understand it now, I overlooked that detail before :)

File: kolibri/plugins/learn/assets/src/views/LearningActivityBar.vue (hunk 2 above)
Comment (LianaHarris360) [reply kolibri/plugins/learn/assets/src/views/LearningActivityBar.vue:24]: Thank you for the explanation, that makes sense to me! Now that all the tests pass, this should be good to merge in!

**Review by LianaHarris360 — APPROVED** [review]
