### PR TITLE
Deprecate media queries

### LINKED ISSUE #1476: user and class management tables broken on smaller monitors
what ever media query code we're using causes the tables to be truncated and the layout to be broken:

image

Recommend stripping out any media queries and other responsive code, and adding 

```css
overflow-x: auto
```

to a wrapper around the tables. This has been an effective alternative to designing mobile views in report tables.

### PR DESCRIPTION
**Pull request by indirectlylit**
Removes all CSS media queries from our code.

* In some cases, transitions to `responsiveWindow`mixin.
* In other cases (large table views) adds a min-width and horizontal scrolling. Fixes #1476

### CODE REVIEW

File: kolibri/core/assets/src/mixins/responsive-element.js [hunk 1]
```diff
@@ -6,7 +6,7 @@
 
     <script>
 
-      import responsiveElement from './responsive-element-mixin.js';
+      import responsiveWindow from 'kolibri.coreVue.mixins.responsiveElement';
```
Comment (christianmemije) [inline kolibri/core/assets/src/mixins/responsive-element.js]: Should be `import responsiveElement`?

File: kolibri/plugins/management/assets/src/management-styles.styl [hunk 2]
```diff
@@ -1,15 +0,0 @@
-  @require '~kolibri.styles.definitions'
-
-  .manage-content
-    width: 100%
-    @media screen and (max-width: $medium-breakpoint)
-        width: 90%
-        margin-left: auto
-        margin-right: auto
-
-  .page
```
Comment (christianmemije) [inline kolibri/plugins/management/assets/src/management-styles.styl:10]: Some of this style should have not been removed, like background-color.

Comment (indirectlylit) [reply kolibri/plugins/management/assets/src/management-styles.styl:10]: Are you sure? I couldn't actually find a reference to the `page` class

Comment (indirectlylit) [reply kolibri/plugins/management/assets/src/management-styles.styl:10]: oh, I found it here .. https://github.com/learningequality/kolibri/pull/2215/files#diff-a895b0f385c04308a48a2128fbbbb789L9

I'll check the styling again. It might actually be good to remove these styles, because they should be set globally? It's not clear to me why the background color would be different for this one section

Comment (indirectlylit) [reply kolibri/plugins/management/assets/src/management-styles.styl:10]: added back in

**Comment by indirectlylit** [comment]
issues addressed
