### PR TITLE
Prevent display of welcome modal in LOD's

### LINKED ISSUE #11456: The 'Welcome to Kolibri' modal is displayed regardless of the fact that I have imported channels
## Observed behavior

This is a follow-up issue to https://github.com/learningequality/kolibri/pull/11449 - since we are not tracking the dismissal in anything other than browser state the 'Welcome to Kolibri!' modal will show on the Library page and on Device > Channels regardless of whether the user has already imported channels or not.

## Expected behavior
The 'Welcome to Kolibri!' should only be displayed to actual first time users.

## Steps to reproduce the issue
1. Install the latest build from https://github.com/learningequality/kolibri/pull/11449 and setup a full facility.
3. Sign in and go to the Library page and/or Device > Channels - observe the welcome modal
4. Import channels
5. Clear all the browser cookies and sign in again, or sign in using a different browser - observe that the Welcome modal is displayed regardless of the fact that the user has already downloaded channels to the device.

## More information

Library:

https://github.com/learningequality/kolibri/assets/79847249/270a830b-d6e5-4e10-be37-735a89c8c4cc

Device > Channels:

## Usage Details
Kolibri 0.16beta6
Ubuntu - Chrome, Firefox

### PR DESCRIPTION
**Pull request by ozer550**
## Summary
Use the existing getter function "isLearnerOnlyImport" to prevent display of welcome modal in the LOD's

…

## References
closes #11456 

…

## Reviewer guidance
- Open the library section.
- The Welcome Modal does not appear any more.

## Testing checklist

- [x] Contributor has fully tested the PR manually
- [ ] If there are any front-end changes, before/after screenshots are included
- [ ] Critical user journeys are covered by Gherkin stories
- [ ] Critical and brittle code paths are covered by unit tests

## PR process

- [x] PR has the correct target branch and milestone
- [ ] PR has 'needs review' or 'work-in-progress' label
- [x] If PR is ready for review, a reviewer has been added. (Don't use 'Assignees')
- [ ] If this is an important user-facing change, PR or related issue has a 'changelog' label
- [ ] If this includes an internal dependency change, a link to the diff is provided

## Reviewer checklist

- Automated test coverage is satisfactory
- PR is fully functional
- PR has been tested for [accessibility regressions](http://kolibri-dev.readthedocs.io/en/develop/manual_testing.html#accessibility-a11y-testing)
- External dependency files were updated if necessary (`yarn` and `pip`)
- Documentation is updated
- Contributor is in AUTHORS.md

### CODE REVIEW

**Comment by pcenov** [comment]
Hi @ozer550 I can confirm that the welcome modal is no longer being displayed for a LOD device. What I find strange is that while regression testing I noticed that the issue whit the reappearing modal which was fixed in https://github.com/learningequality/kolibri/pull/11492 is now observed in this build - have you rebased to the latest version of Kolibri?

**Comment by ozer550** [comment]
Hi @pcenov! The build does seem to have required code to fix the issue that you mentioned as regression. I checked both local branch and downloading the pex file. It seems to be working correctly for me.

File: kolibri/plugins/learn/assets/src/views/LibraryPage/index.vue [hunk 1]
```diff
@@ -402,6 +405,7 @@
       };
     },
     computed: {
+      ...mapGetters(['isLearnerOnlyImport']),
```
Comment (rtibbles) [inline kolibri/plugins/learn/assets/src/views/LibraryPage/index.vue:408]: This is fine - in future, we'll try to move more towards using the core `useUser` composable that wraps this, so we can deprecate and remove the core vuex state.

**Review by rtibbles — APPROVED** [review]
Fixes the issue at hand.

**Review by pcenov — COMMENTED** [review]
Hi @ozer550 after additional investigation on my end, the issue with the Welcome modal being constantly displayed is still valid in LODs and in normal devices if there aren't any downloaded channels yet. Will open a separate issue for that.

https://github.com/learningequality/kolibri/assets/79847249/20d2bb5a-b2d1-4a72-a1b5-959d61fecd27

**Comment by ozer550** [comment]
Hi @pcenov, If I understand correctly here, we do not want the WelcomeModal to be displayed once again when the user deletes all the channels, it should be just displayed once at the very start when there are no channels and the user has never seen the welcome Modal before? cc @radinamatic

**Comment by radinamatic** [comment]
@ozer550 

Yes, the welcome modal should not be displayed to users who have seen it already, back when they installed Kolibri for the first time, even when they (for any reason at some point) delete all the channels they have on the device. 

This condition should be implemented together with **not displaying the welcome modal to LoDs altogether**, since the wording of the string is clearly directed to admins, and not learner users. To sum it up:

1. Completely disable the welcome modal for LoDs. 
2. Do not use the presence of channels as the condition for displaying the welcome modal (therefore those users who at some point delete all their channels do not need to see the welcome modal again).

**Comment by rtibbles** [comment]
I am not sure why we would remove the no channel condition. If anything this will make it more likely for a user to see the modal again (it would happen every time they clear the site data, rather than if they cleared the site data and had no channels).
