### PR TITLE
Add P2P-sync workflow on Facility > Data page. Fix some UX issues on Device > Facilities page

### LINKED ISSUE #7117: KDP Sync tasks do not display facility name and "retry" button does not work
### Observed behavior

Screenshots are from the https://kolibri-beta.learningequality.org/en/device/#/facilities from around this time

The name of the facility is not shown here:

CleanShot 2020-06-22 at 10 17 28@2x

Because the `facility_name` field is missing from the Task object

CleanShot 2020-06-22 at 10 17 44@2x

Also the "retry" button is not triggering a kdp sync task, so there might be something off about the sending the click even from "retry" to here
https://github.com/learningequality/kolibri/blob/fe997ef0bfa150c01f067602b5644bda484bbf27/kolibri/plugins/device/assets/src/views/FacilitiesPage/facilityTasksQueue.js#L60-L77

### Expected behavior

1. For KDP sync tasks, the "facility name" is added to the Task metadata, so it appears on the UI
1. The "retry" button works

### User-facing consequences

…

### Errors and logs

…

### Steps to reproduce

…

### Context
0.14b3

### LINKED ISSUE #7153: On Facility > Data page, sync interface needs to allow "P2P" sync
### Observed behavior

reported by @jonboiser 

On Facility > Data page, my facility has been synced, but the "register" button is still enabled

image

### Context

0.14.0 beta 3

### PR DESCRIPTION
**Pull request by jonboiser**
#### Facility > Data Page

1. Add full workflow for syncing from either a Peer or KDP
1. Fix the "sync failed" logic which looked like dead code originally

#### Device > Facilities Page
1. Add ability to filter network locations by whether they have a specific facility or not. This allows us to prevent users from trying to sync with a device that doesn't have the facility they want.
1. Fix missing facility name and broken "retry" button for KDP sync tasks
1. Add visual feedback on last "import facility" modal when the import request is pending
1. 

### Reviewer guidance

1. Test out the syncing stuff on the Facility > Data page. Try cases where a peer doesn't have the facility you want
1. Do facility import + syncing tasks on the Device > Facilities page.

### References
Fixes #7153 
Fixes #7117

----

### Contributor Checklist

PR process:

- [x] PR has the correct target branch and milestone
- [x] PR has 'needs review' or 'work-in-progress' label
- [x] If PR is ready for review, a reviewer has been added. (Don't use 'Assignees')
- [ ] If this is an important user-facing change, PR or related issue has a 'changelog' label
- [ ] If this includes an internal dependency change, a link to the diff is provided

Testing:

- [ ] Contributor has fully tested the PR manually
- [ ] If there are any front-end changes, before/after screenshots are included
- [ ] Critical user journeys are covered by Gherkin stories
- [ ] Critical and brittle code paths are covered by unit tests

### Reviewer Checklist

- Automated test coverage is satisfactory
- PR is fully functional
- PR has been tested for [accessibility regressions](http://kolibri-dev.readthedocs.io/en/develop/manual_testing.html#accessibility-a11y-testing)
- External dependency files were updated if necessary (`yarn` and `pip`)
- Documentation is updated
- Contributor is in AUTHORS.md

### CODE REVIEW

File: kolibri/core/assets/src/mixins/commonSyncElements.js [hunk 1]
```diff
@@ -67,12 +67,16 @@ export default {
...
         url: urls['kolibri:core:networklocation_facilities-detail'](locationId),
-      }).then(response => {
-        return response.data;
-      });
+      })
+        .then(response => {
+          return response.data;
+        })
+        .catch(() => {
+          return [];
```
Comment (micahscopes) [inline kolibri/core/assets/src/mixins/commonSyncElements.js:75]: ooh, good `catch`

File: kolibri/core/assets/src/views/sync/SelectAddressModalGroup/api.js [hunk 2]
```diff
@@ -47,21 +50,68 @@ function fetchAddresses(withChannelId = '', LocationResource = NetworkLocationRe
   });
 }
 
-export function fetchStaticAddresses(withChannelId = '') {
-  return fetchAddresses(withChannelId, StaticNetworkLocationResource);
+function facilityIsAvailableAtLocation(facilityId, location) {
+  if (!location.available) {
+    return Promise.resolve(false);
```
Comment (micahscopes) [inline kolibri/core/assets/src/views/sync/SelectAddressModalGroup/api.js:55]: Nice

File: kolibri/core/assets/src/views/sync/SelectAddressModalGroup/api.js [hunk 3]
```diff
@@ -47,21 +50,68 @@ function fetchAddresses(withChannelId = '', LocationResource = NetworkLocationRe
...
+    .fetchNetworkLocationFacilities(location.id)
+    .then(({ facilities }) => {
+      return Boolean(facilities.find(({ id }) => id === facilityId));
+    });
+}
+
+function fetchAddressesWithFacility(facilityId = '', LocationResource = NetworkLocationResource) {
+  return LocationResource.fetchCollection({ force: true }).then(locations => {
+    if (facilityId !== '') {
+      const locationsWithAvailbilityPromises = locations.map(location => {
```
Comment (micahscopes) [inline kolibri/core/assets/src/views/sync/SelectAddressModalGroup/api.js]: `locationsWithAvailbilityPromises` is missing an "`a`" somewhere in there

**Review by micahscopes — CHANGES_REQUESTED** [review]
The syncing consistently worked great, and peers without facilities were appropriately disabled.

What I noticed, however, was that the continue button was still enabled even if no relevant peers were available.  This happened on both pages.  Here's an example:

I can still press the continue button even if there aren't any syncable facilities

After I click continue, both the cancel and continue buttons are now disabled and there's no way to get out of the dialog.
