### PR TITLE
sets side nav submenus to remain active onclick

### LINKED ISSUE #10674: Side navigation - The currently selected page link is not displayed in bold
## Observed behavior
For both devices with a single or multiple facilities the currently selected page link in the Coach and Facility plugins is not displayed in bold.

## Expected behavior
Each selected page should be displayed in bold as is the case with the Device plugin for example.

## Steps to reproduce the issue
1. Install the the build asset from [this PR](https://github.com/learningequality/kolibri/pull/10550)
2. Open the SideNav and select a page from either the Facility or the Coach plugin.
3. Observe that the link to the selected page is not displayed in bold.

## Video

https://github.com/learningequality/kolibri/assets/79847249/458b8d72-e6bc-42ec-aa61-bd7232324c4a

## Usage Details
Ubuntu 22  - Chrome, Firefox

### PR DESCRIPTION
**Pull request by AllanOXDi**
## Summary
This PR sets the submenus to remain active on click

Closes #10674

# References
#10674
[screen-capture (4).webm](https://github.com/learningequality/kolibri/assets/103313919/576e9f87-195b-47a9-8708-2fd3ace1d07c)

## Reviewer guidance
1. Open the SideNav and select a page from either the Facility or the Coach plugin.
2. Observe that the link to the selected page is displayed in bold.

## Testing checklist

- [ ] Contributor has fully tested the PR manually
- [ ] If there are any front-end changes, before/after screenshots are included
- [ ] Critical user journeys are covered by Gherkin stories
- [ ] Critical and brittle code paths are covered by unit tests

## PR process

- [ ] PR has the correct target branch and milestone
- [ ] PR has 'needs review' or 'work-in-progress' label
- [ ] If PR is ready for review, a reviewer has been added. (Don't use 'Assignees')
- [ ] If this is an important user-facing change, PR or related issue has a 'changelog' label
- [ ] If this includes an internal dependency change, a link to the diff is provided

## Reviewer checklist

- Automated test coverage is satisfactory
- PR is fully functional
- PR has been tested for [accessibility regressions](http://kolibri-dev.readthedocs.io/en/develop/manual_testing.html#accessibility-a11y-testing)
- External dependency files were updated if necessary (`yarn` and `pip`)
- Documentation is updated
- Contributor is in AUTHORS.md

### CODE REVIEW

File: kolibri/core/assets/src/views/CoreMenu/CoreMenuOption.vue [hunk 1]
```diff
@@ -158,7 +158,11 @@
     },
     methods: {
       isActiveLink(route) {
-        return `${this.link}#${route}` === `${window.location.pathname}${window.location.hash}`;
+        // return `${this.link}#${route}` === `${window.location.pathname}${window.location.hash}`;
```
Comment (LianaHarris360) [inline kolibri/core/assets/src/views/CoreMenu/CoreMenuOption.vue]: This line can be removed since there is an updated return statement below.

File: kolibri/core/assets/src/views/CoreMenu/CoreMenuOption.vue [hunk 2]
```diff
@@ -205,6 +209,22 @@
...
       },
+      standarizeSubPathRoutes(link) {
+        var subRoutePath = link.replace(/\/:[^/]*\??/, '');
+        return subRoutePath;
+      },
+
+      // for special cases, like the classId in the coach, where the id is required
+      //which bring thr change in the url, this function will handle the change in the url
+      // to match it with the actual url route in the browser
+      checkClassIdInString(str) {
```
Comment (LianaHarris360) [inline kolibri/core/assets/src/views/CoreMenu/CoreMenuOption.vue]: There are some statements in this function that might have been used for testing that can be removed as well.

File: kolibri/core/assets/src/views/CoreMenu/CoreMenuOption.vue [hunk 3]
```diff
@@ -205,6 +209,22 @@
...
         this.$emit('select');
       },
+      standarizeSubPathRoutes(link) {
+        var subRoutePath = link.replace(/\/:[^/]*\??/, '');
+        return subRoutePath;
+      },
+
+      // for special cases, like the classId in the coach, where the id is required
+      //which bring thr change in the url, this function will handle the change in the url
+      // to match it with the actual url route in the browser
```
Comment (LianaHarris360) [inline kolibri/core/assets/src/views/CoreMenu/CoreMenuOption.vue]: On a smaller note, I think this function description could still be understood and shorted if rephrased to something like - this function changes urls that contain IDs to match with the actual url route in the browser

**Review by LianaHarris360 — CHANGES_REQUESTED** [review]
I manually tested the changes and everything works as expected! The code changes look good to me, I just noted some lines that should be removed and possibly rephrased.

File: kolibri/core/assets/src/views/CoreMenu/CoreMenuOption.vue (hunk 3 above)
Comment (AllanOXDi) [reply kolibri/core/assets/src/views/CoreMenu/CoreMenuOption.vue]: Okay! Thanks for the feedback .

**Comment by AllanOXDi** [comment]
Hey reviewers,  Could you  re-review this PR again?

**Review by LianaHarris360 — APPROVED** [review]
LGTM! Thanks @AllanOXDi

File: kolibri/core/assets/src/views/CoreMenu/CoreMenuOption.vue [hunk 4]
```diff
@@ -158,7 +158,10 @@
     },
     methods: {
       isActiveLink(route) {
-        return `${this.link}#${route}` === `${window.location.pathname}${window.location.hash}`;
+        return (
+          this.standarizeSubPathRoutes('#' + route) === `${window.location.hash}` ||
```
Comment (akolson) [inline kolibri/core/assets/src/views/CoreMenu/CoreMenuOption.vue]: You probably don't the backticks in  `` `${window.location.hash}` `` as `window.location.hash` always returns a string. But also since you are using the same `window.location.hash` in the `||` part, you are better off defining a constant to hold it eg `const hash = window.location.hash;` and then use `hash` in the areas where it appears.

**Review by akolson — CHANGES_REQUESTED** [review]
Thanks @AllanOXDi, generally, code looks good to me. Some minor refactors and we should be good to merge

**Review by akolson — DISMISSED** [review]
LGTM! Thanks @AllanOXDi. Tagging @radinamatic to take a look

File: kolibri/core/assets/src/views/CoreMenu/CoreMenuOption.vue (hunk 2 above)
Comment (rtibbles) [reply kolibri/core/assets/src/views/CoreMenu/CoreMenuOption.vue]: I am confused by this function - it seems to be entirely specific to a URL parameter that is used in the coach plugin (and maybe in a sub route in the facility plugin), so I am not sure why it has been added here?

**Review by rtibbles — CHANGES_REQUESTED** [review]
I was a little suspicious of the coach specific subroute in here, and unfortunately, it is as I suspected. This fix does not work for e.g. looking at a specific class under the facilities plugin (note that the Classes link is selected in the top nav, but not bolded in the side nav):
image

**Comment by rtibbles** [comment]
I think the only robust fix here is to use the RouterLink component for these links when we are in the specific plugin.

In order to be able to use the RouterLink component, you'd have to have access to the route names, which are not currently being passed to the sub nav route specification, e.g.: https://github.com/learningequality/kolibri/blob/develop/kolibri/plugins/facility/assets/src/views/FacilityManagementSideNavEntry.js#L13

So, each side nav entry would need to be updated to pass the name property from the baseRoutes and then that would need to be referenced in the CoreMenuOption when inside the specific plugin (i.e. `this.isActive` is `true`: https://github.com/learningequality/kolibri/blob/develop/kolibri/core/assets/src/views/CoreMenu/CoreMenuOption.vue#L113) so in the case that `isActive` is `true` we would use the RouterLink component, otherwise, we'd continue to use the `a` tag.

**Comment by AllanOXDi** [comment]
I think this should be fixed now.

https://github.com/learningequality/kolibri/assets/103313919/5bafe206-69d9-4603-aeb9-d996a3e19a4f

File: kolibri/core/assets/src/views/CoreMenu/CoreMenuOption.vue [hunk 5]
```diff
@@ -158,7 +167,8 @@
     },
     methods: {
       isActiveLink(route) {
-        return `${this.link}#${route}` === `${window.location.pathname}${window.location.hash}`;
+        const full_path = !route.includes('#') ? `${this.link}#${route}` : route;
```
Comment (akolson) [inline kolibri/core/assets/src/views/CoreMenu/CoreMenuOption.vue]: 👀 . maybe `fullPath` instead? 🙂

**Review by akolson — COMMENTED** [review]
Thanks @AllanOXDi! Changes look correct to me! waiting upon @rtibbles and @pcenov for final approvals.

**Review by akolson — COMMENTED** [review]
Thanks @AllanOXDi! Changes look correct to me! waiting upon @rtibbles and @pcenov for final approvals.

File: kolibri/core/assets/src/views/CoreMenu/CoreMenuOption.vue (hunk 5 above)
Comment (rtibbles) [reply kolibri/core/assets/src/views/CoreMenu/CoreMenuOption.vue]: I am wondering if this method is even needed any more? The link will only be active when we are in the single page app itself, in which case, we will be using KRouterLink, which will handle the bold styling internally. This means that we don't need to conditionalize the styling using `isActiveLink` and we could probably get rid of the method completely.

Comment (marcellamaki) [reply kolibri/core/assets/src/views/CoreMenu/CoreMenuOption.vue]: Yes, I think that this would only be true if we are within the SPA and therefore we would always be using KRouterLink. However, I am actually not actually sure that  all of the styles of the bold active link _would_ be the default. I took a quick look and it seems that  focus and hover are built into the component, but that 'active' is not.

So, first would be to confirm whether or not KRouterLink is fully handling active styles. - looking at the code and documentation. If not, something would probably still be needed here to manage this, although it perhaps could be updated based on the other changes you've made, Allan.

Comment (akolson) [reply kolibri/core/assets/src/views/CoreMenu/CoreMenuOption.vue]: @rtibbles @marcellamaki, this seems like an important piece to the stying from what I can remember. @AllanOXDi?

Comment (rtibbles) [reply kolibri/core/assets/src/views/CoreMenu/CoreMenuOption.vue]: It seems if this is not the case, this is a flaw in the KRouterLink implementation, as the base <router-link> component has support to allow `isActive` and `isExactActive` to be propagated into slots included in it: https://v3.router.vuejs.org/api/#example-applying-active-class-to-outer-element

My main concern here is us expending time and energy trying to get the 'isActiveLink' algorithm correct, which would be better deferred to <router-link> which has already solved this problem.

Comment (rtibbles) [reply kolibri/core/assets/src/views/CoreMenu/CoreMenuOption.vue]: That said - if it would be better to merge this and open a follow up issue, I am fine with that - we just have to be open to the possibility that there will still be bugs in the styling because of our hand made isActiveLink checking.

Comment (AllanOXDi) [reply kolibri/core/assets/src/views/CoreMenu/CoreMenuOption.vue]: Okay!

> It seems if this is not the case, this is a flaw in the KRouterLink implementation, as the base component has support to allow `isActive` and `isExactActive` to be propagated into slots included in it: https://v3.router.vuejs.org/api/#example-applying-active-class-to-outer-element
> 
> My main concern here is us expending time and energy trying to get the 'isActiveLink' algorithm correct, which would be better deferred to which has already solved this problem.

**Review by rtibbles — APPROVED** [review]
