### PR TITLE
Replaced the Placeholder with 'Find' for smaller screen sizes

### LINKED ISSUE #12238: Keywords search placeholder text cut off at narrow sizes
## Observed behavior

When the viewport is between and 840 and 1264 pixels, Kolibri's left sidebar is made narrower, which includes the Keywords search input (`.search-box-row .search-input`). This input field has placeholder text saying "Find something to learn".

At the narrower size, the placeholder text is cut off. On my device, it displays "Find someth". The problem is exacerbated by another element (`.search-box-row .search-buttons-wrapper`) causing the available space for the actual input field to be quite small despite the reserved space being empty.

Screen Shot 2024-06-04 at 10 42 47

## Expected behavior

Instead, either this placeholder text should be replaced with a shorter string at this breakpoint, or it should be removed altogether. (One convention is to place a small label below the input field with the same text).

In addition, the appearance of `.search-clear-button` could be conditional on whether the placeholder text is displayed.

## User-facing consequences

The result of this is Kolibri's Library page looks kind of incomplete with a wide range of viewport sizes.

## Context

- Kolibri version: Kolibri 0.16.2 via https://flathub.org/apps/org.learningequality.Kolibri
- Operating system: Fedora Silverblue 40
- Browser: Both Firefox (with which I took the screenshot), and kolibri-gnome.

### PR DESCRIPTION
**Pull request by Abhishek-Punhani**
The placeholder text is replaced with a shorter string "Find" when the viewport width is between 840 and 1264 pixels.
Fixes : #12238 
Screenshot from 2025-01-13 19-13-03

### CODE REVIEW

File: packages/kolibri-common/components/SearchBox.vue [hunk 1]
```diff
@@ -117,15 +121,29 @@
           textAlign: this.isRtl ? 'right' : '',
         };
       },
+      computedPlaceholder() {
+      if (this.viewportWidth < 1264 && this.viewportWidth >= 840) {
```
Comment (AlexVelezLl) [inline packages/kolibri-common/components/SearchBox.vue]: Here instead of checking with these specific pixels, lets instead do this check using our [useKResponsiveWindow composable](https://design-system.learningequality.org/usekresponsivewindow). We can use the `windowBreakpoint` property, and lets show the "find" string if this windowBreakpoint is 3 or 4 which are the corresponding breakpoints.

File: packages/kolibri-common/components/SearchBox.vue [hunk 2]
```diff
@@ -117,15 +121,29 @@
...
       value(current) {
         this.searchInputValue = current || '';
       },
+     viewportWidth(newWidth) {
+      this.viewportWidth = newWidth;
     },
-    created() {
-      this.searchInputValue = this.value;
     },
+  created() {
```
Comment (AlexVelezLl) [inline packages/kolibri-common/components/SearchBox.vue]: After using useKResponsiveWindow, we can remove these listeners and watchers since that composable already take care of that.

File: packages/kolibri-common/components/SearchBox.vue [hunk 3]
```diff
@@ -66,6 +66,9 @@
   export default {
     name: 'SearchBox',
     mixins: [commonCoreStrings],
+    $trs: {
```
Comment (AlexVelezLl) [inline packages/kolibri-common/components/SearchBox.vue]: Lets add this property as the last property of the exported object. And lets run `yarn lint-frontend:format` to correct some linting errors in the PR.

**Review by AlexVelezLl — CHANGES_REQUESTED** [review]
Thanks for your contribution @Abhishek-Punhani! Code changes makes sese to me, although we have this `useKResponsiveWindow` composable that can help better in this case :).

Also, just a little note: As flagged in https://github.com/learningequality/kolibri/issues/12238#issuecomment-2517776923, we have two things to do here:
```
* In all cases, truncate "Find something to learn" with ellipsis ...
* Further improve experience by changing "Find something to learn" string to only "Find" on all smaller breakpoints where "Find something to learn" is not visible in its entirety (truncation described above serves rather as fallback to this behavior because we may not be able to estimate precisely)
```

We have met just the second point with this PR. Lets try to met the first point using some css :).

Let us know if you have any question.

File: packages/kolibri-common/components/SearchBox.vue (hunk 3 above)
Comment (Abhishek-Punhani) [reply packages/kolibri-common/components/SearchBox.vue]: @AlexVelezLl 
Thank you for the feedback and guidance!

I've made the requested changes:

- Implemented the use of useKResponsiveWindow to determine breakpoints dynamically.
- Added a CSS solution to truncate the placeholder text "Find something to learn" with an ellipsis (text-overflow: ellipsis, white-space: nowrap, and overflow: hidden styles applied to the .search-input element).
- Updated the placeholder text to dynamically display "Find" on smaller screens (breakpoint <= 3.5) where truncation isn't sufficient.
- Reduced the placeholder font size for better fit and readability on narrower viewports (font-size: 12px for screens below 1260px).

Comment (Abhishek-Punhani) [reply packages/kolibri-common/components/SearchBox.vue]: [Screencast from 01-14-2025 11:45:39 AM.webm](https://github.com/user-attachments/assets/5e78ce7c-ecb3-49d6-840a-9c9e8b47eb9e)

File: packages/kolibri-common/components/SearchBox.vue [hunk 4]
```diff
@@ -117,6 +124,12 @@
           textAlign: this.isRtl ? 'right' : '',
         };
       },
+      computedPlaceholder() {
+        if (this.windowBreakpoint <= 3.5) {
```
Comment (AlexVelezLl) [inline packages/kolibri-common/components/SearchBox.vue]: We should just test for 3 and 4 breakpoints, so lets update this validation to `if ([3, 4].includes(this.windowBreakpoint)) {`

File: packages/kolibri-common/components/SearchBox.vue [hunk 5]
```diff
@@ -184,8 +200,16 @@
...
     padding-left: 8px;
     margin: 0;
+    overflow: hidden;
+    text-overflow: ellipsis;
+    white-space: nowrap;
     vertical-align: middle;
     border: 0;
+    @media (max-width: 1260px) {
+      &::placeholder {
+        font-size: 12px;
```
Comment (AlexVelezLl) [inline packages/kolibri-common/components/SearchBox.vue]: Lets remove this font-size, as is being too small, and the font-size of the rest of the text doesnt change, so I think the placeholder text shouldnt neither.

File: packages/kolibri-common/components/SearchBox.vue [hunk 6]
```diff
@@ -117,6 +124,12 @@
           textAlign: this.isRtl ? 'right' : '',
         };
       },
+      computedPlaceholder() {
+        if (this.windowBreakpoint <= 3.5) {
+          return this.$tr('find');
+        }
+        return this.placeholder || coreString('searchLabel');
```
Comment (AlexVelezLl) [inline packages/kolibri-common/components/SearchBox.vue:131]: Bear in mind that the `this.placeholder` value should have max priority. If its defined we should return it regardless of the windowBreakpoint

**Review by AlexVelezLl — CHANGES_REQUESTED** [review]
Thanks @Abhishek-Punhani! We are almost there! I just left some minor comments, let me know if you have any question :).

File: packages/kolibri-common/components/SearchBox.vue (hunk 6 above)
Comment (Abhishek-Punhani) [reply packages/kolibri-common/components/SearchBox.vue:131]: @AlexVelezLl  Thank you for the feedback!

Just to confirm, should we always display this.placeholder regardless of the screen size? And only when this.placeholder is not defined, we fallback to displaying "Find" for smaller screen sizes? Please let me know if that aligns with the expected behavior, and I can make the necessary adjustments.

Comment (AlexVelezLl) [reply packages/kolibri-common/components/SearchBox.vue:131]: > Just to confirm, should we always display this.placeholder regardless of the screen size? And only when this.placeholder is not defined, we fallback to displaying "Find" for smaller screen sizes? 

Yes, thats it @Abhishek-Punhani . We only need to tweak the find... string when there isnt a this.placeholder value set

Comment (Abhishek-Punhani) [reply packages/kolibri-common/components/SearchBox.vue:131]: @AlexVelezLl  Thanks for clarifying. I guess I have already pushed required changes .Please let me know if any further changes are required.

**Review by AlexVelezLl — APPROVED** [review]
Thanks for your contribution @Abhishek-Punhani! Code changes makes sense, and manual QA confirms the expected behaviour. Thanks!
