### PR TITLE
Use TextTruncatorCss for cards on library page and truncate resource titles to five lines

### LINKED ISSUE #8667: text does not wrap in cards
## Observed behavior

Text in content cards is not wrapping. For example:

image

## Expected behavior

Text should wrap and fill all available vertical space and only truncate at the end if there still isn't room.

## User-facing consequences

Cannot read titles even when space is available

## Steps to reproduce

Browse library content

## Context

0.15.0-beta1

### PR DESCRIPTION
**Pull request by MisRob**
## Summary

Fixes a bug when the resource title was truncated to one line instead of five lines on the library page and in line with #8532 removes `TextTruncator` in favor of `TextTruncatorCss` on that opportunity.

| Before | After |
| --------- | ------ |
| before | after |

## References

Fixes #8667

## Reviewer guidance

Check cards on the library page in regards to text truncation

## Testing checklist

- [x] Contributor has fully tested the PR manually
- [x] If there are any front-end changes, before/after screenshots are included
- [ ] Critical user journeys are covered by Gherkin stories
- [ ] Critical and brittle code paths are covered by unit tests

## PR process

- [x] PR has the correct target branch and milestone
- [x] PR has 'needs review' or 'work-in-progress' label
- [x] If PR is ready for review, a reviewer has been added. (Don't use 'Assignees')
- [ ] If this is an important user-facing change, PR or related issue has a 'changelog' label
- [ ] If this includes an internal dependency change, a link to the diff is provided

## Reviewer checklist

- Automated test coverage is satisfactory
- PR is fully functional
- PR has been tested for [accessibility regressions](http://kolibri-dev.readthedocs.io/en/develop/manual_testing.html#accessibility-a11y-testing)
- External dependency files were updated if necessary (`yarn` and `pip`)
- Documentation is updated
- Contributor is in AUTHORS.md

### CODE REVIEW

File: kolibri/plugins/learn/assets/src/views/HybridLearningContentCard/index.vue [hunk 1]
```diff
@@ -138,14 +138,6 @@
         }
         return styles;
       },
-      maxTitleHeight() {
```
Comment (MisRob) [inline kolibri/plugins/learn/assets/src/views/HybridLearningContentCard/index.vue:141]: The original implementation didn't work in some cases because `this.subtitle` was always `undefined`. I am not sure what was supposed to be represented by `subtitle`. Looking into designs, maybe it was meant to be a category text? (e.g. _"Logical and critical thinking"_ on the screenshot below). In any case, I haven't noticed any indications in the current code that I should maintain this conditional logic because it seems that we don't display a category yet, so I removed it all and just replaced it with the five lines limit for now.

design

**Review by indirectlylit — APPROVED** [review]
text wrapping appears to work correctly for me

File: kolibri/plugins/learn/assets/src/views/HybridLearningContentCard/index.vue (hunk 1 above)
Comment (indirectlylit) [reply kolibri/plugins/learn/assets/src/views/HybridLearningContentCard/index.vue:141]: makes sense to me. I don't know the details of the designs though
