### PR TITLE
Attempt to fix issues seemingly caused by global loading state not being observed.

### LINKED ISSUE #11380: Quizzes - Incorrect score report
## Observed behavior
Observed while testing https://github.com/learningequality/kolibri/pull/11374 but not caused by the changes made there as it's extant in previous builds as well - once a quiz has been completed clicking on the quiz to view the details results in in incorrect score and number of questions. Then if I go back and click the report again I am seeing the correct values.
The following error is displayed in the console: `TypeError: Cannot read properties of null (reading 'restoreSerializedState')`

## Expected behavior
Correctly displayed quiz report and score.

## Steps to reproduce the issue
1. Install the build from https://github.com/learningequality/kolibri/pull/11177
2. Start a quiz on a full device.
3. Take the quiz on a learn-only device.
4. Wait for sync to happen and click on the quiz to view the details.

## More information

Coach:

https://github.com/learningequality/kolibri/assets/79847249/ab62cfbe-7537-4ffa-811f-aa1380040c04

Learner:

https://github.com/learningequality/kolibri/assets/79847249/9580b2f7-afa6-453a-98d7-d822b1183c24

## Usage Details
Kolibri 0.16beta6
Ubuntu - Chrome, Firefox

### PR DESCRIPTION
**Pull request by rtibbles**
## Summary
* The removal of the global loader from CoreBase was never fully accounted for in the coach reports, which were still relying on the delay of component render until page specific state was instantiated in order to prevent access to potentially undefined state
* Fixes this by adding in a temporary measure into the CoachImmersivePage to show nothing except the ImmersivePage linear loader while global loading state is active.
* Similar issues seem to be active on the class routes for the Learn plugin, it fixes this by adding in loading states on each individual class route page.

## References
Fixes [#11380](https://github.com/learningequality/kolibri/issues/11380)

## Reviewer guidance
@pcenov I wasn't able to exactly replicate the errors you were seeing, but have definitely made the described flow more robust. I think the errors were occurring due to conflicting state being displayed/loaded, but I can't be sure.

----

## Testing checklist

- [ ] Contributor has fully tested the PR manually
- [ ] If there are any front-end changes, before/after screenshots are included
- [ ] Critical user journeys are covered by Gherkin stories
- [ ] Critical and brittle code paths are covered by unit tests

## PR process

- [ ] PR has the correct target branch and milestone
- [ ] PR has 'needs review' or 'work-in-progress' label
- [ ] If PR is ready for review, a reviewer has been added. (Don't use 'Assignees')
- [ ] If this is an important user-facing change, PR or related issue has a 'changelog' label
- [ ] If this includes an internal dependency change, a link to the diff is provided

## Reviewer checklist

- Automated test coverage is satisfactory
- PR is fully functional
- PR has been tested for [accessibility regressions](http://kolibri-dev.readthedocs.io/en/develop/manual_testing.html#accessibility-a11y-testing)
- External dependency files were updated if necessary (`yarn` and `pip`)
- Documentation is updated
- Contributor is in AUTHORS.md

### CODE REVIEW

**Review by pcenov — CHANGES_REQUESTED** [review]
Hi @rtibbles I confirm that you have managed to fix the issue at Coach > Class home however this is still happening at the learner's home page (apologies for not pointing out this more clearly in https://github.com/learningequality/kolibri/issues/11380):

https://github.com/learningequality/kolibri/assets/79847249/97bc3a06-9772-4df0-8570-2711c851bcc9

**Comment by rtibbles** [comment]
Ah, sorry - I had thought this was only impacting the coach - I will revisit!

**Comment by rtibbles** [comment]
@pcenov I replicated this issue as well and am fairly sure it should now be fixed.

File: kolibri/plugins/coach/assets/src/views/CoachImmersivePage.vue [hunk 1]
```diff
@@ -12,7 +12,12 @@
       :loading="loading"
       :appearanceOverrides="appearanceOverrides"
     >
-      <div class="coach-main">
+      <KCircularLoader
+        v-if="coreLoading"
```
Comment (MisRob) [inline kolibri/plugins/coach/assets/src/views/CoachImmersivePage.vue]: Some time ago, we attempted to move away from having global loading state being managed by these root pages but instead let it be managed by the child pages as such architecture showed up not being very flexible and on some cases preventing us from updating pages in a reasonable manner. I'm concerned that by introducing this again here will lead to same issues. I didn't dig into detail into all pages at this point, but here's one example where I see potential confusion https://github.com/learningequality/kolibri/blob/release-v0.16.x/kolibri/plugins/coach/assets/src/views/plan/QuizEditDetailsPage.vue#L93-L96

I didn't review in detail yet and can think about it more. Just looking at it very high-level, I think that this type of change may easily end up having unexpected impact and seems to go against the new pattern we've tried to adopt in the whole codebase to address problems caused by this approach. For now, I wanted to ask what was the reason for introducing it in this manner and if you've already considered alternatives.

Comment (MisRob) [reply kolibri/plugins/coach/assets/src/views/CoachImmersivePage.vue]: I know it'd be lots of work to do it from child pages. On the other hand, it seems that we'd need to have a look at them anyways to cleanup conflicting or overlapping loading states so that we don't run again into issues we've been cleaning up lately after the core base refactor.

Comment (rtibbles) [reply kolibri/plugins/coach/assets/src/views/CoachImmersivePage.vue]: I did this because when the refactor happened to remove the global loading state from CoreBase, it wasn't then re-added to each individual page in coach, which for many of the pages were reliant on the global loading state preventing their components from being shown until state has been set.

As a result, all of these components make unguarded reads from their module state - or are not set up to reactively update if the module state changes while they are displayed. This is the cause of the bug that Peter has reported here.

I agree that we _should_ be moving in the direction you describe, but this is a bandaid to account for the incomplete refactor, and I think not doing it is far more likely to leave additional regressions undiscovered until after release.

The code you are pointing to has not changed for 4 years (long predating the refactor) so I think the chance of this change causing issues for the loading state there is minimal.

Comment (MisRob) [reply kolibri/plugins/coach/assets/src/views/CoachImmersivePage.vue]: I definitely agree it's caused by incomplete refactor and no problem to keep addressing this outside of the scope of this particular PR. My only suggestion would be to have an issue explaining why this change happened and in what direction we want to move on.

> The code you are pointing to has not changed for 4 years (long predating the refactor) so I think the chance of this change causing issues for the loading state there is minimal.

I would rather say that we don't know, but one thing we can do to be more sure is to test loading states thoroughly.

One last high-level question, before I look into details, why is circular loader used rather than the linear one?

Comment (rtibbles) [reply kolibri/plugins/coach/assets/src/views/CoachImmersivePage.vue]: The only PRs that I am aware of that have made changes to the loading state since the refactor are this one: https://github.com/learningequality/kolibri/pull/11218 and this one: https://github.com/learningequality/kolibri/pull/11201

Neither of which affect pages that use the CoachImmersivePage, so I think the chance of a conflict between this change and previous loading state work. Unless I've missed a PR?

Comment (rtibbles) [reply kolibri/plugins/coach/assets/src/views/CoachImmersivePage.vue]: > One last high-level question, before I look into details, why is circular loader used rather than the linear one?

The linear loader's appearance is somewhat subtle, and can easily not be noticed (at least by me) - plus there is already a linear loader in the immersive and app bar pages I believe, so adding another one below seemed a bit odd.

The alternative is not to include a loader here at all and just gate the main HTML tag with `v-if="!loading"`

Comment (MisRob) [reply kolibri/plugins/coach/assets/src/views/CoachImmersivePage.vue]: > Neither of which affect pages that use the CoachImmersivePage, so I think the chance of a conflict between this change and previous loading state work. Unless I've missed a PR?

It's possible, yes. I don't recall all PRs as I only worked on a small portion. @nucleogenesis and @marcellamaki may know more. From my perspective, in many places in Coach we moved towards handling loading state locally overall, that's why I think that introducing new global condition to one of the root pages would deserve some testing across Coach rather than just verifying the bug. Hopefully, it will be okay. It's just my recommendation based on various updates around loaders during the past few months.

> The linear loader's appearance is somewhat subtle, and can easily not be noticed (at least by me) - plus there is already a linear loader in the immersive and app bar pages I believe, so adding another one below seemed a bit odd.

> The alternative is not to include a loader here at all and just gate the main HTML tag with v-if="!loading"

Regarding technical side of things, I don't know what's better, taking into account that loading states are overall work in progress. So I think there's not a perfect solution at this point and either is okay.

Regarding UX and the subtlety of the linear loader, that's true. I usually recommend to follow [our current guidelines](https://develop--kolibri-design-system.netlify.app/loaders/#overview) to not complicate things and to not introduce inconsistencies into the app. I also see this as something to be discussed with designers at first, and then refactored in the whole Kolibri if we decide to move away from linear loaders. To prevent back and forth and to be on the same page with them and also between us, devs, rather then each of us approaching it differently. So from this point of view `v-if="!loading"` would make sense?

Comment (rtibbles) [reply kolibri/plugins/coach/assets/src/views/CoachImmersivePage.vue]: Yes, that should work - I'll double check the linear loader is appearing properly for the immersive pages and remove the circular loader.

Comment (rtibbles) [reply kolibri/plugins/coach/assets/src/views/CoachImmersivePage.vue]: Updated.

Comment (MisRob) [reply kolibri/plugins/coach/assets/src/views/CoachImmersivePage.vue]: I can also raise the issue of global vs local loaders in a KDS tactical if that'd be helpful. I heard more devs "complaining" about it :)

Comment (rtibbles) [reply kolibri/plugins/coach/assets/src/views/CoachImmersivePage.vue]: I am fine with mostly doing away with global loaders (although I think having the linear loader consistently be turned on until route navigation has completed at least would be fairly easy to do globally, without having to mess around with anything in each route) - but getting rid of them completely would mean that we need to rearchitect all our pages to handle their loading states internally (which is probably best achieved by moving their loading state into `setup` in the component).

**Review by pcenov — CHANGES_REQUESTED** [review]
@rtibbles Now when I submit the quiz I am brought back to the Home page seeing only the spinner icon and manually refreshing the page doesn't help. I have to navigate to a different plugin and come back to the Home page to see the correct data:

https://github.com/learningequality/kolibri/assets/79847249/cb6dc03d-c307-429b-b491-f698142b0386

File: kolibri/plugins/coach/assets/src/views/CoachImmersivePage.vue (hunk 1 above)
Comment (MisRob) [reply kolibri/plugins/coach/assets/src/views/CoachImmersivePage.vue]: > although I think having the linear loader consistently be turned on until route navigation has completed at least would be fairly easy to do globally, without having to mess around with anything in each route

Yes, I see value in this. Can't think of any issues in this particular case. I assume it should be pretty brief (after we deal with issues like https://github.com/learningequality/kolibri/issues/11219) so in that case it may even make more sense to stay with the subtler global linear loader.

Comment (MisRob) [reply kolibri/plugins/coach/assets/src/views/CoachImmersivePage.vue]: By "it" I meant route navigation, if we stop doing API requests there

**Comment by rtibbles** [comment]
Odd, I'll take another look @pcenov.

**Comment by rtibbles** [comment]
Hi @pcenov - thanks, this was again caused by some sloppy programming by me - this should now be resolved (the error was that it was always waiting about 30 seconds to stop showing the loading state!)

**Review by pcenov — APPROVED** [review]
Thanks @rtibbles - everything is working correctly now, good to go!

**Review by MisRob — APPROVED** [review]
Thank you @rtibbles. In the light of what we discussed before, I think it's good to go. I didn't check in detail the affected sub-pages - relying on QA done. One thing I'd ask you is to only prepare a follow-up issue we talked about earlier.

**Comment by rtibbles** [comment]
Follow up filed here: https://github.com/learningequality/kolibri/issues/11422

**Comment by MisRob** [comment]
Thank you, it's looking great
