### PR TITLE
Handle keyboard-dependent focus outlines in Vuex

### LINKED ISSUE #4822: regression: focus outline styling displays when clicking
### Observed behavior

the styles now appear when you click - sometimes briefly, and sometimes permanently:

image

### Expected behavior

Outlines should only show when keyboard-tabbing. There is a mechanism in `body` like `modality="keyboard"` or something similar. I don't know offhand which library is providing it for us, but it's supposed to apply `outline: none` until the user starts keyboard-navigating.

### User-facing consequences

helpful outline styling for keyboard users is unhelpful and unattractive for mouse and touchscreen users

### Steps to reproduce

click around the app and notice lots of new outlines appearing

### Context

see https://github.com/learningequality/kolibri/pull/4802/files

### PR DESCRIPTION
**Pull request by jonboiser**
### Summary

1. vendors and modifies modality.js helper to manipulate vuex theme module. manages a `core.modality` property in vuex
1. rewrites $coreOutline getter to conditionally apply outline styles depending on value of `core.modality`

### Reviewer guidance

1. Interact with links, buttons, and all kinds of inputs (inside and outside of exercises) to see if keyboard focus works okay

### References

Fixes #4822 
----

### Contributor Checklist

PR process:

- [ ] PR has the correct target branch and milestone
- [ ] PR has 'needs review' or 'work-in-progress' label
- [ ] If PR is ready for review, a reviewer has been added. (Don't use 'Assignees')
- [ ] If this is an important user-facing change, PR or related issue has a 'changelog' label
- [ ] If this includes an internal dependency change, a link to the diff is provided

Testing:

- [ ] Contributor has fully tested the PR manually
- [ ] If there are any front-end changes, before/after screenshots are included
- [ ] Gherkin stories have been updated
- [ ] Unit tests have been updated

### Reviewer Checklist

- Automated test coverage is satisfactory
- PR is fully functional
- PR has been tested for [accessibility regressions](http://kolibri-dev.readthedocs.io/en/develop/manual_testing.html#accessibility-a11y-testing)
- External dependency files were updated if necessary (`yarn` and `pip`)
- Documentation is updated
- Contributor is in AUTHORS.rst

### CODE REVIEW

File: kolibri/core/assets/src/core-app/vuexModality.js [hunk 1]
```diff
@@ -0,0 +1,112 @@
...
+      if (isHandlingKeyboardThrottle) {
+        clearTimeout(isHandlingKeyboardThrottle);
+      }
+
+      isHandlingKeyboardThrottle = setTimeout(() => {
+        hadKeyboardEvent = false;
+      }, 100);
+    },
+    true
+  );
```
Comment (indirectlylit) [inline kolibri/core/assets/src/core-app/vuexModality.js:93]: I know this was probably just copied over during the port so fine to leave as-is. However heads-up that we have two throttling libraries already included:

* https://github.com/pelotoncycle/frame-throttle for high FPS stuff
* lodash throttle for other stuff

File: kolibri/core/assets/src/core-app/vuexModality.js [hunk 2]
```diff
@@ -0,0 +1,112 @@
...
+
+    if (el.msMatchesSelector) {
+      return el.msMatchesSelector;
+    }
+
+    /* eslint-disable-next-line */
+    console.error("Couldn't find any matchesSelector method on document.body.");
+  })();
+
+  const disableFocusRingByDefault = function() {
```
Comment (rtibbles) [inline kolibri/core/assets/src/core-app/vuexModality.js:49]: Do we need this function here? Presumably the Keen-UI helper is still doing this part?

File: kolibri/core/assets/src/core-app/vuexModality.js [hunk 3]
```diff
@@ -0,0 +1,112 @@
...
+      }, 100);
+    },
+    true
+  );
+
+  document.body.addEventListener(
+    'focus',
+    e => {
+      if (hadKeyboardEvent || focusTriggersKeyboardModality(e.target)) {
+        kolibriGlobal.coreVue.vuex.store.commit('SET_MODALITY', 'keyboard');
```
Comment (rtibbles) [inline kolibri/core/assets/src/core-app/vuexModality.js:99]: Any reason we can't just import the store here, rather than referencing the global?
Should be able to do: `import store from 'kolibri.coreVue.vuex.store';` and then just reference that, no?

File: kolibri/core/assets/src/core-app/vuexModality.js [hunk 4]
```diff
@@ -0,0 +1,112 @@
...
+      }
+    },
+    true
+  );
+
+  document.body.addEventListener(
+    'blur',
+    () => {
+      kolibriGlobal.coreVue.vuex.store.commit('SET_MODALITY', null);
```
Comment (rtibbles) [inline kolibri/core/assets/src/core-app/vuexModality.js:108]: As above.

**Review by rtibbles — COMMENTED** [review]
Can do a little bit of cleanup in the vendored code, but looks like the right fix!

**Comment by indirectlylit** [comment]
tested and it seems to work well

note there are broken snapshot tests

**Review by indirectlylit — APPROVED** [review]
merging in  -  created follow up issue at https://github.com/learningequality/kolibri/issues/4859
