### PR TITLE
Error page formatting

### LINKED ISSUE #7098: error page formatting
### Observed behavior

copy button missing top margin, and clipped shadows:

image

observed in https://github.com/learningequality/kolibri/issues/7097

### Expected behavior

proper formatting as seen in 0.13

### User-facing consequences

styling regression

### Steps to reproduce

manually force an error

### Context

0.14 beta 2

### PR DESCRIPTION
**Pull request by MisRob**
### Summary

Add margin to "Copy to clipboard" button.

| Before | After |
|---|---|
| error-before | error-after | 

### Reviewer guidance

Manually force an error

### References

Fixes #7098

----

### Contributor Checklist

PR process:

- [ ] PR has the correct target branch and milestone
- [ ] PR has 'needs review' or 'work-in-progress' label
- [ ] If PR is ready for review, a reviewer has been added. (Don't use 'Assignees')
- [ ] If this is an important user-facing change, PR or related issue has a 'changelog' label
- [ ] If this includes an internal dependency change, a link to the diff is provided

Testing:

- [x] Contributor has fully tested the PR manually
- [x] If there are any front-end changes, before/after screenshots are included
- [ ] Critical user journeys are covered by Gherkin stories
- [ ] Critical and brittle code paths are covered by unit tests

### Reviewer Checklist

- Automated test coverage is satisfactory
- PR is fully functional
- PR has been tested for [accessibility regressions](http://kolibri-dev.readthedocs.io/en/develop/manual_testing.html#accessibility-a11y-testing)
- External dependency files were updated if necessary (`yarn` and `pip`)
- Documentation is updated
- Contributor is in AUTHORS.md

### CODE REVIEW

**Review by jonboiser — APPROVED** [review]
Looks good on IE11!

File: kolibri/core/assets/src/views/AppError/TechnicalTextBlock.vue [hunk 1]
```diff
@@ -20,6 +20,7 @@
       <KButton
         v-if="clipboardCapable"
         ref="copyButton"
+        :style="{ marginTop: '8px', marginBottom: '8px' }"
```
Comment (indirectlylit) [inline kolibri/core/assets/src/views/AppError/TechnicalTextBlock.vue:23]: note that since nothing is dynamic here, this could have been written in pure css:

```
style="margin-top: 8px; margin-bottom: 8px;"
```
