### PR TITLE
Prevent attemptlog overwriting in vuex store

### LINKED ISSUE #2417: Coach report under learner tab's answer history
## Summary
After completing mastery of challenge set for **learner**. When I login with teacher id, I can not see all the questions in answer history. 
There is mismatch in the answer history and the questions attempted history.

## System information

 - Version: Kolibri 0.4.6beta1
 - Operating system: Ubuntu14.04
 - Browser: Chrome

## How to reproduce

1. Login with learner.
2. Solve complete exercise of any subtopic.(Reach mastery level)
3. Then, Login with coach user.
4. Click on Coach tab then go to learners.
5. Go to the topic that learner solved.

## Screenshots

Completed mastery by solving more than 4 questions but showing only 2
img_20171011_172137

In question 1, question does not change but correct option keeps changing 
img_20171011_172144
img_20171011_172147
img_20171011_172150
img_20171011_172152
img_20171011_172154

### PR DESCRIPTION
**Pull request by rtibbles**
# Checklist

- [x] PR has the correct target milestone when it's merged
- [x] Automated test coverage is satisfactory
- [x] PR has been fully tested manually
- [ ] Documentation is updated as necessary
- [ ] External dependency files are updated (`yarn` and `pip`)
- [ ] If internal dependency are updated, link to diff is included
- [ ] Screenshots of any front-end changes are in the PR description
- [ ] CHANGELOG.rst is updated for high-level changes
- [ ] You've added yourself to AUTHORS.rst if you're not there

# Details

### Summary

Previously, we were using `samePageCheckGenerator` to prevent delayed attemptLog saves from writing their payload into the vuex store.

Unfortunately, this strategy does not work, because when we move onto a new item in an exercise (and hence a new attempt log) the page does not change, it's still on the same resource.

This had the unfortunate effect of a new attemptlog being created in the vuex store (using the `createAttemptLog` action), but then that being overwritten when the attemptLog save resolved in `saveAndStoreAttemptLog` action.

This meant that a subsequent answer would then be appended to the attemptlog for the previous question as an additional interaction, and not recorded on the new attempt log.

This PR solves that in a two step strategy:

* Firstly, by creating a test to replicate this scenario.
* Creating a 'same item' check instead of same page check, which only allows the resulting save payload to be set if two conditions are met: firstly, that at the time the save was initiated, the attemptlog did not have an id, we need this id for future updating saves, but no other information saved to the server needs to be persisted back into the vuex store; secondly, we check that the item id when the save has resolved is the same as when the save was initiated, ensuring that we are not overwriting the vuex attemptlog representation for a different question.

Fixes #2417

This is a bit of a pain to test, as it relies on a race condition between the frontend and the API. I think my test case covers the problem well, but to actually check that this is resolved you would need to add this code to the AttemptLogViewSet in kolibri/logger/api.py:
```
    def create(self, request, *args, **kwargs):
        import time
        time.wait(10)
        return super(AttemptLogViewSet, self).create(request, *args, **kwargs)
```
This should delay the initial AttemptLog save by 10 seconds, and then you can wait for that API call to complete, and then answer another question.
Without the patch in this PR, this should replicate the issue. With it, it should not have an effect.

### CODE REVIEW

File: kolibri/core/assets/src/state/actions.js [hunk 1]
```diff
@@ -642,8 +642,13 @@ function saveAttemptLog(store) {
 }
 
 function saveAndStoreAttemptLog(store) {
+  const attemptLogId = store.state.core.logging.attempt.id;
+  const attemptLogItem = store.state.core.logging.attempt.item;
+  const storeAttemptLog = () =>
```
Comment (indirectlylit) [inline kolibri/core/assets/src/state/actions.js]: maybe call this `isSameAttempt`?

some more comments in here would be helpful - there's a lot of useful info in the PR description.

is the idea here that unsaved attempts don't have IDs?

Comment (rtibbles) [reply kolibri/core/assets/src/state/actions.js]: Yeah, I can copy some stuff over.

Unsaved attempts don't have ids, no.

**Comment by rtibbles** [comment]
I can't think of an instance where the samePageCheckGenerator would fail but the sameItem check wouldn't.

**Comment by rtibbles** [comment]
Updated with more semantic check function name and a big comment.
