### PR TITLE
Fix the invalid prop on the KTable usage

### LINKED ISSUE #13243: Facility : Invalid prop console warning
Originally reported [here](https://github.com/learningequality/kolibri/issues/13142)

## Observed behavior

An invalid prop console warning can be seen for Facility>Users and Facility>Classes table.

Image
## Guidance
The introduction of [defaultSort attribute](https://github.com/learningequality/kolibri-design-system/pull/824) to KTable in KDS mandates the addition of a columnId prop to the headers array for every column. Examples for this can be seen in the documentation for KTable [here](https://design-system.learningequality.org/ktable).
Quoting an example from the same, the headers array needs to be defined as ,
```
 headers: [
        { label: 'Name', dataType: 'string', columnId: 'name' },
        { label: 'Age', dataType: 'number', columnId: 'age' },
        { label: 'City', dataType: 'string', columnId: 'city' },
      ],
```
This needs to be done for both the [Facility>Users](https://github.com/learningequality/kolibri/blob/dd5e8837baa4d624091c92b5d2cb39aab96f061f/kolibri/plugins/facility/assets/src/views/UserPage/index.vue) and [Facility>Classes](https://github.com/learningequality/kolibri/blob/dd5e8837baa4d624091c92b5d2cb39aab96f061f/kolibri/plugins/facility/assets/src/views/ManageClassPage/index.vue) table

## Steps to reproduce

- Navigate to Facility>Users or Facility>Classes
- Check the console logs.

cc @MisRob

### PR DESCRIPTION
**Pull request by AllanOXDi**
## Summary
This PR fixes the invalid prop console warning on KTable
Closes #13243

## References
#13243

## Reviewer guidance

1. Navigate to the Facility plugin 
2. Click on the user link
3. Inspect what is happening in the browser console.

### CODE REVIEW

File: kolibri/plugins/facility/assets/src/views/ManageClassPage/index.vue [hunk 1]
```diff
@@ -145,24 +145,28 @@
             dataType: 'string',
             minWidth: '150px',
             width: '20%',
+            columnId: this.coreString('classNameLabel'),
```
Comment (nucleogenesis) [inline kolibri/plugins/facility/assets/src/views/ManageClassPage/index.vue]: Why are you using the translated string here for the `columnId`? Is it going to be user-facing or just internal to KTable?

Comment (AllanOXDi) [reply kolibri/plugins/facility/assets/src/views/ManageClassPage/index.vue]: It's supposed to be internal.

Comment (BabyElias) [reply kolibri/plugins/facility/assets/src/views/ManageClassPage/index.vue]: I think we can omit using translated strings here then, since it is unnecessary for internal usage.

**Review by BabyElias — APPROVED** [review]
Additions look good to me, the console logs have been resolved :)

**Review by AlexVelezLl — APPROVED** [review]
LGTM thanks @AllanOXDi!
