### PR TITLE
conditionalizes display of device connection status and prevents unec…

### LINKED ISSUE #10735: DeviceConnectionStatus is inserted in every page on learn and continuously polls the backend regardless of whether we are browsing a remote device
## Observed behavior
This component https://github.com/learningequality/kolibri/blob/develop/kolibri/plugins/learn/assets/src/views/DeviceConnectionStatus.vue#L42

Is injected into multiple pages in learn now, but is not conditionalized to only appear in the case that the deviceId is not null, nor does it restrict its polling behaviour to only occur when a remote device is being browsed.

## Errors and logs
When browsing learn as a guest, this causes repeated 401s from attempting to access the backend without proper authentication.

## Expected behavior
No polling should happen when a remote device is not being browsed.

Additionally, it seems a bit wasteful to be polling for _every_ device, rather than the one specifically identified by the deviceId.

## User-facing consequences
Lots of console errors for a guest user. Hammering the Kolibri server unnecessarily to get all the current devices even when not needed.

## Steps to reproduce
Open any page in learn.

### PR DESCRIPTION
**Pull request by akolson**
## Summary

This pr conditionalizes display of device connection status and prevents unnecessary device polling. It also adds the ability to filter by deviceId

## References

Fixes https://github.com/learningequality/kolibri/issues/10735

## Reviewer guidance

- Browse any page in the `Learn` plugin
- Inspect the page taking note of any polling on the pages in the network tab.
   - Polling should occur when exploring remote content browsing devices only
   - Look out for `/discovery/networklocation` as one of the requests polled

----

## Testing checklist

- [x] Contributor has fully tested the PR manually
- [ ] If there are any front-end changes, before/after screenshots are included
- [ ] Critical user journeys are covered by Gherkin stories
- [ ] Critical and brittle code paths are covered by unit tests

## PR process

- [x] PR has the correct target branch and milestone
- [x] PR has 'needs review' or 'work-in-progress' label
- [x] If PR is ready for review, a reviewer has been added. (Don't use 'Assignees')
- [ ] If this is an important user-facing change, PR or related issue has a 'changelog' label
- [ ] If this includes an internal dependency change, a link to the diff is provided

## Reviewer checklist

- Automated test coverage is satisfactory
- PR is fully functional
- PR has been tested for [accessibility regressions](http://kolibri-dev.readthedocs.io/en/develop/manual_testing.html#accessibility-a11y-testing)
- External dependency files were updated if necessary (`yarn` and `pip`)
- Documentation is updated
- Contributor is in AUTHORS.md

### CODE REVIEW

File: kolibri/plugins/learn/assets/src/views/TopicsPage/index.vue [hunk 1]
```diff
@@ -31,7 +35,10 @@
       />
 
       <!-- mobile tabs (different alignment and interactions) -->
-      <TopicsMobileHeader v-else :topic="topic" />
```
Comment (rtibbles) [inline kolibri/plugins/learn/assets/src/views/TopicsPage/index.vue]: Seeing a lot of flyby refactors caused by what I assume is IDE based code formatting. I would prefer that these changes not get committed, as it causes code churn/blame changes that make tracking through the git history a little bit more difficult.

I would suggest ensuring that the autoformatting that your code editor does uses the same criteria as Kolibri enforces to avoid this.

File: kolibri/core/assets/src/views/sync/SelectDeviceModalGroup/useDevices.js [hunk 2]
```diff
@@ -153,15 +153,15 @@ export function useDevicesWithChannel(channelId = '') {
  *  filterFailed: Ref<bool>, forceFetch: (function(): Promise<void>)
  * }}
  */
-export function useDevicesWithFacility({ facilityId = '', soud = false } = {}) {
+export function useDevicesWithFacility({ deviceId, facilityId = '', soud = false } = {}) {
```
Comment (rtibbles) [inline kolibri/core/assets/src/views/sync/SelectDeviceModalGroup/useDevices.js]: I wonder if `useDevicesWithFacility` is the right place for this? Seems like 'facilityId' has become optional now, which means that the name of the function seems wrong?

File: kolibri/plugins/learn/assets/src/views/DeviceConnectionStatus.vue [hunk 3]
```diff
@@ -39,7 +39,10 @@
        * null has been specified to return both type of devices which
        * is necesary for device connection statuses
        */
-      const { isFetching, devices } = useDevicesWithFacility({ soud: null });
+      const { isFetching, devices } = useDevicesWithFacility({
+        deviceId: props.deviceId,
+        soud: null,
+      });
       const isFetched = ref(false);
       const allDevices = ref([]);
```
Comment (rtibbles) [inline kolibri/plugins/learn/assets/src/views/DeviceConnectionStatus.vue:41]: We should also conditionalize the Studio getting on whether `deviceId` is the Studio deviceId, not just that the deviceId is truthy. Otherwise, we're going to be continually pinging the Studio status endpoint for a non-Studio remote device.

**Review by rtibbles — CHANGES_REQUESTED** [review]
One question about the API/naming. Two blockers around unnecessary code linting, and still polling the Studio endpoint when not needed.

File: kolibri/plugins/learn/assets/src/views/TopicsPage/index.vue (hunk 1 above)
Comment (akolson) [reply kolibri/plugins/learn/assets/src/views/TopicsPage/index.vue]: Not sure what could be wrong here. But I do normally run the linting command which almost every time reverts the IDE formatting. Any reason this could be happening?

Comment (rtibbles) [reply kolibri/plugins/learn/assets/src/views/TopicsPage/index.vue]: I think it's more that the way your IDE has linted it is still acceptable (but so is the original) so your IDE is being _more_ opinionated than the Kolibri linting in this case.

**Review by rtibbles — APPROVED** [review]

File: kolibri/core/assets/src/views/sync/SelectDeviceModalGroup/useDevices.js (hunk 2 above)
Comment (akolson) [reply kolibri/core/assets/src/views/sync/SelectDeviceModalGroup/useDevices.js]: This was probably not a necessary change as `useDevices({id:<some id>})` works just fine. The changes have been reverted to keep this function for facility specific purposes.

**Review by pcenov — APPROVED** [review]
Excellent @akolson - the unnecessary device polling is removed now as specified.
