### PR TITLE
Card fixes

### LINKED ISSUE #12280: EQM: Improve card layout alignments/prevent overlapping text
_Originally posted by @pcenov in https://github.com/learningequality/kolibri/issues/12265#issuecomment-2165606357_
            

The text 'N questions unused' overlaps with either the coach resources icon or the text:

### PR DESCRIPTION
**Pull request by marcellamaki**
## Summary

Makes some mostly-cosmetic card layout and styling adjustments. Does a teensy refactor to put the learning activity chips and icon mapping into kolibri-common, which will be used in 0.18 as part of the card and refactoring work. 

## References
Fixes #12280 
[Related slack conversation](https://learningequality.slack.com/archives/C05FSV4BEJ1/p1719432456973439) 

## Reviewer guidance
Testing updates: 
content cards (both channel and resources) used in coach resources management 
- lesson and quiz creation
- Navigate up and down the topic tree from channel into folders and to resources and ensure all render correctly.
- Confirm that the layout and text does not collide even when on mobile screens, or when there is additional "helper text" on the card regarding question selection
- Ensure that there are no regressions in the lesson management work flow 

Learn:
I refactored the "LearningActivityChip" to `kolibri-common` so the places where it is used in learn should be regression tested. 
Screenshot 2024-06-27 at 1 53 41 PM
It's present in the resource's information side panel accessed in
- Bookmarks - clicking on the info for the card
- Topics - clicking on the info for the card
- Content Renderer/Resource page - clicking on the info for the open resource
- Library - clicking on the info for the card

----

## Testing checklist

- [ ] Contributor has fully tested the PR manually
- [ ] If there are any front-end changes, before/after screenshots are included
- [ ] Critical user journeys are covered by Gherkin stories
- [ ] Critical and brittle code paths are covered by unit tests

## PR process

- [ ] PR has the correct target branch and milestone
- [ ] PR has 'needs review' or 'work-in-progress' label
- [ ] If PR is ready for review, a reviewer has been added. (Don't use 'Assignees')
- [ ] If this is an important user-facing change, PR or related issue has a 'changelog' label
- [ ] If this includes an internal dependency change, a link to the diff is provided

## Reviewer checklist

- Automated test coverage is satisfactory
- PR is fully functional
- PR has been tested for [accessibility regressions](http://kolibri-dev.readthedocs.io/en/develop/manual_testing.html#accessibility-a11y-testing)
- External dependency files were updated if necessary (`yarn` and `pip`)
- Documentation is updated
- Contributor is in AUTHORS.md

### CODE REVIEW

File: kolibri/plugins/coach/assets/src/views/plan/LessonResourceSelectionPage/ContentCardList.vue [hunk 1]
```diff
@@ -45,7 +45,7 @@
           :title="content.title"
           :thumbnail="content.thumbnail"
           :description="content.description"
-          :kind="content.kind"
+          :kind="content.is_leaf ? content.learning_activities : 'folder'"
```
Comment (rtibbles) [inline kolibri/plugins/coach/assets/src/views/plan/LessonResourceSelectionPage/ContentCardList.vue]: Let's change the prop name here to indicate that it is no longer accepting a content kind?

File: kolibri/plugins/coach/assets/src/views/plan/LessonResourceSelectionPage/LessonContentCard/index.vue [hunk 2]
```diff
@@ -21,49 +14,49 @@
...
+        v-if="isLeaf"
+        :kind="kind"
+        class="chip"
+      />
     </div>
+    <CardThumbnail
+      v-if="!windowIsSmall"
+      class="thumbnail"
+      :thumbnail="thumbnail"
+      :kind="kind"
```
Comment (rtibbles) [inline kolibri/plugins/coach/assets/src/views/plan/LessonResourceSelectionPage/LessonContentCard/index.vue]: It seems that no updates have been made to the CardThumbnail component, but we are now passing a learning activity array to this, rather than a content kind, I haven't checked, but I expect this to end poorly.

File: kolibri/plugins/coach/assets/src/views/plan/LessonResourceSelectionPage/LessonContentCard/index.vue [hunk 3]
```diff
@@ -21,49 +14,49 @@
...
         <CoachContentLabel
           class="coach-content-label"
           :value="numCoachContents"
           :isTopic="isTopic"
         />
       </div>
       <slot name="notice"></slot>
+      <LearningActivityChip
+        v-if="isLeaf"
+        :kind="kind"
```
Comment (rtibbles) [inline kolibri/plugins/coach/assets/src/views/plan/LessonResourceSelectionPage/LessonContentCard/index.vue]: Is it a kind or a learning_activity? I know the component was already like this, but this naming all seems very confusing.

**Review by rtibbles — COMMENTED** [review]
I am _kind_ of confused by the names.

**Comment by pcenov** [comment]
Hi @marcellamaki - looks great in both desktop and mobile view, couldn't spot any issues caused by the changes made here.

I'm gonna mention that I noticed the following issue with overlapping learning activity chips, which is preexisting and I'm not sure whether is not caused by anything on Studio's end:

https://github.com/learningequality/kolibri/assets/79847249/ccf1668a-dd5a-4518-a7b2-0b120a706d47

You can replicate it by going to the following resource [Hoja de Reflexión para Estudiantes - Acertijos Wiixii](http://127.0.0.1:8080/en/learn/#/topics/2d04ed86aa8c519fae78a250e03d8482/c/227f743d6c37417da567a30056b67897?prevName=LIBRARY&prevQuery=%257B%2522prevName%2522%3A%2522LIBRARY%2522,%2522learning_activities%2522%3A%25223dSeJhqs%2522%257D&prevParams=%257B%2522deviceId%2522%3A%25222d04ed86aa8c519fae78a250e03d8482%2522%257D)

File: kolibri/plugins/coach/assets/src/views/plan/LessonResourceSelectionPage/LessonContentCard/index.vue [hunk 4]
```diff
@@ -91,25 +85,8 @@
...
-        default: null,
-      },
-      kind: {
-        type: String,
-        required: true,
-        validator: validateContentNodeKind,
-      },
-      isLeaf: {
-        type: Boolean,
+      content: {
```
Comment (rtibbles) [inline kolibri/plugins/coach/assets/src/views/plan/LessonResourceSelectionPage/LessonContentCard/index.vue:88]: As a tech debt cleanup, we should define a content node spec using the core validator stuff, so that we can just reuse that every time we want content/contentnode as a prop. I would be happy to be assigned to this.

**Review by rtibbles — APPROVED** [review]
I am confident now that even if the LearningActivityChip component exposes a very misleading prop name, it and the CardThumbnail component are both being given the correct values.
