### PR TITLE
don't use zeroconf to send channel/facility info

### LINKED ISSUE #6080: zeroconf: Crashes when starting devserver
### Observed behavior
Tried to run devserver.
```
Traceback (most recent call last):
  File "/home/richard/.virtualenvs/kolibri/bin/kolibri", line 11, in <module>
    load_entry_point('kolibri', 'console_scripts', 'kolibri')()
  File "/home/richard/.virtualenvs/kolibri/local/lib/python2.7/site-packages/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/home/richard/.virtualenvs/kolibri/local/lib/python2.7/site-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/home/richard/.virtualenvs/kolibri/local/lib/python2.7/site-packages/click/core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/richard/github/kolibri/kolibri/utils/cli.py", line 237, in invoke
    return super(KolibriDjangoCommand, self).invoke(ctx)
  File "/home/richard/.virtualenvs/kolibri/local/lib/python2.7/site-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/richard/.virtualenvs/kolibri/local/lib/python2.7/site-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/home/richard/github/kolibri/kolibri/utils/cli.py", line 610, in services
    server.services()
  File "/home/richard/github/kolibri/kolibri/utils/server.py", line 167, in services
    run_services(port=port)
  File "/home/richard/github/kolibri/kolibri/utils/server.py", line 121, in run_services
    register_zeroconf_service(port=port, id=instance.id[:4])
  File "/home/richard/github/kolibri/kolibri/core/discovery/utils/network/search.py", line 160, in register_zeroconf_service
    ZEROCONF_STATE["service"].register()
  File "/home/richard/github/kolibri/kolibri/core/discovery/utils/network/search.py", line 68, in register
    properties=self.data,
  File "/home/richard/.virtualenvs/kolibri/local/lib/python2.7/site-packages/zeroconf.py", line 1485, in __init__
    self._set_properties(properties)
  File "/home/richard/.virtualenvs/kolibri/local/lib/python2.7/site-packages/zeroconf.py", line 1516, in _set_properties
    result = b"".join((result, int2byte(len(item)), item))
ValueError: chr() arg not in range(256)
```

### Expected behavior
Devserver should run :)

### PR DESCRIPTION
**Pull request by micahscopes**
### Summary
This change fixes #6080. 

Zeroconf limits the amount of data that can be sent between peers.  The prototype peer discovery implementation used zeroconf to communicate information about available channels and facilities, but for Kolibri instances with long channel names, this caused Kolibri to crash on startup.

Going forward, zeroconf will only be used for discovery.  Right now, the only device info it sends is the version info.  Once peer instances of Kolibri discover each other they'll talk directly with the API (coming soon!)

### Reviewer guidance
Try starting Kolibri.  If it starts, we should be okay.

If you want to be really thorough, you can go and try starting an instance of Kolibri that has a channel with a very long name.  But I don't think this is necessary.  You can see in the code that zeroconf is no longer being passed channels or facilities.

### References
#6080 

----

### Contributor Checklist

PR process:

- [x] PR has the correct target branch and milestone
- [x] PR has 'needs review' or 'work-in-progress' label
- [x] If PR is ready for review, a reviewer has been added. (Don't use 'Assignees')
- [ ] If this is an important user-facing change, PR or related issue has a 'changelog' label
- [ ] If this includes an internal dependency change, a link to the diff is provided

Testing:

- [x] Contributor has fully tested the PR manually
- [ ] If there are any front-end changes, before/after screenshots are included
- [ ] Critical user journeys are covered by Gherkin stories
- [x] Critical and brittle code paths are covered by unit tests

### Reviewer Checklist

- Automated test coverage is satisfactory
- PR is fully functional
- PR has been tested for [accessibility regressions](http://kolibri-dev.readthedocs.io/en/develop/manual_testing.html#accessibility-a11y-testing)
- External dependency files were updated if necessary (`yarn` and `pip`)
- Documentation is updated
- Contributor is in AUTHORS.md

### CODE REVIEW

File: kolibri/plugins/device/assets/src/views/ManageContentPage/SelectNetworkAddressModal/SelectAddressForm.vue [hunk 1]
```diff
@@ -68,7 +68,7 @@
       </div>
     </template>
 
-    <template>
+    <template v-if="false">
```
Comment (indirectlylit) [inline kolibri/plugins/device/assets/src/views/ManageContentPage/SelectNetworkAddressModal/SelectAddressForm.vue:71]: this is useful for beta testing

**Review by indirectlylit — APPROVED** [review]
works for me!
