### PR TITLE
Fix #7386: Make reusable NewBadge component.

### LINKED ISSUE #7386: create a reusable 'New' badge component
### Observed behavior

as of https://github.com/learningequality/kolibri/pull/7368 the 'New' label is used in 3 places, with duplicated styling and strings:

> image

### Expected behavior

badge should be be a re-usable core component

### Context

0.14.0

### PR DESCRIPTION
**Pull request by YashJipkate**
### Summary

Extract code and logic of the new badge to a reusable component - NewBadge.

### Reviewer guidance

The element is used in three places:
- `NewChannelVersionBanner.vue`
- `WithSizeAndOptions.vue`
- `WithImportDetails.vue`

### References

Fixes #7386.

### Contributor Checklist

PR process:

- [x] PR has the correct target branch and milestone
- [ ] PR has 'needs review' or 'work-in-progress' label
- [ ] If PR is ready for review, a reviewer has been added. (Don't use 'Assignees')
- [ ] If this is an important user-facing change, PR or related issue has a 'changelog' label
- [ ] If this includes an internal dependency change, a link to the diff is provided

Testing:

- [x] Contributor has fully tested the PR manually
- [ ] If there are any front-end changes, before/after screenshots are included
- [ ] Critical user journeys are covered by Gherkin stories
- [ ] Critical and brittle code paths are covered by unit tests

### Reviewer Checklist

- Automated test coverage is satisfactory
- PR is fully functional
- PR has been tested for [accessibility regressions](http://kolibri-dev.readthedocs.io/en/develop/manual_testing.html#accessibility-a11y-testing)
- External dependency files were updated if necessary (`yarn` and `pip`)
- Documentation is updated
- Contributor is in AUTHORS.md

### CODE REVIEW

File: kolibri/plugins/device/assets/src/views/ManageContentPage/NewBadge.vue [hunk 1]
```diff
@@ -0,0 +1,40 @@
...
+        type: String,
+        required: true,
+      },
+    },
+  };
+
+</script>
+
+
+<style>
```
Comment (jonboiser) [inline kolibri/plugins/device/assets/src/views/ManageContentPage/NewBadge.vue]:
```suggestion
<style lang="scss" scoped>
```

Could you convert these to scoped styles? You will also see that the `NewBadge` component is still inheriting styles from the parent components. If you make them scoped, they lose the styling:

image

**Review by jonboiser — CHANGES_REQUESTED** [review]

File: kolibri/plugins/device/assets/src/views/ManageContentPage/NewBadge.vue (hunk 1 above)
Comment (YashJipkate) [reply kolibri/plugins/device/assets/src/views/ManageContentPage/NewBadge.vue]: Done!

Comment (jonboiser) [reply kolibri/plugins/device/assets/src/views/ManageContentPage/NewBadge.vue]: It's not enough to just change the scoping. You'll need to transfer the styles from the `new-badge` classes into the component, and also make sure that the styling is responsive. For example, in `WithSizeAndOptionslvue`, the `.new-label.panel-sm` styles would have been applied when the window is narrow before you extracted `NewBadge`. With this PR, that no longer happens.

Comment (jonboiser) [reply kolibri/plugins/device/assets/src/views/ManageContentPage/NewBadge.vue]: It might be good enough to just add another `new-label` class to the `NewBadge` component like this `<NewBadge class="new-label">`. Then both the styles from the parent and from within the component will be applied.

Comment (YashJipkate) [reply kolibri/plugins/device/assets/src/views/ManageContentPage/NewBadge.vue]: I am sorry but I'm not able to reproduce this. I am getting a perfectly aligned component (even without the scoping).
Screenshot from 2021-03-17 01-58-38

The `.new-label.panel-sm` style applies too.
Screenshot from 2021-03-17 01-58-50

Is there something I am missing?

File: kolibri/plugins/device/assets/src/views/ManageContentPage/NewBadge.vue [hunk 2]
```diff
@@ -0,0 +1,40 @@
...
+      },
+    },
+  };
+
+</script>
+
+
+<style lang="scss" scoped>
+
+  .new-label {
```
Comment (indirectlylit) [inline kolibri/plugins/device/assets/src/views/ManageContentPage/NewBadge.vue]: This `new-label` class definition has moved _inside_ the `NewBadge` component but has conflicting definitions that remain in parent components.

Classes used on the root node of a child component are a subtle case where vue's scoped styles mechanism breaks down, and it's possible for class definitions to collide with between child and parent component styles.

See https://vue-loader.vuejs.org/guide/scoped-css.html#child-component-root-elements

Therefore, it's important that the class name used inside the badge component is different than class names defined and applied from outside the badge.

**Review by indirectlylit — DISMISSED** [review]

File: kolibri/plugins/device/assets/src/views/ManageContentPage/NewBadge.vue (hunk 2 above)
Comment (YashJipkate) [reply kolibri/plugins/device/assets/src/views/ManageContentPage/NewBadge.vue]: Hi @indirectlylit!
Thanks for the information, it was new to me.
I have only put the common stylings - the 'badge specific' styles like padding and font size - in the `NewBadge` component, as should be the case. The stylings for its positioning relative to the external components are defined in the parent components. Hence the same class name won't create conflicts but compliment each other. 

But I agree with you, the parent and child shouldn't be this tightly coupled. I have changed the class name of the component. Please take a look.
Thanks!

Comment (indirectlylit) [reply kolibri/plugins/device/assets/src/views/ManageContentPage/NewBadge.vue]: thank you! that addresses my concern.

I haven't tested locally and will let @jonboiser or others give the final OK to merge

**Review by jonboiser — APPROVED** [review]
looks good, thanks!
