### PR TITLE
Make Import More Prominent.

### LINKED ISSUE #2725: import/export: make "Import" more prominent?
### Observed behavior

The most important button on the page gets a little lost with low contrast, sandwiched between two bits of metadata. 

image

### Expected behavior

It should be very clear what the primary action is

### User-facing consequences

The user may not immediately know what to do.

* Maybe make it primary and left-aligned, clearly associating it with the purple checkboxes?
* Can also consolidate all size metadata on the right, so they're also clearly associated with the information below

image

-----

cc @khangmach @jonboiser

### PR DESCRIPTION
**Pull request by DXCanas**
### Summary

Highlights the import button a little more, follows design in issue referenced.

Making import button primary.
Tweaking styles to reflect new mockups.
Removing comment from template.

### Reviewer guidance

image
Find test edge cases?

### References

resolves #2725 
----

### Contributor Checklist

- [x] PR has the correct target milestone
- [x] PR has 'needs review' or 'work-in-progress' label
- [x] If PR is ready for review, it has been assigned or requests review from someone and labeled as 'needs review'
- [x] PR has been fully tested manually
- [x] Screenshots of any front-end changes are in the PR description
- [x] PR does not introduce [accessibility regressions](http://kolibri.readthedocs.io/en/develop/dev/manual_testing.html#accessibility-a11y-testing)

#### NA
- [ ] You've added yourself to AUTHORS.rst if you're not there
- [ ] External dependencies files were updated (`yarn` and `pip`)
- [ ] Link to diff of internal dependency change is included
- [ ] CHANGELOG.rst is updated for high-level changes
- [ ] Documentation is updated

### Reviewer Checklist

- [ ] Automated test coverage is satisfactory
- [ ] PR has been fully tested manually

### CODE REVIEW

File: kolibri/plugins/management/assets/src/device_management/views/select-content-page/selected-resources-size.vue [hunk 1]
```diff
@@ -96,21 +99,25 @@
 
 <style lang="stylus" scoped>
 
+  .selected-resources-size
+    // using table to separate element by alignment while keeping them on the same line
+    // avoids magic numbers, keeps text lined up.
```
Comment (indirectlylit) [inline kolibri/plugins/management/assets/src/device_management/views/select-content-page/selected-resources-size.vue:104]: [pure grids](https://purecss.io/grids/) might also be a good solution for a case like this. I'd like to try to start using them a bit more

Comment (DXCanas) [reply kolibri/plugins/management/assets/src/device_management/views/select-content-page/selected-resources-size.vue:104]: I tried it at first, but they're still just floated divs, which meant the `inline` line wasn't consistent

Comment (indirectlylit) [reply kolibri/plugins/management/assets/src/device_management/views/select-content-page/selected-resources-size.vue:104]: interesting. would love to see a demo at some point so I can understand the limitations of pure grids
