### PR TITLE
Fix back button in LearnImmersiveLayout

### LINKED ISSUE #8512: Back button in LearnImmersiveLayout is Broken
The back button in the learn immersive layout page is not working as expected 

When the previous page is the library page, the back button returns to the topics browser page

From other pages, the back button either does nothing or results in an `Avoided redundant navigation to current location` error

### PR DESCRIPTION
**Pull request by marcellamaki**
## Summary
When leaving content renderer, back button should correctly revert to home, lesson, library, topic, or bookmarks page. 

## References
Fixes #8512

## Reviewer guidance
I tried to use `last` and `prevContext` to account for both the previous page name and the previous page params, rather than having many conditions trying to match up with page names, but I'm not sure if this is more confusing, since it's less explicit.

Any scenarios this doesn't account for?

----

## Testing checklist

- [ ] Contributor has fully tested the PR manually
- [ ] If there are any front-end changes, before/after screenshots are included
- [ ] Critical user journeys are covered by Gherkin stories
- [ ] Critical and brittle code paths are covered by unit tests

## PR process

- [ ] PR has the correct target branch and milestone
- [ ] PR has 'needs review' or 'work-in-progress' label
- [ ] If PR is ready for review, a reviewer has been added. (Don't use 'Assignees')
- [ ] If this is an important user-facing change, PR or related issue has a 'changelog' label
- [ ] If this includes an internal dependency change, a link to the diff is provided

## Reviewer checklist

- Automated test coverage is satisfactory
- PR is fully functional
- PR has been tested for [accessibility regressions](http://kolibri-dev.readthedocs.io/en/develop/manual_testing.html#accessibility-a11y-testing)
- External dependency files were updated if necessary (`yarn` and `pip`)
- Documentation is updated
- Contributor is in AUTHORS.md

### CODE REVIEW

File: kolibri/plugins/learn/assets/src/views/HybridLearningCardGrid.vue [hunk 1]
```diff
@@ -79,7 +79,7 @@
       :isLeaf="content.is_leaf"
       :progress="content.progress_fraction || 0"
       :numCoachContents="content.num_coach_contents"
-      :link="genContentLink(content.id, content.is_leaf)"
+      :link="genContentLink(content.id, content.is_leaf, backRoute)"
```
Comment (rtibbles) [inline kolibri/plugins/learn/assets/src/views/HybridLearningCardGrid.vue]: Why is the `genContentLink` above passed the context, but this one isn't?

File: kolibri/plugins/learn/assets/src/utils/genContentLink.js [hunk 2]
```diff
@@ -1,8 +1,10 @@
 import { PageNames } from '../constants';
 
-export default function genContentLink(id, isLeaf) {
+// previous context allows to pass in ids or params from the last route
+export default function genContentLink(id, isLeaf, last, prevContext) {
   return {
     name: isLeaf ? PageNames.TOPICS_CONTENT : PageNames.TOPICS_TOPIC,
     params: { id },
+    query: { last: last, prevContext },
```
Comment (rtibbles) [inline kolibri/plugins/learn/assets/src/utils/genContentLink.js:8]: How does the `prevContext` object get encoded into the URL? I assume it's fine?

**Review by rtibbles — COMMENTED** [review]
Haven't tested, and while I share your aesthetic disregard for the lack of specificity, this seems like the simplest way for now.

One argument for making it more explicit would be for resolving this: https://github.com/learningequality/kolibri/issues/8577 so we have a canonical source of truth on the content page about the context it was loaded from.

File: kolibri/plugins/learn/assets/src/utils/genContentLink.js (hunk 2 above)
Comment (marcellamaki) [reply kolibri/plugins/learn/assets/src/utils/genContentLink.js:8]: That's an oversight -- I've now added encoding

File: kolibri/plugins/learn/assets/src/views/HybridLearningCardGrid.vue (hunk 1 above)
Comment (marcellamaki) [reply kolibri/plugins/learn/assets/src/views/HybridLearningCardGrid.vue]: It's an optional param. i.e. library page does not need it, but since the lessons cards _do_ since their route requires a specific classid and lessonid, it is passed there. Maybe I can name it something clearer...

Comment (rtibbles) [reply kolibri/plugins/learn/assets/src/views/HybridLearningCardGrid.vue]: I think would be good to just always pass it for consistency - means that we won't get bitten in the behind in future when we decide we need to pass context from the library page (like the search term that someone arrived at the content from) and we can't understand why the context is missing.

**Review by rtibbles — APPROVED** [review]
