### PR TITLE
Disable hashi on iOS

### LINKED ISSUE #6624: African Storybook on the iPad2s does not work anymore
### Observed behavior
When using kolibri in iPad2s (limited to iOS 9.3.5)
The maximize button no longer works, nor does the page turn feature, the back arrow to on the page to return to the folders does not work and the page reloads following an error with Safari reporting “A problem occurred with this webpage so it was reloaded.” Following the reload, there is not improvement in behavior of the page.

The web page crashes after some time and is non-responsive otherwise (only once an ASb content is loaded)
It works fine on later versions of iOS. Also, I discovered one strange thing. I tried it out on an iPad2 that has only iOS 7.7 installed. ASb worked except the  cover page of the book does not load completely. However every other page loads find and the controls work fine also

### Expected behavior
ASb worked in previous versions of Kolibri in this devices using this IOS  version

### User-facing consequences
Using ASb is not possible

### Errors and logs
Here’s the errors in Web Inspector:

```
[Error] Failed to load resource: the server responded with a status of 404 (Not Found) (2_css, line 0)
[Error] Failed to load resource: the server responded with a status of 404 (Not Found) (3_css, line 0)
[Error] Failed to load resource: the server responded with a status of 404 (Not Found) (right.png, line 0)
[Error] Failed to load resource: the server responded with a status of 404 (Not Found) (left.png, line 0)
[Error] Failed to load resource: the server responded with a status of 404 (Not Found) (NotoSans.ttf, line 0)
[Error] Failed to load resource: the server responded with a status of 404 (Not Found) (NotoSansEthiopic-Regular.ttf, line 0)
[Error] Failed to load resource: the server responded with a status of 404 (Not Found) (NotoSansEthiopic-Bold.ttf, line 0)

```

### Context
Reported by Chris Jackson
Using kolibri 0.13.0 & 0.13.1 on a Raspberry Pi server
Clients are the iPad2s (limited to iOS 9.3.5)

### PR DESCRIPTION
**Pull request by rtibbles**
### Summary
A previous bug fix (#6268) for Hashi had done a small refactor on how scripts are got from the page and loaded (in order to accommodate parsing the body and the head separately, so that HTML5 zips that rely on the body not being loaded as some sort of signal don't break).

Unfortunately, it was relying on the experimental `children` property of `DocumentFragment` as opposed to the canonical `childNodes` property. This caused a breakage in browsers that did not implement this experimental property.

### Reviewer guidance
Load up browserstack, choose iOS 8, and then use African Storybook or some other HTML5 content.

### References
Fixes #6624

----

### Contributor Checklist

PR process:

- [x] PR has the correct target branch and milestone
- [x] PR has 'needs review' or 'work-in-progress' label
- [x] If PR is ready for review, a reviewer has been added. (Don't use 'Assignees')
- [ ] If this is an important user-facing change, PR or related issue has a 'changelog' label
- [ ] If this includes an internal dependency change, a link to the diff is provided

Testing:

- [x] Contributor has fully tested the PR manually
- [ ] If there are any front-end changes, before/after screenshots are included
- [ ] Critical user journeys are covered by Gherkin stories
- [ ] Critical and brittle code paths are covered by unit tests

### Reviewer Checklist

- Automated test coverage is satisfactory
- PR is fully functional
- PR has been tested for [accessibility regressions](http://kolibri-dev.readthedocs.io/en/develop/manual_testing.html#accessibility-a11y-testing)
- External dependency files were updated if necessary (`yarn` and `pip`)
- Documentation is updated
- Contributor is in AUTHORS.md

### CODE REVIEW

**Comment by benjaoming** [comment]
Test results on iPhone 6S with iOS 9:

* Brings back left/right arrow buttons on African Storybook
* Safari 9 still crashes when viewing books from African Storybook the same way as reported in #6624 
* No regressions found: Firefox still show correctly shows African Storybook w/ arrows, scrollbars etc.

**Comment by rtibbles** [comment]
Damn, I also got these errors, but assumed it was local - every time it reloaded for me, it brought back the old erroring version.

**Comment by benjaoming** [comment]
We've tested this on African Storybook and may have to skip hashi on all iOS versions.

* iOS 8 now works because it skips hashi :tada: 
* iOS 9 still has issues of crashing and reloading the page
* Errors on iOS 10, 12 and 13 are similar: Arrow left and right don't work, changing pages works otherwise
* iOS 11 is unique and has new `TypeError: undefined is not an object (evaluating '$$('.readerSwiper')[0].swiper.slideTo`, cannot change pages but doesn't crash as iOS 9.

**Comment by benjaoming** [comment]
@rtibbles based on the above testing, if you can push a change that has hashi blocked on all versions of iOS/Safari, I think that's the way forward?

The right/left arrow buttons work on Safari for desktop MacOS, so it should be a combination of Safari and iOS.

**Comment by benjaoming** [comment]
It works!

The left/right buttons might have worked all the time: But not exactly as expected. It seems (I haven't tested on all systems) that for various Webkit-based iOS browsers (perhaps all), both with and without Hashi enabled, the click event area doesn't trigger exactly on the area of the buttons but somewhere to the left of that area.

File: kolibri/plugins/html5_viewer/assets/src/views/Html5AppRendererIndex.vue [hunk 1]
```diff
@@ -57,7 +61,10 @@
         return nameSpace;
       },
       rooturl() {
-        return this.defaultFile.storage_url;
+        const isOS = iOSTest.test(navigator.userAgent);
+        const iOSorIE11 = isOS || IE11Test.test(navigator.userAgent);
```
Comment (indirectlylit) [inline kolibri/plugins/html5_viewer/assets/src/views/Html5AppRendererIndex.vue]:
```suggestion
        const iOS = iOSTest.test(navigator.userAgent);
        const iOSorIE11 = iOS || IE11Test.test(navigator.userAgent);
```

Comment (benjaoming) [reply kolibri/plugins/html5_viewer/assets/src/views/Html5AppRendererIndex.vue]: Haha, that was fun, "this constant indicates if the user has an operating system" :)

**Comment by indirectlylit** [comment]
@benjaoming is this ready to merge or were there changes requested?

**Review by benjaoming — APPROVED** [review]
Tested and still works after the change!

**Comment by indirectlylit** [comment]
great, thank you!
