### PR TITLE
BUM SidePanel: Implement Assign (coaches) to classes functionality

### LINKED ISSUE #13407: Bulk User Management SidePanel: Assign (coaches) to classes
❌ **This issue is not open for contribution. Visit <a href="https://learningequality.org/contributing-to-our-open-code-base/" target="_blank">Contributing guidelines</a>** to learn about the contributing process and how to find suitable issues.

## Overview

[Figma](https://www.figma.com/design/2aE0zEXmyysxMZ6qO0ufh8/Bulk-User-Management?node-id=397-8515&t=YdB4uWeMAd6PeI85-0)

This will permit the user to assign coaches to the classes they'll coach in bulk. Only non-Learners (ie, admin, super admin, coach) can be assigned to classes as a "Coach". 

Image

#### Filterable Classes table w/ selection checkboxes

You'll have the classes & selected users available via props.

The whole list will start with each of the classes' checkboxes **unchecked.** From there, the admin can modify their selection and click the "Enroll" button to apply the changes.

**Note** that although some of the selected users may already be assigned to the classes listed, this workflow does not _toggle_ assignment, but simply selects classes into which the selected coaches will be assigned.

- [ ] Handle events from the component introduced by #13408 - track checked items as well
- [ ] "Enroll" button is disabled so long as all items are unselected (because there is only a change to apply if a class is selected)
- [ ] The user should see a loading spinner while the API request is made
- [ ] Close the side panel once the request has succeeded
- [ ] Handle failed API requests gracefully with a notice at the top of the side panel that there was an error and to try again.
- [ ] When the admin **has not** changed their selection, **Cancel** button simply closes the side panel _without_ confirmation 

#### Undoing / cancelling

Image

- [ ] Upon Assigning the learners, the side panel will close and the user will be presented with a KModal message allowing them to undo the decision
- [ ] When the admin has changed their selection, then the **Cancel** button should present a user with an "Are you sure?" KModal confirmation noting that their changes will be lost

#### Assignment

A user being assigned as a coach for a class is modeled in Kolibri using the [`Role`](https://github.com/learningequality/kolibri/blob/915e90fc5a38a6c262694e74c36072e3eb872f5a/kolibri/core/auth/models.py#L1343) class. This model relates the higher-level idea of a "Collection" (ie, a class).

A membership is an relational table between FacilityUsers and Collections - so if you assign a coach to a class, you'll be creating a new Membership record in the database between that learner and the selected class.

This was previously done w/ [Vuex actions](https://github.com/learningequality/kolibri/blob/develop/kolibri/plugins/facility/assets/src/modules/classAssignMembers/actions.js) which you can use as inspiration as you assign coaches to the class (although, be mindful of the `user_ids` param for bulk actions, noted below).

- [ ] No regressions or errors when mass-creating memberships between users and classes
- [ ] Leverage the already-existing "bulk operation" functionality present thanks to how the RoleViewSet mixes in the BulkCreateMixin class, allowing us to send an array. You can pass `{ collection: <class_id>, user_ids: [<id1>,<id2>,...] }` using the RoleResource.

### PR DESCRIPTION
**Pull request by ozer550**
## Summary
This pull request updates the AssignCoachesSidePanel component to carry out the bulk action to assign coaches to one or more classes, with intelligent filtering to handle mixed user selections. 

 **AssignCoaches in Bulk:** Uses RoleResource to bulk assign or un-assign (undo) coaches to classes with proper role management and duplicate prevention.

**User Filtering:** The component now automatically filters out learners from the assignment process, only assigning coaches, admins, and superusers to classes. Users can now select a mix of coaches/admins and learners, with the system automatically handling the filtering and showing appropriate warnings.

**Fixed Button Assign Logic**: The "Assign coach" button on the main users page is now enabled when at least one eligible user (coach/admin/superuser) is selected, rather than requiring all selected users to be eligible.

**Discard functionality:** Added a confirmation modal that appears when users try to close the side panel with unsaved class selections, preventing accidental loss of work.

**Undo System**: After successful assignment, a confirmation modal allows users to undo the coach assignments, with proper API calls to remove the created roles. changes also properly handle reassigning coaches who are already assigned to classes, preventing duplicate assignments and ensuring clean role management.

**_Assigning coaches using SidePanel:_**

https://github.com/user-attachments/assets/3a6e41dc-96ad-482d-95ca-25d360f1c04e

**_Assigning coaches and undoing:_**

https://github.com/user-attachments/assets/08f6b047-e691-47ff-b25d-4399cde2323a

## References
 closes #13407 

## Reviewer guidance
- On the Facility > Users page, select one or more users and click the assign coach icon button.
- Once the side panel opens, confirm that the correct warnings apply based on if the selected users are coaches, learners, and not assigned to any classes.
- Select a class to assign the coaches to and undo the assignment to confirm that the functionality works as intended. Note: Users that are already assigned as coaches to the selected classes will not be affected by selecting assign or undo.

### CODE REVIEW

File: kolibri/plugins/facility/assets/src/views/users/sidePanels/AssignCoachesSidePanel.vue [hunk 1]
```diff
@@ -1,40 +1,430 @@
...
+            :options="formattedClasses"
+            aria-labelledby="classes-heading"
+            :selectAllLabel="assignToAllClasses$()"
+            :searchLabel="searchForAClass$()"
+          />
+
+          <!-- Footer Buttons -->
+          <div class="footer-buttons">
+            <KButton
+              appearance="secondary-button"
```
Comment (nucleogenesis) [inline kolibri/plugins/facility/assets/src/views/users/sidePanels/AssignCoachesSidePanel.vue]: [This should be](https://design-system.learningequality.org/kbutton#prop:appearance) `flat-button` and to determine primariness-vs-secondariness you can use the `primary` prop set as false.

Comment (LianaHarris360) [inline kolibri/plugins/facility/assets/src/views/users/sidePanels/AssignCoachesSidePanel.vue]: You can omit this `appearance` prop, and if primary is not passed, the `KButton` will automatically be a secondary button. The only acceptable strings that can be passed to `appearance` are 'raised-button', 'flat-button', or 'basic-link'

File: kolibri/plugins/facility/assets/src/views/users/sidePanels/AssignCoachesSidePanel.vue [hunk 2]
```diff
@@ -1,40 +1,430 @@
...
+          <div class="info-message">
+            <KIcon
+              icon="info"
+              color="orange"
+              class="sidepanel-icon"
+            />
+            {{ usersNotInClassNotAffected$() }}
+          </div>
+          <hr class="divider" >
+          <h2>{{ assignToAClassLabel$() }}</h2>
```
Comment (LianaHarris360) [inline kolibri/plugins/facility/assets/src/views/users/sidePanels/AssignCoachesSidePanel.vue]: This string should say 'Select classes' rather than 'Assign to a class'.

Screenshot 2025-08-12 at 1 38 21 PM

File: kolibri/plugins/facility/assets/src/views/users/sidePanels/AssignCoachesSidePanel.vue [hunk 3]
```diff
@@ -1,40 +1,430 @@
...
+          </div>
+          <div class="info-message">
+            <KIcon
+              icon="info"
+              color="orange"
+              class="sidepanel-icon"
+            />
+            {{ usersNotInClassNotAffected$() }}
+          </div>
+          <hr class="divider" >
```
Comment (LianaHarris360) [inline kolibri/plugins/facility/assets/src/views/users/sidePanels/AssignCoachesSidePanel.vue]: I'm not sure if a horizontal divider was included in the original Figma designs, but the updated designs do not include this, it can be removed.

File: kolibri/plugins/facility/assets/src/views/users/sidePanels/AssignCoachesSidePanel.vue [hunk 4]
```diff
@@ -1,40 +1,430 @@
...
+      </span>
+    </KModal>
+    <SidePanelModal
+      v-else
+      alignment="right"
+      sidePanelWidth="700px"
+      @closePanel="closeSidePanel(false)"
+    >
+      <template #header>
+        <h1>{{ assignCoach$() }}</h1>
```
Comment (LianaHarris360) [inline kolibri/plugins/facility/assets/src/views/users/sidePanels/AssignCoachesSidePanel.vue]: In the updated Figma designs, the top heading string says 'Assign [N] users' instead of 'Assign coach'. 

Screenshot 2025-08-12 at 1 38 21 PM

**Review by LianaHarris360 — DISMISSED** [review]
I noted a few changes that need to be made on the frontend. In the newest Figma designs, the top the warning messages have been updated:
- [ ] Only includes the [infoOutline](https://design-system.learningequality.org/icons/#token-infoOutline:~:text=info-,infoOutline,-language) `KIcon`
- [ ] Should contain the two messages:
       - '[N] users are learners and won’t be assigned' (only if learners have been selected)
       - 'Users already in selected classes stay unchanged'
- [ ]  Should have the gray (`palette.grey.v_100`) background

**Current implementation:**
Screenshot 2025-08-122


**Figma designs:**
Screenshot 2025-08-12

File: kolibri/core/auth/serializers.py [hunk 5]
```diff
@@ -27,10 +27,32 @@
...
+    def create(self, validated_data):
+        ModelClass = self.child.Meta.model
+        created_objects = []
+
+        for model_data in validated_data:
+            try:
+                obj, created = ModelClass.objects.get_or_create(**model_data)
+                if created:
+                    created_objects.append(obj)
+            except Exception as e:
```
Comment (nucleogenesis) [inline kolibri/core/auth/serializers.py]: A few things to note here.

1. It is a Python anti-pattern to except the `Exception` class - in part because it will often except on errors you never expected it to. [Some well-aged Stack Overflow discussion](https://stackoverflow.com/questions/14797375/should-i-always-specify-an-exception-type-in-except-statements) on the topic.

I don't think we really need to do a `try/catch` here because the only data you're getting here is already validated. If there was something wrong w/ the data it ought to have failed in the `RoleSerializer#validate` method below.

2. It was a bit confusing to me seeing the generic class variable `ModelClass` because I couldn't figure out where/when/why `ModelClass` would be anything other than the `Role` class here. 

3. You could also avoid looping over each item by using the [Django `Queryset#bulk_create`](https://docs.djangoproject.com/en/3.2/ref/models/querysets/#bulk-create) method w/ the `ignore_conflicts=True` parameter - this should basically be a bulk version of `get_or_create` because it'll ignore `IntegrityErrors` when trying to create something that exists already.

**Review by nucleogenesis — DISMISSED** [review]
I added some notes about a wonky "Cancel" button and some suggestions for the RoleListSerializer. I tested manually and things worked well though.

File: kolibri/core/auth/serializers.py (hunk 5 above)
Comment (ozer550) [reply kolibri/core/auth/serializers.py]: For 3: I initially started with implementing it using bulk_create. I was not successful in getting the desired results, it bypasses model/serializer validation, which leads to unique constraints still surfacing awkwardly. Even with ignore_conflicts, we hit unique key constraint edge cases and couldn’t distinguish conflicts from real errors cleanly..

Comment (nucleogenesis) [reply kolibri/core/auth/serializers.py]: Thanks - if we can get a sense of what the errors are we can investigate further. Optimizing this won't be a blocker for merge.

File: kolibri/core/auth/serializers.py [hunk 6]
```diff
@@ -27,10 +27,27 @@
 logger = logging.getLogger(__name__)
 
 
+class RoleListSerializer(serializers.ListSerializer):
+    def create(self, validated_data):
+        created_objects = []
+
+        for model_data in validated_data:
+            obj, created = Role.objects.get_or_create(**model_data)
```
Comment (nucleogenesis) [inline kolibri/core/auth/serializers.py:35]: Noting for posterity here that the `bulk_create` method did not work out here because among [the caveats](https://docs.djangoproject.com/en/3.2/ref/models/querysets/#bulk-create) for that method includes that it doesn't work with many-to-many relationships, so the IntegrityErrors persisted despite using the `ignore_conflicts` kwarg. (cc @rtibbles)

Comment (rtibbles) [reply kolibri/core/auth/serializers.py:35]: But, the Role object only has direct ForeignKey relationships, not ManyToMany fields? So I'm not sure why that caveat would apply here: https://github.com/learningequality/kolibri/blob/develop/kolibri/core/auth/models.py#L1343

Comment (nucleogenesis) [reply kolibri/core/auth/serializers.py:35]: I trusted my intuition and didn't consult the model :man_facepalming:

I wonder if it's because `save()` isn't called then (or one of the other caveats). This part of the [`save()`](https://github.com/learningequality/kolibri/blob/d0176a6d5bada473ebe48850b795b74e61d65ae9/kolibri/core/auth/models.py#L1418-L1420) method in particular seems like it'd avoid the error @ozer550 was getting:

```bash
[python-devserver]     return Database.Cursor.execute(self, query, params)
[python-devserver] django.db.utils.IntegrityError: UNIQUE constraint failed: kolibriauth_role.user_id, kolibriauth_role.collection_id, kolibriauth_role.kind
```

Curious what you think @rtibbles - if the save() method not being called is the culprit, seems we're stuck iterating rather than batching the creates here?

**Comment by pcenov** [comment]
Hi @ozer550, as always I'm listing here all of my testing observations for consideration, anything out of scope for this PR can be filed as a separate issue:

1. Assigning a coach from the 'New users' table is not working at all:

user field is required

2. There are several unhandled edge cases, such as assigning a coach to a deleted class, assigning a deleted user to a class and assigning 0 selected users by directly going to http://127.0.0.1:8080/en/facility/#/users/assign-coaches


https://github.com/user-attachments/assets/c1caca37-af88-400f-ba6c-1ca5434acdbb


https://github.com/user-attachments/assets/51339b02-ae13-47eb-ba5b-6bb9898b7296


https://github.com/user-attachments/assets/f49bd821-f514-4e26-aa57-fe9a7a6a4886

3. I'm not seeing the "Discard changes?" message when accidentally clicking outside of the side panel or attempting to close it after having already selected classes.
4. If I select several users and assign them then after dismissing the confirmation modal I am back at the Users table and all of the selected users remain selected. Typically after completion of the action the table should be displayed in its default state.

https://github.com/user-attachments/assets/4e3f2257-e600-4927-bdab-441c9a6b9170

5. I'm not sure what are the final approved texts for the notice section and the modal so posting a screenshot of what I am observing. In my opinion the N users value should be only for the admins/coaches that can actually be assigned, and not for the total of selected users. Then in the notice/info section it seems that mentioning that N learner's can't be assigned as coaches is sufficient ("They won't be added" is just repeating the same info and "Users already in selected classes will not be affected" seems unnecessary as I am not deleting users so I'm not scared that users will be ''affected".
The modal almost repeats the same text twice, so both should be updated.

texts

6. Same goes for the snackbar messages which currently are "Selected coaches have been assigned" and "Assign action has been undone" - both should be updated.

7. The classes in the "Select classes" table are not sorted.

sorting

8. I have previously mentioned somewhere that the main button and course of action at the success modal should not be UNDO as we are intentionally assigning users.

undo

File: kolibri/core/auth/serializers.py (hunk 6 above)
Comment (rtibbles) [reply kolibri/core/auth/serializers.py:35]: I agree that this may be something specific for morango models. My guess is that the id is not being set properly during bulk create. I have no objections with us not doing the bulk create at this juncture.

It's an optimization, and we can dig in more if it seems necessary during testing - as long as we encourage Peter to try with large numbers of users!

Comment (nucleogenesis) [reply kolibri/core/auth/serializers.py:35]: Thanks @rtibbles - [for when we come back to it](https://github.com/learningequality/kolibri/issues/13657)

**Comment by nucleogenesis** [comment]
@pcenov -- @ozer550 has pushed changes addressing 1, 3, 4, and 7.

2, 5, 6 and 8 are being tracked elsewhere - once this is rebased it'll be ready for re-review

**Comment by ozer550** [comment]
> @pcenov -- @ozer550 has pushed changes addressing 1, 3, 4, and 7.
> 
> 2, 5, 6 and 8 are being tracked elsewhere - once this is rebased it'll be ready for re-review

Done! should be ready for QA @pcenov .

**Review by pcenov — APPROVED** [review]
Thanks @ozer550 - I confirm that 1, 3, 4, and 7 are fixed now, and since the other comments will be addressed separately this PR is good to go!

File: kolibri/plugins/facility/assets/src/views/users/sidePanels/AssignCoachesSidePanel.vue [hunk 7]
```diff
@@ -1,35 +1,347 @@
...
+        return [...props.classes]
+          .sort((a, b) => a.name.localeCompare(b.name))
+          .map(({ id, name }) => ({ id, label: name }));
+      });
+
+      const selectedUsersCount = computed(() => props.selectedUsers.size);
+
+      const hasSelectedClasses = computed(() => selectedClasses.value.length > 0);
+
+      const getSelectedClassObjects = computed(() =>
```
Comment (AlexVelezLl) [inline kolibri/plugins/facility/assets/src/views/users/sidePanels/AssignCoachesSidePanel.vue]: We usually don't want to frame the name of a computed property as a verb, since it gives the sense this is a function, when its not. Other thing that I noticed is that this property is just used on the `assignCoachesToClasses` method, and if a calculation is just going to be used once in the component workflow, then its usually not a good idea to create a computed property, since this object is going to be recalculated each time a user select a class, but we won't need that value until the user clicks on the save button, its not a big overhead at all, but its good to know!

File: kolibri/plugins/facility/assets/src/views/users/sidePanels/AssignCoachesSidePanel.vue [hunk 8]
```diff
@@ -1,35 +1,347 @@
...
+        props.classes.filter(cls => selectedClasses.value.includes(cls.id)),
+      );
+
+      // Filter eligible users (coaches, admins, superusers)
+      const eligibleUsers = computed(() => {
+        return facilityUsers.value.filter(
+          user =>
+            props.selectedUsers.has(user.id) &&
```
Comment (AlexVelezLl) [inline kolibri/plugins/facility/assets/src/views/users/sidePanels/AssignCoachesSidePanel.vue]: Now that `facilityUsers` are the selected users loaded from the api, this condition is no longer necessary, removing it will make that this condition is more readable.

File: kolibri/plugins/facility/assets/src/views/users/sidePanels/AssignCoachesSidePanel.vue [hunk 9]
```diff
@@ -1,35 +1,347 @@
...
+              user.kind === UserKinds.ADMIN ||
+              user.kind === UserKinds.SUPERUSER ||
+              user.is_superuser),
+        );
+      });
+
+      // Filter ineligible users (learners)
+      const ineligibleUsers = computed(() => {
+        return facilityUsers.value.filter(
+          user => props.selectedUsers.has(user.id) && user.kind === UserKinds.LEARNER,
```
Comment (AlexVelezLl) [inline kolibri/plugins/facility/assets/src/views/users/sidePanels/AssignCoachesSidePanel.vue]: idem. we dont need the check `props.selectedUsers.has(user.id)`

File: kolibri/plugins/facility/assets/src/views/users/sidePanels/AssignCoachesSidePanel.vue [hunk 10]
```diff
@@ -1,35 +1,347 @@
...
+
+      async function assignCoachesToClasses() {
+        const selectedClasses = getSelectedClassObjects.value;
+        const eligibleUserIds = eligibleUsers.value.map(user => user.id);
+        if (eligibleUserIds.length === 0) {
+          return;
+        }
+
+        for (const classObj of selectedClasses) {
+          const newRoles = await RoleResource.saveCollection({
```
Comment (AlexVelezLl) [inline kolibri/plugins/facility/assets/src/views/users/sidePanels/AssignCoachesSidePanel.vue]: (Important) We are making too many api requests with this for. We can bulk save data from multiple users and multiple classes in the same request, we don't need to make a single request for each class. Look at [this](https://github.com/ozer550/kolibri/blob/9ff8e08c51a5caff5389be762025b4d871aab542/kolibri/plugins/facility/assets/src/views/users/sidePanels/UserCreate/index.vue#L356) for example, where we use this method to save multiple classes for the same user.

File: kolibri/plugins/facility/assets/src/views/users/sidePanels/AssignCoachesSidePanel.vue [hunk 11]
```diff
@@ -1,35 +1,347 @@
...
+        instance.proxy.$router.back();
+      }
+
+      async function handleUndoAssignments() {
+        isLoading.value = true;
+        try {
+          if (createdRoles.value.length > 0) {
+            for (const role of createdRoles.value) {
+              if (role.id) {
+                await RoleResource.deleteModel({ id: role.id });
```
Comment (AlexVelezLl) [inline kolibri/plugins/facility/assets/src/views/users/sidePanels/AssignCoachesSidePanel.vue]: (Mega important) Idem, we are making too many api request, we can bulk delete these roles using the `by_ids` filter. (Here its even more important since we are making a request for evey single combination of classes/users):

```javascript
RoleResource.deleteCollection({ by_ids })
```

File: kolibri/plugins/facility/assets/src/views/users/NewUsersPage.vue [hunk 12]
```diff
@@ -218,6 +236,39 @@
...
+    computed: {
+      hasSelectedUsers() {
+        return this.selectedUsers && this.selectedUsers.size > 0;
+      },
+      listContainsLoggedInUser() {
+        return this.selectedUsers.has(this.currentUserId);
+      },
+      canAssignCoaches() {
+        if (!this.hasSelectedUsers) return false;
+        return this.facilityUsers
```
Comment (AlexVelezLl) [inline kolibri/plugins/facility/assets/src/views/users/NewUsersPage.vue:265]: @nucleogenesis Just a note that we will need to solve this in a more robust way, since this array of `facilityUsers` only contains the users of the current page, so we can skip the validations if a selected user is in another page. Also, it'd be great if we can share these conditions for both pages, the new users and the users root:

https://github.com/user-attachments/assets/2966f777-d6fb-4f94-bc2a-94af6ccfde7f

File: packages/kolibri-common/strings/bulkUserManagementStrings.js [hunk 13]
```diff
@@ -292,6 +308,10 @@ export const bulkUserManagementStrings = createTranslator('BulkUserManagementStr
     message: 'Assign to a class',
     context: 'Label for the classes input field in the create user modal',
   },
+  selectClassesLabel: {
+    message: 'Select classes',
```
Comment (AlexVelezLl) [inline packages/kolibri-common/strings/bulkUserManagementStrings.js]: Just noting that we have other select classes translation https://github.com/ozer550/kolibri/blob/9ff8e08c51a5caff5389be762025b4d871aab542/packages/kolibri-common/strings/bulkUserManagementStrings.js#L65

File: kolibri/plugins/facility/assets/src/views/users/sidePanels/AssignCoachesSidePanel.vue [hunk 14]
```diff
@@ -1,35 +1,347 @@
...
+          })
+        }}
+      </span>
+    </KModal>
+    <SidePanelModal
+      v-else
+      alignment="right"
+      sidePanelWidth="700px"
+      :addBottomBorder="false"
+      @closePanel="closeSidePanel(selectedClasses.length > 0)"
```
Comment (AlexVelezLl) [inline kolibri/plugins/facility/assets/src/views/users/sidePanels/AssignCoachesSidePanel.vue]: Just noting that here we should use the [useGoBack](https://github.com/lianaharris360/kolibri/blob/ccda0041b98f14fb0a7dd2f513b21252226ad48e/kolibri/plugins/facility/assets/src/views/users/sidePanels/FilterUsersSidePanel/index.vue#L131) composable to prevent the 4th point that Peter mentioned in this PR https://github.com/learningequality/kolibri/pull/13608#issuecomment-3167608877

File: kolibri/plugins/facility/assets/src/views/users/sidePanels/AssignCoachesSidePanel.vue [hunk 15]
```diff
@@ -1,35 +1,347 @@
...
+              :text="assignAction$()"
+              :disabled="!hasSelectedClasses || isLoading"
+              @click="handleAssign"
+            />
+          </KButtonGroup>
+        </div>
+      </template>
+
+      <KModal
+        v-if="showCloseConfirmationModal"
```
Comment (AlexVelezLl) [inline kolibri/plugins/facility/assets/src/views/users/sidePanels/AssignCoachesSidePanel.vue]: We have this [CloseConfirmationGuard](https://github.com/lianaharris360/kolibri/blob/ccda0041b98f14fb0a7dd2f513b21252226ad48e/kolibri/plugins/facility/assets/src/views/users/common/CloseConfirmationGuard.vue#L28) component to abstract the confirmation modal logic.

[Here](https://github.com/lianaharris360/kolibri/blob/ccda0041b98f14fb0a7dd2f513b21252226ad48e/kolibri/plugins/facility/assets/src/views/users/sidePanels/UserCreate/index.vue#L109) is an example of how we can use it. (Just noticed the beforeRouteLeave link that needs to be done is not well docummented in the component 😅).

**Review by AlexVelezLl — COMMENTED** [review]
Just one important note: We usually should try not to make api requests inside fors as much as possible. The rest of the comments are non blocking :), in general there are some things we can standarize across these side panels, but it's probably a better idea to handle it separately.

**Review by AlexVelezLl — APPROVED** [review]
Code changes look good to me!

**Comment by ozer550** [comment]
Hi @pcenov! Due to some latest changes structurally and logically this would require re-QA.

**Comment by pcenov** [comment]
Thanks @ozer550 - no new issues observed while testing again, LGTM!
