### PR TITLE
Make points completion popover disappear after 5 seconds.

### LINKED ISSUE #1417: Exercise points snackbar doesn't disappear
## Summary

Upon completing any kind of exercise or watching a video, I am awarded points but the snackbar indicator that appears doesn't disappear after waiting a certain amount of time, as desired.

## How to reproduce

1. Navigate to Learn
2. Complete any exercise
3. Watch for indicated problem

## Screenshots
https://cloud.githubusercontent.com/assets/25045166/25634969/5fd95d84-2f31-11e7-9755-e50a3219584e.png

### PR DESCRIPTION
**Pull request by rtibbles**
## Summary

Fixes #1417

Having issues doing a screen record atm - @khangmach has witnessed the desired behaviour, however.

### CODE REVIEW

File: kolibri/plugins/learn/assets/src/views/content-points/index.vue [hunk 1]
```diff
@@ -81,6 +84,11 @@
       closePopover() {
         this.internalPopoverShown = false;
       },
+      popOverSetTime(newVal, oldVal) {
+        if (newVal === true && oldVal !== true) {
+          setTimeout(this.closePopover.bind(this), 5000);
```
Comment (indirectlylit) [inline kolibri/plugins/learn/assets/src/views/content-points/index.vue]: I'm going to recommend removing `.bind`.

As far as I can tell it's not necessary because vue methods are already bound to the vm context
