### PR TITLE
Device provisioning error handling

### LINKED ISSUE #10598: Unhandled error from the device provision endpoint
## Observed behavior
[Reported by @rtibbles in the alpha 13 bug bash ](https://www.notion.so/learningequality/Unhandled-error-from-the-device-provision-endpoint-6e4b0ac806304f45a09d120f12438b83?pvs=4)

> Seems to be happening because I had some saved state, and it was attempting to immediately do the provisioning at start.

## Errors and logs

```
ERROR 2023-04-27 09:37:35,307 django.request Internal Server Error: /api/device/deviceprovision/
Traceback (most recent call last):
  File "/home/richard/.pex/install/kolibri-0.16.0a13-py2.py3-none-any.whl.5fde7692abbe85a2d3272cba207b2e678d7f19c6/kolibri-0.16.0a13-py2.py3-none-any.whl/kolibri/dist/django/core/handlers/exception.py", line 41, in inner
    response = get_response(request)
  File "/home/richard/.pex/install/kolibri-0.16.0a13-py2.py3-none-any.whl.5fde7692abbe85a2d3272cba207b2e678d7f19c6/kolibri-0.16.0a13-py2.py3-none-any.whl/kolibri/dist/django/core/handlers/base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/home/richard/.pex/install/kolibri-0.16.0a13-py2.py3-none-any.whl.5fde7692abbe85a2d3272cba207b2e678d7f19c6/kolibri-0.16.0a13-py2.py3-none-any.whl/kolibri/dist/django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/richard/.pex/install/kolibri-0.16.0a13-py2.py3-none-any.whl.5fde7692abbe85a2d3272cba207b2e678d7f19c6/kolibri-0.16.0a13-py2.py3-none-any.whl/kolibri/dist/django/views/decorators/csrf.py", line 58, in wrapped_view
    return view_func(*args, **kwargs)
  File "/home/richard/.pex/install/kolibri-0.16.0a13-py2.py3-none-any.whl.5fde7692abbe85a2d3272cba207b2e678d7f19c6/kolibri-0.16.0a13-py2.py3-none-any.whl/kolibri/dist/rest_framework/viewsets.py", line 116, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/richard/.pex/install/kolibri-0.16.0a13-py2.py3-none-any.whl.5fde7692abbe85a2d3272cba207b2e678d7f19c6/kolibri-0.16.0a13-py2.py3-none-any.whl/kolibri/dist/rest_framework/views.py", line 495, in dispatch
    response = self.handle_exception(exc)
  File "/home/richard/.pex/install/kolibri-0.16.0a13-py2.py3-none-any.whl.5fde7692abbe85a2d3272cba207b2e678d7f19c6/kolibri-0.16.0a13-py2.py3-none-any.whl/kolibri/dist/rest_framework/views.py", line 455, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/home/richard/.pex/install/kolibri-0.16.0a13-py2.py3-none-any.whl.5fde7692abbe85a2d3272cba207b2e678d7f19c6/kolibri-0.16.0a13-py2.py3-none-any.whl/kolibri/dist/rest_framework/views.py", line 492, in dispatch
    response = handler(request, *args, **kwargs)
  File "/home/richard/.pex/install/kolibri-0.16.0a13-py2.py3-none-any.whl.5fde7692abbe85a2d3272cba207b2e678d7f19c6/kolibri-0.16.0a13-py2.py3-none-any.whl/kolibri/core/device/api.py", line 91, in create
    data = serializer.save()
  File "/home/richard/.pex/install/kolibri-0.16.0a13-py2.py3-none-any.whl.5fde7692abbe85a2d3272cba207b2e678d7f19c6/kolibri-0.16.0a13-py2.py3-none-any.whl/kolibri/dist/rest_framework/serializers.py", line 214, in save
    self.instance = self.create(validated_data)
  File "/home/richard/.pex/install/kolibri-0.16.0a13-py2.py3-none-any.whl.5fde7692abbe85a2d3272cba207b2e678d7f19c6/kolibri-0.16.0a13-py2.py3-none-any.whl/kolibri/core/device/serializers.py", line 118, in create
    facility = Facility.objects.get(pk=facility_id)
  File "/home/richard/.pex/install/kolibri-0.16.0a13-py2.py3-none-any.whl.5fde7692abbe85a2d3272cba207b2e678d7f19c6/kolibri-0.16.0a13-py2.py3-none-any.whl/kolibri/dist/django/db/models/manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/home/richard/.pex/install/kolibri-0.16.0a13-py2.py3-none-any.whl.5fde7692abbe85a2d3272cba207b2e678d7f19c6/kolibri-0.16.0a13-py2.py3-none-any.whl/kolibri/dist/django/db/models/query.py", line 380, in get
    self.model._meta.object_name
DoesNotExist: Facility matching query does not exist.
```

## Context
v0.16.0-a13

### PR DESCRIPTION
**Pull request by akolson**
## Summary

Improves error handling in the device provisioning API and also updates UI to show error messages(if any) and also an option to start the setup process over again

## References

Fixes https://github.com/learningequality/kolibri/issues/10598

## Reviewer guidance

Ensure that device setup works as expected without any any errors or usability issues

----

## Testing checklist

- [x] Contributor has fully tested the PR manually
- [x] If there are any front-end changes, before/after screenshots are included
- [ ] Critical user journeys are covered by Gherkin stories
- [ ] Critical and brittle code paths are covered by unit tests

## PR process

- [x] PR has the correct target branch and milestone
- [x] PR has 'needs review' or 'work-in-progress' label
- [x] If PR is ready for review, a reviewer has been added. (Don't use 'Assignees')
- [ ] If this is an important user-facing change, PR or related issue has a 'changelog' label
- [ ] If this includes an internal dependency change, a link to the diff is provided

## Reviewer checklist

- Automated test coverage is satisfactory
- PR is fully functional
- PR has been tested for [accessibility regressions](http://kolibri-dev.readthedocs.io/en/develop/manual_testing.html#accessibility-a11y-testing)
- External dependency files were updated if necessary (`yarn` and `pip`)
- Documentation is updated
- Contributor is in AUTHORS.md

### CODE REVIEW

**Review by rtibbles — COMMENTED** [review]
All the backend changes here make sense to me, and take a very defensive approach to making sure we return 400s instead of 500s! The test coverage of those changes looks good too.

I'd like @nucleogenesis' eye on the frontend pieces to be sure of those changes.

File: kolibri/plugins/setup_wizard/assets/src/views/onboarding-forms/SettingUpKolibri.vue [hunk 1]
```diff
@@ -1,7 +1,28 @@
...
 
   <div class="full-page">
-    <main class="content">
+    <div
+      v-if="coreError"
+      style="padding: 16px;"
+    >
+      <AppError :hideParagraphs="true">
+        <h2>{{ coreError }}</h2>
+        <template
```
Comment (nucleogenesis) [inline kolibri/plugins/setup_wizard/assets/src/views/onboarding-forms/SettingUpKolibri.vue]: Glad you caught this! I put this in `OnboardingStepBase` not fully considering that `SettingUpKolibri` doesn't use it 🤦🏻‍♂️

File: kolibri/plugins/setup_wizard/assets/src/views/onboarding-forms/SettingUpKolibri.vue [hunk 2]
```diff
@@ -1,7 +1,28 @@
...
+          v-if="restart"
```
Comment (nucleogenesis) [inline kolibri/plugins/setup_wizard/assets/src/views/onboarding-forms/SettingUpKolibri.vue]: Curious why you hide the "startOver" behind the `restart` prop. I don't think I put this in `OnboardingStepBase`. 

If we only offer the restart on a `400` then that means we won't offer people to restart if they hit a `500` or something, which I think is good because that's not an indication that their request was bad, but that something went wrong server-side.

It just got me wondering if the same logic should be applied throughout or if it just applies to the provisioning case

**Review by nucleogenesis — APPROVED** [review]
Looks good to me - if you think that the `restart` being added into `OnboardingStepBase` as well then adding that is the only "change request" -- but if there isn't a solid reason to, then code review is approved.

File: kolibri/plugins/setup_wizard/assets/src/views/onboarding-forms/SettingUpKolibri.vue (hunk 2 above)
Comment (akolson) [reply kolibri/plugins/setup_wizard/assets/src/views/onboarding-forms/SettingUpKolibri.vue]: @nucleogenesis This was to purely to target only bad requests. I also share the same thought that 500s should not warrant a restart of a process.  I think it would be good to look at the AppError and assess the feasibility to add it to AppError as a prop. I think other scenarios within Kolibri could benefit from this too.

Comment (rtibbles) [reply kolibri/plugins/setup_wizard/assets/src/views/onboarding-forms/SettingUpKolibri.vue]: AppError is a very generic error handling page - I think in general we'd be better off not using it when we have a more defined behaviour in mind, although still being able to surface the error for reporting is helpful.

My general suggestion is in the same vein as my specific implementation here: https://github.com/learningequality/kolibri/pull/10747/files#diff-57cf66f4895f6b2b6a6ec06c72ddfc271f48202177c120cd8f0da81a8dfe1ccbR4 where I am still surfacing content rendering errors and making them reportable, but not completely overloading the page like AppError does.

Comment (akolson) [reply kolibri/plugins/setup_wizard/assets/src/views/onboarding-forms/SettingUpKolibri.vue]: Ahh I see

**Comment by akolson** [comment]
Pr has been updated based on Richard's recommendation.

**Review by nucleogenesis — APPROVED** [review]
Latest code updates to use the `UiAlert` LGTM
