### PR TITLE
Deal better with stale content API responses

### LINKED ISSUE #10968: Stale content API responses
## Observed behavior

Content API responses are cached to avoid expensive database queries. This is great since the content doesn't typically change frequently, but it also means stale responses will be sent until the cached responses expire. The current workaround is to include the content cache key in a query parameter so that the URL changes and bypasses both the browser and server caches. However, the content cache key value is only made available to the frontend statically in HTML, so the only way to ensure fresh API responses is to reload the page. That makes dynamic content management in the frontend difficult.

See https://github.com/endlessm/kolibri-explore-plugin/issues/687 for how this was affecting kolibri-explore-plugin. We worked around it by adding our own API endpoints that don't do caching, but I think this is more appropriate upstream. See #10898 for some other background and my previous attempt to fix this while retaining caching.

## Errors and logs

There are no errors, but if you run kolibri with `--debug-database`, you can see that it is not performing database queries even if `ContentCacheKey` is updated unless different URLs are sent.

## Expected behavior

When the content is updated in the backend, API responses include the new data.

## User-facing consequences

The frontend can show new content without reloading the page.

## Steps to reproduce

Start a kolibri server with `kolibri start --debug --debug-database --foreground`. From another shell query the channel API using `curl -I 'http://127.0.0.1:8080/api/content/channel/'`. Note the `ETag` header in the response so it can be used as the `contentCacheKey` query parameter.

Now make 2 requests using the `contentCacheKey` query parameter like the frontend would do but update the content cache key between the requests:
```
$ curl -sI 'http://127.0.0.1:8080/api/content/channel/?contentCacheKey=1688997709' | grep -i -e etag: -e expires:
Expires: Fri, 12 Jul 2024 02:21:37 GMT
ETag: "1688997709"
$ kolibri manage shell -c 'from kolibri.core.device.models import ContentCacheKey; ContentCacheKey.update_cache_key()'
$ curl -sI 'http://127.0.0.1:8080/api/content/channel/?contentCacheKey=1688997709' | grep -i -e etag: -e expires:
Expires: Fri, 12 Jul 2024 02:21:37 GMT
ETag: "1688997709"
```

If you look at the kolibri logs from the server, you'll see that no database queries are being made. If the `contentCacheKey` value is changed, then it will be a new URL and a new database query will be made along with a new response:

```
$ curl -sI 'http://127.0.0.1:8080/api/content/channel/?contentCacheKey=1688997710' | grep -i -e etag: -e expires:
Expires: Fri, 12 Jul 2024 02:31:49 GMT
ETag: "1689194283.413364"
```

The problem is that the client doesn't know when the `contentCacheKey` value has changed.

## Context

Kolibri 0.16.0alpha19
Linux
Chrome

### LINKED ISSUE #11028: Ensure loading state on "Explore Libraries" immersive pages is correctly implemented
## Observed behavior
Reported by @nucleogenesis in the beta0 bug bash

> Wonky loading state for the Explore libraries immersive content navigation page - it just looks frozen with no page loader or spinners where content is going to appear

https://www.notion.so/learningequality/Wonky-loading-state-for-the-Explore-libraries-immersive-content-navigation-page-it-just-looks-froz-41da053c6e8547ac84bcbfe067fb436b?pvs=4

## Expected behavior
Loading states should be fully handled to properly manage title/base page loading, data loading, etc. with KDS loaders used according to the pattern that has been updated in recent loading state work post-0.15

## User-facing consequences
Looks frozen/glitchy

## Context
beta0

### LINKED ISSUE #11033: different UI states briefly visible when loading Learn > Library
## Observed behavior
distracting UI changes flashing as `Library` loads - observed every time the page loads without any throttling & issue became much more evident once throttled to "slow 3g." appears to be briefly displaying UI for other states (e.g. side menu opens as if content existed) while loading.

may be resolved by same PR that addresses #11028 - may be a different manifestation with the same root cause as the behavior reported there

## Screen recording

https://github.com/learningequality/kolibri/assets/43046460/1d40c559-dffa-42eb-9e15-80b3eaa5a655

## Expected behavior
show loading spinners or other appropriate content placeholders during loading

## Steps to reproduce
navigate to `Learn` > `Library` when there is no content on your device (see screen recording for additional context)

### PR DESCRIPTION
**Pull request by rtibbles**
## Summary
* Ultimately, this is needed to allow dynamic updating of available resources due to learner initiated content download
* Incorporates the removal of the content cache key in metadata requests from #10969
* Completes the removal of content cache key from GET parameter handling and being passed into the frontend in a bootstrap
* Removes bootstrapped channels, languages, and other search metadata labels to ensure they are updated based on dynamic content loading
* Updates VueRouter wrapper to allow delegation of `next` calls to handler functions, but only if they resolve synchronously. Adds a warning statement in case an async handler attempts to do this.
* Updates all learn existence checks for channels to do an asynchronous call to fetch channels
* Updates search global label setting to use an API call for the local device case
* Moves all state setting in handlers for Topics pages, content page, and Library page into the component setup method.
* Removes unneeded vuex state, instead using composition API to set local state.
* Updates all relevant test suites to feed in data via mock API calls, which effectively adds test coverage of the previous handler functions.
* Adds the `flushPromises` npm library for testing, to allow waiting for all async calls made inside the setup function to have finished before making assertions about component state.
* Updates loading state for ExploreLibrariesPage to progressively display them as they load
* Sort devices by locale sensitive name order
* Display circular loaders consistently until something is ready to be displayed on the library, topics, and topics content pages

## References
Fixes [#10968](https://github.com/learningequality/kolibri/issues/10968)
Supersedes #10969

Fixes [#11033](https://github.com/learningequality/kolibri/issues/11033)
Fixes [#11028](https://github.com/learningequality/kolibri/issues/11028)

## Reviewer guidance
As this changes the core vue router to allow the use of `next` in handlers, it is possible this could have unintended side effects if other handler functions return promises.

----

## Testing checklist

- [ ] Contributor has fully tested the PR manually
- [ ] If there are any front-end changes, before/after screenshots are included
- [ ] Critical user journeys are covered by Gherkin stories
- [ ] Critical and brittle code paths are covered by unit tests

## PR process

- [ ] PR has the correct target branch and milestone
- [ ] PR has 'needs review' or 'work-in-progress' label
- [ ] If PR is ready for review, a reviewer has been added. (Don't use 'Assignees')
- [ ] If this is an important user-facing change, PR or related issue has a 'changelog' label
- [ ] If this includes an internal dependency change, a link to the diff is provided

## Reviewer checklist

- Automated test coverage is satisfactory
- PR is fully functional
- PR has been tested for [accessibility regressions](http://kolibri-dev.readthedocs.io/en/develop/manual_testing.html#accessibility-a11y-testing)
- External dependency files were updated if necessary (`yarn` and `pip`)
- Documentation is updated
- Contributor is in AUTHORS.md

### CODE REVIEW

File: kolibri/core/assets/src/router.js [hunk 1]
```diff
@@ -18,10 +18,21 @@ class Router {
...
+      if (!nextCalled) {
+        nextCalled = true;
+        next(...args);
+      }
+    };
+    let promise = Promise.resolve();
     if (this._actions[toRoute.name]) {
-      this._actions[toRoute.name](toRoute, fromRoute);
+      const handlerPromise = this._actions[toRoute.name](toRoute, fromRoute, nextOnce);
+      if (handlerPromise && handlerPromise instanceof Promise) {
```
Comment (marcellamaki) [inline kolibri/core/assets/src/router.js]: is it possible for `const handlerPromise` to not be a promise? reading 
`handlerPromise && handlerPromise instanceof Promise` suggests that it could _not_ be a Promise, which makes the naming of the `const` confusing

File: kolibri/plugins/learn/assets/src/composables/useSearch.js [hunk 2]
```diff
@@ -350,7 +339,7 @@ export default function useSearch(descendant, store, router) {
   // component to setup the available labels for child components
   // to consume them.
 
-  const otherDeviceGlobalLabels = ref(null);
+  const globalLabels = ref(null);
```
Comment (marcellamaki) [inline kolibri/plugins/learn/assets/src/composables/useSearch.js:342]: So we have combined both other dvice and local device labels into one category, and we have none set by default before fetching, right?

File: kolibri/plugins/learn/assets/src/composables/useChannels.js [hunk 3]
```diff
@@ -1,28 +1,25 @@
...
 
 function fetchChannels(params) {
-  return ChannelResource.list(params).then(channels => {
+  params = pickBy(params || {});
+  return ChannelResource.list({ available: true, ...params }).then(channels => {
     for (const channel of channels) {
       set(channelsMap, channel.id, channel);
     }
+    if (Object.keys(params).length === 0) {
+      set(localChannelsCache, channels);
```
Comment (marcellamaki) [inline kolibri/plugins/learn/assets/src/composables/useChannels.js:21]: are we only setting this if there are no params, so that we are not setting a subset (i.e. a search) as the local cache?

File: kolibri/plugins/learn/assets/src/modules/topicsTree/handlers.js [hunk 4]
```diff
@@ -78,23 +79,25 @@ function _getChildren(id, topic, skip) {
...
   } else if (skipped) {
     // If we have skipped down the topic tree, replace to the new top level topic
-    router.replace({ name: route.name, params: { ...route.params, id }, query: route.query });
+    next({ name: route.name, params: { ...route.params, id }, query: route.query, replace: true });
+    return true;
   }
 }
 
-function _loadTopicsTopic(store, { route, baseurl } = {}) {
+function _loadTopicsTopic(next, { route, baseurl, shouldResolve } = {}) {
```
Comment (marcellamaki) [inline kolibri/plugins/learn/assets/src/modules/topicsTree/handlers.js]: This is not about this function specifically, but more that as I am reading through these handlers, I am realizing that despite reading through what I have so far, I do not have a good sense of when we are going to start needing to use this new `next` functionality. Will it be always, going forward? or is this a work around to deal with existing code, that we can approach differently going forward?

File: kolibri/plugins/learn/assets/src/routes/index.js [hunk 5]
```diff
@@ -51,39 +49,42 @@ export default [
   {
     name: PageNames.ROOT,
     path: '/',
-    handler: () => {
-      if (get(isUserLoggedIn) && get(channels).length) {
-        return router.replace({ name: PageNames.HOME });
+    redirect: () => {
```
Comment (marcellamaki) [inline kolibri/plugins/learn/assets/src/routes/index.js:34]: is this changing because the `next` is added anove in the unassigned content guard rather than rhe `router.replace`?

**Review by marcellamaki — COMMENTED** [review]
So far, I have really just added questions - I don't have specific recommendations or requests for things to change. I do find the earlier commits somewhat difficult to read, but I am guessing that this is related at least to the fact that I am not familiar with some of the django functions that are being used for caching. If @akolson or @nucleogenesis are more familiar and have any thoughts there, it would be welcome. The router changes are much easier for me to read, although I do still have some questions, which I noted, about the implications for the future.

My other thought is that while this is a needed change, it also somewhat large for being relatively close to release, and that makes me a little nervous. I don't know the best approach for having some regression testing here, but if we can figure out a way for Peter to do some manual QA before this is merged, that would give me a lot of peace of mind. Maybe doing critical workflows on learn (non-syncing related but including remote browsing) and ensuring the core functionality is still working as expected. (I have not done any manual QA yet myself)

File: kolibri/core/assets/src/router.js (hunk 1 above)
Comment (akolson) [reply kolibri/core/assets/src/router.js]: Its probably best called a `handler` to clear the confusion?

Comment (rtibbles) [reply kolibri/core/assets/src/router.js]: It's the return value of the handler function, which currently could be anything - although is mostly likely to be `undefined` - if I did change the name `handlerReturnValue` would be the most explicit.

File: kolibri/plugins/learn/assets/src/composables/useSearch.js (hunk 2 above)
Comment (rtibbles) [reply kolibri/plugins/learn/assets/src/composables/useSearch.js:342]: Correct - previously we were treating the local device search labels specially because we bootstrapped them into the page and loaded them from plugin_data, however, that's not compatible with them changing during the course of the page lifetime (as they will need to when resources are being dynamically downloaded by the learner).

File: kolibri/plugins/learn/assets/src/composables/useChannels.js (hunk 3 above)
Comment (rtibbles) [reply kolibri/plugins/learn/assets/src/composables/useChannels.js:21]: The main target here is if the `baseurl` parameter is defined, in which case it is fetching channels from another device - although if there was any filtering here aside from `available: true` then this would also need to be excluded, because it would only be a subset of channels.

File: kolibri/plugins/learn/assets/src/routes/index.js (hunk 5 above)
Comment (rtibbles) [reply kolibri/plugins/learn/assets/src/routes/index.js:34]: The main reason here is to avoid repeated calls to `fetchChannels` now that we don't statically load the channels into the page.

We just do the plain redirect here based on statically defined properties, and then let the HOME page do the `fetchChannels` call and then redirect again if we shouldn't be there!

File: kolibri/plugins/learn/assets/src/routes/index.js [hunk 6]
```diff
@@ -51,39 +49,42 @@ export default [
...
-          .catch(error => {
-            return store.dispatch('handleApiError', { error, reloadOnReconnect: true });
-          });
+      return fetchChannels().then(channels => {
+        if (!channels.length) {
+          next({ name: PageNames.LIBRARY, replace: true });
+          return;
+        }
+
+        return store.dispatch('loading').then(() => {
```
Comment (rtibbles) [inline kolibri/plugins/learn/assets/src/routes/index.js]: Possible we should call this synchronously with the fetch channels call.

**Comment by rtibbles** [comment]
Key things that would need to be regression tested:
* Channel browsing (local and remote)
* Search (local and remote)
* Redirects after a fresh setup for an on my own user
* Ensure that navigation is unaffected by the vue router wrapping changes here in say, the facility plugin

File: kolibri/core/content/api.py [hunk 7]
```diff
@@ -97,30 +99,25 @@ def metadata_cache(some_func):
...
-            patch_response_headers(response, cache_timeout=timeout)
-
+        key_prefix = get_cache_key()
+        url_key = hashlib.md5(
+            force_bytes(iri_to_uri(request.build_absolute_uri()))
+        ).hexdigest()
+        cache_key = "{}:{}".format(key_prefix, url_key)
+        response = cache.get(cache_key)
+        if response is None:
+            response = some_func(*args, **kwargs)
```
Comment (akolson) [inline kolibri/core/content/api.py]: Not a blocker, just more concerned about the readability of this `some_func`. I understand its just an arg, but it doesn't indicate what that function does.

File: kolibri/core/assets/src/router.js (hunk 1 above)
Comment (marcellamaki) [reply kolibri/core/assets/src/router.js]: `handlerReturnValue` seems clearer to me

File: kolibri/plugins/learn/assets/src/modules/topicsTree/handlers.js (hunk 4 above)
Comment (rtibbles) [reply kolibri/plugins/learn/assets/src/modules/topicsTree/handlers.js]: One thing it allows is to properly redirect without risk of duplicate navigation errors or other errors from trying to navigate using the router while in a navigation guard.

I implemented it here because it was necessary to wait for the fetchChannel async call before we know if it's OK to complete the navigation or not.

**Review by akolson — COMMENTED** [review]
Generally, implementation and usage of the `next()` function looks correct to me. Also, the code is very readable and understandable. Thanks @rtibbles. This certainly needs a bit of regression testing and it remains to be seen if anything pops up, but from a code perspective, I am comfortable with the changes. 

I will be taking some time to do some manual testing and in case anything comes up, I will update the pr accordingly.

File: kolibri/core/content/api.py (hunk 7 above)
Comment (rtibbles) [reply kolibri/core/content/api.py]: Yes, this should really be `view_func` - I had a similar thought as I was looking at it and making these changes. Can update.

**Comment by rtibbles** [comment]
I have been doing some additional work on top of this PR to handle loading states, and it has persuaded me that I have made a slight mistake in the implementation here.

The overall intention of using `next` is sensible and workable, but the issue is that delaying instantiation of the components without the global management of loading states that CoreBase used to provide is simply not workable. It leads to very weird UI states, where 'loading' is happening, but because 'loading' is presumed to be the state on entry to a component, and not on exit, it makes things look very weird.

So - I think I need to revert these changes and look for a different path to achieve the same goals. Some of this will probably involve moving some of the handler logic into the relevant components instead.

**Review by nucleogenesis — DISMISSED** [review]
The code looks good but I ran into one issue that seems likely related to the router changes.

When I am not signed in and I go to http://localhost:8000/en/coach/#/d56772ffa2f689742cf5f190d8debabe/plan/lessons/new (ie, Lesson Creation) it just shows a blank screen.

I know this redirects to the "sign in to kolibri" page on develop because I've run into it while working on the quiz creation stuff a few times recently.

I'm not getting any error messages - just the terminal output:

```bash
"GET /en/coach/" 304 0 "" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/116.0.0.0 Safari/537.36"
"PUT /api/auth/session/current/" 200 0 "http://localhost:8000/en/coach/" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/116.0.0.0 Safari/537.36"
"GET /api/content/channel/" 304 0 "http://localhost:8000/en/coach/" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/116.0.0.0 Safari/537.36"
"GET /coach/api/classsummary/d56772ffa2f689742cf5f190d8debabe/" 401 0 "http://localhost:8000/en/coach/" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/116.0.0.0 Safari/537.36"
"GET /coach/api/notifications/" 401 0 "http://localhost:8000/en/coach/" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/116.0.0.0 Safari/537.36"
```

Note that if I just go to `/en/coach` then it shows the expected "Sign into kolibri" message but `/en/coach/#/4148b1e3a85a9e1a5b3536bb77728ace/` doesn't.

Also - seems localized to coach as a similar paths in Facility don't fail ie, `/en/facility/#/users/3aab37116b1972529d84b0fa4a82c99f`

**Comment by rtibbles** [comment]
> The code looks good but I ran into one issue that seems likely related to the router changes.
> 
> When I am not signed in and I go to http://localhost:8000/en/coach/#/d56772ffa2f689742cf5f190d8debabe/plan/lessons/new (ie, Lesson Creation) it just shows a blank screen.
> 
> I know this redirects to the "sign in to kolibri" page on develop because I've run into it while working on the quiz creation stuff a few times recently.
> 
> I'm not getting any error messages - just the terminal output:
> 
> ```shell
> "GET /en/coach/" 304 0 "" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/116.0.0.0 Safari/537.36"
> "PUT /api/auth/session/current/" 200 0 "http://localhost:8000/en/coach/" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/116.0.0.0 Safari/537.36"
> "GET /api/content/channel/" 304 0 "http://localhost:8000/en/coach/" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/116.0.0.0 Safari/537.36"
> "GET /coach/api/classsummary/d56772ffa2f689742cf5f190d8debabe/" 401 0 "http://localhost:8000/en/coach/" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/116.0.0.0 Safari/537.36"
> "GET /coach/api/notifications/" 401 0 "http://localhost:8000/en/coach/" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/116.0.0.0 Safari/537.36"
> ```
> 
> Note that if I just go to `/en/coach` then it shows the expected "Sign into kolibri" message but `/en/coach/#/4148b1e3a85a9e1a5b3536bb77728ace/` doesn't.
> 
> Also - seems localized to coach as a similar paths in Facility don't fail ie, `/en/facility/#/users/3aab37116b1972529d84b0fa4a82c99f`

Thanks @nucleogenesis - I think this validates my decision to partially roll back these changes, and to remove the tricky 'async inference' stuff. 

Although, oddly, this particular route doesn't even use a handler: https://github.com/learningequality/kolibri/blob/release-v0.16.x/kolibri/plugins/coach/assets/src/routes/planLessonsRoutes.js#L52

**Comment by rtibbles** [comment]
I thought this was ready to go, but it is not yet.

**Comment by rtibbles** [comment]
This should now be ready to review - as it fixed a lot of the loading state issues as well, I finalized that work here within the same PR rather than doing a follow up.

File: kolibri/plugins/learn/assets/src/views/TopicsPage/index.vue [hunk 8]
```diff
@@ -419,11 +419,7 @@
 
             id = childrenResults.id;
 
-            const redirected = _handleTopicRedirect(route, children, id, skipped);
-
-            if (redirected) {
-              return;
-            }
+            _handleTopicRedirect(route, children, id, skipped);
```
Comment (marcellamaki) [inline kolibri/plugins/learn/assets/src/views/TopicsPage/index.vue:422]: I don't understand this change. Well, I understand it in a literal sense but I don't know really why it's happening or where it's needed.

**Comment by marcellamaki** [comment]
@rtibbles - I took a read through this and I am going to do so again Monday AM to see if I have more useful questions/comments at that time, but hopefully @pcenov will be able to do some testing Monday and we can move forward with getting this merged then

File: kolibri/plugins/learn/assets/src/views/ExploreLibrariesPage/index.vue [hunk 9]
```diff
@@ -211,8 +233,7 @@
         return this.createPinForUser(instance_id).then(response => {
           const id = response.id;
           this.usersPins = [...this.usersPins, { instance_id, id }];
-          this.moreDevices = this.unpinnedDevices;
-
+          this.moreDevices = 0;
```
Comment (akolson) [inline kolibri/plugins/learn/assets/src/views/ExploreLibrariesPage/index.vue:236]: For purposes of clarity, why are we resetting this to `0`?

File: kolibri/plugins/learn/assets/src/views/TopicsPage/index.vue (hunk 8 above)
Comment (rtibbles) [reply kolibri/plugins/learn/assets/src/views/TopicsPage/index.vue:422]: I had originally added this to prevent calling `next` twice when I was trying to do all the redirect handling using `next` - I forgot to remove it when I was reverting that change, so I cleaned it up here rather than faff around more with the commit history (even more than I already have).

File: kolibri/plugins/learn/assets/src/views/ExploreLibrariesPage/index.vue (hunk 9 above)
Comment (rtibbles) [reply kolibri/plugins/learn/assets/src/views/ExploreLibrariesPage/index.vue:236]: Because, by default, if there are any pinned devices we don't display 'more devices' - we could attempt to preserve user intent if they have already pressed 'show more' but this was simpler to do for now.

**Review by akolson — COMMENTED** [review]
Thanks @rtibbles! More generally the code looks good to me. However, with lots of moving pieces and very large diffs, it got more complex while trying to navigate the code and put the pieces together. I guess the complexity of the issue at hand sometimes calls for massive changes :)  
I will be doing some manual testing too to see if I can pick up anything!

**Review by marcellamaki — APPROVED** [review]
Since neither @akolson nor I have come up with any blocking change requests, I am going to approve and merge this, but @radinamatic and @pcenov it would be helpful to get some QA here - either on this build, or in the 0.16.x branch (I can tag a beta if that is helpful), in case any follow up is needed. Thank you!

**Comment by pcenov** [comment]
@marcellamaki and @radinamatic I didn't spot any issues while testing the following regression testing areas: Channel browsing (local and remote); Search (local and remote); Redirects after a fresh setup for an on my own user; Ensure that navigation is unaffected by the vue router wrapping changes here in say, the facility plugin

Will further keep looking for any regressions in the upcoming Beta 6!
