### PR TITLE
In Facility task cards, only quote the facility name and not the ID fragment

### LINKED ISSUE #7123: name of facility is incorrectly wrapped in single-quotes
### Observed behavior

We use single-quotes to wrap user-generated text, like the name of facilities. We use parentheses to wrap the computer-generated IDs of facilities.

The task manager combines the two as `Sync '{facility} (`id`)'`

image

### Expected behavior

String should be `Sync '{facility}' (`id`)`

### User-facing consequences

potential confusion about what the actual name of the facility is

### Steps to reproduce

import a facility

### Context

0.14 beta 3

### PR DESCRIPTION
**Pull request by jonboiser**
## Summary

Fixes #7123

## Reviewer guidance

The tests should confirm the new behavior, but this can be manually confirmed by importing/syncing/deleting a facility in the app.

## Testing checklist

- [x] Contributor has fully tested the PR manually
- [ ] If there are any front-end changes, before/after screenshots are included
- [ ] Critical user journeys are covered by Gherkin stories
- [ ] Critical and brittle code paths are covered by unit tests

## PR process

- [ ] PR has the correct target branch and milestone
- [ ] PR has 'needs review' or 'work-in-progress' label
- [ ] If PR is ready for review, a reviewer has been added. (Don't use 'Assignees')
- [ ] If this is an important user-facing change, PR or related issue has a 'changelog' label
- [ ] If this includes an internal dependency change, a link to the diff is provided

## Reviewer checklist

- Automated test coverage is satisfactory
- PR is fully functional
- PR has been tested for [accessibility regressions](http://kolibri-dev.readthedocs.io/en/develop/manual_testing.html#accessibility-a11y-testing)
- External dependency files were updated if necessary (`yarn` and `pip`)
- Documentation is updated
- Contributor is in AUTHORS.md

### CODE REVIEW

**Review by rtibbles — APPROVED** [review]

File: kolibri/core/assets/src/mixins/taskStrings.js [hunk 1]
```diff
@@ -69,7 +69,7 @@ const taskStrings = createTranslator('TaskStrings', {
     context: 'Sync task status',
   },
   syncFacilityTaskLabel: {
-    message: "Sync '{facilityName}'",
+    message: 'Sync {facilityName}',
```
Comment (indirectlylit) [inline kolibri/core/assets/src/mixins/taskStrings.js:72]: This change and similar ones looks incorrect to me. From [the design system](https://design-system.learningequality.org/writing/#notes):

> Always wrap user-generated text in 'single quotes'.

**Review by indirectlylit — COMMENTED** [review]
I think this PR may have taken away some single-quotes that were actually correct (cc @jonboiser @rtibbles)

File: kolibri/core/assets/src/mixins/taskStrings.js (hunk 1 above)
Comment (jonboiser) [reply kolibri/core/assets/src/mixins/taskStrings.js:72]: `facilityName` is interpolated to something like `'My facility' (a1b2)`, so the full message should match what you're saying. Check out the tests.

Comment (indirectlylit) [reply kolibri/core/assets/src/mixins/taskStrings.js:72]: Ah, interesting – I didn't realize that `facilityNameWithId` was used inside other strings. I think that this pattern, while DRY, is technically incorrect for i18n strings because we're essentially using string concatenation to join two incomplete phrases.

A more technically correct string would include both inputs:

```
     message: `Sync '{facilityName}' ({id})`, 
```

My understanding is that this less-DRY format is easier for the translators to work with effectively.

(cc @radinamatic in case you have guidance and @jredrejo from the original change)

None of this is super critical – just wanted to flag for discussion and future work.
