### PR TITLE
Fix facility sync elapsed time

### LINKED ISSUE #10759: Scheduled sync - The 'Last synced' value won't auto-update
## Observed behavior
Reporting this as a follow-up issue noticed in https://github.com/learningequality/kolibri/pull/10748
When a sync is happening while one is at the Facilities page, the 'Last synced' value doesn't update unless I manually refresh the page.

## Expected behavior
The 'Last synced' value should get updated immediately.

## Steps to reproduce the issue
1. Install the latest build asset from https://github.com/learningequality/kolibri/pull/10748
2. Create a scheduled sync either for a device or KDP
3. Observe the behavior of the 'Last synced' value immediately after the sync has occurred.

## Video

https://github.com/learningequality/kolibri/assets/79847249/ae9bcd27-a85a-48f1-a5b4-4c97fcba223a

## Usage Details
Kolibri 0.16alfa14
Windows 10, Ubuntu - Chrome

### PR DESCRIPTION
**Pull request by AlexVelezLl**
## Summary

Refresh elapsed time since last sync in the Facility sync status

## References

Closes #10759

## Reviewer guidance

Reproduce #10759

## Testing checklist

- [x] Contributor has fully tested the PR manually
- [ ] If there are any front-end changes, before/after screenshots are included
- [ ] Critical user journeys are covered by Gherkin stories
- [ ] Critical and brittle code paths are covered by unit tests

## PR process

- [x] PR has the correct target branch and milestone
- [x] PR has 'needs review' or 'work-in-progress' label
- [ ] If PR is ready for review, a reviewer has been added. (Don't use 'Assignees')
- [ ] If this is an important user-facing change, PR or related issue has a 'changelog' label
- [ ] If this includes an internal dependency change, a link to the diff is provided

## Reviewer checklist

- Automated test coverage is satisfactory
- PR is fully functional
- PR has been tested for [accessibility regressions](http://kolibri-dev.readthedocs.io/en/develop/manual_testing.html#accessibility-a11y-testing)
- External dependency files were updated if necessary (`yarn` and `pip`)
- Documentation is updated
- Contributor is in AUTHORS.md

### CODE REVIEW

**Comment by pcenov** [comment]
Hi @AlexVelezLl, the fix is working correctly at `Device > Facilities` if I click the Sync button and select to sync either to KDP or a facility in the local network. However if while I am at `Device > Facilities` I go to `Options > Manage sync schedule` and I edit the sync schedule, when I go back to `Device > Facilities` then I see that there's a sync in progress and after it has finished the `Last synced` value doesn't refresh automatically:

https://github.com/learningequality/kolibri/assets/79847249/9d6d914f-bbfc-4127-a74b-676311dc89c1

Also, we have the same sync feature at `Facility > Data` where I am not seeing the auto refresh at all:

https://github.com/learningequality/kolibri/assets/79847249/ccbb39a9-a7d9-487f-a698-32a0268a5b04

File: kolibri/plugins/device/assets/src/views/FacilitiesPage/index.vue [hunk 1]
```diff
@@ -253,11 +253,14 @@
...
     watch: {
       // Update facilities whenever a watched task completes
-      facilityTasks(newTasks) {
+      facilityTasks(newTasks, prevTasks) {
         for (const index in newTasks) {
           const task = newTasks[index];
           if (this.taskIdsToWatch.includes(task.id)) {
-            if (task.status === TaskStatuses.COMPLETED) {
+            if (
+              task.status === TaskStatuses.COMPLETED ||
```
Comment (AlexVelezLl) [inline kolibri/plugins/device/assets/src/views/FacilitiesPage/index.vue:261]: We werent taking into account that repeating tasks doesnt have a "completed" status when they are synced and thats why we hadnt the `last_successful_sync` value updated.

**Comment by AlexVelezLl** [comment]
Thank you @pcenov! I have addressed the issue in both places.

File: kolibri/plugins/device/assets/src/views/FacilitiesPage/index.vue [hunk 2]
```diff
@@ -284,6 +287,16 @@
         .catch(() => (this.loadingFacilities = false));
     },
     methods: {
+      isRepeatingTaskCompleted(task, prevTasks) {
+        if (!task.repeat_interval) {
+          return false;
+        }
+        const prevTask = prevTasks.find(({ id }) => id === task.id);
+        if (!prevTask) {
```
Comment (rtibbles) [inline kolibri/plugins/device/assets/src/views/FacilitiesPage/index.vue:295]: Hrm, wondering why there is this "previous task" at all, the API should only be returning a single job status from the backend for an id.

If it is happening, liable to be a frontend state persisting which would go away if we refreshed the page.

File: kolibri/plugins/facility/assets/src/views/DataPage/SyncInterface/index.vue [hunk 3]
```diff
@@ -232,8 +232,8 @@
         TaskResource.get(this.syncTaskId).then(task => {
           if (task.clearable) {
             this.isSyncing = false;
-            this.syncTaskId = '';
             TaskResource.clear(this.syncTaskId);
+            this.syncTaskId = '';
```
Comment (rtibbles) [inline kolibri/plugins/facility/assets/src/views/DataPage/SyncInterface/index.vue:236]: Why did this need to be moved? The clear method returns a promise, so if we want to wait until after the clear we would need to await it.

**Review by rtibbles — COMMENTED** [review]
A couple of questions about the code.

File: kolibri/plugins/device/assets/src/views/FacilitiesPage/index.vue (hunk 2 above)
Comment (AlexVelezLl) [reply kolibri/plugins/device/assets/src/views/FacilitiesPage/index.vue:295]: Probably, the name should be improved. Here, by previousTasks, I mean the previous snapshot of the tasks list. The thing is that for repeating tasks, we never had the task with a "COMPLETED" status, and thereby [this line](https://github.com/learningequality/kolibri/pull/12158/files#diff-000e3e069f5a647e12d6fa6acfec612deb07b16fcc9216515f48066de0cebd84R264) is not executed, and we do not have the updated value of `facility.last_successful_sync` .

The problem is that repeating tasks keep the same reference for multiple executions, and they never end in a "COMPLETED" status because, after the "RUNNING" state, they pass to "QUEUED" again when the execution ends. So the way I found to determine if a single task run has been completed was comparing the current state of the task with the previous snapshot.

File: kolibri/plugins/facility/assets/src/views/DataPage/SyncInterface/index.vue (hunk 3 above)
Comment (AlexVelezLl) [reply kolibri/plugins/facility/assets/src/views/DataPage/SyncInterface/index.vue:236]: Oh no no, I am not sure the reason for setting an empty string to `syncTaskId`, but the thing was that if we first set `this.syncTaskId = '';` and after we execute `TaskResource.clear(this.syncTaskId);`, we would be excecuting TaskResource.clear with an empty string, and because of this, it was throwing an exception, and the code below wasn't executing, and therefore the last sync value wasn't being updated.

**Comment by pcenov** [comment]
Hi @AlexVelezLl I confirm that the reported issues are fixed now and there are no new issues observed while manually testing. LGTM!

**Review by radinamatic — APPROVED** [review]
Manual QA passes, good to go! 💯 👏🏽 :shipit:

File: kolibri/plugins/device/assets/src/views/FacilitiesPage/index.vue (hunk 2 above)
Comment (rtibbles) [reply kolibri/plugins/device/assets/src/views/FacilitiesPage/index.vue:295]: Yeah - my point was that if this is working it's because we had data from a previous fetch where the task was in progress, so it's quite possible that on a refresh of the page we would still get an issue here.

I don't think this needs to be resolved now - but there's definitely some cleanup we can do overall for how we handle tasks on the frontend (probably through a core useTasks composable that consolidates a lot of this logic).

File: kolibri/plugins/facility/assets/src/views/DataPage/SyncInterface/index.vue (hunk 3 above)
Comment (rtibbles) [reply kolibri/plugins/facility/assets/src/views/DataPage/SyncInterface/index.vue:236]: Ah, that makes a lot of sense, yes!
