### PR TITLE
The questions attempted is more than the total number of questions in an exam.

### LINKED ISSUE #3244: The questions attempted is more than the total number of questions in an exam.
### Observed behaviour
The actual exam created has 30 questions, but when learners attempt them we are getting 38 questions answered out of 30 questions

whatsapp image 2018-02-23 at 9 31 54 am
whatsapp image 2018-02-23 at 9 32 09 am
 
### Expected behaviour
The attempts should be the exact number of questions answered by the learner.

### User-facing consequences
The learners and the teachers are confused and shows incorrect data, which losses the purpose of conducting exam on Kolibri.

### Steps to reproduce
1. Create an exam.
2. Attempt as a learner.
3. Watch the attempted count to total questions count.
##Note:
This might not be easily reproducible while testing in a local server, but appears on the a classroom setting, 50-70% of the kids in a class of 38 face this issue and not all.

### Context
 * Kolibri version = 0.4.9
 * Operating system = Ubuntu 14.4 LTS
 * Browser Chrome.

### PR DESCRIPTION
**Pull request by mrpau-richard**
### Summary
Reset examAttemptLogs value at the exam list page. To prevent the existing attempt logs merge at the exam page.

### References
This fixes #3244

### Contributor Checklist

- [x] PR has the correct target branch and milestone
- [x] PR has 'needs review' or 'work-in-progress' label
- [x] Contributor has fully tested the PR manually
- [ ] Screenshots of any front-end changes are in the PR description
- [ ] If PR is ready for review, a reviewer has been added. (Don't use 'Assignees')

### Reviewer Checklist

- [ ] Automated test coverage is satisfactory
- [ ] Reviewer has fully tested the PR manually
- [ ] PR has been tested for [accessibility regressions](http://kolibri-dev.readthedocs.io/en/develop/manual_testing.html#accessibility-a11y-testing)
- [ ] External dependencies files were updated (`yarn` and `pip`)
- [ ] Documentation is updated
- [ ] Link to diff of internal dependency change is included
- [ ] CHANGELOG.rst is updated for high-level changes
- [ ] Contributor is in AUTHORS.rst

### CODE REVIEW

**Comment by indirectlylit** [comment]
remember to lint your code!

File: kolibri/plugins/learn/assets/src/views/classes/AssignedExamsTable.vue [hunk 1]
```diff
@@ -112,6 +112,16 @@
       },
       examViewerLink,
     },
+    created() {
+      this.resetExamAttempLogs();
+    },
+    vuex: {
+      actions: {
+        resetExamAttempLogs(store) {
+          store.state.examAttemptLogs = [];
```
Comment (jonboiser) [inline kolibri/plugins/learn/assets/src/views/classes/AssignedExamsTable.vue]: I think this might work in special cases, but let's pretend we're running vuex in "safe" mode, so we can only make changes to `store.state` by dispatching a mutation.

**Comment by mrpau-richard** [comment]
@christianmemije I moved the reseting attempt logs at showClassAssignmentsPage actions.

**Comment by indirectlylit** [comment]
Hey @mrpau-richard - please take a read through the vuex 1.0 documentation here to got a more thorough understanding of how to interact with vuex state: https://github.com/vuejs/vuex/blob/1.0/docs/en/SUMMARY.md

In particular, note that in the [getting started](https://github.com/vuejs/vuex/blob/1.0/docs/en/getting-started.md) page it says:

> You cannot directly mutate the store's state. The only way to change a store's state is by explicitly dispatching **mutations**. This makes every state change easily track-able, and enables tooling that helps us better understand our applications.

**Comment by mrpau-richard** [comment]
@indirectlylit I apology, I mistakenly understand the feedback of @jonboiser [here](https://github.com/learningequality/kolibri/pull/3354#discussion_r174247741)
I have a new changes that reset the exam attempt logs using the dispatching mutations.

File: kolibri/plugins/learn/assets/src/state/actions/classesActions.js [hunk 2]
```diff
@@ -47,6 +47,8 @@ export function showClassAssignmentsPage(store, classId) {
       currentClassroom: {},
     },
   });
+  // Reset examAttemptLogs, so that it will not merge into another exam.
+  store.dispatch('SET_EXAM_ATTEMPT_LOGS', 'RESET_EXAM_LOGS');
```
Comment (christianmemije) [inline kolibri/plugins/learn/assets/src/state/actions/classesActions.js]: My approach would be to add a `RESET_EXAM_ATTEMPT_LOGS` mutation that clears the logs when the `showExam` action is called. 
```js
  RESET_EXAM_ATTEMPT_LOGS(state) {
    state.examAttemptLogs = {};
  },  
```
```js
export function showExam(store, examId, questionNumber) {
  store.dispatch('RESET_EXAM_ATTEMPT_LOGS');
  ...
}
```

**Comment by mrpau-richard** [comment]
@christianmemije your approach is much better than mine so I use it, Thanks.

**Comment by indirectlylit** [comment]
merging in latest develop to fix build
