### PR TITLE
Ensure only quiz and lesson sizes for the current class are fetched.

### LINKED ISSUE #10643: when user is multi-facility admin, Coach > Class Home errors once a facility is selected
## Observed behavior
If a user is a multi-facility admin and they navigate to the Coach plugin and any of its subtopics, they will be redirected to "All Facilities" containing links to each of the user's facilities. If the user selects a facility with a single class, navigation can fail (you may catch a brief glimpse of the intended page) and user is redirected to "Something happened" error page. If the user selects a facility with multiple classes, navigation may not fail until a specific class is selected, but once the selection is made the user is redirected to the error page.  

Navigation will subsequently fail if you attempt to navigate to other subtopics within Coach, e.g. "Plans" will also bring you to the error page.

https://user-images.githubusercontent.com/43046460/236279907-140cf2d8-bfb2-4ca3-b0d0-6148d45911dc.mov

## Errors and logs

browser devtools console: 
image

## Expected behavior
Successful navigation to "Class home" and all other subtopic pages once a facility is selected

**Note:** it is a known issue that in the multi-facility use-case, opening Coach in the sidenav and selecting any subtopic besides "Class home" will lead to the "All Facilities" page with links to each facility that bring you to "Class home" regardless of your initial selection. [There is a separate issue addressing this and other elements of Coach multi-facility navigation](https://github.com/learningequality/kolibri/issues/10650): #10650. 

## User-facing consequences
For multi-facility admins, this leads to the inability to see any details about any classes, as navigation to any & all subtopics fails. 

## Steps to reproduce

* user must be multi-facility admin (if none of your users have 2+ facilities, you can follow the flow `Device > Facilities Tab > Import learning facility` to add an additional facility & access shared credentials for the team's facilities in Notion)

* navigate to Coach > Class home & select a facility

## Context
MacOS Chrome

### PR DESCRIPTION
**Pull request by rtibbles**
## Summary
* Ensures fetches for lesson and quiz sizes are properly filtered by the classId
* Adds a safety check to only try to set quiz sizes on quizzes that exist

## References
Fixes [#10643](https://github.com/learningequality/kolibri/issues/10643)

## Reviewer guidance
If there are quizzes in multiple classes or across multiple facilities, this error will occur, so check that it does not with these changes.

----

## Testing checklist

- [ ] Contributor has fully tested the PR manually
- [ ] If there are any front-end changes, before/after screenshots are included
- [ ] Critical user journeys are covered by Gherkin stories
- [ ] Critical and brittle code paths are covered by unit tests

## PR process

- [x] PR has the correct target branch and milestone
- [x] PR has 'needs review' or 'work-in-progress' label
- [x] If PR is ready for review, a reviewer has been added. (Don't use 'Assignees')
- [ ] If this is an important user-facing change, PR or related issue has a 'changelog' label
- [ ] If this includes an internal dependency change, a link to the diff is provided

## Reviewer checklist

- Automated test coverage is satisfactory
- PR is fully functional
- PR has been tested for [accessibility regressions](http://kolibri-dev.readthedocs.io/en/develop/manual_testing.html#accessibility-a11y-testing)
- External dependency files were updated if necessary (`yarn` and `pip`)
- Documentation is updated
- Contributor is in AUTHORS.md

### CODE REVIEW

File: kolibri/plugins/coach/assets/src/modules/classSummary/index.js [hunk 1]
```diff
@@ -431,14 +431,16 @@ export default {
     SET_CLASS_LESSONS_SIZES(state, sizes = {}) {
       state.lessonsSizes = sizes;
     },
-    SET_CLASS_QUIZZES_SIZES(state, sizes = {}) {
+    SET_CLASS_QUIZZES_SIZES(state, sizes) {
       if (sizes.length > 0) {
-        sizes.forEach(sizeItem => {
+        for (const sizeItem of sizes) {
```
Comment (thanksameeelian) [inline kolibri/plugins/coach/assets/src/modules/classSummary/index.js:436]: when you were theorizing that this issue was due to a race condition, i was envisioning something along the lines the additional `if` here and the promises added below, but i was wondering if you could explain how the `for (const sizeItem of sizes)` plays in to these changes and how you knew it would perform better than the line it's replacing - is it because of the slight speed difference functionally, as `forEach` can be somewhat slower and we're trying to speed up things as best we can? or potentially another reason?

**Review by thanksameeelian — COMMENTED** [review]
this is looking good to me! i'm no longer experiencing the errors reported in the issue, and now am able to browse classes whether or not they contain quizzes!

i did encounter a bit of weirdness when navigating - i'm including it in a separate comment as i'd like to document it & potentially discuss, but i don't believe the behavior is related to this PR, just that i observed it now because i was able to successfully navigate to places that were erroring before the changes you introduced here.

**Comment by thanksameeelian** [comment]
strange behavior i was seeing that i believe is unrelated to this PR, but uncovered by it:

as a multi-facility admin user, when i navigate to the classes page within my second facility and select a class, there is a split-second flash of the _other_ facility's (my default facility) classes page that renders in the view before successful navigation to the class initially selected. no matter the order in which i select them, when i click on Class 2A in Mr. Tibbles' House of Phun, the flash of my other facility's classes is _usually_ visible to the naked eye, and clicking on Class 1B leads to the same experience but also an error in the console. i don't experience this at all when selecting classes from my default facility.


https://github.com/learningequality/kolibri/assets/43046460/aa82810d-b9c3-4dec-b62f-be0972fd88dc

now in slow motion!
slo-mo


there is a related error in the console, seen in full in the screen recordings: `Duplicate keys detected: 'Resource_e2ad087ebe8c2ff47b9f20dc375c93f7_8136d96151c349ef9f3ddae633179f75_d56772ffa2f689742cf5f190d8debabe_undefined'. This may cause an update error.` 

i realized i have observed this error before, when demonstrating the initial issue that led to this PR & recording the console warnings -- while navigating to my default facility's classes with quizzes, i just got the errors that this PR has now fixed, but when navigating to Class 1B i also experienced the `Duplicate keys` error, it was just a bit buried within the other errors. 

https://github.com/learningequality/kolibri/assets/43046460/d1a6f4e5-1efc-4962-9761-9f388f3a9d39

i am ready to create an issue and add all this context to it, but just wanted to raise the topic here first in case there was something that was readily solvable or more related to this PR than i initially thought.

File: kolibri/plugins/coach/assets/src/modules/classSummary/index.js (hunk 1 above)
Comment (rtibbles) [reply kolibri/plugins/coach/assets/src/modules/classSummary/index.js:436]: Yes - I just did this because for... of.. is generally faster than `forEach` (because of the redefinition of the anonymous function). So this was a flyby cleanup.

**Review by thanksameeelian — APPROVED** [review]
looks good to me! will be turning my comment into its own issue :)
