### PR TITLE
Fix welcome modal appearing after deleting channels

### LINKED ISSUE #11644: The 'Welcome' modal is still being shown in LODs and normal devices if there are no imported channels
## Observed behavior
While regression testing https://github.com/learningequality/kolibri/pull/11587 I noticed that the 'Welcome' modal is still being shown in LODs and normal devices if there are no imported channels.

https://github.com/learningequality/kolibri/assets/79847249/db7d58c8-0e2e-4075-8405-b16354e60b41

## Expected behavior

The 'Welcome modal' should never be displayed in LODs. For normal devices it should only be displayed once to the user and not be displayed in subsequent sign-ins with the same or a different browser. 

## Steps to reproduce the issue

1. Install the [latest Beta 9 build asset](https://github.com/learningequality/kolibri/releases/tag/v0.16.0-beta9).
2. Create a full facility and sign in.
3. Observe that the 'Welcome modal' is displayed correctly at the Library page or at Device > Channels.
4. Open a new browser window and sign in. Going to the Library page or at Device > Channels results in the modal being shown.
5. If you install the Android app and sign in as a LOD user the modal will also be displayed when there are no imported channels.

## Usage Details
[Beta 9](https://github.com/learningequality/kolibri/releases/tag/v0.16.0-beta9)
Ubuntu 22  - Chrome

### PR DESCRIPTION
**Pull request by ozer550**
## Summary
- Consolidated welcomeModalVisible logic with number of channels present.

## References
closes #11644

## Reviewer guidance
- Remove the local storage key "welcomeDismissalKey".
- Welcome modal appears initially.
- Add channels.
- Remove them.
- The Welcome Modal does not appear again.

----

## Testing checklist

- [x] Contributor has fully tested the PR manually
- [ ] If there are any front-end changes, before/after screenshots are included
- [ ] Critical user journeys are covered by Gherkin stories
- [ ] Critical and brittle code paths are covered by unit tests

## PR process

- [ ] PR has the correct target branch and milestone
- [ ] PR has 'needs review' or 'work-in-progress' label
- [ ] If PR is ready for review, a reviewer has been added. (Don't use 'Assignees')
- [ ] If this is an important user-facing change, PR or related issue has a 'changelog' label
- [ ] If this includes an internal dependency change, a link to the diff is provided

## Reviewer checklist

- Automated test coverage is satisfactory
- PR is fully functional
- PR has been tested for [accessibility regressions](http://kolibri-dev.readthedocs.io/en/develop/manual_testing.html#accessibility-a11y-testing)
- External dependency files were updated if necessary (`yarn` and `pip`)
- Documentation is updated
- Contributor is in AUTHORS.md

### CODE REVIEW

File: kolibri/plugins/learn/assets/src/views/LibraryPage/index.vue [hunk 1]
```diff
@@ -416,7 +414,7 @@
       };
     },
     computed: {
-      ...mapGetters(['isLearnerOnlyImport']),
+      ...mapGetters(['isLearner']),
```
Comment (rtibbles) [inline kolibri/plugins/learn/assets/src/views/LibraryPage/index.vue]: My only question is about this change - I think what we probably want to do here is to retain the `isLearnerOnlyImport` condition, _and_ also add a condition checking if the user is a superadmin, otherwise, for the first imported learner only import user, the modal will now still display.

**Review by rtibbles — COMMENTED** [review]
code changes look correct to me.

**Comment by pcenov** [comment]
Hi @ozer550 the 'Welcome to Kolibri!' modal is still popping up in the Android app after deleting the channels. Can you fix it there as well?
Otherwise I confirm that this scenario is fixed in the desktop app!

**Comment by rtibbles** [comment]
@pcenov - if this is specific to the Android app, I am guessing that this is probably an issue with the Android app specifically (like we had with the user login not persisting across app restarts). Probably best to file a follow up issue on the Android repo to address this: https://github.com/learningequality/kolibri-installer-android

**Comment by pcenov** [comment]
Hi @rtibbles, after further investigation I don't think this is specific only to the Android app because the modal is still being displayed on a desktop LOD when I go to Device > Channels:

https://github.com/learningequality/kolibri/assets/79847249/2391dc80-eafb-4ef9-b0a2-adc9694ba350

**Comment by rtibbles** [comment]
OK - that's fair. @ozer550 to finish up here, could you add the isLearnerOnlyImport restriction to the Device page modal display as well?

i.e. We shouldn't show welcome modals to isLearnerOnlyImport users on either Learn or Device.

**Review by rtibbles — COMMENTED** [review]
Looks good to me, will just wait for final sign off by @pcenov

**Review by pcenov — APPROVED** [review]
Thank you @ozer550  - the modal is no longer displayed in LODs, looks good to me as well this time.

**Comment by rtibbles** [comment]
Docs build issue is resolved on release branch.
