### PR TITLE
KL-10308: Sorting tasks by `scheduled_datetime`

### LINKED ISSUE #10308: Tasks displayed in a list in the Task Manager do not have any explicit ordering
## Observed behavior
Currently, when we display tasks that are running, neither the API, nor their display in the frontend enforces any specific ordering. This can make it harder for administrators to find a running task if there is a long list.

## Expected behavior
I think the simplest behaviour here is simply to order by 'scheduled_datetime' in the frontend, which is now returned by the API endpoint.

## User-facing consequences
Confusion, irritation, annoyance.

## Steps to reproduce
Queue several tasks and see the order being somewhat random.

## Context
 * Kolibri version: 0.15+

### PR DESCRIPTION
**Pull request by luna215**
## Summary

Tasks that were running were not being enforced by any sort of order, neither from the API or the front end. The changes here enforces the order by `scheduled_datetime`. Oldest tasks added will display towards the top. 

Screenshot 2023-03-27 at 10 41 11 AM

In the sample above, I first imported the channels in the following order:
- Touchable Earth (en)
- Free English with Hello Channel
- Citoynnes de La Terre
## References

Resolves #10308. 

## Reviewer guidance

Pull in the changes, and then add channels to import. First channels added should display towards the top. 
----

## Testing checklist

- [x] Contributor has fully tested the PR manually
- [x] If there are any front-end changes, before/after screenshots are included
- [ ] Critical user journeys are covered by Gherkin stories
- [ ] Critical and brittle code paths are covered by unit tests

## PR process

- [ ] PR has the correct target branch and milestone
- [ ] PR has 'needs review' or 'work-in-progress' label
- [ ] If PR is ready for review, a reviewer has been added. (Don't use 'Assignees')
- [ ] If this is an important user-facing change, PR or related issue has a 'changelog' label
- [ ] If this includes an internal dependency change, a link to the diff is provided

## Reviewer checklist

- Automated test coverage is satisfactory
- PR is fully functional
- PR has been tested for [accessibility regressions](http://kolibri-dev.readthedocs.io/en/develop/manual_testing.html#accessibility-a11y-testing)
- External dependency files were updated if necessary (`yarn` and `pip`)
- Documentation is updated
- Contributor is in AUTHORS.md

### CODE REVIEW

**Comment by luna215** [comment]
@rtibbles tagging you to make you aware of the PR here.

File: kolibri/plugins/device/assets/src/views/ManageTasksPage/index.vue [hunk 1]
```diff
@@ -98,7 +96,15 @@
         return { name: PageNames.MANAGE_CONTENT_PAGE };
       },
       sortedTaskList() {
-        return reverse(this.managedTasks);
+        const sorterArray = this.managedTasks;
+        sorterArray.sort(
+          (a, b) => {
+            const dateA = new Date(a.scheduled_datetime)
+            const dateB = new Date(b.scheduled_datetime)
+            return (dateA > dateB) ? 1 : -1
```
Comment (rtibbles) [inline kolibri/plugins/device/assets/src/views/ManageTasksPage/index.vue]: It's an edge case, but should add some conditionality for `dateA === dateB` in which case the return value should be zero.

Can just do as an early return check before this statement:
```
if (dateA === dateB) {
   return 0;
}
```

then keep your current return statement as the final return.

**Review by rtibbles — APPROVED** [review]
