### PR TITLE
Ensure the snackbar does not reappear after the resource page is left

### LINKED ISSUE #4848: spurious 'removed 0 resources' notification
### Observed behavior

observed by @jtamiace during 0.12.0 alpha 7 testing:

> image

### Expected behavior

Notifications should not be displayed until the user has made a change

### User-facing consequences

possible confusion

### Errors and logs

…

### Steps to reproduce

…

### Context

0.12.0 alpha 5

### PR DESCRIPTION
**Pull request by jredrejo**
### Summary
Ensures the snackbar does not appear after the page is left in Lessons and Quiz plans.

### Reviewer guidance
Instruccions to reproduce the issue are at #4848 
Using this PR code the snackbar will disappear after leaving the resource that has been added.

### References
Closes #4848 

### Contributor Checklist

PR process:

- [x] PR has the correct target branch and milestone
- [x] PR has 'needs review' or 'work-in-progress' label
- [x] If PR is ready for review, a reviewer has been added. (Don't use 'Assignees')
- [ ] If this is an important user-facing change, PR or related issue has a 'changelog' label
- [ ] If this includes an internal dependency change, a link to the diff is provided

Testing:

- [x] Contributor has fully tested the PR manually
- [ ] If there are any front-end changes, before/after screenshots are included
- [ ] Gherkin stories have been updated
- [ ] Unit tests have been updated

### Reviewer Checklist

- Automated test coverage is satisfactory
- PR is fully functional
- PR has been tested for [accessibility regressions](http://kolibri-dev.readthedocs.io/en/develop/manual_testing.html#accessibility-a11y-testing)
- External dependency files were updated if necessary (`yarn` and `pip`)
- Documentation is updated
- Contributor is in AUTHORS.rst

### CODE REVIEW

File: kolibri/plugins/coach/assets/src/views/plan/PlanLessonSelectionContentPreview.vue [hunk 1]
```diff
@@ -50,8 +50,11 @@
         return false;
       },
     },
+    beforeDestroy() {
+      this.clearSnackbar();
+    },
```
Comment (indirectlylit) [inline kolibri/plugins/coach/assets/src/views/plan/PlanLessonSelectionContentPreview.vue:55]: I think this should be okay here because `clearSnackbar` is a core action.

However just a heads-up that (I believe) triggering actions and other logic from `beforeDestroy` hooks is an anti-pattern, because by the time the component is getting destroyed, app vuex state is generally unpredictable. In general I recommend that `beforeDestroy` only gets used for cleanup like removing event listeners and tearing down third-party libraries (like video.js).

Sometimes it's hard to find a reasonable alternative to `beforeDestroy`, though.

Comment (jredrejo) [reply kolibri/plugins/coach/assets/src/views/plan/PlanLessonSelectionContentPreview.vue:55]: Yes, I also dislike the moment this action is done, but what other way can we detect the person is leaving this component?
Anyway, this is a workaround, the main problem here is the SnackBar is being re-mounted whenever any of these components are destroyed. It's the mount event in the snackbar what's restarting the timeout. I haven't been able to find what is triggering the `mounted` event once again, lost in the internal vue & vuex multiple internal hooks and triggers. @indirectlylit do you have any idea of why the SnackBar is mounted when moving through components? If that event is cached we could avoid using the `beforeDestroy` event.

**Review by rtibbles — APPROVED** [review]
Merging until we can find a better pattern!
