### PR TITLE
Fix facility guard redirection on the facility plugin

### LINKED ISSUE #13929: [Facility w/ Multiple Facilities]: Side nav sub-route selection not honored after selecting a facility
❌ **This issue is not open for contribution. Visit <a href="https://learningequality.org/contributing-to-our-open-code-base/" target="_blank">Contributing guidelines</a>** to learn about the contributing process and how to find suitable issues.

## Observed behavior

* Have a device with multiple facilities
* Open side nav and select "Facility > Users" 
* You will see the "AllFacilitiesPage" - select a facility
* You'll find yourself on the "Facility > Classes" page 🙅 

## Expected behavior

You ought to go to the "Facility > Whatever you selected" page instead for the facility you end up selecting in the "AllFacilitiesPage".

## User-facing consequences

Confusing and annoying UI quirk

## Context

0.19 beta2

### PR DESCRIPTION
**Pull request by AlexVelezLl**
## Summary

* Adds new users page to facilityPageLinks so that they were available to be used on the [AllFacilitiesPage](https://github.com/AlexVelezLl/kolibri/blob/6051c55633c24fb05f7f59ea06dc67dc78ba862f/kolibri/plugins/facility/frontend/views/AllFacilitiesPage.vue#L85) component.

https://github.com/user-attachments/assets/eaa5b579-f2be-4f3c-9cc3-7b67f6a15f21

## References
Closes #13929

## Reviewer guidance

* Navigate through the different facility pages using the side navbar.

### CODE REVIEW

File: kolibri/plugins/facility/frontend/modules/pluginModule.js [hunk 1]
```diff
@@ -67,6 +67,18 @@ export default {
...
+          params,
+        },
+        NewUsersPage: {
+          name: PageNames.NEW_USERS_PAGE,
+          params,
+        },
+        UsersTrashPage: {
+          name: PageNames.USERS_TRASH_PAGE,
+          params,
+        },
```
Comment (nucleogenesis) [inline kolibri/plugins/facility/frontend/modules/pluginModule.js:81]: These don't appear to be used anywhere but it does seem like it's worth being thorough here as they are legitimate `facilityPageLinks`. Just thinking aloud a bit here I guess 😅  - it's just something I noticed while looking around the code near the changes.

**Review by nucleogenesis — APPROVED** [review]
I've performed manual QA locally and the code changes look good to me ensuring the facilityPageLinks returns a full list of available links!

Thanks @AlexVelezLl !

File: kolibri/plugins/facility/frontend/modules/pluginModule.js (hunk 1 above)
Comment (AlexVelezLl) [reply kolibri/plugins/facility/frontend/modules/pluginModule.js:81]: Oh, it was just in case someone copied and pasted a link to these pages and removed the facilityId somehow. Since in the route definitions we define these routes with the optional facilityId, we needed to support the guard on it too!
