### PR TITLE
Learner exam and exercise bug fixes

### LINKED ISSUE #1229: learner exam list page didn't refresh after submitting exam
the exam just-taken still said 'start'

### PR DESCRIPTION
**Pull request by rtibbles**
## Summary

Fixes #1229, #1242, #1246, #1247.

Some of the above also require an update from this PR: https://github.com/learningequality/kolibri-exercise-perseus-plugin/pull/66 which further fixes: #1239, #1240.

Put a WIP label here, to flag that it needs the updated perseus build before merge.

Additional note, that attemptlog saving is currently still broken, but will be fixed in @DXCanas's next PR, so don't be alarmed by that!

Finally, it makes a small tweak to how we address content scrolling, as previously it was adding a scrollbar to Perseus items, which was unnecessary and caused an ugly visual flow. Have moved the relevant fixes inside HTML5 and video renderer plugins.

### CODE REVIEW

File: kolibri/core/assets/src/views/content-renderer/index.vue [hunk 1]
```diff
@@ -14,6 +14,7 @@
         @answerGiven="answerGiven"
         @hintTaken="hintTaken"
         @itemError="itemError"
+        @interaction="interaction"
```
Comment (indirectlylit) [inline kolibri/core/assets/src/views/content-renderer/index.vue:17]: nice

File: kolibri/plugins/learn/assets/src/state/actions.js [hunk 2]
```diff
@@ -682,8 +683,14 @@ function setAndSaveCurrentExamAttemptLog(store, contentId, itemId, currentAttemp
...
-  const examAttemptLogModel = ExamAttemptLogResource.getModel(
-    currentAttemptLog.id);
+  let examAttemptLogModel = ExamAttemptLogResource.findModel({
+    content_id: contentId,
+    item: itemId,
+  });
+  if (!examAttemptLogModel) {
+    examAttemptLogModel = ExamAttemptLogResource.getModel(
+      currentAttemptLog.id);
+  }
```
Comment (indirectlylit) [inline kolibri/plugins/learn/assets/src/state/actions.js]: mind adding some comments here? It's not obvious to me why this was necessary

File: kolibri/plugins/html5_app_renderer/assets/src/views/index.vue [hunk 3]
```diff
@@ -83,6 +83,8 @@
     height: 100vh
     max-height: calc(100vh - 24em)
     min-height: 400px
+    overflow-x: auto
+    -webkit-overflow-scrolling: touch
```
Comment (christianmemije) [inline kolibri/plugins/html5_app_renderer/assets/src/views/index.vue]: Can do without `-webkit-overflow-scrolling`, as it appears to have almost no support https://developer.mozilla.org/en-US/docs/Web/CSS/-webkit-overflow-scrolling

File: kolibri/plugins/learn/assets/src/views/exam-page/index.vue [hunk 4]
```diff
@@ -116,13 +119,24 @@
...
+        this.saveAnswer();
         this.$router.push({
           name: PageNames.EXAM,
           params: { channel_id: this.channelId, id: this.exam.id, questionNumber },
         });
       },
+      submitExam() {
+        if (!this.submitModalOpen) {
+          this.saveAnswer().then(() => {
+            this.toggleModal();
```
Comment (christianmemije) [inline kolibri/plugins/learn/assets/src/views/exam-page/index.vue]: can be inlined `this.saveAnswer().then(() => this.toggleModal());`

File: kolibri/plugins/video_mp4_render/assets/src/views/index.vue [hunk 5]
```diff
@@ -217,6 +217,8 @@
     height: 480px
     max-width: 100%
     max-height: 480px
+    overflow: auto
+    -webkit-overflow-scrolling: touch
```
Comment (christianmemije) [inline kolibri/plugins/video_mp4_render/assets/src/views/index.vue]: Same as comment above.

File: kolibri/plugins/html5_app_renderer/assets/src/views/index.vue [hunk 6]
```diff
@@ -83,6 +83,8 @@
     height: 100vh
     max-height: calc(100vh - 24em)
     min-height: 400px
+    overflow-x: auto
```
Comment (christianmemije) [inline kolibri/plugins/html5_app_renderer/assets/src/views/index.vue:86]: `scroll` instead of `auto`

File: kolibri/plugins/video_mp4_render/assets/src/views/index.vue [hunk 7]
```diff
@@ -217,6 +217,8 @@
     height: 480px
     max-width: 100%
     max-height: 480px
+    overflow: auto
```
Comment (christianmemije) [inline kolibri/plugins/video_mp4_render/assets/src/views/index.vue]: Did you mean `overflow-x`?

File: kolibri/plugins/learn/assets/src/state/actions.js (hunk 2 above)
Comment (rtibbles) [reply kolibri/plugins/learn/assets/src/state/actions.js]: In short, it's because if a save happened while the first save hadn't completed, a new model would be created, so we'd end up with two attempt logs. Will add comments.

File: kolibri/plugins/html5_app_renderer/assets/src/views/index.vue (hunk 6 above)
Comment (rtibbles) [reply kolibri/plugins/html5_app_renderer/assets/src/views/index.vue:86]: I tested on browser-stack iOS iPhone5S Safari, and this still seemed to work.

File: kolibri/plugins/html5_app_renderer/assets/src/views/index.vue (hunk 3 above)
Comment (rtibbles) [reply kolibri/plugins/html5_app_renderer/assets/src/views/index.vue]: Yeah, was just copying from http://stackoverflow.com/questions/23083462/how-to-get-an-iframe-to-be-responsive-in-ios-safari#answer-23123845

File: kolibri/plugins/learn/assets/src/views/exam-page/index.vue (hunk 4 above)
Comment (rtibbles) [reply kolibri/plugins/learn/assets/src/views/exam-page/index.vue]: Actually, could be further reduced to `this.saveAnswer().then(this.toggleModal);`

File: kolibri/plugins/video_mp4_render/assets/src/views/index.vue (hunk 7 above)
Comment (rtibbles) [reply kolibri/plugins/video_mp4_render/assets/src/views/index.vue]: Will correct.

File: kolibri/plugins/html5_app_renderer/assets/src/views/index.vue (hunk 6 above)
Comment (rtibbles) [reply kolibri/plugins/html5_app_renderer/assets/src/views/index.vue:86]: Confirmed, no difference in behaviour on browser stack between `scroll` and `auto` - would prefer `auto` as it means that scroll bars are only displayed when they are needed.

Comment (christianmemije) [reply kolibri/plugins/html5_app_renderer/assets/src/views/index.vue:86]: Sounds good!
