### PR TITLE
Fix bug where lesson active state was not properly conditionalized

### LINKED ISSUE #10236: Wrong modal is displayed when toggling off the 'Visible to learners' toggle
## Observed behavior
When I go to Coach > Plan > Lesson and I attempt to toggle off the 'Visible to learners' toggle I see the 'Make lesson visible' modal, while since I want to make it invisible the modal should be 'Make lesson not visible'. This is functioning correctly at Coach > Reports > Lessons

## Expected behavior
The correct modal should be displayed

## Steps to reproduce the issue
1. Install the the [following build ](https://buildkite.com/learningequality/kolibri-debian/builds/6281) 
2.  Coach > Plan > Lesson and I try to toggle off the 'Visible to learners' toggle
3. Observe the text of the displayed modal

## Video

https://user-images.githubusercontent.com/79847249/225036061-2af71d4e-b6f7-490b-b92b-1e367977ceb8.mp4

## Usage Details
Windows 10, Ubuntu 22  - Chrome

### PR DESCRIPTION
**Pull request by marcellamaki**
## Summary

Not actually a string regression, rather an uncaught bug, but... a quick fix! 

## References
Fixes #10236 

Now, a currently visible lesson under the "plan" tab displays the "make lesson not visible" state 

Screenshot 2023-03-14 at 2 12 46 PM

----

## Testing checklist

- [ ] Contributor has fully tested the PR manually
- [ ] If there are any front-end changes, before/after screenshots are included
- [ ] Critical user journeys are covered by Gherkin stories
- [ ] Critical and brittle code paths are covered by unit tests

## PR process

- [ ] PR has the correct target branch and milestone
- [ ] PR has 'needs review' or 'work-in-progress' label
- [ ] If PR is ready for review, a reviewer has been added. (Don't use 'Assignees')
- [ ] If this is an important user-facing change, PR or related issue has a 'changelog' label
- [ ] If this includes an internal dependency change, a link to the diff is provided

## Reviewer checklist

- Automated test coverage is satisfactory
- PR is fully functional
- PR has been tested for [accessibility regressions](http://kolibri-dev.readthedocs.io/en/develop/manual_testing.html#accessibility-a11y-testing)
- External dependency files were updated if necessary (`yarn` and `pip`)
- Documentation is updated
- Contributor is in AUTHORS.md

### CODE REVIEW

File: kolibri/plugins/coach/assets/src/views/common/LessonStatus.vue [hunk 1]
```diff
@@ -198,7 +198,7 @@
         const hideModalConfirmation = Lockr.get(LESSON_VISIBILITY_MODAL_DISMISSED);
         this.activeLesson = lesson;
         if (!hideModalConfirmation) {
-          if (lesson.active) {
+          if (lesson.active || lesson.is_active) {
```
Comment (rtibbles) [inline kolibri/plugins/coach/assets/src/views/common/LessonStatus.vue]: Hrm, there seem to be several references in the codebase to `lesson.active` and I don't know where that state might even be set. It seems like we should just generally clear these up and replace with `lesson.is_active` rather than having them live side by side?

**Review by rtibbles — CHANGES_REQUESTED** [review]
Let's clean this up properly!

**Review by rtibbles — APPROVED** [review]

**Comment by rtibbles** [comment]
Postgres test failure is, unsurprisingly, not caused by the code changes here, rather it's a flakey test.
