### PR TITLE
 Fixes a case where sidenav  is not working in special cases.

### LINKED ISSUE #10649: sidenav not working in special cases, triggered by facility plugin routing updates
## Observed behavior
The SideNav routing for the Facility plugin has undergone updates in order to fix a regression and introduce additional desired behavior (#10550). Those changes have led to unexpected behavior in SideNav in a specific case when a subtopic is selected (detailed in **_Steps to reproduce_**), leading to console errors & no navigation instead of re-rendering the page as expected, using the new params.

Problems similar to this have been raised & addressed on [vue-router's github](https://github.com/vuejs/vue-router/issues/2881#issuecomment-520554378) & stack overflow ([1](https://stackoverflow.com/questions/71874944/is-there-anyway-to-ignore-the-failure-avoided-redundant-navigation-to-current), [2](https://stackoverflow.com/questions/59428227/how-to-use-router-push-for-same-path-different-query-parameter-in-vue-js), [3](https://stackoverflow.com/questions/45432208/vue-router-same-route-with-different-param), [4](https://stackoverflow.com/questions/58560336/vue-router-push-with-same-route-but-different-parameters-how-to-trigger-trans)), but the current structure of our modules and the construction of their routes appears to make implementing these solutions difficult and hack-y. 

It would be helpful to invest a bit of thought or group discussion into addressing this root(& route) problem because the decisions made here about how to alter our routing approach will also have implications for the Coach plugin when similar routing updates are made there (#10650). 

https://user-images.githubusercontent.com/43046460/236602257-5149c528-cf12-4f96-a538-b3985ff4e7e2.mov

## Errors and logs
Screen Shot 2023-05-06 at 12 31 48 AM

## Expected behavior
When a user is on the "All Facilities" page, opens the SideNav, and selects a subtopic, the SideNav should automatically close and the "All Facilities" page should re-render with new links to each facility's page for the newly-selected subtopic.

## User-facing consequences
Navigation fails with no UI warning - unclear to users why no navigation or update has happened & are forced to use other workarounds to access subtopics in this situation (e.g. click on an available facility link -> once initial subtopic page loads, select the actual subtopic user wanted in the side- or topnav)

## Steps to reproduce
- must be multi-facility admin
- select a subtopic in the facility plugin in the sidenav
- should be redirected to the "All Facilities" page which has links to each facility's page for selected subtopic
- reopen the sidenav and select a different Facility subtopic
---> the page is not re-rendered with links to the new subtopic and an error appears in the console

## Context
MacOS Monterey - Chrome

### PR DESCRIPTION
**Pull request by AllanOXDi**
## Summary

This PR fixes redundant navigation waring issue   specifically triggered by facility plugin routing updates on the sidenav
### After
https://github.com/learningequality/kolibri/assets/103313919/d3fe70a7-b8a4-4e26-bf63-eb7cad6e5af9
## References
fixes [#10649](https://github.com/learningequality/kolibri/issues/10649)
## Reviewer guidance
- Navigate to facility and the click the side nave menus while your developer console is open

## Testing checklist

- [ ] Contributor has fully tested the PR manually
- [ ] If there are any front-end changes, before/after screenshots are included
- [ ] Critical user journeys are covered by Gherkin stories
- [ ] Critical and brittle code paths are covered by unit tests

## PR process

- [ ] PR has the correct target branch and milestone
- [ ] PR has 'needs review' or 'work-in-progress' label
- [ ] If PR is ready for review, a reviewer has been added. (Don't use 'Assignees')
- [ ] If this is an important user-facing change, PR or related issue has a 'changelog' label
- [ ] If this includes an internal dependency change, a link to the diff is provided

## Reviewer checklist

- Automated test coverage is satisfactory
- PR is fully functional
- PR has been tested for [accessibility regressions](http://kolibri-dev.readthedocs.io/en/develop/manual_testing.html#accessibility-a11y-testing)
- External dependency files were updated if necessary (`yarn` and `pip`)
- Documentation is updated
- Contributor is in AUTHORS.md

### CODE REVIEW

**Comment by AllanOXDi** [comment]
Okay on taking a second look. I think I have missed out one thing here . Marking it as a draft for now.

File: kolibri/plugins/facility/assets/src/routes.js [hunk 1]
```diff
@@ -24,21 +24,45 @@ import {
...
+      router.replace({
+        name: PageNames.ALL_FACILITIES_PAGE,
+        query: { subtopicName },
+        params: { subtopicName },
+      });
+      return true;
+    }
+    return false;
+  } else {
+    if (!toRoute.params.facility_id) {
```
Comment (rtibbles) [inline kolibri/plugins/facility/assets/src/routes.js]: This will catch the instance where the facility_id can indeed be optional - which is when the user is not a multi-facility admin, so this doesn't seem quite right. What behaviour is this meant to catch?

File: kolibri/plugins/facility/assets/src/routes.js [hunk 2]
```diff
@@ -24,21 +24,45 @@ import {
...
-    router.replace({
-      name: 'ALL_FACILITIES_PAGE',
-      params: { subtopicName },
-    });
-    return true;
+function facilityParamRequiredGuard(toRoute, fromRoute, subtopicName) {
+  if (
+    store.getters.userIsMultiFacilityAdmin &&
+    !toRoute.params.facility_id &&
+    fromRoute.query.subtopicName !== subtopicName
```
Comment (rtibbles) [inline kolibri/plugins/facility/assets/src/routes.js]: `fromRoute.query.subTopicName` will always be undefined, so this will always be true.

I don't think you need to make this comparison here at all...

File: kolibri/plugins/facility/assets/src/routes.js [hunk 3]
```diff
@@ -24,21 +24,45 @@ import {
...
+  ) {
+    const currentSubtopicName = toRoute.query.subtopicName;
+    if (currentSubtopicName !== subtopicName) {
```
Comment (rtibbles) [inline kolibri/plugins/facility/assets/src/routes.js]: The `toRoute` will never have a subtopicName because that's only a defined parameter for the ALL_FACILITIES page, which we are not using this guard on (and definitely shouldn't).

File: kolibri/plugins/facility/assets/src/routes.js [hunk 4]
```diff
@@ -24,21 +24,45 @@ import {
...
+      router.replace({
+        name: PageNames.ALL_FACILITIES_PAGE,
+        query: { subtopicName },
+        params: { subtopicName },
+      });
```
Comment (rtibbles) [inline kolibri/plugins/facility/assets/src/routes.js:42]: I think if you just catch the error from this `router.replace` that is all that is needed along with properly defining the `subtopicName` in the ALL_FACILITIES URL.

File: kolibri/plugins/facility/assets/src/routes.js [hunk 5]
```diff
@@ -24,21 +24,45 @@ import {
...
+    }
   }
 }
 
 export default [
   // Routes for multi-facility case
   {
     name: PageNames.ALL_FACILITIES_PAGE,
-    path: '/facilities',
+    path: '/:subtopicName?/facilities',
```
Comment (rtibbles) [inline kolibri/plugins/facility/assets/src/routes.js:51]: This is definitely needed here.

File: kolibri/core/assets/src/router.js [hunk 6]
```diff
@@ -86,7 +86,6 @@ class Router {
   replace(location, onComplete, onAbort) {
     return this._vueRouter.replace(location, onComplete, onAbort);
   }
-
```
Comment (rtibbles) [inline kolibri/core/assets/src/router.js]: Ideally, best not to commit diffs to files you've not ended up editing!

**Review by rtibbles — DISMISSED** [review]
I think the same could be achieved here with a simpler diff - I think the parameter guard function has got overly complex here.

**Review by thanksameeelian — DISMISSED** [review]
i think this is moving in a really good direction, and is looking much cleaner than previous iterations! :) 

i noticed that with these new changes, we've lost the ability to redirect to our original intended page after selecting a facility, and that's functionality that is important for us to retain. (e.g. working off your branch, when a multi-facility user clicks on "settings" and then selects a facility, they're no longer redirected to that facility's "settings" page the way a user would be on the current `develop` branch)


https://github.com/learningequality/kolibri/assets/43046460/29e4dd08-f138-4ece-81b2-db07dbff3e55



the redirect as it is written now is looking to `params` to know which page to redirect to. because you removed `params` on what was originally line 31, it's no longer functioning as intended.

i think the most straightforward solutions here are either to add `params: { subtopicName },` back into this file in the place it had been _or_ change the way we take in the redirect information to now look to `query` params instead of `params`.

File: kolibri/plugins/facility/assets/src/routes.js [hunk 7]
```diff
@@ -25,20 +26,28 @@ import {
 import { PageNames } from './constants';
 
 function facilityParamRequiredGuard(toRoute, subtopicName) {
+  const { isNavigationFailure, NavigationFailureType } = VueRouter;
   if (store.getters.userIsMultiFacilityAdmin && !toRoute.params.facility_id) {
-    router.replace({
-      name: 'ALL_FACILITIES_PAGE',
-      params: { subtopicName },
```
Comment (thanksameeelian) [inline kolibri/plugins/facility/assets/src/routes.js:31]: reintroducing this line here, `params: { subtopicName }`, should resolve the problem mentioned in my review comment

File: kolibri/plugins/facility/assets/src/routes.js [hunk 8]
```diff
@@ -25,20 +26,28 @@ import {
...
-    });
-    return true;
+    router
+      .replace({
+        name: 'ALL_FACILITIES_PAGE',
+        query: { subtopicName },
```
Comment (rtibbles) [inline kolibri/plugins/facility/assets/src/routes.js:34]: In case the above comment is unclear, this should be `params` in place of `query`.

File: kolibri/plugins/facility/assets/src/routes.js [hunk 9]
```diff
@@ -25,20 +26,28 @@ import {
...
+      })
+      .catch(e => {
+        if (!isNavigationFailure(e, NavigationFailureType.duplicated)) {
+          console.debug(e);
+          throw Error(e);
+        }
+      });
   }
+  return true;
```
Comment (rtibbles) [inline kolibri/plugins/facility/assets/src/routes.js]: This is now always returning `true` from this guard - regardless of whether the condition pertains or not - this should be inside the if statement.

File: kolibri/plugins/facility/assets/src/routes.js (hunk 8 above)
Comment (AllanOXDi) [reply kolibri/plugins/facility/assets/src/routes.js:34]: No, I addressed it .

**Review by thanksameeelian — COMMENTED** [review]
this is looking good to me, @AllanOXDi! i looked over the code and manually went through a lot of navigation paths between different classes, facilities, and subtopics, and it seemed to me like it was working as intended!

in terms of the specific initial problem this issue set out to solve, i noted that when i was on the "ALL FACILITIES" page and opened the sidenav and selected different subtopics, the facility links on the page would successfully update to the proper URLs & also not produce the previous console errors. yessss!!

would QA, @radinamatic & @pcenov, be able to take a look at this to confirm that the facility plugin routing (if you select a facility subtopic from the sidenav but are a multi-facility user and aren't currently inside a specific facility, you are redirected to the "ALL FACILITIES" page with the links to each facility resolving to the URL of that facility's page for the originally-selected subtopic) is working as we intend in both the multi-facility & single facility user use-cases.

**Comment by pcenov** [comment]
Hi @thanksameeelian and @AllanOXDi, I can confirm that there are no longer any errors in the console in the above mentioned scenarios.

Observed the following minor issues while manually testing this one:

1. In Internet Explorer 11 specifically the side bar doesn't close if I am already on one of the pages in Facility or Coach and I am trying to navigate to a different one.
2. In all supported browsers the side bar doesn't close if I am already on one of the pages in Coach and I am trying to navigate to a different one. Also all of the links 'Class home', 'Reports' and 'Plan' are displayed in bold as if they are selected.

Here's a video for both cases:

https://github.com/learningequality/kolibri/assets/79847249/c053eabe-f73f-4f65-9f48-ecfc8e73106b

**Comment by akolson** [comment]
Hi @pcenov! Just a heads up that in @AllanOXDi's absence, I will be stepping in to support this issue.

**Comment by thanksameeelian** [comment]
> Hi @thanksameeelian and @AllanOXDi, I can confirm that there are no longer any errors in the console in the above mentioned scenarios.
> 
> Observed the following minor issues while manually testing this one:
> 
> 1. In Internet Explorer 11 specifically the side bar doesn't close if I am already on one of the pages in Facility or Coach and I am trying to navigate to a different one.
> 2. In all supported browsers the side bar doesn't close if I am already on one of the pages in Coach and I am trying to navigate to a different one. Also all of the links 'Class home', 'Reports' and 'Plan' are displayed in bold as if they are selected.
> 
> Here's a video for both cases:
> 
>  2023-07-10_15-21-55.mp4

thank you so much @pcenov! because @AllanOXDi's away (and you can see that this PR has already inspired some healthy back-and-forth debate), after seeing your comments i chatted with @rtibbles & came to the conclusion that this specific PR can be merged and that i will attempt to address your concerns in my own upcoming PR that addresses this same sidebar navigation issue in `Coach` - this aforementioned PR should be ready for review in the next couple days. 

if i'm unable to address both of the bugs you caught in that PR, we could also make them into separate follow up issues to be taken on by @AllanOXDi, myself, or anyone else who's up for it! i plan on merging this PR but don't want to close down any discussion held here, so will be keeping an eye out for responses here & elsewhere!

**Review by thanksameeelian — APPROVED** [review]
looking good!

@pcenov's concerns to be addressed in upcoming `Coach`-specific sidenav work or separate follow-up issue(s)
