### PR TITLE
fix(qti-viewer): accessibility and maxChoices fixes for choice and text-entry interactions

### LINKED ISSUE #14347: [QTI Viewer] Accessibility and spec fixes for ChoiceInteraction, SimpleChoice, and TextEntryInteraction
🙂 Looking for an issue? Welcome! This issue is open for contribution. If this is the first time you’re requesting an issue, please:

- **Read <a href="https://learningequality.org/contributing-to-our-open-code-base/" target="_blank">Contributing guidelines</a>** carefully. **Pay extra attention to [Using generative AI](https://learningequality.org/contributing-to-our-open-code-base/#using-generative-ai)**. **Pull requests and comments that don’t follow the guidelines won’t be answered.**
- **Confirm that you’ve read the guidelines** in your comment.

## Overview

While reviewing the QTI viewer components, I found a few accessibility and specification issues in the following components:

- ChoiceInteraction.vue
- SimpleChoice.vue
- TextEntryInteraction.vue

These issues affect keyboard navigation, screen reader support, and correct enforcement of the QTI maxChoices constraint.

This issue proposes fixing them in a single small PR.

Related to: #11428 (QTI accessibility improvements)

### Context

During an audit of the QTI viewer, several gaps were identified that break keyboard accessibility and ignore QTI-specific constraints like maxChoices.

- Keyboard Navigation: Choice options (SimpleChoice.vue) lack tabindex, making them invisible to keyboard users and preventing interaction handlers from firing.
- ARIA Semantics: The ChoiceInteraction.vue list container lacks the role="listbox" needed to define the collection of options for screen readers.
- Specification Compliance: maxChoices is used to toggle multi-select mode but does not logically enforce the selection limit in toggleSelection.
- Form Accessibility: TextEntryInteraction.vue lacks an accessible name and basic interactive styling.

### Evidence

1. Keyboard Navigation Failure for ChoiceInteraction

Keyboard navigation skips the choice options because the `<li>` elements are not focusable.

Image

2. maxChoices Enforcement Failure

The interface allows selecting more options than specified by the `max-choices` attribute.

Image

3. TextEntry Interaction State

DevTools inspection shows that the rendered `<input>` element does not include an accessible name.

Image

Missing attributes:

- aria-label
- aria-labelledby

### Proposed Changes
- Add role="listbox" to the ul element in ChoiceInteraction.vue

- Enforce the maxChoices limit in toggleSelection

- Add tabindex="0" to SimpleChoice.vue list items

- Add visible focus styles for keyboard navigation

- Add an aria-label to the text entry input

- Disable browser autofill with autocomplete="off"

- Add basic styling for the interactive text entry input

### References

- **WAI-ARIA Listbox Role**  
  https://www.w3.org/TR/wai-aria-1.2/#listbox

- **WCAG Keyboard Accessibility (SC 2.1.1)**  
  https://www.w3.org/WAI/WCAG21/Understanding/keyboard.html

- **WCAG Name, Role, Value (SC 4.1.2)**  
  https://www.w3.org/WAI/WCAG21/Understanding/name-role-value.html

### PR DESCRIPTION
**Pull request by rajeshuchil**
### Summary

Fixes accessibility and spec-compliance issues in the QTI Viewer's choice and text-entry interactions (Issue #14347).

**Changes**

**ChoiceInteraction.vue**

- Add role="listbox" and aria-label="Answer choices" to the <ul> choices container (WCAG 1.3.1, 4.1.2)
- Add aria-multiselectable="true/false" based on whether maxChoices is 1 (single-select) or not
- Enforce the maxChoices constraint before state mutation in toggleSelection, so selecting beyond the limit silently no-ops                     instead of over-filling
- Add a watch on maxChoices to trim excess selections when the limit changes dynamically 
- Implement roving tabindex keyboard navigation  ArrowDown/Up moves focus between choices.
- Fix long-standing shuffle bug: typedProps.shuffle → typyedProps.shuffle.value (the old reference was always truthy, so shuffle never actually activated)
- Use shallowRef + selectionVersion counter to force reactive re-evaluation when the responses object is replaced wholesale (Vue 2 reactivity limitation)

**SimpleChoice.vue**

- Apply roving tabindex: :tabindex="isFocused ? 0 : -1" driven by isFocusTarget injected from parent
- Apply Kolibri's standard $coreOutline focus ring via $computedClass on :focus
- Sync focusedIndex back to the parent on native focus events

**TextEntryInteraction.vue**

- Add :aria-label with translated "Text entry" label bound to the native <input> (WCAG 4.1.2)
- Add autocomplete="off" to prevent browser autofill interfering with QTI responses

**Manual verification**

- Loaded a single-select item: keyboard ArrowDown/Up navigates options, Space/Enter selects, Tab leaves the widget. Focus ring is visible.
- Loaded a multi-select item (maxChoices=2): third click is blocked; reducing maxChoices to 1 in sandbox XML trims excess selection immediately.
- Loaded a textEntryInteraction item: input has visible border, aria-label "Text entry [identifier]", no autocomplete dropdown.
- Ran existing test suite: 62 tests pass across 2 suites.

**UI Evidence**

Keyboard navigation
keyboardnavigation

maxChoices enforcement
maxChoice

Shuffle behavior
shuffle

## References

Closes #14347 

**Reviewer guidance**

- Keyboard navigation: Open the QTI sandbox (/learn → any QTI item with choice interactions), focus the first choice with Tab,  then use ArrowDown/Up to move between options, Space to select. Verify focus ring appears.
- maxChoices enforcement: In the sandbox XML editor, set max-choices="2", select 2 options, attempt a 3rd — it should be ignored. Then set max-choices="1" — both selections should collapse to one.
- Shuffle fix: Set shuffle="true" in the XML — choices should appear in a different order on each page reload (was broken before this PR).
- Text entry: Focus the text input — it should show a clear border and an aria-label of "Text entry [responseIdentifier]" visible in the accessibility tree.

## AI usage
I used AI assistance to help draft and refine parts of the implementation. I reviewed all generated code critically, removed/adjusted unnecessary output, and manually verified behavior in the QTI sandbox keyboard navigation, selection constraints, focus visibility, and text-entry accessibility before submission.

### CODE REVIEW

File: kolibri/plugins/qti_viewer/frontend/components/interactions/SimpleChoice.vue [hunk 1]
```diff
@@ -55,10 +72,19 @@
         };
       });
 
+      // Define focus outline that matches Kolibri's standard
+      const coreOutline = {
+        outline: '3px solid rgb(51, 172, 245)',
```
Comment (rtibblesbot) [inline kolibri/plugins/qti_viewer/frontend/components/interactions/SimpleChoice.vue]: **blocking:** This hardcodes the focus outline color as `rgb(51, 172, 245)`. Every other component in the codebase uses the `$coreOutline` instance property provided by `KThemePlugin` — e.g., `':focus': this.$coreOutline` (see `CoreMenuOption.vue`, `CardLink.vue`, `TranscriptCue.vue`, etc.).

Hardcoding the color means this won't respond to theme changes and could drift out of sync with the rest of the app.

Since this is a Composition API `setup()` component, you can access it via the component instance proxy. You're already using `getCurrentInstance()` in ChoiceInteraction — same pattern here:

```js
const { proxy } = getCurrentInstance();
// then in the return:
coreOutline: proxy.$coreOutline,
```

Or access it from the template as `$coreOutline` directly:
```vue
':focus': $coreOutline,
```

File: kolibri/plugins/qti_viewer/frontend/components/interactions/TextEntryInteraction.vue [hunk 2]
```diff
@@ -82,13 +84,25 @@
...
   };
 
 </script>
 
 
 <style scoped>
 
+  .qti-text-entry-interaction {
+    padding: 4px 8px;
+    border: 1px solid;
```
Comment (rtibblesbot) [inline kolibri/plugins/qti_viewer/frontend/components/interactions/TextEntryInteraction.vue]: **blocking:** `border: 1px solid` without a color value inherits from the text color, which means it won't adapt to theme changes. Per the project convention (CLAUDE.md: "Use Theme Tokens, Not Hard-Coded Colors"), the border color should come from a theme token.

For example:
```css
border: 1px solid var(--some-token);
```
Or apply it dynamically via `:style` using `$themeTokens.fineLine` or `$themePalette.grey.v_400` (check which other input-like elements in the codebase use). The `QTISandboxPage.vue` in this same plugin uses hardcoded `#cccccc` borders, but that's the sandbox dev tool — this is a learner-facing component.

File: kolibri/plugins/qti_viewer/frontend/components/interactions/ChoiceInteraction.vue [hunk 3]
```diff
@@ -1,20 +1,36 @@
 <script>
 
   import get from 'lodash/get';
+  import isArray from 'lodash/isArray';
```
Comment (rtibblesbot) [inline kolibri/plugins/qti_viewer/frontend/components/interactions/ChoiceInteraction.vue]: **suggestion:** `lodash/isArray` is a polyfill for `Array.isArray` that hasn't been necessary since IE9. The rest of the QTI viewer already uses `Array.isArray` (e.g., `useTypedProps.js`). Consider using the native method to avoid the unnecessary import.

File: kolibri/plugins/qti_viewer/frontend/components/interactions/ChoiceInteraction.vue [hunk 4]
```diff
@@ -27,43 +43,144 @@
...
+
+      const isSelected = identifier => {
+        const variable = trackedVariable.value;
+        // eslint-disable-next-line no-unused-expressions
+        selectionVersion.value;
+        if (!variable || variable.value === null || variable.value === undefined) {
+          return false;
         }
-        return variable.value === identifier;
+        return getSelectionsArray(variable.value).includes(identifier);
```
Comment (rtibblesbot) [inline kolibri/plugins/qti_viewer/frontend/components/interactions/ChoiceInteraction.vue:59]: **suggestion:** `isSelected` wraps `variable.value` with `getSelectionsArray(...).includes(identifier)`, but `toggleSelection` also calls `getSelectionsArray` on the same value. This is fine for correctness, but the normalization in `isSelected` means the earlier null/undefined check on lines 62 is partially redundant — `getSelectionsArray(null).includes(x)` returns `false`. You could simplify to just:

```js
const isSelected = identifier => {
  const variable = trackedVariable.value;
  selectionVersion.value;
  if (!variable) return false;
  return getSelectionsArray(variable.value).includes(identifier);
};
```

File: kolibri/plugins/qti_viewer/frontend/components/interactions/ChoiceInteraction.vue [hunk 5]
```diff
@@ -27,43 +43,144 @@
...
+      provide('setFocusedIndex', identifier => {
+        const idx = orderedIdentifiers.value.indexOf(identifier);
+        if (idx >= 0) {
+          focusedIndex.value = idx;
+        }
+      });
 
       const getShuffledOrder = choices => {
-        if (!typedProps.shuffle) {
+        if (!typedProps.shuffle.value) {
```
Comment (rtibblesbot) [inline kolibri/plugins/qti_viewer/frontend/components/interactions/ChoiceInteraction.vue:99]: **praise:** Good catch fixing `typedProps.shuffle` → `typedProps.shuffle.value`. The old code was always truthy (the ref object itself), so shuffle never actually activated. Subtle bug, well spotted.

File: kolibri/plugins/qti_viewer/frontend/components/interactions/ChoiceInteraction.vue [hunk 6]
```diff
@@ -27,43 +43,144 @@
...
+            newIndex = count - 1;
+            break;
+          default:
+            // Don't prevent default for keys we don't handle
+            return;
+        }
+        event.preventDefault();
+        focusedIndex.value = newIndex;
+        const listEl = event.currentTarget;
+        const options = listEl.querySelectorAll('[role="option"]');
```
Comment (rtibblesbot) [inline kolibri/plugins/qti_viewer/frontend/components/interactions/ChoiceInteraction.vue]: **praise:** The roving tabindex implementation with ArrowDown/Up, Home/End, and wrapping is well-structured and follows the WAI-ARIA listbox keyboard interaction pattern correctly.

**Review by rtibblesbot — COMMENTED** [review]
Solid accessibility improvements for QTI choice and text-entry interactions — keyboard navigation, ARIA semantics, maxChoices enforcement, and the shuffle bug fix are all welcome.

CI passing. Screenshots show keyboard navigation, maxChoices enforcement, and shuffle behavior working correctly.

- **blocking:** Hardcoded focus outline color should use `$coreOutline` (SimpleChoice.vue)
- **blocking:** `border: 1px solid` without color should use a theme token (TextEntryInteraction.vue)
- **suggestion:** `lodash/isArray` → `Array.isArray` (ChoiceInteraction.vue)
- **suggestion:** `isArray` not needed in `isSelected` — `getSelectionsArray` already normalizes (ChoiceInteraction.vue)
- **praise:** Good shuffle bug fix and keyboard navigation implementation

---
_@rtibblesbot's comments are generated by an LLM, and should be evaluated accordingly_

<details><summary>How was this generated?</summary>

Reviewed the pull request diff checking for:
- **Correctness:** bugs, edge cases, undocumented behavior, resource leaks, hardcoded values
- **Design:** unnecessary complexity, naming, readability, comment accuracy, redundant state
- **Architecture:** duplicated concerns, minimal interfaces, composition over inheritance
- **Testing:** behavior-based assertions, mocks only at hard boundaries, accurate coverage
- **Completeness:** missing dependencies, unupdated usages, i18n, accessibility, security
- **Principles:** DRY (same reason to change), SRP, Rule of Three (no premature abstraction)
- Checked CI status and linked issue acceptance criteria
- For UI changes: inspected screenshots for layout, visual completeness, and consistency

</details>

File: kolibri/plugins/qti_viewer/frontend/components/interactions/SimpleChoice.vue [hunk 7]
```diff
@@ -35,15 +37,31 @@
     tag: 'qti-simple-choice',
 
     setup(props) {
+      const { proxy } = getCurrentInstance();
+      const outlineColor = proxy.$themeTokens.primary;
```
Comment (rtibblesbot) [inline kolibri/plugins/qti_viewer/frontend/components/interactions/SimpleChoice.vue]: **suggestion:** This uses `$themeTokens.primary` with a CSS custom property and `:focus-visible` for modality detection. It works, but it's inconsistent with the rest of the codebase — every other component uses `$coreOutline` via `$computedClass` (e.g., `ChannelCard.vue`, `CoreMenuOption.vue`, `CardLink.vue`). TextEntryInteraction in this same PR also uses `$coreOutline`.

`$coreOutline` differs in two ways: it uses the theme's designated outline color (not `primary`), and it uses JS-based input modality detection rather than `:focus-visible`. Consider aligning with the established pattern:

```js
// Remove outlineColor, add to $computedClass in template:
$computedClass({
  '::before': { ... },
  ':focus': $coreOutline,
})
```

This would also let you remove the `&:focus` / `&:focus:not(:focus-visible)` CSS rules and the `--focus-color` custom property.

File: kolibri/plugins/qti_viewer/frontend/components/interactions/TextEntryInteraction.vue [hunk 8]
```diff
@@ -3,13 +3,16 @@
   <input
     v-if="interactive"
     v-model="variable"
-    class="qti-text-entry-interaction"
+    :class="['qti-text-entry-interaction', $computedClass({ ':focus': coreOutline })]"
```
Comment (rtibblesbot) [inline kolibri/plugins/qti_viewer/frontend/components/interactions/TextEntryInteraction.vue]: **praise:** Good use of `$coreOutline` via `$computedClass` here — consistent with the codebase pattern and input-modality aware.

File: kolibri/plugins/qti_viewer/frontend/components/interactions/ChoiceInteraction.vue [hunk 9]
```diff
@@ -27,43 +52,144 @@
...
+      provide('setFocusedIndex', identifier => {
+        const idx = orderedIdentifiers.value.indexOf(identifier);
+        if (idx >= 0) {
+          focusedIndex.value = idx;
+        }
+      });
 
       const getShuffledOrder = choices => {
-        if (!typedProps.shuffle) {
+        if (!typedProps.shuffle.value) {
```
Comment (rtibblesbot) [inline kolibri/plugins/qti_viewer/frontend/components/interactions/ChoiceInteraction.vue:99]: **praise:** The shuffle bug fix (`typedProps.shuffle` → `typedProps.shuffle.value`) and the roving tabindex keyboard navigation are both well-implemented. The `orderedIdentifiers` sync logic with the initial-render vs nextTick distinction is a thoughtful solution to the Vue 2 render-loop problem.

**Review by rtibblesbot — COMMENTED** [review]
Re-review after ae4cd161. All four prior findings addressed.

CI passing. Screenshots show keyboard navigation, maxChoices enforcement, and shuffle working. PR targets `develop` (default branch); new strings are appropriate.

**Prior findings:**
- Hardcoded focus outline color (SimpleChoice.vue): ACKNOWLEDGED — hardcoded `rgb()` removed, now uses `$themeTokens.primary` via CSS custom property. Downgraded to suggestion below since the original theming concern is resolved, but approach differs from codebase pattern.
- `border: 1px solid` without color (TextEntryInteraction.vue): RESOLVED — now uses `$themeTokens.fineLine`
- `lodash/isArray` → `Array.isArray`: RESOLVED
- Simplify `isSelected`: RESOLVED

**New findings:**
- **suggestion:** SimpleChoice focus approach inconsistent with `$coreOutline` pattern used elsewhere (and in TextEntryInteraction in this same PR)
- **praise:** TextEntryInteraction now correctly uses `$coreOutline` and `$themeTokens.fineLine`
- **praise:** All acceptance criteria from #14347 met

---
_@rtibblesbot's comments are generated by an LLM, and should be evaluated accordingly_

<details><summary>How was this generated?</summary>

Compared the current PR state against findings from a prior review:
- Retrieved prior bot reviews deterministically via the GitHub API
- Classified each prior finding as RESOLVED, UNADDRESSED, ACKNOWLEDGED, or CONTESTED
- Only raised NEW findings for newly introduced code
- Reviewed the pull request diff checking for correctness, design, architecture, testing, completeness, and adherence to DRY/SRP principles
- Checked CI status and linked issue acceptance criteria

</details>

**Comment by rajeshuchil** [comment]
Hi @rtibbles I’ve addressed the blocking issues raised in the previous review and pushed the fixes. The PR should now resolve the accessibility and maxChoices issues, I’d appreciate a review when you have time. Thanks!

File: kolibri/plugins/qti_viewer/frontend/components/interactions/SimpleChoice.vue (hunk 7 above)
Comment (rajeshuchil) [reply kolibri/plugins/qti_viewer/frontend/components/interactions/SimpleChoice.vue]: I’ve reviewed the suggestion to use $coreOutline within $computedClass. While I agree that it aligns better with the codebase patterns, I've had to revert to the current implementation because the suggested approach caused a rendering regression where the choice options became invisible in the UI. Given that the current fix meets accessibility requirements and maintains UI stability

File: kolibri/plugins/qti_viewer/frontend/components/interactions/ChoiceInteraction.vue [hunk 10]
```diff
@@ -27,43 +52,144 @@
         return typedProps.maxChoices.value !== 1;
       });
 
-      const isSelected = identifier => {
+      // shallowRef wrapper so computeds re-evaluate when the underlying
```
Comment (rtibbles) [inline kolibri/plugins/qti_viewer/frontend/components/interactions/ChoiceInteraction.vue]: This feels like the wrong layer to make this change. The issue here is that the responses object is not reactively updating, so we should fix that, rather than add extra wrapping here.

File: kolibri/plugins/qti_viewer/frontend/components/interactions/SimpleChoice.vue [hunk 11]
```diff
@@ -35,15 +37,31 @@
     tag: 'qti-simple-choice',
 
     setup(props) {
+      const { proxy } = getCurrentInstance();
```
Comment (rtibbles) [inline kolibri/plugins/qti_viewer/frontend/components/interactions/SimpleChoice.vue]: I know it gets used in other parts of the codebase, but getCurrentInstance is an anti-pattern (see reasoning from the Vue creator here: https://github.com/vuejs/docs/issues/1422#issuecomment-1032120675 ) - so I'd rather we avoid this here and below.

theme tokens are already available in _this_ file in the module scope, so reading them off the proxy here seems like the existing code has not been read as well as it could have been.

File: kolibri/plugins/qti_viewer/frontend/components/interactions/SimpleChoice.vue (hunk 7 above)
Comment (rtibbles) [reply kolibri/plugins/qti_viewer/frontend/components/interactions/SimpleChoice.vue]: It does indeed align with the patterns, and we should use it.

File: kolibri/plugins/qti_viewer/frontend/components/interactions/TextEntryInteraction.vue [hunk 12]
```diff
@@ -39,6 +42,7 @@
     tag: 'qti-text-entry-interaction',
 
     setup(props) {
+      const { proxy } = getCurrentInstance();
```
Comment (rtibbles) [inline kolibri/plugins/qti_viewer/frontend/components/interactions/TextEntryInteraction.vue]: Can remove this here too and just use a direct KDS import for the value below.

File: kolibri/plugins/qti_viewer/frontend/components/interactions/TextEntryInteraction.vue [hunk 13]
```diff
@@ -3,13 +3,16 @@
   <input
     v-if="interactive"
     v-model="variable"
-    class="qti-text-entry-interaction"
+    :class="['qti-text-entry-interaction', $computedClass({ ':focus': coreOutline })]"
+    :aria-label="`${$tr('textEntryLabel')} ${responseIdentifier}`"
```
Comment (rtibbles) [inline kolibri/plugins/qti_viewer/frontend/components/interactions/TextEntryInteraction.vue]: We should use a placeholder in the ICU string definition directly rather than concatenating here.

File: kolibri/plugins/qti_viewer/frontend/components/interactions/SimpleChoice.vue [hunk 14]
```diff
@@ -82,6 +103,15 @@
     border-radius: 8px;
     transition: all 0.3s ease;
 
+    &:focus {
+      outline: 3px solid var(--focus-color);
```
Comment (rtibbles) [inline kolibri/plugins/qti_viewer/frontend/components/interactions/SimpleChoice.vue]: Noting that we currently can't use CSS variables because of our browser support - this may change in time for this code to be released, but it's important to pay attention to codebase norms for these kinds of things.

File: kolibri/plugins/qti_viewer/frontend/components/interactions/ChoiceInteraction.vue [hunk 15]
```diff
@@ -136,6 +291,12 @@
       },
       /* eslint-enable */
     },
+    $trs: {
```
Comment (rtibbles) [inline kolibri/plugins/qti_viewer/frontend/components/interactions/ChoiceInteraction.vue]: Can avoid use of the proxy here by instead defining this string with a `createTranslator` object from the kolibri/utils/i18n module.

File: kolibri/plugins/qti_viewer/frontend/components/interactions/ChoiceInteraction.vue [hunk 16]
```diff
@@ -27,43 +52,144 @@
...
+          if (newMax > 0 && selections.length > newMax) {
+            variable.value = multiSelectable.value
+              ? selections.slice(0, newMax)
+              : selections[0] || null;
+            selectionVersion.value++;
+          }
+        },
+      );
+
+      // Roving tabindex: only one option has tabindex="0" at a time;
```
Comment (rtibbles) [inline kolibri/plugins/qti_viewer/frontend/components/interactions/ChoiceInteraction.vue]: I am confused by this implementation - this is not what was specified in the issue at all. In the issue the proposal was simply to ensure that every `li` element had tabindex 0, but this is doing something quite different.

**Review by rtibbles — CHANGES_REQUESTED** [review]
Implementation seems to have spiralled into something rather complex, and the explicit tracking of a non-reactive value is adding a lot of complexity.

I would suggest that we just don't address the reactivity issue in the scope of this PR, because it only affects the QTI Sandbox for now, not production usage.

Everything else should be simplified and pared back to what was described in the issue.

A reminder of what was there:

> Add role="listbox" to the ul element in ChoiceInteraction.vue
> 
> Enforce the maxChoices limit in toggleSelection
> 
> Add tabindex="0" to SimpleChoice.vue list items
> 
> Add visible focus styles for keyboard navigation
> 
> Add an aria-label to the text entry input
> 
> Disable browser autofill with autocomplete="off"
> 
> Add basic styling for the interactive text entry input
> 
>

File: kolibri/plugins/qti_viewer/frontend/components/interactions/TextEntryInteraction.vue (hunk 13 above)
Comment (rajeshuchil) [reply kolibri/plugins/qti_viewer/frontend/components/interactions/TextEntryInteraction.vue]: Fixed. I’ve updated the createTranslator definition to include the {identifier} placeholder and passed the variable through the translator function

**Comment by rajeshuchil** [comment]
Hi @rtibbles, I have pushed the refactored code to strictly align with my proposed solution and your feedback and didnt address the reactivity issues 
I apologize for the confusion there. While working on the file, I had started exploring Up/Down arrow key navigation for better screen reader flow, which is why I initially introduced the roving focus and the extra reactivity logic. I've now undone those changes to keep this PR focused and maintainable. I'll stick strictly to the issue scope moving forward

File: kolibri/plugins/qti_viewer/frontend/components/interactions/SimpleChoice.vue (hunk 11 above)
Comment (rajeshuchil) [reply kolibri/plugins/qti_viewer/frontend/components/interactions/SimpleChoice.vue]: Removed getCurrentInstance() and I'm importing themeTokens at the module scope now.

File: kolibri/plugins/qti_viewer/frontend/components/interactions/SimpleChoice.vue (hunk 14 above)
Comment (rajeshuchil) [reply kolibri/plugins/qti_viewer/frontend/components/interactions/SimpleChoice.vue]: Replaced CSS variables with $computedClass to handle the focus styles dynamically without relying on CSS vars.

File: kolibri/plugins/qti_viewer/frontend/components/interactions/ChoiceInteraction.vue (hunk 16 above)
Comment (rajeshuchil) [reply kolibri/plugins/qti_viewer/frontend/components/interactions/ChoiceInteraction.vue]: Reverted. I got a little too ambitious trying to add Up/Down arrow navigation. Simplified it to just a tabindex='0' on every li as originally requested.

File: kolibri/plugins/qti_viewer/frontend/components/interactions/ChoiceInteraction.vue [hunk 17]
```diff
@@ -3,24 +3,45 @@
...
   import useTypedProps from '../../composables/useTypedProps';
 
+  const strings = createTranslator('ChoiceInteractionStrings', {
+    choiceListLabel: {
+      message: 'Answer choices',
+      context: 'Accessible label for the list of answer choices in an assessment question',
+    },
+  });
+
+  const { choiceListLabel$ } = strings;
```
Comment (rtibblesbot) [inline kolibri/plugins/qti_viewer/frontend/components/interactions/ChoiceInteraction.vue:17]: **praise:** Good use of `createTranslator` at module scope with proper destructuring — consistent with the codebase pattern for i18n in Composition API components.

File: kolibri/plugins/qti_viewer/frontend/components/interactions/ChoiceInteraction.vue [hunk 18]
```diff
@@ -44,26 +62,37 @@
...
-          variable.value = multiSelectable.value
-            ? [...(variable.value || []), identifier]
-            : identifier;
+          if (multiSelectable.value) {
+            const maxChoices = typedProps.maxChoices.value;
+            const currentSelections = getSelectionsArray(variable.value);
+            if (maxChoices > 0 && currentSelections.length >= maxChoices) {
+              return false;
+            }
+            variable.value = [...currentSelections, identifier];
```
Comment (rtibblesbot) [inline kolibri/plugins/qti_viewer/frontend/components/interactions/ChoiceInteraction.vue:85]: **praise:** The `maxChoices` enforcement is well-structured — `maxChoices > 0` correctly treats 0 as unlimited per the QTI spec, and the guard prevents over-selection cleanly.

File: kolibri/plugins/qti_viewer/frontend/components/interactions/TextEntryInteraction.vue [hunk 19]
```diff
@@ -65,10 +81,13 @@
       });
 
       return {
+        $themeTokens,
+        textEntryLabel$,
         variable,
         placeholder: typedProps.placeholderText,
         interactive,
         inputType,
+        coreOutline: themeOutlineStyle(),
```
Comment (rtibblesbot) [inline kolibri/plugins/qti_viewer/frontend/components/interactions/TextEntryInteraction.vue:159]: **praise:** Using `themeOutlineStyle()` here aligns with the established `$coreOutline` pattern. This is the right approach.

**Review by rtibblesbot — COMMENTED** [review]
Re-review after simplification per maintainer feedback. Implementation is now clean and focused on the issue scope.

CI passing. PR targets `develop` (default branch); new i18n strings are appropriate for the accessibility labels specified in the issue.

**Prior findings (review 1):**
- RESOLVED: Hardcoded focus outline color (SimpleChoice.vue) — now uses `$themeTokens.primary` via `$computedClass`
- RESOLVED: `border: 1px solid` without color (TextEntryInteraction.vue) — now uses `$themeTokens.fineLine`
- RESOLVED: `lodash/isArray` replaced with `Array.isArray`
- RESOLVED: `isSelected` simplified with `getSelectionsArray`

**Prior findings (review 2):**
- ACKNOWLEDGED: SimpleChoice focus style not using `$coreOutline` — maintainer confirmed it should be used; author reported a rendering regression when attempting `$coreOutline` via `$computedClass`. Direction established between maintainer and author.

**New findings:**
- **praise:** Clean `getSelectionsArray` normalizer and well-structured `maxChoices` enforcement (ChoiceInteraction.vue)
- **praise:** TextEntryInteraction correctly uses `themeOutlineStyle()` and `$themeTokens.fineLine`
- **praise:** Good simplification — removed roving tabindex, `getCurrentInstance()`, and CSS variables per maintainer feedback

---
_@rtibblesbot's comments are generated by an LLM, and should be evaluated accordingly_

<details><summary>How was this generated?</summary>

Compared the current PR state against findings from a prior review:
- Retrieved prior bot reviews deterministically via the GitHub API
- Classified each prior finding as RESOLVED, UNADDRESSED, ACKNOWLEDGED, or CONTESTED
- Only raised NEW findings for newly introduced code
- Reviewed the pull request diff checking for correctness, design, architecture, testing, completeness, and adherence to DRY/SRP principles
- Checked CI status and linked issue acceptance criteria

</details>

File: kolibri/plugins/qti_viewer/frontend/components/interactions/ChoiceInteraction.vue [hunk 20]
```diff
@@ -3,24 +3,45 @@
...
+    return [value];
+  }
+
   export default {
     name: 'QtiChoiceInteraction',
     tag: 'qti-choice-interaction',
 
     setup(props, { slots, attrs }) {
       const responses = inject('responses');
-
```
Comment (rtibbles) [inline kolibri/plugins/qti_viewer/frontend/components/interactions/ChoiceInteraction.vue:19]: Let's make sure to remove all non-essential changes from the diff - this kind of churn is not very helpful.

File: kolibri/plugins/qti_viewer/frontend/components/interactions/ChoiceInteraction.vue [hunk 21]
```diff
@@ -44,26 +62,37 @@
...
+            variable.value = [...currentSelections, identifier];
+          } else {
+            variable.value = identifier;
+          }
         }
 
         return true;
       };
 
-      // Provide functions to child components
```
Comment (rtibbles) [inline kolibri/plugins/qti_viewer/frontend/components/interactions/ChoiceInteraction.vue:61]: Why are code comments being removed?

File: kolibri/plugins/qti_viewer/frontend/components/interactions/ChoiceInteraction.vue [hunk 22]
```diff
@@ -85,7 +114,6 @@
         return result;
       };
 
-      // Return render function
```
Comment (rtibbles) [inline kolibri/plugins/qti_viewer/frontend/components/interactions/ChoiceInteraction.vue:88]: And again here.

File: kolibri/plugins/qti_viewer/frontend/components/interactions/ChoiceInteraction.vue [hunk 23]
```diff
@@ -113,14 +141,15 @@
...
+              'aria-label': choiceListLabel$(),
               'aria-multiselectable': multiSelectable.value,
-              class: (attrs.class || '') + ' qti-choice-interaction',
             },
+            class: [attrs.class || '', 'qti-choice-interaction'],
           },
           orderedChoices.map(choice => choice.vnode),
         );
 
-        // Create container with non-choice content first, then choices list
```
Comment (rtibbles) [inline kolibri/plugins/qti_viewer/frontend/components/interactions/ChoiceInteraction.vue:123]: Also here.

File: kolibri/plugins/qti_viewer/frontend/components/interactions/SimpleChoice.vue [hunk 24]
```diff
@@ -3,15 +3,20 @@
...
-    :class="
+    tabindex="0"
+    :class="[
       $computedClass({
         '::before': {
           border: `2px solid ${selected ? $themeTokens.textInverted : $themeTokens.annotation}`,
         },
-      })
-    "
+        ':focus': {
```
Comment (rtibbles) [inline kolibri/plugins/qti_viewer/frontend/components/interactions/SimpleChoice.vue]: This should be `coreOutline` here too, as you have used in the TextEntryInteraction. You suggested earlier that using it caused a "rendering regression" - but didn't specify what - if it does cause an issue we should look at how to adjust where and how the style is applied, not change the style that is applied.

**Review by rtibbles — CHANGES_REQUESTED** [review]
This is much more tightly scoped - but still has quite a few unnecessary edits, and not clear why coreOutline is not being used in SimpleChoice still.

**Comment by rajeshuchil** [comment]
@rtibbles Thanks for the review, i have cleaned up the diff and restored the removed comments also updated SimpleChoice to use coreOutline consistently with TextEntryInteraction.

File: kolibri/plugins/qti_viewer/frontend/components/interactions/SimpleChoice.vue [hunk 25]
```diff
@@ -3,15 +3,17 @@
...
-    :class="
+    tabindex="0"
+    :class="[
       $computedClass({
         '::before': {
           border: `2px solid ${selected ? $themeTokens.textInverted : $themeTokens.annotation}`,
         },
-      })
-    "
+        ':focus': coreOutline,
```
Comment (rtibblesbot) [inline kolibri/plugins/qti_viewer/frontend/components/interactions/SimpleChoice.vue:12]: **praise:** Good adoption of `themeOutlineStyle()` here — consistent with TextEntryInteraction and the broader codebase pattern, as the maintainer requested.

**Review by rtibblesbot — APPROVED** [review]
Re-review after 6e2bf654. All maintainer feedback addressed — comments restored, diff cleaned up, `coreOutline` now used consistently in both SimpleChoice and TextEntryInteraction.

CI passing. PR targets `develop` (default branch); new i18n strings are appropriate for the accessibility labels.

### Prior findings

All 5 prior findings remain resolved — no changes since last review. The one previously ACKNOWLEDGED finding (SimpleChoice focus style not using `$coreOutline`) is now RESOLVED via `themeOutlineStyle()` import.

- **praise:** Clean resolution of the `$coreOutline` consistency issue across both SimpleChoice and TextEntryInteraction
- **praise:** `getSelectionsArray` normalizer and `maxChoices` enforcement are well-structured

---
_@rtibblesbot's comments are generated by an LLM, and should be evaluated accordingly_

<details><summary>How was this generated?</summary>

Compared the current PR state against findings from a prior review:
- Retrieved prior bot reviews deterministically via the GitHub API
- Classified each prior finding as RESOLVED, UNADDRESSED, ACKNOWLEDGED, or CONTESTED
- Only raised NEW findings for newly introduced code
- Reviewed the pull request diff checking for correctness, design, architecture, testing, completeness, and adherence to DRY/SRP principles
- Checked CI status and linked issue acceptance criteria

</details>

File: kolibri/plugins/qti_viewer/frontend/components/interactions/ChoiceInteraction.vue (hunk 20 above)
Comment (rtibbles) [reply kolibri/plugins/qti_viewer/frontend/components/interactions/ChoiceInteraction.vue:19]: These are still here?

File: kolibri/plugins/qti_viewer/frontend/components/interactions/SimpleChoice.vue [hunk 26]
```diff
@@ -82,6 +87,10 @@
     border-radius: 8px;
     transition: all 0.3s ease;
 
+    &:focus:not(:focus-visible) {
```
Comment (rtibbles) [inline kolibri/plugins/qti_viewer/frontend/components/interactions/SimpleChoice.vue]: focus-visible is only supported on newer browsers than Kolibri's browser range. I am not entirely sure what the interaction will be when the pseudo selector is not available, so I think it would be safer to remove this rather than risk not doing a focus outline on older browsers.

**Review by rtibbles — COMMENTED** [review]
Still a little bit of churn to revert, and unnecessary addition of focus-visible selector - I think by our keyboard modality outline, we are already achieving most of what this aims to achieve, so the additional uncertainty about older browsers is unnecessary.

File: kolibri/plugins/qti_viewer/frontend/components/interactions/SimpleChoice.vue (hunk 26 above)
Comment (rajeshuchil) [reply kolibri/plugins/qti_viewer/frontend/components/interactions/SimpleChoice.vue]: I added :focus-visible to try and improve focus styling for keyboard users, but I see your point about browser support and consistency with existing patterns. I’ll remove it and revert to the standard approach

**Comment by rajeshuchil** [comment]
@rtibbles I've removed the :focus-visible selector and cleaned up the remaining churn.

**Comment by radinamatic** [comment]
Keyboard navigation among the options, and selecting them in **Single choice**, **Multiple choice** and the **True/False** questions is now working correctly.

One thing I find questionable is the same color choice for the background of the *selected* answer(s), as the color of the visual focus outline for whichever option is currently _in focus_. That makes it difficult to distinguish and confusing, can we use different colors for these?

outline-selected-same color

------

What is even more problematic is the screen reader output when the input field is in focus:

input-field-sr-output

NVDA output for the above numeric input field is:

``Text entry RESPONSE  spin button  editable  Enter your answer here  [object object] (not supported)  blank``

1. `Text entry RESPONSE` is not the best choice for `aria-label`, I suggest changing it to simply `Your answer`.
2. First I was wondering why is NVDA now also announcing _Enter your answer here_, since `aria-label` takes precedence over `placeholder`, and then discovered another attribute there: `placeholder-text="Enter your answer here"` 😳 
What purpose does this serve if there's already a `placeholder`...?
3. I am at loss where does the `[object object] (not supported)` part come from (maybe from the container `div`...?), but it definitely should not be in the screen reader output for the input field.

I would expect NVDA output to be:
* `Your answer spin button  editable  blank` for the numeric input field (when empty), and 
* `Your answer  edit  blank` for the free response field (when empty).

**Comment by rajeshuchil** [comment]
@radinamatic thanks for the reveiw ma'am,
1. I’ll update it to “Your answer”. 

2. I looked into the placeholder-text attribute, and it wasn’t introduced in my changes. It already exists in the QTI data and has been part of TextEntryInteraction since the initial implementation. It’s mapped internally to the native placeholder, but due to attribute forwarding, the original placeholder-text is also ending up on the input. This likely explains why NVDA is announcing “Enter your answer here” in addition to the label.

 3. For the [object Object] (not supported) output, my understanding is that it’s likely caused by unexpected attributes being passed down to the input, which NVDA cannot interpret correctly. So this seems to be a side effect of attribute fallthrough rather than a specific single attribute. 
 
 To address the root issuefor [object object ], I’m planning to use inheritAttrs: false and explicitly pass only the intended attributes (aria-label, placeholder, type, etc.) to the <input>. This should prevent attributes like placeholder-text from reaching the DOM
 
 Does this approach look correct?

**Comment by rtibbles** [comment]
> Does this approach look correct?

Yes, that seems right - `placeholder-text` is the attribute name on the XML, so it is being passed in as is, but preventing the inheritAttrs when we are specifically capturing and remapping these seems appropriate.

**Comment by rajeshuchil** [comment]
Sorry for the delay, I was tied up with proposal work, but I’ll push the fix soon.

**Comment by rtibbles** [comment]
No worries, @rajeshuchil thanks for coming back to it!

**Comment by rajeshuchil** [comment]
1. Updated the aria-label to “Your answer”
2. Stopped placeholder-text from reaching the DOM so no duplicate announcement
3. Filtered out non-primitive attributes to fix the [object Object] issue
4. Checked the focus vs selected styles selected uses primary background and focus uses outline, so they’re visually distinguishable now

Sharing screenshots below for reference.
image
image

**Comment by rajeshuchil** [comment]
Hi @rtibbles , I’ve completed the updates and pushed the changes. Please let me know  if there’s anything else you’d like me to improve.

**Comment by radinamatic** [comment]
Re-tested with the most recent asset:

* `aria-label` now reads as “Your answer”, and focus outline is improved ✅ 
* `placeholder-text` seems to be hidden properly (my NVDA apparently still reads the default placeholder, but it could be something in my settings, so let's leave it as is)
* however, `[object object] (not supported)` attributes are still there 😕  

numeric input field | free response field 
-- | --
Win11 (start)  Running  - Oracle VirtualBox_012 | Win11 (start)  Running  - Oracle VirtualBox_015

**Comment by rajeshuchil** [comment]
Thanks for re-testing!

I’ve tested again with NVDA and attached a screenshot of the current output. The [object Object] (not supported) issue no longer appears, and the aria-label now reads correctly as “Your answer”.

From my testing, the issue seems to be resolved. Please let me know if you're still able to reproduce it on your end or if there are specific cases I should check further.

image

**Comment by radinamatic** [comment]
Great! This latest asset had the cleanest NVDA output, good job! 💯 

Win10 (start)  Running  - Oracle VirtualBox_015

**Review by radinamatic — APPROVED** [review]
LGTM, thank you @rajeshuchil ! 💯 🎉 :shipit:

**Review by rtibbles — APPROVED** [review]
All comments addressed and manual QA checks out - thanks @rajeshuchil!
