### PR TITLE
Change template for personal facility name to "Home facility for {name}"

### LINKED ISSUE #7152: auto-generated facility names are not well-formatted
### Observed behavior

it appears that we concatenate two strings together with a space:

image

### Expected behavior

strings should be concatenated with a ` - ` or similar

### Steps to reproduce

create a facility using the basic flow

### Context

0.14.0 beta 3

### PR DESCRIPTION
**Pull request by jonboiser**
### Summary

When using the Personal Use/Quick Start Setup Wizard path, this changes the template for the default facility name from:

"Home Facility [admin's full name]"

To 

"Home Facility **for** [admin's full name]"

So it reads better in the Facility Syncing flows.

### Reviewer guidance

To test, go through [this gherkin](https://github.com/jonboiser/kolibri/blob/4238156726800498a23b4aae66568d418178e9b2/integration_testing/features/super-admin/super-admin-quick-start-setup-wizard.feature#L1), on the "Personal setup" scenario.

You can verify the new name by going to `Device > Facilities`. The default name should be shown:

CleanShot 2021-03-30 at 14 41 13

### References

Fixes #7152 

----

### Contributor Checklist

PR process:

- [x] PR has the correct target branch and milestone
- [x] PR has 'needs review' or 'work-in-progress' label
- [x] If PR is ready for review, a reviewer has been added. (Don't use 'Assignees')
- [x] If this is an important user-facing change, PR or related issue has a 'changelog' label
- [ ] If this includes an internal dependency change, a link to the diff is provided

Testing:

- [ ] Contributor has fully tested the PR manually
- [ ] If there are any front-end changes, before/after screenshots are included
- [ ] Critical user journeys are covered by Gherkin stories
- [ ] Critical and brittle code paths are covered by unit tests

### Reviewer Checklist

- Automated test coverage is satisfactory
- PR is fully functional
- PR has been tested for [accessibility regressions](http://kolibri-dev.readthedocs.io/en/develop/manual_testing.html#accessibility-a11y-testing)
- External dependency files were updated if necessary (`yarn` and `pip`)
- Documentation is updated
- Contributor is in AUTHORS.md

### CODE REVIEW

**Comment by pcenov** [comment]
@jonboiser today I tested this locally and I confirm that the text is now "Home Facility for [admin's full name]". My only question is how is this going to be handled for the other supported languages? For example if I select Spanish as the default language for Kolibri and continue with the setup wizard the text is "Kolibri de mi casa [admin's full name]".

**Comment by radinamatic** [comment]
This PR is targeting `develop` branch which will become 0.15.x soon, so this string change is going to be included in the string audit, freeze and localization for the Kolibri version 0.15 🙂

File: kolibri/plugins/setup_wizard/assets/src/modules/pluginModule.js [hunk 1]
```diff
@@ -6,7 +6,7 @@ import { FacilityImportResource } from '../api';
 
 const SetupStrings = createTranslator('SetupStrings', {
   personalFacilityName: {
-    message: 'Home Facility {name}',
+    message: 'Home Facility for {name}',
```
Comment (indirectlylit) [inline kolibri/plugins/setup_wizard/assets/src/modules/pluginModule.js:9]: This should be:

```
Home facility for '{name}'
```

From the [design system](https://design-system.learningequality.org/writing/#notes):

> Always wrap user-generated text in 'single quotes'.


and 

> "You are a coach", not "You are a Coach"
