### PR TITLE
Static network device form error handling updates

### LINKED ISSUE #10267: Server error when adding static network device
## Observed behavior

I accidentally swapped the address and name when manually adding a network address for a device, and it produced a 500 error which broke the form (wouldn't submit again)

## Errors and logs

```
ERROR    2023-03-16 10:45:51,888 Internal Server Error: /api/discovery/staticnetworklocation/
Traceback (most recent call last):
  File "/home/bjester/Projects/learningequality/pyenv/versions/3.9.13/envs/kolibri-3.9.13/lib/python3.9/site-packages/django/core/handlers/exception.py", line 41, in inner
    response = get_response(request)
  File "/home/bjester/Projects/learningequality/pyenv/versions/3.9.13/envs/kolibri-3.9.13/lib/python3.9/site-packages/django/core/handlers/base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/home/bjester/Projects/learningequality/pyenv/versions/3.9.13/envs/kolibri-3.9.13/lib/python3.9/site-packages/django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/bjester/Projects/learningequality/pyenv/versions/3.9.13/envs/kolibri-3.9.13/lib/python3.9/site-packages/django/views/decorators/csrf.py", line 58, in wrapped_view
    return view_func(*args, **kwargs)
  File "/home/bjester/Projects/learningequality/pyenv/versions/3.9.13/envs/kolibri-3.9.13/lib/python3.9/site-packages/rest_framework/viewsets.py", line 116, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/bjester/Projects/learningequality/pyenv/versions/3.9.13/envs/kolibri-3.9.13/lib/python3.9/site-packages/rest_framework/views.py", line 495, in dispatch
    response = self.handle_exception(exc)
  File "/home/bjester/Projects/learningequality/pyenv/versions/3.9.13/envs/kolibri-3.9.13/lib/python3.9/site-packages/rest_framework/views.py", line 455, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/home/bjester/Projects/learningequality/pyenv/versions/3.9.13/envs/kolibri-3.9.13/lib/python3.9/site-packages/rest_framework/views.py", line 492, in dispatch
    response = handler(request, *args, **kwargs)
  File "/home/bjester/Projects/learningequality/pyenv/versions/3.9.13/envs/kolibri-3.9.13/lib/python3.9/site-packages/rest_framework/mixins.py", line 20, in create
    serializer.is_valid(raise_exception=True)
  File "/home/bjester/Projects/learningequality/pyenv/versions/3.9.13/envs/kolibri-3.9.13/lib/python3.9/site-packages/rest_framework/serializers.py", line 236, in is_valid
    self._validated_data = self.run_validation(self.initial_data)
  File "/home/bjester/Projects/learningequality/pyenv/versions/3.9.13/envs/kolibri-3.9.13/lib/python3.9/site-packages/rest_framework/serializers.py", line 437, in run_validation
    value = self.validate(value)
  File "/home/bjester/Projects/learningequality/kolibri/kolibri/core/discovery/serializers.py", line 51, in validate
    client = NetworkClient.build_for_address(data["base_url"])
  File "/home/bjester/Projects/learningequality/kolibri/kolibri/core/discovery/utils/network/client.py", line 71, in build_for_address
    for url in get_normalized_url_variations(address):
  File "/home/bjester/Projects/learningequality/kolibri/kolibri/core/discovery/utils/network/urls.py", line 158, in get_normalized_url_variations
    p_scheme, p_hostname, p_port, p_path = parse_address_into_components(address)
  File "/home/bjester/Projects/learningequality/kolibri/kolibri/core/discovery/utils/network/urls.py", line 147, in parse_address_into_components
    raise errors.InvalidHostname(p_hostname)
kolibri.core.discovery.utils.network.errors.InvalidHostname: local studio
```

## Expected behavior

Errors are appropriately handled

## Steps to reproduce

1) Import channel content
2) Choose local network or internet
3) Manually add a new device
4) Enter an invalid address

## Context

Kolibri develop

### PR DESCRIPTION
**Pull request by marcellamaki**
## Summary
Fixes https://github.com/learningequality/kolibri/issues/10267

This adds additional error handling for address input that is a string with a space in it. It also adjusts the frontend so that if there is an error message for the address, the focus is automatically shifted back to that form field, so the user sees it by default. Previously, the way the KModal was managing the errors didn't update until the user clicked back into the form field, which is not the best user experience and could cause confusion about if there is an error

BEFORE 

https://user-images.githubusercontent.com/17235236/233707932-42c69d39-d1f6-40f1-accd-608c6c064c8c.mp4

AFTER

https://user-images.githubusercontent.com/17235236/233707979-700394a2-71bd-4b4c-a541-161f842aade6.mp4

## Reviewer guidance
Enter a non-address string (i.e. either one or multiple words) into the form field

----

## Testing checklist

- [ ] Contributor has fully tested the PR manually
- [ ] If there are any front-end changes, before/after screenshots are included
- [ ] Critical user journeys are covered by Gherkin stories
- [ ] Critical and brittle code paths are covered by unit tests

## PR process

- [ ] PR has the correct target branch and milestone
- [ ] PR has 'needs review' or 'work-in-progress' label
- [ ] If PR is ready for review, a reviewer has been added. (Don't use 'Assignees')
- [ ] If this is an important user-facing change, PR or related issue has a 'changelog' label
- [ ] If this includes an internal dependency change, a link to the diff is provided

## Reviewer checklist

- Automated test coverage is satisfactory
- PR is fully functional
- PR has been tested for [accessibility regressions](http://kolibri-dev.readthedocs.io/en/develop/manual_testing.html#accessibility-a11y-testing)
- External dependency files were updated if necessary (`yarn` and `pip`)
- Documentation is updated
- Contributor is in AUTHORS.md

### CODE REVIEW

File: kolibri/core/assets/src/views/sync/SelectDeviceModalGroup/AddDeviceForm.vue [hunk 1]
```diff
@@ -123,8 +124,10 @@
             ]);
             if (errorsCaught.includes(ERROR_CONSTANTS.NETWORK_LOCATION_NOT_FOUND)) {
               this.status = Statuses.COULD_NOT_CONNECT;
+              this.$refs.address.focus();
             } else if (errorsCaught.includes(ERROR_CONSTANTS.INVALID_NETWORK_LOCATION_FORMAT)) {
               this.status = Statuses.INVALID_ADDRESS;
+              this.$refs.address.focus();
```
Comment (bjester) [inline kolibri/core/assets/src/views/sync/SelectDeviceModalGroup/AddDeviceForm.vue:130]: Nice! Above and beyond

**Review by bjester — APPROVED** [review]
Nice work!

**Comment by pcenov** [comment]
Tested and confirmed that this is implemented as specified. Nice!
