### PR TITLE
Fix no resources available" instead of the available libraries 

### LINKED ISSUE #13071: Learn > Library - Seeing "No resources available" instead of the available libraries
## Observed behavior
In [Kolibri 0.18 alpha1](https://github.com/learningequality/kolibri/releases/tag/v0.18.0-alpha1) we are showing the "No resources available" instead of the available other libraries.

https://github.com/user-attachments/assets/b5263a8d-933e-4bca-a21f-b517ba93c5d8

Here's how this looks in the official Kolibri 0.17.5:

https://github.com/user-attachments/assets/c8561232-81d4-4b86-8b44-1742c9a6198e

## Expected behavior

Unless otherwise specified somewhere, we should keep the 0.17.5 behavior.

## Steps to reproduce the issue

1. Install the [Kolibri 0.18 alpha1](https://github.com/learningequality/kolibri/releases/tag/v0.18.0-alpha1) build
2. Navigate to Home or Library

## Usage Details
[Kolibri 0.18 alpha1](https://github.com/learningequality/kolibri/releases/tag/v0.18.0-alpha1)
Windows 11, Ubuntu 22  - Chrome, Firefox

### PR DESCRIPTION
**Pull request by AllanOXDi**
## Summary

Fixes the showing of  "No resources available" instead of the available other libraries.
### Before 
image
#### After

https://private-user-images.githubusercontent.com/79847249/412370388-c8561232-81d4-4b86-8b44-1742c9a6198e.mp4?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3NDE3MjQ3NzcsIm5iZiI6MTc0MTcyNDQ3NywicGF0aCI6Ii83OTg0NzI0OS80MTIzNzAzODgtYzg1NjEyMzItODFkNC00Yjg2LThiNDQtMTc0MmM5YTYxOThlLm1wND9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNTAzMTElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjUwMzExVDIwMjExN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWY3OTc2MDRhNzU1NDMyZDM2Y2FmMWIyYjk2MDgzN2UxNWExMzI1ZjljNDBlMjViZDVjYzk5OGE2MGExMGFmYjEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.NqF-Y_nU0vZ7PejskuqmGM5Yl4E_QlMzjIWuFmiZoZ8

closes  #13071
## References
 #13071

### CODE REVIEW

**Comment by LianaHarris360** [comment]
Tagging @radinamatic @pcenov for QA review

**Comment by radinamatic** [comment]
Assets from this PR were tested on both Ubuntu and Windows 11, and the originally reported issue is indeed corrected.

learn-library

---
However, in the [scenario that we were discussing on Slack](https://learningequality.slack.com/archives/C0LK8QS9J/p1742253090937379) with @rtibbles, when there are no resources in the library and no peers in the local network:
* admin would (eventually) see the channels on Kolibri Studio (as in the screenshot), but
* non-admin users would see a rather empty page, which is not ideal

For that reason @rtibbles suggested we would want that page to be more dynamic based on whether there are local libraries available, and preserve the [messaging from the content unavailable page](https://github.com/learningequality/kolibri/blob/develop/kolibri/plugins/learn/assets/src/views/ContentUnavailablePage.vue#L60) for the empty state.

So the idea is for the non-admin users to keep the current change from this PR **IF there are other peers in the local network** (and something does appear under the **Other libraries**). And in case there are no other peers around, and the class server has no channels, display the **No resources available** heading and **Ask your coach or administrator for assistance** below.

cc @marcellamaki @jtamiace

**Review by LianaHarris360 — DISMISSED** [review]
I’m seeing the `CONTENT_UNAVAILABLE` page as an admin when I should be able to browse channels on Kolibri Studio.
Screenshot 2025-03-19 at 11 37 36 AM


Based on Radina’s comment, I believe the `CONTENT_UNAVAILABLE` page should only displayed for **non-admin** users if there are no peers in the local network and no channels.

When there are no channels and no other libraries for the learner to browse, I currently see the LibraryPage:
learnerNoChannels

But in this case, a learner should see the ContentUnavailablePage with the message _Ask your coach or administrator for assistance_ instead:
LearnerNoContent2

**Comment by radinamatic** [comment]
Thank you @LianaHarris360 for including the screenhots of what @rtibbles was suggesting. I thought of trying to mock that alongside my description, but it would have certainly taken me much more time! 🙏🏽

**Comment by rtibbles** [comment]
I think let's pull the body of this component out into a separate component: https://github.com/learningequality/kolibri/blob/develop/kolibri/plugins/learn/assets/src/views/ContentUnavailablePage.vue - reuse it in the page there, and then also display it within the context of the LibraryPage.vue? That will allow us to continue to have the Content Unavailable page when we need to - but also mean we can show the appropriate language if there are no channels available, but also still display any locally available libraries (or Studio in the case of a super admin).

@AllanOXDi @LianaHarris360 does that make sense as an approach here?

File: kolibri/plugins/learn/assets/src/views/LibraryPage/NoResourcePage.vue [hunk 1]
```diff
@@ -0,0 +1,90 @@
+<template>
+
+  <LearnAppBarPage :appBarTitle="learnString('learnLabel')">
```
Comment (rtibbles) [inline kolibri/plugins/learn/assets/src/views/LibraryPage/NoResourcePage.vue]: Rather than duplicating the component completely - my suggestion was to make a component that represented the body of the ContentUnavailablePage component (everything _but_ the `LearnAppBarPage` component) and then reuse it in the LibraryPage and the ContentUnavailablePage.

Doing this has caused us to have two LearnAppBarPage components, one nested inside the other:

image

File: kolibri/plugins/learn/assets/src/views/LibraryPage/index.vue [hunk 2]
```diff
@@ -77,7 +81,7 @@
           />
           <!-- Other Libraries -->
           <OtherLibraries
-            v-if="showOtherLibraries"
+            v-if="showOtherLibraries && !isLearner"
```
Comment (rtibbles) [inline kolibri/plugins/learn/assets/src/views/LibraryPage/index.vue]: Not sure why we're now hiding the other libraries from learners?

This basically creates no change from the previous experience for learners, even though there are browsable libraries on the network:

image

File: kolibri/plugins/learn/assets/src/views/LibraryPage/index.vue [hunk 3]
```diff
@@ -333,10 +341,10 @@
 
       function _showLibrary(baseurl) {
         return fetchChannels({ baseurl }).then(channels => {
-          if (!channels.length && isUserLoggedIn) {
-            router.replace({ name: PageNames.CONTENT_UNAVAILABLE });
-            return;
+          if (!channels.length) {
+            set(isChannelEmpty, true);
```
Comment (rtibbles) [inline kolibri/plugins/learn/assets/src/views/LibraryPage/index.vue]: Don't need to add this, we're already tracking this with `isLocalLibraryEmpty`.

File: kolibri/plugins/learn/assets/src/views/LibraryPage/index.vue [hunk 4]
```diff
@@ -49,16 +49,20 @@
...
-            {{ channelsLabel }}
-          </h1>
-          <p
-            v-if="isLocalLibraryEmpty"
-            data-test="nothing-in-lib-label"
-            class="nothing-in-lib-label"
-          >
-            {{ coreString('nothingInLibraryLearner') }}
-          </p>
+          <NoResourcePage v-if="isChannelEmpty && isLearner" />
```
Comment (rtibbles) [inline kolibri/plugins/learn/assets/src/views/LibraryPage/index.vue]: I think we probably want to conditionally show this based on whether there are any libraries around you or not. If there are, we should show the existing message below, if not, then we should show this component.

This will require us to communicate something out of the OtherLibraries component to dynamically update this based on whether any libraries are being shown.

Comment (rtibbles) [reply kolibri/plugins/learn/assets/src/views/LibraryPage/index.vue]: Conditionalizing this on being a learner means that in the completely empty state, we're not showing proper messaging to an admin to prompt them to add resources to the device:

image

**Review by rtibbles — COMMENTED** [review]
Still not quite cleanly handling this empty state without side effects. I trust you are testing this with a clean Kolibri home directory to see how this renders?

The goal here is to retain our previous messaging in the case of a truly empty state, while also not blocking browsing of remote or local libraries when they are available.

**Comment by AllanOXDi** [comment]
Hi @rtibbles   I'm not sure, do we update the view as soon as we discover a library, learner initially doesn't have local libraries on the network but then one joins?

**Comment by rtibbles** [comment]
Yes, the OtherLibraries component is checking for other libraries on the network, so we would need a mechanism for it to communicate out when it is displaying libraries or not (probably by emitting an event and having the LibraryPage listening to that).

File: kolibri/plugins/learn/assets/src/views/LibraryPage/NoResourcePage.vue [hunk 5]
```diff
@@ -0,0 +1,90 @@
...
+
+<script>
+
+  import urls from 'kolibri/urls';
+  import useUser from 'kolibri/composables/useUser';
+  import LearnAppBarPage from '../LearnAppBarPage';
+  import commonLearnStrings from '../commonLearnStrings';
+
+  export default {
+    name: 'NoResourcePage',
```
Comment (rtibbles) [inline kolibri/plugins/learn/assets/src/views/LibraryPage/NoResourcePage.vue:27]: This is more like "NoResourceComponent" now, I think? And then we could import this into the ContentUnavailablePage to act as the body and avoid the duplication here.

File: kolibri/plugins/learn/assets/src/views/LibraryPage/NoResourcePage.vue [hunk 6]
```diff
@@ -0,0 +1,90 @@
...
+    metaInfo() {
+      return {
+        title: this.$tr('documentTitle'),
+      };
+    },
+    components: {
+      LearnAppBarPage,
```
Comment (rtibbles) [inline kolibri/plugins/learn/assets/src/views/LibraryPage/NoResourcePage.vue]: This component is no longer used here, hence the linting errors.

File: kolibri/plugins/learn/assets/src/views/LibraryPage/index.vue [hunk 7]
```diff
@@ -49,16 +49,19 @@
...
-            class="nothing-in-lib-label"
-          >
-            {{ coreString('nothingInLibraryLearner') }}
-          </p>
+          <div v-if="isLocalLibraryEmpty && isNetworkLibraryAvailable">
+            <h1 class="channels-label">
+              {{ channelsLabel }}
+            </h1>
+            <p
+              data-test="nothing-in-lib-label"
```
Comment (LianaHarris360) [inline kolibri/plugins/learn/assets/src/views/LibraryPage/index.vue:63]: Since the condition for this element to be displayed has been changed to include `isNetworkLibraryAvailable`, the test for it in `kolibri/plugins/learn/assets/test/views/library-page.spec.js` should be updated as well

Comment (AllanOXDi) [reply kolibri/plugins/learn/assets/src/views/LibraryPage/index.vue:63]: Fixed!

**Review by LianaHarris360 — COMMENTED** [review]
This might not be blocking or could be fixed in a follow-up, but another thing I noticed is that the `NoResources` component and the `OtherLibraries` message 'No other libraries around you right now' are displayed before the correct components load, with no indication that the page is still loading. This is more noticeable at slower data speeds.

https://github.com/user-attachments/assets/0f9c4927-8ad7-4085-8ed7-c9a65c738635

File: kolibri/plugins/learn/assets/src/views/LibraryPage/index.vue [hunk 8]
```diff
@@ -427,6 +429,7 @@
         metadataSidePanelContent: null,
         mobileSidePanelIsOpen: false,
         usingMeteredConnection: true,
+        isNetworkLibraryAvailable: false,
```
Comment (rtibbles) [inline kolibri/plugins/learn/assets/src/views/LibraryPage/index.vue]: I think maybe we could address part of @LianaHarris360's concern by defaulting this to `true`? Then once we've tried to load the network devices, the event you're emitting will then set this to false?

File: kolibri/plugins/learn/assets/src/views/LibraryPage/OtherLibraries.vue [hunk 9]
```diff
@@ -226,6 +226,22 @@
...
     },
+    watch: {
+      devicesWithChannelsExist: {
+        handler(newValue) {
+          this.$emit('availableNetworkDevices', newValue);
+        },
+        deep: true,
+      },
+    },
+    mounted() {
```
Comment (rtibbles) [inline kolibri/plugins/learn/assets/src/views/LibraryPage/OtherLibraries.vue]: I suspect using mounted here might be a little flaky, as we don't actually know that the initial data has been loaded at the point of the component being mounted?

Maybe we can use the `isLoadingChannels` value from the `useDevices` composable to do an initial trigger here rather than mounted? So the first time that goes from `true` to `false` we can then trigger this method.

**Comment by rtibbles** [comment]
This is much closer - one other slight issue, when there are resources available on my device, I am seeing this.
image

I think a little bit more cleanup to take care of this, and the "not quite loaded" state that @LianaHarris360 flagged and we should be good to go.

**Comment by LianaHarris360** [comment]
@radinamatic Tagging for a QA re-review

**Review by rtibbles — COMMENTED** [review]
Issues I was seeing previously appear to be resolved - will leave for QA to give the final thumbs up here!

**Comment by pcenov** [comment]
I'll probably have to revisit this on Monday as it is getting late here but so far the only issues I am observing are on slow internet connection where if there are other libraries and I refresh the page I am seeing first the search panel, then "There's nothing in your library yet..." and "No other libraries around you right now", then "No resources available" and after that the correct state:

https://github.com/user-attachments/assets/c52fcbc0-bceb-4b50-bc04-6ed000c42b79

Similarly if there are no libraries:

https://github.com/user-attachments/assets/734c2b5a-df3e-439d-bbb4-120b58410a85

**Comment by rtibbles** [comment]
I suspect that these loading state problems have probably been better surfaced by @AllanOXDi's work here, rather than created by it. We'll wait for the rest of @pcenov's review on Monday, but unless there are other significant issues we've not yet encountered, I'd rather put the loading state concerns into a follow up issue rather than block this PR any further.

**Comment by pcenov** [comment]
@rtibbles I have filled a follow-up for the loading state problems. ~I didn't observe any other issues.~

**Comment by pcenov** [comment]
Actually, I had it in my notes to double check how are we proceeding with the following issue where we are now not showing the "No resources available" page to a learner without resources or other libraries:

no resources available

**Comment by pcenov** [comment]
OK - sorry for the confusion, this scenario is also handled correctly now by showing a modified text under "No resources available" which reads: "Ask your coach or administrator for assistance"

**Review by LianaHarris360 — APPROVED** [review]
