### PR TITLE
Facility selection on login

### LINKED ISSUE #2552: Force selection of facility in user login
### Observed behavior

Currently a device with multiple facilities will not let a user login to the non-default facility. This may be at odds with the desires of some deployments who have roving models.

### Expected behavior

Show a list of facilities to login with.

Any simplified login autocomplete should be based on the currently selected facility.

### User-facing consequences

Users can't login!

### PR DESCRIPTION
**Pull request by DXCanas**
### Summary
Follows behaviour specified in 
https://github.com/learningequality/kolibri/issues/2552#issuecomment-368140529
and
https://github.com/learningequality/kolibri/issues/2552#issuecomment-368141194

basically, opens this onload with multifacility set ups

image

…

### Reviewer guidance

Currently, form behind it validates the first field, as modal removes focus from first input
Ideal testing involves creating a new facility using Kolibri's console. 

I'd post directions if I knew them - I received help from Ralphie. @rtibbles might be able to shed some light.
…

### References
resolves #2552 

…

----

### Contributor Checklist

- [ ] PR has the correct target branch and milestone
- [ ] PR has 'needs review' or 'work-in-progress' label
- [ ] Contributor has fully tested the PR manually
- [ ] Screenshots of any front-end changes are in the PR description
- [ ] If PR is ready for review, a reviewer has been added. (Don't use 'Assignees')

### Reviewer Checklist

- [ ] Automated test coverage is satisfactory
- [ ] Reviewer has fully tested the PR manually
- [ ] PR has been tested for [accessibility regressions](http://kolibri-dev.readthedocs.io/en/develop/manual_testing.html#accessibility-a11y-testing)
- [ ] External dependencies files were updated (`yarn` and `pip`)
- [ ] Documentation is updated
- [ ] Link to diff of internal dependency change is included
- [ ] CHANGELOG.rst is updated for high-level changes
- [ ] Contributor is in AUTHORS.rst

### CODE REVIEW

File: kolibri/core/assets/src/state/actions.js [hunk 1]
```diff
@@ -233,11 +233,11 @@ function getCurrentSession(store, force = false) {
     });
 }
 
-function getFacilityConfig(store) {
+function getFacilityConfig(store, facilityId = '') {
```
Comment (indirectlylit) [inline kolibri/core/assets/src/state/actions.js]: You shouldn't actually set a default empty string here. Letting `facilityId` be undefined when nothing is passed in is more semantically correct, because in theory the empty string could be an ID.

File: kolibri/plugins/user/assets/src/views/sign-in-page/facility-modal.vue [hunk 2]
```diff
@@ -0,0 +1,85 @@
...
+    components: {
+      coreModal,
+      kRadioButton,
+      kButton,
+    },
+    props: {
+      facilities: {
+        type: Array,
+        required: true,
+      },
```
Comment (indirectlylit) [inline kolibri/plugins/user/assets/src/views/sign-in-page/facility-modal.vue]: Since this component is already referencing vuex, might as well just reference `state.core.facilities` directly in this component. Passing it as a prop with type `Array` creates extra complexity with no benefit.

File: kolibri/plugins/user/assets/src/views/sign-in-page/index.vue [hunk 3]
```diff
@@ -289,7 +318,7 @@
             username: this.username,
             password: this.password,
             facility: this.facility,
-          });
+          }).catch(this.setFacilityModal());
```
Comment (indirectlylit) [inline kolibri/plugins/user/assets/src/views/sign-in-page/index.vue]: I don't entirely understand what's happening here. Some code comments?

File: kolibri/core/assets/src/state/actions.js (hunk 1 above)
Comment (indirectlylit) [reply kolibri/core/assets/src/state/actions.js]: alternatively you can set it to `null` by default

File: kolibri/plugins/user/assets/src/views/sign-in-page/facility-modal.vue [hunk 4]
```diff
@@ -0,0 +1,85 @@
+<template>
+
+  <core-modal @cancel="emitClose" title="Select a facility">
+    <form @submit.prevent="submitAndClose">
+
+    </form>
+    Which facility do you want to log into?
```
Comment (christianmemije) [inline kolibri/plugins/user/assets/src/views/sign-in-page/facility-modal.vue]: sign*

File: kolibri/plugins/user/assets/src/views/sign-in-page/index.vue [hunk 5]
```diff
@@ -201,9 +212,27 @@
       versionMsg() {
         return this.$tr('poweredBy', { version: __version });
       },
+      hasServerError() {
+        return !!(this.passwordMissing || this.invalidCredentials);
```
Comment (christianmemije) [inline kolibri/plugins/user/assets/src/views/sign-in-page/index.vue]: Cast it to a Boolean instead.

Comment (DXCanas) [reply kolibri/plugins/user/assets/src/views/sign-in-page/index.vue]: but https://user-images.githubusercontent.com/25045166/35070604-a1aad520-fb92-11e7-8423-feeeacfdfd25.png

Comment (DXCanas) [reply kolibri/plugins/user/assets/src/views/sign-in-page/index.vue]: I agree though

File: kolibri/plugins/user/assets/src/views/sign-in-page/facility-modal.vue (hunk 2 above)
Comment (DXCanas) [reply kolibri/plugins/user/assets/src/views/sign-in-page/facility-modal.vue]: I think I have a hard time striking a balance between making a component completely functional vs state driven

Comment (indirectlylit) [reply kolibri/plugins/user/assets/src/views/sign-in-page/facility-modal.vue]: compromise can result in inconsistency

File: kolibri/plugins/user/assets/src/views/sign-in-page/index.vue (hunk 3 above)
Comment (DXCanas) [reply kolibri/plugins/user/assets/src/views/sign-in-page/index.vue]: Explained a bit in https://github.com/learningequality/kolibri/issues/2552#issuecomment-368105613

Going for the behavior described in 
https://github.com/learningequality/kolibri/issues/2552#issuecomment-368140529
and
https://github.com/learningequality/kolibri/issues/2552#issuecomment-368141194

instead

**Comment by DXCanas** [comment]
@indirectlylit made some changes, now following the spec set out in the issue. Gonna shift focus to Lessons for a while

File: kolibri/plugins/user/assets/src/views/sign-in-page/index.vue [hunk 6]
```diff
@@ -288,8 +311,8 @@
           this.kolibriLogin({
             username: this.username,
             password: this.password,
-            facility: this.facility,
-          });
+            facility: this.facilityConfig.id,
```
Comment (rtibbles) [inline kolibri/plugins/user/assets/src/views/sign-in-page/index.vue]: Why is this set to the id of the facilityConfig object? This is not a facility, it's a facilitydataset's id.

Comment (DXCanas) [reply kolibri/plugins/user/assets/src/views/sign-in-page/index.vue]: That was a mistake ^ found this out the hard way

File: kolibri/plugins/user/assets/src/state/actions.js [hunk 7]
```diff
@@ -121,11 +122,21 @@ export function showSignInPage(store) {
     });
     Lockr.set(SIGNED_OUT_DUE_TO_INACTIVITY, null);
   }
-  resetAndSetPageName(store, {
-    pageName: PageNames.SIGN_IN,
-    title: translator.$tr('userSignInPageTitle'),
-  });
-  store.dispatch('SET_PAGE_STATE', {});
+
+  FacilityResource.getCollection()
```
Comment (rtibbles) [inline kolibri/plugins/user/assets/src/state/actions.js]: Given that this is happening on every load of the user page, I think we should make a cached bootstrap of the Facility collection into the `user.html` template.

Will open a PR shortly.

File: kolibri/plugins/user/assets/src/views/sign-in-page/facility-modal.vue [hunk 8]
```diff
@@ -0,0 +1,83 @@
...
+      };
+    },
+    methods: {
+      emitClose() {
+        this.$emit('close');
+      },
+      submitAndClose() {
+        this.setFacilityId();
+        this.clearLoginError();
+        this.getFacilityConfig(this.selectedFacility);
```
Comment (rtibbles) [inline kolibri/plugins/user/assets/src/views/sign-in-page/facility-modal.vue]: Also, we shouldn't clear the modal until the new facility config has been loaded and set, otherwise it may produce a confusing user experience? If the facility config for the newly selected facility is different, this could cause the interface to change mid-user input if the response is slow.

File: kolibri/plugins/user/views.py [hunk 9]
```diff
@@ -1,18 +1,8 @@
-from __future__ import absolute_import, print_function, unicode_literals
-from django.views.generic.base import TemplateView
-from kolibri.auth.models import Facility
+from __future__ import absolute_import
+from __future__ import print_function
+from __future__ import unicode_literals
```
Comment (indirectlylit) [inline kolibri/plugins/user/views.py:3]: @rtibbles why are these here?

Comment (rtibbles) [reply kolibri/plugins/user/views.py:3]: Because they are not on one line any more (we had a change in python linter that now splits imports into repeated, but multiline).

File: kolibri/plugins/user/assets/src/views/sign-in-page/facility-modal.vue [hunk 10]
```diff
@@ -51,8 +51,7 @@
       submitAndClose() {
         this.setFacilityId();
         this.clearLoginError();
-        this.getFacilityConfig(this.selectedFacility);
-        this.emitClose();
+        this.getFacilityConfig(this.selectedFacility).then(this.emitClose);
```
Comment (indirectlylit) [inline kolibri/plugins/user/assets/src/views/sign-in-page/facility-modal.vue]: we might need a 'fetching' state to prevent re-submission?
