### PR TITLE
Fix alignment of language buttons in setup flow

### LINKED ISSUE #12298: Fix alignment of language buttons in setup flow
## Observed behavior
Noted by @tomiwaoLE in the 0.17.0-alpha0 bug bash 

## Errors and logs
image

## Expected behavior
All items should be aligned

## Context
0.17.0-alpha0 _mac app_

### PR DESCRIPTION
**Pull request by malviya-rajveer**
# Summary 
+ Perfect alignment of language buttons in the setup flow default language page
fixes #12298 
## before alignment of languages 
Screenshot from 2025-01-23 22-32-42
## After alignment of languages
Screenshot from 2025-01-24 13-07-46

### CODE REVIEW

**Comment by MisRob** [comment]
Hi @malviya-rajveer, thanks!

Would you please post before/after screenshot? Also for next time, it's best to keep the pull request description template and fill it in as it guides you to provide information that's needed.

Also, before working on an issue, next time I'd suggest you ask for an assignment first. See more [in the contributing guidelines](https://github.com/learningequality/kolibri/blob/develop/CONTRIBUTING.md).

**Comment by malviya-rajveer** [comment]
Hello @MisRob, thank you for reviewing my pull request! I really appreciate your time and feedback. I apologize for not including the before/after screenshots; I understand how important they are for clarity. I'll be sure to follow the pull request description template more closely in the future. 

I also appreciate your suggestion regarding assignment requests before working on issues. I’ll make sure to refer to the contributing guidelines next time. Thank you for your guidance!

**Comment by MisRob** [comment]
No worries and thank you @malviya-rajveer

File: packages/kolibri/components/language-switcher/LanguageSwitcherList.vue [hunk 1]
```diff
@@ -149,6 +149,10 @@
     padding-left: 8px;
   }
 
+  .px-6 {
+    padding-bottom: 6px;
```
Comment (AllanOXDi) [inline packages/kolibri/components/language-switcher/LanguageSwitcherList.vue]: I think we can take this to 2px.

File: packages/kolibri/components/language-switcher/internal/SelectedLanguage.vue [hunk 2]
```diff
@@ -48,6 +48,7 @@
 
   .px-8 {
     padding-right: 8px;
+    padding-bottom: 4px;
```
Comment (AllanOXDi) [inline packages/kolibri/components/language-switcher/internal/SelectedLanguage.vue]: 2px here too

**Review by AllanOXDi — CHANGES_REQUESTED** [review]

**Comment by AllanOXDi** [comment]
Hi @malviya-rajveer  I left you a few  minor comment. From this PR I can  still see this 
Screenshot 2025-01-27 at 17 45 11

**Comment by malviya-rajveer** [comment]
Hi @AllanOXDi, I've implemented the changes you suggested. Please review it thank you!!

**Review by AllanOXDi — APPROVED** [review]
LGTM! Thanks @malviya-rajveer
