### PR TITLE
Hide mark attendance button when no learners are enrolled

### LINKED ISSUE #14412: Attendance Tracking - The 'Mark attendance' button should be hidden when there are no learners in a class
❌ **This issue is not open for contribution. Visit <a href="https://learningequality.org/contributing-to-our-open-code-base/" target="_blank">Contributing guidelines</a>** to learn about the contributing process and how to find suitable issues.

## Observed behavior

If I have a brand news class without learners and I go to `Coach > Class home > class` then I see the Attendance section with the 'Mark attendance' button visible and enabled.

https://github.com/user-attachments/assets/8d0c1ccc-be3e-4724-a255-1ef29d57c624

## Expected behavior

Should be further discussed.
For consistency with the other sections I would expect in that case the 'Mark attendance' button to be absent and the 'Attendance' section to be present with the just the text 'No attendance sessions yet'
 
## Steps to reproduce the issue

1. Install the build from https://github.com/learningequality/kolibri/releases/tag/v0.19.3-rc1
2. Create a class without learners
3. Go to `Coach > Class home > class` and see that the 'Mark attendance' button is visible

## Usage Details
Windows 11, Ubuntu 22, Mac OS 15.5  - Chrome, Firefox
https://github.com/learningequality/kolibri/releases/tag/v0.19.3-rc1

### PR DESCRIPTION
**Pull request by akolson**
## Summary

Fixes a bug where the "Mark attendance" button was visible on the class home page even when no learners were enrolled in the class. This is inconsistent with the behavior of other blocks on the same page, which hide their action buttons when there's no data to act on.

Changes:
- Gate the "Mark attendance" button behind a `v-if="learners.length"` check so it only renders when the class has enrolled learners
- Show a more helpful empty state message (`"No attendance sessions yet. Enroll learners to mark attendance"`) instead of `"No attendance sessions yet"` when there are zero learners

| State | Screenshot |
|-------|------------|
| Class with 0 learners (button hidden, helpful message shown) |image|
| Class with learners (button shown as expected) | image|

## References

Fixes #14412

## Reviewer guidance

- Test with a class that has 0 enrolled learners: the "Mark attendance" button should not appear
- Test with a class that has ≥1 enrolled learners: the "Mark attendance" button should appear as before
- The empty state message differs between the two states — verify both messages render correctly

## AI usage

I used Claude Code to implement this change, guiding it to use the existing `learners` computed from `classSummary/learners` in the Vuex store and wrap the button in a `v-if` conditional. I reviewed the generated code, verified the logic against the issue description, and confirmed the fix works in both the empty-class and populated-class scenarios.

### CODE REVIEW

**Review by rtibbles — COMMENTED** [review]
Code changes look correct to me - and I have just noticed that the bot implemented the attendance block tests using vue test utils, not vue test library! Will open a follow up issue in develop to rectify this once we've merged down.

File: packages/kolibri-common/strings/attendanceStrings.js [hunk 1]
```diff
@@ -174,4 +174,9 @@ export const attendanceStrings = createTranslator('AttendanceStrings', {
     message: 'Absent',
     context: 'Column header for the count of learners absent',
   },
+  noSessionsEnrollMessage: {
+    message: 'No attendance sessions yet. Enroll learners to mark attendance',
+    context:
+      'Empty state message when no attendance sessions exist and no learners are enrolled in the class',
+  },
```
Comment (rtibblesbot) [inline packages/kolibri-common/strings/attendanceStrings.js:181]: **blocking:** This PR adds a new translatable string (`noSessionsEnrollMessage`) but targets `release-v0.19.x`, not the default branch (`develop`). New strings on release branches can disrupt the i18n/translation pipeline since string extraction and Crowdin syncs typically run against the default branch.

The linked issue (#14412) doesn't call for a new message — its expected behavior is: *"the 'Attendance' section to be present with just the text 'No attendance sessions yet'."* Consider dropping this new string and reusing the existing `noSessionsMessage` for both cases (matching the issue's stated expectation). If the distinct message is desired, it should land on `develop` first and be cherry-picked after translations are in place.

File: kolibri/plugins/coach/frontend/views/home/HomePage/__tests__/AttendanceBlock.spec.js [hunk 2]
```diff
@@ -122,10 +146,18 @@ describe('AttendanceBlock', () => {
...
+    await global.flushPromises();
+    expect(wrapper.text()).toContain('No attendance sessions yet');
+    expect(wrapper.text()).not.toContain('Enroll learners');
+  });
+
+  it('renders enroll message when no sessions and no learners are enrolled', async () => {
+    const { wrapper } = makeWrapper({ sessions: [], learners: [] });
     await global.flushPromises();
     expect(wrapper.text()).toContain('No attendance sessions yet');
+    expect(wrapper.text()).toContain('Enroll learners to mark attendance');
```
Comment (rtibblesbot) [inline kolibri/plugins/coach/frontend/views/home/HomePage/__tests__/AttendanceBlock.spec.js:160]: **suggestion:** The primary acceptance criterion from #14412 is that the "Mark attendance" button is hidden when no learners are enrolled, but no test asserts this. Consider adding an assertion that the `KRouterLink` stub is absent when `learners` is empty, e.g.:

```js
expect(wrapper.findComponent({ name: 'KRouterLink' }).exists()).toBe(false);
```

And conversely, that it's present when learners exist.

File: kolibri/plugins/coach/frontend/views/home/HomePage/__tests__/AttendanceBlock.spec.js [hunk 3]
```diff
@@ -88,6 +99,19 @@ function makeWrapper({ sessions = [], pendingFetch = false, rejectWith = null }
 
   const testStore = makeStore();
 
+  // Populate learnerMap so the component's learners computed property works
+  const learnerMap = {};
+  learners.forEach(l => {
+    learnerMap[l.id] = l;
+  });
+  testStore.state.classSummary.learnerMap = learnerMap;
```
Comment (rtibblesbot) [inline kolibri/plugins/coach/frontend/views/home/HomePage/__tests__/AttendanceBlock.spec.js:107]: **praise:** Good job wiring up the `classSummary` module and `learnerMap` in the test store — this ensures the component's `computed(() => store.getters['classSummary/learners'])` works correctly in tests without over-mocking.

**Review by rtibblesbot — DISMISSED** [review]
Straightforward fix that gates the button behind `learners.length` — the core logic is correct.

CI passing. Screenshots provided and consistent with code changes.

- **blocking:** New translatable string `noSessionsEnrollMessage` added on `release-v0.19.x` (non-default branch), and adding strings was not specified in #14412. See inline comment.
- **suggestion:** Missing test assertion for button visibility — see inline comment.
- **praise:** Clean test setup wiring the Vuex `classSummary` module with learner data — see inline comment.

---
_@rtibblesbot's comments are generated by an LLM, and should be evaluated accordingly_

<details><summary>How was this generated?</summary>

Reviewed the pull request diff checking for:
- **Correctness:** bugs, edge cases, undocumented behavior, resource leaks, hardcoded values
- **Design:** unnecessary complexity, naming, readability, comment accuracy, redundant state
- **Architecture:** duplicated concerns, minimal interfaces, composition over inheritance
- **Testing:** behavior-based assertions, mocks only at hard boundaries, accurate coverage
- **Completeness:** missing dependencies, unupdated usages, i18n, accessibility, security
- **Principles:** DRY (same reason to change), SRP, Rule of Three (no premature abstraction)
- Checked CI status and linked issue acceptance criteria
- For UI changes: inspected screenshots for layout, visual completeness, and consistency

</details>

**Comment by radinamatic** [comment]
Looking good in Firefox and Chrome on Ubuntu.

Firefox | Chrome
-- | --
Ubuntu22 04 (start)  Running  - Oracle VirtualBox_009 | Ubuntu22 04 (start)  Running  - Oracle VirtualBox_010

0 learners, no button, 1+ learner button appears 🙂 👏🏽

File: packages/kolibri-common/strings/attendanceStrings.js (hunk 1 above)
Comment (rtibbles) [reply packages/kolibri-common/strings/attendanceStrings.js:181]: This is fine, this feature is gated to English only, so untranslated strings will not appear.

**Review by rtibbles — APPROVED** [review]
Bot does not have access to the full facts.
