### PR TITLE
Don't let a user delete themselves.

### LINKED ISSUE #1643: Facility admin is able to delete his/her own user ID while logged in using the same ID.
## Summary
Facility admin is able to delete his/her own user ID while logged in using the same ID

## How to reproduce
1. Add a Facility admin.
2. Login with the same facility admin.
3. Click on edit and delete the ID.
4. It gets deleted.

### PR DESCRIPTION
**Pull request by rtibbles**
## Summary

Fixes #1643 by disabling delete user button on logged in user.

## Screenshots (if appropriate)

image

### CODE REVIEW

File: kolibri/plugins/management/assets/src/views/user-page/user-edit-modal.vue [hunk 1]
```diff
@@ -37,7 +37,7 @@
 
         <div class="advanced-options" @keydown.enter.stop>
           <button @click="pw_reset=!pw_reset"> {{$tr('resetPw')}} </button>
-          <button @click="usr_delete=!usr_delete"> {{$tr('deleteUsr')}}</button>
+          <button @click="usr_delete=!usr_delete" :disabled="'disabled' ? userid === session_user_id : null"> {{$tr('deleteUsr')}}</button>
```
Comment (DXCanas) [inline kolibri/plugins/management/assets/src/views/user-page/user-edit-modal.vue]: Looks like 
```
<button @click="usr_delete=!usr_delete" :disabled="userid === session_user_id"> {{$tr('deleteUsr')}}</button>
```
works ok for me
