### PR TITLE
Fix points updating after content completion.

### LINKED ISSUE #1656: After dismissing 'great work' modal, points added to total are taken back
When the modal appears, you can see the points total in upper right corner get updated. But after dismissing the modal, the points go back to old value.

points reverted

### PR DESCRIPTION
**Pull request by rtibbles**
## Summary

Consolidate progress updating logic into a single function.
Fix points updating after content completion.

## Issues addressed

Fixes #1656

### CODE REVIEW

File: kolibri/core/assets/src/state/actions.js [hunk 1]
```diff
@@ -428,39 +428,53 @@ function saveLogs(store) {
...
- * @param {float} progressPercent
- * @param {boolean} forceSave
+ * Helper function to handle common functionality between updateProgress and updateExerciseProgress
+ * @param  {VuexStore} store        The currently active Vuex store
+ * @param  {Number} sessionProgress The progress made in this session
+ * @param  {[type]} summaryProgress The progress made on this content overall
+ * @param {boolean} forceSave       Force saving of logs?
  */
-function updateProgress(store, progressPercent, forceSave = false) {
+function _updateProgress(store, sessionProgress, summaryProgress, forceSave = false) {
```
Comment (DXCanas) [inline kolibri/core/assets/src/state/actions.js:447]: Would be helpful to give the helper function a more semantic name, less associated with `updateProgress`

File: kolibri/core/assets/src/state/actions.js [hunk 2]
```diff
@@ -428,39 +428,53 @@ function saveLogs(store) {
   }
 }
 
+function fetchPoints(store) {
+  if (!getters.isSuperuser(store.state) && getters.isUserLoggedIn(store.state)) {
```
Comment (DXCanas) [inline kolibri/core/assets/src/state/actions.js:432]: I also cleaned up the `getters` include statement in #1792 , which should make this a little easier to read once I merge this in.

File: kolibri/core/assets/src/state/actions.js (hunk 1 above)
Comment (rtibbles) [reply kolibri/core/assets/src/state/actions.js:447]: Hrm, but it is about updating progress!
