### PR TITLE
Fix course unit navigation issues

### LINKED ISSUE #14221: Course content viewer in mobile view - Navigation issues
❌ **This issue is not open for contribution. Visit <a href="https://learningequality.org/contributing-to-our-open-code-base/" target="_blank">Contributing guidelines</a>** to learn about the contributing process and how to find suitable issues.

## Observed behavior
Observed while testing https://github.com/learningequality/kolibri/pull/14122:

If I am viewing a course in mobile view, then when I open the course sidebar and select a resource from the list the sidebar remains open until I click the X icon. Similarly if select the next unit from the bottom of the page the sidebar remains open while I would expect to be able to immediately proceed with the next unit:

https://github.com/user-attachments/assets/3bf9790e-71ef-4558-998d-f30a05c3d1d7

## Expected behavior

To be further discussed.
 
## Steps to reproduce the issue

1. Install the build from https://github.com/learningequality/kolibri/pull/14122
2. Sign in as a learner with assigned courses
3. Start interacting with a course in mobile view

## Usage Details
Windows 11, Ubuntu 22, Mac OS 15.5  - Chrome, Firefox

### PR DESCRIPTION
**Pull request by AlexVelezLl**
## Summary

* Exposes a `onSidePanelNavigation` public method from ResourceLayout, so that if the parent component calls this method, the ResourceLayout component will close the side panel if it was in modal mode.
  * Is the name of this method okay? Tried to be abstract about the required behavior, but we can also call it something more specific, like "closeSidePanelIfModalMode".
* Call this method on resource/unit navigation in CourseUnitView. 

https://github.com/user-attachments/assets/361b6dd9-4dc6-4665-8663-607cb6478283

## References
Closes #14221.

## Reviewer guidance
Replicate #14221.

## AI usage
* Asked Gemini how to expose a method inside the `setup` method.

### CODE REVIEW

File: kolibri/plugins/learn/frontend/views/ResourceLayout/index.vue [hunk 1]
```diff
@@ -168,6 +172,21 @@
...
+       * Called by parent components when navigation occurs due to an action on the
+       * side panel.
+       */
+      function onSidePanelNavigation() {
+        if (sidePanelOpen.value && isSidePanelModalMode.value) {
+          closeSidePanel();
+        }
+      }
+
+      expose({ onSidePanelNavigation });
```
Comment (rtibblesbot) [inline kolibri/plugins/learn/frontend/views/ResourceLayout/index.vue:188]: **praise:** Good use of `expose` to define a clean public API for this component. This is the first usage in the codebase — worth noting that in Vue 2.7, `expose` documents intent but doesn't restrict access like in Vue 3. Still valuable as a forward-compatible pattern, and the JSDoc comment on `onSidePanelNavigation` makes the contract clear.

File: kolibri/plugins/learn/frontend/views/ResourceLayout/index.vue [hunk 2]
```diff
@@ -168,6 +172,21 @@
         }
       }
 
+      const isSidePanelModalMode = computed(() => windowBreakpoint.value <= 2);
```
Comment (rtibblesbot) [inline kolibri/plugins/learn/frontend/views/ResourceLayout/index.vue:175]: **praise:** Extracting `isSidePanelModalMode` as a computed and reusing it for `showPushPanel`/`showModalPanel` (lines 215-217) eliminates the duplicated `windowBreakpoint.value <= 2` condition. Nice cleanup.

File: kolibri/plugins/learn/frontend/views/CourseUnitView/UnitTreeAccordion/index.vue [hunk 3]
```diff
@@ -245,14 +240,7 @@
...
       const onResourceClick = resource => {
-        router.replace({
-          name: PageNames.COURSE_CONTENT__RESOURCE,
-          params: {
-            ...route.params,
-            resourceId: resource.id,
-            lessonId: resource.parent,
-          },
-        });
+        emit('navigateToResource', resource);
```
Comment (rtibblesbot) [inline kolibri/plugins/learn/frontend/views/CourseUnitView/UnitTreeAccordion/index.vue:243]: **praise:** Good refactoring — emitting `navigateToResource` instead of navigating directly moves the routing concern to the parent that owns the `ResourceLayout` ref. This follows the "tell, don't ask" principle and avoids the child needing to know about sibling component internals.

**Review by rtibblesbot — APPROVED** [review]
Clean fix for the P0 mobile sidebar navigation issue (#14221).

CI: Python tests pass; frontend tests, linting, and WHL build still pending. PR targets `release-v0.19.x` — appropriate for a P0 bug fix with no new strings.

- **praise:** Good refactoring — moving navigation responsibility from UnitTreeAccordion up to CourseUnitView keeps side-panel-closing logic co-located with the ResourceLayout ref owner, and the `isSidePanelModalMode` computed eliminates the duplicated `windowBreakpoint.value <= 2` check.
- **praise:** All side-panel-triggered navigation paths are covered (`handleNavigateToResource`, `goToNextUnit`, `handlePrev`, `handleNext`).

---
_@rtibblesbot's comments are generated by an LLM, and should be evaluated accordingly_

<details><summary>How was this generated?</summary>

Reviewed the pull request diff checking for:
- **Correctness:** bugs, edge cases, undocumented behavior, resource leaks, hardcoded values
- **Design:** unnecessary complexity, naming, readability, comment accuracy, redundant state
- **Architecture:** duplicated concerns, minimal interfaces, composition over inheritance
- **Testing:** behavior-based assertions, mocks only at hard boundaries, accurate coverage
- **Completeness:** missing dependencies, unupdated usages, i18n, accessibility, security
- **Principles:** DRY (same reason to change), SRP, Rule of Three (no premature abstraction)
- Checked CI status and linked issue acceptance criteria
- For UI changes: inspected screenshots for layout, visual completeness, and consistency

</details>

File: kolibri/plugins/learn/frontend/views/CourseUnitView/index.vue [hunk 4]
```diff
@@ -621,6 +623,12 @@
         return false;
       };
 
+      const onSidePanelNavigation = () => {
```
Comment (AllanOXDi) [inline kolibri/plugins/learn/frontend/views/CourseUnitView/index.vue:626]: None blocking: `onSidePanelNavigation()` sounds like an event handler. Is the name of this method okay?

File: kolibri/plugins/learn/frontend/views/CourseUnitView/index.vue [hunk 5]
```diff
@@ -621,6 +623,12 @@
...
+        if (resourceLayoutRef.value) {
+          resourceLayoutRef.value.onSidePanelNavigation();
```
Comment (AllanOXDi) [inline kolibri/plugins/learn/frontend/views/CourseUnitView/index.vue:628]: This is fine, but I am thinking` resourceLayoutRef` should always be set once the component is mounted, you could simplify it to called the method directly if you're confident about mount order.

**Review by AllanOXDi — COMMENTED** [review]
Thanks @AlexVelezLl , I just left a few questions for you. Otherwise, it's all good.

File: kolibri/plugins/learn/frontend/views/ResourceLayout/index.vue [hunk 6]
```diff
@@ -168,6 +172,21 @@
...
+
+      /**
+       * Public method to close the side panel if open and in modal mode.
+       * Called by parent components when navigation occurs due to an action on the
+       * side panel.
+       */
+      function onSidePanelNavigation() {
+        if (sidePanelOpen.value && isSidePanelModalMode.value) {
```
Comment (AllanOXDi) [inline kolibri/plugins/learn/frontend/views/ResourceLayout/index.vue:183]: Just thinking, what if the breakpoint changes while navigating? For example:

- User opens side panel in modal mode
- User resizes window to desktop while panel is open
- User navigates to a resource

File: kolibri/plugins/learn/frontend/views/CourseUnitView/index.vue (hunk 4 above)
Comment (AlexVelezLl) [reply kolibri/plugins/learn/frontend/views/CourseUnitView/index.vue:626]: In theory, it is an event handler, yes.

File: kolibri/plugins/learn/frontend/views/CourseUnitView/index.vue (hunk 5 above)
Comment (AlexVelezLl) [reply kolibri/plugins/learn/frontend/views/CourseUnitView/index.vue:628]: We use to treat refs carefully always, perhaps an event like this may be called just before the unmount? Or it may be called directly on the `setup()` method, where the component hasn't been mounted yet.

File: kolibri/plugins/learn/frontend/views/ResourceLayout/index.vue (hunk 6 above)
Comment (AlexVelezLl) [reply kolibri/plugins/learn/frontend/views/ResourceLayout/index.vue:183]: This is why `isSidePanelModalMode` is a computed (and reactive) property 👐. It will read the window breakpoint when the user navigates to the resource, not when the user opens the side panel.

**Review by marcellamaki — COMMENTED** [review]
code changes look good (as it seems like Allan's comments as well were non-blocking but more talking through ideas) and manual QA confirms the fix is working as intended. Not "approving" just because we will wait until after release to merge, but good to go.

**Review by marcellamaki — APPROVED** [review]
