### PR TITLE
Fix task cancellation

### LINKED ISSUE #5513: Cancelling content import and export not working
### Observed behavior

Cancelling import is not working: once the <kbd>Cancel</kbd> button is clicked, it appears disabled, but the import continues and there seems not to be a way to stop it, even on page reload the bar is still in progress.

### Expected behavior
User should be able to stop the content import if they need.

### User-facing consequences
Unable to cancel import operation.

### Errors and logs
Nothing overt in the command line or the browser console

[kolibri.log.part.log](https://github.com/learningequality/kolibri/files/3194771/kolibri.log.part.log)
(partial during the import operation)

### Steps to reproduce
Try to cancel channel mid import.

### Context
 * Kolibri version: 0.12.y dev branch
 * Operating system: Ubuntu 18.04
 * Browser: FF 66 & Chrome on Ubuntu 18.04

### PR DESCRIPTION
**Pull request by rtibbles**
### Summary
* Revert change to one step cancellation process.
* Disable cancel button once pressed.
* Clear tasks based on `CANCELED` state being reported.

### Reviewer guidance
Can you cancel tasks?
Can you always cancel tasks?
Does cancelling tasks ever not work?

### References
Fixes #5513 

Updates iceqube: https://github.com/learningequality/iceqube/compare/0.2...0.3

----

### Contributor Checklist

PR process:

- [x] PR has the correct target branch and milestone
- [x] PR has 'needs review' or 'work-in-progress' label
- [x] If PR is ready for review, a reviewer has been added. (Don't use 'Assignees')
- [ ] If this is an important user-facing change, PR or related issue has a 'changelog' label
- [x] If this includes an internal dependency change, a link to the diff is provided

Testing:

- [x] Contributor has fully tested the PR manually
- [ ] If there are any front-end changes, before/after screenshots are included
- [ ] Critical user journeys are covered by Gherkin stories
- [ ] Critical and brittle code paths are covered by unit tests

### Reviewer Checklist

- Automated test coverage is satisfactory
- PR is fully functional
- PR has been tested for [accessibility regressions](http://kolibri-dev.readthedocs.io/en/develop/manual_testing.html#accessibility-a11y-testing)
- External dependency files were updated if necessary (`yarn` and `pip`)
- Documentation is updated
- Contributor is in AUTHORS.md

### CODE REVIEW

**Comment by jonboiser** [comment]
I got this, where it disables the "cancel" button, but the tasks completes anyway, so the "close" button is disabled. From downloading about 20 MB from Multaqaddarain.

Refreshing the page will re-enable the button and I can close the notification.

Screen Shot 2019-05-23 at 12 55 31 PM

I couldn't cancel out of downloading the metadata DB and getting to that same channel's "select content page".

I tried it again with Khan Academy English. Pressing "cancel" still does not cancel the Metadata DB import, but you can still click the "X" button, which will exit the workflow, and then show an error in the Progress widget. After clicking "close", then all the Tasks are cleared from the queue.

**Comment by rtibbles** [comment]
Ah, good catch. Need to re-enable the button if the task state changes.

**Comment by rtibbles** [comment]
Will double check the metadata download flow.

File: kolibri/plugins/device_management/assets/src/views/ManageContentPage/index.vue [hunk 1]
```diff
@@ -109,7 +109,7 @@
           // Handle failures silently in case of near-simultaneous cancels.
           .catch(() => {})
           .then(() => {
-            unblockCb();
+            unblockCb ? unblockCb() : null;
```
Comment (indirectlylit) [inline kolibri/plugins/device_management/assets/src/views/ManageContentPage/index.vue]: non-blocking, but might write this more explicitly as 

```javascript
if (unblockCb) unblockCb();
```

since ternaries are usually used to return values, not trigger side effects

**Comment by jonboiser** [comment]
1. ❌ 	Clicking "close" after deleting a channel is not refreshing the page/channel list for me.
1. ✅ 	Cancelling works when downloading metadataDB at Select Content page
1. ❌ 	Clicking "cancel" after selecting all of CK-12 seems to be ignored. Refreshed page (to undisable button) and tried again. Still being ignored.

**Comment by rtibbles** [comment]
Ah, I had some more commits to push here, sorry. Will update.

Was trying to work out how to replicate your case of 'press cancel, but completes anyway' - what was your sure fire method for that?

**Comment by jonboiser** [comment]
At the moment, press cancel seems to be consistently ignored when actually importing content from Studio. The cancel request does seem to go through at the metadata DB-download stage, which wasn't happening when I last checked.

**Comment by rtibbles** [comment]
I've probably missed another event rename, will check that also.

**Comment by rtibbles** [comment]
The inability to cancel content import is actually a slightly subtle iceqube bug that was missed in testing. Will be switching gears to fix the iceqube bug and then add an upgrade to this PR.

**Comment by rtibbles** [comment]
This should now fix the cancellation issues described above!

**Comment by lyw07** [comment]
I cancelled the work when importing a channel (downloading the database) from studio but got an error. Is this expected?

```
INFO     Downloading data for channel id 1ceff53605e55bef987d88e0908658c5

ERROR    An error occurred during channel import: [Errno 2] No such file or directory: '/Users/lingyiwang/.kolibri/content/databases/1ceff53605e55bef987d88e0908658c5.sqlite3'
ERROR    Job a529b3bd4f9a4078883825d17b263416 raised an exception: Traceback (most recent call last):
  File "kolibri/dist/iceqube/worker.py", line 63, in handle_finished_future
    result = future.result()
  File "kolibri/dist/py2only/concurrent/futures/_base.py", line 422, in result
    return self.__get_result()
  File "kolibri/dist/py2only/concurrent/futures/thread.py", line 62, in run
    result = self.fn(*self.args, **self.kwargs)
  File "kolibri/dist/iceqube/worker.py", line 208, in wrap
    raise e
OSError: [Errno 2] No such file or directory: '/Users/lingyiwang/.kolibri/content/databases/1ceff53605e55bef987d88e0908658c5.sqlite3'
```

Screen Shot 2019-06-04 at 4 36 01 PM

**Comment by rtibbles** [comment]
No - that seems like an issue that I thought I had fixed.

File: kolibri/core/content/management/commands/importchannel.py [hunk 2]
```diff
@@ -120,21 +120,22 @@ def _start_file_transfer(self, filetransfer, channel_id, dest):
...
-                    import_channel_by_id(channel_id, self.is_cancelled)
-                except channel_import.ImportCancelError:
-                    # This will only occur if is_cancelled is True.
-                    pass
                 if self.is_cancelled():
                     try:
                         os.remove(dest)
-                    except IOError as e:
+                    except OSError as e:
                         logger.error(
```
Comment (lyw07) [inline kolibri/core/content/management/commands/importchannel.py]: I wonder if it's going to make more sense here to display the message as info instead of an error message.
in the current code, when cancelling channel import (database download), although in the UI everything looks great, errors will be shown in the log file, which may be confusing to users or developers who look at the log file to debug other issues.
```
ERROR    Tried to remove /Users/lingyiwang/.kolibri/content/databases/a9b25ac9814742c883ce1b0579448337.sqlite3, but exception [Errno 2] No such file or directory: '/Users/lingyiwang/.kolibri/content/databases/a9b25ac9814742c883ce1b0579448337.sqlite3' occurred.
```

File: kolibri/core/content/management/commands/importchannel.py [hunk 3]
```diff
@@ -120,21 +120,22 @@ def _start_file_transfer(self, filetransfer, channel_id, dest):
...
                             "Tried to remove {}, but exception {} occurred.".format(
                                 dest, e
                             )
                         )
                     self.cancel()
```
Comment (lyw07) [inline kolibri/core/content/management/commands/importchannel.py]: another thing I notice is that during this cancel() call, an exception will be raised, which will be caught in line 141. probably from iceqube?
so in the log file, it has
```
ERROR    An error occurred during channel import: 
```
I wonder if we can add `return True` after the cancel() call.

File: kolibri/core/content/management/commands/importchannel.py (hunk 2 above)
Comment (rtibbles) [reply kolibri/core/content/management/commands/importchannel.py]: Yeah - it's intended behaviour, so we shouldn't error.

File: kolibri/core/content/management/commands/importchannel.py (hunk 3 above)
Comment (rtibbles) [reply kolibri/core/content/management/commands/importchannel.py]: I am not actually sure what the point of that cancel call is, except to cause an error, so I have just deleted it.

**Comment by rtibbles** [comment]
Also fixes #5621 (which was caused by this PR, I believe).

**Comment by lyw07** [comment]
Do we only use iceqube with sqlite? 
When I set the database engine to be postgresql, I got this error when I started kolibri:
```
Traceback (most recent call last):
  File "/usr/local/Cellar/python/3.7.3/Frameworks/Python.framework/Versions/3.7/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/local/Cellar/python/3.7.3/Frameworks/Python.framework/Versions/3.7/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/usr/local/lib/python3.7/site-packages/kolibri/__main__.py", line 11, in <module>
    main(args=sys.argv[1:])
  File "/usr/local/lib/python3.7/site-packages/kolibri/utils/cli.py", line 711, in main
    start(port, daemon=daemon)
  File "/usr/local/lib/python3.7/site-packages/kolibri/utils/cli.py", line 333, in start
    server.start(port=port, run_cherrypy=run_cherrypy)
  File "/usr/local/lib/python3.7/site-packages/kolibri/utils/server.py", line 102, in start
    run_services()
  File "/usr/local/lib/python3.7/site-packages/kolibri/utils/server.py", line 85, in run_services
    from kolibri.core.tasks.queue import get_queue
  File "/usr/local/lib/python3.7/site-packages/kolibri/core/tasks/queue.py", line 57, in <module>
    queue = Queue(app, connection=connection)
  File "/usr/local/lib/python3.7/site-packages/kolibri/dist/iceqube/queue.py", line 11, in __init__
    self.storage = Storage(app, app, connection)
  File "/usr/local/lib/python3.7/site-packages/kolibri/dist/iceqube/storage.py", line 57, in __init__
    Base.metadata.create_all(self.engine)
  File "/usr/local/lib/python3.7/site-packages/kolibri/dist/sqlalchemy/sql/schema.py", line 4005, in create_all
    tables=tables)
  File "/usr/local/lib/python3.7/site-packages/kolibri/dist/sqlalchemy/engine/base.py", line 1939, in _run_visitor
    with self._optional_conn_ctx_manager(connection) as conn:
  File "/usr/local/Cellar/python/3.7.3/Frameworks/Python.framework/Versions/3.7/lib/python3.7/contextlib.py", line 112, in __enter__
    return next(self.gen)
  File "/usr/local/lib/python3.7/site-packages/kolibri/dist/sqlalchemy/engine/base.py", line 1932, in _optional_conn_ctx_manager
    with self.contextual_connect() as conn:
  File "/usr/local/lib/python3.7/site-packages/kolibri/dist/sqlalchemy/engine/base.py", line 2123, in contextual_connect
    self._wrap_pool_connect(self.pool.connect, None),
  File "/usr/local/lib/python3.7/site-packages/kolibri/dist/sqlalchemy/engine/base.py", line 2158, in _wrap_pool_connect
    return fn()
  File "/usr/local/lib/python3.7/site-packages/kolibri/dist/sqlalchemy/pool.py", line 403, in connect
    return _ConnectionFairy._checkout(self)
  File "/usr/local/lib/python3.7/site-packages/kolibri/dist/sqlalchemy/pool.py", line 791, in _checkout
    fairy = _ConnectionRecord.checkout(pool)
  File "/usr/local/lib/python3.7/site-packages/kolibri/dist/sqlalchemy/pool.py", line 532, in checkout
    rec = pool._do_get()
  File "/usr/local/lib/python3.7/site-packages/kolibri/dist/sqlalchemy/pool.py", line 1196, in _do_get
    self._dec_overflow()
  File "/usr/local/lib/python3.7/site-packages/kolibri/dist/sqlalchemy/util/langhelpers.py", line 66, in __exit__
    compat.reraise(exc_type, exc_value, exc_tb)
  File "/usr/local/lib/python3.7/site-packages/kolibri/dist/sqlalchemy/util/compat.py", line 249, in reraise
    raise value
  File "/usr/local/lib/python3.7/site-packages/kolibri/dist/sqlalchemy/pool.py", line 1193, in _do_get
    return self._create_connection()
  File "/usr/local/lib/python3.7/site-packages/kolibri/dist/sqlalchemy/pool.py", line 350, in _create_connection
    return _ConnectionRecord(self)
  File "/usr/local/lib/python3.7/site-packages/kolibri/dist/sqlalchemy/pool.py", line 477, in __init__
    self.__connect(first_connect_check=True)
  File "/usr/local/lib/python3.7/site-packages/kolibri/dist/sqlalchemy/pool.py", line 686, in __connect
    pool.dispatch.connect(self.connection, self)
  File "/usr/local/lib/python3.7/site-packages/kolibri/dist/sqlalchemy/event/attr.py", line 284, in __call__
    fn(*args, **kw)
  File "/usr/local/lib/python3.7/site-packages/kolibri/dist/iceqube/storage.py", line 92, in _pragmas_on_connect
    dbapi_con.execute("PRAGMA journal_mode = WAL;")
AttributeError: 'psycopg2.extensions.connection' object has no attribute 'execute'
```

I tested it by installing the whl file from this PR.

**Comment by rtibbles** [comment]
Oh, interesting - I had extended iceqube to allow postgres as a backend, but looks like we need to conditionally set the pragmas only if we are using SQLite. Thanks for the test, that's saved some work on the cloud kolibri side!

**Review by lyw07 — APPROVED** [review]
tested importing, exporting and deleting channels when using sqlite and postgresql. everything works!
