### PR TITLE
kolibri studio no of remote channel issue resolved

### LINKED ISSUE #10931: Remote browsing - Several UX issues
## Observed behavior
Noticed several UX issues while comparing the current implementation to what we have in [Figma](https://www.figma.com/file/MpCG7r5PULOCJsEvnTSti8/Android-Designs-2022?type=design&node-id=194-2922&mode=design).

## Expected behavior
Should be further discussed /changes made.

## Steps to reproduce the issue
1. Install the latest develop build
2. Navigate to Library > Explore libraries

## More information

| Issue| Screenshot |
:-------------------------:|:-------------------------:
| RESOLVED in https://github.com/learningequality/kolibri/pull/11090 ~Library > Other libraries - Design differences~ | 
| (WIP in https://github.com/learningequality/kolibri/pull/11097) Library > Other libraries - Design differences | |
| RESOLVED in https://github.com/learningequality/kolibri/pull/11100 ~Library > View all libraries - Missing number of available channels~ |   |
| RESOLVED in https://github.com/learningequality/kolibri/pull/10974 ~Library > Explore libraries - Missing Search pane, Language filter displayed to the right and ‘All libraries’ link to go back~ |  |

## Usage Details
Kolibri 0.16alfa17
Windows 10, Ubuntu - Chrome

### PR DESCRIPTION
**Pull request by GarvitSinghal47**
#10931 
## Summary
Added the no of remote channel line under the library .

Before :

[channelnobefore.webm](https://github.com/learningequality/kolibri/assets/82756460/48036f1b-6850-4a93-8106-f7b52a6fc184)

After :

[channelnoafter.webm](https://github.com/learningequality/kolibri/assets/82756460/80e2dc96-1534-45f3-8321-ac37d7ea5ed8)

…

## References

…

## Reviewer guidance

…

----

## Testing checklist

- [ ] Contributor has fully tested the PR manually
- [ ] If there are any front-end changes, before/after screenshots are included
- [ ] Critical user journeys are covered by Gherkin stories
- [ ] Critical and brittle code paths are covered by unit tests

## PR process

- [ ] PR has the correct target branch and milestone
- [ ] PR has 'needs review' or 'work-in-progress' label
- [ ] If PR is ready for review, a reviewer has been added. (Don't use 'Assignees')
- [ ] If this is an important user-facing change, PR or related issue has a 'changelog' label
- [ ] If this includes an internal dependency change, a link to the diff is provided

## Reviewer checklist

- Automated test coverage is satisfactory
- PR is fully functional
- PR has been tested for [accessibility regressions](http://kolibri-dev.readthedocs.io/en/develop/manual_testing.html#accessibility-a11y-testing)
- External dependency files were updated if necessary (`yarn` and `pip`)
- Documentation is updated
- Contributor is in AUTHORS.md

### CODE REVIEW

File: kolibri/plugins/learn/assets/src/views/LibraryPage/PinnedNetworkResources.vue [hunk 1]
```diff
@@ -7,11 +7,17 @@
...
       :key="device.id"
     >
+
       <KGridItem>
         <h2>
           <KIcon :icon="getDeviceIcon(device)" />
           <span class="device-name">{{ device.device_name }}</span>
         </h2>
+        <p>
+                  {{ totalRemoteChannelsCount }} channels |
```
Comment (rtibbles) [inline kolibri/plugins/learn/assets/src/views/LibraryPage/PinnedNetworkResources.vue]: Hi @GarvitSinghal47 thanks for this update - one thing to flag is that in order to ensure that user facing text is appropriately translated, we do not put text directly into the template in this way, but rather use references to specific messages (which can then be swapped out for the message in the correct language for the user).

Unfortunately, the message you are trying to render here has only been included in a different component, due to some poor planning on our part! You can see the message here: https://github.com/learningequality/kolibri/blob/release-v0.16.x/kolibri/plugins/learn/assets/src/views/ExploreLibrariesPage/LibraryItem.vue#L170

To handle this, we have a workaround which allows us to import and reuse a string from another component in a different component. See here for another example where we are using it to get strings from the LibraryItem component: https://github.com/learningequality/kolibri/blob/06d6c8961c66625822f5855d089cc82c1a9f5f7f/kolibri/plugins/learn/assets/src/views/ExploreLibrariesPage/index.vue#L84

It should be used similarly here, with the `totalRemoteChannelsCount` passed in the second argument: `PinStrings.$tr('channels', { channels: totalRemoteChannelsCount })` (you can also just expose this as a computed prop on the component to avoid having to reference `PinStrings` in the template). Note that the first argument to the `$tr` method is the message identifier, and the second is an object that passes in values to be interpolated into the string.

**Review by rtibbles — DISMISSED** [review]
Just need to make sure that we are using the translated string!

**Comment by MisRob** [comment]
Thank you, @GarvitSinghal47. We noticed one more thing here that I will need to look into in more detail than I can manage now so I will return to it on Monday.

**Review by MisRob — CHANGES_REQUESTED** [review]
Hi again, @GarvitSinghal47, this is a good start, thank you! Due to the similarity of some places in Kolibri Library, during the first review we didn't notice a few things, apologies. There will be a few updates needed.

(1) **The issue reported in https://github.com/learningequality/kolibri/issues/10931 is related to the missing number of available channels on the "All libraries" page rather than on the root "Library" page.** I double-checked designs and we don't want to show the number on the root "Library" page like implemented in this PR. You can follow the guidance in the issue to navigate to the right place, however you'd need to have some other devices on your network to have "View all" button available like here

all-libs

Alternatively, I think that navigating to http://localhost:8000/en/learn/#/explore_libraries?prevName=LIBRARY should do, too.

(2) **We only want to display the number of channels for Kolibri Library (Studio) library rather than the total number of channels on remote devices.**

Let me know if you needed some help with setting up another device on your network. It's not that complicated and we can support. It might be useful for you to be able to navigate everywhere and also to check that the correct number is calculated.

**Comment by GarvitSinghal47** [comment]
> Hi again, @GarvitSinghal47, this is a good start, thank you! Due to the similarity of some places in Kolibri Library, during the first review we didn't notice a few things, apologies. There will be a few updates needed.
> 
> (1) **The issue reported in #10931 is related to the missing number of available channels on the "All libraries" page rather than on the root "Library" page.** I double-checked designs and we don't want to show the number on the root "Library" page like implemented in this PR. You can follow the guidance in the issue to navigate to the right place, however you'd need to have some other devices on your network to have "View all" button available like here
> 
> all-libs
> 
> Alternatively, I think that navigating to http://localhost:8000/en/learn/#/explore_libraries?prevName=LIBRARY should do, too.
> 
> (2) **We only want to display the number of channels for Kolibri Library (Studio) library rather than the total number of channels on remote devices.**
> 
> Let me know if you needed some help with setting up another device on your network. It's not that complicated and we can support. It might be useful for you to be able to navigate everywhere and also to check that the correct number is calculated.

Oh i realized now after seeing the design docs i have done it in the wrong place, will  move it to all library page .

@MisRob i need help in setting it up in my network as while i am trying to access this on my wifi with the url given in device then info , i was able to get the url but the problem i am facing in both my other laptop and the mobile is that the loading page is just appearing and not forwarding to auth page .

and when i inspect the page it is showing err connection refused and uncaught reference error : kolibricore app global is not defined.
and when i run it in the same laptop where localhost is running then it is working fine .

i have tried removing all security related thing of browser and the security software of my laptop as well.

can you tell me what is the issue and how to resolve it .

**Comment by MisRob** [comment]
> i need help in setting it up in my network ...

@GarvitSinghal47 just to clarify, you're doing this so you can see more devices in the Library, is that correct?

**Comment by MisRob** [comment]
I will need to move to something else in a moment, so if that's case, I'd recommend a simpler way of running another device alongside your dev server, just one laptop needed :)

You can download pex file from one of the latest [Build Assets](https://github.com/learningequality/kolibri/actions/workflows/pr_build_kolibri.yml)(if you can access the page), for example this one https://github.com/learningequality/kolibri/suites/15341352681/artifacts/876105184. Then unzip the file and run `KOLIBRI_HOME="kolibri-home" python <filename>.pex start` (you can choose any location for `KOLIBRI_HOME`, just don't forget to set it so that you don't override your default .kolibri). This will run another Kolibri instance. In the terminal, you will find its URL. Follow it and do the initial device setup as usual, and also import few resources from some channels. Then, when you run your development server as usual, you should see this other device on your network. When you're done, you can run `KOLIBRI_HOME="kolibri-home" python <filename>.pex stop` to stop the other Kolibri instance. 

---

When it comes to ` uncaught reference error : kolibricore app global`, what usually helps me is to restart the server or rebuild frontend assets, but I think it might be easier to try to follow the steps above. That's how we commonly do it and I rarely experience issues. Let us know how it goes.

**Comment by GarvitSinghal47** [comment]
> > i need help in setting it up in my network ...
> 
> @GarvitSinghal47 just to clarify, you're doing this so you can see more devices in the Library, is that correct?

Yes , to see more devices .

**Comment by GarvitSinghal47** [comment]
updated video after changes in description

File: kolibri/plugins/learn/assets/src/views/ExploreLibrariesPage/index.vue [hunk 2]
```diff
@@ -25,9 +25,9 @@
       :deviceName="device['device_name']"
       :deviceIcon="getDeviceIcon(device)"
       :channels="device.channels"
-      :totalChannels="device['total_channels']"
+      :totalChannels="device['total_count']"
```
Comment (MisRob) [inline kolibri/plugins/learn/assets/src/views/ExploreLibrariesPage/index.vue:28]: Good catch. Could you also please update line 54 in this way? It still uses non-existing `total_channels` property too,

File: kolibri/plugins/learn/assets/src/views/ExploreLibrariesPage/index.vue [hunk 3]
```diff
@@ -25,9 +25,9 @@
...
       :pinIcon="getPinIcon(true)"
-      :disablePinDevice="device['instance_id'] === studioId"
```
Comment (MisRob) [inline kolibri/plugins/learn/assets/src/views/ExploreLibrariesPage/index.vue:30]: This change is perfectly aligned with the designs, but let me check with the team at first before we merge it because disabling pinning the Kolibri Library here is looking pretty intentional so now I am not clear if the deviation from the designs had a reason or if it's just our oversight.

Comment (rtibbles) [reply kolibri/plugins/learn/assets/src/views/ExploreLibrariesPage/index.vue:30]: Let's revert this change - the designs are out of date, and this should indeed be disabled instead.

**Review by MisRob — APPROVED** [review]
Thank you @GarvitSinghal47
