### PR TITLE
Fix #11891 Enhanced Input Mode Detection for Hybrid Devices

### LINKED ISSUE #11891: Keyboard input in perseus does not work with touchscreen devices
Spotted by @jamalex during the 0.16 sync session on Feb 14 2024

## Observed behavior
When using a touch-screen device (such as a laptop that features a touch screen), our implementation of perseus currently does not accept the option for both touch and keyboard input. Perseus requires us to set whether it's a mobile display, and we use `isTouch` to do this. When set to mobile display, clicking on text input boxes in an exercise does not set focus or allow text to be entered.

## Expected behavior
We should update the condition to `isTouch && !isKeyboardAndMouse` in order to set whether it is a mobile display.

## Context
0.16.x

### PR DESCRIPTION
**Pull request by poju3185**
## Summary
Fix #11891
This Pull Request introduces an enhancement to the input mode detection logic for devices with both touch and mouse inputs. The core of this update is a global mouse click listener across the app, ensuring that once a mouse click is detected, Perseus will consistently render in standard mode. This approach simplifies the input mode logic and provides a more predictable user experience on hybrid devices.

## References
https://stackoverflow.com/a/70827986  provided by @rtibbles 

## Reviewer guidance

1. On a hybrid device or using device emulation, open the app and navigate to a Perseus exercise.
2. Initially use touch input to interact with the app and observe Perseus rendering in mobile mode.
3. Click anywhere in the app using the mouse or trackpad.
4. Navigate to the same or a different Perseus exercise and verify that it now renders in standard mode, reflecting the detected mouse input.
5. Attempt to switch back to touch input and observe that Perseus continues to render in standard mode, demonstrating the mouse input precedence.

https://github.com/learningequality/kolibri/assets/81625625/a0f82eb1-1525-411a-a5b5-4b1b130d7892

----

## Testing checklist

- [x] Contributor has fully tested the PR manually
- [ ] If there are any front-end changes, before/after screenshots are included
- [ ] Critical user journeys are covered by Gherkin stories
- [ ] Critical and brittle code paths are covered by unit tests

## PR process

- [ ] PR has the correct target branch and milestone
- [ ] PR has 'needs review' or 'work-in-progress' label
- [ ] If PR is ready for review, a reviewer has been added. (Don't use 'Assignees')
- [ ] If this is an important user-facing change, PR or related issue has a 'changelog' label
- [ ] If this includes an internal dependency change, a link to the diff is provided

## Reviewer checklist

- Automated test coverage is satisfactory
- PR is fully functional
- PR has been tested for [accessibility regressions](http://kolibri-dev.readthedocs.io/en/develop/manual_testing.html#accessibility-a11y-testing)
- External dependency files were updated if necessary (`yarn` and `pip`)
- Documentation is updated
- Contributor is in AUTHORS.md

### CODE REVIEW

**Comment by rtibbles** [comment]
Sorry @poju3185, I forgot to mention that we are targeting this fix to 0.16. I have retargeted the PR (please ignore the diff from that). Please follow the instructions here: https://kolibri-dev.readthedocs.io/en/develop/howtos/rebasing_a_pull_request.html
To rebase your pull request onto the release-v0.16.x branch.

**Comment by poju3185** [comment]
No worries. I've already rebased the pull request onto the release-v0.16.x branch as instructed. Thank you for the guidance!

File: kolibri/core/assets/src/kolibri_app.js [hunk 1]
```diff
@@ -58,6 +58,12 @@ export default class KolibriApp extends KolibriModule {
     return {};
   }
 
+  handlePointerDown(event) {
```
Comment (rtibbles) [inline kolibri/core/assets/src/kolibri_app.js]: I think I would rather move all of this logic into the browserInfo.js module - and create a simple exportable boolean in there `mousePointerUsed` or something like that.

This can be initialized from the localStorage initially, and then we can update both the localStorage and the value when the condition below happens.

File: kolibri/core/assets/src/kolibri_app.js [hunk 2]
```diff
@@ -110,6 +116,10 @@ export default class KolibriApp extends KolibriModule {
         ...this.stateSetters.map(setter => setter(this.store)),
       ]).then(() => {
         this.startRootVue();
+        window.addEventListener('pointerdown', this.handlePointerDown.bind(this));
```
Comment (rtibbles) [inline kolibri/core/assets/src/kolibri_app.js]: This can be done in the module level of browserInfo.js - it will only get executed once, so it feels safe to me.

In terms of unbinding, once we have detected this once, we don't need to be checking any more, so at that point we could remove the event listener.

File: kolibri/plugins/perseus_viewer/assets/src/views/PerseusRendererIndex.vue [hunk 3]
```diff
@@ -144,7 +144,7 @@
         return this.windowBreakpoint < 3;
       },
       usesTouch() {
-        return isTouchDevice;
+        return isTouchDevice && localStorage.getItem('mouseUsed') !== 'true';
```
Comment (rtibbles) [inline kolibri/plugins/perseus_viewer/assets/src/views/PerseusRendererIndex.vue]: As I commented above, let's add a browserInfo exportable variable that will define this value - so that the implementation details are hidden from the code consumer here.

**Review by rtibbles — DISMISSED** [review]
This definitely works, but I think I'd rather make the API a bit more explicit and hide the implementation details from the API consumer.

**Comment by poju3185** [comment]
I've made the updates, please notice that `isMouseUsed` is implemented as a function rather than a constant because its value may change over time.

File: kolibri/core/assets/src/utils/browserInfo.js [hunk 4]
```diff
@@ -69,3 +69,16 @@ export const isTouchDevice =
...
+function handlePointerDown(event) {
+  if (event.pointerType === 'mouse') {
+    localStorage.setItem('mouseUsed', 'true');
+    window.removeEventListener('pointerdown', handlePointerDown);
+  }
+}
+
+window.addEventListener('pointerdown', handlePointerDown);
+
+export function isMouseUsed() {
```
Comment (rtibbles) [inline kolibri/core/assets/src/utils/browserInfo.js]: One of the nice things about Javascript exports is that they are referential - this has the nice effect of being able to export dynamic variables from a module.

This means that we don't have to have `isMouseUsed` as a function, instead it can be initialized as:

```
export let isMouseUsed = localStorage.getItem('mouseUsed') === 'true';
```

File: kolibri/core/assets/src/utils/browserInfo.js [hunk 5]
```diff
@@ -69,3 +69,16 @@ export const isTouchDevice =
   'ontouchstart' in window ||
   window.navigator?.maxTouchPoints > 0 ||
   window.navigator?.msMaxTouchPoints > 0;
+
+function handlePointerDown(event) {
+  if (event.pointerType === 'mouse') {
+    localStorage.setItem('mouseUsed', 'true');
```
Comment (rtibbles) [inline kolibri/core/assets/src/utils/browserInfo.js:75]: Then in here we can do this and:
```
isMouseUsed = true;
```

**Review by rtibbles — COMMENTED** [review]
Just one last thing to have a referent rather than a function for `isMouseUsed`.

**Comment by poju3185** [comment]
I've made the suggested change to initialize isMouseUsed using the export with the dynamic variable approach. Now the code looks better.

**Review by rtibbles — COMMENTED** [review]
This looks good! I'll ask our QA team to give it a quick test if possible, just to make sure it's all working as intended.

**Comment by pcenov** [comment]
Hi @rtibbles - I've just tested this on a Chromebook laptop and I can confirm that I can input an answer both when using the touch screen or the trackpad. However when using only the touch screen I still have to type the answer using the physical keyboard of the device while I was expecting to see the onscreen numeric keyboard. The same is valid when I flip the physical keyboard of the Chromebook and start using it as a tablet in which case instead of seeing the onscreen numeric keyboard I see the normal digital keyboard.

**Comment by rtibbles** [comment]
Thanks @pcenov - I think what you describe is sufficient to fix the issue at hand (being able to input at all in this scenario) but we can file a follow up issue for the behaviour that is more responsive to the current state of the device. This more responsive functionality will be significantly harder to implement.

**Comment by rtibbles** [comment]
Follow up filed here: https://github.com/learningequality/kolibri/issues/12016

**Review by rtibbles — APPROVED** [review]
Great work, thank you!
