### PR TITLE
Many numerals are not localized

### LINKED ISSUE #2788: many numerals are not localized
### Observed behavior

for example...

* Percentage imported during content import
* How many users you are going to add to a class
* Choose number of questions when creating an exam
  * image
* Showing how many people are in a class
  * image
* Validating the number of characters in a text field
  * image

...there are likely many more and we should do a thorough audit.

### Expected behavior

All numbers should be localized.

### User-facing consequences

Unintelligible numbers in many cases

### PR DESCRIPTION
**Pull request by mrpau-richard**
### Summary

 * Make the numerals to be localized.

### References
This fixes #2788 

### Contributor Checklist

- [x] PR has the correct target branch and milestone
- [x] PR has 'needs review' or 'work-in-progress' label
- [x] Contributor has fully tested the PR manually
- [ ] Screenshots of any front-end changes are in the PR description
- [ ] If PR is ready for review, a reviewer has been added. (Don't use 'Assignees')

### Reviewer Checklist

- [ ] Automated test coverage is satisfactory
- [ ] Reviewer has fully tested the PR manually
- [ ] PR has been tested for [accessibility regressions](http://kolibri-dev.readthedocs.io/en/develop/manual_testing.html#accessibility-a11y-testing)
- [ ] External dependencies files were updated (`yarn` and `pip`)
- [ ] Documentation is updated
- [ ] Link to diff of internal dependency change is included
- [ ] CHANGELOG.rst is updated for high-level changes
- [ ] Contributor is in AUTHORS.rst

### CODE REVIEW

File: kolibri/plugins/facility_management/assets/src/views/user-page/edit-user-modal.vue [hunk 1]
```diff
@@ -30,7 +30,7 @@
         ref="username"
         type="text"
         :label="$tr('username')"
-        :maxlength="30"
+        :maxlength="$tr('userMaxLength', { userMaxLength: 30 })"
```
Comment (benjaoming) [inline kolibri/plugins/facility_management/assets/src/views/user-page/edit-user-modal.vue]: Is this used as an an HTML attribute also? `<input type="text" maxlength="123">` ? Because in that case, translating it is a bad idea, it would have to be separated into two different properties...

Comment (indirectlylit) [reply kolibri/plugins/facility_management/assets/src/views/user-page/edit-user-modal.vue]: Good catch, yes. `maxlength` is a programmatic attribute, not a user-facing string.

File: kolibri/plugins/facility_management/assets/src/views/user-page/edit-user-modal.vue [hunk 2]
```diff
@@ -79,6 +79,8 @@
   export default {
     name: 'editUserModal',
     $trs: {
+      nameMaxLength: '{nameMaxLength, number, integer}',
```
Comment (rtibbles) [inline kolibri/plugins/facility_management/assets/src/views/user-page/edit-user-modal.vue]: As the strings here have no content apart from the number, they are not necessary, instead you can directly invoke `$formatNumber` rather than `$tr`: https://www.npmjs.com/package/vue-intl#formatnumber

Comment (indirectlylit) [reply kolibri/plugins/facility_management/assets/src/views/user-page/edit-user-modal.vue]: Neat, didn't know that existed!

Note that this particular string is another instance of the [comment above](maxlength) and needs no localization at all.

Comment (rtibbles) [reply kolibri/plugins/facility_management/assets/src/views/user-page/edit-user-modal.vue]: I have tried to enforce it, but evidently it has not caught on :)

https://github.com/learningequality/kolibri/search?utf8=%E2%9C%93&q=%24formatNumber&type=

Comment (mrpau-richard) [reply kolibri/plugins/facility_management/assets/src/views/user-page/edit-user-modal.vue]: @rtibbles & @indirectlylit  I already used the `$formatNumber` and it worked. The only task remaining is how I can localised the [valueLength](https://github.com/learningequality/Keen-UI/blob/17911401dff3d65f78bc1edbc32acf675864da03/src/UiTextbox.vue#L84)

Comment (indirectlylit) [reply kolibri/plugins/facility_management/assets/src/views/user-page/edit-user-modal.vue]: @mrpau-richard please read the comments from me and @benjaoming again, and ping me in slack if you have questions.

The `maxlength` property of text boxes is _not_ a user-facing string and should _not_ be localized.

Comment (indirectlylit) [reply kolibri/plugins/facility_management/assets/src/views/user-page/edit-user-modal.vue]: > The only task remaining is how I can localised the valueLength

I created a new issue for this here: #3141

That one will be a little more complicated because we may need to fork the keen textbox component. (cc @christianmemije)

**Comment by mrpau-richard** [comment]
@indirectlylit I already removed the localized maxlength. Lets localized it after we fix the #3141

**Comment by indirectlylit** [comment]
thanks @mrpau-richard!
