### PR TITLE
Fix flash of unstyled text (FOUT) on login page

### LINKED ISSUE #7487: flash of unstyled text on login page
### Observed behavior

FOUT observed in both safari and chrome on mac, specifically on the login page:

### Expected behavior

fout-free

### User-facing consequences

* slightly ugly behavior
* regression from 0.13

### Steps to reproduce

refresh 

### Context

0.14.3

### PR DESCRIPTION
**Pull request by rtibbles**
## Summary

Fix flash of unstyled text (FOUT) on login page.

`font-display: swap` tells the browser to immediately show text in a system font, then swap to the web font once loaded. This applies even to the subset/common fonts that are inlined as data URIs in the HTML head — despite decoding almost instantly, the browser still briefly renders system fonts before swapping, causing a visible flash.

Changing subset/common fonts to `font-display: fallback` instead blocks rendering briefly (~100ms) to allow the data URI decode to complete, which eliminates the flash. Full fonts (loaded as separate files) keep `swap` since they genuinely need background loading time.

Previously, browsers supporting `font-display: swap` used `loadFullFontsImmediately()`, which added the `full-fonts-loaded` class right away and relied on the browser's native swap behavior — this was actually the source of the FOUT. Browsers *without* swap support used FontFaceObserver-based progressive loading, which ironically produced better results by waiting for fonts to fully load before switching. Now all browsers use the progressive FontFaceObserver path. The browser capability check is still used to select the appropriate CSS file, but the loading strategy no longer needs to differ.

## References

Closes #7487

## Reviewer guidance

- The bulk of the diff is regenerated font CSS files (`kolibri/core/static_fonts/`) — the only meaningful changes are in `build_tools/i18n/fonts.py` and `packages/kolibri/utils/internal/setupAndLoadFonts.js`.
- To test: load the Mac app and watch for a flash of system fonts before Noto renders on the login page. The flash should be gone.
- `font-display: fallback` has a ~3s swap window — on very slow connections, if the data URI decode somehow exceeds this, text would stay in system fonts rather than swapping late. This is the intended tradeoff.

## AI usage

Claude Code implemented the fix and regenerated font CSS files. Changes were reviewed for correctness and unnecessary complexity before committing.

### CODE REVIEW

File: packages/kolibri/utils/internal/setupAndLoadFonts.js [hunk 1]
```diff
@@ -87,9 +83,12 @@ function addFontStylesheetLink(href) {
...
-    loadFullFontsImmediately();
   } else {
     addFontStylesheetLink(plugin_data.fullCSSFileBasic);
-    loadFullFontsProgressively();
   }
+  // Always use progressive loading to prevent FOUT. This works in combination with
+  // font-display: fallback on subset/common fonts (prevents initial flash) and
+  // font-display: swap on full fonts (allows graceful background loading).
+  // We explicitly control when to switch from subset to full fonts.
+  loadFullFontsProgressively();
```
Comment (rtibblesbot) [inline packages/kolibri/utils/internal/setupAndLoadFonts.js:93]: **praise:** Moving `loadFullFontsProgressively()` outside the if/else so all browsers use it is the key fix. The old code's `loadFullFontsImmediately()` for modern browsers was the root cause — it added `full-fonts-loaded` before fonts were actually ready, defeating the purpose of the subset fonts.

File: build_tools/i18n/fonts.py [hunk 2]
```diff
@@ -113,9 +113,18 @@
 }
 
 
-def _gen_font_face(family, url, weight, unicodes):
+def _gen_font_face(family, url, weight, unicodes, display="swap"):
```
Comment (rtibblesbot) [inline build_tools/i18n/fonts.py:116]: **praise:** Good API design — making `display` a parameter with `swap` as default keeps full fonts on `swap` without changing any call sites, while letting `_write_inline_font` explicitly pass `fallback` for the subset/common case.

File: build_tools/i18n/fonts.py [hunk 3]
```diff
@@ -505,6 +514,7 @@ def _write_inline_font(file_object, font_path, font_family, weight):
             url=data_uri,
             weight=weight,
             unicodes=_fmt_range(glyphs),
+            display="fallback",  # Use fallback for subset/common fonts to prevent FOUT
```
Comment (rtibblesbot) [inline build_tools/i18n/fonts.py:517]: **nitpick:** The comment is helpful but could note that `fallback` has a ~100ms block period followed by a ~3s swap window, which is why it works well for data-URI fonts that decode near-instantly but would be risky for network-loaded fonts.

**Review by rtibblesbot — COMMENTED** [review]
Clean, well-targeted fix for a long-standing FOUT regression (#7487). The two meaningful source changes are correct and the approach is sound.

CI passing. No UI files changed beyond generated font CSS — Phase 3 skipped.

- **suggestion:** The PR targets `release-v0.19.x` rather than `develop`. The PR description mentions #7487, which is a regression from v0.14. Is this intentional for a point release, or should it target `develop`?
- **praise:** Good decision to unify all browsers onto the progressive FontFaceObserver path — the old split where modern browsers used `loadFullFontsImmediately()` was the actual source of the FOUT, and the explanation in the PR description is clear.

---
_@rtibblesbot's comments are generated by an LLM, and should be evaluated accordingly_

<details><summary>How was this generated?</summary>

Reviewed the pull request diff checking for:
- **Correctness:** bugs, edge cases, undocumented behavior, resource leaks, hardcoded values
- **Design:** unnecessary complexity, naming, readability, comment accuracy, redundant state
- **Architecture:** duplicated concerns, minimal interfaces, composition over inheritance
- **Testing:** behavior-based assertions, mocks only at hard boundaries, accurate coverage
- **Completeness:** missing dependencies, unupdated usages, i18n, accessibility, security
- **Principles:** DRY (same reason to change), SRP, Rule of Three (no premature abstraction)
- Checked CI status and linked issue acceptance criteria
- For UI changes: inspected screenshots for layout, visual completeness, and consistency

</details>

File: build_tools/i18n/fonts.py (hunk 3 above)
Comment (rtibbles) [reply build_tools/i18n/fonts.py:517]: Yes, we are only using it for data-URI fonts.

**Comment by rtibbles** [comment]
> The PR targets release-v0.19.x rather than develop. The PR description mentions https://github.com/learningequality/kolibri/issues/7487, which is a regression from v0.14. Is this intentional for a point release, or should it target develop?

This is a long overdue regression fix, it's low risk and eminently testable, perfect for a patch release.

**Review by pcenov — APPROVED** [review]
Thanks @rtibbles, LGTM - I'm not seeing a flash of system fonts before Noto renders on the login page.

**Review by akolson — APPROVED** [review]
Changes look correct to me! Thanks @rtibbles
