### PR TITLE
Exam lag fixes

### LINKED ISSUE #4159: Exam page has lag when I creating an exam
### Observed behavior
I observed the exam page was lag when I click the checkbox. When I click Stop it, theirs error message in console. 
Refer to Gherkin scenarios :
https://github.com/learningequality/kolibri/blob/gherkin-features/integration_testing/features/coach/coach-create-exams.feature
lag-error

error-msg

### Expected behavior

no lag when clicking the checkbox.

### Errors and logs
```
Error: Script terminated by timeout at:
get@http://127.0.0.1:8080/static/default_frontend/default_frontend-0.11.0a5.js:7:6674
exerciseIsSelected/<@http://127.0.0.1:8080/static/coach_module/coach_module-0.11.0a5.js:1:61791
exerciseIsSelected@http://127.0.0.1:8080/static/coach_module/coach_module-0.11.0a5.js:1:61751
allExercisesWithinTopicSelected@http://127.0.0.1:8080/static/coach_module/coach_module-0.11.0a5.js:1:61374
kolibriGlobal</</Le.prototype.get@http://127.0.0.1:8080/static/default_frontend/default_frontend-0.11.0a5.js:7:15849
kolibriGlobal</</Le.prototype.evaluate@http://127.0.0.1:8080/static/default_frontend/default_frontend-0.11.0a5.js:7:17006
$e/<@http://127.0.0.1:8080/static/default_frontend/default_frontend-0.11.0a5.js:7:18899
$e<@http://127.0.0.1:8080/static/coach_module/coach_module-0.11.0a5.js:1:62248
kolibriGlobal</</</t.prototype._render@http://127.0.0.1:8080/static/default_frontend/default_frontend-0.11.0a5.js:7:32600
kolibriGlobal</</fn.prototype.$mount/</<@http://127.0.0.1:8080/static/default_frontend/default_frontend-0.11.0a5.js:7:60780
kolibriGlobal</</Le.prototype.get@http://127.0.0.1:8080/static/default_frontend/default_frontend-0.11.0a5.js:7:15849
kolibriGlobal</</Le.prototype.run@http://127.0.0.1:8080/static/default_frontend/default_frontend-0.11.0a5.js:7:16740
Ae@http://127.0.0.1:8080/static/default_frontend/default_frontend-0.11.0a5.js:7:14878
Zt/<@http://127.0.0.1:8080/static/default_frontend/default_frontend-0.11.0a5.js:7:11350
Wt@http://127.0.0.1:8080/static/default_frontend/default_frontend-0.11.0a5.js:7:10852
kolibriGlobal</t.exports@http://127.0.0.1:8080/static/default_frontend/default_frontend-0.11.0a5.js:91:13652
@http://127.0.0.1:8080/static/default_frontend/default_frontend-0.11.0a5.js:91:10695
y@http://127.0.0.1:8080/static/default_frontend/default_frontend-0.11.0a5.js:91:10553
b@http://127.0.0.1:8080/static/default_frontend/default_frontend-0.11.0a5.js:91:10573
default_frontend-0.11.
```

### Context

Kolibri 0.11.0a5
windows 7 (64-bit)
Firefox 61.0.2 (64-bit)

### PR DESCRIPTION
**Pull request by rtibbles**
### Summary
Mitigates issues caused by adding large number of exercises to an exam by not allowing adding whole channels, and making navigable topics look more linky.

### Reviewer guidance
Can you create exams?
Can you still add whole topics?
Can you not add whole channels?
Do topics without any exercises get hidden?
Do channels without any exercises get hidden?

### References
Fixes #4159 

Before:
image

image

After:
image

image

----

### Contributor Checklist

- [x] Contributor has fully tested the PR manually
- [x] PR has the correct target branch and milestone
- [x] PR has 'needs review' or 'work-in-progress' label
- [x] If PR is ready for review, a reviewer has been added. (Don't use 'Assignees')
- [x] If there are any front-end changes, before/after screenshots are included
- [x] If this is an important user-facing change, PR or related issue has a 'changelog' label

### Reviewer Checklist

- [ ] Automated test coverage is satisfactory
- [ ] Reviewer has fully tested the PR manually
- [ ] PR has been tested for [accessibility regressions](http://kolibri-dev.readthedocs.io/en/develop/manual_testing.html#accessibility-a11y-testing)
- [ ] External dependencies files were updated (`yarn` and `pip`)
- [ ] Documentation is updated
- [ ] Link to diff of internal dependency change is included
- [ ] CHANGELOG.rst is updated for high-level changes
- [ ] Contributor is in AUTHORS.rst

### CODE REVIEW

File: kolibri/plugins/coach/assets/src/views/exams/create-exam-page/topic-row.vue [hunk 1]
```diff
@@ -3,21 +3,20 @@
...
         :indeterminate="someExercisesWithinTopicSelected"
-        :disabled="!topicHasExercises"
         @change="changeSelection"
       />
     </th>
     <td class="core-table-main-col">
       <div class="topic-title">
         <content-icon :kind="topic" :class="{ disabled: !topicHasExercises }" />
-        <button v-if="topicHasExercises" class="title" @click="$emit('goToTopic', topicId)">
+        <button class="title" @click="$emit('goToTopic', topicId)">
```
Comment (indirectlylit) [inline kolibri/plugins/coach/assets/src/views/exams/create-exam-page/topic-row.vue:17]: haven't tested yet .. but shouldn't the `v-if` remain here? I believe the decision was that that we want to completely hide items that don't have exercises

Comment (indirectlylit) [reply kolibri/plugins/coach/assets/src/views/exams/create-exam-page/topic-row.vue:17]: oh nevermind - that's here https://github.com/learningequality/kolibri/pull/4173/files#diff-b4cc9678ab849b9bff180cbba2e98b45R91

Comment (rtibbles) [reply kolibri/plugins/coach/assets/src/views/exams/create-exam-page/topic-row.vue:17]: The hiding now happens in `index.vue`, this `v-if` logic toggled the disabled state, so was no longer necessary if we are just completely hiding topics without exercises.

**Comment by khangmach** [comment]
The link styling looks great! I think it would be reasonable to also hide the "[checkbox] Name" on the channel node, since there's nothing to select there.

**Comment by rtibbles** [comment]
Updated based on @khangmach's feedback:

image

**Review by khangmach — APPROVED** [review]

**Comment by indirectlylit** [comment]
soon we'll fix those [poor claustrophobic icons](https://github.com/learningequality/kolibri/issues/4175) :)
