### PR TITLE
Learning activities labels and duration improvements

### LINKED ISSUE #8829: Broken string for duration overlay tag
The overlay on the bottom of a thumbnail image, which displays duration, seems to have a broken string. Potentially also in the chips on the library page
https://www.notion.so/learningequality/REGRESSION-Anywhere-potentially-Broken-52ca67f257f84c1d966e941092132618

### PR DESCRIPTION
**Pull request by MisRob**
## Summary

- Move shared logic related to learning activities into a composable function
- Extract logic from `LearningActivityLabel` related to duration to new `LearningActivityDuration` component
- Use  `LearningActivityDuration` on `HybridLearningContentCard` for displaying duration chips in the thumbnail area for larger resolutions - fixes  #8829. Adding mobile screenshot too here just FYI:

| Mobile | Desktop |
| -------- | ----------- |
| mobile | desktop |

- Simplify `LearningActivityLabel` styles, decouple them from `ResourceCard`, and make them safer so that the component can be used easily from other cards
- Move `LearningActivityLabel` and `LearningActivityDuration` components outside of `ResourceCard` directory since `ResourceCard` is not the only component using them

Note that no updates to logic around what should be source metadata for deciding how to display duration were made. I only extracted existing logic from `LearningActivityLabel`. This might need some more updates after we know more about metadata related to this (#8767).

## Reviewer guidance

For resources with various learning activities and durations, can you see any regressions of how learning activities labels, icons, and durations are displayed on cards on Home, Library, and Bookmarks pages?

## Testing checklist

- [x] Contributor has fully tested the PR manually
- [x] If there are any front-end changes, before/after screenshots are included
- [ ] Critical user journeys are covered by Gherkin stories
- [x] Critical and brittle code paths are covered by unit tests

## PR process

- [x] PR has the correct target branch and milestone
- [x] PR has 'needs review' or 'work-in-progress' label
- [x] If PR is ready for review, a reviewer has been added. (Don't use 'Assignees')
- [ ] If this is an important user-facing change, PR or related issue has a 'changelog' label
- [ ] If this includes an internal dependency change, a link to the diff is provided

## Reviewer checklist

- Automated test coverage is satisfactory
- PR is fully functional
- PR has been tested for [accessibility regressions](http://kolibri-dev.readthedocs.io/en/develop/manual_testing.html#accessibility-a11y-testing)
- External dependency files were updated if necessary (`yarn` and `pip`)
- Documentation is updated
- Contributor is in AUTHORS.md

### CODE REVIEW

File: kolibri/plugins/learn/assets/src/views/HybridLearningContentCard/index.vue [hunk 1]
```diff
@@ -84,7 +84,7 @@
   import TextTruncatorCss from 'kolibri.coreVue.components.TextTruncatorCss';
   import commonCoreStrings from 'kolibri.coreVue.mixins.commonCoreStrings';
   import ProgressBar from '../ProgressBar';
-  import LearningActivityLabel from '../cards/ResourceCard/LearningActivityLabel';
+  import LearningActivityLabel from '../LearningActivityLabel';
```
Comment (rtibbles) [inline kolibri/plugins/learn/assets/src/views/HybridLearningContentCard/index.vue:87]: Need to update v-bind for `CardThumbnail` and `LearningActivityLabel` in here to correlate with the change to just the `contentNode` prop.

Getting vue warnings from use of this component as a result.

File: kolibri/plugins/learn/assets/src/composables/useLearningActivities.js [hunk 2]
```diff
@@ -0,0 +1,118 @@
...
+ */
+
+import { computed } from 'kolibri.lib.vueCompositionApi';
+import { get } from '@vueuse/core';
+import { LearningActivities } from 'kolibri.coreVue.vuex.constants';
+import { coreStrings } from '../../../../../core/assets/src/mixins/commonCoreStrings';
+
+const ReferenceLabel = coreStrings.$tr('readReference');
+const _LearningActivityToLabelMap = {
+  [LearningActivities.CREATE]: coreStrings.$tr('create'),
```
Comment (rtibbles) [inline kolibri/plugins/learn/assets/src/composables/useLearningActivities.js]: Out of an abundance of caution, if we could move this logic inside the function scope that would be preferable, as we've previously had issues caused by accessing translations in module scope: https://github.com/learningequality/kolibri/issues/6003

(note - these only show up when the Intl polyfill is used, so it's hard to spot, and would only really occur in Safari).

**Review by rtibbles — CHANGES_REQUESTED** [review]
Code read through makes sense, and manual testing checks out except for the HybridLearningContentCard. Two changes to make here before merging.

**Comment by MisRob** [comment]
Thank you, @rtibbles. Resolved.

File: kolibri/plugins/learn/assets/src/composables/useLearningActivities.js [hunk 3]
```diff
@@ -8,18 +8,18 @@ import { get } from '@vueuse/core';
 import { LearningActivities } from 'kolibri.coreVue.vuex.constants';
 import { coreStrings } from '../../../../../core/assets/src/mixins/commonCoreStrings';
```
Comment (rtibbles) [inline kolibri/plugins/learn/assets/src/composables/useLearningActivities.js]: Sorry, I missed this in the first pass - we shouldn't import core API objects in this way, as otherwise this will replicate this code into the learn plugin (using the import below, it accesses it at runtime via the default frontend object).
```suggestion
import coreStrings from 'kolibri.coreVue.mixins.commonCoreStrings';
```

**Comment by rtibbles** [comment]
All issues from previous pass resolved - just one more thing that I missed first time.

File: kolibri/plugins/learn/assets/src/composables/useLearningActivities.js (hunk 3 above)
Comment (MisRob) [reply kolibri/plugins/learn/assets/src/composables/useLearningActivities.js]: This ends up with the following Webpack error

```
[Vue warn]: Error in data(): "TypeError: kolibri_coreVue_mixins_commonCoreStrings__WEBPACK_IMPORTED_MODULE_3___default.a.$tr is not a function"
```

I think this may be happening because `commonCoreStrings` [exports Vue mixin by default](https://github.com/MisRob/kolibri/blob/f9fcd0a6f4e6315ffa6e0af64958e7d020cbf495/kolibri/core/assets/src/mixins/commonCoreStrings.js#L1089) that is then registered [in the core API](https://github.com/MisRob/kolibri/blob/f9fcd0a6f4e6315ffa6e0af64958e7d020cbf495/kolibri/core/assets/src/core-app/apiSpec.js#L48). I'd like to only use [this translator](https://github.com/MisRob/kolibri/blob/f9fcd0a6f4e6315ffa6e0af64958e7d020cbf495/kolibri/core/assets/src/mixins/commonCoreStrings.js#L8) though. Is that a problem too? I think I already saw translator functions being imported and used in javascript files.

Comment (rtibbles) [reply kolibri/plugins/learn/assets/src/composables/useLearningActivities.js]: It's fine to import translators across files, it's just a special case for the core API. The only issue is that it will bundle the code for the core translator into the learn plugin, and then the string extraction machinery will duplicate the core strings into the learn plugin message bundles too, so it will cause a fair amount of bloat.

I think maybe better to add just the strings translator to the core API?

Can update this import https://github.com/learningequality/kolibri/blob/release-v0.15.x/kolibri/core/assets/src/core-app/apiSpec.js#L48 to import `commonCoreStrings, { coreStrings }` and then add `coreStrings` to the core API here under utils? https://github.com/learningequality/kolibri/blob/release-v0.15.x/kolibri/core/assets/src/core-app/apiSpec.js#L218

Comment (MisRob) [reply kolibri/plugins/learn/assets/src/composables/useLearningActivities.js]: I see now, thank you. Yes, I can add it to the core utils.

Comment (rtibbles) [reply kolibri/plugins/learn/assets/src/composables/useLearningActivities.js]: Only thing to be wary about here is that in tests you may need to explicitly mock the `coreString` import in this case, as our Jest auto-import patching for coreAPI imports only works for default exports.

Comment (MisRob) [reply kolibri/plugins/learn/assets/src/composables/useLearningActivities.js]: `import commonCoreStrings, { coreStrings } from '../mixins/commonCoreStrings';` is breaking the build process:

```
Error: Cannot find module '/home/michaela/dev/kolibri/packages/kolibri-tools/dist/apiSpec.json'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:636:15)
    at Function.Module._load (internal/modules/cjs/loader.js:562:25)
    at Module.require (internal/modules/cjs/loader.js:692:17)
    at require (internal/modules/cjs/helpers.js:25:18)
    at Object.<anonymous> (/home/michaela/dev/kolibri/packages/kolibri-tools/lib/apiSpecExportTools.js:106:13)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Module.require (internal/modules/cjs/loader.js:692:17)
    at require (internal/modules/cjs/helpers.js:25:18)
    at Object.<anonymous> (/home/michaela/dev/kolibri/packages/kolibri-tools/lib/webpack.config.base.js:20:23)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
internal/modules/cjs/loader.js:638
    throw err;
    ^
```

and the linter as well:

```
kolibri/plugins/user_auth/assets/test/views/auth-select-page.spec.js
  1:1   error    Resolve error: Cannot find module '/home/michaela/dev/kolibri/packages/kolibri-tools/dist/apiSpec.json'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:636:15)
    at Function.Module._load (internal/modules/cjs/loader.js:562:25)
    at Module.require (internal/modules/cjs/loader.js:692:17)
    at require (internal/modules/cjs/helpers.js:25:18)
    at Object.<anonymous> (/home/michaela/dev/kolibri/packages/kolibri-tools/lib/apiSpecExportTools.js:106:13)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)  import/namespace
```

I wasn't able to find out what's the problem in a reasonable timeframe so I just left those two imports on different lines.

**Comment by MisRob** [comment]
I forgot to add some related changes to the last commit, so I forced pushed it now. All previous commits should stay the same as before.

File: kolibri/plugins/learn/assets/src/composables/useLearningActivities.js (hunk 3 above)
Comment (MisRob) [reply kolibri/plugins/learn/assets/src/composables/useLearningActivities.js]: Should be resolved and will follow-up on Slack with modules resolution errors

Comment (rtibbles) [reply kolibri/plugins/learn/assets/src/composables/useLearningActivities.js]: Yeah that seems fine, probable that some AST parsing code is not setup to handle the same line import.

**Review by rtibbles — APPROVED** [review]
