### PR TITLE
Fixes back button behaviour for content pages in Learn

### LINKED ISSUE #9342: Library & Topic Pages: Track user preference for Card vs List views
## Observed behavior

A user can alternate between Grid and Card views, but when they navigate, they are reverted to the default card view even if they've previously selected the list view.

## Expected behavior

When a user selects List or Grid in any given context, that should be stored as a cookie which can be used to ensure the user has a consistent experience across navigations.

## User-facing consequences

User has a more consistent experience.

Note that this would need to be an optional cookie when/if the #8148 feature is implemented.

### LINKED ISSUE #9622: Immersive back button does not return to search results
## Observed behavior
After filtering resources down using a search, if you click into a specific resource, then exit using the 'Go back' button in the immersive toolbar, it returns you to main Library page, rather than back to the context of your search.

This appears to be because the link to the resource itself is not encoding the search parameters.

## Expected behavior
Navigation should preserve the search parameters so that you are returned back into the context of the search.

## User-facing consequences
Confusion, losing place in search.

## Steps to reproduce
Use any search filter.
Click on a resource.
Press the immersive back button.
Get returned to the main Library page.

## Context
 * Kolibri version: Develop branch

### PR DESCRIPTION
**Pull request by rtibbles**
## Summary
* Properly passes the current route query parameters to link generation to preserve search parameters
* Directly references the id param on the route to infer the currently topicId
* Removes unused `genContentLink` props
* Update code comments
* Delete unused component and references to it
* Fixes unreported bug whereby navigating directly to a search page within a topic would run an unscoped search due to attempting to load the search data before the topic metadata has been loaded
* Refactors `genContentLink` utility into a more general purpose composable that can do one of two things:
  * Return a link that includes query parameters that will create a back link to return to the page the user is currently on
  * Return a link that includes query parameters that will create a back link to return to the page that the current page is pointing at

## References
Fixes #9622
Fixes #9342

## Reviewer guidance
* Use search and navigate to a resource - confirm that the back button returns you to search
* Navigate to a resource via the topic tree - confirm that the back button returns you to the same place in the topic tree
* Navigate to a resource via searching within a channel - confirm that the back button returns you to the same place, and to the same listing of results

[Screencast from 12-12-2022 04:21:26 PM.webm](https://user-images.githubusercontent.com/1680573/207195616-f07aebd3-c5ee-437e-a852-fa1bce7d0b6d.webm)

All back behaviours in various permutations for lesson navigation:
[lesson_back.webm](https://user-images.githubusercontent.com/1680573/207480540-03e9fa9f-b777-4894-b35d-0cb1de3dec2f.webm)

All back behaviours in various permutations for library navigation:
[library_back.webm](https://user-images.githubusercontent.com/1680573/207480567-74007460-3399-4f0e-aa9f-0f8dadb1db39.webm)

----

## Testing checklist

- [x] Contributor has fully tested the PR manually
- [x] If there are any front-end changes, before/after screenshots are included
- [x] Critical user journeys are covered by Gherkin stories
- [ ] Critical and brittle code paths are covered by unit tests

## PR process

- [x] PR has the correct target branch and milestone
- [x] PR has 'needs review' or 'work-in-progress' label
- [x] If PR is ready for review, a reviewer has been added. (Don't use 'Assignees')
- [ ] If this is an important user-facing change, PR or related issue has a 'changelog' label
- [ ] If this includes an internal dependency change, a link to the diff is provided

## Reviewer checklist

- Automated test coverage is satisfactory
- PR is fully functional
- PR has been tested for [accessibility regressions](http://kolibri-dev.readthedocs.io/en/develop/manual_testing.html#accessibility-a11y-testing)
- External dependency files were updated if necessary (`yarn` and `pip`)
- Documentation is updated
- Contributor is in AUTHORS.md

### CODE REVIEW

**Comment by pcenov** [comment]
Nice! I confirm - everything is functioning correctly as described and there no newly introduced issues or regressions.
@radinamatic

**Review by radinamatic — APPROVED** [review]
Manual QA by @pcenov confirms everything is working smoothly! 💯 :shipit:

File: kolibri/plugins/learn/assets/src/composables/useContentLink.js [hunk 1]
```diff
@@ -0,0 +1,66 @@
...
+import { PageNames } from '../constants';
+
+export default function useContentLink(store) {
+  // Get store reference from the curent instance
+  // but allow it to be passed in to allow for dependency
+  // injection, primarily for tests.
+  store = store || getCurrentInstance().proxy.$store;
+  const route = computed(() => store.state.route);
+
+  function genContentLink(id, isLeaf = false, repeatParams = false) {
```
Comment (nucleogenesis) [inline kolibri/plugins/learn/assets/src/composables/useContentLink.js]: Looking at the uses of this in practice I think that it might help clarify things to make this take an object so we pass named params wherever it is used. I had to come back and reread the whole function when I got down to where it's passing `true` to the third param. 

This might save someone reading code using this function the trouble of having to read it to remember what that last param is and does

```javascript
genContentLink({id: node.id, is_leaf: node.is_leaf, repeatParams: true});
```

Comment (nucleogenesis) [reply kolibri/plugins/learn/assets/src/composables/useContentLink.js]: Separately, the name `repeatParams` feels a little bit vague here. The comment explaining what it is for is halfway into the function. Maybe something more verbose like `usePreviousQueryParams` or something would be clearer.

Comment (nucleogenesis) [reply kolibri/plugins/learn/assets/src/composables/useContentLink.js]: Perhaps a JSDoc description of the function and its params would be helpful to clarify the purpose up front as well.

File: kolibri/plugins/learn/assets/src/views/AlsoInThis.vue [hunk 2]
```diff
@@ -9,7 +9,7 @@
       <KRouterLink
         v-for="content in contentNodes"
         :key="content.id"
-        :to="genContentLink(content.id, null, content.is_leaf, null, context)"
+        :to="genContentLink(content.id, content.is_leaf, true)"
```
Comment (nucleogenesis) [inline kolibri/plugins/learn/assets/src/views/AlsoInThis.vue]: I guess my thought around passing an object instead would make this a bit gross and annoying to format -- especially if using a longer property name for the third param

Comment (nucleogenesis) [reply kolibri/plugins/learn/assets/src/views/AlsoInThis.vue]: I guess we could make a computed property for the object we need here if the function took an object instead

File: kolibri/plugins/learn/assets/src/views/TopicsPage/index.vue [hunk 3]
```diff
@@ -76,17 +76,13 @@
             </template>
 
             <!-- display for each nested topic/folder  -->
-            <!-- search results -->
-            <!----
-              TODO - is this necessary at all? how is this different than the search results below?
-            -->
+            <!-- display all resources at the top level of the folder -->
```
Comment (nucleogenesis) [inline kolibri/plugins/learn/assets/src/views/TopicsPage/index.vue:80]: Thanks for the clarification here :)

File: kolibri/plugins/learn/assets/src/views/TopicsPage/index.vue [hunk 4]
```diff
@@ -606,15 +597,17 @@
       this.translator = crossComponentTranslator(LibraryPage);
       this.filterTranslator = crossComponentTranslator(FilterTextbox);
       window.addEventListener('scroll', this.throttledHandleScroll);
-      this.setSearchWithinDescendant(this.topic);
-      this.search();
+      const loadingWatch = this.$watch('loading', () => {
+        this.setSearchWithinDescendant(this.topic);
+        this.search();
+        loadingWatch();
+      });
```
Comment (nucleogenesis) [inline kolibri/plugins/learn/assets/src/views/TopicsPage/index.vue]: This whole thing works so weirdly that `$watch` returns a function that stops the watcher. This isn't super common and maybe a comment or calling the variable `stopWatchingThis` would help clarify. Also, since these functions aren't async and you're not waiting for something to resolve before stopping the watcher, it might be clearer if you just declare the watcher into it's `stopMe` function, then call that stopper function outside of it's watcher handler's scope.

I may be reading this wrongly - so any clarification would be great (here or in code comments)

**Review by nucleogenesis — CHANGES_REQUESTED** [review]
Overall this is great. I think this will dovetail nicely with anything we have to implement around the remote content browsing for sure.

The blocking comments are mostly around some clarifications in the code.

Not blocking is the suggestion around passing `genContentLink` an object -- I'm interested in your and Samson's thoughts but think that with clarifying the parameter name/adding a JSDoc would get the job done.

File: kolibri/plugins/learn/assets/src/composables/useContentLink.js (hunk 1 above)
Comment (rtibbles) [reply kolibri/plugins/learn/assets/src/composables/useContentLink.js]: The other alternative would be to expose two functions, one that generates a link back to this page, and another that generates a link that preserves the query parameter context of the current page.

**Comment by rtibbles** [comment]
Have updated by splitting `genContentLink` into two functions, one for the each case. Have added additional tests, and added more code comments for clarity.

**Comment by pcenov** [comment]
@rtibbles the following issues came out after the regression testing of the latest build:

| Issue| Screenshot |
:-------------------------:|:-------------------------:
| Closing the channel modal window brings the user back to the Home page, instead of the Library page | https://user-images.githubusercontent.com/79847249/208104274-54f71734-a04e-4ad1-89f9-90b9f0141fc4.mp4 |
:-------------------------:|:-------------------------:
| Opening a folder via searching within a channel and clicking the Back button results in bringing the user back to the search results while not showing the Folder. This scenario is working correctly with the main search.  | https://user-images.githubusercontent.com/79847249/208104799-1abae91d-55e6-47c5-8a30-748bc8351ecf.mp4 |
:-------------------------:|:-------------------------:

**Comment by rtibbles** [comment]
I don't think these were regressions from the minor refactor, just other edge cases we had both missed before! These should now be fixed also.

**Comment by radinamatic** [comment]
Several other small state cleanups after (not caused by this refactor), and this is where we stand on the 2 issues reported above by @pcenov :

* Closing the main channel window does return to Library, but closing the **folder** window still returns to Home:
   
   https://user-images.githubusercontent.com/1457929/208203459-2af474da-52ea-4904-acdc-cf13a8b9f18c.mp4


   
* Closing the folder from search now does return to the search results, but there is a brief flash of a different search results number...? 😕 

   https://user-images.githubusercontent.com/1457929/208203831-fed64ade-addd-479b-8a82-7c63f575bbae.mp4

**Comment by rtibbles** [comment]
> Closing the main channel window does return to Library, but closing the folder window still returns to Home:

Specifically, I think this happens when using the breadcrumbs to navigate to a folder.

**Comment by radinamatic** [comment]
> happens when using the breadcrumbs to navigate to a folder.

Yes, my bad for not specifying it above!

**Comment by pcenov** [comment]
@radinamatic all the previously reported issues are now fixed and there are no regressions. LGTM!

**Review by radinamatic — APPROVED** [review]
One thorough manual QA passes, good to go! 💯 👏🏽 :shipit:

**Review by nucleogenesis — APPROVED** [review]
Looks great. This should be much clearer to use and the comments are clear. Look forward to using this next year!
