### PR TITLE
Answer history layout fix

### LINKED ISSUE #9116: Answer history section for a practice quiz is not displayed correctly
## Observed behavior
[Reported by @pcenov](https://learningequality.slack.com/archives/C02JTHE8EV9/p1644857494478009?thread_ts=1643744227.404699&cid=C02JTHE8EV9) while doing the critical workflows testing on the [EXE and DEB assets](https://buildkite.com/learningequality/kolibri-python-package/builds/4892) from #9078 (0.16.x branch).

## Errors and logs
…

## Expected behavior
...

## User-facing consequences
…

## Steps to reproduce
Make several attempts on a practice quiz and try to review past answers.

## Context
* Kolibri version: asset from #9078 (0.16.x branch)
 * Operating system: Windows & Linux
 * Browser: Chrome

### PR DESCRIPTION
**Pull request by rtibbles**
## Summary
* Fixes regression introduced by survey work, where wrapping the icons in a div caused them to break the layout styling
* Fixes errors that happen during rendering when `currentTry` is undefined on the ExamReport

## References
Fixes #9116

## Reviewer guidance
See issue for before image.

After fix:
Big
Screenshot from 2022-02-16 12-59-55

Medium
Screenshot from 2022-02-16 13-00-08

Mobile
Screenshot from 2022-02-16 13-00-17

----

## Testing checklist

- [x] Contributor has fully tested the PR manually
- [x] If there are any front-end changes, before/after screenshots are included
- [ ] Critical user journeys are covered by Gherkin stories
- [ ] Critical and brittle code paths are covered by unit tests

## PR process

- [x] PR has the correct target branch and milestone
- [x] PR has 'needs review' or 'work-in-progress' label
- [x] If PR is ready for review, a reviewer has been added. (Don't use 'Assignees')
- [ ] If this is an important user-facing change, PR or related issue has a 'changelog' label
- [ ] If this includes an internal dependency change, a link to the diff is provided

## Reviewer checklist

- Automated test coverage is satisfactory
- PR is fully functional
- PR has been tested for [accessibility regressions](http://kolibri-dev.readthedocs.io/en/develop/manual_testing.html#accessibility-a11y-testing)
- External dependency files were updated if necessary (`yarn` and `pip`)
- Documentation is updated
- Contributor is in AUTHORS.md

### CODE REVIEW

File: kolibri/core/assets/src/views/AttemptLogItem.vue [hunk 1]
```diff
@@ -49,7 +49,7 @@
         :value="attemptLog.num_coach_contents || 0"
         :isTopic="false"
       />
-    </div>
+    </template>
```
Comment (sairina) [inline kolibri/core/assets/src/views/AttemptLogItem.vue:53]: Changing this from a `div` to a `template` helps with the positioning of the icon because the `template` doesn't show up in the DOM, correct?

File: kolibri/core/assets/src/views/ExamReport/index.vue [hunk 2]
```diff
@@ -66,7 +66,10 @@
       />
     </template>
 
-    <template v-if="!windowIsSmall && !loading && currentTry.attemptlogs.length" #aside>
+    <template
+      v-if="!windowIsSmall && !loading && currentTry && currentTry.attemptlogs.length"
```
Comment (sairina) [inline kolibri/core/assets/src/views/ExamReport/index.vue:70]: Why is it better that we also include a check for `currentTry`?

**Review by sairina — APPROVED** [review]
LGTM - just some questions for my own learning!

File: kolibri/core/assets/src/views/AttemptLogItem.vue (hunk 1 above)
Comment (rtibbles) [reply kolibri/core/assets/src/views/AttemptLogItem.vue:53]: Yes, the div was adding in an extra DOM node that messed with the layout styling that was being used.

File: kolibri/core/assets/src/views/ExamReport/index.vue (hunk 2 above)
Comment (rtibbles) [reply kolibri/core/assets/src/views/ExamReport/index.vue:70]: Without it, when `currentTry` wasn't defined, attempting to read `currentTry.attemptLogs` would produce an error for trying to read a property from `undefined`.

**Review by radinamatic — APPROVED** [review]
Answer history looking good again! 👍🏽 💯
