### PR TITLE
Fix lesson content preview add button

### LINKED ISSUE #7475: Lesson Resource Preview page action button is "Add" when resource is already in Lesson
### Observed behavior

"Pim's Mother" video is already in the Lesson:

image

But when you look into the preview, the action button says "Add"

image

And clicking the "button" seems to re-add the the resource to the Lesson. Because unselecting it via checkbox will say something like "Removed 3 resources" if you e.g. clicked "Add" twice.

cc @MisRob if you have any insights on what's causing this.

### Expected behavior

1. If resource is in lesson, then the button in the preview says "Remove" and causes a remove action when clicked.

### Errors and logs

…

### Steps to reproduce

1. Add a resource to a lesson
1. Go to that resources' preview in the Manage Resources workflow
1. See the wrong button ("Add") on the top corner

### Context

0.14.1

### PR DESCRIPTION
**Pull request by alexMet**
### Summary

Fix the add button in lesson content preview. If the resource is already in lesson, show the correct remove button.

simplescreenrecorder

### Reviewer guidance

#7475 

----

### Contributor Checklist

PR process:

- [x] PR has the correct target branch and milestone
- [ ] PR has 'needs review' or 'work-in-progress' label
- [ ] If PR is ready for review, a reviewer has been added. (Don't use 'Assignees')
- [ ] If this is an important user-facing change, PR or related issue has a 'changelog' label
- [ ] If this includes an internal dependency change, a link to the diff is provided

Testing:

- [ ] Contributor has fully tested the PR manually
- [x] If there are any front-end changes, before/after screenshots are included
- [ ] Critical user journeys are covered by Gherkin stories
- [ ] Critical and brittle code paths are covered by unit tests

### Reviewer Checklist

- Automated test coverage is satisfactory
- PR is fully functional
- PR has been tested for [accessibility regressions](http://kolibri-dev.readthedocs.io/en/develop/manual_testing.html#accessibility-a11y-testing)
- External dependency files were updated if necessary (`yarn` and `pip`)
- Documentation is updated
- Contributor is in AUTHORS.md

### CODE REVIEW

File: kolibri/plugins/coach/assets/src/modules/lessonResources/handlers.js [hunk 1]
```diff
@@ -148,17 +148,19 @@ export function showLessonResourceContentPreview(store, params) {
 
 export function showLessonSelectionContentPreview(store, params, query = {}) {
   const { classId, lessonId, contentId } = params;
+
```
Comment (jonboiser) [inline kolibri/plugins/coach/assets/src/modules/lessonResources/handlers.js]: Just going to suggest removing these lines to make the diff more minimal.
```suggestion
```

File: kolibri/plugins/coach/assets/src/modules/lessonResources/handlers.js [hunk 2]
```diff
@@ -148,17 +148,19 @@ export function showLessonResourceContentPreview(store, params) {
...
   return store.dispatch('loading').then(() => {
     const pendingSelections = store.state.lessonSummary.workingResources || [];
+
```
Comment (jonboiser) [inline kolibri/plugins/coach/assets/src/modules/lessonResources/handlers.js]:
```suggestion
```

File: kolibri/plugins/coach/assets/src/modules/lessonResources/handlers.js [hunk 3]
```diff
@@ -148,17 +148,19 @@ export function showLessonResourceContentPreview(store, params) {
...
       _prepLessonContentPreview(store, classId, lessonId, contentId),
       store.dispatch('lessonSummary/updateCurrentLesson', lessonId),
     ])
       .then(([contentNode, lesson]) => {
         // TODO state mapper
-        const preselectedResources = lesson.resources.map(({ contentnode_id }) => contentnode_id);
-
+        const preselectedResources = lesson.resources;
         const { searchTerm, ...otherQueryParams } = query;
+
```
Comment (jonboiser) [inline kolibri/plugins/coach/assets/src/modules/lessonResources/handlers.js]:
```suggestion
```

File: kolibri/plugins/coach/assets/src/modules/lessonResources/handlers.js [hunk 4]
```diff
@@ -148,17 +148,19 @@ export function showLessonResourceContentPreview(store, params) {
...
     return Promise.all([
       _prepLessonContentPreview(store, classId, lessonId, contentId),
       store.dispatch('lessonSummary/updateCurrentLesson', lessonId),
     ])
       .then(([contentNode, lesson]) => {
         // TODO state mapper
-        const preselectedResources = lesson.resources.map(({ contentnode_id }) => contentnode_id);
-
+        const preselectedResources = lesson.resources;
```
Comment (jonboiser) [inline kolibri/plugins/coach/assets/src/modules/lessonResources/handlers.js:159]: So this was the main cause, that this should have been an array of Content Node objects instead of an array of strings? We had done a refactor that replaced our representation of Lesson Contents from the IDs of the nodes to the full objects, so we must not have updated the code in this place.

**Review by jonboiser — CHANGES_REQUESTED** [review]

**Review by jonboiser — APPROVED** [review]
Tested this out manually and it looks good!
