### PR TITLE
Fix users reload after soft-deleting a user

### LINKED ISSUE #13685: Facility > Users - The table should be reloaded after deleting a user from the hamburger menu
❌ **This issue is not open for contribution. Visit <a href="https://learningequality.org/contributing-to-our-open-code-base/" target="_blank">Contributing guidelines</a>** to learn about the contributing process and how to find suitable issues.

## Observed behavior

This is a follow-up to https://github.com/learningequality/kolibri/pull/13674

If I delete a user by selecting the Delete option from the hamburger menu then the table is not reloaded and the user remains selected as if nothing has happened. If I manually reload the page I can see that the user has actually been correctly removed.

https://github.com/user-attachments/assets/205694b9-b43c-4bd9-b223-8e7f338a5fe7

## Expected behavior

The table should be reloaded after deleting the user.
 
## Steps to reproduce the issue

1. Install the build from https://github.com/learningequality/kolibri/pull/13674
2. Go to Facility > Users and delete a usr from the hamburger menu

## Usage Details
Kolibri 0.19.0a0
Windows 11, Ubuntu 22, Mac OS 15.5  - Chrome, Firefox

### PR DESCRIPTION
**Pull request by AlexVelezLl**
## Summary

* Reloads users table after soft-deleting a user using the user dropdown.
* Reload users table if there was an active filter filtering by classes, and the side panel operations modifies the filtered list.
  * Moved the `onChange` logic to the `useUserManagement` composable to prevent code duplication.

https://github.com/user-attachments/assets/24d2f1b3-6b27-48c4-92f9-13f1e863db1b

## References

Closes #13685.

## Reviewer guidance

Replicate steps taken in #13685. Check that error does not happen anymore.

### CODE REVIEW

**Review by LianaHarris360 — COMMENTED** [review]
Just noting that #13685 also mentions that the table should be reloaded after filtering users by class, then removing users from the class. I don't see that bug mentioned in any other issue, so it can probably be fixed in this PR as well.

**Comment by AlexVelezLl** [comment]
Thanks @LianaHarris360! Haven't noticed that comment, just pushed some changes to address these cases!

File: kolibri/plugins/facility/assets/src/composables/useUserManagement.js [hunk 1]
```diff
@@ -75,6 +76,20 @@ export default function useUserManagement({
...
 
+  function onChange({ resetSelection = false, affectedClasses = null } = {}) {
+    if (resetSelection) {
+      selectedUsers.value = new Set();
+    }
+    if (
+      // If there isn't any specific class affected, always refetch
+      affectedClasses === null ||
+      // If there are affected classes, only refetch if one of them is in the current filters
+      routeFilters.value.classes.some(classId => affectedClasses.includes(classId))
```
Comment (nucleogenesis) [inline kolibri/plugins/facility/assets/src/composables/useUserManagement.js:87]: Love this check to avoid unnecessary API calls.

**Review by nucleogenesis — COMMENTED** [review]
Code overall looks great. This should be good to go for QA

**Review by pcenov — APPROVED** [review]
Thanks @AlexVelezLl, LGTM!

**Comment by AlexVelezLl** [comment]
Thanks @pcenov!
