### PR TITLE
Fix urls.js module regression

### LINKED ISSUE #13566: Change to urls API for unregistered URLs causes errors
❌ **This issue is not open for contribution. Visit <a href="https://learningequality.org/contributing-to-our-open-code-base/" target="_blank">Contributing guidelines</a>** to learn about the contributing process and how to find suitable issues.

## Observed behavior
If the Facility plugin is disabled, the Device settings page does not load.

This is particularly problematic, as the facility page can be disabled from the same page!

## Errors and logs

```
8vue.runtime.common.prod.js:11 Error: URL pattern "kolibri:kolibri.plugins.facility:facility_management" not found
    at urlFunc (urls.js:76:15)
    at i.getFacilitySettingsPath (index.vue:794:1)
    at index.vue:665:45
    at i.de [as _l] (vue.runtime.common.prod.js:11:13326)
    at i.DeviceSettingsPagevue_type_template_id_814e494a_scoped_true_render (index.vue:657:29)
    at t._render (vue.runtime.common.prod.js:11:44429)
    at i.o (vue.runtime.common.prod.js:11:74040)
    at wn.value (vue.runtime.common.prod.js:11:24951)
    at wn.value (vue.runtime.common.prod.js:11:25594)
    at Vn (vue.runtime.common.prod.js:11:27459)
Ge @ vue.runtime.common.prod.js:11Entender este error
19vue.runtime.common.prod.js:11 Error: URL pattern "kolibri:kolibri.plugins.facility:facility_management" not found
    at urlFunc (urls.js:76:15)
    at i.getFacilitySettingsPath (index.vue:794:1)
    at index.vue:665:45
    at i.de [as _l] (vue.runtime.common.prod.js:11:13326)
    at i.DeviceSettingsPagevue_type_template_id_814e494a_scoped_true_render (index.vue:657:29)
    at t._render (vue.runtime.common.prod.js:11:44429)
    at i.o (vue.runtime.common.prod.js:11:74040)
    at wn.value (vue.runtime.common.prod.js:11:24951)
    at wn.value (vue.runtime.common.prod.js:11:25594)
    at Vn (vue.runtime.common.prod.js:11:27459)
Ge @ vue.runtime.common.prod.js:11
qe @ vue.runtime.common.prod.js:11
We @ vue.runtime.common.prod.js:11
t._render @ vue.runtime.common.prod.js:11
o @ vue.runtime.common.prod.js:11
value @ vue.runtime.common.prod.js:11
value @ vue.runtime.common.prod.js:11
Vn @ vue.runtime.common.prod.js:11
(anónimo) @ vue.runtime.common.prod.js:11
Ye @ vue.runtime.common.prod.js:11Entender este error
15device/#/settings:1 Uncaught (in promise) Error: A listener indicated an asynchronous response by returning true, but the message channel closed before a response was receivedEntender este error
2vue.runtime.common.prod.js:11 Error: URL pattern "kolibri:kolibri.plugins.facility:facility_management" not found
    at urlFunc (urls.js:76:15)
    at i.getFacilitySettingsPath (index.vue:794:1)
    at index.vue:665:45
    at i.de [as _l] (vue.runtime.common.prod.js:11:13326)
    at i.DeviceSettingsPagevue_type_template_id_814e494a_scoped_true_render (index.vue:657:29)
    at t._render (vue.runtime.common.prod.js:11:44429)
    at i.o (vue.runtime.common.prod.js:11:74040)
    at wn.value (vue.runtime.common.prod.js:11:24951)
    at wn.value (vue.runtime.common.prod.js:11:25594)
    at Vn (vue.runtime.common.prod.js:11:27459)
Ge @ vue.runtime.common.prod.js:11Entender este error
session.js:86 Error: URL pattern "kolibri:kolibri.plugins.facility:facility_management" not found
    at urlFunc (urls.js:76:15)
    at i.getFacilitySettingsPath (index.vue:794:1)
    at index.vue:665:45
    at i.de [as _l] (vue.runtime.common.prod.js:11:13326)
    at i.DeviceSettingsPagevue_type_template_id_814e494a_scoped_true_render (index.vue:657:29)
    at t._render (vue.runtime.common.prod.js:11:44429)
    at i.o (vue.runtime.common.prod.js:11:74040)
    at wn.value (vue.runtime.common.prod.js:11:24951)
    at wn.value (vue.runtime.common.prod.js:11:25594)
    at Vn (vue.runtime.common.prod.js:11:27459)
```

## Expected behavior
We should always guard cross-plugin URL references as other plugins may be disabled.

## User-facing consequences
If you disable the facility plugin, you have to use the command line to enable it.

## Steps to reproduce
Disable the facility plugin on the device settings page. When it reloads, the page will error.

### PR DESCRIPTION
**Pull request by rtibbles**
## Summary
* Reverts accidental API change where the urls.js module would always return a function instead of returning nothing when no matching pattern was found
* Disables facility settings section when the facility plugin is not available

## References
Fixes #13566 

## Reviewer guidance
Follow the steps to reproduce in the issue, confirm this is no longer a concern.

Note that the settings page restart does not work for the development server.

### CODE REVIEW

File: packages/kolibri/urls.js [hunk 1]
```diff
@@ -65,19 +65,16 @@ class UrlResolver {
...
-              `URL pattern names should use underscores instead of dashes. Try "${name.replace('-', '_')}"`,
-            );
-          }
+      if (process.env.NODE_ENV !== 'production') {
+        if (name.includes('-')) {
+          throw new Error(
+            `URL pattern names should use underscores instead of dashes. Try "${name.replace('-', '_')}"`,
+          );
         }
-        throw new Error(`URL pattern "${name}" not found`);
```
Comment (marcellamaki) [inline packages/kolibri/urls.js:76]: So this has been deleted because we don't want to throw an error here if not found, we want to just advance to `urlFunc = this._createUrlFunction(name, patterns);` ?

Comment (rtibbles) [reply packages/kolibri/urls.js:76]: We are just returning nothing at this point now. So that the returned value is undefined. If I had left this error throwing in, it would have thrown an error every time we got a non-existent URL, which would have still meant a regression from the previous API for the module, which was just to return undefined for non-existent URLs.

**Comment by radinamatic** [comment]
Tested on Windows 10, **Facility** page can now be disabled and enabled again without issues 👍🏽 


https://github.com/user-attachments/assets/1b1effae-6884-4c36-8d05-588d36f1ebd2

**Comment by radinamatic** [comment]
Fix confirmed on Windows 11 too, good to go! 👍🏽 🚀

**Review by radinamatic — APPROVED** [review]
Manual QA on Windows 10 & 11 passed, merge away! 💯 🚀 :shipit:
