### PR TITLE
Fix new class creation title false error

### LINKED ISSUE #7556: Duplicate-classroom-title error message appears when creating a new classroom
### Observed behavior

Similar to #6593, when you create a new classroom as an admin on the Facility > Classes page, you briefly see an error message in the text field.

GIF from kolibri-demo server:

CleanShot 2020-10-13 at 10 13 27

### Expected behavior

No error message shows after you click "submit"

### User-facing consequences

…

### Errors and logs

…

### Steps to reproduce

1. Go to the Facility > Classes page
1. Click "New class" button
1. Fill out the name field
1. Click submit
1. See the error before the modal disappears

### Context

K 0.14.3

### PR DESCRIPTION
**Pull request by alexMet**
### Summary

Fixes the incorrect duplicate title error on new class creation.

simplescreenrecorder-(2)

### References

#7556 

----

### Contributor Checklist

PR process:

- [x] PR has the correct target branch and milestone
- [ ] PR has 'needs review' or 'work-in-progress' label
- [ ] If PR is ready for review, a reviewer has been added. (Don't use 'Assignees')
- [ ] If this is an important user-facing change, PR or related issue has a 'changelog' label
- [ ] If this includes an internal dependency change, a link to the diff is provided

Testing:

- [x] Contributor has fully tested the PR manually
- [x] If there are any front-end changes, before/after screenshots are included
- [ ] Critical user journeys are covered by Gherkin stories
- [ ] Critical and brittle code paths are covered by unit tests

### Reviewer Checklist

- Automated test coverage is satisfactory
- PR is fully functional
- PR has been tested for [accessibility regressions](http://kolibri-dev.readthedocs.io/en/develop/manual_testing.html#accessibility-a11y-testing)
- External dependency files were updated if necessary (`yarn` and `pip`)
- Documentation is updated
- Contributor is in AUTHORS.md

### CODE REVIEW

File: kolibri/plugins/facility/assets/src/views/ManageClassPage/ClassCreateModal.vue [hunk 1]
```diff
@@ -48,16 +49,12 @@
     },
     computed: {
       duplicateName() {
-        const index = this.classes.findIndex(
+        return !!this.classes.find(
```
Comment (jonboiser) [inline kolibri/plugins/facility/assets/src/views/ManageClassPage/ClassCreateModal.vue:52]: I prefer the explicit coercion to `Boolean` over the `!!`

e.g. `return Boolean(this.classes.find(`

Comment (jonboiser) [reply kolibri/plugins/facility/assets/src/views/ManageClassPage/ClassCreateModal.vue:52]: But I see we're not doing this consistently in the codebase! I'll make a note of this to make `Boolean()` the standard way to do coercion.

**Review by jonboiser — APPROVED** [review]
Looks good!

File: kolibri/plugins/facility/assets/src/views/ManageClassPage/ClassCreateModal.vue (hunk 1 above)
Comment (alexMet) [reply kolibri/plugins/facility/assets/src/views/ManageClassPage/ClassCreateModal.vue:52]: I prefer the explicit version (`Boolean`) also, but i wanted to stay consistent.

I also changed the `.findIndex` to `.find` because it is more straightforward, i think. :)
