### PR TITLE
facility tab navigation bug

### LINKED ISSUE #10430: Incorrect page opens when tabs under facility plugin are selected
## Observed behavior
Reported by: @LianaHarris360 and @AllanOXDi  in the alpha-12 bug bash

On Facility plugin, when selecting Users, Settings, or Data tab, “Classes” opens instead.

https://user-images.githubusercontent.com/46411498/230917933-21ee7bc6-c2f6-488e-83f0-01e2ad589978.mp4

## Expected behavior
Correct page opens when corresponding tab is selected.

## User-facing consequences
User cannot access the correct pages.

## Context
0.16.0-alpha12

### PR DESCRIPTION
**Pull request by thanksameeelian**
## Summary
During a bug bash, it was discovered that clicking any of the Facility subtopic links in the SideNav would always direct you to the Classes page regardless of the user's selection. 

This PR restores the intended behavior of SideNav links for Facility subtopics and also adds more complex functionality when a user is a multi-facility admin  - now when a user clicks on a Facility subtopic & has more than one facility, they'll be directed to the "All Facilities" page as per usual, but the links to each facility will now resolve to the subtopic initially selected (they previously always resolved to that facility's "Classes" page).

This PR also alters the string used in the backlink from a subtopic back to the "All Facilities" page, from "← All Facilities" to "← Change Learning Facility" upon team suggestion. This link has been added to each of the four main Facility subtopic pages (link was previously only on "Classes" page) & modified so that once you navigate back to "All Facilities" the routes for each facility will resolve to the same subtopic you came from (e.g. if you were on _Home Facility for A_'s "Settings" page and clicked "← Change Learning Facility" the links to each facility would resolve to their respective "Settings" pages.

This PR also adds tests for `generateNavRoutes.js` & expands tests for `facilityConfig` module functionality, making them more robust.

# `TODO`: follow-up issue addressing bug in this PR - #10649 
### _currently if you have 2+ facilities, are on the "All Facilities" page, open the SideNav, and select a different Facility subtopic, the page will not re-render and it will error in the console. The SideNav remains open & the links do not re-render to resolve to the newly-selected route. Solving this issue calls for a wider conversation about route handling with input from additional team members._
------------------------------------

### backlink text _before_:
Screen Shot 2023-05-05 at 11 55 25 PM

### backlink text _after_:
Screen Shot 2023-05-05 at 11 46 31 PM

### single-facility use-case: links now resolving to correct subtopic (see status bar at bottom of page displaying link URLs upon hover)
single-facility-subtopic-links_AdobeExpress

### multi-facility use-case example user flow, showing possible navigation:
_select subtopic > "All Facilities" page > select link to specific subtopic > select different subtopic through SideNav > select "← Change learning facility" > return to "All Facilities" ~>  links resolve to subtopic user just came from_

https://user-images.githubusercontent.com/43046460/236600514-fc68f5e9-cce9-4e19-ab18-262418cce785.mov

## References
fixes #10430 

## Reviewer guidance
* Please test functionality as both a single-facility and multi-facility user. 
* Adding a facility flow: `Device > Facilities Tab > Import learning facility`
   * You can find credentials for other team members' facilities in Notion.    
* **Note:** these changes only apply to Facility plugin and have no effect on Coach plugin behavior

----

## Testing checklist

- [X] Contributor has fully tested the PR manually
- [X] If there are any front-end changes, before/after screenshots are included
- [ ] Critical user journeys are covered by Gherkin stories
- [X] Critical and brittle code paths are covered by unit tests

## PR process

- [x] PR has the correct target branch and milestone
- [x] PR has 'needs review' or 'work-in-progress' label
- [x] If PR is ready for review, a reviewer has been added. (Don't use 'Assignees')
- [ ] If this is an important user-facing change, PR or related issue has a 'changelog' label
- [ ] If this includes an internal dependency change, a link to the diff is provided

## Reviewer checklist

- Automated test coverage is satisfactory
- PR is fully functional
- PR has been tested for [accessibility regressions](http://kolibri-dev.readthedocs.io/en/develop/manual_testing.html#accessibility-a11y-testing)
- External dependency files were updated if necessary (`yarn` and `pip`)
- Documentation is updated
- Contributor is in AUTHORS.md

### CODE REVIEW

File: kolibri/plugins/facility/assets/src/routes.js [hunk 1]
```diff
@@ -41,7 +43,14 @@ export default [
     path: '/:facility_id?/classes',
     component: ManageClassPage,
     handler: toRoute => {
-      showClassesPage(store, toRoute);
+      if (store.getters.userIsMultiFacilityAdmin && !toRoute.params.facility_id) {
```
Comment (nucleogenesis) [inline kolibri/plugins/facility/assets/src/routes.js]: I wonder if we could clean this up a bit w/ a [Vue Router Guard](https://router.vuejs.org/guide/advanced/navigation-guards.html) like a

```javascript
router.beforeEach((to, from) => {
    if(store.getters... && !to.params.facility_id) { 
         return router.replace({...});
    } else {
        return true; // indicates that things should just move along
    }
})
```

**Review by nucleogenesis — CHANGES_REQUESTED** [review]
I think this should get a QA pass @pcenov 

I left one suggestion for DRYing up the updates to the router a bit (which hopefully works like I think it would :smile: )

File: kolibri/plugins/facility/assets/src/routes.js (hunk 1 above)
Comment (thanksameeelian) [reply kolibri/plugins/facility/assets/src/routes.js]: can you say a bit more about where you imagine this being placed and elaborate a bit? i totally agree with making it more DRY, but tried a lot of different things to get this working so would love to hear more detail about what you're thinking 🙂 

it's my understanding that the handlers in each of these routes are [effectively acting as a beforeEach](https://github.com/learningequality/kolibri/blob/develop/kolibri/core/assets/src/router.js#L50) for each route, and i wasn't successful when trying to place many variations of this logic in, for example, a more global `beforeEach` within `ready()` in facility's `app.js`. i have tried (and failed at haha) rendering this logic more extensible and/or general and also placing it in a lot of different areas of the plugin, so at this point i'm hoping for more specific guidance, as my ideas are all tapped out. 

i also thought through the possibility of adding something like a `showAllFacilitiesPage` handler which could be checked (and passed a variable or two -- basically this logic would DRYly live within it) before then turning to the page-specific handler, but right now each of the routes with their own handlers are their own modules while `AllFacilitesPage` is just a stand-alone file, and there didn't seem like there was structure in place to support that change nor that it was worth it to refactor the file and split it apart. 

i welcome ideas pertaining to this, your suggestion above, or other things, but just have exhausted my imagination a bit in all my attempts so you may have to over-explain 🫠

**Comment by pcenov** [comment]
I confirm that this is implemented correctly as specified in the PR's description. I have reported separately the following issues which I was able to identify while regression testing: https://github.com/learningequality/kolibri/issues/10673 and https://github.com/learningequality/kolibri/issues/10674

**Review by radinamatic — APPROVED** [review]
Manual QA passed, good to go! 💯 :shipit:

File: kolibri/plugins/facility/assets/src/routes.js (hunk 1 above)
Comment (akolson) [reply kolibri/plugins/facility/assets/src/routes.js]: Not sure if [this](https://github.com/learningequality/kolibri/blob/3937057d00c37d1f1db6fae74461aa3686446879/kolibri/plugins/device/assets/src/app.js#L56) will help, but I recently implemented a nav guard for the pin setup feature I was working in. The only difference is that I was implementing this within the `beforeResolve` , but I think the principal should still be the same

**Review by akolson — COMMENTED** [review]
Generally, code looks good to me. Thanks @thanksameeelian! We should be good for a merge once feedback raised by Jacob(which I share too) is incorporated.

File: kolibri/plugins/facility/assets/src/routes.js (hunk 1 above)
Comment (thanksameeelian) [reply kolibri/plugins/facility/assets/src/routes.js]: yes, this is actually precisely where i initially tried to implement this, @akolson & @nucleogenesis! but it ended up introducing even more "stuck navigation" errors like the one mentioned in the `TODO` in the description, #10649. i'll revisit it since i've changed a couple things since then, and ping you again once i have either updated it or have a better explanation for not using it than my current fuzzy memory 🙂 thanks for your feedback!!

Comment (nucleogenesis) [reply kolibri/plugins/facility/assets/src/routes.js]: I don't think it's super important to clean this up so no need to go down this route, but I think that maybe a wildcard route could work where this is put as the _first_ route.

```
  {
    path: '*',
    beforeEnter: (toRoute, fromRoute, next) => {
      if (store.getters.userIsMultiFacilityAdmin && !toRoute.params.facility_id) {
        next({
          name: 'ALL_FACILITIES_PAGE',
          // not sure what the `subTopicName` param does though so this might not work because of that?
        });
      } else {
        next(); // Should move along to the `toRoute` I don't think you have to pass `toRoute` to `next()`
      }
    },
  },

```

In any case, just a thought and I think it's something that can be put off as a dev chore to look into it for a patch release or something.

**Review by nucleogenesis — APPROVED** [review]
I resolved the conversation re: DRYing things up. No need to delay for this.

File: kolibri/plugins/facility/assets/src/routes.js (hunk 1 above)
Comment (rtibbles) [reply kolibri/plugins/facility/assets/src/routes.js]: I think the main reason for not DRYing this up is that it's not a check that should happen before _every_ route - for example, we don't want this to happen before the `ALL_FACILITIES_PAGE` route itself.

One way it could be dried up slightly would be to create a function that does this check, and then invoke it in each handler function, similar to the unassigned content guard in Learn: https://github.com/learningequality/kolibri/blob/develop/kolibri/plugins/learn/assets/src/routes/index.js#L25

So, in the case that it catches, it returns `true`. E.g.:

```
function facilityParamRequiredGuard(toRoute, next, subtopicName) {
  if (store.getters.userIsMultiFacilityAdmin && !toRoute.params.facility_id) {
    next({
        name: 'ALL_FACILITIES_PAGE',
        params: { subtopicName },
      });
      return true;
  }
}
```

then the handler function in this case simplifies to:
```
handler: (toRoute, fromRoute, next) => {
  if (facilityParamRequiredGuard(toRoute, next, ManageClassPage.name)) {
    return;
  }
  showClassesPage(store, toRoute);
},
```

The other thing this does is use the [return early pattern](https://gomakethings.com/the-early-return-pattern-in-javascript/), which helps to reduce the nesting in functions.

**Comment by rtibbles** [comment]
After chatting with @thanksameeelian I unresolved the conversation so that she can take another look at this before merge, but I agree, it doesn't need to block it ultimately.

File: kolibri/plugins/facility/assets/src/routes.js (hunk 1 above)
Comment (thanksameeelian) [reply kolibri/plugins/facility/assets/src/routes.js]: thanks @rtibbles! this feels somewhat close to what i was envisioning as behavior for a `showAllFacilitiesPage` handler that gets called in the needed routes before hitting the page-specific handler, but i wasn't really sure how it would fit into the current code structure, which this completely clarifies. i'll be trying it out now and should be updating soon!

**Review by rtibbles — APPROVED** [review]
