### PR TITLE
Back navigation

### LINKED ISSUE #8614: When referred from the topics page, make sure to generate the back link using the parent of the content item
## Observed behavior
When navigating to the content page from the topics page, the generated backlink to the topics page uses the id of the node being displayed on the content page, and not the id of its parent.

Because it is not a topic, this causes navigation to appear to fail.

## Expected behavior
Back navigation should work.

### PR DESCRIPTION
**Pull request by marcellamaki**
## Summary
Updates genContentLink to take a topicId, rather than conditionally referring to the parent in Topic/TopicSearch page 
Fixes the issue with topic page back button appearing to break, and also ensures that the back button takes the user to their previous view, not just the parent (which can be disorienting, due to nested folder display)

## References
Fixes #8614

topics-back-button

…

## Reviewer guidance
Do all of the back links still work? 
Any edge cases not considered or potentially breaking?

----

## Testing checklist

- [x] Contributor has fully tested the PR manually
- [ ] If there are any front-end changes, before/after screenshots are included
- [ ] Critical user journeys are covered by Gherkin stories
- [ ] Critical and brittle code paths are covered by unit tests

## PR process

- [ ] PR has the correct target branch and milestone
- [ ] PR has 'needs review' or 'work-in-progress' label
- [ ] If PR is ready for review, a reviewer has been added. (Don't use 'Assignees')
- [ ] If this is an important user-facing change, PR or related issue has a 'changelog' label
- [ ] If this includes an internal dependency change, a link to the diff is provided

## Reviewer checklist

- Automated test coverage is satisfactory
- PR is fully functional
- PR has been tested for [accessibility regressions](http://kolibri-dev.readthedocs.io/en/develop/manual_testing.html#accessibility-a11y-testing)
- External dependency files were updated if necessary (`yarn` and `pip`)
- Documentation is updated
- Contributor is in AUTHORS.md

### CODE REVIEW

File: kolibri/plugins/learn/assets/src/views/HybridLearningCardGrid.vue [hunk 1]
```diff
@@ -12,7 +12,7 @@
           :isMobile="windowIsSmall"
           :content="content"
           :thumbnail="content.thumbnail"
-          :link="genContentLink(content.id, content.is_leaf, backRoute, context)"
+          :link="genContentLink(content.id, topicId, content.is_leaf, backRoute, context)"
```
Comment (indirectlylit) [inline kolibri/plugins/learn/assets/src/views/HybridLearningCardGrid.vue:15]: interesting – did the API change? I found a couple other instances in the codebase that seem to lack a `topicId`:


https://github.com/learningequality/kolibri/blob/802f02eabecd24f99085add228b15dfd06835eac/kolibri/plugins/learn/assets/src/views/CompletionModal/index.vue#L115-L120

https://github.com/learningequality/kolibri/blob/802f02eabecd24f99085add228b15dfd06835eac/kolibri/plugins/learn/assets/src/views/CompletionModal/index.vue#L262-L267

Any chance there are others?

One strategy to avoid regressions would be to give default values to parameters in `genContentLink`, e.g.

```js
export default function genContentLink(
  id,
  topicId = null,
  isLeaf = false,
  last = null,
  prevContext = {}
) {
  const query = { ...prevContext };
  if (last) {
    query.last = last;
  }
  if (topicId) {
    query.topicId = topicId;
  }
  return {
    name: isLeaf ? PageNames.TOPICS_CONTENT : PageNames.TOPICS_TOPIC,
    params: { id },
    query,
  };
}
```


Another option is to have `genContentLink` take an options object with all optional parameters packed in there:

```js
export default function genContentLink(id, options = {}) {
  // ...
```

**Review by indirectlylit — COMMENTED** [review]
confirmed that the 'back' link works in the case reported by the issue

File: kolibri/plugins/learn/assets/src/views/HybridLearningCardGrid.vue (hunk 1 above)
Comment (marcellamaki) [reply kolibri/plugins/learn/assets/src/views/HybridLearningCardGrid.vue:15]: Good catch - I've update with the defaults and I've also gone through and added params explicitly. Yes - it did change. I added the topic ID to accommodate some nested folder displays on the topics page, which means you can't just reference `parent` anymore

**Review by indirectlylit — APPROVED** [review]
cool, thank you. 

flagging that there is now a conflict in `BrowseResourceMetadata.vue`
