### PR TITLE
Fix top navigation positioning when window is resized

### LINKED ISSUE #12813: Top navigation - The username and the 'More options' button are not positioned correctly when shrinking the page
## Observed behavior

This is a follow-up to https://github.com/learningequality/kolibri/pull/12775 as the issue is present on `develop`:

The tabs in the navigation should go to the second line when there isn't enough space, and only after that we should be showing the *...* button. See the video:

https://github.com/user-attachments/assets/d324f647-e98b-4ed3-9397-85248fec9568

## Steps to reproduce the issue

1. Install the latest `develop` build
2. Use a long facility name and username
3. Go to Coach > Class home and start shrinking the page to see the responsive design behavior

## Usage Details
Windows 11, Ubuntu 22  - Chrome

### PR DESCRIPTION
**Pull request by LianaHarris360**
## Summary

This pull request adjusts the positioning of the `NavBar` within `AppBar.vue` so that the tabs in the navigation move to the second line when the page shrinks and there isn't enough space. Only after that, on smaller screen sizes, is the overflow menu dropdown button displayed.

This issue is most apparent in the Coach plugin when the classroom title is very long, however this change does impact other Kolibri plugins.

To prevent the overflow menu dropdown button from appearing when the navigation is at the top position, the position of the Navbar is now determined by the number of `overflowMenuLinks` in the first Navbar component found in `AppBar.vue`. 

The top NavBar is hidden and the bottom NavBar is displayed if the length of `overflowMenuLinks` is greater than 0.

Before:

https://github.com/user-attachments/assets/002ea05b-8c02-44b2-99a1-2ebe5fb56ec6

After:

https://github.com/user-attachments/assets/8d613907-8ac9-4f4d-ac0c-92fcadb05ffc

## References

Fixes #12813 

## Reviewer guidance

1. Create a class with a long class name.
2. Navigate to Coach > Class home and resize the page to see the responsive design behavior

### CODE REVIEW

**Comment by marcellamaki** [comment]
@pcenov this seems relatively straightforward, but if it can go on your to-do list I would appreciate the QA team review! thank you (cc @radinamatic)

File: packages/kolibri/components/pages/AppBarPage/internal/AppBar.vue [hunk 1]
```diff
@@ -222,9 +224,18 @@
       window.addEventListener('click', this.handleWindowClick);
       window.addEventListener('keydown', this.handlePopoverByKeyboard, true);
```
Comment (akolson) [inline packages/kolibri/components/pages/AppBarPage/internal/AppBar.vue:223]: Probably out of scope for this fix, but might be worth using the opportunity to move the event additions to the mounted hook instead? Unless there are strong opinions one why it was done that way :)

File: packages/kolibri/components/pages/AppBarPage/internal/AppBar.vue [hunk 2]
```diff
@@ -222,9 +224,18 @@
...
     },
+    beforeUpdate() {
+      // Essential for title updates after data finishes loading
+      this.breakpointLimit = this.title && this.title.length >= 20 ? 4 : 3;
```
Comment (akolson) [inline packages/kolibri/components/pages/AppBarPage/internal/AppBar.vue]: Is the title length we are checking against arbitrary?

**Review by akolson — COMMENTED** [review]
Hi @LianaHarris360! Changes look good and make sense to me! The only question I have is around how we arrive to the title length we used to determine the breakpoint limit. Beyond that, we should be good to go after manual QA.

File: packages/kolibri/components/pages/AppBarPage/internal/AppBar.vue (hunk 1 above)
Comment (LianaHarris360) [reply packages/kolibri/components/pages/AppBarPage/internal/AppBar.vue:223]: I am not against moving these event listeners to the mounted hook instead, I will update the PR with this change.

File: packages/kolibri/components/pages/AppBarPage/internal/AppBar.vue (hunk 2 above)
Comment (LianaHarris360) [reply packages/kolibri/components/pages/AppBarPage/internal/AppBar.vue]: This comparison to the title length is important for determining the lowest `breakpointLimit`, which is initially set to be 4. However, with a title length that is 20 characters or less, the `NavBar` can be positioned at the bottom when the `windowBreakpoint` is 3, without the overflow menu button being displayed. With longer titles, the `breakpointLimit` should continue to be 4.

Comment (akolson) [reply packages/kolibri/components/pages/AppBarPage/internal/AppBar.vue]: Ahh I see, thanks. For purposes of clarity, I think it would be great to add a comment( or use descriptive variable or both? whichever makes more sense) describing that the value `20` is what is currently specified as the maximum title length on small windows. Otherwise, this could end up being a potential source of bugs, considering that any change here would also require a change in the `AppBar.js` where this value is specified.

https://github.com/learningequality/kolibri/blob/bf1989708090683d42733cb2dbd3915eeb265999/packages/kolibri/components/pages/AppBarPage/internal/AppBar.vue#L26

**Comment by LianaHarris360** [comment]
@marcellamaki observed that switching the language to Fulfulde resulted in longer navigation link text in the Coach plugin, which triggered the overflow menu button even though the navbar was positioned at the top of the AppBar.

The navbar position is now determined by the `widthThreshold` variable: it is set to 1600 if the AppBar title is 20 characters or longer, and 1350 otherwise. This allows the navbar to dynamically adjust its position based on the available space in the AppBar.

https://github.com/user-attachments/assets/e93bed6b-a9c8-499d-b6ea-420f3fcbe15d

**Review by akolson — APPROVED** [review]
LGTM! Thanks @LianaHarris360!

**Comment by pcenov** [comment]
Hi @LianaHarris360 and @marcellamaki - I am currently observing the following in the latest build (in all supported browsers):

https://github.com/user-attachments/assets/af89ef96-c0f2-4599-acfc-a2b0574efcd0

1. When I shrink the window to less than 1600 pixels there's too much space between the name of the facility and the tabs under it? That's valid for the other plugins as well, not just for the Coach plugin and it's causing issues on the Library page.

library

2. Even though there seems to be plenty of space for the name of the facility to be fully shown, it's still displayed with ellipsis:

ellipsis

3. When I shrink the width to less than 600px then I still see some overlapping between the facility's name and the username:

https://github.com/user-attachments/assets/87041a76-5aa0-4a1f-a1b7-fdd87697053c

**Comment by LianaHarris360** [comment]
To address point # 1, the padding set within AppBarPage has been adjusted to prevent the content on the pages from being blocked by the App Bar.

To fix the name being truncated with an ellipsis despite having enough space and the username colliding with the AppBar title on smaller screens, the title is now shortened based on the amount of space remaining.

I tested different languages and noticed that the length of the text in the AppBar title and Navbar links can vary by language. Because of this, the position of the Navbar is now determined by the number of `overflowMenuLinks` in the first Navbar component found in `AppBar.vue`.

If the length of `overflowMenuLinks` is greater than 0, the bottom Navbar component is shown; otherwise, the top Navbar is displayed.

File: packages/kolibri/components/pages/AppBarPage/internal/AppBar.vue [hunk 3]
```diff
@@ -207,24 +212,43 @@
...
         return !hashedValuePattern.test(this.username) ? this.username : this.fullName;
       },
+      showTopNavBar() {
+        return this.overflowCount === 0;
+      },
+      truncatedTitle() {
+        if (!this.title) return '';
+        // Dynamically truncate title based on remaining space in AppBar
+        const offset = this.$refs.appBarActions?.clientWidth + 100;
+        const averageCharWidth = 10;
```
Comment (marcellamaki) [inline packages/kolibri/components/pages/AppBarPage/internal/AppBar.vue:232]: I am interpreting averageCharWidth to be the average number of pixels per character in a string - is that right?

File: packages/kolibri/components/pages/AppBarPage/internal/AppBar.vue [hunk 4]
```diff
@@ -394,4 +421,15 @@
     font-size: 14px;
   }
 
+  // Hide top navbar, but keep it in the DOM for overflow calulations
```
Comment (marcellamaki) [inline packages/kolibri/components/pages/AppBarPage/internal/AppBar.vue]: This is just a "i forgot" not an "it shouldn't be so" but what is the scenario where we have a hidden nav bar but still want it to be available for calculations? 

I'm also wondering if there are accessibility considerations, which is why I'm trying to remember the scenario

File: packages/kolibri/components/pages/AppBarPage/internal/AppBar.vue (hunk 3 above)
Comment (marcellamaki) [reply packages/kolibri/components/pages/AppBarPage/internal/AppBar.vue:232]: Overall, I think this title truncation is 👍 - thanks for taking some additional time to tweak the approach

**Review by marcellamaki — COMMENTED** [review]
Hi @LianaHarris360 - thanks for taking some time to make some additional adjustments based on our conversation. In my browser manual QA it's looking good :) 

@pcenov or @radinamatic - could I ask you to do another round of QA on this? In particular, I think it would be good to do at least regression testing on physical devices (tablet and mobile) on the app assets if possible, as the app navigation setup is different. I can handle the mac app QA if that's helpful, but could use some help with the other devices.

File: packages/kolibri/components/pages/AppBarPage/internal/AppBar.vue (hunk 4 above)
Comment (LianaHarris360) [reply packages/kolibri/components/pages/AppBarPage/internal/AppBar.vue]: The AppBar component contains two navbar components. The first one is displayed at the top, beside the AppBar title and the second is displayed below the title. When the top navbar cannot fit all of the links in the AppBar, it adds links to its `overflowMenuLinks` array and this is how we know when the top navbar should no longer be displayed, because we don't want the `overflowMenu` button to show on the top navbar.

If the window is resized to be larger and the top navbar can fit all of the links again (and no longer tries to show the `overflowMenu` button), we can display the top navbar again, and hide the bottom one.

However, if we were to set `display: none` on the first navbar, it would remove it from the DOM and stop calculating how many links can fit and we won't know when all of the links can fit into the top navbar again. 

In that case, the bottom navbar would still show, even on larger window sizes, when the top navbar should be showing instead. So instead, the top navbar is visually hidden, but still there to let the AppBar component know when it can be displayed again. I hope this makes sense, I had to really dig into the code here to come to this conclusion!

I was worried that a screen reader would pick up on both of the navbar components and read the links aloud twice. But I was able test these changes with a screen reader chrome extension, and the navbar links are only read aloud once, even when both were still in the DOM. Hopefully this is still the case when QA does a more thorough accessibility & regression check!

File: packages/kolibri/components/pages/AppBarPage/internal/AppBar.vue (hunk 3 above)
Comment (LianaHarris360) [reply packages/kolibri/components/pages/AppBarPage/internal/AppBar.vue:232]: Yes, that's exactly it. Dividing by it returns how many letters can be displayed before the title needs to be shortened.

I found that an average of 10 allows the title to be truncated while maximizing its visibility. With higher numbers, it truncates the title too soon, and with numbers lower than 10, the truncation is delayed and pushes the profile icon and username out of view.

**Comment by pcenov** [comment]
Hi @LianaHarris360 and @marcellamaki - I've retested the build assets confirming that the issues raised in my previous comment are fixed now and there are no regressions in the mac/android apps.

I was able to identify just the following remaining issues:

1. At 'Coach > Class home' going lower than 1135 pixels results in the username going immediately under the icon while there still seems plenty of space for it, so if there's anything that can be done to handle that case - that would be great!

https://github.com/user-attachments/assets/53af1534-fa6b-46da-88b0-d336a38e02ad

2. At Learn > Library going lower than 841 pixels results in the Filter button being displayed with too much empty space above it:

filterbtnpng

File: packages/kolibri/components/pages/AppBarPage/index.vue [hunk 5]
```diff
@@ -146,20 +145,17 @@
...
       },
     },
-    watch: {
-      windowBreakpoint() {
-        //Update the the app bar height at every breakpoint
-        this.appBarHeight = this.$refs.appBar.$el.scrollHeight || 0;
-      },
+    beforeUpdate() {
+      // Update appBarHeight after AppBar is rerendered and updated
+      this.appBarHeight = this.$refs.appBar.$el.scrollHeight || 124;
```
Comment (akolson) [inline packages/kolibri/components/pages/AppBarPage/index.vue]: With this being done by the [`handleWindowResize`](https://github.com/learningequality/kolibri/pull/13007/files#diff-bc65d92949eabd53d17d9ba8b3666a6dca734c335814690d8e673425ae8ea526R189-R192), it probably makes sense to just call it here?

File: packages/kolibri/components/pages/AppBarPage/internal/AppBar.vue (hunk 3 above)
Comment (akolson) [reply packages/kolibri/components/pages/AppBarPage/internal/AppBar.vue:232]: and the `100`, is it an arbitrary additional offset to cater for something in the app bar actions?

**Comment by radinamatic** [comment]
To add to the first comment above by @pcenov I also retested the latest asset on my Android devices, and can replicate the issue about the username being displayed below the icon (default On-my-own setup - phone screen size):

1. On the Learn and Device pages (there is no space issue) username is below the icon.
2. It is displayed correctly on the Coach page, even with very long facility name.


Device/Learn | Coach
-- | --
 | 

Phone Motorola G51 with Android 12 

Curious thing is that I can replicate the point 1. on Device page even on a tablet size screen, but not on Learn.

**Comment by LianaHarris360** [comment]
The profile icon and username are now positioned next to each other whenever the space allows for it, the spacing on the Learn > Library page has been modified to remove the empty space above the filter button, and I removed the extra spacing between the AppBar title and navigation links which was previously causing problems on the Library page as well.

**Comment by pcenov** [comment]
Thanks @LianaHarris360 - everything looks and feels great now with the exception of the position of the "Filter" button at Learn > Library which when compared with the version in Kolibri 0.17.5 is now higher than it should be:

https://github.com/user-attachments/assets/bfd241a9-0599-4a81-a75c-2db8dcfba6c8

I'm just mentioning it as a difference I noticed and I don't have a preference so leaving it up to you and Marcella to further discuss. :)

File: packages/kolibri/components/pages/AppBarPage/internal/AppBar.vue (hunk 3 above)
Comment (LianaHarris360) [reply packages/kolibri/components/pages/AppBarPage/internal/AppBar.vue:232]: The `appBarActions.clientWidth` alone did not add enough space between the title and the actions, but it does account for the width of the appbar actions. If the `100` is removed, or set to a lower number, everything on the right side of the AppBar (like the profile icon and username) will collide with the title sooner than it should.

**Comment by LianaHarris360** [comment]
Thanks for catching that! I adjusted the position of the `FILTER` button so that it matches the version in Kolibri 0.17.5, there was no reason for it to be higher.

Learn Library Page Filter Button

**Comment by radinamatic** [comment]
Looking good over here! 👍🏽 

Learn | Device | Coach
-- | -- | -- 
 |  |

**Review by akolson — APPROVED** [review]
LGTM! Thanks for patiently working on this issue @LianaHarris360
