### PR TITLE
Only auto-delete individual tasks when they finish

### LINKED ISSUE #6140: tasks got cleared without triggering a 'clear task' action
### Observed behavior

Observed that my list of tasks got cleared after initiating a new import

### Expected behavior

tasks should not be cleared until explicitly done by the user

### User-facing consequences

loss of data: historical context

### Errors and logs

none

### Steps to reproduce

see notes below

### Context

0.13.0 beta 1

### PR DESCRIPTION
**Pull request by jonboiser**
### Summary

1. Updates the places where we clear out the whole queue after a task completes under the old only-one-task-at-a-time model with code to only clear out the task that was being watched for whatever reason. Fixes #6140 
1. ~Removes the lock icon on the SelectContentPage that used to be shown conditionally when a channel is unlisted (relies on a `channel.public` field that has been lost in recent changes)~
1. Add 'public' field to ChannelMetadataSerializer, so that the unlisted channel icon would show. This icon shows strictly when public = false, and not when public = null just in case the channel was never given an annotation.
1. Fixes code in NewChannelVersionPage that would short circuit a new CHANNELDIFFSTATS task if a similar looking task (but not the same kind of Task) of a different type was in the queue. Provides a solution to #6229 
1. Add channel list updating logic described in #6314

### Reviewer guidance

1. Can test the fix for #6140 by starting and finishing some tasks, then starting an import from Kolibri Studio (preferably a channel that you have not already downloaded the sqlite3 file for). This will not clear out the tasks from the Task Manager.
1. Test the fix for the channeldiffstats issue, by importing from a private channel on Studio. Don't clear out your queue. Then update the channel and re-view the upgrade page. Without this change, you should see the empty diffstats table. With this change, you should not see an empty table. This could be dependent on the order of things in the queue, so make sure the import task is towards the top.

### References

…

----

### Contributor Checklist

PR process:

- [x] PR has the correct target branch and milestone
- [x] PR has 'needs review' or 'work-in-progress' label
- [x] If PR is ready for review, a reviewer has been added. (Don't use 'Assignees')
- [ ] If this is an important user-facing change, PR or related issue has a 'changelog' label
- [ ] If this includes an internal dependency change, a link to the diff is provided

Testing:

- [ ] Contributor has fully tested the PR manually
- [ ] If there are any front-end changes, before/after screenshots are included
- [ ] Critical user journeys are covered by Gherkin stories
- [ ] Critical and brittle code paths are covered by unit tests

### Reviewer Checklist

- Automated test coverage is satisfactory
- PR is fully functional
- PR has been tested for [accessibility regressions](http://kolibri-dev.readthedocs.io/en/develop/manual_testing.html#accessibility-a11y-testing)
- External dependency files were updated if necessary (`yarn` and `pip`)
- Documentation is updated
- Contributor is in AUTHORS.md

### CODE REVIEW

File: kolibri/plugins/device/assets/src/views/SelectContentPage/ChannelContentsSummary.vue [hunk 1]
```diff
@@ -13,11 +13,12 @@
...
         <h1>
           <KLabeledIcon icon="channel" :label="channel.name" />
-          <KIcon
+          <!-- Commenting out this icon because we've lost the channel.public attribute -->
+          <!-- <KIcon
             ref="lockicon"
             class="lock-icon"
             icon="unlistedchannel"
-          />
+          /> -->
```
Comment (indirectlylit) [inline kolibri/plugins/device/assets/src/views/SelectContentPage/ChannelContentsSummary.vue]: @bjester do you have any info here? I think this implementation may have changed recently?

Comment (bjester) [reply kolibri/plugins/device/assets/src/views/SelectContentPage/ChannelContentsSummary.vue]: I'm not clear what this is. My work with public channel status was only in the backend.

Comment (jonboiser) [reply kolibri/plugins/device/assets/src/views/SelectContentPage/ChannelContentsSummary.vue]: The `public` field is only returned on the PublicChannelSerializer. The other ChannelSerializers do not seem to have the field as part of their output. I think we are able to show the lock icon properly at the Studio Channel Listing step, because we call the Public version of the channels API. In most other import/export workflows were are calling the ChannelMetadataViewset, which only shows local channels.

Comment (jonboiser) [reply kolibri/plugins/device/assets/src/views/SelectContentPage/ChannelContentsSummary.vue]: It's actually this change that removed the conditional too from this icon. https://github.com/jonboiser/kolibri/commit/4d9aa48f3a94d00acefa827e8fd2073bbd646d00#diff-9127258abd7abf8268a08ff621f35266

To show the icon correctly, we need to add the 'public' field to the Channel-list endpoint and bring back the v-if on the icon as well.

Comment (jonboiser) [reply kolibri/plugins/device/assets/src/views/SelectContentPage/ChannelContentsSummary.vue]: I'm noticing that in my content_channelmetadata table, all of the Channels have their `public` field equal to null. This feature is new to me, so I'm assuming at some point at import this field was supposed to be set to True or False?

Comment (bjester) [reply kolibri/plugins/device/assets/src/views/SelectContentPage/ChannelContentsSummary.vue]: On the Kolibri side, the `public` field is brand new. I believe that information was being used in a response from studio. If it's needed, I would suggest adding it.

Comment (bjester) [reply kolibri/plugins/device/assets/src/views/SelectContentPage/ChannelContentsSummary.vue]: Yeah it's `null` for channels imported prior to the migration since that's an annotation at time of import.

Comment (jonboiser) [reply kolibri/plugins/device/assets/src/views/SelectContentPage/ChannelContentsSummary.vue]: Oh yeah I'm seeing this, but it seems to label USB-imported channels as public = null by default. Or maybe because i exported these channels before this annotation.

File: kolibri/plugins/device/assets/src/views/ManageContentPage/TasksBar.vue [hunk 2]
```diff
@@ -81,6 +75,14 @@
...
       },
     },
+    watch: {
+      doneTasks(val, oldVal) {
+        // Just refresh the channel list whenever anything finishes to get the latest version
+        if (val > oldVal) {
+          this.$store.dispatch('manageContent/refreshChannelList');
+        }
+      },
+    },
```
Comment (indirectlylit) [inline kolibri/plugins/device/assets/src/views/ManageContentPage/TasksBar.vue]: It seems a bit odd to put this logic inside a watcher in a vue component. I would have expected it to live inside  the handler from the `refreshTaskList` action:

https://github.com/learningequality/kolibri/blob/aecc35cd267ea15d8e4e4bf30ecdcfcd90c29d92/kolibri/plugins/device/assets/src/modules/manageContent/actions/taskActions.js#L37-L47

Some of the computed props in this component might be implemented as vuex getters instead to help abstract away the task implementation details stuff.

related: https://github.com/learningequality/kolibri/issues/6177

Comment (jonboiser) [reply kolibri/plugins/device/assets/src/views/ManageContentPage/TasksBar.vue]: I'd rather not put the refresh channel side effect in refreshTaskList, since we would potentially be updating the channel list in places other than the ManageContentPage. We'd need to think about how to handle sudden changes to the channel list like in Delete/Export flows.

Comment (jonboiser) [reply kolibri/plugins/device/assets/src/views/ManageContentPage/TasksBar.vue]: In practice, I've found that having the channel list in vuex and globally shared is not always ideal and that each component should request and manage the channel list themselves for their own purposes. Under this structure, the ManageContentPage would still be watching the Task queue and refreshing its local copy of the channels.

File: kolibri/plugins/device/assets/src/views/ManageContentPage/ChannelPanel/WithSizeAndOptions.vue [hunk 3]
```diff
@@ -110,4 +154,23 @@
...
+      margin-top: -1px;
+      margin-bottom: 1px;
+    }
+  }
+
+  .new-label {
+    padding: 2px 5px 2px 4px;
+    margin-left: 8px;
+    font-size: 14px;
+    border-radius: 2px;
```
Comment (indirectlylit) [inline kolibri/plugins/device/assets/src/views/ManageContentPage/ChannelPanel/WithSizeAndOptions.vue:177]: recommend some slight styling changes to this and the other 'New' label:

* bold
* 8px left and right padding
* align text bottom with row


| before | after |
|--|--|
| image|image|

```css
  .new-label {
    position: relative;
    top: 2px;
    padding: 2px 8px;
    margin-left: 8px;
    font-size: 14px;
    font-weight: bold;
    border-radius: 2px;
  }
```

**Review by indirectlylit — APPROVED** [review]
this looks great - nice job!

File: kolibri/plugins/device/assets/src/views/ManageContentPage/TasksBar.vue (hunk 2 above)
Comment (indirectlylit) [reply kolibri/plugins/device/assets/src/views/ManageContentPage/TasksBar.vue]: sounds good

**Comment by indirectlylit** [comment]
also fixes https://github.com/learningequality/kolibri/issues/6365

**Comment by rtibbles** [comment]
The build is stalled waiting for the MacOS build agent - merging.
