### PR TITLE
Fix redirection issues in coach resource selection side panels

### LINKED ISSUE #13073: Manage lesson resources - Navigation issues
## Observed behavior

The first issue is that if I have already 'added' a resource when I click on the 'N resources selected' link and then go back and click the 'Remove' button then I am incorrectly returned to the 'N resources selected' page:

https://github.com/user-attachments/assets/44b1f36b-066c-4b84-aba9-f39de7b715b7

Also when I add/remove a resource I am immediately brought back to the previous page which is a bit confusing (especially when working with multiple similar resources) as I'm not sure what has happened, since there's no confirmation and everything is happening really fast. The same scenario is valid when adding/removing resources from the search results.
It seems that it will be better to leave the user at the same page, as there will be a clear indication that the item has been added or removed by the labels 'Added' and 'Removed' and the user will be able to navigate back whenever they wish to do so:

https://github.com/user-attachments/assets/e355f284-01a4-4470-8d14-36e97158ae87

Lastly, we have the back arrow everywhere else, but it's not present when previewing a resource - seems that it would be great to have it there as well!

## Expected behavior

Smoother user navigation as described above.

## Steps to reproduce the issue

1. Install the [Kolibri 0.18 alpha1](https://github.com/learningequality/kolibri/releases/tag/v0.18.0-alpha1) build
2. Navigate to Class > Lessons > Lesson and click "Manage resources"
3. Click on a resource and add it.
4. Reopen the resource, click the 'N resources selected' link, then go back and remove the resource.

## Usage Details
[Kolibri 0.18 alpha1](https://github.com/learningequality/kolibri/releases/tag/v0.18.0-alpha1)
Windows 11, Ubuntu 22  - Chrome, Firefox

### PR DESCRIPTION
**Pull request by AlexVelezLl**
## Summary

The previous pattern to redirect back used to store the previous route, and when the user clicked on a back button this pushed the previous route into the history stack. Now we are leveraging this to the router.back() method that pops out the current route from the history stack to go back, but we only do this if the previous route was in the same sub-routes context, this prevents the user to exit the current sub-routes context (e.g. exit the side panel) if they were previously redirected from anywhere outside the side panel (This even prevents that if the user had an external page opened before, we dont redirect back to that external page).

https://github.com/user-attachments/assets/87acfc6a-6808-49f5-b4e9-10a4bca3203e

## References

Closes #13073

## Reviewer guidance

* Play with back buttons both in lessons and quizzes. In quizzes test also the flow to replace questions.

**Note:**
I have wear my user hat and have tried to follow what my user instict was expecting when I clicked on a goBack button, but does it makes sense? Feel free to question if a back button dont redirect you to where you were expecting.

### CODE REVIEW

File: kolibri/plugins/coach/assets/src/composables/usePreviousRoute.js [hunk 1]
```diff
@@ -0,0 +1,67 @@
+import { ref, provide, inject } from 'vue';
+import { onBeforeRouteUpdate, useRouter } from 'vue-router/composables';
+
+/**
+ * Composable for providing a route tracking context to track the previous route. You can
```
Comment (AlexVelezLl) [inline kolibri/plugins/coach/assets/src/composables/usePreviousRoute.js:5]: Does this composable makes sense? The benefit of having this like this is that if I tracked the routes higher in the routing hierarchy as for example in the coach app.js, then I would need to validate if the previous route belongs to the routes related to the side panel and that seems like adding a little bit more complexity.

File: kolibri/plugins/coach/assets/src/composables/usePreviousRoute.js [hunk 2]
```diff
@@ -0,0 +1,67 @@
...
+      return router.back();
+    }
+
+    if (fallbackRoute) {
+      return router.push(fallbackRoute);
+    }
+
+    if (getFallbackRoute) {
+      router.push(getFallbackRoute());
+    }
```
Comment (nucleogenesis) [inline kolibri/plugins/coach/assets/src/composables/usePreviousRoute.js:63]: Might be worth console.error-ing or throwing an error here so we don't run into it silently failing to go back without warning.

File: kolibri/plugins/coach/assets/src/composables/usePreviousRoute.js (hunk 1 above)
Comment (nucleogenesis) [reply kolibri/plugins/coach/assets/src/composables/usePreviousRoute.js:5]: It makes sense to me be used like this where it's scoped to a particular sub-hierarchy in the code. It does seem like it's something that is specific to the side panel use case - do you anticipate this being used in other contexts as well?

**Review by nucleogenesis — COMMENTED** [review]
Just gave the code a once-over and left some questions. Looking great Alex!

File: kolibri/plugins/coach/assets/src/composables/usePreviousRoute.js (hunk 2 above)
Comment (AlexVelezLl) [reply kolibri/plugins/coach/assets/src/composables/usePreviousRoute.js:63]: Sounds good! Thanks @nucleogenesis!

File: kolibri/plugins/coach/assets/src/composables/usePreviousRoute.js (hunk 1 above)
Comment (AlexVelezLl) [reply kolibri/plugins/coach/assets/src/composables/usePreviousRoute.js:5]: For now, yes, just for side panels, but it would work on any sub-route context with scoped navigation

**Review by pcenov — APPROVED** [review]
No issues observed while manually testing, LGTM!

File: kolibri/plugins/coach/assets/src/composables/usePreviousRoute.js [hunk 3]
```diff
@@ -0,0 +1,70 @@
...
+ * route defined by the `fallbackRoute` prop or the `getFallbackRoute` function.
+ */
+export function useGoBack({ fallbackRoute, getFallbackRoute }) {
+  const previousRoute = injectPreviousRoute();
+  const router = useRouter();
+
+  function goBack() {
+    // Go back just if there is a previous route that belongs to the
+    // same routes context.
+    if (previousRoute.value) {
```
Comment (rtibbles) [inline kolibri/plugins/coach/assets/src/composables/usePreviousRoute.js:53]: This will break if someone refreshes the page, as previousRoute.value will be reinitialized to `null` - I think this would work just as well if we checked `window.history.length > 1` instead?

That would also mean we don't need to do any provide inject here, and this function could be exposed directly from a reusable composable.

Comment (AlexVelezLl) [reply kolibri/plugins/coach/assets/src/composables/usePreviousRoute.js:53]: > This will break if someone refreshes the page, as previousRoute.value will be reinitialized to null

It would use the fallback route when that happens!
 
> I think this would work just as well if we checked window.history.length > 1 instead?

Its not totally equivalent. This method provides two "guards" here, one is if a user copy an url and paste it in another tab that has already some history there. Then if they click on go back, it will redirect the page to the external page they were before. This is a very edge case that if we dont want to support its okay :sweat_smile:.

The other case is what would we expect to happen when we click, for example, on "replace question" and we get redirected to the exercise preview and then we click on go back? would we expect the side panel to close, or to go to the parent folder? The first time I tried I unconsciously expected it would take me to the parent folder, but any other perspective is welcome :). For that we would need to check the previous route to check where is it coming from. And the intention of making it a composable was to reutilize this logic, but unfortunately vue-router doesnt expose anything like a `onBeforeRouteEnter` for composables :/ because of that limitation is why I needed to track these routes in an `onBeforeRouteUpdate` and have set the previous route in the root of the sub-routes context. To reuse this logic without the provide inject for it to be reusable we would need to use mixins as there we would be able to introduce the `beforeRouteEnter`.

I tried to build something reusable without having to write the `beforeRouteEnter` each time that we wanted to access the prev route and avoiding the mixins. But if this adds too much complexity, we can just get back to the `beforeRouteEnter` pattern and just use the `router.back` method instead of the `router.push` and that would solve the most of the problems reported in #13073 aswell :).

Comment (rtibbles) [reply kolibri/plugins/coach/assets/src/composables/usePreviousRoute.js:53]: Yes, sorry, the fallback route does provide some coverage, even if at the loss of some state on refresh.

I think this is fine to merge as is - as we implement side panel workflows in more places in later releases we can revisit whether this is something we want to reuse in this way, or have a simpler implementation.

The more general thing I am thinking about is the contrast with Learn where we encode the full back route in the URL itself (at least partly because we anticipate links from Learn being shared more frequently) - but it does cause a horribly bloated URL, and can encode two or three steps of navigation in it too. I don't think I'd want to lose some of that state, just because of the immersive modal nature of the navigation there, rather than a side panel, but worth reflecting on what our more general story for "back arrow" navigation is, both from a user experience, and a technical perspective!

File: kolibri/plugins/coach/assets/src/composables/usePreviousRoute.js [hunk 4]
```diff
@@ -0,0 +1,70 @@
...
+    if (fallbackRoute) {
+      return router.push(fallbackRoute);
+    }
+
+    if (getFallbackRoute) {
+      return router.push(getFallbackRoute());
+    }
+
+    // eslint-disable-next-line no-console
+    console.warn('No fallback route provided to navigate back. No action taken.');
```
Comment (rtibbles) [inline kolibri/plugins/coach/assets/src/composables/usePreviousRoute.js:66]: Oh, sorry, one thing I should have caught - you should use the kolibri-logging library here instead of disabling linting...
