### PR TITLE
Hinting fixes

### LINKED ISSUE #1298: After taking the hint and entering the right answer, not able to proceed to the next question.
## Summary
After taking the hint and entering the right answer, not able to proceed to the next question.

## System information
 - Version: Kolibri 0.4.0aplha4
 - Operating system: Ubuntu 14.04 LTS
 - Browser: Chrome

## How to reproduce
1. Open an exercise. 
2. Hit on get hint. 
3. Enter the correct answer.
4. Click on next question.

**Expected result:** 
Should go to next question.

**Actual result:**
Stays in the same question.

## Screenshots
not able to proce

### LINKED ISSUE #1299: After taking the hint and refreshing the page the hint is not getting recorded in the progress bar.
## Summary

After taking the hint and refreshing the page the hint is not getting recorded in the progress bar.

## System information
 - Version: Kolibri 0.4.0alpha4
 - Operating system: Ubuntu 14.04 LTS
 - Browser: Chrome

## How to reproduce
1. Start an exercise 
2. Take a hint.
3. Refresh the page.
4. Observe the exercise progress bar.

**Expected result:**
The hint taken should be present in the exercise progress bar.

**Actual result:**
The question reappears without the hint taken status.

## Screenshots
refresh 1
refresh 2

### LINKED ISSUE #1300: The hint option is always opened up on subsequent questions.
## Summary

The hint option is always opened up on every questions. This happens after the learner opens hint after entering the correct answer for the present question. 

## System information
 - Version: Kolibri 0.4.0alpha4
 - Operating system: Ubuntu 14.04 LTS
 - Browser: Chrome

## How to reproduce

1. Start and exercise 
2. Enter the correct answer.
3. Click on "check answer" button.
4. Do not click on next question.
5. Instead click on "get hint"
6. Now click on next question.

**Expected result:**
Next question should be displayed with no hint or hiden.

**Actual Result:**
The next question appears with the hint readily available.  

## Screenshots
refresh 3
refresh 4
refresh 5

### PR DESCRIPTION
**Pull request by rtibbles**
## Summary

Fixes various bugs related to hinting functionality. Fixes #1298, resolves #1299, and closes #1300.

Does this by preventing attempts from being set as 'unhinted' after a hint has been taken, and also prevents attempts being set as correct after the first attempt.

Updates the Perseus Renderer to reset hint state when a new question is loaded.

It also ensures that an answer and simpleanswer are set on the attempt log when the user gets a hint as their first interaction.

Finally, it corrects all front end usage of 'correct' to represent answers as a float between 0 and 1, rather than Booleans.

### CODE REVIEW

File: kolibri/plugins/learn/assets/src/views/assessment-wrapper/index.vue [hunk 1]
```diff
@@ -117,15 +117,15 @@ oriented data synchronization.
...
     methods: {
       updateAttemptLogMasteryLog({
         correct,
         complete,
         firstAttempt = false,
-        hinted = false,
+        hinted,
         answerState,
         simpleAnswer,
       }) {
```
Comment (DXCanas) [inline kolibri/plugins/learn/assets/src/views/assessment-wrapper/index.vue:131]: Interesting way to filter out the properties of an object. Is there a reason to do it this way rather than creating separate parameters for each property (besides making the function call nicer)?

File: kolibri/plugins/learn/assets/src/views/assessment-wrapper/index.vue [hunk 2]
```diff
@@ -154,8 +154,9 @@ oriented data synchronization.
         }
       },
       answerGiven({ correct, answerState, simpleAnswer }) {
+        correct = Number(correct); // eslint-disable-line no-param-reassign
         this.correct = correct;
-        if (!correct) {
+        if (correct < 1) {
```
Comment (DXCanas) [inline kolibri/plugins/learn/assets/src/views/assessment-wrapper/index.vue:159]: I take it I should start taking this into account in exercise-detail-view?

File: kolibri/plugins/learn/assets/src/views/assessment-wrapper/index.vue [hunk 3]
```diff
@@ -154,8 +154,9 @@ oriented data synchronization.
         }
       },
       answerGiven({ correct, answerState, simpleAnswer }) {
+        correct = Number(correct); // eslint-disable-line no-param-reassign
```
Comment (DXCanas) [inline kolibri/plugins/learn/assets/src/views/assessment-wrapper/index.vue:157]: It would be nice if we could cast parameters in the declaration

File: kolibri/plugins/learn/assets/src/views/assessment-wrapper/index.vue (hunk 1 above)
Comment (rtibbles) [reply kolibri/plugins/learn/assets/src/views/assessment-wrapper/index.vue:131]: It makes the function call nicer, it also means that when you have a very long list of parameters, it i less cumbersome to call because it is the name of the parameter, not the specific order that determines the output. I think overall it is a more robust way and descriptive way to call a function.

File: kolibri/plugins/learn/assets/src/views/assessment-wrapper/index.vue (hunk 3 above)
Comment (rtibbles) [reply kolibri/plugins/learn/assets/src/views/assessment-wrapper/index.vue:157]: I think we would need typescript for that!

File: kolibri/plugins/learn/assets/src/views/assessment-wrapper/index.vue (hunk 2 above)
Comment (rtibbles) [reply kolibri/plugins/learn/assets/src/views/assessment-wrapper/index.vue:159]: As we clean up, we will want to - but it is not required for 0.4.x

**Comment by rtibbles** [comment]
Keyword bingo!
