### PR TITLE
Fix password fields in modals.

### LINKED ISSUE #3824: No cursor appear in password field, both user's add and edit password.
### Observed behavior

I use the <a href="https://docs.google.com/spreadsheets/d/1FhA5qIDB2DfNJW7bCPZ8lweVI-ZfDUchwY8mJwqdMWE/edit#gid=1279941688">Kolibri integration testing spreadsheet</a> as a guide to test the Kolibri 0.8.0 upgrade to 0.10.0b3 in Ubuntu 18.04. From the Superuser there's a instruction to Create a facility administrator account.

 In users tab, I click add new, then fill-up the name and username. But the password  and re-enter password field was no cursor to type in. I try to click and press tab on keyboard, but no cursor appear so that I can't enter my password. I found out, that the cursor is overlap by the label name of password and re-password. Because of that, It's hard to entered a password in user's add and even in edit password. so we think that the browser has a problem within the typing field.

### Steps to reproduce

-  Install the 0.8.0
-  Copy the 0.8.0 <a href="https://drive.google.com/drive/shared-with-me">Kolibri sample data</a>  the .kolibri
-  Upgrade to 0.10.0b3
-  Log in as admin
-  Go to facility then click users tab and add new user or edit the password.

### Context
 Kolibri version: 0.10.0b3
    Operating system: Ubuntu 18.04
    Browser: Firefox 59.0.2(64-bit)

### Screenshot
screenshot from 2018-06-20 13-58-46

### PR DESCRIPTION
**Pull request by christianmemije**
### Summary

Fixes #3824 
There is a bug in password inputs in FF. (Try focusing on the password field using FF in [this demo](https://www.w3schools.com/html/tryit.asp?filename=tryhtml_inputpassword), and notice the lag.) After clicking on the input field the focus changes to the HTMLDocument before focusing back on the input field? So I had to adjust the focus event handler. Note that this does not fix the lag that exists when trying to focus on a password input in FF.

I also fixed the focus logic for the create user account modal.

#### Before

before

#### After

after

### Reviewer guidance

Test password fields within modals in FF.

----

### Contributor Checklist

- [ ] Contributor has fully tested the PR manually
- [ ] PR has the correct target branch and milestone
- [ ] PR has 'needs review' or 'work-in-progress' label
- [ ] If PR is ready for review, a reviewer has been added. (Don't use 'Assignees')
- [ ] If there are any front-end changes, before/after screenshots are included
- [ ] If this is an important user-facing change, PR or related issue has a 'changelog' label

### Reviewer Checklist

- [ ] Automated test coverage is satisfactory
- [ ] Reviewer has fully tested the PR manually
- [ ] PR has been tested for [accessibility regressions](http://kolibri-dev.readthedocs.io/en/develop/manual_testing.html#accessibility-a11y-testing)
- [ ] External dependencies files were updated (`yarn` and `pip`)
- [ ] Documentation is updated
- [ ] Link to diff of internal dependency change is included
- [ ] CHANGELOG.rst is updated for high-level changes
- [ ] Contributor is in AUTHORS.rst

### CODE REVIEW

File: kolibri/plugins/facility_management/assets/src/views/user-page/user-create-modal.vue [hunk 1]
```diff
@@ -292,10 +292,15 @@
...
-        this.confirmedPasswordIsInvalid && this.$refs.confirmedPassword.focus();
+        if (this.nameIsInvalid) {
+          this.$refs.name.focus();
+        } else if (this.usernameIsInvalid) {
+          this.$refs.username.focus();
+        } else if (this.passwordIsInvalid) {
+          this.$refs.password.focus();
+        } else if (this.confirmedPasswordIsInvalid) {
+          this.$refs.confirmedPassword.focus();
+        }
```
Comment (indirectlylit) [inline kolibri/plugins/facility_management/assets/src/views/user-page/user-create-modal.vue:303]: nice job improving the readability here

Comment (indirectlylit) [reply kolibri/plugins/facility_management/assets/src/views/user-page/user-create-modal.vue:303]: Looks like the intent may have actually been to show all errors simultaneously. Could you confirm whether this is the case and which version is the desired behavior?

Comment (christianmemije) [reply kolibri/plugins/facility_management/assets/src/views/user-page/user-create-modal.vue:303]: Yes that behavior still exists
wut

File: kolibri/core/assets/src/views/core-modal.vue [hunk 2]
```diff
@@ -131,6 +131,12 @@
         if (!this.$refs.modal) {
           return;
         }
+        if (event.target === this.$refs.modal) {
+          return;
+        }
+        if (this.$refs.modal.contains(event.target.activeElement)) {
+          return;
+        }
```
Comment (indirectlylit) [inline kolibri/core/assets/src/views/core-modal.vue]: could you add comments for each of those exceptions explaining when they occur, similar to the other examples?

**Review by indirectlylit — APPROVED** [review]

File: kolibri/core/assets/src/views/core-modal.vue (hunk 2 above)
Comment (indirectlylit) [reply kolibri/core/assets/src/views/core-modal.vue]: clarified here: https://github.com/learningequality/kolibri/pull/3857/commits/f703a7795c2e88a55bc5583e396428aeac435e4d
