### PR TITLE
Fix error when deleting a single user in UsersTable 

### LINKED ISSUE #13563: Users table - Error when deleting a user
❌ **This issue is not open for contribution. Visit <a href="https://learningequality.org/contributing-to-our-open-code-base/" target="_blank">Contributing guidelines</a>** to learn about the contributing process and how to find suitable issues.

## Observed behavior

If I delete a user at the main Users table, the table is not auto reloaded after the deleting and if I try to delete the user again I am getting an error:

https://github.com/user-attachments/assets/daaec704-e3d5-4231-a4a7-9068efe33518

## Expected behavior

The table should be reloaded.
 
## Steps to reproduce the issue

1. Install the build from https://github.com/learningequality/kolibri/releases/tag/v0.19.0-alpha0
2. Go to Facility > Users and delete a user

## Usage Details
https://github.com/learningequality/kolibri/releases/tag/v0.19.0-alpha0
Windows 11, Ubuntu 22, Mac OS 15.5  - Chrome, Firefox

### PR DESCRIPTION
**Pull request by LianaHarris360**
## Summary

This pull request updates the behavior when deleting a single user within the users table when selecting the options dropdown menu button. Updated decisions regarding behavior were discussed and decided in this [Slack thread](https://learningequality.slack.com/archives/C08JY65NPSQ/p1754395477974499?thread_ts=1753990842.048699&cid=C08JY65NPSQ).
- Added `MoveToTrashModal` to `UsersTable` for deleting single users
- Removed the `DeleteUserModal` component as it was not being used elsewhere.

Before:

https://github.com/user-attachments/assets/daaec704-e3d5-4231-a4a7-9068efe33518

After:

https://github.com/user-attachments/assets/a53ee3f2-f1e8-40c7-a05d-b5858358d5d6

## References

Fixes #13563 

## Reviewer guidance

Testing:
1. Go to Facility > Users and delete a user by pressing the three vertical dots to open the dropdown menu.
2. Ensure the user table updates, the removed user is no longer displayed, and that there are no errors.

### CODE REVIEW

File: kolibri/plugins/facility/assets/src/views/users/common/UsersTable.vue [hunk 1]
```diff
@@ -158,10 +158,9 @@
       @close="closeModal"
     />
 
-    <DeleteUserModal
+    <MoveToTrashModal
       v-if="modalShown === Modals.DELETE_USER"
-      :id="userToChange.id"
-      :username="userToChange.username"
+      :selectedUsers="new Set([userToChange.id])"
```
Comment (AlexVelezLl) [inline kolibri/plugins/facility/assets/src/views/users/common/UsersTable.vue]: (Non blocking) If we create a new set inline in the template, we will be creating a new set on every re-render and slightly increasing the memory usage. A better approach can be to create a computed property that only gets recalculated when the rective prop is changed, and then pass that computed property here, so we avoid creating new sets on every re-render.

File: kolibri/plugins/facility/assets/src/views/users/common/UsersTable.vue [hunk 2]
```diff
@@ -158,10 +158,9 @@
...
       @close="closeModal"
       @change="$emit('change')"
```
Comment (AlexVelezLl) [inline kolibri/plugins/facility/assets/src/views/users/common/UsersTable.vue]: Not sure how we can best handle this, but here we may need to emit a config object to set the `resetSelection` option to true, so the selection is reset after a delete [here](https://github.com/lianaharris360/kolibri/blob/f8828bc25d3debc1f294d2861a6212bf660dea39/kolibri/plugins/facility/assets/src/views/users/NewUsersPage.vue#L171), so in case the removed user was selected, we reset the selection, and avoid having operations with the removed users:

https://github.com/user-attachments/assets/2138b264-c389-42cb-a7a6-faef1af4fe43

**Review by AlexVelezLl — COMMENTED** [review]
Code changes look good! Just a couple of things to consider.

File: kolibri/plugins/facility/assets/src/views/users/common/UsersTable.vue (hunk 2 above)
Comment (LianaHarris360) [reply kolibri/plugins/facility/assets/src/views/users/common/UsersTable.vue]: I think this is the best approach to go with because `onUsersChange()` will be called either way since the facility users need to be refetched.

**Review by AlexVelezLl — COMMENTED** [review]
Code changes look good to me!

**Review by pcenov — APPROVED** [review]
Thanks @LianaHarris360 - LGTM!
