### PR TITLE
Fix selected value handling in  select components

### LINKED ISSUE #14137: Handle empty `KSelect` value gracefully in BirthYear/Gender selects
🙂 Looking for an issue? Welcome! This issue is open for contribution. If this is the first time you’re requesting an issue, please:

- **Read <a href="https://learningequality.org/contributing-to-our-open-code-base/" target="_blank">Contributing guidelines</a>** carefully. **Pay extra attention to [Using generative AI](https://learningequality.org/contributing-to-our-open-code-base/#using-generative-ai)**. **Pull requests and comments that don’t follow the guidelines won’t be answered.**
- **Confirm that you’ve read the guidelines** in your comment.

## Observed behavior

While creating an account, we see custom prop validation failed when `value` is empty  because of the current computed function logic

Image

## Errors and logs

```
[Vue warn]: Invalid prop: custom validator check failed for prop "value".
```
## Expected behavior

- When `value` is empty or no matching option exists, the component's `selected` computed should return `null` (or another value accepted by `KSelect`'s validator) so `KSelect` sees an explicitly empty value rather than an invalid object.
- No Vue prop-validator warnings should appear in the console during initial render or navigation.

## Steps to reproduce

1.  Open the Create Account page (User Auth -> Create account) 
2. Inspect the browser console

## Context

- Application: Kolibri 
- OS: Debian (PopOs)

### PR DESCRIPTION
**Pull request by Abhishek-Punhani**
## Summary

- Fix default return value in select components to include empty label and value, since when the value is empty or null, it would return an empty object, which would raise a Vue Prop warning
- I found a similar bug in `ExtraDemographicField.vue`, and when I added a demo demographic field in my local facility, I noticed the same Vue prop warning 
- 
image

## References

Fixes : #14137 

## Reviewer guidance

- Open the Create Account page (User Auth -> Create account)
- Inspect the browser console and see if there are any Vue-prop-related warnings.
- Migrate to the facility section and open the create-new-user form, make sure the facility has some demographic fields.
-  Inspect the browser console and see if there are any Vue-prop-related warnings.

### CODE REVIEW

File: packages/kolibri-common/components/ExtraDemographics/ExtraDemographicField.vue [hunk 1]
```diff
@@ -46,7 +46,10 @@
         }));
       },
       optionValue() {
-        return this.options.find(option => option.value === this.value) || {};
+        if (!this.value || !this.value.trim()) {
+          return { value: '', label: '' };
+        }
```
Comment (akolson) [inline packages/kolibri-common/components/ExtraDemographics/ExtraDemographicField.vue]: I don't think this condition necessary. Defaulting to `{ value: '', label: '' }` in the return statement below seems sufficient to me.

File: packages/kolibri-common/components/userAccounts/BirthYearSelect.vue [hunk 2]
```diff
@@ -75,7 +75,10 @@
     },
     computed: {
       selected() {
-        return this.options.find(o => o.value === this.value) || {};
+        if (!this.value || !this.value.trim()) {
+          return { value: '', label: '' };
+        }
```
Comment (akolson) [inline packages/kolibri-common/components/userAccounts/BirthYearSelect.vue]: https://github.com/learningequality/kolibri/pull/14250/changes#r2883804111

File: packages/kolibri-common/components/userAccounts/GenderSelect.vue [hunk 3]
```diff
@@ -30,7 +30,10 @@
     },
     computed: {
       selected() {
-        return this.options.find(o => o.value === this.value) || {};
+        if (!this.value || !this.value.trim()) {
+          return { value: '', label: '' };
+        }
```
Comment (akolson) [inline packages/kolibri-common/components/userAccounts/GenderSelect.vue]: https://github.com/learningequality/kolibri/pull/14250/changes#r2883804111

**Review by akolson — CHANGES_REQUESTED** [review]
Hi @Abhishek-Punhani! Great work on this pr. I have left some clean up comments for your consideration.

**Comment by Abhishek-Punhani** [comment]
Hi @akolson, Yes, I added it to prevent having to look for a key that doesn't exist. Should I update the PR by removing this from all three files?

**Comment by akolson** [comment]
@Abhishek-Punhani there's not much value add as we don't have that many options in those particular select components so removing those lines shouldn't be a problem

**Review by akolson — CHANGES_REQUESTED** [review]
Hi @Abhishek-Punhani I've left a comment to your question! Thanks

**Comment by Abhishek-Punhani** [comment]
> @Abhishek-Punhani there's not much value add as we don't have that many options in those particular select components so removing those lines shouldn't be a problem

@akolson ,I have removed the lines.

**Review by akolson — APPROVED** [review]
LGTM! Thanks @Abhishek-Punhani for your perseverance on this issue.
