### PR TITLE
EQM: On first save, update the quiz's ID when redirecting

### LINKED ISSUE #12263: EQM: Cannot "Save & Close" directly after "Save"-ing a quiz
## Overview

Following up on work in #12182 

When a user saves a quiz using the "Save" button, and the quiz has not been saved before, the user is redirected to that newly created quiz's edit page.

If they now click "Save & Close" it fails on the uniqueness of the title. 

Seems there is an issue where some state is not being updated when we navigate to the quiz edit page.

### PR DESCRIPTION
**Pull request by nucleogenesis**
## Summary

Fixes #12263 

When the `new` quiz is saved, since we replace the route, we need to also update the ID of the quiz so that subsequent saves are updating the quiz rather than trying to save the same quiz anew.

## Reviewer guidance

- [ ] If you save a newly created quiz, then click "Save and close" or "Save" after that, you should not see errors.

### CODE REVIEW

File: kolibri/plugins/coach/assets/src/views/plan/CreateExamPage/index.vue [hunk 1]
```diff
@@ -174,16 +174,16 @@
...
               this.$router.replace({
                 name: PageNames.EXAM_CREATION_ROOT,
                 params: {
                   classId: this.$route.params.classId,
                   quizId: exam.id,
                 },
               });
+              // Update the quiz with the new id - there won't be if this is a new quiz,
+              // this ensures the quiz is kept up-to-date since we're replacing the route
+              this.updateQuiz({ id: exam.id });
```
Comment (rtibbles) [inline kolibri/plugins/coach/assets/src/views/plan/CreateExamPage/index.vue]: This seems right - although maybe this should live inside the useQuizCreation composable?

File: kolibri/plugins/coach/assets/src/views/plan/CreateExamPage/index.vue [hunk 2]
```diff
@@ -174,16 +174,16 @@
                 },
               });
             } else {
-              if (this.$route.params.quizId === exam.id) {
```
Comment (rtibbles) [inline kolibri/plugins/coach/assets/src/views/plan/CreateExamPage/index.vue:177]: I don't think we should remove this - but we should coerce them both to strings for the comparison because for draft exams the exam.id will be an integer, but the route parameter will be a string.

When I did a subsequent save, not having this here led me to get a redundant navigation error from the replace below.

**Review by rtibbles — CHANGES_REQUESTED** [review]
It works, but I think it could live somewhere else, and we do need the checking to prevent redundant navigation errors.

File: kolibri/plugins/coach/assets/src/views/plan/CreateExamPage/index.vue (hunk 1 above)
Comment (nucleogenesis) [reply kolibri/plugins/coach/assets/src/views/plan/CreateExamPage/index.vue]: I tried putting it at the end of saveQuiz but it wasn't working so I tried this... I think that maybe the issue was that I wasn't returning the exam in the `then` callback on the `ExamResource.saveModel` -- I've pushed an update that seems to work better there.

File: kolibri/plugins/coach/assets/src/composables/useQuizCreation.js [hunk 3]
```diff
@@ -323,7 +323,12 @@ export default function useQuizCreation() {
       finalQuiz.question_sources = questionSourcesWithoutResourcePool;
     }
 
-    return ExamResource.saveModel({ id, data: finalQuiz });
+    return ExamResource.saveModel({ id, data: finalQuiz }).then(exam => {
+      if (!get(_quiz).id) {
```
Comment (nucleogenesis) [inline kolibri/plugins/coach/assets/src/composables/useQuizCreation.js]: Should this maybe be `if (!id || id !== exam.id) {`

`id` here being assigned to the `get(_quiz).id` up above.

Comment (rtibbles) [reply kolibri/plugins/coach/assets/src/composables/useQuizCreation.js]: Presumably if `id` is undefined then it won't equal `exam.id` either, so the falsy check might be redundant.

But yeah, using the id that we already grabbed in the outer scope feels safer, just in case we're accidentally mutating state for some reason.

Comment (nucleogenesis) [reply kolibri/plugins/coach/assets/src/composables/useQuizCreation.js]: Okay cool - I was getting mixed up a bit around the use of `"new"` for the route until they save the quiz but `get(_quiz).id` will always be `null/undefined` here eh?

**Review by rtibbles — APPROVED** [review]
Code looks good, have manually tested creating a new quiz, saving it. Updating it again, and saving again. Everything is working as expected with no errors.
