### PR TITLE
Topics page fixes

### LINKED ISSUE #8847: ux issues with 'search' tab in Library
## Observed behavior

| observation | illustration |
|--|--|
| At smaller sizes the 'Search' tab launches the side panel which seems incorrect |   |
| The tabs also initially start out with neither selected | | 
| Additionally, on mid-size responsive views when there are no folders there is a only single tab. At this point, it should probably be replaced with just a header or a label rather than being clickable. | image |

## Expected behavior

* Make sure there is always one tab selected
* Do not overload the 'search' tab to launch filter side view
* Display as header instead of tab when there is only one tab

## User-facing consequences

confusing navigation and interaction

### PR DESCRIPTION
**Pull request by marcellamaki**
## Summary
- Updates 'search' button to be 'filter' button per spec (and to reduce confusion about multiple references to 'search'ing)
- Fixes tab behavior - tabs update main view and routes, whereas filter button opens filtering side panel
- Folder tab doesn't display when we are at the last child folder
- replaces breadcrumbs that seem to have disappeared on mobile

## References
Fixes #8847

**Figma spec for medium screens (where the toggling changes were most relevant)**
Screen Shot 2021-12-14 at 3 48 00 PM

**Implementation**
updated-topics-page

updated-topics-mobile

## Reviewer guidance
- Any oversights or regressions that I missed?

----

## Testing checklist

- [ ] Contributor has fully tested the PR manually
- [ ] If there are any front-end changes, before/after screenshots are included
- [ ] Critical user journeys are covered by Gherkin stories
- [ ] Critical and brittle code paths are covered by unit tests

## PR process

- [ ] PR has the correct target branch and milestone
- [ ] PR has 'needs review' or 'work-in-progress' label
- [ ] If PR is ready for review, a reviewer has been added. (Don't use 'Assignees')
- [ ] If this is an important user-facing change, PR or related issue has a 'changelog' label
- [ ] If this includes an internal dependency change, a link to the diff is provided

## Reviewer checklist

- Automated test coverage is satisfactory
- PR is fully functional
- PR has been tested for [accessibility regressions](http://kolibri-dev.readthedocs.io/en/develop/manual_testing.html#accessibility-a11y-testing)
- External dependency files were updated if necessary (`yarn` and `pip`)
- Documentation is updated
- Contributor is in AUTHORS.md

### CODE REVIEW

File: kolibri/plugins/learn/assets/src/views/TopicsPage.vue [hunk 1]
```diff
@@ -99,15 +101,15 @@
         class="main-content-grid"
         :style="gridOffset"
       >
-        <slot v-if="windowIsSmall" name="breadcrumbs" class="breadcrumbs"></slot>
+        <KBreadcrumbs v-if="breadcrumbs.length && windowIsSmall" :items="breadcrumbs" />
```
Comment (rtibbles) [inline kolibri/plugins/learn/assets/src/views/TopicsPage.vue:104]: Ah, this was my fault, I think - I didn't replace both the breadcrumbs slots.

File: kolibri/plugins/learn/assets/src/views/TopicsPage.vue [hunk 2]
```diff
@@ -80,12 +81,13 @@
...
           <HeaderTabs>
             <HeaderTab
+              v-if="topics.length"
               :text="coreString('folders')"
               :to="foldersLink"
             />
             <HeaderTab
               :text="coreString('searchLabel')"
-              :to="searchLink"
+              :to="searchLink "
```
Comment (rtibbles) [inline kolibri/plugins/learn/assets/src/views/TopicsPage.vue]: Weird additional whitespace here?

**Review by rtibbles — CHANGES_REQUESTED** [review]
There are still some issues here from testing.

**Comment by rtibbles** [comment]
When first navigating to the topics page, the folder header is not highlighted, because it requires the query parameter to be set.

Screenshot from 2021-12-15 05-50-33

Overall, I think the interaction on mobile is still confusing - the header links being used as buttons to toggle the side panels feels counterintuitive. As such, the fact that the button for filter is only available in tablet layout but not smaller layouts seems like an issue.

**Comment by rtibbles** [comment]
Also, when first navigating to the search tab, I think we should show the search side panel - otherwise we are requiring users to click the search header and _then_ open the search panel separately, making two clicks to express what they want to do.

**Comment by marcellamaki** [comment]
Updated interactions -- this briefly broke my brain, but I think it covers the scenarios discussed earlier...
updated-topics-desktop

updated-topics-tablet

updated-topics-mobile

File: kolibri/plugins/learn/assets/src/views/TopicsPage.vue [hunk 3]
```diff
@@ -619,8 +616,9 @@
         }
       },
       searchTerms(newVal, oldVal) {
-        if (!isEqual(newVal, oldVal) && this.displayingSearchResults) {
-          this.$router.push({ ...this.searchLink, sidePanel: false });
+        if (!isEqual(newVal, oldVal)) {
+          this.$router.push({ ...this.searchTabLink });
```
Comment (rtibbles) [inline kolibri/plugins/learn/assets/src/views/TopicsPage.vue]: Getting redundant navigation errors here now - simplest fix might be to just to update it to:
```suggestion
          if (!isEqual(this.searchTabLink, this.$route)) {
            this.$router.push({ ...this.searchTabLink });
          }
```

Don't know if this will actually work, alternatively can just wrap it in a try/catch.

**Review by rtibbles — CHANGES_REQUESTED** [review]
Manual testing checks out - just need to prevent the redundant navigation error.

**Review by rtibbles — APPROVED** [review]
