### PR TITLE
Fixes selected users clearing before  an action is completed

### LINKED ISSUE #13691: Facility > Users - The selected users should remain selected until an action is completed
❌ **This issue is not open for contribution. Visit <a href="https://learningequality.org/contributing-to-our-open-code-base/" target="_blank">Contributing guidelines</a>** to learn about the contributing process and how to find suitable issues.

## Observed behavior

If I have selected a number of users and I just open any of the available options such as "Assign coach", "Enroll in class", "Remove from class" and then close the side panel to go back to the table then the selected users should not be deselected as I have to start the process of selecting them again:

https://github.com/user-attachments/assets/2e7b24ca-e9d4-4eff-b743-2885775b4999

## Expected behavior

The selected users should be deselected only after completing the desired operation.
 
## Steps to reproduce the issue

1. Install the build from https://github.com/learningequality/kolibri/releases/tag/v0.19.0-alpha1
2. Go to Facility > Users and select several users
3. Open any of the available options such as "Assign coach", "Enroll in class", "Remove from class" and then close the side panel

## Usage Details
[﻿Kolibri 0.19.0a1](https://github.com/learningequality/kolibri/releases/tag/v0.19.0-alpha1)
Windows 11, Ubuntu 22, Mac OS 15.5  - Chrome, Firefox

### PR DESCRIPTION
**Pull request by AllanOXDi**
## Summary
This PR fixes the issue where selected users in the Users table were being cleared whenever a side panel (Assign Coach, Enroll in Class, Remove from Class) was opened and then closed.
fixes #13691
## References
#13691

## Reviewer guidance

- Go to Facility > Users and select several users
- Open any of the available options such as "Assign coach", "Enroll in class", "Remove from class" and then close the side panel

### CODE REVIEW

File: kolibri/plugins/facility/assets/src/views/users/UsersRootPage/index.vue [hunk 1]
```diff
@@ -56,7 +56,7 @@
           <template #userActions>
             <component
               :is="canAssignCoaches ? 'router-link' : 'span'"
-              :to="overrideRoute($route, { name: PageNames.ASSIGN_COACHES_SIDE_PANEL })"
+              :to="overrideRoute($route, { name: PageNames.SSAIGN_COACHES_SIDE_PANEL })"
```
Comment (AlexVelezLl) [inline kolibri/plugins/facility/assets/src/views/users/UsersRootPage/index.vue]: Seems like an unnoticed change here is breaking the open assign coaches side panel

File: kolibri/plugins/facility/assets/src/views/users/sidePanels/AssignCoachesSidePanel.vue [hunk 2]
```diff
@@ -264,6 +264,7 @@
       });
 
       function closeSidePanel() {
+        emit('clearSelection');
```
Comment (AlexVelezLl) [inline kolibri/plugins/facility/assets/src/views/users/sidePanels/AssignCoachesSidePanel.vue]: This `closeSidePanel` is the general method we use to close the side panel, adding the clearSelection here is incorrect because it will always clear the selection when closing the side panel even if the operation was not completed. This should be moved to the `_handleAssign` method after closing the side panel.

**Review by AlexVelezLl — DISMISSED** [review]
Thanks @AllanOXDi! Code changes look good. Just found a minor regression, and an oversight in the AssignCoachesSidePanel.

File: kolibri/plugins/facility/assets/src/views/users/UsersRootPage/index.vue (hunk 1 above)
Comment (AllanOXDi) [reply kolibri/plugins/facility/assets/src/views/users/UsersRootPage/index.vue]: Good catch! Thanks

**Review by pcenov — CHANGES_REQUESTED** [review]
Hi @AllanOXDi - I confirm that this is working fine for the Users table, but it's not fixed at all for the New users table:

https://github.com/user-attachments/assets/8e9fe0ce-90b3-4d18-a7b2-916d43b46c11

**Comment by AllanOXDi** [comment]
Thanks for pointing that out @pcenov . Let me push the fix momentarily

**Comment by AllanOXDi** [comment]
Hi @pcenov It should be fixed now.

**Comment by pcenov** [comment]
Thanks @AllanOXDi - I have just one additional question: In the "New users" table after I complete an action such as enrolling a user in a class or removing them, then the selected user(s) remain selected in the table, while in this case the users should no longer be selected. Is this something that can be addressed as part of this PR or I should report it separately? 

https://github.com/user-attachments/assets/fe3ca47a-067e-47c3-9c5b-b9ec5016f5e6

**Comment by nucleogenesis** [comment]
@pcenov @AllanOXDi let's keep the experience consistent across the two pages where the user's selection is cleared after they've taken an action on their selection

**Review by nucleogenesis — COMMENTED** [review]
Code changes lgtm - good to merge once @pcenov 's last bit of feedback has been addressed.

**Review by nucleogenesis — DISMISSED** [review]
@AllanOXDi on the New Users page when the selection is cleared, if I'd selected all (and thus the "Select all" checkbox is checked) - then I complete a bulk action.

In this case, all selected users are deselected, but for some reason the "Select all" is still checked.

**Review by pcenov — APPROVED** [review]
Thanks @AllanOXDi - LGTM!
