### PR TITLE
fix device limitations modal

### LINKED ISSUE #9495: "Device limitations" modal when attempting to import non-learner account behaves incorrectly
## Observed behavior

In the setup wizard, when importing individual user accounts, and entering the credentials of an admin user as the account to import, the popup modal has several issues:

image

- It shows the appropriate message (although "a admin" is incorrect), but only has a "cancel" option -- it should also allow you to continue ("OK").
- When you click cancel, it stays on the form it was on before, but then in the background it actually does initiate the single user import of the admin anyway, which isn't immediately apparent, until you reload or do something else, and then it pops you over to the device tab, logged in as the admin account you initially tried to import.

## Expected behavior

1. There should be both "OK" and "Cancel" options.
2. "OK" should take you to the next page in the sequence, showing the import of that user.
3. "Cancel" should actually cancel (not initiate the import silently in the background).
4. Stretch goal (but maybe not possible within 0.15): the indefinite article should take the form appropriate to the noun ("a coach" but "an admin").

## Steps to reproduce

1. Start with a fresh device, and a full-facility device elsewhere on the network
2. Choose "advanced > import individual user accounts"
3. Select the full-facility device from the list
4. Put in the credentials of an admin (or coach?)
5. Notice the modal that pops up, and cancel it
6. Wait a bit and then close and reopen, or refresh, the browser
7. Note that you've now been logged in as the admin account, which was synced

## Context

Extant on Kolibri 0.15.3

CC @radinamatic for replication 🙏

### PR DESCRIPTION
**Pull request by thanksameeelian**
## Summary
This PR updates the "device limitations" modal, which can appear during individual user import when you're attempting to import an admin or coach from an existing facility on to a fresh device. Previously, the modal only had one button, `Cancel`, which ended up initiating the import process despite its intended functionality & user-facing label. Attempting to import a coach would result in an error because of a variable being referenced in the message string was missing, and an admin-specific message was available but not displayed to the user. 

This PR adds an `Import` option to the "Device limitations" modal, adjusts the BE to accept user imports outside of learners at this endpoint, adds the variable needed for the "coach" message to be rendered, and adds conditionality to allow for the rendering of the "admin"-specific message when appropriate

`TODO`: address subsequent issue of users being imported despite "cancel" being selected -- likely related to the process in which we initially get a certificate corresponding to the selected user from the remote server and store it locally, but this certificate is not locally removed upon "cancel": #10675  

**before**
QA screenshot from issue

**after**

_coach_
coach device limitations modal message

_admin_
admin device limitations modal message

## References
fixes #9495 

## Reviewer guidance
_additional details may be found in #9495_
- create a user on a remote facility with "coach" or "admin" permissions
- on a fresh learn-only device, choose to import an individual account and enter the user's credentials
- upon selecting "continue," you should remain on the same page and the "device limitations" modal should render, correctly displaying the details of your user's username and role. 
- "Import" should bring you to the next step of the setup wizard, where you can choose to finish the process and will be logged in as the user you selected
- "Cancel" should dismiss the modal and keep you on the import individual user page
----

## Testing checklist

- [X] Contributor has fully tested the PR manually
- [X] If there are any front-end changes, before/after screenshots are included
- [ ] Critical user journeys are covered by Gherkin stories
- [ ] Critical and brittle code paths are covered by unit tests

## PR process

- [x] PR has the correct target branch and milestone
- [x] PR has 'needs review' or 'work-in-progress' label
- [x] If PR is ready for review, a reviewer has been added. (Don't use 'Assignees')
- [ ] If this is an important user-facing change, PR or related issue has a 'changelog' label
- [ ] If this includes an internal dependency change, a link to the diff is provided

## Reviewer checklist

- Automated test coverage is satisfactory
- PR is fully functional
- PR has been tested for [accessibility regressions](http://kolibri-dev.readthedocs.io/en/develop/manual_testing.html#accessibility-a11y-testing)
- External dependency files were updated if necessary (`yarn` and `pip`)
- Documentation is updated
- Contributor is in AUTHORS.md

### CODE REVIEW

**Comment by pcenov** [comment]
Thanks @thanksameeelian - no issues observed while manually testing the modal behavior, works correctly for both admin and coach users as specified above.

**Review by radinamatic — APPROVED** [review]
Manual QA passed, good to go! 👏🏽 💯 :shipit:

**Review by rtibbles — APPROVED** [review]
Code changes all make sense!

File: kolibri/plugins/setup_wizard/assets/src/views/ImportIndividualUserForm.vue [hunk 1]
```diff
@@ -169,12 +173,22 @@
...
-        return this.$tr('deviceLimitationsMessage', {
+        const importedUserIsAdmin = this.roles && this.roles.includes('admin');
+
+        const messageArgs = {
           full_name: this.full_name,
           username: this.username,
-          roles: this.roles,
+          non_admin_role:
+            !importedUserIsAdmin &&
+            this.coreString('coachLabel').toLocaleLowerCase(currentLanguage),
```
Comment (akolson) [inline kolibri/plugins/setup_wizard/assets/src/views/ImportIndividualUserForm.vue:183]: Non blocking: It doesn't look like we get to use the `toLocaleLowerCase` that much, its actually a first 😄. Because of its benefits with localization strings, It might be good to implement it as a utility function that will rid developers of the need to  import and pass the currentLanguage every time they need a localized lower case string

**Review by akolson — APPROVED** [review]
LGTM! Thanks @thanksameeelian

File: kolibri/plugins/setup_wizard/assets/src/views/ImportIndividualUserForm.vue (hunk 1 above)
Comment (thanksameeelian) [reply kolibri/plugins/setup_wizard/assets/src/views/ImportIndividualUserForm.vue:183]: this is a great point, @akolson! i realized it wasn't present in the codebase (or at least i couldn't find it haha) but sought it out because i was a bit nervous `.toLowerCase`ing a potentially-translated string. i think this is a great suggestion that could be its own little Issue, if this case is encountered elsewhere or we just want to have it in place

**Comment by rtibbles** [comment]
Failure is due to Github actions incident yesterday. Merging.
