### PR TITLE
Fix blank AppBar title on Learner Quiz Pages

### LINKED ISSUE #6323: after refreshing a quiz, app bar title disappears
### Observed behavior

quiz title disappears on refresh or direct navigation to URL:

### Expected behavior

quiz title should always be visible

### User-facing consequences

important context missing from page

### Steps to reproduce

* as a learner, start taking a quiz
* refresh

### Context

0.13.0 beta 7

### PR DESCRIPTION
**Pull request by bransgithub**
### Summary

Fixes #6323 

Currently, refreshing a quiz page or navigating to it directly results in a blank app bar title:

before

By fetching the LearnerClassroomResource based on the classId param, we can set the classroom name/title whenever the page loads:

after

### Reviewer guidance

…

### References

…

----

### Contributor Checklist

PR process:

- [x] PR has the correct target branch and milestone
- [x] PR has 'needs review' or 'work-in-progress' label
- [x] If PR is ready for review, a reviewer has been added. (Don't use 'Assignees')
- [ ] If this is an important user-facing change, PR or related issue has a 'changelog' label
- [ ] If this includes an internal dependency change, a link to the diff is provided

Testing:

- [x] Contributor has fully tested the PR manually
- [x] If there are any front-end changes, before/after screenshots are included
- [ ] Critical user journeys are covered by Gherkin stories
- [ ] Critical and brittle code paths are covered by unit tests

### Reviewer Checklist

- Automated test coverage is satisfactory
- PR is fully functional
- PR has been tested for [accessibility regressions](http://kolibri-dev.readthedocs.io/en/develop/manual_testing.html#accessibility-a11y-testing)
- External dependency files were updated if necessary (`yarn` and `pip`)
- Documentation is updated
- Contributor is in AUTHORS.md

### CODE REVIEW

File: kolibri/plugins/learn/assets/src/modules/examViewer/handlers.js [hunk 1]
```diff
@@ -32,14 +33,17 @@ export function showExam(store, params, alreadyOnQuiz) {
     store.commit('CORE_SET_PAGE_LOADING', false);
   } else {
     const promises = [
```
Comment (jonboiser) [inline kolibri/plugins/learn/assets/src/modules/examViewer/handlers.js:35]: could you try using the `ClassroomResource`? You can import it from `kolibri.resources`. If you only want the name of the class, this is a lighter-weight Viewset, since it doesn't retrieve the lessons and quizzes too.

Another optimization would be to check to see if the `currentClassroom` is defined before making the API call to ClassroomResource, potentially saving a network call.

Comment (jonboiser) [reply kolibri/plugins/learn/assets/src/modules/examViewer/handlers.js:35]: Just confirmed that `ClassroomResource.fetchModel({ id: classId })` works fine at line 36.

Comment (rtibbles) [reply kolibri/plugins/learn/assets/src/modules/examViewer/handlers.js:35]: Yeah, rather than requiring another request - wouldn't this data be available from the class_summary_api call as well?

Comment (jonboiser) [reply kolibri/plugins/learn/assets/src/modules/examViewer/handlers.js:35]: I don't think so, since this is the Learner Quiz viewer, not the Coach quiz viewer (where Class Summary is available)

Comment (rtibbles) [reply kolibri/plugins/learn/assets/src/modules/examViewer/handlers.js:35]: Oh sorry - completely missed that. Disregard!

Comment (podenborg) [reply kolibri/plugins/learn/assets/src/modules/examViewer/handlers.js]: Thanks for the advice everyone, and sorry for the delay. I've changed the handlers to use `ClassroomResource` instead of `LearnerClassroomResource`, and it seems to work great.

As for this suggestion:
> Another optimization would be to check to see if the currentClassroom is defined before making the API call to ClassroomResource, potentially saving a network call.

I definitely agree that this would save an API call, but I'm not sure if the way I'd do it is clean enough. 

Given that the API calls are effectively wrapped into `promises` and called altogether via `ConditionalPromise.all(promises).only`, would it be better readability-wise to have a separate check for `currentClassroom` >> Make a separate call to `ClassroomResource` >> Make the aforementioned `ConditionalPromise` call for the rest of the APIs?

Comment (bransgithub) [reply kolibri/plugins/learn/assets/src/modules/examViewer/handlers.js:35]: Thanks for the advice everyone, and sorry for the delay! I've changed `LearnerClassroomResource` to `ClassroomResource` and it seems to work great. 

As for checking for the existence of `classroomResource` before making a call to the API, I'm not sure if the way I'd implement it would be clean enough. 

It looks like the API calls are wrapped into `promises` and then  effectively 'batch called' with `ConditionalPromise.all(promises).only()`. I think something like this would work: Check if `classroomResource` exists >> Make call to `ClassroomResource` if it doesn't >> Make the rest of the 'batch' calls - but I'm not entirely sure if the extra handful of lines I'd add would be worth the single API call - any advice one way or the other would be great!

**Comment by indirectlylit** [comment]
hi @bransgithub - I think you need to rebase this in order for it to build. There might also be a front-end linting issue

**Review by jonboiser — APPROVED** [review]

**Comment by indirectlylit** [comment]
thank you!
