### PR TITLE
EQM Lesson regression fixes

### LINKED ISSUE #12349: Kolibri 0.17 regression - Cannot set a lesson to being visible
## Observed behavior

Observed while testing the latest Kolibri 0.17 develop build - when I create a new lesson and click the 'Visible to learners' toggle, I see the snackbar message 'Lesson is visible to learners' however the state of the button doesn't actually change to enabled and when I sign in as a learner the lesson is not visible.

Video:

https://github.com/learningequality/kolibri/assets/79847249/555755d7-9768-4da2-8092-2551034f42ba

## Expected behavior

Fully functional 'Lesson is visible to learners' toggle.

## Steps to reproduce the issue

1. Install the the latest Kolibri 0.17 develop build
2. Observe the steps in the provided video.

## Usage Details
Windows 11, Ubuntu 22  - Chrome

### LINKED ISSUE #12351: Kolibri 0.17 regression - Cannot preview a resource when creating a new lesson
## Observed behavior

Observed while testing the latest Kolibri 0.17 develop build - when I go to Coach > Plan > Lesson > Manage resources and I attempt to preview a file I am getting a server error: TypeError: Cannot read properties of null (reading 'assessment_item_ids')

https://github.com/learningequality/kolibri/assets/79847249/a69091d0-846d-4c5c-811d-7384189b8434

## Expected behavior

Previewing resources should be fully functional.

## Steps to reproduce the issue

1. Install the the latest Kolibri 0.17 develop build
2. Setup a full facility and import the QA channel
3. Go to Coach > Plan > Lesson > Manage resources and attempt to preview a resource

## Usage Details
Windows 11, Ubuntu 22  - Chrome

### PR DESCRIPTION
**Pull request by nucleogenesis**
## Summary

Fixes #12349  -- Cannot set lesson to visible (9fc128d94ebbe89c9cd2914e794417d3f9b2df45)
- Reverts to use `is_active` in `validated_data.get()` call introduced in ac175410a30d40c51dea16e816b5d5fe8b49c3b4

Fixes #12351 -- Cannot preview content in lesson creation (15d63b0f106ce469fd27fd7df1d18d9ac947ce26)
- Ensures lessonRoot handler only does Exercise things when there is an exercise

## Reviewer guidance

@pcenov - do these address the issues linked above?

### CODE REVIEW

File: kolibri/plugins/coach/assets/src/modules/lessonResources/handlers.js [hunk 1]
```diff
@@ -267,18 +267,22 @@ function _prepLessonContentPreview(store, classId, lessonId, contentId) {
...
   }).then(
     contentNode => {
-      const assessmentMetadata = contentNode.assessmentmetadata;
       store.commit('lessonSummary/SET_STATE', {
         toolbarRoute: {},
         // only exist if exercises
         workingResources: null,
         resourceCache: cache,
       });
+
```
Comment (nucleogenesis) [inline kolibri/plugins/coach/assets/src/modules/lessonResources/handlers.js:276]: In case this looks mistaken I did add it on purpose to put visual space between the logical blocks a bit

File: kolibri/plugins/coach/assets/src/modules/lessonResources/handlers.js [hunk 2]
```diff
@@ -267,18 +267,22 @@ function _prepLessonContentPreview(store, classId, lessonId, contentId) {
...
-        questions: assessmentMetadata.assessment_item_ids,
-        completionData: assessmentMetadata.mastery_model,
-      });
+
+      if (contentNode.assessmentmetadata) {
+        store.commit('lessonSummary/resources/SET_PREVIEW_STATE', {
+          questions: contentNode.assessmentmetadata.assessment_item_ids,
+          completionData: contentNode.assessmentmetadata.mastery_model,
+        });
+      }
```
Comment (nucleogenesis) [inline kolibri/plugins/coach/assets/src/modules/lessonResources/handlers.js:284]: I initially considered just updating the `lessonSummary/resources/SET_CURRENT_CONTENT_NODE` handler to just set the `state.preview` value if/when these values are present since we're already sending it the `contentNode` but went with the path of least resistance here to avoid giving our neglected Vuex modules any false hope of being refactored in the future, for their fated doom is imminent.

File: kolibri/core/lessons/serializers.py [hunk 3]
```diff
@@ -127,7 +127,7 @@ def update(self, instance, validated_data):
         # Update the scalar fields
         instance.title = validated_data.get("title", instance.title)
         instance.description = validated_data.get("description", instance.description)
-        instance.is_active = validated_data.get("active", instance.is_active)
+        instance.is_active = validated_data.get("is_active", instance.is_active)
```
Comment (rtibbles) [inline kolibri/core/lessons/serializers.py:130]: Looking above, in the create method, validated data is just passed directly to the Lesson.objects.create method, so it does make sense that the validated data contains the attribute mapped to source.

File: kolibri/plugins/coach/assets/src/modules/lessonResources/handlers.js [hunk 4]
```diff
@@ -267,18 +267,22 @@ function _prepLessonContentPreview(store, classId, lessonId, contentId) {
     getParams: { no_available_filtering: true },
   }).then(
     contentNode => {
-      const assessmentMetadata = contentNode.assessmentmetadata;
```
Comment (rtibbles) [inline kolibri/plugins/coach/assets/src/modules/lessonResources/handlers.js:270]: Hrm, yes, I think this was a result of the refactor that removed the assessment state mapper, which presumably returned an empty object when it wasn't an exercise.

**Review by rtibbles — COMMENTED** [review]
Code changes make sense, just needs manual QA.

Adding a regression test to the lesson API endpoint would be good too @nucleogenesis.

**Review by pcenov — APPROVED** [review]
LGTM - both issues are fixed now!
