### PR TITLE
Reactivates sorting on coach reports

### LINKED ISSUE #1390: Sorting functionalities on Coach reports
## Summary
Sorting on functionalities on recents tab,Topics tab and Exams tab.

## System information

 - Version: Kolibri 0.4.0alpha6
 - Operating system: Ubuntu 14.04 LTS
 - Browser: Chrome browser and Firefox

## How to reproduce

1. Login as a Coach user.
2. Click on class name.
3. then you will see Recent, Topics and Exams tab.
4. In those tabs, sort the data according to Name or progress.

## Screenshots
sort in recet
sort in topic area
sort n exam

### PR DESCRIPTION
**Pull request by rtibbles**
## Summary

Fixes #1390

### CODE REVIEW

File: kolibri/plugins/coach/assets/src/views/reports/table-cells/header-cell.vue [hunk 1]
```diff
@@ -1,6 +1,6 @@
 <template>
 
-  <th scope="col" :style="{ textAlign: align }">
+  <th @click="setSortOrder" scope="col" :style="{ textAlign: align }">
     <button v-if="sortable" class="header-text" @click="$emit('click')">
```
Comment (indirectlylit) [inline kolibri/plugins/coach/assets/src/views/reports/table-cells/header-cell.vue]: We should use the button's click event rather than attaching to the table header.

For context, in the old implementation the table header had state set completely from the outside and just emitted click events. I think tying this to vuex is fine for now, and we can remove the click event.

Comment (rtibbles) [reply kolibri/plugins/coach/assets/src/views/reports/table-cells/header-cell.vue]: Oh, whoops - I completely missed that there was a button here. Go me.
