### PR TITLE
Changes data prop progress to a computed prop for reactivity

### LINKED ISSUE #10589: Learn-only device - The quiz score doesn't get displayed immediately after having completed the quiz
## Observed behavior
The quiz score doesn't get displayed immediately after having completed the quiz. If I manually refresh the page it gets displayed correctly.

## Expected behavior
This could be a bit confusing so it's best to display the correct result immediately.

## Steps to reproduce the issue
1. Assign quizzes to a learner on a learn-only device
2. Complete a quiz as the learner

## Video

https://user-images.githubusercontent.com/79847249/235173363-048da172-ab52-4fd2-9b9d-53fa42e914fb.mp4

## Usage Details
Kolibri 0.16alfa13
Ubuntu - Chrome, Firefox

### PR DESCRIPTION
**Pull request by LianaHarris360**
## Summary

This pr changes the data property `progress` within the component `QuizCard` into a computed property instead. Previously `progress` was not updating when the `quiz` object was updated because when a prop is assigned to a value in data, only the prop's value is used to initialize it, so the `progress` data prop was only updated when the page was reloaded.

Before

https://github.com/learningequality/kolibri/assets/46411498/8d921ed9-1ee1-4516-9c47-04a646ed295b

After

https://github.com/learningequality/kolibri/assets/46411498/7e6c5c20-e769-4705-8e74-8f4f16d621f1

## References

Fixes #10589 

## Reviewer guidance

1. Assign quizzes to a learner on a learn-only device.
2. Complete a quiz as the learner.
3. Quiz score should be updated without reloading the page.

## Testing checklist

- [x] Contributor has fully tested the PR manually
- [x] If there are any front-end changes, before/after screenshots are included
- [ ] Critical user journeys are covered by Gherkin stories
- [ ] Critical and brittle code paths are covered by unit tests

## PR process

- [x] PR has the correct target branch and milestone
- [ ] PR has 'needs review' or 'work-in-progress' label
- [x] If PR is ready for review, a reviewer has been added. (Don't use 'Assignees')
- [ ] If this is an important user-facing change, PR or related issue has a 'changelog' label
- [ ] If this includes an internal dependency change, a link to the diff is provided

## Reviewer checklist

- Automated test coverage is satisfactory
- PR is fully functional
- PR has been tested for [accessibility regressions](http://kolibri-dev.readthedocs.io/en/develop/manual_testing.html#accessibility-a11y-testing)
- External dependency files were updated if necessary (`yarn` and `pip`)
- Documentation is updated
- Contributor is in AUTHORS.md

### CODE REVIEW

File: kolibri/plugins/learn/assets/src/views/cards/QuizCard/index.vue [hunk 1]
```diff
@@ -51,11 +51,13 @@
     },
     data() {
       return {
-        progress: this.quiz ? this.quiz.progress : undefined,
         title: this.quiz ? this.quiz.title : '',
```
Comment (rtibbles) [inline kolibri/plugins/learn/assets/src/views/cards/QuizCard/index.vue]: Maybe for consistency we could do the same for the title here? Seems like using a computed prop for this kind of conditional check is more reliable in general.

Comment (LianaHarris360) [reply kolibri/plugins/learn/assets/src/views/cards/QuizCard/index.vue]: Right, I only left it as it because the title is something that I assume would not need to be updated reactively, but I agree that setting a computed prop for this use case is more reliable!

**Review by rtibbles — COMMENTED** [review]
Code changes look good to me - will wait on QA confirmation for final approval!

**Review by akolson — COMMENTED** [review]
LGTM! Thanks @LianaHarris360

**Comment by pcenov** [comment]
LGTM as well @LianaHarris360 - the quiz result is displayed immediately now.

**Review by radinamatic — APPROVED** [review]
Manual QA passed, good to go! 💯 :shipit:
