### PR TITLE
Better setup wizard errors

### LINKED ISSUE #11574: Improve error management and allow the user to retry and report errors during "Setting Up Kolibri"
## Observed behavior
When the user is on the "Setting Up Kolibri" page of the setup wizard, we do not have a good error management experience. 

In some instances, content syncing tasks begin running in the background once the user is imported from the facility, and this can create a lock on the database. 

In other cases, errors with the import itself (such as the issue Radina reported with the "on my own flow" on Android) do not have a clear step of what to do next. 

Finally, when there is an error screen on android, much of the text is cut off, making troubleshooting difficult.

## Errors and logs
UI example: 

## Expected behavior

- [ ] If we get an error back from the provision device endpoint, we should be able to retry, rather than the user getting stuck at the end of the setup wizard. 
- [ ] Other errors should also be better managed
- [ ] We should enhance our middleware to catch the 503 error, and manage that case, so that the user is able to retry.
- [ ] We should repurpose the generic "something went wrong" error message, which would allow the user to report the error, and would pop up the modal that properly displays the error text
- [ ] We should add a retry button 
- [ ] If the retry is unsuccessful, the user should be able to start over at the beginning of the setup wizard

### PR DESCRIPTION
**Pull request by rtibbles**
## Summary
* Does some cleanup of vue prop warnings
* Cleans up some form warnings
* Reverts my previous suggestion to @akolson to use UIAlert, as it causes a big old mess without additional strings, and reverts to the AppError component
* Always displays a retry and a restart button if there is an error on the provisioning page to ensure that people can start over if needed.

## References
Fixes https://github.com/learningequality/kolibri/issues/11574

image

## Reviewer guidance
I tested this by adding `raise Exception` here: https://github.com/learningequality/kolibri/blob/release-v0.16.x/kolibri/core/device/api.py#L101

----

## Testing checklist

- [ ] Contributor has fully tested the PR manually
- [ ] If there are any front-end changes, before/after screenshots are included
- [ ] Critical user journeys are covered by Gherkin stories
- [ ] Critical and brittle code paths are covered by unit tests

## PR process

- [ ] PR has the correct target branch and milestone
- [ ] PR has 'needs review' or 'work-in-progress' label
- [ ] If PR is ready for review, a reviewer has been added. (Don't use 'Assignees')
- [ ] If this is an important user-facing change, PR or related issue has a 'changelog' label
- [ ] If this includes an internal dependency change, a link to the diff is provided

## Reviewer checklist

- Automated test coverage is satisfactory
- PR is fully functional
- PR has been tested for [accessibility regressions](http://kolibri-dev.readthedocs.io/en/develop/manual_testing.html#accessibility-a11y-testing)
- External dependency files were updated if necessary (`yarn` and `pip`)
- Documentation is updated
- Contributor is in AUTHORS.md

### CODE REVIEW

File: kolibri/plugins/setup_wizard/assets/src/views/onboarding-forms/SettingUpKolibri.vue [hunk 1]
```diff
@@ -166,7 +163,7 @@
         return this.wizardContext('onMyOwnOrGroup') == UsePresets.ON_MY_OWN;
       },
     },
-    mounted() {
+    created() {
```
Comment (nucleogenesis) [inline kolibri/plugins/setup_wizard/assets/src/views/onboarding-forms/SettingUpKolibri.vue:166]: Curious why the change from mounted -> created?

Comment (marcellamaki) [reply kolibri/plugins/setup_wizard/assets/src/views/onboarding-forms/SettingUpKolibri.vue:166]: "Do you need to access the DOM? If no, don't use mounted." - past Richard (to me)

Comment (akolson) [reply kolibri/plugins/setup_wizard/assets/src/views/onboarding-forms/SettingUpKolibri.vue:166]: Well from the look of it, we are not manipulating the DOM(at least not directly) so it justifies the change.

**Review by akolson — COMMENTED** [review]
Changes look correct to me. With additional manual QA, we should be good to go! Thanks @rtibbles!

File: packages/kolibri-common/components/AppError/index.vue [hunk 2]
```diff
@@ -8,27 +8,26 @@
...
-          @click="reloadPage"
-        />
-        <KButton
-          :primary="isPageNotFound"
-          appearance="raised-button"
-          :text="exitButtonLabel"
-          @click="handleClickBackToHome"
-        />
+      <KButtonGroup>
+        <slot name="buttons">
```
Comment (nucleogenesis) [inline packages/kolibri-common/components/AppError/index.vue:17]: Nice <3

**Review by nucleogenesis — APPROVED** [review]
Overall this LGTM!

**Comment by marcellamaki** [comment]
@radinamatic - could we get some manual QA here? One use case to test Radina was the issue you reported some time ago with running into issues with Android "On My Own" setup with earlier android devices. Testing on this would be helpful because it would be two for the price of one - seeing if the updates here are working, and it would give us more useful error messages for that problem to see if we can continue to make some progress on it, since I've been a bit blocked in being able to figure out what's wrong. Thank you!

**Review by marcellamaki — DISMISSED** [review]
Requesting changes just to block for merge until manual QA happens. Noting that I have not done code review here and have deferred to @akolson and @nucleogenesis on this one, but I would be happy to review the code if needed.

**Review by pcenov — CHANGES_REQUESTED** [review]
Hi @rtibbles, unfortunately now the error page gets briefly displayed in all setup flows just after having successfully completed the setup process. It won't let me click on `Help us by reporting this error`. Here's an example for `On my own`:

https://github.com/learningequality/kolibri/assets/79847249/f48c9361-545b-4861-afaa-f985ccdebf92

The same is also happening in the Android app:

https://github.com/learningequality/kolibri/assets/79847249/820895ff-2cf3-42a1-83c6-d33fd9c96306

Otherwise I can confirm that in a scenario where there is an actual error it's now being handled gracefully:

https://github.com/learningequality/kolibri/assets/79847249/70c941cd-b9ef-44cd-9341-358817a974cf

Logs: 
[UbuntuLogs.zip](https://github.com/learningequality/kolibri/files/13831245/UbuntuLogs.zip)

[AndroidOnMyOwnLogs.zip](https://github.com/learningequality/kolibri/files/13831251/AndroidOnMyOwnLogs.zip)

**Comment by rtibbles** [comment]
Thanks @pcenov a simple oversight on my part to not conditionalize the display of the error - should be fixed now.

**Review by pcenov — APPROVED** [review]
Implemented as specified above, no regression issues observed - good to go!
