### PR TITLE
Ensure Attendance Tracking confirmation snackbar is displayed

### LINKED ISSUE #14417: Attendance Tracking - Missing snackbar confirmation messages
❌ **This issue is not open for contribution. Visit <a href="https://learningequality.org/contributing-to-our-open-code-base/" target="_blank">Contributing guidelines</a>** to learn about the contributing process and how to find suitable issues.

## Observed behavior

Could be a known issue but currently the snackbar messages for successful submission and edit are missing (or rather disappear too quickly):

https://github.com/user-attachments/assets/19d734cb-fcbc-4358-bbc9-3d8f1d0cb687

## Expected behavior

The snackbar messages should be shown for sufficiently long period of time.
 
## Steps to reproduce the issue

1. Install the build from https://github.com/learningequality/kolibri/releases/tag/v0.19.3-rc1
2. Go to `Coach > Class home > class > Mark attendance`

## Usage Details
Windows 11, Ubuntu 22, Mac OS 15.5  - Chrome, Firefox
https://github.com/learningequality/kolibri/releases/tag/v0.19.3-rc1

### PR DESCRIPTION
**Pull request by LianaHarris360**
## Summary

This pull request shows the attendance success snackbar on `AttendanceHistoryPage` after redirect, instead of on the page being left. The attendance flow has been updated so `AttendanceNewPage` and `AttendanceEditPage` pass the snackbar message through navigation, and `AttendanceHistoryPage` displays it once on load, then clears it from the URL.

Before:

https://github.com/user-attachments/assets/99ecc562-c064-4f43-a3f7-e36066596ba7

After:

https://github.com/user-attachments/assets/b2bab13f-a71c-4862-9ca3-fbafb00668c8

## References

Fixes #14417 

## Reviewer guidance

1. Go to Coach > Class home > class > Mark attendance
2. Edit or create a new attendance session and confirm the success snackbar appears on the attendance history page
3. Confirm that the snackbar only appears once and does not reappear on refresh

## AI usage
I used Codex to help implement the route-based snackbar handling and update the related tests. I reviewed and refined the changes, checked that the flow stayed consistent with existing coach patterns, and verified the Jest tests pass.

### CODE REVIEW

**Review by rtibblesbot — COMMENTED** [review]
Clean fix for the snackbar timing issue. The approach — passing the message as a query param and displaying it `onMounted` in the destination page — is a well-established pattern that correctly solves the race between navigation and snackbar display.

CI still running. Videos confirm the snackbar now appears on the history page after redirect.

- **suggestion:** Snackbar message passed as a URL query param (see inline)
- **praise:** Good test coverage for the new snackbar-via-query flow, including URL cleanup verification

---
_@rtibblesbot's comments are generated by an LLM, and should be evaluated accordingly_

<details><summary>How was this generated?</summary>

Reviewed the pull request diff checking for:
- **Correctness:** bugs, edge cases, undocumented behavior, resource leaks, hardcoded values
- **Design:** unnecessary complexity, naming, readability, comment accuracy, redundant state
- **Architecture:** duplicated concerns, minimal interfaces, composition over inheritance
- **Testing:** behavior-based assertions, mocks only at hard boundaries, accurate coverage
- **Completeness:** missing dependencies, unupdated usages, i18n, accessibility, security
- **Principles:** DRY (same reason to change), SRP, Rule of Three (no premature abstraction)
- Checked CI status and linked issue acceptance criteria
- For UI changes: inspected screenshots for layout, visual completeness, and consistency

</details>

File: kolibri/plugins/coach/frontend/views/attendance/AttendanceHistoryPage.vue [hunk 1]
```diff
@@ -189,6 +194,18 @@
         baseOptions.find(o => o.value === DateRangeFilters.LAST_30_DAYS),
       );
 
+      onMounted(() => {
+        const { snackbar, ...query } = route.query;
+        if (snackbar) {
+          createSnackbar(snackbar);
```
Comment (rtibblesbot) [inline kolibri/plugins/coach/frontend/views/attendance/AttendanceHistoryPage.vue:200]: **suggestion:** The snackbar text is read directly from `route.query.snackbar`, which means any string placed in the URL will be displayed. Since snackbars render text content (not HTML), this isn't a security issue, but it does mean a user could craft a URL that displays arbitrary text in the snackbar. This is low-risk and probably fine for an internal coach page, but worth being aware of.

File: kolibri/plugins/coach/frontend/composables/useAttendanceForm.js [hunk 2]
```diff
@@ -121,8 +121,11 @@ export default function useAttendanceForm({ hasChanges, markClean, submitting, o
     showMarkAllModal.value = false;
   }
 
-  function navigateBack() {
-    router.push(backRoute.value);
+  function navigateBack(query = {}) {
```
Comment (rtibblesbot) [inline kolibri/plugins/coach/frontend/composables/useAttendanceForm.js:124]: **praise:** Nice clean change — making `navigateBack` accept an optional `query` parameter keeps the composable flexible without overcomplicating it. The default empty object means existing call sites (if any) continue to work unchanged.

File: kolibri/plugins/coach/frontend/views/attendance/AttendanceEditPage.vue [hunk 3]
```diff
@@ -182,8 +181,7 @@
           originalAttendanceMap.value = { ...currentMap };
           form.setPreviouslyEnrolled(removedRecords);
         } catch (_err) {
-          createSnackbar(submitErrorMessage$());
-          form.navigateBack();
+          form.navigateBack({ snackbar: submitErrorMessage$() });
```
Comment (rtibblesbot) [inline kolibri/plugins/coach/frontend/views/attendance/AttendanceEditPage.vue]: **suggestion:** This changes the error-on-load behavior: previously the error snackbar was shown on the current page before navigating back, now the error message is passed via the URL and shown after arriving at the history page. The new behavior is arguably better (user sees the error on the page they land on), but it's a subtle behavioral change beyond the stated fix. Just flagging in case it was unintentional.

File: kolibri/plugins/coach/frontend/views/attendance/__tests__/AttendanceHistoryPage.spec.js [hunk 4]
```diff
@@ -179,6 +196,20 @@ describe('AttendanceHistoryPage', () => {
       expect(wrapper.findComponent({ name: 'ReportsControls' }).exists()).toBe(true);
     });
 
+    it('shows the snackbar from the route query and clears it', async () => {
```
Comment (rtibblesbot) [inline kolibri/plugins/coach/frontend/views/attendance/__tests__/AttendanceHistoryPage.spec.js:199]: **praise:** Good test — verifies both that the snackbar is shown and that the query param is cleaned from the URL afterward. This ensures the snackbar won't reappear on refresh.

File: kolibri/plugins/coach/frontend/views/attendance/AttendanceEditPage.vue (hunk 3 above)
Comment (nucleogenesis) [reply kolibri/plugins/coach/frontend/views/attendance/AttendanceEditPage.vue]: (Non-blocking)

To see how this feels I put a `Promise.reject()` up above in the `Promise.all()` params to get a failure and the UX for this ends up being:

- Click to edit attendance
- See failed attempt to navigate by going to the form then back to the history page
- See snackbar "There was a problem saving attendance"

This feels right to me, although maybe there is a better message for that particular case, but that's not the scope of this PR.

File: kolibri/plugins/coach/frontend/views/attendance/AttendanceHistoryPage.vue (hunk 1 above)
Comment (nucleogenesis) [reply kolibri/plugins/coach/frontend/views/attendance/AttendanceHistoryPage.vue:200]: I think that this works good here - I thought that `<GlobalSnackbar />` prevented this specific bug where we can trigger Snackbars while navigating away and went looking for another instance where I recall we had this requirement and found this example where we used a pattern similar to the one you used here 😅 

https://github.com/learningequality/kolibri/blob/c42b60db8c7e2e7b0a69f515713657b023ed47a7/kolibri/plugins/coach/frontend/views/quizzes/CreateExamPage/index.vue#L332-L343

**Review by nucleogenesis — APPROVED** [review]
Tested it out locally and things look great to me. Just added a couple non-blocking comments in-thread w/ rtibblesbot. Thanks @LianaHarris360

File: kolibri/plugins/coach/frontend/views/attendance/AttendanceEditPage.vue (hunk 3 above)
Comment (LianaHarris360) [reply kolibri/plugins/coach/frontend/views/attendance/AttendanceEditPage.vue]: I agree that there should be a more relevant message shown here. I've updated it to show the `defaultErrorMessage` "Sorry! Something went wrong, please try again." instead.

https://github.com/user-attachments/assets/78c7867e-7cbb-4612-8db1-448a0b0bb709

File: kolibri/plugins/coach/frontend/views/attendance/AttendanceEditPage.vue [hunk 5]
```diff
@@ -182,8 +181,7 @@
           originalAttendanceMap.value = { ...currentMap };
           form.setPreviouslyEnrolled(removedRecords);
         } catch (_err) {
-          createSnackbar(submitErrorMessage$());
-          form.navigateBack();
+          form.navigateBack({ snackbar: coreString('defaultErrorMessage') });
```
Comment (rtibblesbot) [inline kolibri/plugins/coach/frontend/views/attendance/AttendanceEditPage.vue:184]: **praise:** Good fix — using `defaultErrorMessage` here correctly distinguishes a data-loading failure from a submission failure. The previous `submitErrorMessage$()` would have been confusing to the user in this context.

**Review by rtibblesbot — APPROVED** [review]
Clean delta addressing the prior review feedback.

**Prior-review finding resolution:**
- **CONTESTED:** Snackbar text from query param (AttendanceHistoryPage.vue:200) — @nucleogenesis confirmed the pattern is acceptable and pointed to existing precedent in CreateExamPage. Dropping.
- **RESOLVED:** Error message on load failure (AttendanceEditPage.vue:184) — @LianaHarris360 updated to use `defaultErrorMessage` in commit a0ee6b2f, which is more appropriate for a data-loading error than the previous submit-specific message. @nucleogenesis approved.

New commit a0ee6b2f changes the catch handler in `loadData` to show the generic error message instead of the submit-specific one. The change is correct and well-scoped.

CI still running (build assets). Videos confirm the snackbar appears on the history page after redirect. PR targets `release-v0.19.x` (not the default branch `develop`), which is appropriate for a patch release bugfix — no new i18n strings are introduced by this delta.

---
_@rtibblesbot's comments are generated by an LLM, and should be evaluated accordingly_

<details><summary>How was this generated?</summary>

Compared the current PR state against findings from a prior review:
- Retrieved prior bot reviews deterministically via the GitHub API
- Classified each prior finding as RESOLVED, UNADDRESSED, ACKNOWLEDGED, or CONTESTED
- Only raised NEW findings for newly introduced code
- Reviewed the pull request diff checking for correctness, design, architecture, testing, completeness, and adherence to DRY/SRP principles
- Checked CI status and linked issue acceptance criteria

</details>
