### PR TITLE
Bookmark font size

### LINKED ISSUE #8844: Metadata font sizes on bookmarks page cards (below thumbnail) are incorrect
Update to ensure fonts match figma spec 
https://www.notion.so/learningequality/FEEDBACK-Learn-Bookmarks-List-80103926efec4dcb8d6e1a1467234278

Untitled (1)

### PR DESCRIPTION
**Pull request by sairina**
## Summary
Some UI updates to make the bookmark cards more closely aligned to [spec in Figma](https://www.figma.com/file/uiZuCIqh2KYvBUfbCiJyyA/Hybrid-Learning?node-id=76%3A6747).
- Moved the right icons into their own separate row, per spec
- Updated size of thumbnail
- Updated margins for card

Screen Shot 2021-12-08 at 12 05 04 PM

## References
Fixes #8844 

## Reviewer guidance

- [ ] Check to see if bookmarked cards now more closely match the specs
- [ ] Check to see if there is brittleness in CSS that should be fixed
- [ ] Check for regressions

## Testing checklist

- [x] Contributor has fully tested the PR manually
- [x] If there are any front-end changes, before/after screenshots are included

## PR process

- [x] PR has the correct target branch and milestone
- [x] PR has 'needs review' or 'work-in-progress' label
- [x] If PR is ready for review, a reviewer has been added. (Don't use 'Assignees')

## Reviewer checklist

- Automated test coverage is satisfactory
- PR is fully functional
- PR has been tested for [accessibility regressions](http://kolibri-dev.readthedocs.io/en/develop/manual_testing.html#accessibility-a11y-testing)
- External dependency files were updated if necessary (`yarn` and `pip`)
- Documentation is updated
- Contributor is in AUTHORS.md

### CODE REVIEW

File: kolibri/plugins/learn/assets/src/views/HybridLearningContentCardListView.vue [hunk 1]
```diff
@@ -268,24 +268,20 @@
     position: absolute;
     bottom: 0;
     width: 100%;
-    padding: $margin;
+    padding: $margin 24px;
```
Comment (indirectlylit) [inline kolibri/plugins/learn/assets/src/views/HybridLearningContentCardListView.vue]: Is there a reason to keep `$margin` around? It doesn't appear to be used except here.

We can delete it and just do:


```suggestion
    padding: 16px 24px;
```

File: kolibri/plugins/learn/assets/src/views/HybridLearningContentCardListView.vue [hunk 2]
```diff
@@ -70,7 +70,7 @@
       </span>
     </router-link>
     <KFixedGrid :numCols="10" class="footer">
-      <KFixedGridItem span="6" class="footer-elements">
+      <KFixedGridItem span="3" class="footer-elements">
```
Comment (indirectlylit) [inline kolibri/plugins/learn/assets/src/views/HybridLearningContentCardListView.vue]: This is a bit confusing because `numCols` is 10 but the grid item spans are 3 and 10, which don't add up.

If these items are always on separate rows, we don't need the grid at all and can just use two divs.

**Review by indirectlylit — APPROVED** [review]
no blocking changes, but some cleanup would be nice for future editors

File: kolibri/plugins/learn/assets/src/views/HybridLearningContentCardListView.vue [hunk 3]
```diff
@@ -278,13 +278,18 @@
...
+
+  .footer-progress {
+    width: 240px;
   }
 
   .footer-icons {
     // this override fixes an existing KDS bug with
     // the hover state circle being squished
     // and can be removed upon that hover state fix
+    float: right;
```
Comment (indirectlylit) [inline kolibri/plugins/learn/assets/src/views/HybridLearningContentCardListView.vue:292]: two issues here:

1. the new line is inserted below a comment that describes something completely unrelated! that will be very confusing for future editors.
2. `float: right` is a very brittle mechanism for doing layout. Instead, it's usually better to use one or more of `position: absolute; right: 0`, `text-align: right`, `KGrid`, or flexbox

**Review by indirectlylit — CHANGES_REQUESTED** [review]
Today I looked closer at both the changes in this PR and also the preexisting code and a few things raised some flags.

I went back to check [the Figma spec](https://www.figma.com/file/uiZuCIqh2KYvBUfbCiJyyA/Hybrid-Learning?node-id=76%3A6747), and unfortunately it isn't explicit about how the grid layout within the card is supposed to work. This is something that future KDS reviews should hopefully help address.

Looking at it though, my impression was that the intent is something like this:

image

However the actual DOM structure looks like this:



One serious user-facing consequence of this is that the whole bottom-half of the card looks like it should be clickable but is not. This will cause especially tablet users a ton of frustration:



I think the overall layout of this component needs to be cleaned up. If it would be helpful, I'd be happy to take this on in order to demonstrate how `KGrid` can be useful here.

File: kolibri/plugins/learn/assets/src/views/HybridLearningContentCardListView.vue (hunk 1 above)
Comment (indirectlylit) [reply kolibri/plugins/learn/assets/src/views/HybridLearningContentCardListView.vue]: now that `$margin` is completely unused, the definition should be deleted
