### PR TITLE
Hashi and content renderer cleanup

### LINKED ISSUE #4724: Hashi no hash-y
### Observed behavior
Currently we build hashi without a build hash. This means that in the future if we upgrade our Hashi functionality, this may not get cache busted.

### Expected behavior
New versions of Hashi should cache bust old versions!

### User-facing consequences
Weird, unpredictable Hashi behaviour, depending on previous use.

### LINKED ISSUE #4725: Not possible to 'complete' an HTML5 App
### Observed behavior
In introducing Hashi, the 15s insta-points was removed from HTML5 apps. Now impossible to register any progress.

### Expected behavior
What should progress look like for an arbitrary HTML5 app?

### User-facing consequences
Confusion?

### PR DESCRIPTION
**Pull request by rtibbles**
### Summary
Hashi did not have a build hash for each build. This left it vulnerable to never being upgraded.
This fixes this by adding a build has to the build, and then using that to calculate an ETag on the zipcontent endpoint, so that the ETag gets updated for html files fetched from the endpoint, based on the hashi tag. This will allow cache busting when the hashi version is updated.

In addition, this reinstate completion for HTML5 apps, with a 5 minute timer.

Further, it adds a minor bug fix to session progress logging, whereby we were not maxing out the session progress at `1`.

### Reviewer guidance
Does the HTML5 renderer still work as expected?
Given that I am doing a vary-on the `XHR` header, perhaps all of the etag business is unnecessary, because the resource will be reloaded as long as the last time something was loaded was with XHR if the current request was not with XHR. Thoughts?

### References
Fixes #4724, and closes #4725

----

### Contributor Checklist

PR process:

- [x] PR has the correct target branch and milestone
- [x] PR has 'needs review' or 'work-in-progress' label
- [x] If PR is ready for review, a reviewer has been added. (Don't use 'Assignees')
- [ ] If this is an important user-facing change, PR or related issue has a 'changelog' label
- [ ] If this includes an internal dependency change, a link to the diff is provided

Testing:

- [x] Contributor has fully tested the PR manually
- [ ] If there are any front-end changes, before/after screenshots are included
- [ ] Gherkin stories have been updated
- [ ] Unit tests have been updated

### Reviewer Checklist

- Automated test coverage is satisfactory
- PR is fully functional
- PR has been tested for [accessibility regressions](http://kolibri-dev.readthedocs.io/en/develop/manual_testing.html#accessibility-a11y-testing)
- External dependency files were updated if necessary (`yarn` and `pip`)
- Documentation is updated
- Contributor is in AUTHORS.rst

### CODE REVIEW

**Comment by indirectlylit** [comment]
FYI tests are failing in this PR

File: kolibri/core/assets/src/state/modules/core/actions.js [hunk 1]
```diff
@@ -519,7 +519,7 @@ export function updateProgress(store, { progressPercent, forceSave = false }) {
   /* Calculate progress based on progressPercent */
   // TODO rtibbles: Delegate this to the renderers?
   progressPercent = progressPercent || 0;
-  const sessionProgress = sessionLog.progress + progressPercent;
+  const sessionProgress = Math.min(1, sessionLog.progress + progressPercent);
```
Comment (rtibbles) [inline kolibri/core/assets/src/state/modules/core/actions.js:565]: Hrm, this should be `Math.max`, I think...

Comment (rtibbles) [reply kolibri/core/assets/src/state/modules/core/actions.js:565]: Oh no - this is right, nvm...

**Review by kollivier — APPROVED** [review]
Change itself looks good to go, but I think we really need to rethink the point allocation metric. Five minutes may be too long for some of the simpler simulations, where you can run through them within a couple minutes, and it can also be way too low for some other experiences.  We should seriously consider either allowing customization, or, my preference, just awarding points based on time spent with a max of 500 total to be earned.

**Comment by ralphiee22** [comment]
I am getting completion of html 5 apps in PHET in around 1m30s. Is this expected?
