### PR TITLE
Better missing resources handling

### LINKED ISSUE #13447: Follow-up to "Handle missing resources better in quiz editing"
❌ **This issue is not open for contribution. Visit <a href="https://learningequality.org/contributing-to-our-open-code-base/" target="_blank">Contributing guidelines</a>** to learn about the contributing process and how to find suitable issues.

 
1. When I attempt to preview deleted questions - in that case I can see the titles of the questions but if I try to preview them I am seeing "Kolibri is unable to render this resource" and the problem with that is that it's not clear why this is so whether the resource is not working properly or is not present on the device. 
https://github.com/user-attachments/assets/61874cdd-063f-4f58-bb61-9c33819a0a47

2. When I try to add more questions and there are no resources, then I am seeing "There are currently **only 0** questions across all practice resources on your device", the "Continue" button is still active too.

https://github.com/user-attachments/assets/7a542b9c-29a1-4ed2-9edd-5e71fff1fcae

_Originally posted by @pcenov in https://github.com/learningequality/kolibri/issues/13288#issuecomment-2922723269_

### PR DESCRIPTION
**Pull request by akolson**
## Summary

This pr improves handling of missing resources during quiz editing. See details in #13447.

## References

Fixes #13447

## Reviewer guidance

The behavior should be as detailed by @pcenov  [here](https://github.com/learningequality/kolibri/issues/13447#issuecomment-3841364039)

### CODE REVIEW

File: kolibri/plugins/coach/frontend/views/common/QuestionsAccordion.vue [hunk 1]
```diff
@@ -356,6 +356,10 @@
       getDisplayQuestionTitle(question, title) {
         return title || this.coreString('resourceNotFoundOnDevice');
       },
+      questionContentExists(question) {
+        const content = this.getQuestionContent(question);
+        return content && content.available;
+      },
```
Comment (rtibblesbot) [inline kolibri/plugins/coach/frontend/views/common/QuestionsAccordion.vue:362]: **praise:** Good improvement — checking `content.available` rather than just truthiness of the content object properly distinguishes between "content metadata exists" and "resource is actually on device". This directly addresses the confusing "unable to render" message from the issue.

File: kolibri/plugins/coach/frontend/views/quizzes/CreateExamPage/sidePanels/QuizResourceSelection/subPages/QuestionsSettings.vue [hunk 2]
```diff
@@ -160,13 +160,14 @@
       onMounted(() => {
         props.setContinueAction({
           handler: continueHandler,
+          disabled: addableQuestionCount.value === 0,
```
Comment (rtibblesbot) [inline kolibri/plugins/coach/frontend/views/quizzes/CreateExamPage/sidePanels/QuizResourceSelection/subPages/QuestionsSettings.vue:163]: **praise:** Correctly disables the Continue button both on mount and when `invalidSettings` changes. This directly fixes the issue where users could click Continue with 0 available questions.

File: kolibri/plugins/coach/frontend/views/quizzes/CreateExamPage/sidePanels/SectionSidePanel/SectionEditor.vue [hunk 3]
```diff
@@ -408,6 +427,14 @@
           this.$emit('closePanel');
         }
       },
+      async loadChannels() {
+        this.loading = true;
+        try {
+          this.channels = await this.fetchChannels({ contains_exercise: true });
+        } finally {
+          this.loading = false;
+        }
```
Comment (rtibblesbot) [inline kolibri/plugins/coach/frontend/views/quizzes/CreateExamPage/sidePanels/SectionSidePanel/SectionEditor.vue:436]: **suggestion:** This `loadChannels` method (plus `channels` data, `loading` data, `hasChannels` computed, and `mounted` hook) is now duplicated identically in `SectionEditor`, `QuizLessonDetailsHeader`, and with minor variation in `ExamsRootPage`. Consider extracting this into a shared composable (e.g. `useExerciseChannels`) that returns `{ channels, hasChannels, loading }` and handles the fetch internally. This would reduce the repeated boilerplate and make the channel-availability logic easier to maintain.

**Review by rtibblesbot — COMMENTED** [review]
Solid PR that addresses all three acceptance criteria from the linked issue: replacing the vague "unable to render" message with "Resource not found on device", showing the correct alert banner depending on whether channels exist, and disabling the Continue button when no resources are available.

CI passing. No blocking issues found.

- **suggestion:** The `loadChannels` pattern is duplicated across three components — consider extracting it (see inline comment)
- **suggestion:** Moving the `adminLink` string to a new component creates a new translation key on a non-default branch (see inline comment)
- **praise:** Good addition of `hasMissingResources` on the quizzes list page and the `questionContentExists` availability check

---
_@rtibblesbot's comments are generated by an LLM, and should be evaluated accordingly_

<details><summary>How was this generated?</summary>

Reviewed the pull request diff checking for:
- **Correctness:** bugs, edge cases, undocumented behavior, resource leaks, hardcoded values
- **Design:** unnecessary complexity, naming, readability, comment accuracy, redundant state
- **Architecture:** duplicated concerns, minimal interfaces, composition over inheritance
- **Testing:** behavior-based assertions, mocks only at hard boundaries, accurate coverage
- **Completeness:** missing dependencies, unupdated usages, i18n, accessibility, security
- **Principles:** DRY (same reason to change), SRP, Rule of Three (no premature abstraction)
- Checked CI status and linked issue acceptance criteria
- For UI changes: inspected screenshots for layout, visual completeness, and consistency

</details>

File: packages/kolibri-common/components/NoResourceAlert.vue [hunk 4]
```diff
@@ -0,0 +1,93 @@
...
+      deviceContentUrl() {
+        const url = urls['kolibri:kolibri.plugins.device:device_management'];
+        if (url && this.canManageContent) {
+          return `${url()}#/content`;
+        }
+        return '';
+      },
+    },
+    $trs: {
+      adminLink: {
```
Comment (rtibblesbot) [inline packages/kolibri-common/components/NoResourceAlert.vue:55]: **suggestion:** The `adminLink` string was previously under `ExamsRootPage.$trs` and is now under `NoResourceAlert.$trs`. Even though the message text is identical, this creates a new translation key. Since this PR targets `release-v0.19.x` (not the default branch `develop`), check with the team whether CrowdIn's translation memory will automatically match it — otherwise some locales may temporarily show the untranslated English string.

File: kolibri/plugins/coach/frontend/views/quizzes/ExamsRootPage.vue [hunk 5]
```diff
@@ -483,16 +460,11 @@
...
-        }
-
-        return '';
+      hasChannels() {
+        return this.channels.length > 0;
       },
-      hasNoChannels() {
-        return this.channels.length === 0;
+      hasMissingResources() {
+        return Object.values(this.examMap).some(exam => exam.missing_resource);
```
Comment (rtibblesbot) [inline kolibri/plugins/coach/frontend/views/quizzes/ExamsRootPage.vue:467]: **praise:** Good addition — surfacing `hasMissingResources` at the quizzes list level addresses the acceptance criteria point about showing the "Some resources are missing" banner on the Coach > Quizzes page when some (but not all) resources are missing.

File: packages/kolibri-common/components/NoResourceAlert.vue (hunk 4 above)
Comment (nucleogenesis) [reply packages/kolibri-common/components/NoResourceAlert.vue:55]: @akolson this is blocking - will need to use `crossComponentTranslator` to get the string you need from the other component

Comment (rtibblesbot) [reply packages/kolibri-common/components/NoResourceAlert.vue:55]: Good call — `crossComponentTranslator` is the right approach to reuse the existing translation key without creating a duplicate.

**Review by nucleogenesis — CHANGES_REQUESTED** [review]
Changes look good overall, but rtibblesbot correctly points out that we cannot add the string definition to `NoResourceAlert.$trs`  but instead need to create a translator object from the component like:

```javascript
import { crossComponentTranslator } from 'kolibri/utils/i18n';

// Make the translator object for the component
const ExamsRootStrings = crossComponentTranslator(ExamsRoot);

// Then wherever you use the string:
ExamsRootStrings.$tr('adminLink')
```

**Comment by nucleogenesis** [comment]
Noting that I did manual testing on this yesterday and saw no issues. I'm comfortable merging this when the string is updated.

**Review by nucleogenesis — APPROVED** [review]
@rtibbles mentioned that some of our build machinery can do the auto-translate for us (maybe/hopefully) but if not, we can manually do so in Crowdin to avoid the crossComponetnTranslator here

**Comment by pcenov** [comment]
Thanks @akolson and @nucleogenesis!

Just noting that the second point of https://github.com/learningequality/kolibri/issues/13447 is partially fixed as the 'Continue' button is disabled now but the message: "There are currently **only** 0 questions across all practice resources on your device" is still present:

https://github.com/user-attachments/assets/84dd311d-a74e-4bd0-a429-ebe2c8a44410

Since now there are plenty of clear indications as to what the user is actually supposed to do I don't think we should make any additional changes.

**Comment by akolson** [comment]
Thanks @pcenov! we could write up an issue and have this fixed in an upcoming patch if it will makes things even more clearer?
