### PR TITLE
Minimal fixes for IE9 Compatibility

### LINKED ISSUE #149: intl polyfill is not loading - affects at least Safari and IE9
**Branch** vue-hacking
**Browser** Safari 9.1.1

Followed the document at https://docs.google.com/document/d/1OrMHqOscjPHpbjx0eeEylzuS6A94nC2_tgwdBiJkH5E/edit# using Safari but it doesn't load the learn page, with this error

> ReferenceError: Can't find variable: Intl.  

Here's a screenshot:
screenshot 2016-06-10 05 38 10

We tried to re-create our virtualenvs, removed the `node_modules` directory, and re-did the steps but got the same error.

**Workaround**: use Google Chrome.

### PR DESCRIPTION
**Pull request by rtibbles**
## Summary

Kolibri currently does not work at all on IE9.

This makes it work on IE9.

## Reviewer guidance

This is mostly just about shimming and polyfilling things that are missing in IE9.

I have done it on a 'per needs' basis, so we may yet add things that still need to be polyfilled or shimmed.

## Issues addressed

Fixes #149.

## Screenshots (if appropriate)

image

### CODE REVIEW

File: kolibri/core/assets/src/core_app_constructor.js [hunk 1]
```diff
@@ -77,10 +72,20 @@ module.exports = function CoreApp() {
       (require) => {
         require('intl');
         require('intl/locale-data/jsonp/en.js');
+        /**
```
Comment (rtibbles) [inline kolibri/core/assets/src/core_app_constructor.js:75]: Moved this inside the require blocks, because `Intl` has to be defined when `vue-intl` is required.

File: kolibri/core/templates/kolibri/base.html [hunk 2]
```diff
@@ -1,4 +1,5 @@
 {% load i18n kolibri_tags webpack_tags js_reverse cache %}<html>
+<meta http-equiv="X-UA-Compatible" content="IE=Edge">
```
Comment (rtibbles) [inline kolibri/core/templates/kolibri/base.html:2]: Need this to force IE9 to behave more like a modern browser by default.

File: kolibri/core/assets/src/core_app_instance.js [hunk 3]
```diff
@@ -3,6 +3,7 @@
 require('normalize.css');
 require('./font-NotoSans.css');
 require('./core-global.styl');
+require('babel-polyfill');
```
Comment (rtibbles) [inline kolibri/core/assets/src/core_app_instance.js:6]: We weren't loading in the babel polyfill anywhere, so things like Symbols were not being properly polyfilled.

File: kolibri/core/assets/src/api_resource.js [hunk 4]
```diff
@@ -281,7 +281,11 @@ class ResourceManager {
       throw new TypeError('A resource with that name has already been registered!');
     }
     this._resources[name] = new ResourceClass(this._kolibri);
-    Object.defineProperty(this, ResourceClass.name, { value: this._resources[name] });
+    // Shim for IE9 compatibility of .name property.
+    // Modified from: http://matt.scharley.me/2012/03/monkey-patch-name-ie.html#comment-551654096
+    const className = ResourceClass.name || /function\s([^(]{1,})\(/.exec(
```
Comment (rtibbles) [inline kolibri/core/assets/src/api_resource.js:286]: `.name` is a very ES6 thing that does not get transpiled by Babel. This shim gives us consistent naming in IE9 too.

File: frontend_build/src/webpack.config.base.js [hunk 5]
```diff
@@ -41,7 +41,11 @@ var config = {
       {
         test: /\.js$/,
         loader: 'babel',
-        exclude: /node_modules/
+        exclude: /node_modules/,
+        query: {
+          presets: ['es2015-ie'],
```
Comment (rtibbles) [inline frontend_build/src/webpack.config.base.js:46]: Use this special preset that forces classes to be transformed in a way that makes them IE9 compatible. Without this, subclasses of `KolibriModule` were not running the parent constructor.

**Comment by indirectlylit** [comment]
Running `npm run test` gives me:

```
PhantomJS 2.1.1 (Mac OS X 0.0.0) ERROR
  Error: only one instance of babel-polyfill is allowed
  at /Users/d/Projects/learning_equality/repos/kolibri/kolibri/plugins/management/assets/test/app.js:16964 <- webpack:///~/babel-polyfill/lib/index.js:12:0
```

**Comment by rtibbles** [comment]
Yes! Should have remembered that we included that for testing - I had to include it in the main Kolibri App, as IE9 needs the polyfills. Will fix.
