### PR TITLE
Remove kfixedgrid from category search modal

### LINKED ISSUE #8988: Library's category search modal's options' `KFixedGrid` requires `numCols` to be greater than 1
## Observed behavior
In the mobile view, when a learner clicks on Filter button to open the side panel overlay, if they click on a category like "School," there is an error message on the console related to `KFixedGrid` and the `numCols` prop passed from `CategorySearchModal` to `CategorySearchModalOptions`. 

The validator for `KFixedGrid` requires a number between 2 and 12, but the `numCols` passed to `CategorySearchModalOptions` is 1.

Screen Shot 2022-01-11 at 2 49 57 PM

## Errors and logs
Screen Shot 2022-01-11 at 2 50 37 PM

## Expected behavior
No error in console.

## User-facing consequences
Unless there is a design change, there are no user-facing consequences.

## Steps to reproduce
1. Sign in as learner on a small mobile
2. Go to library page
3. Click on "Filter button"
4. Click on a category (like, "School")
5. Check the console in the browser

## Context
Chrome
Kolibri 0.15

### PR DESCRIPTION
**Pull request by marcellamaki**
## Summary

Fixes #8988 

This PR cleans up the `CategorySearchModal` implementation in several ways. 
1) Rather than using `KFixedGrid` (which does not allow for numCols === 1), it uses `KGrid`
2) This eliminates the need for some props (that I probably never should have added) also
3) Removes a file that wasn't being used at all! 🆘 
4) Changes the display of the `CategorySearchModal` on the Library page to use `FullScreenSidePanel` on medium screens, per [slack discussion](https://learningequality.slack.com/archives/CB37UM23A/p1642790416108000).

## References
Most of this refactor should result in no changes to the UI, with the exception of the "medium screen" change (#4): 

medium-screen-category-search

## Reviewer guidance

- Does the category search work at each screen resolution? 
- Are there any bugs in the layout (overlapping/squished words, etc.)? 

----

## Testing checklist

- [x] Contributor has fully tested the PR manually
- [x] If there are any front-end changes, before/after screenshots are included
- [ ] Critical user journeys are covered by Gherkin stories
- [ ] Critical and brittle code paths are covered by unit tests

## PR process

- [x] PR has the correct target branch and milestone
- [x] PR has 'needs review' or 'work-in-progress' label
- [x] If PR is ready for review, a reviewer has been added. (Don't use 'Assignees')
- [ ] If this is an important user-facing change, PR or related issue has a 'changelog' label
- [ ] If this includes an internal dependency change, a link to the diff is provided

## Reviewer checklist

- Automated test coverage is satisfactory
- PR is fully functional
- PR has been tested for [accessibility regressions](http://kolibri-dev.readthedocs.io/en/develop/manual_testing.html#accessibility-a11y-testing)
- External dependency files were updated if necessary (`yarn` and `pip`)
- Documentation is updated
- Contributor is in AUTHORS.md

### CODE REVIEW

File: kolibri/plugins/learn/assets/src/views/CategorySearchModal/CategorySearchOptions.vue [hunk 1]
```diff
@@ -123,8 +95,8 @@
   }
 
   export default {
-    name: 'CategorySearchModalOptions',
```
Comment (rtibbles) [inline kolibri/plugins/learn/assets/src/views/CategorySearchModal/CategorySearchOptions.vue:126]: Was going to leave a comment here about not doing this because strings - but there are no strings in this component, so I'll leave this comment to preempt any such similar comments!

**Review by nucleogenesis — APPROVED** [review]
Code LGTM.

I tested in browser and it looks good! 

One thing - the FullScreenSidePanel that contains the sub-menu on mobile (listing all of the options under headings) - should have the `fullScreenSidePanelCloseButton` prop set to false. In RTL the back arrow and X sit right next to each other. 

image

**Comment by marcellamaki** [comment]
> One thing - the FullScreenSidePanel that contains the sub-menu on mobile (listing all of the options under headings) - should have the `fullScreenSidePanelCloseButton` prop set to false. In RTL the back arrow and X sit right next to each other.

Good catch. Should be fixed now
rtl-close-button
ltr-close-button-fix

**Comment by marcellamaki** [comment]
[Final changes reviewed and ✅  by @radinamatic](https://learningequality.slack.com/archives/CB37UM23A/p1644882031346249?thread_ts=1644846715.694049&cid=CB37UM23A) and @sairina
