### PR TITLE
Refined prev/next buttons in course viewer

### LINKED ISSUE #14220: Course content viewer - The 'Previous' and 'Next' buttons are not styled as specified in Figma
❌ **This issue is not open for contribution. Visit <a href="https://learningequality.org/contributing-to-our-open-code-base/" target="_blank">Contributing guidelines</a>** to learn about the contributing process and how to find suitable issues.

## Observed behavior
Observed while testing https://github.com/learningequality/kolibri/pull/14122:

Image

## Expected behavior

The buttons should be styled as specified in [Figma](https://www.figma.com/design/MtmNfgSbx8xBlBBJOQmW9g/Pre--post-tests?node-id=1788-19166&p=f).
 
## Steps to reproduce the issue

1. Install the build from https://github.com/learningequality/kolibri/pull/14122
2. Sign in as a learner with assigned courses
3. Start interacting with a course

## Usage Details
Windows 11, Ubuntu 22, Mac OS 15.5  - Chrome, Firefox

### PR DESCRIPTION
**Pull request by nucleogenesis**
## Summary

Applies styles to match those in the Figma for PrevNextBar.vue and aligns arrow icons w/ their text. Some specific changes I gleaned from Figma and other notes:

- 8px gap between text & icon 
- 8px padding all around (vs 0 16px previously)
- font weight semibold now (which I think looks aces)
- icons are 2px smaller in size than default KIcon
- icon needs -2px top value (hotfix to -3px due to https://github.com/learningequality/kolibri-design-system/pull/1219)

|Looks good big & small :+1: |
|---|
|image|
|image|

| **No More Eye Twitches** |
|---|
|image|

## References

Closes #14220 

## Reviewer guidance

Check out a course as a learner and see the sweet new button styles!

### CODE REVIEW

File: kolibri/plugins/learn/frontend/views/PrevNextBar/index.vue [hunk 1]
```diff
@@ -3,19 +3,22 @@
   <div class="prev-next-bar">
     <!-- Prev button on the left -->
     <KButton
+      class="btn-flex"
+      appearance="flat-button"
       data-testid="prev-button"
+      :style="{ gap: showButtonLabels ? '8px' : '0px' }"
```
Comment (nucleogenesis) [inline kolibri/plugins/learn/frontend/views/PrevNextBar/index.vue]: This was a bit annoying but it's due to KButton internal `<span>`s being present even if empty, so the gaps would be rendered and the arrow off-center unless I cleared the gap value like this.

File: kolibri/plugins/learn/frontend/views/PrevNextBar/index.vue [hunk 2]
```diff
@@ -168,12 +174,22 @@
...
-
-    .icon {
-      top: 0;
+    padding: 8px;
+    font-weight: 600;
+    line-height: 135%;
+
+    .btn-icon {
+      top: -2px;
+      flex-grow: 1;
```
Comment (rtibblesbot) [inline kolibri/plugins/learn/frontend/views/PrevNextBar/index.vue]: **suggestion:** `flex-grow: 1` on the icon element is surprising — it causes the icon's box to expand to fill remaining space in the flex container, though the SVG stays 16×16. If the intent is just to size and position the icon, `flex-shrink: 0` (prevent shrinking) is more conventional. If this is compensating for a specific KButton slot layout quirk, a brief comment explaining why would help future readers.

File: kolibri/plugins/learn/frontend/views/PrevNextBar/index.vue [hunk 3]
```diff
@@ -168,12 +174,22 @@
...
+      width: 16px;
+      height: 16px;
+
+      &.hotfixed {
```
Comment (rtibblesbot) [inline kolibri/plugins/learn/frontend/views/PrevNextBar/index.vue]: **praise:** Good practice documenting the hotfix with a link to the upstream KDS PR — makes it easy to find and clean up later.

File: kolibri/plugins/learn/frontend/views/PrevNextBar/index.vue [hunk 4]
```diff
@@ -3,19 +3,22 @@
...
+      :text="showButtonLabels ? previousLabel$() : ''"
       @click="handlePrev"
     >
-      <div class="btn-flex">
+      <template #icon>
         <KIcon
-          class="icon"
           icon="back"
+          class="btn-icon"
+          :color="$themeTokens.text"
```
Comment (rtibblesbot) [inline kolibri/plugins/learn/frontend/views/PrevNextBar/index.vue:18]: **praise:** Nice use of `$themeTokens.text` and `$themeTokens.textInverted` for the icon colors — keeps theming consistent.

**Review by rtibblesbot — COMMENTED** [review]
Clean styling refinement that matches the Figma spec. Screenshots look good at both wide and narrow viewports — icons are aligned with text, spacing and font weight match the design.

CI still in progress. PR targets `release-v0.19.x`; no new strings added.

- **suggestion:** `flex-grow: 1` on `.btn-icon` (line 185) — see inline comment
- **praise:** Good use of `#icon`/`#iconAfter` slots and theme tokens

---
_@rtibblesbot's comments are generated by an LLM, and should be evaluated accordingly_

<details><summary>How was this generated?</summary>

Reviewed the pull request diff checking for:
- **Correctness:** bugs, edge cases, undocumented behavior, resource leaks, hardcoded values
- **Design:** unnecessary complexity, naming, readability, comment accuracy, redundant state
- **Architecture:** duplicated concerns, minimal interfaces, composition over inheritance
- **Testing:** behavior-based assertions, mocks only at hard boundaries, accurate coverage
- **Completeness:** missing dependencies, unupdated usages, i18n, accessibility, security
- **Principles:** DRY (same reason to change), SRP, Rule of Three (no premature abstraction)
- Checked CI status and linked issue acceptance criteria
- For UI changes: inspected screenshots for layout, visual completeness, and consistency

</details>

File: kolibri/plugins/learn/frontend/views/PrevNextBar/index.vue (hunk 1 above)
Comment (rtibblesbot) [inline kolibri/plugins/learn/frontend/views/PrevNextBar/index.vue]: **praise:** Pragmatic workaround for the KButton empty-span gap issue — the inline `gap` toggle keeps the icon centered without needing a wrapper element.

**Review by rtibblesbot — APPROVED** [review]
Clean delta — prior `flex-grow` suggestion resolved in 2b923d7. CI passing (core checks green; APK/DMG/Pi builds still pending but unrelated to this change). Screenshots confirm proper alignment and spacing at both wide and narrow viewports.

**Prior review findings:**
- `flex-grow: 1` on `.btn-icon` — **RESOLVED** (removed in latest commit)

No new findings. LGTM.

---
_@rtibblesbot's comments are generated by an LLM, and should be evaluated accordingly_

<details><summary>How was this generated?</summary>

Compared the current PR state against findings from a prior review:
- Retrieved prior bot reviews deterministically via the GitHub API
- Classified each prior finding as RESOLVED, UNADDRESSED, ACKNOWLEDGED, or CONTESTED
- Only raised NEW findings for newly introduced code
- Reviewed the pull request diff checking for correctness, design, architecture, testing, completeness, and adherence to DRY/SRP principles
- Checked CI status and linked issue acceptance criteria

</details>

**Comment by pcenov** [comment]
Hi @nucleogenesis, looks great now, just to make sure: is it intentional that the `Previous` button is reduced to just the label of the button and it changes to a small arrow in mobile view?

https://github.com/user-attachments/assets/46a0cff7-3e08-4fc7-bc60-daaeb798c195

Because for practice quizzes we have the following:

https://github.com/user-attachments/assets/080e1f6d-2332-4a2d-944d-a802f632f1c3

Also a note that the `Submit quiz` looks misplaced in mobile view once both `Previous `and `Next` go on the line above it (quite possibly not in scope of this PR though).

**Comment by marcellamaki** [comment]
> is it intentional that the Previous button is reduced to just the label of the button and it changes to a small arrow in mobile view?

Yes. 

Is the practice quiz view here the practice quiz _within_ a course, or when accessed via a lesson?

I think it would be nice to have these buttons consistent outside the course viewer for quizzes and practice quizzes as well (and I think tomiwa has been leading us toward that), but applying that everwhere is potentially outside of the scope of this PR? I do not actually recall off the top of my head, @nucleogenesis, if these are shared components or not. and yes, the submit button does definitely look a bit out of place 😓

**Comment by nucleogenesis** [comment]
@marcellamaki @pcenov 

Here is a screencast showing the icons are consistent on the AssessmentWrapper & QuizRenderer & navigating between resources.

For consistency I also applied the same typographic styles to the Submit & Check buttons but their general layout relative to other elements has remained the same.

[video-1774042178080.webm](https://github.com/user-attachments/assets/c2f548bc-d004-4182-9bd9-08942575a4c1)

**Comment by pcenov** [comment]
Hi @nucleogenesis noticed that now in a Quiz which is part of the 'Introductory Computing' Course the arrow in the 'Next' button is black:

next button arrow

Also when switching from one exercise to another I am always briefly seeing the Previous and Next buttons:

https://github.com/user-attachments/assets/a497db21-353a-4eda-89db-758e5c344e80

**Comment by nucleogenesis** [comment]
I'm sorry @pcenov - I've fixed the text color now.

The prev/next button flashing is something I can make a follow-up for so we can get this merged I think.

**Review by pcenov — APPROVED** [review]
Thanks @nucleogenesis, LGTM now! I have filed the follow-up issue here: https://github.com/learningequality/kolibri/issues/14455

**Review by marcellamaki — APPROVED** [review]
i'm not totally sure the scss file is really required here, but technically we have hit the rule of three and it is a pattern that still exists within our code, so... i think it's fine! ✅ i have done some manual QA as well but am mainly deferring to Peter's confirmation on that front :D
