### PR TITLE
Fixes UX issues with Sync and Register buttons on Facility Data page

### LINKED ISSUE #9090: Sync facility data - Sync and Register buttons UX issues
## Observed behavior
Currently there's a mini scrollbar displayed in the Sync facility section of the Data tab and when I click the Options button I see a Sync button. If I've previously registered the facility in KDP then there's a Register button displayed to the right of it.

## Expected behavior
Previously both Register and Sync buttons were displayed and the Register button would get disabled once the facility had been registered successfully. So the current expected behavior should be further clarified.

## Steps to reproduce the issue
1. Install the following build: https://buildkite.com/learningequality/kolibri-windows/builds/3136#308b9948-f6b3-466a-a661-162ed2f97d63
2. Go to Faclity>Data and scroll down to the 'Sync facility data' section

## Usage Details
Windows 10, Ubuntu - Chrome

### PR DESCRIPTION
**Pull request by LianaHarris360**
## Summary

This pr updates the buttons on the Facility > Data page in the Sync facility data sections. Previously when clicking the Options icon button the options were `Manage Sync Schedule` and `Sync`. And if the facility is registered in KDP, the Register button was still displayed.
- The `Sync` button is displayed instead of `Register`.
- The option to register a facility is displayed within the Options icon button menu and does not display if a facility is registered.
- The options icon button menu is displayed beneath the buttons instead of opening beside the buttons.

Before
sync-facility-options-button-fix-before

After
Unregistered Facility
sync-facility-options-button-fix-not-registered-after
Registered Facility
sync-facility-options-button-fix-registered-after

## References

Fixes #9090 

## Reviewer guidance

1. Go to Facility > Data and scroll down to the 'Sync facility data' section
2. Confirm that the menu options beneath the Register and options icon buttons.
3. Confirm that the menu option `Register` only shows if the facility is registered.

## Testing checklist

- [x] Contributor has fully tested the PR manually
- [x] If there are any front-end changes, before/after screenshots are included
- [ ] Critical user journeys are covered by Gherkin stories
- [ ] Critical and brittle code paths are covered by unit tests

## PR process

- [ ] PR has the correct target branch and milestone
- [ ] PR has 'needs review' or 'work-in-progress' label
- [ ] If PR is ready for review, a reviewer has been added. (Don't use 'Assignees')
- [ ] If this is an important user-facing change, PR or related issue has a 'changelog' label
- [ ] If this includes an internal dependency change, a link to the diff is provided

## Reviewer checklist

- Automated test coverage is satisfactory
- PR is fully functional
- PR has been tested for [accessibility regressions](http://kolibri-dev.readthedocs.io/en/develop/manual_testing.html#accessibility-a11y-testing)
- External dependency files were updated if necessary (`yarn` and `pip`)
- Documentation is updated
- Contributor is in AUTHORS.md

### CODE REVIEW

**Comment by rtibbles** [comment]
Noting this from the final comment on the issue:

> The Register action should always be hidden in an options dropdown menu that appears below the icon button, not beside it

The original suggestion in the description of the issue that the 'Register' option should be hidden in some circumstances is not correct, as seen from the comment by @marcellamaki that this change was intentional to always show the 'Register' button.

**Comment by LianaHarris360** [comment]
Ah, I was mistaken. We are do not want to block registration (or re-registration), so the Register action should still show in the menu whether a facility is registered or not. I will make that change and update the pr.

File: kolibri/plugins/facility/assets/src/views/DataPage/SyncInterface/index.vue [hunk 1]
```diff
@@ -126,6 +117,7 @@
     SyncFacilityModalGroup,
   } from 'kolibri.coreVue.componentSets.sync';
   import commonSyncElements from 'kolibri.coreVue.mixins.commonSyncElements';
+  import responsiveWindowMixin from 'kolibri.coreVue.mixins.responsiveWindowMixin';
```
Comment (akolson) [inline kolibri/plugins/facility/assets/src/views/DataPage/SyncInterface/index.vue:120]: This is non-blocking but just flagging that we now have the `useKResponsiveWindow` composable that provides for better code readability and control. Here is a [sample usage](https://github.com/learningequality/kolibri/blob/4ad3e289ddf4a00d91f5bccfdf7977147611d0f9/kolibri/plugins/learn/assets/src/views/LibraryPage/SidePanel.vue#L77) of the same

**Review by akolson — APPROVED** [review]
These changes look correct to me. Thanks @LianaHarris360

File: kolibri/plugins/facility/assets/src/views/DataPage/SyncInterface/index.vue (hunk 1 above)
Comment (LianaHarris360) [reply kolibri/plugins/facility/assets/src/views/DataPage/SyncInterface/index.vue:120]: Thanks for pointing this out and providing an example usage. I have noticed some areas where more control would be beneficial, particularly for the Kolibri app, so I will update this PR to use `useKResponsiveWindow` instead.
