### PR TITLE
Various (7) 0.12.6 fixes

### LINKED ISSUE #5563: In User Page, "Search for user" filter is slow when facility has a large number of users
### Observed behavior

With ~800 users in a facility, the 'Search for a user..." box becomes unusably slow:

> image

### Expected behavior

The filtering is done client-side, so it should be very snappy.

It can be throttled if necessary, but there's something deeper happening here than just updates happening too often.

### User-facing consequences

frozen browser, wasted battery

### Steps to reproduce

Try filtering users on either the beta or demo server

### Context

0.12.3

### LINKED ISSUE #5575: Rephrase 'no drives found' message to be less confusing
### Observed behavior
The current message is `No drives that can be written to are connected to the server` which is a bit confusing to me, If I speed-read to it.

@indirectlylit suggested to replace it with `Could not find a connected drive`

### Expected behavior
Rewording the message into a less confusing.

### Errors and logs

Simulator Screen Shot - iPad Pro (12 9-inch) - 2019-05-29 at 09 48 40

### Steps to reproduce
* Export a channel content with no drives available
* The message will display.

### Context

Tell us about your environment, including:
 * Kolibri version: v0.12.4-beta4
 * Operating system: iOS
 * Browser: Safari 11.0.3

### LINKED ISSUE #5606: anchor-tag buttons are not aligned on Safari
### Observed behavior
Error page buttons are not aligned on Safari 12.11

### Expected behavior
It should be aligned in all browsers.

### Errors and logs
Screen Shot 2019-06-03 at 2 50 16 PM

### Context

Tell us about your environment, including:
 * Kolibri version: v0.12.4b4
 * Operating system:  macOS
 * Browser: Safari 12.11

### LINKED ISSUE #5662: RTL layout and alignment issues related to exercise renderer
### Observed behavior

| LTR | RTL |
|--|--|
| image | image |

### Expected behavior

RTL alignment should be the correct inverse of LTR:

* the title should be right-aligned with the exercise icon on the right and the progress icon on the left. (the English title should be a locally LTR inline block within an outer RTL wrapper)
* ~the 'use a hint' link should be left-aligned~ migrated to https://github.com/learningequality/kolibri-exercise-perseus-plugin/issues/193

### User-facing consequences

subpar formatting for RTL users

### Steps to reproduce

https://kolibridemo.learningequality.org/en/learn/#/topics/c/7c9e658ea8de53ceaac9ea9f4fb63c6d

switch to arabic or another RTL language

### Context

0.12.4

### LINKED ISSUE #5663: exercise mastery indicator alignment issue
### Observed behavior

vertical alignment is off:

image

### Expected behavior

we should use the 'labeled icon' component to ensure correct/consistent alignment

### User-facing consequences

slightly jarring visually

### Steps to reproduce

view an exercise

### Context

0.12.4

### LINKED ISSUE #5671: device info page server link is not colored
### Observed behavior

image

### Expected behavior

should use standard colors

### User-facing consequences

slight inconsistency

### Context

0.12.4

### LINKED ISSUE #5706: The size of the channel thumbnail placeholder is different from real thumbnails
### Observed behavior

In the Device > Channels page, channels without thumbnails have a grid icon in a gray rectangle. We tried to get it looking square with CSS, but things might have changed, so it it is more rectangular now.

Screen Shot 2019-06-25 at 10 49 49 AM

### Expected behavior

Thumbnail-less channels have a default thumbnail placeholder that is the same size as other channels with a thumbnail.

One implementation would be to use an actual image instead of a div whose size and icon placement is managed with CSS.

### User-facing consequences

…

### Errors and logs

…

### Steps to reproduce

…

### Context

0.13

### LINKED ISSUE #5717: Exiting from a Content Page to Search results does not save channel or type filters
### Observed behavior

1. Search for a resource using a search term, then filter it down by a channel and/or content type.
1. In the search results, click a card for a resource (not a topic)
1. From the Content Page for that resource, click the "X" on the top-left corner to exit
1. You are taken to the search results page for the original search term, but the channel and/or content filters are not applied any more

### Expected behavior

1. When you exit a Content Page back to a search page, the channel and/or content type filters you had earlier are retained.

### User-facing consequences

…

### Errors and logs

…

### Steps to reproduce

…

### Context

Kolibri 0.12.6

### PR DESCRIPTION
**Pull request by jonboiser**
### Summary

1. Fixes the position of the progress (clock) icon in RTL mode. (Fixes #5662)

Screen Shot 2019-06-21 at 1 50 28 PM

1. Changes the implementation of the Device Info Page to use a `KExternalLink` instead of an anchor tag (fixes #5671)
1. Adjusts the vertical alignment of the star at the bottom the exercise viewer (Fixes #5663)

Screen Shot 2019-06-21 at 1 52 54 PM

1. Replaces the button-looking "Back to home" link on the AppError page with an actual button to fix layout issues on Safari: (fixes #5606)

Screen Shot 2019-06-21 at 1 54 02 PM

1. Simplifies the "no writable drives" message in the Content export wizard (Fixes #5575)

Screen Shot 2019-06-21 at 1 55 15 PM

1. In Device > Channel, Match dimensions of the Channel icon placeholder to match real thumbnails (Fixes #5706)

Screen Shot 2019-06-28 at 10 36 46 AM

1. In Search Page, make sure `kind` and `channel_id` query parameters are passed through to make sure the exit-to-results link preserves filters (fixes #5717)

### Reviewer guidance

1. Check to see if clock is positioned correctly in RTL mode wherever ContentPage is used
1. Check link for the 'localhost' URL in DeviceInfo page, try it in a different theme to see if it follows the theme
1. In the exercise viewer, master an exercise; verify the star icon is colored correctly and aligned with the label
1. Check the AppError page in Safari and other browsers to verify that the button is aligned correctly in all browsers and works the same.
1. Check to see that the right "No writable drives" message appears in the wizard
1. Check to see that channel placeholder icons match thumnails in different screen sizes
1. Check to see that exiting a resource found via search preserves the filters you had set earlier (try channel, kind, both, and neither filter).

### References

…

----

### Contributor Checklist

PR process:

- [x] PR has the correct target branch and milestone
- [x] PR has 'needs review' or 'work-in-progress' label
- [ ] If PR is ready for review, a reviewer has been added. (Don't use 'Assignees')
- [x] If this is an important user-facing change, PR or related issue has a 'changelog' label
- [ ] If this includes an internal dependency change, a link to the diff is provided

Testing:

- [ ] Contributor has fully tested the PR manually
- [ ] If there are any front-end changes, before/after screenshots are included
- [ ] Critical user journeys are covered by Gherkin stories
- [ ] Critical and brittle code paths are covered by unit tests

### Reviewer Checklist

- Automated test coverage is satisfactory
- PR is fully functional
- PR has been tested for [accessibility regressions](http://kolibri-dev.readthedocs.io/en/develop/manual_testing.html#accessibility-a11y-testing)
- External dependency files were updated if necessary (`yarn` and `pip`)
- Documentation is updated
- Contributor is in AUTHORS.md

### CODE REVIEW

File: kolibri/plugins/learn/assets/src/views/AssessmentWrapper/index.vue [hunk 1]
```diff
@@ -50,16 +50,16 @@ oriented data synchronization.
...
-          <div v-if="success" class="completed" :style="{ color: $themeTokens.annotation }">
+          <span v-if="success" class="completed" :style="{ color: $themeTokens.annotation }">
             {{ $tr('completed') }}
-          </div>
-          <div>
+          </span>
+          <span>
             {{ $tr('goal', {count: totalCorrectRequiredM}) }}
-          </div>
+          </span>
```
Comment (indirectlylit) [inline kolibri/plugins/learn/assets/src/views/AssessmentWrapper/index.vue:62]: possible to use the `KLabeledIcon` component here rather than the custom styles?

File: kolibri/plugins/learn/assets/src/views/PageHeader.vue [hunk 2]
```diff
@@ -58,9 +58,9 @@
   }
 
   .progress-icon {
-    position: relative;
-    top: -2px;
     display: inline-block;
+    float: right;
+    margin-top: -2px;
```
Comment (indirectlylit) [inline kolibri/plugins/learn/assets/src/views/PageHeader.vue:61]: similar here - maybe we should extend `KLabeledIcon` to support leading and trailing icons? (We've had a need for that in other places too)

File: kolibri/plugins/learn/assets/src/views/AssessmentWrapper/index.vue (hunk 1 above)
Comment (jonboiser) [reply kolibri/plugins/learn/assets/src/views/AssessmentWrapper/index.vue:62]: I tried that, but couldn't get the vertical alignment right.

File: kolibri/plugins/learn/assets/src/views/PageHeader.vue (hunk 2 above)
Comment (indirectlylit) [reply kolibri/plugins/learn/assets/src/views/PageHeader.vue:61]: Also note that from #5662

> the title should be right-aligned with the exercise icon on the right and the progress icon on the left. (the English title should be a locally LTR inline block within an outer RTL wrapper)

It's a bit subtle but I'm fairly sure that's the expected behavior here

Comment (jonboiser) [reply kolibri/plugins/learn/assets/src/views/PageHeader.vue:61]: So add a 'text-align: left' rule to the outer container? I feel like there's probably a lot of other headers in the app that don't have this rule and are always left-aligned in RTL mode.

Comment (jonboiser) [reply kolibri/plugins/learn/assets/src/views/PageHeader.vue:61]: Actually most headers do act properly. I wonder where PageHeader is being aligned left in spite of RTL

Comment (jonboiser) [reply kolibri/plugins/learn/assets/src/views/PageHeader.vue:61]: I removed the wrapping div from PageHeader, so the top-level tag is h1 and is properly transformed when in RTL mode.

File: kolibri/plugins/learn/assets/src/views/AssessmentWrapper/index.vue (hunk 1 above)
Comment (indirectlylit) [reply kolibri/plugins/learn/assets/src/views/AssessmentWrapper/index.vue:62]: ok

File: kolibri/plugins/learn/assets/src/views/PageHeader.vue (hunk 2 above)
Comment (indirectlylit) [reply kolibri/plugins/learn/assets/src/views/PageHeader.vue:61]: a couple references on mixed RTL/LTR behavior:

* https://www.w3.org/International/articles/inline-bidi-markup/
* https://www.w3.org/International/articles/inline-bidi-markup/uba-basics

**Review by indirectlylit — APPROVED** [review]
confirmed all changes.

still seeing a few issues with RTL headers, but will follow up with a separate PR
