### PR TITLE
Fix menu button icon overlap

### LINKED ISSUE #10533: Double "Data" Tab on the "Facility Page"
## Observed behavior
Noted by @bjester during the alpha12 bug bash 

Pixel 5 dimensions — 393px — if it doesn’t appear immediately, select different tabs and the double data will appear

## Errors and logs
Screenshot from 2023-04-06 13-22-20

## Expected behavior
Each menu item should only appear once

## Steps to reproduce
Pixel 5 dimensions — 393px — if it doesn’t appear immediately, select different tabs and the double data will appear

## Context
0.16.0-alpha12

### PR DESCRIPTION
**Pull request by marcellamaki**
## Summary
Fixes https://github.com/learningequality/kolibri/issues/10533 (sort of... the original problem is no longer replicable, but this one was. See issue for more) 

| | display |
|---|---|
| before: icons collide at certain screen widths  | icon-overlaps |
|  after: no overlap | no-icon-overlap |

## References

…

## Reviewer guidance
Adjust the screen size and observe that the menu icon no longer overlaps with the navigation tab

----

## Testing checklist

- [ ] Contributor has fully tested the PR manually
- [ ] If there are any front-end changes, before/after screenshots are included
- [ ] Critical user journeys are covered by Gherkin stories
- [ ] Critical and brittle code paths are covered by unit tests

## PR process

- [ ] PR has the correct target branch and milestone
- [ ] PR has 'needs review' or 'work-in-progress' label
- [ ] If PR is ready for review, a reviewer has been added. (Don't use 'Assignees')
- [ ] If this is an important user-facing change, PR or related issue has a 'changelog' label
- [ ] If this includes an internal dependency change, a link to the diff is provided

## Reviewer checklist

- Automated test coverage is satisfactory
- PR is fully functional
- PR has been tested for [accessibility regressions](http://kolibri-dev.readthedocs.io/en/develop/manual_testing.html#accessibility-a11y-testing)
- External dependency files were updated if necessary (`yarn` and `pip`)
- Documentation is updated
- Contributor is in AUTHORS.md

### CODE REVIEW

File: kolibri/core/assets/src/views/HorizontalNavBarWithOverflowMenu.vue [hunk 1]
```diff
@@ -120,7 +120,6 @@
   @import '~kolibri-design-system/lib/styles/definitions';
 
   .menu-icon {
-    position: absolute;
     right: 4px;
```
Comment (MisRob) [inline kolibri/core/assets/src/views/HorizontalNavBarWithOverflowMenu.vue]: With `position` removed, `right` will have no effect, so the whole `.menu-icon` can be removed from here as well as its references in the markup

**Review by MisRob — CHANGES_REQUESTED** [review]
Thank you, @marcellamaki, overall it's looking good to me, it seems that flex styles are enough to keep the button on the right and absolute positioning may be just obsolete code. Just some cleanup is needed before merging.

File: kolibri/core/assets/src/views/HorizontalNavBarWithOverflowMenu.vue (hunk 1 above)
Comment (marcellamaki) [reply kolibri/core/assets/src/views/HorizontalNavBarWithOverflowMenu.vue]: oh, what a good point 😄 thanks, Misha!

**Review by MisRob — APPROVED** [review]
