### PR TITLE
Disable form on submit for leaner enrollment and coach assignment

### LINKED ISSUE #7347: When enrolling learners to the class, there is no visual feedback while the request is being made
### Observed behavior

For the Learner-Enrollment and Coach-Assignment workflows, there might be some delay before the request suceeds and the user is redirected back to the Facility > Class page. Some visual feedback that something is happening might be helpful.

### Expected behavior

After clicking the "confirm" button, while waiting for a response from the server:

1. Disable the "Confirm" button
1. Disable the checkboxes next to each users name

If the request succeeds, then we return to the higher-level page.
If the request fails, we stay on this page and show an error, and re-enable all of the controls.

From: https://kolibri-beta.learningequality.org/en/facility/#/a3f606630690237bbe94fe2a1a850af4/classes/0ca0280c91ccb9a880d922914226557f/coach-assignment

image

### Steps to reproduce

Try to enroll some learners/coaches to a class, possibly while throttling connection speed to create a longer delay.

### Context

…

### PR DESCRIPTION
**Pull request by alexMet**
### Summary

Disable the form, all the checkboxes and the confirm button, after submitting, for learner enrollment and coach assignment. Show a generic error message ("Changes not saved") when the API throws an error.

simplescreenrecorder

### Reviewer guidance

Should the error handling do something else, besides only showing a message?

### References

#7347 

----

### Contributor Checklist

PR process:

- [x] PR has the correct target branch and milestone
- [x] PR has 'needs review' or 'work-in-progress' label
- [x] If PR is ready for review, a reviewer has been added. (Don't use 'Assignees')
- [x] If this is an important user-facing change, PR or related issue has a 'changelog' label
- [ ] If this includes an internal dependency change, a link to the diff is provided

Testing:

- [ ] Contributor has fully tested the PR manually
- [x] If there are any front-end changes, before/after screenshots are included
- [ ] Critical user journeys are covered by Gherkin stories
- [ ] Critical and brittle code paths are covered by unit tests

### Reviewer Checklist

- Automated test coverage is satisfactory
- PR is fully functional
- PR has been tested for [accessibility regressions](http://kolibri-dev.readthedocs.io/en/develop/manual_testing.html#accessibility-a11y-testing)
- External dependency files were updated if necessary (`yarn` and `pip`)
- Documentation is updated
- Contributor is in AUTHORS.md

### CODE REVIEW

**Comment by marcellamaki** [comment]
Hi Alex - this looks good. I see your question "Should the error handling do something else, besides only showing a message?" I noticed that you moved the error handling from action.js and added the snackbar. Did you move the catch only for the snackbar, or did you have an idea or suggestion of something else the error handling could do?

**Comment by alexMet** [comment]
Hi @marcellamaki. Yes, i moved the catch so i can re-enable the form and then show the error message. I didn't had an idea or suggestion, i just thought, if the API throws an error, it should be reported. But, since it is an offline platform, i don't know how you get error reports or if you have an error handling pattern, so i thought i should ask. :)

**Comment by jonboiser** [comment]
@alexMet, for errors like this that we can anticipate at design time, we tend to inform the user in a "graceful" way like how've you implemented it with the "Changes not saved" pop-up notification. Although this does make the failure a little mysterious and hard for the user to debug (so normally they'd have to report it to GH or the forum and we would need to do some detective work).

In other places where we did not anticipate a specific error and design a way to handle it in the UI, we use this Vuex action `handleApiError` that brings up a whole page Error page `AppError.vue`, with diagnostic and contact info.

**Review by marcellamaki — APPROVED** [review]
Thanks again @alexMet - this looks good!

File: kolibri/plugins/facility/assets/src/modules/classAssignMembers/actions.js [hunk 1]
```diff
@@ -11,8 +11,6 @@ export function enrollLearnersInClass(store, { classId, users }) {
       collection: classId,
       user: userId,
     })),
-  }).catch(err => {
-    store.dispatch('handleApiError', err, { root: true });
```
Comment (jonboiser) [inline kolibri/plugins/facility/assets/src/modules/classAssignMembers/actions.js:15]: Yeah, so now when this operation fails, you won't see the whole-page `AppError` component, but just the snackbar notification, which is what I recommended in the original issue.

**Comment by alexMet** [comment]
@jonboiser That is what i though, but i wanted to ask, just to be sure. Thank you very much for taking the time explaining it to me. :)
