### PR TITLE
language switcher is not wide enough

### LINKED ISSUE #2593: language switcher is not wide enough
### Observed behavior

The language selector now looks like this:

image

### Expected behavior

switcher should be wide enough to accommodate label

### User-facing consequences

ugliness on the front page

### Context

Kolibri 0.7

### PR DESCRIPTION
**Pull request by mrpau-richard**
### Summary

Adjust the width of the select languages button.

### Reviewer guidance
screen shot 2018-01-15 at 5 43 01 pm

### References
This fixes #2593 

### Contributor Checklist

- [x] PR has the correct target branch and milestone
- [x] PR has 'needs review' or 'work-in-progress' label
- [x] Contributor has fully tested the PR manually
- [x] Screenshots of any front-end changes are in the PR description
- [ ] If PR is ready for review, a reviewer has been added. (Don't use 'Assignees')

### Reviewer Checklist

- [x] Automated test coverage is satisfactory
- [ ] Reviewer has fully tested the PR manually
- [x] PR has been tested for [accessibility regressions](http://kolibri-dev.readthedocs.io/en/develop/manual_testing.html#accessibility-a11y-testing)
- [x] External dependencies files were updated (`yarn` and `pip`)
- [x] Documentation is updated
- [x] Link to diff of internal dependency change is included
- [x] CHANGELOG.rst is updated for high-level changes
- [x] Contributor is in AUTHORS.rst

### CODE REVIEW

**Comment by benjaoming** [comment]
@mrpau-richard this fix will not work in languages where the translation of "More languages" is wider than 145 px.

I think you should add a CSS rule, `white-space: nowrap` instead.

**Comment by mrpau-richard** [comment]
Thanks for reviewing this @benjaoming, Adding the `white-space: nowrap` will work on the tranlated more languages.

**Comment by christianmemije** [comment]
image

On my end there is now an overlap of the drop down arrow. Also, we want to make the change on the language switcher component, not on the k-select component. That max width in the k-select-inline class was set to keep a consistent width among filters throughout the app.

**Comment by christianmemije** [comment]
You could do something like this:
image

**Comment by benjaoming** [comment]
@christianmemije what about `width: auto` I think the fixed width is the actual issue here ?

**Comment by christianmemije** [comment]
Due to the scaling that the label has (see image below) an adjustment needs to be made to account for the expansion to avoid the overlap.

image

Something like the following could work, but the margin-right adjustment is still a guess.

```css
  .language-list-dropdown.k-select-inline
      width: auto

  >>>.ui-select__label-text.is-inline
      margin-right: 2em
```

**Comment by mrpau-richard** [comment]
@christianmemije Thanks for the help. Now the label did not overlap the down arrow.
screen shot 2018-01-18 at 12 30 08 pm
screen shot 2018-01-18 at 12 30 29 pm
screen shot 2018-01-18 at 12 30 44 pm

File: kolibri/core/assets/src/views/k-select/index.vue [hunk 1]
```diff
@@ -142,7 +142,12 @@
   .k-select-inline
     display: inline-block
     vertical-align: bottom
-    width: 100px
     margin-right: 16px
 
+  .language-list-dropdown.k-select-inline
```
Comment (christianmemije) [inline kolibri/core/assets/src/views/k-select/index.vue]: We do not want make any changes to the k-select. Instead we want to add this style to the language switcher component. Also you accidentally checked in some strings.

Comment (mrpau-richard) [reply kolibri/core/assets/src/views/k-select/index.vue]: I already moved it @christianmemije. And also removed some strings that's included in the PR.

File: kolibri/core/assets/src/views/k-select/index.vue [hunk 2]
```diff
@@ -142,7 +142,6 @@
   .k-select-inline
     display: inline-block
     vertical-align: bottom
-    width: 100px
```
Comment (christianmemije) [inline kolibri/core/assets/src/views/k-select/index.vue]: The last thing would be to keep this width since we already added `width: auto` in the language switcher.

Comment (mrpau-richard) [reply kolibri/core/assets/src/views/k-select/index.vue]: Done adding it @christianmemije.

**Comment by benjaoming** [comment]
@mrpau-richard could you squash this into a single commit? `git reset upstream/develop` (supposing your remote is called upstream) + `git commit` + `git push -f`

Tip: In future cases, when you are doing a small change to an existing commit, try `git commit --amend` + `git push -f`, that way you don't have to add an extra commit to your PR, but can replace the previous.

**Comment by mrpau-richard** [comment]
@benjaoming I already reset it into a single commit. Thanks to your comments.

File: kolibri/core/assets/src/views/language-switcher/list.vue [hunk 3]
```diff
@@ -140,4 +140,11 @@
   .language-list-dropdown
     margin-bottom: 8px
 
+  .language-list-dropdown.k-select-inline
+      width: auto
```
Comment (christianmemije) [inline kolibri/core/assets/src/views/language-switcher/list.vue:144]: Since we set width to auto here, you can keep `width: 100px` in the k-select component.

**Comment by indirectlylit** [comment]
> @mrpau-richard could you squash this into a single commit? `git reset upstream/develop` (supposing your remote is called upstream) + `git commit` + `git push -f`
> 
> Tip: In future cases, when you are doing a small change to an existing commit, try `git commit --amend` + `git push -f`, that way you don't have to add an extra commit to your PR, but can replace the previous.

This is a conversation we should migrate to a dev meeting or perhaps a google doc. However In summary:

For the Kolibri code base, I actually prefer that we _don’t_ squash and amend commits when changes are made based on code reviews, for two reasons:

* After a code review it's useful to see the specific changes which were made in response to feedback as individual commits. Squashing or amending loses that granular history.
* By default, PR branches [allow other project contributors to collaborate on them](https://help.github.com/articles/allowing-changes-to-a-pull-request-branch-created-from-a-fork/), meaning they are de facto 'shared' branches. For example in this case, @christianmemije may have decided to push changes directly to @mrpau-dev's branch rather than blocking the merge to speed up the process. Rewriting git history for shared branches makes things difficult for collaborators.

File: kolibri/core/assets/src/views/language-switcher/list.vue (hunk 3 above)
Comment (mrpau-richard) [reply kolibri/core/assets/src/views/language-switcher/list.vue:144]: Done adding it @christianmemije
