### PR TITLE
Layout fixes

### LINKED ISSUE #6022: irregular layout of channel filter UI
### Observed behavior

* inconsistent order on different breakpoints
* irregular text baselines on larger monitors

| Small | Large |
|--|--|
| image | image |

### Expected behavior

* consistent order
* aligned text baselines

image

### Context

0.13.0 alpha

ref: https://github.com/learningequality/kolibri/pull/6018/

### LINKED ISSUE #6072: use standard CoreTable and enter/leave transitions for task manager
### Observed behavior

current table view is slightly non-standard:

image

### Expected behavior

* Standard `CoreTable` behavior with row-dividers, right button alignment, and secondary button style
* `transition-group` enter/leave transitions

### User-facing consequences

inconsistent UI

### Context

0.13.0 alpha

### LINKED ISSUE #6082: channel order drag-drop styling issues
### Observed behavior

styling during drag/drop interaction:

order

### Expected behavior

1. channel being dragged should always appear in front of other channels
2. hover styling (grey background) should be disabled while dragging

### User-facing consequences

styling idiosyncrasies

### Context

0.13.0 alpha 0

### LINKED ISSUE #6083: Center-alignment of content in bottom bar
### Observed behavior

According to our conventions, buttons should always be [left- or right-aligned](http://kolibribeta.learningequality.org/design/components/buttons#placement).

image

### Expected behavior

* right-aligned button, similar to standard modals
* text could be either right or left-aligned

### User-facing consequences

slightly inconsistent layout

### Context

0.13.0 alpha 0

### LINKED ISSUE #6084: snackbar occludes the bottom bar
### Observed behavior

Snackbar occludes the bottom bar

image

### Expected behavior

Snackbar should only be shown over content that is scrollable. When a bottom bar is visible, the snackbar should be vertically raised above the bottom bar

### User-facing consequences

some content is not visible

### Steps to reproduce

trigger an import

### Context

0.13.0 alpha 0

### PR DESCRIPTION
**Pull request by jonboiser**
### Summary

Some layout fixes

1. Change grid layout of the channel filters Fixes #6022 

Screen Shot 2019-11-18 at 3 15 45 PM
Screen Shot 2019-11-18 at 3 15 52 PM

1. Add a opaque background to draggle channels in Edit Channel Order page. Fixes #6082 

1. Change grid layout of selection bottom bar. Mostly works for different languages/button widths, with a variable sized gap between message and buttons. Fixes #6083

Screen Shot 2019-11-18 at 3 18 16 PM
Screen Shot 2019-11-18 at 3 18 11 PM
Screen Shot 2019-11-18 at 3 18 00 PM

1. Fix dropdown positionings for dropdowns on small screens to prevent overflows.
1. Add dividers between tasks and add a fade transition when they (dis)appear. Fixes #6072
1. Make the snackbar's bottom position customizable, then have it appear above selection bottom bar for import/export/manage workflows fixes #6084 

Screen Shot 2019-11-18 at 5 00 14 PM

### Reviewer guidance

…

### References

…

----

### Contributor Checklist

PR process:

- [x] PR has the correct target branch and milestone
- [x] PR has 'needs review' or 'work-in-progress' label
- [x ] If PR is ready for review, a reviewer has been added. (Don't use 'Assignees')
- [ ] If this is an important user-facing change, PR or related issue has a 'changelog' label
- [ ] If this includes an internal dependency change, a link to the diff is provided

Testing:

- [ ] Contributor has fully tested the PR manually
- [ ] If there are any front-end changes, before/after screenshots are included
- [ ] Critical user journeys are covered by Gherkin stories
- [ ] Critical and brittle code paths are covered by unit tests

### Reviewer Checklist

- Automated test coverage is satisfactory
- PR is fully functional
- PR has been tested for [accessibility regressions](http://kolibri-dev.readthedocs.io/en/develop/manual_testing.html#accessibility-a11y-testing)
- External dependency files were updated if necessary (`yarn` and `pip`)
- Documentation is updated
- Contributor is in AUTHORS.md

### CODE REVIEW

File: kolibri/plugins/device/assets/src/views/taskNotificationMixin.js [hunk 1]
```diff
@@ -47,6 +47,8 @@ export default {
         autoDismiss: true,
         duration: 10000,
         actionText: TaskSnackbarStrings.$tr('clearTaskAction'),
+        // HACK make the snackbar appear really high to clear the bottom bar
+        bottomPosition: 80,
```
Comment (indirectlylit) [inline kolibri/plugins/device/assets/src/views/taskNotificationMixin.js:51]: this is an improvement.

However note that this hack doesn't account for switching between a page that has a bottom bar and one that does not

File: kolibri/plugins/device/assets/src/views/ManageContentPage/FilteredChannelListContainer.vue [hunk 2]
```diff
@@ -1,29 +1,34 @@
...
-          v-model="titleFilter"
-          class="filter-title"
-          :placeholder="$tr('titleFilterPlaceholder')"
-          :throttleInput="500"
-        />
-      </div>
-    </div>
+  <div :class="{'fclc-sm': !windowIsLarge}">
+    <KGrid class="top-panel">
+      <KGridItem :layout12="{span: 4}">
```
Comment (indirectlylit) [inline kolibri/plugins/device/assets/src/views/ManageContentPage/FilteredChannelListContainer.vue:5]: should be span 12, not 4:

image

Also, the 'N channels available' text should be below/after the filter, because the number is affected by filter operations:

image

(If it were not affected, it would be above/before)

**Review by indirectlylit — APPROVED** [review]
looks good!

a couple follow-up issues, will submit a PR.

should be secondary flat: 

image

File: kolibri/plugins/device/assets/src/views/ManageContentPage/FilteredChannelListContainer.vue [hunk 3]
```diff
@@ -190,53 +195,31 @@
...
-    flex-wrap: wrap;
-    align-items: flex-start;
     margin-bottom: 24px;
-  }
 
-  .count-msg {
-    flex-grow: 1;
-    max-width: 200px;
-    margin: 0;
+    .fclc-sm & {
```
Comment (indirectlylit) [inline kolibri/plugins/device/assets/src/views/ManageContentPage/FilteredChannelListContainer.vue:200]: I am not able to guess what `fclc` means. Would prefer that we use more verbose class names for code maintainability

Comment (indirectlylit) [reply kolibri/plugins/device/assets/src/views/ManageContentPage/FilteredChannelListContainer.vue:200]: Ah, `FilteredChannelListContainer` - got it.

Agreed that root component nodes can be difficult because the scope namespace is shared with the parent.
