### PR TITLE
Include active facility id in FacilityTopNav routes

### LINKED ISSUE #10294: Facility plugin - The navigation defaults to the main facility
## Observed behavior
As noted by @radinamatic if I have imported an additional facility and I go to the Facility plugin I am being prompted to select a facility. When I select the imported facility I am correctly redirected to the Classes tab, however if I navigate to any of the other tabs then I am seeing the data for the main facility. The facility id value is also no longer displayed in the URL.

Note that the navigation in the Coach plugin is functioning correctly.

## Expected behavior
The data for each selected facility should be displayed correctly when navigating within the Facility plugin.

## Steps to reproduce the issue
1. Install the the latest `develop` build.
2.  Setup a full facility and import an additional facility.
3. Navigate to the Facility plugin and select the imported facility.
4. Attempt to view any of the other tabs such as Users, Settings or Data

## Video

https://user-images.githubusercontent.com/79847249/226886910-e1674124-3015-4acd-9ed2-150b53fcb4be.mp4

## Usage Details
Windows 10, Ubuntu 22  - Chrome, Firefox

### PR DESCRIPTION
**Pull request by nucleogenesis**
## Summary

Includes the currently selected, aka _active_, facility's ID in the params when generating the link for the Facility's top nav items.

## References

Fixes #10294 

## Reviewer guidance

See if the issues reported in #10294 are resolved.

### CODE REVIEW

File: kolibri/plugins/facility/assets/src/views/FacilityTopNav.vue [hunk 1]
```diff
@@ -21,28 +21,30 @@
     mixins: [commonCoreStrings],
     computed: {
       links() {
+        const facility_id = this.$store.getters.activeFacilityId; // Ensure we stay in the current facility
```
Comment (rtibbles) [inline kolibri/plugins/facility/assets/src/views/FacilityTopNav.vue]: One other possibility here would be to read the route parameter, which would mean navigation within the default facility would not inject the route parameter, but other facilities would.

(under the hood this is what active Facility is doing, but then doing a fallback for the default facility)

Comment (nucleogenesis) [reply kolibri/plugins/facility/assets/src/views/FacilityTopNav.vue]: Great call - will update tomorrow thanks!

**Review by thanksameeelian — APPROVED** [review]
this looks good to me! 🎉

**Comment by radinamatic** [comment]
@nucleogenesis Is this ready for manual QA? Thank you!

**Comment by nucleogenesis** [comment]
@radinamatic yep

**Comment by pcenov** [comment]
@radinamatic No issues observed while manually testing this one - now the facility id is included in the params when generating the link for the Facility's top nav items so that the issue described in https://github.com/learningequality/kolibri/issues/10294 is fixed.

**Review by radinamatic — APPROVED** [review]
Manual QA passed, good to go! 💯 :shipit:

**Review by rtibbles — APPROVED** [review]
