### PR TITLE
Do not show password if not needed

### LINKED ISSUE #8390: password field is always shown during user import
## Observed behavior

The password field is always shown:

image

## Expected behavior

User should only be prompted to enter a password when necessary

## User-facing consequences

Unclear how to import learners from a device that has password-free login enabled. Leaving it blank seems to work, but this is a bit confusing.

## Context

latest develop

### PR DESCRIPTION
**Pull request by jredrejo**
## Summary
When syncing from a facility that has password-free login enabled, the setup wizard does not show the password input in order to sync an user:

image

## References
Closes #8390 

## Reviewer guidance
Start provisioning a new kolibri installation syncing users from another facility. Check that if the facility has the password-free login option enabled, only username is required to sync (and syncing keeps working).

## Testing checklist

- [x] Contributor has fully tested the PR manually
- [x] If there are any front-end changes, before/after screenshots are included
- [ ] Critical user journeys are covered by Gherkin stories
- [ ] Critical and brittle code paths are covered by unit tests

## PR process

- [x] PR has the correct target branch and milestone
- [x] PR has 'needs review' or 'work-in-progress' label
- [ ] If PR is ready for review, a reviewer has been added. (Don't use 'Assignees')
- [ ] If this is an important user-facing change, PR or related issue has a 'changelog' label
- [ ] If this includes an internal dependency change, a link to the diff is provided

## Reviewer checklist

- Automated test coverage is satisfactory
- PR is fully functional
- PR has been tested for [accessibility regressions](http://kolibri-dev.readthedocs.io/en/develop/manual_testing.html#accessibility-a11y-testing)
- External dependency files were updated if necessary (`yarn` and `pip`)
- Documentation is updated
- Contributor is in AUTHORS.md

### CODE REVIEW

**Comment by radinamatic** [comment]
@pcenov Could you test this, please? Thank you!

**Comment by pcenov** [comment]
Hi @jredrejo, I had a chance to test this PR today and the main scenario works correctly as described.
At the same time I noticed the following issues:

1 | 2
---- | ---
When I'm importing several users there doesn't seem to be a check whether the user has already been added so that the same user is listed several times (see below) | If I accidentally input an incorrect or not existing username I briefly see an "Incorrect username or password" validation message and then I'm automatically signed in with the last valid user. In this case the validation message is incorrect because I'm not inputting a password and also I should be given a chance to correct the mistake and add the correct user (see below)
Screenshot_20210930-190027_Kolibri | Screenshot_20210930-190048_Kolibri

**Comment by jredrejo** [comment]
Hello @pcenov  are you by chance using a virtual machine to test these things? I am not able to reproduce the problems you're having, so if you're using a VM for the server maybe you could pass it to me

**Comment by pcenov** [comment]
Hi @jredrejo I'm always testing with both real and virtual devices. In this case I'm experiencing the reported issues both on real and virtual devices. I'm on a sick leave today, will reach out to you next week to see why you are not able to replicate them.

**Comment by jredrejo** [comment]
hello @pcenov  I finally could reproduce the two issues you had. It happened they existed since a long time and were not due to this PR and they were quite tricky to fix. Please, check it when you can. They should be fixed.

File: kolibri/plugins/setup_wizard/assets/src/api.js [hunk 1]
```diff
@@ -2,6 +2,7 @@ import { Resource } from 'kolibri.lib.apiResource';
 import pickBy from 'lodash/pickBy';
 import urls from 'kolibri.urls';
 import redirectBrowser from 'kolibri.utils.redirectBrowser';
+import clientFactory from '../../../../core/assets/src/core-app/baseClient';
```
Comment (indirectlylit) [inline kolibri/plugins/setup_wizard/assets/src/api.js]: if we cannot use `import client from 'kolibri.client'` then `clientFactory` should probably be added to `apiSpec.js` to avoid relative imports across the plugin/core boundary

**Review by indirectlylit — COMMENTED** [review]
Always great to fix a long-standing issue!

@jredrejo left a note on the new relative import

> main scenario works correctly as described. At the same time I noticed the following issues

@pcenov in the future for this kind of situation it can be useful to file a follow-up issue. this can help the product team assign a priority to the work independently of the current PR

**Comment by pcenov** [comment]
Perfect @jredrejo I've tested this again on Windows, Ubuntu and Android and everything works correctly as described. :)

File: kolibri/plugins/setup_wizard/assets/src/api.js (hunk 1 above)
Comment (jredrejo) [reply kolibri/plugins/setup_wizard/assets/src/api.js]: @indirectlylit  Thank you! I didn't want to alter the kolibri JS api but it's clear this can't cause any damage, so done!

Comment (indirectlylit) [reply kolibri/plugins/setup_wizard/assets/src/api.js]: Yeah currently `apiSpec` contains both "external API" that external plugins reference as well as "internal API" that is only used in the kolibri repo and is free to change at any time. @rtibbles and I have discussed making this distinction more explicit and also starting to version the external parts (https://github.com/learningequality/kolibri/issues/527)

**Review by indirectlylit — APPROVED** [review]
thank you!
