### PR TITLE
Remote browsing filters

### LINKED ISSUE #10975: Kolibri Library - It's possible to filter by more than one activity type
## Observed behavior
If I am exploring the Kolibri Library and I try filtering by Activity I am able to select several activities.

## Expected behavior
It should be possible to filter only by one Activity at a time.

## Steps to reproduce the issue
1. Install the build asset from the following [PR](https://github.com/learningequality/kolibri/pull/10974)
2. Navigate to Library > Other libraries > Explore
3. Attempt to apply several filters by Activity

## Video

https://github.com/learningequality/kolibri/assets/79847249/a7c56e46-5ffe-4179-90c8-c4b4c308d8a3

## Usage Details
Kolibri 0.16alfa19
Windows 10, Ubuntu - Chrome

### LINKED ISSUE #10976: Remote browsing - Filtering by categories is not working while I am viewing a specific channel
## Observed behavior
Filtering by categories is not working while I am viewing a specific channel. The only option available is to filter by 'Uncategorized. The filter by Categories is also not working correctly for the channels already downloaded to my library.

## Expected behavior
Filtering by categories should be working correctly.

## Steps to reproduce the issue
1. Install the build asset from the following [PR](https://github.com/learningequality/kolibri/pull/10974)
2. Navigate to Library > Other libraries > Explore > Channel or Library > My library > Channel
3. Attempt to filter by Category

## Video

https://github.com/learningequality/kolibri/assets/79847249/b53eca1a-6004-43b1-a0f2-c9f79a3698fa

## Usage Details
Kolibri 0.16alfa19
Windows 10, Ubuntu - Chrome

### PR DESCRIPTION
**Pull request by rtibbles**
## Summary
* Updates logic for displaying whether categories are enabled or disabled within a channel, after incomplete refactor
* Makes SearchFiltersPanel responsible solely for displaying search filters
* Makes SearchFiltersPanel handle its own modal display when needed
* Removes duplicated `section` tag
* Updates SidePanelModal to remove Search filters panel specific aria label, and insert via a prop instead
* Create TopicsPanelModal for displaying topics in the TopicsPage
* Moves all 'currentCategory' logic inside SearchFiltersPanel to encapsulate and reuse logic
* Uses [vue2-teleport](https://github.com/Mechazawa/vue2-teleport) to allow KModal use from within a `fixed` position div, which seems to have been the reason it was previously embedded outside of the SidePanelModal component.
* Update how we display selected categories in the category selection modal to match the original spec
* Update how category selection works, so that all actual categories (but not 'Uncategorized') are additive in their selection, meaning:
  * Selecting a category when another category is already selected will now filter by both categories
  * Selecting a category when _that_ category is already selected will now remove filtering by that category
  * Selecting a category when any of its descendant categories are selected will deselect the descendant categories, and only select the ancestor category that the user clicked
* Fix bug in metadata label filtering, whereby it was doing an OR when multiple categories, learning activities, etc. were selected rather than an AND
* Adds a regression test for this bug

## References
Fixes [#10975](https://github.com/learningequality/kolibri/issues/10975)
Fixes #10976 
Implements this design:
Screenshot 2023-07-14 at 2 01 35 PM
Screenshot 2023-07-14 at 2 01 15 PM

## Reviewer guidance
Removing the aria-label now means that the SidePanelModal doesn't have an aria-label in other places where it is used, but as the previous label was incorrect, this doesn't seem like a regression. We should open a follow up issue for this.

I am very sure that none of the code moves I did moved any strings around, but a double check would never hurt.

I may not have implemented the above design precisely to spec, as the highlight is the same width as the text, not the overall block - so that may need an update? Could also be filed as a follow up issue.

For manual testing, this needs to be tested for searching and filtering on the Library page (both local and remote for peers) and within channels (both for local and remote peers).

I am very sure that the bug that is the root cause of the OR behaviour noted in #10975 is present in Studio, even if it is not manifesting (probably because of differences in Library content).

----

## Testing checklist

- [x] Contributor has fully tested the PR manually
- [ ] If there are any front-end changes, before/after screenshots are included
- [ ] Critical user journeys are covered by Gherkin stories
- [ ] Critical and brittle code paths are covered by unit tests

## PR process

- [x] PR has the correct target branch and milestone
- [x] PR has 'needs review' or 'work-in-progress' label
- [x] If PR is ready for review, a reviewer has been added. (Don't use 'Assignees')
- [ ] If this is an important user-facing change, PR or related issue has a 'changelog' label
- [ ] If this includes an internal dependency change, a link to the diff is provided

## Reviewer checklist

- Automated test coverage is satisfactory
- PR is fully functional
- PR has been tested for [accessibility regressions](http://kolibri-dev.readthedocs.io/en/develop/manual_testing.html#accessibility-a11y-testing)
- External dependency files were updated if necessary (`yarn` and `pip`)
- Documentation is updated
- Contributor is in AUTHORS.md

### CODE REVIEW

**Comment by pcenov** [comment]
Hi @rtibbles,
1. The issue described in https://github.com/learningequality/kolibri/issues/10975 is still present - does that mean that it has to be reported and fixed on Studio's side? Perhaps it's worth discussing and specifying the expected behavior for the Categories and Activities filters as it's different from the rest (we are adding up results and not excluding). That becomes especially obvious when using these filters together with a Keyword for example in which case only results containing the keyword are being returned, the categories in the modal are displayed as disabled and cannot be deselected:

https://github.com/learningequality/kolibri/assets/79847249/2e46c864-b784-48a5-b1d9-488b38d030e7

2 Observed a minor issue where the selected descendant categories are not being highlighted:

https://github.com/learningequality/kolibri/assets/79847249/8f25a6af-2d77-4162-8733-d84b8f422d07

3. I've reported separately an issue about the Language filter: https://github.com/learningequality/kolibri/issues/10989

**Comment by rtibbles** [comment]
For 1) as I mentioned above:

> I am very sure that the bug that is the root cause of the OR behaviour noted in https://github.com/learningequality/kolibri/issues/10975 is present in Studio, even if it is not manifesting (probably because of differences in Library content).

So, this should be functioning correctly now for everything except Studio, and we can port the fix for that to Studio as well.

2 is what I was meant to be implementing here, so I'll fix that within the scope of this PR.

I've self assigned 3, but we can deal with it separately.

**Comment by rtibbles** [comment]
> Perhaps it's worth discussing and specifying the expected behavior for the Categories and Activities filters as it's different from the rest (we are adding up results and not excluding).

This was never intended behaviour, it just hadn't manifested previously because a) we didn't have multiple learning activities for individual resources, and b) category selection before this PR cleared previous category selections.

I think maintaining consistent 'exclusion' filtering - so a resource needs _every_ applied filter to appear seems like the right way to go for now. We can potentially add interactions to allow more advanced OR filtering in the future. This is how it should be functioning for local filtering and filtering on a peer running this code now, just remains for the port to Studio to have this happen universally.

**Comment by rtibbles** [comment]
OK, the bug should be fixed, and in collaboration with @jtamiace I have attempted to update the category modal interface closer to the original spec - removing sub category indentation and using bolding instead:

image

File: kolibri/plugins/learn/assets/src/views/LearnIndex.vue [hunk 1]
```diff
@@ -14,8 +14,8 @@
 
   import { mapGetters, mapState } from 'vuex';
   import NotificationsRoot from 'kolibri.coreVue.components.NotificationsRoot';
-  import { PageNames } from '../constants';
   import plugin_data from 'plugin_data';
+  import { PageNames } from '../constants';
```
Comment (marcellamaki) [inline kolibri/plugins/learn/assets/src/views/LearnIndex.vue:18]: is this just from linting?

Comment (rtibbles) [reply kolibri/plugins/learn/assets/src/views/LearnIndex.vue:18]: Yes, for reasons I couldn't discern, linting changed its mind while I was making this PR and decided to move things around.

**Review by pcenov — APPROVED** [review]
Implemented as specified and looks great! No new issues observed.

**Review by radinamatic — APPROVED** [review]
Filtering now looks much better, good to go! 🎉 💯 :shipit:

File: kolibri/plugins/learn/assets/src/views/SearchFiltersPanel/index.vue [hunk 2]
```diff
@@ -1,38 +1,25 @@
 <template>
 
-  <section
+  <component
+    :is="windowIsLarge ? 'section' : 'SidePanelModal'"
```
Comment (marcellamaki) [inline kolibri/plugins/learn/assets/src/views/SearchFiltersPanel/index.vue:4]: I like this. It is probably something we (or at least I )can make use of more often

File: kolibri/plugins/learn/assets/src/views/SearchFiltersPanel/CategorySearchModal/CategorySearchOptions.vue [hunk 3]
```diff
@@ -103,14 +103,40 @@
...
+    methods: {
+      appearanceOverrides(category, bolded) {
+        const activeOverrides = {
+          backgroundColor: this.$themeBrand.primary.v_50,
+          border: '2px',
+          borderColor: this.$themeTokens.primary,
+          borderStyle: 'solid',
+          borderRadius: '4px',
+        };
+        const appearanceOverrides = {
```
Comment (marcellamaki) [inline kolibri/plugins/learn/assets/src/views/SearchFiltersPanel/CategorySearchModal/CategorySearchOptions.vue:116]: This is a more general thought, but there are quite a few places in the hybrid learning work where we are doing a pretty "unique" variation on our KButton that requires a lot of overrides. Might be worth considering if we want a core button style in the KButton upgrades to cover this when we do the updates for that component, or if we want to just continue this way as needed and essenitally swap the colors @jtamiace @tomiwaoLE

File: kolibri/plugins/learn/assets/src/views/TopicsPage/ToggleHeaderTabs.vue [hunk 4]
```diff
@@ -90,7 +90,6 @@
         // navigates the main page to the search view
         if (this.topic) {
           const query = { ...this.$route.query };
-          delete query.dropdown;
```
Comment (marcellamaki) [inline kolibri/plugins/learn/assets/src/views/TopicsPage/ToggleHeaderTabs.vue:93]: I have no recollection as to why I even added this in the first place!

**Review by marcellamaki — APPROVED** [review]
I think this is good to merge! I added one comment re: button styling but it's for the designers. Thanks for all the cleanup here.

**Review by marcellamaki — COMMENTED** [review]
I think this is good to merge! I added one comment re: button styling but it's for the designers. Thanks for all the cleanup here.

**Review by marcellamaki — APPROVED** [review]

File: kolibri/plugins/learn/assets/src/views/SearchFiltersPanel/index.vue (hunk 2 above)
Comment (rtibbles) [reply kolibri/plugins/learn/assets/src/views/SearchFiltersPanel/index.vue:4]: Yeah, the alternative pattern that was being used was for the main body of the component to be in a child component and then use a v-if on the different potential parent components.

This method is a little more concise, but does mean that for the `section` tag it has a bunch of random meaningless attributes that should only be passed to the SidePanelModal component.

File: kolibri/plugins/learn/assets/src/views/SearchFiltersPanel/CategorySearchModal/CategorySearchOptions.vue (hunk 3 above)
Comment (rtibbles) [reply kolibri/plugins/learn/assets/src/views/SearchFiltersPanel/CategorySearchModal/CategorySearchOptions.vue:116]: I think it might be worth revisiting the API of KButton at a minimum to see if there's a more natural way to apply this kind of styling.

File: kolibri/plugins/learn/assets/src/views/TopicsPage/ToggleHeaderTabs.vue (hunk 4 above)
Comment (rtibbles) [reply kolibri/plugins/learn/assets/src/views/TopicsPage/ToggleHeaderTabs.vue:93]: It was because we used to have a query parameter that determined whether the side panel state was toggled open, I think? Then we refactored it to rely on component JS state, but this was never cleaned up.
