### PR TITLE
Remove redundant mastery label masking exercise card thumbnail

### LINKED ISSUE #11804: Superfluous mastery label covers the thumbnail on the exercise card in the lesson on Android LoDs
## Observed behavior

Since the mastery level is already included below the activity label, maybe we can remove the one over the thumbnail...?
1 | 2
-- | --
 | mastery-overlay

## Errors and logs
...

## Expected behavior
...

## User-facing consequences
...

## Steps to reproduce

Open a lesson that has an exercise resource on Android LoD

## Context

 * Kolibri version:  Windows 7 (0.16b13)

### PR DESCRIPTION
**Pull request by LianaHarris360**
## Summary

This pr modifies the conditional `displayDurationChip` for `HybridLearningContentCard/CardThumbnail`. This tag previously 
covered the thumbnail on exercise cards listed on `LessonPlaylistPage`.

| BEFORE  | AFTER  |
|---|---|
 |  LessonPlaylistPageBefore |  LessonPlaylistPageAfter  |
 | LessonPlaylistPageMobileBefore | LessonPlaylistPageMobileAfter |

The duration chip is still displayed on `TopicsPage` and is hidden on smaller screen sizes.
| TOPICS PAGE NORMAL VIEW  | TOPICS PAGE MOBILE VIEW |
|---|---|
 | TopicsPage |  TopicsPageMobile |

## References

Closes #11804 

## Reviewer guidance

Open a lesson that has an exercise resource on a Learn Only Device

----

## Testing checklist

- [x] Contributor has fully tested the PR manually
- [x] If there are any front-end changes, before/after screenshots are included

## PR process

- [ ] PR has the correct target branch and milestone
- [ ] PR has 'needs review' or 'work-in-progress' label
- [ ] If PR is ready for review, a reviewer has been added. (Don't use 'Assignees')
- [ ] If this is an important user-facing change, PR or related issue has a 'changelog' label
- [ ] If this includes an internal dependency change, a link to the diff is provided

## Reviewer checklist

- Automated test coverage is satisfactory
- PR is fully functional
- PR has been tested for [accessibility regressions](http://kolibri-dev.readthedocs.io/en/develop/manual_testing.html#accessibility-a11y-testing)
- External dependency files were updated if necessary (`yarn` and `pip`)
- Documentation is updated
- Contributor is in AUTHORS.md

### CODE REVIEW

File: kolibri/plugins/learn/assets/src/views/HybridLearningContentCard/CardThumbnail.vue [hunk 1]
```diff
@@ -47,18 +47,8 @@
...
-        }
-        return true;
-      },
-      checkIfExercise() {
-        if (this.contentNode.kind === 'exercise') {
-          return true;
-        }
-        return false;
+        // Hide if hideDuration or isMobile is true, display if contentNode kind is exercise
+        return this.hideDuration || this.isMobile ? false : this.contentNode.kind === 'exercise';
```
Comment (akolson) [inline kolibri/plugins/learn/assets/src/views/HybridLearningContentCard/CardThumbnail.vue:51]: This is more cleaner and understandable!

Comment (akolson) [reply kolibri/plugins/learn/assets/src/views/HybridLearningContentCard/CardThumbnail.vue:51]: Maybe even the below for more conciseness?(Not a blocker though, l'll leave you to choose 🙂  )
 `return !(this.hideDuration || this.isMobile) && this.contentNode.kind === 'exercise';`

**Review by akolson — APPROVED** [review]
Thanks @LianaHarris360. This change looks good to me and checks out.
