### PR TITLE
Update RecipientBehavior behavior; fix bugs when copying Quizzes with individual learner-assignments

### LINKED ISSUE #7580: "Individual learners" item is automatically unchecked on the "edit details" page after unchecking all groups
Environment; Raspberry Pi 3B+
OS: Kolibri 0.14.3 tested on Mac mini (Mid 2011)
Browser: Google Chrome latest

Severity; minor

Preconditions; user is logged in as a coach, Class home page is opened; two groups are created and at least one lesson is created

Steps to reproduce;

1. Proceed to the Plan>Lessons page
2. Click on any lesson
3. Click on the edit details button from the "options" drop-down
4. Select all groups and individual learners
5. Uncheck all groups
6. Pay attention to the "individual learners" item  which was automatically unchecked

Actual result: "Individual learners" item is automatically unchecked on the "edit details" page after unchecking all groups
Expected result: "Individual learners" item shouldn't be automatically unchecked on the "edit details" page after unchecking all groups
Attachment: http://e.pc.cd/vHbotalK

### LINKED ISSUE #7608: When a coach user copies a Quiz from one class to other and assigns it to individuals, it breaks the second Class's Plan > Quizzes page
### Observed behavior
When a coach user copies a Quiz from one class to other, it gets copied but when we try to open the copied quiz from the other class, the page breaks and app stops [responding.
](https://github.com/learningequality/kolibri/blob/release-v0.14.x/integration_testing/features/coach/coach-copy-quiz.feature)
…

### Expected behavior
Application should not stop and user should be able to review the copied Quiz.

…

### User-facing consequences
User might lose lot of data/work as app stops working
…

### Errors and logs

Relevant logs from:
[kolibri-app.txt](https://github.com/learningequality/kolibri/files/5429351/kolibri-app.txt)

```

```

…

### Steps to reproduce
1. Login as Coach.
2. Copy Quiz form one class to another.
3. Try to open copied Quiz from the other class.
4. Notice that user is not able to access that page and application stops responding.

PFA the video for reference.
[CopyQuiz_issue.zip](https://github.com/learningequality/kolibri/files/5429370/CopyQuiz_issue.zip)

…

### Context
Tell us about your environment, including:
 * Kolibri version 0.14.3
 * Operating system Windows 10

…

### PR DESCRIPTION
**Pull request by jonboiser**
### Summary

See the video in #7580 for previous behavior. Here's a GIF of how the controls work now. Basically, it everything works the same, except that the "Individual learners" section stays open as long as its checked, and until the "Entire class" radio button is selected again.

CleanShot 2020-10-29 at 17 23 14

To make these changes easier, I reorganized the props and data within the `RecipientSelector` and `IndividualLearnerSelector` to make `RecipientSelector` the primary control point for the whole part of the form, then also changed up the internals of that component to make it more independent from _its_ parents and easier to reason about.

Also fixed #7608, which was due to passing the wrong classroom ID to the Vuex action that creates copies of assignments.

### Reviewer guidance

Here's a checklist I used to manually test it

- [ ] Create quiz/lesson to same class (entire class)
- [ ] Create quiz/lesson to same class (groups only)
- [ ] Create quiz/lesson to same class (learners only)
- [ ] Create quiz/lesson to same class (groups and learners)
- [ ] Copy quiz/lesson to same class (entire class)
- [ ] Copy quiz/lesson to same class (groups only)
- [ ] Copy quiz/lesson to same class (learners only)
- [ ] Copy quiz/lesson to same class (groups and learners)
- [ ] Copy quiz/lesson to different class (entire class)
- [ ] Copy quiz/lesson to different class (groups only)
- [ ] Copy quiz/lesson to different class (learners only)
- [ ] Copy quiz/lesson to different class (groups and learners)

For each item, I would check to see if the Reports + Plan pages worked still and that I could still edit them. Other areas to test would be if assignments are reflected correctly on the Learn page.

### References

Fixes #7608 
Fixes #7580

----

### Contributor Checklist

PR process:

- [x] PR has the correct target branch and milestone
- [x] PR has 'needs review' or 'work-in-progress' label
- [x] If PR is ready for review, a reviewer has been added. (Don't use 'Assignees')
- [x] If this is an important user-facing change, PR or related issue has a 'changelog' label
- [ ] If this includes an internal dependency change, a link to the diff is provided

Testing:

- [ ] Contributor has fully tested the PR manually
- [ ] If there are any front-end changes, before/after screenshots are included
- [ ] Critical user journeys are covered by Gherkin stories
- [ ] Critical and brittle code paths are covered by unit tests

### Reviewer Checklist

- Automated test coverage is satisfactory
- PR is fully functional
- PR has been tested for [accessibility regressions](http://kolibri-dev.readthedocs.io/en/develop/manual_testing.html#accessibility-a11y-testing)
- External dependency files were updated if necessary (`yarn` and `pip`)
- Documentation is updated
- Contributor is in AUTHORS.md

### CODE REVIEW

File: kolibri/plugins/coach/assets/src/views/plan/assignments/RecipientSelector.vue [hunk 1]
```diff
@@ -83,37 +82,64 @@
         default: new Array(),
       },
     },
+    data() {
+      return {
```
Comment (jonboiser) [inline kolibri/plugins/coach/assets/src/views/plan/assignments/RecipientSelector.vue:86]: This is the main piece of the refactor. I copy all the data from `AssignmentCopy/DetailsModal` into this component's `data` object and communicate changes to the Collection-level assignments through `watch.collectionIds`, but keep the same `updateLearners` event which watches for changes in `selectedLearnerIds` (which is two-way binded with IndividualLearnerSelected to make things cleaner).

**Comment by nucleogenesis** [comment]
Late to come to this for review but it works great!
