### PR TITLE
Disabling additional user import until multiple user syncing is working

### LINKED ISSUE #11223: Prevent multiple-learner-import to a single LOD in the setup wizard
## Observed behavior
During QA, we discovered that the multiple-learner on a single device experience is not a good one and has syncing problems. This has been an issue since 0.15. 

## Expected behavior
Since this is not actually an 0.16 regression and requires some complex changes, we will defer the syncing fixes until an upcoming release, but in the meantime, we want to try to prevent this setup from happening in the UI.

There are two possible ways that this could happen, the main option being through the setup wizard, which should be fixed to close out this issue. The is at least one additional edge case, which would be migrating multiple stand-alone device setups, but that is considered out of scope for this issue.

### PR DESCRIPTION
**Pull request by AllanOXDi**
## Summary
This PR disables the multiple-learner-import on LOD on the setup wizard until multiple user syncing feature is fixed in the upcoming release.

## References
#11223

## Reviewer guidance
On setting up an LOD navigate to import facility and click on "Don't have the user credentials? Use an admin account" link
Try importing a user and observe.

Screenshot 2023-09-14 at 19 44 08

Closes #11223

## Testing checklist

- [x] Contributor has fully tested the PR manually
- [ ] If there are any front-end changes, before/after screenshots are included
- [ ] Critical user journeys are covered by Gherkin stories
- [ ] Critical and brittle code paths are covered by unit tests

## PR process

- [ ] PR has the correct target branch and milestone
- [ ] PR has 'needs review' or 'work-in-progress' label
- [ ] If PR is ready for review, a reviewer has been added. (Don't use 'Assignees')
- [ ] If this is an important user-facing change, PR or related issue has a 'changelog' label
- [ ] If this includes an internal dependency change, a link to the diff is provided

## Reviewer checklist

- Automated test coverage is satisfactory
- PR is fully functional
- PR has been tested for [accessibility regressions](http://kolibri-dev.readthedocs.io/en/develop/manual_testing.html#accessibility-a11y-testing)
- External dependency files were updated if necessary (`yarn` and `pip`)
- Documentation is updated
- Contributor is in AUTHORS.md

### CODE REVIEW

File: kolibri/plugins/setup_wizard/assets/src/views/ImportMultipleUsers.vue [hunk 1]
```diff
@@ -91,6 +92,8 @@
         isPolling: false,
         // array of user/learner ids
         learnersBeingImported: [],
+        // To be removed
+        isImportingUserDisabled: false,
```
Comment (nucleogenesis) [inline kolibri/plugins/setup_wizard/assets/src/views/ImportMultipleUsers.vue:96]: A thought just occurred during review. I think that we might want to instead just redirect the user to the LoadingTasksPage once they start an import from the Multiple Users list. I think this will improve the UX as currently it just feels rude to disable every other button on the screen.

Additionally, when you click to "Go back" -- you are landing back on that page w/ the user credentials form. 

I think that on the router, adding a navigation guard to check something like "is a user being imported right now? OR has a user been successfully imported?" -- then if those things are true, we direct the user to the LoadingTaskPage.

**Review by nucleogenesis — CHANGES_REQUESTED** [review]
I'm sorry to do this but - despite this working as requested originally, I think that we ought to improve the UX here a bit by leveraging the router and a navigation guard to improve the UX and limit opportunities to run into errors.

File: kolibri/plugins/setup_wizard/assets/src/views/ImportMultipleUsers.vue [hunk 2]
```diff
@@ -150,6 +150,9 @@
         return this.wizardService.state.context.importedUsers;
       },
       pollImportTask() {
+        if (this.wizardService.state.context.importedUsers.length > 0) {
+          this.wizardService.send('LOADING');
```
Comment (nucleogenesis) [inline kolibri/plugins/setup_wizard/assets/src/views/ImportMultipleUsers.vue:158]: I think that this should probably get called whenever the task is successfully started to import the user. 

The way it is now - the user is watching the user load with a spinner surrounded by disabled buttons, but if we send them to the loading page, they can see the user they selected being imported.

One other thing that this gives us is that it bypasses the user's opportunity to click the back arrow icon on that "Multiple Import" page, which results in an error.

**Review by nucleogenesis — CHANGES_REQUESTED** [review]

File: kolibri/plugins/setup_wizard/assets/src/views/LoadingTaskPage.vue [hunk 3]
```diff
@@ -143,10 +150,11 @@
       this.pollTask();
     },
     methods: {
-      importAnother() {
-        this.isPolling = false;
-        this.wizardService.send('IMPORT_ANOTHER');
-      },
+      // To Do: role this back when multiple user syncing is working in the upcoming release!
```
Comment (nucleogenesis) [inline kolibri/plugins/setup_wizard/assets/src/views/LoadingTaskPage.vue]: I suggest using all-caps TODO -- often they are treated as keywords in your IDE, highlighted within the comments. Also by keeping the convention of using those all-caps versions, we can reliably grep the codebase for all TODO items

**Review by nucleogenesis — CHANGES_REQUESTED** [review]
Just one small style change needed. I tested it and everything worked perfectly! Thanks Allan!

**Review by nucleogenesis — APPROVED** [review]
Looks good thanks Allan. Not sure why the docs are failing though. Might need to re-run that check?

**Review by rtibbles — DISMISSED** [review]
This seems to have been rebased onto develop, not release-v0.16.x - so putting a blocking review until that's resolved, so we don't accidentally merge!

**Comment by AllanOXDi** [comment]
> This seems to have been rebased onto develop, not release-v0.16.x - so putting a blocking review until that's resolved, so we don't accidentally merge!

Ah! my bad I forgot that I branch off 0.16x.

File: kolibri/plugins/setup_wizard/assets/src/views/LoadingTaskPage.vue (hunk 3 above)
Comment (akolson) [reply kolibri/plugins/setup_wizard/assets/src/views/LoadingTaskPage.vue]: @AllanOXDi ?

File: kolibri/plugins/setup_wizard/assets/src/views/LoadingTaskPage.vue [hunk 4]
```diff
@@ -124,9 +130,10 @@
       isSoud() {
         return this.queue === SoudQueue;
       },
-      isImportingSoud() {
-        return this.wizardService.state.context.lodImportOrJoin === LodTypePresets.IMPORT;
-      },
+      // To Do: role this back when multiple user syncing is working in the upcoming release!
```
Comment (akolson) [inline kolibri/plugins/setup_wizard/assets/src/views/LoadingTaskPage.vue]: See comment from @nucleogenesis below. Its also good to clean out any commented out code.

File: kolibri/plugins/setup_wizard/assets/src/views/LoadingTaskPage.vue [hunk 5]
```diff
@@ -35,12 +35,13 @@
       </template>
       <span v-else></span>
     </template>
-    <KButton
+    <!-- To DO: to be roled back when multiple user syncing is working in the upcoming release -->
+    <!-- <KButton
```
Comment (akolson) [inline kolibri/plugins/setup_wizard/assets/src/views/LoadingTaskPage.vue:39]: Lets remove this, we can add it later when we need to. ([YAGNI](https://en.wikipedia.org/wiki/You_aren%27t_gonna_need_it))

Comment (akolson) [reply kolibri/plugins/setup_wizard/assets/src/views/LoadingTaskPage.vue:39]: We can keep the TODO:  comment. Please see Jacob's comments on the naming the TODO.

**Review by akolson — CHANGES_REQUESTED** [review]
Thanks @AllanOXDi code generally looks good. Just a few cleanup tasks that I think should happen(leaving commented code only increases the burden on technical debt), to get the code cleaned up and ready for the merge. I will leave the final approval to @nucleogenesis  in case he has other thoughts.

File: kolibri/plugins/setup_wizard/assets/src/views/LoadingTaskPage.vue (hunk 4 above)
Comment (AllanOXDi) [reply kolibri/plugins/setup_wizard/assets/src/views/LoadingTaskPage.vue]: Hi @akolson , this is a temporary fix we shall need to reinstate it easily in future.

**Comment by nucleogenesis** [comment]
@marcellamaki @rtibbles we _are_ planning to revert the changes that enforce the limit of 1 imported user?

@akolson I was thinking that we should keep it so that whenever we make it so that we can accommodate multiple user import we can quickly and easily revert.

That said, it might just be as easy as just dropping the commits in this PR whenever we get into patch territory post-release. 

In either case, this PR merging should result in a follow-up issue targeted at an 0.16 patch or 0.17 (will defer to Marcella here to be sure)  so that we are sure of how to go about the reversion of these changes in any case. (@AllanOXDi)

**Comment by marcellamaki** [comment]
Yes, we will revert the change, but the timeline of when is still a bit TBD, as it will require some pretty significant updates to some of the syncing work. For now I think let's open a tracking issue and put it in the milestone for 0.16 patches, although I don't actually know that it will be in a patch release, it might make more sense for it to go in a major depending on the changes.

**Review by akolson — APPROVED** [review]
Approving following the discussions. Thanks @AllanOXDi
