### PR TITLE
fixed hidden banner on mobile view

### LINKED ISSUE #9962: Fix "Channel banner" regression on mobile view
## Observed behavior

At some point (probably due to a refactor) - the header on the channel page became hidden and lost the proper spacing. This resulted in the opening of issue https://github.com/learningequality/kolibri/issues/9500, which identified the problem of too much space. This issue will supersede that issue, as the problem is the missing element in the empty space, but not actually the spacing itself. 

## Expected behavior

This issue should revert the changes that caused this banner to disappear. From some initial investigation, I believe it is a spacing issue, and that the component is hidden under the black toolbar, not that the component itself has been deleted.

@pcenov created these images for reference when confirming this problem as part of testing #9883. For this issue to be fixed, the 0.15 view should be present in develop.

image

## User-facing consequences
Missing information

## Context
Kolibri `develop`

### PR DESCRIPTION
**Pull request by AllanOXDi**
## Summary
This PR fixes regression on the mobile view 

…

## References
closes #9962
Before
Screenshot 2023-01-05 at 19 53 21

After
Screenshot 2023-01-05 at 19 41 42

…

## Reviewer guidance
1. Go to the Library > Browse channel.
2. Reduce your screen size to mobile view and observe

## Testing checklist

- [x] Contributor has fully tested the PR manually
- [ ] If there are any front-end changes, before/after screenshots are included
- [ ] Critical user journeys are covered by Gherkin stories
- [ ] Critical and brittle code paths are covered by unit tests

## PR process

- [x] PR has the correct target branch and milestone
- [x] PR has 'needs review' or 'work-in-progress' label
- [ ] If PR is ready for review, a reviewer has been added. (Don't use 'Assignees')
- [ ] If this is an important user-facing change, PR or related issue has a 'changelog' label
- [ ] If this includes an internal dependency change, a link to the diff is provided

## Reviewer checklist

- Automated test coverage is satisfactory
- PR is fully functional
- PR has been tested for [accessibility regressions](http://kolibri-dev.readthedocs.io/en/develop/manual_testing.html#accessibility-a11y-testing)
- External dependency files were updated if necessary (`yarn` and `pip`)
- Documentation is updated
- Contributor is in AUTHORS.md

### CODE REVIEW

**Comment by pcenov** [comment]
@AllanOXDi I confirm, the previously hidden banner is now displayed correctly in all supported browsers.
Just pointing out that there is still a small difference with the 0.15 implementation in terms of the space above the buttons and maybe that should be further specified/corrected? The 0.15 version is to the right:

File: kolibri/plugins/learn/assets/src/views/TopicsPage/TopicsMobileHeader.vue [hunk 1]
```diff
@@ -16,7 +16,7 @@
       </h1>
     </KGridItem>
     <KGridItem
-      :layout4="{ span: 1 }"
+      :layout4="{ span: 4 }"
```
Comment (MisRob) [inline kolibri/plugins/learn/assets/src/views/TopicsPage/TopicsMobileHeader.vue]: What is the intended change in the UI?

File: kolibri/plugins/learn/assets/src/views/TopicsPage/index.vue [hunk 2]
```diff
@@ -32,7 +32,7 @@
         :style="gridOffset"
       >
         <KBreadcrumbs
-          v-if="breadcrumbs.length && windowIsSmall"
+          v-if="breadcrumbs.length"
```
Comment (MisRob) [inline kolibri/plugins/learn/assets/src/views/TopicsPage/index.vue]: This is causing the following regression on non-small screens:

duplicate-breadcrumbs

Needs to be fixed.

File: kolibri/plugins/learn/assets/src/views/TopicsPage/index.vue [hunk 3]
```diff
@@ -693,7 +693,7 @@
 <style lang="scss" scoped>
 
   $header-height: 324px;
-  $toolbar-height: 70px;
+  $toolbar-height: 50px;
```
Comment (MisRob) [inline kolibri/plugins/learn/assets/src/views/TopicsPage/index.vue]: This is causing the following regression on non-small screens:

spacing

Needs to be fixed.

**Review by MisRob — CHANGES_REQUESTED** [review]
Thank you, @AllanOXDi. There are two regressions on non-small screens caused by code updates in this PR that need to be addressed before merging it.

File: kolibri/plugins/learn/assets/src/views/TopicsPage/index.vue (hunk 3 above)
Comment (AllanOXDi) [reply kolibri/plugins/learn/assets/src/views/TopicsPage/index.vue]: @MisRob Thanks for letting me know, I am taking a look at it. I will revert back

**Review by MisRob — APPROVED** [review]
Thank you for the updates

**Comment by pcenov** [comment]
Manual QA passes as well!

**Review by radinamatic — APPROVED** [review]
Manual QA passed, good to go! 💯 :shipit:

**Comment by AllanOXDi** [comment]
Thanks,  proceeding to merge it.
