### PR TITLE
Use useGoBack for course back navigation instead of hardcoded HOME

### LINKED ISSUE #14222: Courses - Clicking the back arrow always brings the user back to the 'Home' page
❌ **This issue is not open for contribution. Visit <a href="https://learningequality.org/contributing-to-our-open-code-base/" target="_blank">Contributing guidelines</a>** to learn about the contributing process and how to find suitable issues.

## Observed behavior
Observed while testing https://github.com/learningequality/kolibri/pull/14122:

If I am viewing a course and I click the back arrow I am always brought back to the Home page:

https://github.com/user-attachments/assets/4a26924c-7012-49c7-bdad-d8401ab85cc5

## Expected behavior

It would be great if we can bring the user back to the page they came from, so that if I were at `Home > Classes > My class` then I should be brought back to that page and if I were at the Home page, I should be brought back to the Home page.
 
## Steps to reproduce the issue

1. Install the build from https://github.com/learningequality/kolibri/pull/14122
2. Sign in as a learner with assigned courses
3. Start interacting with a course and click the back arrow

## Usage Details
Windows 11, Ubuntu 22, Mac OS 15.5  - Chrome, Firefox

### PR DESCRIPTION
**Pull request by nucleogenesis**
## Summary

CourseWelcomePage hardcoded its back arrow to always navigate to the Home page,
regardless of where the user came from. This fix adopts the existing
`useGoBack` / `usePreviousRoute` pattern (used in Facility and Coach plugins)
for course navigation:

1. New `CourseRootPage` wrapper component calls `usePreviousRoute()` and renders `<router-view />`
2. Course routes are nested as children of `CourseRootPage`, enabling previous route tracking
3. `CourseWelcomePage` uses `useGoBack({ fallbackRoute: HOME })` instead of a hardcoded HOME link

This follows the same pattern as `UsersRootPage` (Facility), `QuizResourceSelection` and
`LessonResourceSelection` (Coach).

## References

Fixes #14222

#### QA guidance

> I took these steps to confirm the fix

Setup prerequisites:
- A facility with at least one class
- A learner enrolled in that class
- At least one course assigned to that class
- Content channels imported so the course has content

**Test path 1: From Classes page**
1. Sign in as a learner with assigned courses
2. Navigate to Classes > [Your Class]
3. Click a course card
4. On the CourseWelcomePage, click the back arrow
5. Expected: returns to the class page, not Home

**Test path 2: From Home page**
1. Sign in as the same learner
2. From the Home page, click a course card
3. On the CourseWelcomePage, click the back arrow
4. Expected: returns to Home

**Test path 3: Regression tests on 'no classes guard'**
> This is to ensure that we still correctly redirect people who are not in the class given in their URL
1. 'Signin' as a user by way of the "Explore without account" in an incognito window
2. Copy the URL to a course or class page from a regular browser and try to access it as the anonymous user in incognito
3. See that the user is simply redirected to the Library (this is expected as they are not in any class)

Note that the other case I tested was for a logged-in user trying to go to a class URL for a class they're not in and it resulted in a 404 Error which is right because to the user not in the class, the class doesn't exist.

#### Code Reviewer notes (from Claude)

- `CourseRootPage` is a thin wrapper (~15 lines) following an established pattern — compare with
  `UsersRootPage` in Facility or `QuizResourceSelection` in Coach
- Course routes were restructured from flat to nested under `CourseRootPage`, with the
  `noClassesGuard` handler consolidated on the parent route. URL paths are unchanged.
- We initially explored the `useContentLink` query-param approach (used by TopicsPage for deep
  content browsing), but `useGoBack` is a better fit here — CourseWelcomePage is simple
  "go back one level" navigation, not deep content browsing
- The `useGoBack` pattern relies on `onBeforeRouteUpdate` firing on `CourseRootPage` when
  `CourseUnitView` does `router.replace` to `CourseWelcomePage` (both are child routes).
  This sets `previousRoute`, enabling `router.back()` to return to the correct origin page.
  When no previous route exists (direct link/refresh), it falls back to HOME.

## AI usage

I used Claude Code to investigate the root cause, trace the navigation chain, and explore
two approaches: query-param threading via `useContentLink` and the `useGoBack` /
`usePreviousRoute` pattern. After testing both, we chose `useGoBack` as the better fit
for this use case. I reviewed the generated code and verified it follows the same pattern
used elsewhere in the codebase.

### CODE REVIEW

**Review by rtibblesbot — COMMENTED** [review]
Clean bugfix that correctly adopts the established `usePreviousRoute`/`useGoBack` pattern for course back navigation.

CI: Python tests passing. Frontend tests, linting, and WHL build still pending — verify before merge.

- **suggestion** (1): Bare `/course` path is now routable — see inline comment on `classesRoutes.js:90`
- **praise** (2): See inline comments

---
_@rtibblesbot's comments are generated by an LLM, and should be evaluated accordingly_

<details><summary>How was this generated?</summary>

Reviewed the pull request diff checking for:
- **Correctness:** bugs, edge cases, undocumented behavior, resource leaks, hardcoded values
- **Design:** unnecessary complexity, naming, readability, comment accuracy, redundant state
- **Architecture:** duplicated concerns, minimal interfaces, composition over inheritance
- **Testing:** behavior-based assertions, mocks only at hard boundaries, accurate coverage
- **Completeness:** missing dependencies, unupdated usages, i18n, accessibility, security
- **Principles:** DRY (same reason to change), SRP, Rule of Three (no premature abstraction)
- Checked CI status and linked issue acceptance criteria
- For UI changes: inspected screenshots for layout, visual completeness, and consistency

</details>

File: kolibri/plugins/learn/frontend/routes/classesRoutes.js [hunk 1]
```diff
@@ -86,69 +87,50 @@ export default [
     component: ExamReportViewer,
   },
   {
-    name: PageNames.COURSE_WELCOME,
-    path: '/course/:courseSessionId([a-f0-9]{32})/welcome',
-    component: CourseWelcomePage,
+    path: '/course',
```
Comment (rtibblesbot) [inline kolibri/plugins/learn/frontend/routes/classesRoutes.js:90]: **suggestion:** The parent route `path: '/course'` is now a routable URL, but it has no `name`, no `redirect`, and no default child. If a user navigates to `/course` directly, they'll see `CourseRootPage` rendering an empty `<router-view />` — a blank page.

No UI link currently points to bare `/course`, so this is unlikely to be hit in practice. But a defensive `redirect` (e.g., to HOME) would prevent the blank page if someone bookmarks or manually enters the URL. Low priority — just something to be aware of.

File: kolibri/plugins/learn/frontend/views/CourseRootPage.vue [hunk 2]
```diff
@@ -0,0 +1,19 @@
...
+</template>
+
+
+<script>
+
+  import usePreviousRoute from 'kolibri-common/composables/usePreviousRoute';
+
+  export default {
+    name: 'CourseRootPage',
+    setup() {
```
Comment (rtibblesbot) [inline kolibri/plugins/learn/frontend/views/CourseRootPage.vue:14]: **praise:** Minimal wrapper following the exact same pattern as `UsersRootPage` in Facility — just `usePreviousRoute()` + `<router-view />`. Good restraint keeping it thin.

File: kolibri/plugins/learn/frontend/views/CourseWelcomePage.vue [hunk 3]
```diff
@@ -1,13 +1,13 @@
...
 
   <ImmersivePage
-    :route="homePageLink"
     :appBarTitle="(course && course.title) || ''"
     :loading="loading"
     icon="back"
     :appBarBgColor="$themeTokens.surface"
     :appBarHoverBgColor="$themePalette.grey.v_100"
     :appearanceOverrides="{ backgroundColor: $themeTokens.surface }"
+    @navIconClick="goBack"
```
Comment (rtibblesbot) [inline kolibri/plugins/learn/frontend/views/CourseWelcomePage.vue:10]: **praise:** Good switch from `:route` to `@navIconClick`. `ImmersiveToolbar` renders a static `<router-link>` when `route` is provided, but `useGoBack` needs runtime logic to choose between `router.back()` and the fallback — so the event handler is the correct mechanism.

File: kolibri/plugins/learn/frontend/routes/classesRoutes.js [hunk 4]
```diff
@@ -86,69 +87,52 @@ export default [
...
-  {
-    name: PageNames.COURSE_CONTENT__COURSE,
-    path: '/course/:courseId([a-f0-9]{32})',
-    handler: () => {
-      if (noClassesGuard()) {
-        return noClassesGuard();
+        return;
       }
+      next();
     },
```
Comment (rtibblesbot) [inline kolibri/plugins/learn/frontend/routes/classesRoutes.js:98]: **praise:** Clean consolidation — six identical `handler` wrappers replaced with a single `beforeEnter` on the parent. The guard only needs to check class membership on entry to the `/course` subtree, not on every sibling navigation, so this is both simpler and semantically correct.

**Review by rtibblesbot — APPROVED** [review]
Clean follow-up addressing the prior suggestion.

### Delta from prior review

- **RESOLVED:** bare `/course` blank page — `redirect: '/'` added (d5be2cbef)
- **New:** `beforeEnter` consolidation moves the `noClassesGuard` to the parent route, eliminating six identical `handler` wrappers. Good simplification.

CI: build assets still in progress — verify before merge.

No new findings.

---
_@rtibblesbot's comments are generated by an LLM, and should be evaluated accordingly_

<details><summary>How was this generated?</summary>

Compared the current PR state against findings from a prior review:
- Retrieved prior bot reviews deterministically via the GitHub API
- Classified each prior finding as RESOLVED, UNADDRESSED, ACKNOWLEDGED, or CONTESTED
- Only raised NEW findings for newly introduced code
- Reviewed the pull request diff checking for correctness, design, architecture, testing, completeness, and adherence to DRY/SRP principles
- Checked CI status and linked issue acceptance criteria

</details>

**Review by pcenov — APPROVED** [review]
Thanks @nucleogenesis, implemented as specified with no issues observed while manually testing.

**Review by rtibbles — APPROVED** [review]
I don't know if it's based in anything, but event based navigation versus anchor based always riles me. But it is the most reasonable way to handle this!
