### PR TITLE
Controls overlapping content

### LINKED ISSUE #9345: Controls overlapping content in folder resources panel
## Observed behavior

In the "folder resources" panel for some resources, both the close button and the arrow icon overlap with text:

Screenshot 2022-04-22 at 15-53-19 Watch Me - TED-Ed Lessons - Kolibri

## User-facing consequences

This does not block interaction, but it makes text difficult to read and it looks ugly.

## Steps to reproduce

This occurs using Ted Ed content at https://kolibri-demo.learningequality.org/en/learn/#/topics/c/5900e6eab432596d88ab8cf455a77995?last=TOPICS_TOPIC_SEARCH&topicId=68ad96dcf36f54db9367e76ee7afc015.

## Context

The screenshot was created using Firefox with a 1366×768 resolution.

The same issue was also seen using the Kolibri desktop app for GNOME: https://flathub.org/apps/details/org.learningequality.Kolibri.

Kolibri version: 0.15.1.

### PR DESCRIPTION
**Pull request by LianaHarris360**
## Summary

This PR fixes the icons overlapping with the content in the folder resources side panel. The width of the header content was changed to 90% instead of 100% and the vertical positioning of the forward icon was changed to 15px instead of 34px.

Before Updates:
Before

After Updates:
After

## References

Fixes #9345 

## Reviewer guidance

1. Import Ted Ed content videos 'What really happens to the plastic you throw away - Emma Bryce' and 'Will the ocean ever run out of fish? - Ayana Elizabeth Johnson and Jennifer Jacquet'.
2. Browse the Ted Ed channel to watch the 'What really happens to the plastic you throw away' video
3. Click View Folder Resources in the top right corner.
4. Check if content titles overlap with the close and arrow icons in the folder resources side panel.
5. Check if there is any overlapping with other lengthy titles as well.
----

## Testing checklist

- [x ] Contributor has fully tested the PR manually
- [ x] If there are any front-end changes, before/after screenshots are included
- [ ] Critical user journeys are covered by Gherkin stories
- [ ] Critical and brittle code paths are covered by unit tests

## PR process

- [ ] PR has the correct target branch and milestone
- [ ] PR has 'needs review' or 'work-in-progress' label
- [ ] If PR is ready for review, a reviewer has been added. (Don't use 'Assignees')
- [ ] If this is an important user-facing change, PR or related issue has a 'changelog' label
- [ ] If this includes an internal dependency change, a link to the diff is provided

## Reviewer checklist

- Automated test coverage is satisfactory
- PR is fully functional
- PR has been tested for [accessibility regressions](http://kolibri-dev.readthedocs.io/en/develop/manual_testing.html#accessibility-a11y-testing)
- External dependency files were updated if necessary (`yarn` and `pip`)
- Documentation is updated
- Contributor is in AUTHORS.md

### CODE REVIEW

File: kolibri/core/assets/src/views/SidePanelModal/index.vue [hunk 1]
```diff
@@ -252,7 +252,7 @@
   @import '~kolibri-design-system/lib/styles/definitions';
 
   .header-content {
-    width: 100%;
+    width: 90%;
```
Comment (bjester) [inline kolibri/core/assets/src/views/SidePanelModal/index.vue]: Looking around, it seems we've started accepting usage of CSS `calc()` in Kolibri. That could be an option here, since the 10% you removed would vary depending on width. So something like:
```css
width: calc(100% - 30px);
```

Comment (bjester) [reply kolibri/core/assets/src/views/SidePanelModal/index.vue]: Just using `30px` as an example, I'm not sure how much space is actually needed

Comment (LianaHarris360) [reply kolibri/core/assets/src/views/SidePanelModal/index.vue]: Yes, that's a good point. All of the titles will not be the same width. I will test a few different numbers with the different titles to find an appropriate amount of space to subtract!

Comment (rtibbles) [reply kolibri/core/assets/src/views/SidePanelModal/index.vue]: This seems like an unproblematic use of `calc` - there are some caveats for `calc` in IE11 (look under the known issues tab): https://caniuse.com/?search=calc, but they don't seem to apply here!

**Comment by rtibbles** [comment]
Oh, one thing I'm noticing - the issue that this is fixing is in the Planned Patch 6 milestone, but the PR is targeted at develop. Could you rebase your PR onto release-v0.15.x and retarget to that branch?

**Comment by rtibbles** [comment]
Github actions is being uncooperative because of the target branch change. Will test this locally.

**Comment by pcenov** [comment]
Tested with the latest [0.15.8](https://buildkite.com/organizations/learningequality/pipelines/kolibri-debian/builds/5014/jobs/01833811-8d1e-47af-a6f2-5c179b0a08e9/artifacts/01833ae8-f892-449c-890e-eb89fd93f991) build - everything is as described and functioning correctly. No regressions observed in any of the supported browsers.

File: AUTHORS.md [hunk 2]
```diff
@@ -85,3 +85,4 @@ If you have contributed to Kolibri, feel free to add your name and Github accoun
 | Yash Jipkate | YashJipkate |
 | Yixuan Liu | yil039 |
 | Allan Otodi | AllanOXDi |
+| Liana Harris | LianaHarris360 |
```
Comment (MisRob) [inline AUTHORS.md:88]: Woohoo :)

**Review by MisRob — APPROVED** [review]
Thank you, @LianaHarris360. Code is looking good to me.

**Review by radinamatic — APPROVED** [review]
Manual QA by @pcenov confirms the fix, good to go! 👏🏽 :shipit:

**Comment by rtibbles** [comment]
No linting errors when I check locally, and nothing that would trigger a change in frontend tests. Merging.
