### PR TITLE
Fix alignment of CoreTable headers on IE11

### LINKED ISSUE #7220: Reports and Plan tables alignment issue on IE11
### Observed behavior
Reports and Plan tables alignment issue on IE11

### Expected behavior

…

### User-facing consequences
Reports and Plan tables display like this on IE11
c1

This is the display on Firefox and Chrome 
c2

### Steps to reproduce

…

### Context

Tell us about your environment, including:
 * Kolibri version: 0.14.0 beta7
 * Operating system: Windows 7
 * Browser: IE11

### PR DESCRIPTION
**Pull request by blackboxo**
### Summary
fix table th alignment from center to left on IE

on IE before: 
image

on IE after: 
image

on Chrome(didn't change):
image

### Reviewer guidance

The css of "table th" of component CoreTable has been changed.

### References

#7220 

### Contributor Checklist

PR process:

- [x] PR has the correct target branch and milestone
- [ ] PR has 'needs review' or 'work-in-progress' label
- [ ] If PR is ready for review, a reviewer has been added. (Don't use 'Assignees')
- [ ] If this is an important user-facing change, PR or related issue has a 'changelog' label
- [ ] If this includes an internal dependency change, a link to the diff is provided

Testing:

- [x] Contributor has fully tested the PR manually
- [x] If there are any front-end changes, before/after screenshots are included
- [ ] Critical user journeys are covered by Gherkin stories
- [ ] Critical and brittle code paths are covered by unit tests

### Reviewer Checklist

- Automated test coverage is satisfactory
- PR is fully functional
- PR has been tested for [accessibility regressions](http://kolibri-dev.readthedocs.io/en/develop/manual_testing.html#accessibility-a11y-testing)
- External dependency files were updated if necessary (`yarn` and `pip`)
- Documentation is updated
- Contributor is in AUTHORS.md

### CODE REVIEW

**Comment by blackboxo** [comment]
Sorry. It is my first time to PR. Is it ok that 3 checks are failing? I just change one line code in css.

File: kolibri/core/assets/src/views/CoreTable.vue [hunk 1]
```diff
@@ -109,6 +109,7 @@
 
   /deep/ thead th {
     vertical-align: bottom;
+    text-align: left;
```
Comment (jonboiser) [inline kolibri/core/assets/src/views/CoreTable.vue]:
```suggestion
    text-align: left;
    vertical-align: bottom;
```

**Review by jonboiser — APPROVED** [review]
Looks good, thank you!
