### PR TITLE
Fix global loading state on root Coach pages

### LINKED ISSUE #10729: Update loading state in Coach
## Observed behavior
Plugin specific follow up to https://github.com/learningequality/kolibri/issues/10336

## Expected behavior
When navigating through the coach plugin, users should see proper loading states. If an entire page is loading, the "linear loader" should be displayed at the top of the page. If a section of the page is loading (i.e. the contents of a table, a list of resources) then the circular spinner loader should be used. 

## User-facing consequences
User should have a consistent, smooth experience that properly indicates when there is a transition is happening and/or when data is being loaded.

## Steps to reproduce
Using the "throttle" function on Google chrome with Slow 3G is a helpful way to find problem areas. 

```[tasklist]
### Tasks
- [ ] Investigate and fix https://github.com/learningequality/kolibri/issues/10797
```

### PR DESCRIPTION
**Pull request by MisRob**
## Summary

- Removes global loader from the Coach Classes page since there is already the local one
- Fixes missing global loader on root Coach pages and tabs

See commit messages for more details.

| Before | After |
| -------- | ------ |
| coach-before | coach-after |

## Comments

Further improvements in the Coach loading states and navigation overall are needed. See https://github.com/learningequality/kolibri/issues/11219.

## References

Closes https://github.com/learningequality/kolibri/issues/10729

## Reviewer guidance

On slow network, navigate the root Coach pages and tabs

## Testing checklist

- [x] Contributor has fully tested the PR manually
- [x] If there are any front-end changes, before/after screenshots are included
- [ ] Critical user journeys are covered by Gherkin stories
- [ ] Critical and brittle code paths are covered by unit tests

## PR process

- [x] PR has the correct target branch and milestone
- [x] PR has 'needs review' or 'work-in-progress' label
- [x] If PR is ready for review, a reviewer has been added. (Don't use 'Assignees')
- [ ] If this is an important user-facing change, PR or related issue has a 'changelog' label
- [ ] If this includes an internal dependency change, a link to the diff is provided

## Reviewer checklist

- Automated test coverage is satisfactory
- PR is fully functional
- PR has been tested for [accessibility regressions](http://kolibri-dev.readthedocs.io/en/develop/manual_testing.html#accessibility-a11y-testing)
- External dependency files were updated if necessary (`yarn` and `pip`)
- Documentation is updated
- Contributor is in AUTHORS.md

### CODE REVIEW

**Review by akolson — APPROVED** [review]
Changes look correct to me! Thanks @MisRob!

File: kolibri/plugins/coach/assets/src/routes/index.js [hunk 1]
```diff
@@ -26,7 +26,8 @@ export default [
     path: '/classes',
     component: CoachClassListPage,
     handler(toRoute) {
-      store.dispatch('loading');
+      // loading state is handled locally
+      store.dispatch('notLoading');
```
Comment (rtibbles) [inline kolibri/plugins/coach/assets/src/routes/index.js:30]: This accords with my general sense that we can reduce the role of the core loading state to be about toggling the linear loader when the navigation is still resolving. In this frame, we could handle it entirely within our core routing setup, where we toggle it on before route enter, and toggle it after after the route has resolved.

**Review by rtibbles — APPROVED** [review]
