### PR TITLE
Fix various issues obvious from navigation of coach reports

### LINKED ISSUE #4930: Shouldn't generate links to unstarted exercise detail views
### Observed behavior
Currently all learners have links to the exercise detail view, regardless of whether there are any attempt logs for that learner. If the learner has the status of not started for this exercise, then there should be no link.

Clicking the link gives an error.

### Expected behavior
Should be no link to exercises that a learner has not started.

### User-facing consequences
Confusion, pain, suffering.

### Steps to reproduce
Given that there is a lesson with an exercise in it.
Given that it has been assigned to a class with at least one learner in it.
Given that it has been activated.
Given that the learner has not engaged with the exercise.
When you navigate to the learn report page for that lesson.
When you click on the exercise link.
Then you will see a link for that learner's detail report.

This should be:
Then you will not see a link for that learner's detail report.

### PR DESCRIPTION
**Pull request by rtibbles**
### Summary
* Hides detail links for learners that haven't started.
* Use Score component so that we don't show NaN%
* Hides 'All classes' backlinks when there is only one class for the user
* Refresh class summary when creating new groups, lessons, and modifying lesson resources.

### Reviewer guidance
* For quizzes and exercises in lessons, make sure no links are shown if a learner has not started.
* For a quiz where there is no progress by any students, ensure that Average Score shows a grey dash.
* For a user with only one class that they can see, make sure that the backlinks at the top of each top level page (Home, Report, Plan) are hidden. For a user with more than one class, make sure they are shown.
* Create a new group, lesson, copy a lesson, and modify lesson resources and verify nothing breaks.

### References
Fixes #4930

----

### Contributor Checklist

PR process:

- [x] PR has the correct target branch and milestone
- [x] PR has 'needs review' or 'work-in-progress' label
- [x] If PR is ready for review, a reviewer has been added. (Don't use 'Assignees')
- [ ] If this is an important user-facing change, PR or related issue has a 'changelog' label
- [ ] If this includes an internal dependency change, a link to the diff is provided

Testing:

- [x] Contributor has fully tested the PR manually
- [ ] If there are any front-end changes, before/after screenshots are included
- [ ] Gherkin stories have been updated
- [ ] Unit tests have been updated

### Reviewer Checklist

- Automated test coverage is satisfactory
- PR is fully functional
- PR has been tested for [accessibility regressions](http://kolibri-dev.readthedocs.io/en/develop/manual_testing.html#accessibility-a11y-testing)
- External dependency files were updated if necessary (`yarn` and `pip`)
- Documentation is updated
- Contributor is in AUTHORS.rst

### CODE REVIEW

**Comment by radinamatic** [comment]
> For quizzes and exercises in lessons, make sure no links are shown if a learner has not started. :+1: :heavy_check_mark: 

selection_011

> For a quiz where there is no progress by any students, ensure that Average Score shows a grey dash. :+1: :heavy_check_mark: 

selection_012


> For a user with only one class that they can see, make sure that the backlinks at the top of each top level page (Home, Report, Plan) are hidden. For a user with more than one class, make sure they are shown.  :+1: :heavy_check_mark:  :+1: :heavy_check_mark: 

selection_013


> Create a new group, lesson, copy a lesson, and modify lesson resources and verify nothing breaks.

1. Enrolling learners into the newly created group by class coach throws an error:

workspace 1_014

But if I use the back arrow button, the group is listed correctly with the chosen learners.

2. Creating a lesson also throws errors, and it seems impossible to proceed or go back in the browser:

workspace 1_015


When I edited the URL to go back to Class home, the failed lesson was there and by some magic already completed by all learners... :joy_cat: 
workspace 1_016

3. Copying the lesson and modifying resources seem to work well.

File: kolibri/plugins/coach/assets/src/modules/pluginModule.js [hunk 1]
```diff
@@ -40,6 +40,11 @@ export default {
       state.toolbarRoute = toolbarRoute;
     },
   },
+  getters: {
+    multipleClasses(state) {
+      return state.classList.length > 1;
+    },
```
Comment (indirectlylit) [inline kolibri/plugins/coach/assets/src/modules/pluginModule.js:46]: * since this is a coach-wide getter, recommend renaming to something that conveys its intention a little more - for example `classListPageEnabled`
* also heads-up that the root handler could use a little clean-up (seems to call classroom resource twice?), and maybe even could reference this getter: https://github.com/learningequality/kolibri/blob/develop/kolibri/plugins/coach/assets/src/routes/index.js#L18-L37

**Review by indirectlylit — APPROVED** [review]
looks good

File: kolibri/plugins/coach/assets/src/modules/pluginModule.js (hunk 1 above)
Comment (rtibbles) [reply kolibri/plugins/coach/assets/src/modules/pluginModule.js:46]: Have updated both of these.

**Comment by rtibbles** [comment]
@radinamatic have addressed the two issues you found, firstly by polyfilling Promise.finally, and secondly by delaying the routing to the lesson detail page until we have refreshed the class summary data.
