### PR TITLE
Fix clear button not visible in Channel select due to text overflow for long labels

### LINKED ISSUE #10370: Clear button not visible  properly in Learn > Library > Channels selection box
## Observed behavior

I was just  going through the learn > Library section  where I found that the **cancel button** is n**ot visible especially for long channel names** 

image

Even the channel name  text is overlapping the  section so I think it needs some improvements 
## Errors and logs

…

## Expected behavior

It should either wraps the text or hides the text or  append the with ...

Eg channel_name = kolibri_education_foundation_chapter13

can be change as : kolibri.....chapter13            or            kolibri_education_foundation....

## User-facing consequences

Make sure you have at least some resources locally

## Steps to reproduce

1. Download any resources channels pick longer  resources channels  names
2. Navigate towards the learn > library 
3. On the left side there is a sidebar 
4. Inside the sidebar we have the option to select channels 
5. If you selected longer channel you will unable to see the cancel icon its overlaps with the sidebar

## Context

I would like to solve this issue  so if its possible kindly assigned me 

thank you

### PR DESCRIPTION
**Pull request by Pursottam6003**
Resolves  #10370

## Summary

Fixed the text overlapping from the Library > Resources > select channel 
## References

Before 
Screenshot from 2023-04-02 01-42-49

- [X] After 
image

References : 
https://kolibri-dev.readthedocs.io/en/develop/getting_started.html?highlight=linting#manual-linting-and-formatting
…

## Reviewer guidance

----

## Testing checklist

- [X] Contributor has fully tested the PR manually
- [X] If there are any front-end changes, before/after screenshots are included
- [ ] Critical user journeys are covered by Gherkin stories
- [ ] Critical and brittle code paths are covered by unit tests

## PR process

- [ ] PR has the correct target branch and milestone
- [ ] PR has 'needs review' or 'work-in-progress' label
- [ ] If PR is ready for review, a reviewer has been added. (Don't use 'Assignees')
- [ ] If this is an important user-facing change, PR or related issue has a 'changelog' label
- [ ] If this includes an internal dependency change, a link to the diff is provided

## Reviewer checklist

- Automated test coverage is satisfactory
- PR is fully functional
- PR has been tested for [accessibility regressions](http://kolibri-dev.readthedocs.io/en/develop/manual_testing.html#accessibility-a11y-testing)
- External dependency files were updated if necessary (`yarn` and `pip`)
- Documentation is updated
- Contributor is in AUTHORS.md

### CODE REVIEW

**Comment by Pursottam6003** [comment]
Hii @marcellamaki Mam could you please review this PR 

Thank you

**Comment by Pursottam6003** [comment]
@MisRob mam  could you please review this PR

**Comment by marcellamaki** [comment]
Hi @Pursottam6003 - we appreciate your contribution to Kolibri! We will review it as soon as we are able - it may take a couple of days. Thank you for your patience.

**Review by thanksameeelian — COMMENTED** [review]
this looks good to me! i reviewed the code & tested out @Pursottam6003's solution, and saw it working successfully in Chrome on Mac (Monterey) for many different window dimensions.
Screen Shot 2023-04-11 at 9 40 04 AM

i'm hopeful to see how it performs under QA, and if it's successful after @radinamatic or @pcenov review, it looks good to merge! 🙂

**Comment by radinamatic** [comment]
Manual QA passes on both Ubuntu 20.04 (Firefox & Chrome), and Windows 10 (Firefox, Edge & Chrome):

### Ubuntu

1 | 2 | 3
-- | -- | --
Ubuntu20 04 (start)  Running  - Oracle VM VirtualBox_002 | Ubuntu20 04 (start)  Running  - Oracle VM VirtualBox_003 | Ubuntu20 04 (start)  Running  - Oracle VM VirtualBox_004

### Windows

1 | 2 | 3
-- | -- | --
Win10-2304 (start)  Running  - Oracle VM VirtualBox_003 | Win10-2304 (start)  Running  - Oracle VM VirtualBox_002 | Win10-2304 (start)  Running  - Oracle VM VirtualBox_001

File: kolibri/plugins/learn/assets/src/views/SearchFiltersPanel/SelectGroup.vue [hunk 1]
```diff
@@ -216,6 +216,17 @@
 
 <style lang="scss" scoped>
 
+  // Do not let text oveflow in select menu
+  /deep/ .ui-select-content {
+    width: 100%;
+
+    // remove position absolute to prevent text from getting under button
```
Comment (MisRob) [inline kolibri/plugins/learn/assets/src/views/SearchFiltersPanel/SelectGroup.vue:223]: Thanks again for the helpful explanations, this will surely be valuable in the future

**Comment by MisRob** [comment]
Thank you, @Pursottam6003. I noticed that you aren't in `AUTHORS.md` file yet. I will merge this PR now because I think you have some other work in progress and when you open another PR, please add yourself to the authors list if you'd like to on that opportunity (alternatively, you can open a separate PR).

**Review by MisRob — APPROVED** [review]
