### PR TITLE
Fix exam rendering, prevent exam from rendering if it is completely malformed

### LINKED ISSUE #1301: As learner not able to start the existing exams
## Summary
Learner is not able to start/continue the existing exam
## System information
 - Version: kolibri 0.4.0alpha4
 - Operating system: ubuntu 14.04
 - Browser: chrome and firefox

## How to reproduce

1. Create new user as learner.
2. Add created user into existing class. Where exam is assigned to same class.
3. Login as learner.
4. Click on Exam tab. Then click on start or continue button.

## Screenshots
exam_tab
could_not_start_exam

### PR DESCRIPTION
**Pull request by rtibbles**
## Summary

Fixes a severe bug (caused by an incorrect property name) that stops all exams rendering for learners.

Also just shows an error if *none* of the questions in an exam are capable of being rendered.

refs #1301

### CODE REVIEW

File: kolibri/plugins/learn/assets/src/state/actions.js [hunk 1]
```diff
@@ -601,49 +601,54 @@ function showExam(store, channelId, id, questionNumber) {
...
-                  answer: undefined,
-                  simple_answer: '',
-                  interaction_history: [],
-                  hinted: false,
-                  channel_id: channelId,
-                  content_id: currentQuestion.contentId,
+              if (questions.every(question => !question.itemId)) {
+                // Exam is drawing solely on malformed exercise data, best to quit now
+                coreActions.handleError(store, `This exam has no valid questions`);
+              } else {
```
Comment (indirectlylit) [inline kolibri/plugins/learn/assets/src/state/actions.js:607]: _very_ minor style note: personally I avoid wrapping big chunks of primary code in an `else`, and instead tend to "bail out" of the function on validation failures:

```javascript
if (questions.every(question => !question.itemId)) {
  // Exam is drawing solely on malformed exercise data, best to quit now
  coreActions.handleError(store, `This exam has no valid questions`);
  return;
}
```

Makes cleaner diffs, and also makes it clear that nothing else after that point is relevant.

**Comment by indirectlylit** [comment]
still having some issues with an existing exam:

```
actions.js?5a40:572 Uncaught (in promise) SyntaxError: Unexpected token u in JSON at position 0
    at JSON.parse (<anonymous>)
    at eval (eval at <anonymous> (learn_module-0.4.0alpha4.dev39.js:187), <anonymous>:597:36)
    at eval (eval at <anonymous> (default_frontend-0.4.0alpha4.dev39.js:1046), <anonymous>:37:7)
```

this is happening here:
```javascript
const questionSources = JSON.parse(exam.question_sources);
```

The request to the userexam endpoint was:

```
Request URL: http://localhost:8000/api/content/1ceff53605e55bef987d88e0908658c5/userexam/fbdac6536de24597a860dbdaec8d6d31/?1493171429164=1493171429164
Request Method: GET
Status Code: 200 OK

Response:
{"dataset":null,"exam":null,"collection":null,"assigned_by":null}
```

**Comment by indirectlylit** [comment]
made a new exam and still encountering the same error:

```
mappers.js?d9b6:9 Uncaught (in promise) TypeError: Cannot read property 'assessmentmetadata' of undefined
    at assessmentMetaDataState (eval at <anonymous> (http://localhost:3000/js-dist/default_frontend-0.4.0alpha4.dev39.js:1064:1), <anonymous>:9:32)
    at selectQuestionFromExercise (eval at <anonymous> (http://localhost:3000/js-dist/default_frontend-0.4.0alpha4.dev39.js:1776:1), <anonymous>:12:28)
    at eval (eval at <anonymous> (http://localhost:3000/js-dist/learn_module-0.4.0alpha4.dev39.js:187:1), <anonymous>:623:25)
    at Array.map (native)
    at eval (eval at <anonymous> (http://localhost:3000/js-dist/learn_module-0.4.0alpha4.dev39.js:187:1), <anonymous>:622:49)
    at eval (eval at <anonymous> (http://localhost:3000/js-dist/default_frontend-0.4.0alpha4.dev39.js:1046:1), <anonymous>:37:7)
```

I'll dig a bit deeper...

**Comment by indirectlylit** [comment]
Looks like the content promise is returning an empty list...

```javascript
          const contentPromise = ContentNodeResource.getCollection(
            { channel_id: channelId },
            { ids: questionSources.map(item => item.exercise_id) }).fetch();
```

results in:

```
Request URL: http://localhost:8000/api/content/1ceff53605e55bef987d88e0908658c5/contentnode/?ids=fe0ecde51c1f49bfa60815af0a3859bf%2Cdb214541f8ef47e9a00d94ce67cfcd9d&1493173624859=1493173624859
Request Method: GET
Status Code: 200 OK

Response:
[]
```

**Comment by indirectlylit** [comment]
Ah ha! I think I have a clue. Turns out that the learn view doesn't filter exams by current channel, and these errors seem to occur when I click on an exam which was created for a different channel...

**Comment by indirectlylit** [comment]
(I also never followed up on the first error I saw above - https://github.com/learningequality/kolibri/pull/1335#issuecomment-297215319)

File: kolibri/plugins/learn/assets/src/state/actions.js (hunk 1 above)
Comment (rtibbles) [reply kolibri/plugins/learn/assets/src/state/actions.js:607]: Yeah, does look cleaner.

**Comment by rtibbles** [comment]
For the issue https://github.com/learningequality/kolibri/pull/1335#issuecomment-297215319 were you logged in as an admin?

**Comment by indirectlylit** [comment]
> For the issue #1335 (comment) were you logged in as an admin?

Yes. I've played around with a few user-types, but recently added my admin account to the class.

(There's another minor issue I haven't logged yet around learn behaviors for non-activated exams visible to admins...)

**Comment by indirectlylit** [comment]
actually, maybe that's what it was related to...

**Comment by rtibbles** [comment]
Yeah, I think this might be related to the very permissive permissions that admins have compared to learners, wrt exams.
