### PR TITLE
When toggling Demo Banner, do not send focus to a new location outside of the sign-in page forms

### LINKED ISSUE #7661: Closing the demo banner does not return focus to the username/password field on the Sign In Page
### Observed behavior

When you first load Kolibri with the demo banner enabled and the username form is shown, the username field is focused for you. But if you close the demo banner, focus is returned several positions before the username field on the form, so you need to tab or click back to get to that field.

### Expected behavior

After you close the demo banner, focus is returned to the username form, as it was before you closed the banner.

CleanShot 2020-11-04 at 09 57 20@2x

### Errors and logs

…

### Steps to reproduce

1. With the demo banner enabled, go to the sign in screen and go to a username or password form
1. Close the demo banner
1. Focus will _not_ be returned to the text field that was originally focused.

### Context

…

### PR DESCRIPTION
**Pull request by apurva-modi**
Recorded the previous element that holds focus before the close button is clicked and transfer focus to that element once the header is dismissed

7661-demo

…

### Contributor Checklist

PR process:

- [x] PR has the correct target branch and milestone
- [ ] PR has 'needs review' or 'work-in-progress' label
- [x] If PR is ready for review, a reviewer has been added. (Don't use 'Assignees')
- [ ] If this is an important user-facing change, PR or related issue has a 'changelog' label
- [ ] If this includes an internal dependency change, a link to the diff is provided

Testing:

- [x] Contributor has fully tested the PR manually
- [x] If there are any front-end changes, before/after screenshots are included
- [ ] Critical user journeys are covered by Gherkin stories
- [ ] Critical and brittle code paths are covered by unit tests

### Reviewer Checklist

- Automated test coverage is satisfactory
- PR is fully functional
- PR has been tested for [accessibility regressions](http://kolibri-dev.readthedocs.io/en/develop/manual_testing.html#accessibility-a11y-testing)
- External dependency files were updated if necessary (`yarn` and `pip`)
- Documentation is updated
- Contributor is in AUTHORS.md

### CODE REVIEW

File: kolibri/core/assets/src/views/CoreBanner.vue [hunk 1]
```diff
@@ -57,9 +58,22 @@
...
+    created() {
+      document.addEventListener('focusin', this.focusChange);
+    },
+    beforeDestroy() {
+      document.removeEventListener('focusin', this.focusChange);
+    },
     methods: {
       toggleBanner() {
         this.bannerClosed = !this.bannerClosed;
+        this.previouslyFocusedElement.focus();
```
Comment (jonboiser) [inline kolibri/core/assets/src/views/CoreBanner.vue]: Put a guard here, since it's possible that `this.previouslyFocusedElement` is undefined.

File: kolibri/core/assets/src/views/CoreBanner.vue [hunk 2]
```diff
@@ -57,9 +58,22 @@
...
+      },
+      focusChange(e) {
+        // We need the element prior to the close button
+        if (this.$refs.close_button && e.target != this.$refs.close_button.$el) {
```
Comment (jonboiser) [inline kolibri/core/assets/src/views/CoreBanner.vue]: This extra check for `$refs.close_button` can make this feature a little confusing. For example, if I do this:

1. At Sign-In screen, click "Close" on demo bar right away.
2. Use my keyboard to focus on the "Create Account" button 
3. Press "More info" on demo bar
4. Then focus returns to the username bar.

Do you think you can update this to always have this behavior:

```
Given The demo banner is in closed state
When I focus on an element `$el` on the sign-in page
	And I re-open the demo banner
	And I re-close the demo banner
	Then focus is returned to `$el`.
```

Here's a video of the scenario above.

CleanShot 2021-03-29 at 13 55 14

Comment (apurva-modi) [reply kolibri/core/assets/src/views/CoreBanner.vue]: okay I understood I will do it.

**Review by jonboiser — APPROVED** [review]
Looks good!
