### PR TITLE
Coach loading state reports

### LINKED ISSUE #11856: Loading issues while viewing reports (part 2 & 3)
## Observed behavior
Follow-up from  #11824 (part 1 with `Resource not found` notification was fixed in  https://github.com/learningequality/kolibri/pull/11843)

1. When trying to open the ``need help`` resource in the second lesson, there is a brief flash of the title of the ``need help`` resource from the first lesson (see the recording below). 

2. Size of the lesson (before the resource itself is opened) has a flash of ``NaN B``.

Dual Core 8GBs | Quad Core 16GB
-- | --
https://github.com/learningequality/kolibri/assets/1457929/a6c850c1-6fcb-413f-bdc7-4b01bae3deaa | https://github.com/learningequality/kolibri/assets/1457929/eaad3f2b-5812-4943-b908-519e94e99b6c

## Errors and logs
No errors in the Network tab or the console. Use any of the following to debug:

* [full home folder (280MB)](https://drive.google.com/file/d/14fdx8ynheoCajPBeVyTlOzAffv7sqXnr/view?usp=drive_link)
* [everything but the content (38MB)](https://drive.google.com/file/d/1wQcgFKFxmUiPUkaeDy1LDhiI8ognXcSQ/view?usp=drive_link) 
* [just logs](https://drive.google.com/file/d/1YSi_ymrlXTQnUB0joZe-6hP1lGXXPYvz/view?usp=drive_link)

## Expected behavior
Clear and seamless navigation through coach reports without loading issues. 

## User-facing consequences
Bad coach experience. 

## Steps to reproduce
Load the home folder provided above, try to navigate the **Lek3** and **Lek4** lessons to open and review the resources that learners ``need help`` with.

## Context

 * Kolibri version: 0.16b13
 * Operating system: Windows 7

### LINKED ISSUE #12126: Fix loading state at Coach > Reports
_Originally posted by @pcenov in https://github.com/learningequality/kolibri/issues/12082#issuecomment-2072372525_

> While regression testing I noticed that this is not fixed at Coach > Reports

https://github.com/learningequality/kolibri/assets/79847249/790c7c74-74f9-4fe5-9bad-38cfb161bddf

### PR DESCRIPTION
**Pull request by marcellamaki**
## Summary

Makes some small improvements to loading state management. (There may be other places where we see similar scenarios that are just not found yet due to lingering coach tech debt in loading state).

## References
Fixes #12126
Fixes #11856 
(hopefully)

## Reviewer guidance
Linked PRs have more relevant screengrabs/guidance to better understand the scenarios

## Testing checklist

- [ ] Contributor has fully tested the PR manually
- [ ] If there are any front-end changes, before/after screenshots are included
- [ ] Critical user journeys are covered by Gherkin stories
- [ ] Critical and brittle code paths are covered by unit tests

## PR process

- [ ] PR has the correct target branch and milestone
- [ ] PR has 'needs review' or 'work-in-progress' label
- [ ] If PR is ready for review, a reviewer has been added. (Don't use 'Assignees')
- [ ] If this is an important user-facing change, PR or related issue has a 'changelog' label
- [ ] If this includes an internal dependency change, a link to the diff is provided

## Reviewer checklist

- Automated test coverage is satisfactory
- PR is fully functional
- PR has been tested for [accessibility regressions](http://kolibri-dev.readthedocs.io/en/develop/manual_testing.html#accessibility-a11y-testing)
- External dependency files were updated if necessary (`yarn` and `pip`)
- Documentation is updated
- Contributor is in AUTHORS.md

### CODE REVIEW

File: kolibri/plugins/coach/assets/src/views/reports/ExerciseQuestionListPageBase.vue [hunk 1]
```diff
@@ -81,11 +81,12 @@
     mixins: [commonCoach],
     computed: {
       ...mapState('questionList', ['exercise']),
+      ...mapState('resourceDetail', ['resource']),
       ...mapGetters('questionList', ['difficultQuestions']),
       lesson() {
         return this.lessonMap[this.$route.params.lessonId];
       },
-      resource() {
+      exercise() {
```
Comment (rtibbles) [inline kolibri/plugins/coach/assets/src/views/reports/ExerciseQuestionListPageBase.vue]: I think this computed prop can just be deleted, as both exercise and resource are coming from the vuex state now.

**Review by rtibbles — APPROVED** [review]
Code changes check out.

**Comment by pcenov** [comment]
Looks and feels much better, was able to identify just a couple of issues and filed a follow-up issue here: https://github.com/learningequality/kolibri/issues/12180
