### PR TITLE
Fix Loader Misallignment and Flickering 

### LINKED ISSUE #11884: Loading spinner misalignment
## Observed behavior
There are a couple of places where the `KCircularLoader` spinner is misaligned to the text that it should be next to

## Incorrect display

Sync status display
statusdisplay2

On the downloads page:
image (24)

## Expected behavior
- The `KCircularLoader` should be sized proportionally to the text 
- The loader should be in line with the text, and the items should be alined horizontally

Example of proper scale and alignment:
Screenshot 2024-02-15 at 12 58 10 PM

## Steps to reproduce

1. Set up two Kolibris - one as a Learn Only Device (LOD) and one as a full facility. The LOD should be set up to sync back the main facility
2. Assign some resources to the Learner
3. Observe the sync status 

Part 2:
1. Set up Kolibri as an "on my own" setup
2. download some content from the Kolibri Content Library via your internet connection by browsing the library page
3. go to "my downloads" and observe the syncing display and spinner 

Note: modifying your connection speed to "Slow 3G" in the browser may help with replicating a slower download so the loading/waiting state can be properly observed

## Context
Kolibri v0.16.x

### PR DESCRIPTION
**Pull request by iskipu**
## Summary

This PR fixes Loader misalignment in some places, and also resolves flickering of loader in download page.

https://github.com/learningequality/kolibri/assets/143542192/c590a639-ab75-4c28-8f99-949839770fc9

## References

Fix  #11884

### CODE REVIEW

**Review by LianaHarris360 — CHANGES_REQUESTED** [review]
Thank you for working on this, the improvement of the icon alignment is definitely noticeable! One small issue I noticed is a console error related to setting `disableDefaultTransition` to string "true" instead of a Boolean value.

**Comment by iskipu** [comment]
Thanks @LianaHarris360 i overlooked it, fixed it in the new commit.

File: kolibri/plugins/learn/assets/src/my_downloads/views/DownloadsList/index.vue [hunk 1]
```diff
@@ -83,10 +86,13 @@
...
                   class="icon"
                 />
-                <KCircularLoader
-                  v-if="download.status === 'IN_PROGRESS'"
-                  class="icon"
-                />
+                <div v-if="download.status === 'IN_PROGRESS'" class="inline-loader">
+                  <KCircularLoader
+                    :size="20"
+                    disableDefaultTransition="true"
```
Comment (LianaHarris360) [inline kolibri/plugins/learn/assets/src/my_downloads/views/DownloadsList/index.vue]: The change needs to be made here as well. Once that is done, this PR should be ready to merge :)

Comment (iskipu) [reply kolibri/plugins/learn/assets/src/my_downloads/views/DownloadsList/index.vue]: Apologies, I was in a bit of a hurry yesterday and missed it. Thanks @LianaHarris360  for keeping an eye out! :clinking_glasses: 

Fixed in new commit

**Review by LianaHarris360 — APPROVED** [review]
Everything looks good, thank you!
