### PR TITLE
Hide 'channels' header

### LINKED ISSUE #2758: Remove the "Channels" heading from Learn - Channels
### Observed behavior

Heading `Channels` is repetitive since the wording change from `Topics` ([context here](https://github.com/learningequality/kolibri/issues/2621#issuecomment-345371987)), let's make it `visuallyhidden`. 

win7 start running - oracle vm virtualbox_096

cc @indirectlylit @christianmemije for assignees and milestones

### PR DESCRIPTION
**Pull request by indirectlylit**
### Summary

* visually hides 'channels' title
* deletes a lot of seemingly unused code

old:

image

new:

image

### Reviewer guidance

* Make sure behavior is as expected
* Make sure I didn't "clean up" anything that was being used

### References

fixes #2758

----

### Contributor Checklist

- [x] PR has the correct target milestone
- [x] PR has 'needs review' or 'work-in-progress' label
- [x] If PR is ready for review, it has been assigned or requests review from someone and labeled as 'needs review'
- [x] PR has been fully tested manually
- [ ] Documentation is updated
- [ ] External dependencies files were updated (`yarn` and `pip`)
- [ ] Link to diff of internal dependency change is included
- [ ] Screenshots of any front-end changes are in the PR description
- [x] PR does not introduce [accessibility regressions](http://kolibri.readthedocs.io/en/develop/dev/manual_testing.html#accessibility-a11y-testing)
- [ ] CHANGELOG.rst is updated for high-level changes
- [ ] You've added yourself to AUTHORS.rst if you're not there

### Reviewer Checklist

- [ ] Automated test coverage is satisfactory
- [ ] PR has been fully tested manually

### CODE REVIEW

**Comment by christianmemije** [comment]
We should also add a hidden h1 to the Recommended page

**Comment by christianmemije** [comment]
And while we are here, the titles in the recommend categories should be h1s, not h2s
image

File: kolibri/plugins/learn/assets/src/views/channels-page/index.vue [hunk 1]
```diff
@@ -54,9 +51,7 @@
 
 <style lang="stylus" scoped>
 
-  .page-description
-    margin-top: 1em
-    margin-bottom: 1em
-    line-height: 1.5em
+  .grid
+    margin-top: 48px
```
Comment (christianmemije) [inline kolibri/plugins/learn/assets/src/views/channels-page/index.vue]: Let's reduce this margin-top to 16px, since we are also trying to make better use of space.

**Comment by christianmemije** [comment]
Also let's reduce the top/bottom margin of the k-breadcrumbs component to 16 or 8 px

24px
localhost_8000_learn_ 13

8px
localhost_8000_learn_ 12

**Comment by radinamatic** [comment]
👍 for reminder by @christianmemije above!

Tested on PEX/Ubuntu 16.10: the "behavior is as expected", and I didn't see any signs or consequences of overzealous "clean up"... 🙂 

On the other side, some checkers now report not properly nested headings as content cards are `H3`:

ubuntu16 10 start running - oracle vm virtualbox_105

However, since [WCAG 2.0 does not actually specify that sequential heading structure is required to comply](http://www.accessiq.org/news/news/2017/01/does-non-sequential-heading-structure-fail-wcag-20), even though it is **recommended** in practice, and that inside (our) `Recommended` tab there are `H2` subheadings, I'm not sure how much effort should we put into achieving this at the moment.

File: kolibri/plugins/learn/assets/src/views/channels-page/index.vue (hunk 1 above)
Comment (indirectlylit) [reply kolibri/plugins/learn/assets/src/views/channels-page/index.vue]: 16 looked a bit too small, but will shrink it.

(I was roughly lining them up with the cards in 'Recommended')

Comment (christianmemije) [reply kolibri/plugins/learn/assets/src/views/channels-page/index.vue]: I don't think it's necessary to line up.

**Comment by indirectlylit** [comment]
> We should also add a hidden h1 to the Recommended page

Can't do this without violating string freeze. Filed  #2818

**Comment by indirectlylit** [comment]
> Also let's reduce the top/bottom margin of the k-breadcrumbs component to 16 or 8 px

Can't do this without editing the core-component styles, which could have unintended ramifications. For such a risky change we should do it in develop. filed #2819

File: kolibri/plugins/learn/assets/src/views/channels-page/index.vue (hunk 1 above)
Comment (indirectlylit) [reply kolibri/plugins/learn/assets/src/views/channels-page/index.vue]: addressed

**Comment by indirectlylit** [comment]
> And while we are here, the titles in the recommend category route should be h1s, not h2s

addressed
