### PR TITLE
coach layout updates

### LINKED ISSUE #7422: Coach content counter overflows the channel description tile
### Observed behavior

Do note the coach content counter in the "CSPathshala (English)" tile -

image

### Expected behavior

Given the fixed height of the tile, the description could have a `more` link. In any case, the counter should be within the tile.

### User-facing consequences

Visual inconvenience.

### Errors and logs

…

### Steps to reproduce

1. Ensure `CSPathshala (English)` channel is imported to your device. 
2. Try adding resources to a lesson plan which open the `Manage Resources` screen.

### Context

Kolibri 0.14b15
Any OS, any browser.

### LINKED ISSUE #7437: filters in lesson management have layout regressions
### Observed behavior

image

image

### Context

0.14.0 beta 14

### PR DESCRIPTION
**Pull request by indirectlylit**
### Summary

* adjusts layout behavior to more closely match new 'learn' cards
* 16:9 thumbnails
* cards expand vertically when necessary ref https://github.com/learningequality/kolibri/issues/7422
* fixes search layout regressions

| before | after |
|--|--|
|  |  |

### Reviewer guidance

* look good?
* any regressions?

### References

* fixes https://github.com/learningequality/kolibri/issues/7422
* fixes https://github.com/learningequality/kolibri/issues/7437

----

### Contributor Checklist

PR process:

- [x] PR has the correct target branch and milestone
- [x] PR has 'needs review' or 'work-in-progress' label
- [x] If PR is ready for review, a reviewer has been added. (Don't use 'Assignees')
- [ ] If this is an important user-facing change, PR or related issue has a 'changelog' label
- [ ] If this includes an internal dependency change, a link to the diff is provided

Testing:

- [x] Contributor has fully tested the PR manually
- [x] If there are any front-end changes, before/after screenshots are included
- [ ] Critical user journeys are covered by Gherkin stories
- [ ] Critical and brittle code paths are covered by unit tests

### Reviewer Checklist

- Automated test coverage is satisfactory
- PR is fully functional
- PR has been tested for [accessibility regressions](http://kolibri-dev.readthedocs.io/en/develop/manual_testing.html#accessibility-a11y-testing)
- External dependency files were updated if necessary (`yarn` and `pip`)
- Documentation is updated
- Contributor is in AUTHORS.md

### CODE REVIEW

File: kolibri/plugins/coach/assets/src/views/plan/LessonResourceSelectionPage/LessonContentCard/index.vue [hunk 1]
```diff
@@ -15,34 +15,32 @@
         :class="{ 'has-message': Boolean(message) }"
         dir="auto"
       >
-        {{ title }}
+        <KLabeledIcon
+
+          :label="title"
+        >
+          <ContentIcon
```
Comment (jonboiser) [inline kolibri/plugins/coach/assets/src/views/plan/LessonResourceSelectionPage/LessonContentCard/index.vue:22]: Use the new `<template #icon>...` syntax here

**Review by jonboiser — APPROVED** [review]
