### PR TITLE
Hide the  'Search' button when there's nothing to search for

### LINKED ISSUE #13261: Coach > Lessons > Manage resources - The "Search" button is active when there are no available resources
## Observed behavior

See the following video:

https://github.com/user-attachments/assets/05223ddb-c8d1-45f6-aac6-cb3e00579ccd

## Expected behavior

Should be further discussed but it seems that it's best to not show the 'Search' button at all when there's nothing to search for.

## Steps to reproduce the issue

1. Install the latest `develop` build and make sure that there are no imported channels with resources on the device
2. Navigate to Class > Lessons > Lesson and click "Manage resources"
3. Observe the enabled 'Search' button

## Usage Details
Windows 11, Ubuntu 22  - Chrome, Firefox

### PR DESCRIPTION
**Pull request by AllanOXDi**
## Summary
This PR hides the 's  the 'Search' button at all when there's nothing to search for
## References

closes #13261
## Reviewer guidance
Navigate to Coach > Lessons > Manage resources - See if the  "Search" button is active with resources in devices Vs without it.

### CODE REVIEW

File: kolibri/plugins/coach/assets/src/views/common/resourceSelection/subPages/SelectionIndex.vue [hunk 1]
```diff
@@ -23,6 +23,7 @@
         {{ selectFromBookmarks$() }}
       </div>
       <KButton
+        v-if="bookmarksCount > 0"
```
Comment (rtibbles) [inline kolibri/plugins/coach/assets/src/views/common/resourceSelection/subPages/SelectionIndex.vue]: This will hide the search button unless the user has bookmarks. I am unsure how this is fixing the issue?

I think you probably intended to do the same if statement here as below, conditionalised on channels.length.

**Review by rtibbles — CHANGES_REQUESTED** [review]
One of the conditions needs to be corrected.

File: kolibri/plugins/coach/assets/src/views/common/resourceSelection/subPages/SelectionIndex.vue (hunk 1 above)
Comment (AllanOXDi) [reply kolibri/plugins/coach/assets/src/views/common/resourceSelection/subPages/SelectionIndex.vue]: Ohh my bad , I see the point. Fixed now I think

**Comment by rtibbles** [comment]
It looks like there's also a search button nested inside the QuizResourceSelectionHeader component here as well: https://github.com/learningequality/kolibri/blob/develop/kolibri/plugins/coach/assets/src/views/common/resourceSelection/QuizResourceSelectionHeader.vue#L21

I know the original issue that was raised by @pcenov was just for lessons, but it looks like quizzes would also be affected. I see this component has a `hideSearch` prop already, so it seems like it would be easy to conditionalize display of that too.

Can you test reproducing this issue for quiz resource selection as well, and if it reproduces we should add the same handling here.

**Comment by AllanOXDi** [comment]
Yes I saw the prop too ! But I am not sure if I can reproduce it quiz .






Screenshot 2025-03-31 at 19 52 19

**Comment by rtibbles** [comment]
If you edit the quiz and then try to add questions would it not appear?

**Comment by pcenov** [comment]
Hi @AllanOXDi - I confirm that the Search button is now hidden in Lessons > Manage resources when there aren't any resources.
As for the Quizzes, this can only be replicated if you have already created some quizzes, then deleted some or all of the resources and after that when you attempt to edit a quiz you will see the following:

https://github.com/user-attachments/assets/5072b0ef-1cef-406b-9f2b-fca5e63f1bbc

So it seems that this should be a follow-up issue as the Search button is not the only thing that should be handled better.

**Review by rtibbles — APPROVED** [review]
Manual QA passes, we can punt the quiz changes to a follow up issue.

**Comment by rtibbles** [comment]
Opened a follow up issue.
