### PR TITLE
Show notification on SelectImportSourceModal while checking STudio

### LINKED ISSUE #4070: No indication that anything is happening during long wait for content import method selection modal
### Observed behavior

On a slow/high-latency connection (I'm tethering at the moment), it takes a long time to check whether we're online and un-gray the options on this modal:

image

If I didn't know better, I'd think nothing was happening, and no options were available. But then eventually it resolves.

### Expected behavior

Some sort of indication that processing/activity is going on, so that I know to wait, rather than hitting cancel. Perhaps that spinner in the top-right of the modal that @khangmach experimented with for adding of network addresses?

### User-facing consequences

Confusion and frustration.

### PR DESCRIPTION
**Pull request by jonboiser**
### Summary

Shows a on the Select Import Source Modal if it takes more than 100 msec to determine whether or not Kolibri Studio is available.

loading

Fixes #4070

### Reviewer guidance

1. Check modal behavior on a fast connection
1. Check modal behavior on a slow connection
1. Check modal behavior when offline

### References

…

----

### Contributor Checklist

- [x] Contributor has fully tested the PR manually
- [x] PR has the correct target branch and milestone
- [x] PR has 'needs review' or 'work-in-progress' label
- [x] If PR is ready for review, a reviewer has been added. (Don't use 'Assignees')
- [x] If there are any front-end changes, before/after screenshots are included
- [x] If this is an important user-facing change, PR or related issue has a 'changelog' label

### Reviewer Checklist

- [ ] Automated test coverage is satisfactory
- [ ] Reviewer has fully tested the PR manually
- [ ] PR has been tested for [accessibility regressions](http://kolibri-dev.readthedocs.io/en/develop/manual_testing.html#accessibility-a11y-testing)
- [ ] External dependencies files were updated (`yarn` and `pip`)
- [ ] Documentation is updated
- [ ] Link to diff of internal dependency change is included
- [ ] CHANGELOG.rst is updated for high-level changes
- [ ] Contributor is in AUTHORS.rst

### CODE REVIEW

**Comment by radinamatic** [comment]
Excellent, as this has been known to confuse even in house (#3949)...

File: kolibri/plugins/device_management/assets/src/views/ManageContentPage/SelectTransferSourceModal/SelectImportSourceModal.vue [hunk 1]
```diff
@@ -41,26 +47,33 @@
...
         ContentSources,
+        showNotifications: false,
       };
     },
     computed: {
       ...mapGetters('manageContent/wizard', ['isImportingMore']),
     },
     created() {
+      // Only show notification if things take too long
+      setTimeout(() => {
```
Comment (rtibbles) [inline kolibri/plugins/device_management/assets/src/views/ManageContentPage/SelectTransferSourceModal/SelectImportSourceModal.vue]: Can probably remove the `setTimeout` and `showNotification` flag, as it doesn't seem to benefit the slower case, and can cause a weird popin/out effect in the faster case.

notification

Comment (rtibbles) [reply kolibri/plugins/device_management/assets/src/views/ManageContentPage/SelectTransferSourceModal/SelectImportSourceModal.vue]: I tried it without the setTimeout and it seemed to be a slightly less jarring experience.

**Review by indirectlylit — APPROVED** [review]
thanks!
