### PR TITLE
Robustify frontend to missing assessment metadata

### LINKED ISSUE #1238: Coach is not able to create exam
## Summary
Coach user is not able to create exam for learners.

## System information

 - Version: kolibri 0.4.0alpha2
 - Operating system: Ubuntu 14.04 LTS
 - Browser: Chrome Browser and Firefox

## How to reproduce

1. Login with Coach user.
2. Click on coach and then class name.
3. Nothing will appear on screen.
## Screenshots
screenshot from 2017-04-18 10_52_12

### LINKED ISSUE #1301: As learner not able to start the existing exams
## Summary
Learner is not able to start/continue the existing exam
## System information
 - Version: kolibri 0.4.0alpha4
 - Operating system: ubuntu 14.04
 - Browser: chrome and firefox

## How to reproduce

1. Create new user as learner.
2. Add created user into existing class. Where exam is assigned to same class.
3. Login as learner.
4. Click on Exam tab. Then click on start or continue button.

## Screenshots
exam_tab
could_not_start_exam

### LINKED ISSUE #1303: Coach report Exercise Detail View is not working.
## Summary
Coach report Exercise Detail View is not working.

## System information
 - Version: Kolibri 0.4.0alpha4
 - Operating system: Ubuntu 14.04 LTS
 - Browser: Chrome

## How to reproduce

1. Master an exercise as a learner.
2. Login as a coach.
3. Drill down on to see the detailed view of the exercise.

## Screenshots
coach report recent
coach report 1
coach report 2

### LINKED ISSUE #1305: Question content not showing
## Summary

After importing magogenie test channel. Question content of existing topic(not newly updated topic) of same channel is not shown.

## System information

 - Version: kolibri 0.4.0aplha4
 - Operating system: ubuntu 14.04
 - Browser: chrome and firefox
- Channel ID : 7769d932b2cc49efb18c5e665cda64ff

## How to reproduce

1. Login as device owner . 
2. Import channel "7769d932b2cc49efb18c5e665cda64ff"
3. Click on topic->MG Copied->Rupees and Paise - > Notes and Coins ->level1

## Screenshots
content_not_showing

### LINKED ISSUE #1309: add handling for missing assessment meta data
Sometimes assessment metadata is missing from content nodes, and the front-end makes the assumption that it's always there. We should add handling to either gracefully fail when it's missing or insert some empty metadata so the attribute is at least defined.

cc @rtibbles @jayoshih

### PR DESCRIPTION
**Pull request by rtibbles**
## Summary

Fixes #1309, and in the process should resolve #1238, resolve #1301, fix #1303, and close #1305.

Does this by using the same assessment meta data validation logic everywhere that we use assessment meta data in the app, by means of a core util function.

### CODE REVIEW

File: kolibri/core/assets/src/content/utils.js [hunk 1]
```diff
@@ -0,0 +1,27 @@
+function validateAssessmentMetaData(data) {
+  // Data is coming from a serializer for a one to many key, so at least will return an empty array.
+  const assessmentMetaData = data.assessmentmetadata[0];
+  if (!assessmentMetaData) {
+    return {
+      assessment: false,
+    };
```
Comment (indirectlylit) [inline kolibri/core/assets/src/content/utils.js]: shouldn't we include `assessmentIds: []` here?

Otherwise there's still a chance that a user will do a check of `assessmentmetadata.assessmentIds.length` and throw an error.

Comment (indirectlylit) [reply kolibri/core/assets/src/content/utils.js]: Also, maybe consider adding

```
  masteryModel: null,
  randomize: false,
```

Things get tricky when fields are sometimes set and sometimes not, because it's not clear whether it's intentional or a bug. Setting `masteryModel` to `null` explicitly says "this attribute exists but doesn't have a value".

File: kolibri/core/assets/src/content/utils.js [hunk 2]
```diff
@@ -0,0 +1,27 @@
+function validateAssessmentMetaData(data) {
+  // Data is coming from a serializer for a one to many key, so at least will return an empty array.
```
Comment (indirectlylit) [inline kolibri/core/assets/src/content/utils.js]: > so at least will return an empty array

I don't quite understand what this means. Is `data.assessmentmetadata` always an array with length 0 or 1?

File: kolibri/core/assets/src/content/utils.js [hunk 3]
```diff
@@ -0,0 +1,27 @@
...
+  return {
+    assessment: true,
+    assessmentIds,
+    masteryModel,
+    randomize: assessmentMetaData.randomize,
+  };
+}
+
+module.exports = {
+  validateAssessmentMetaData,
```
Comment (indirectlylit) [inline kolibri/core/assets/src/content/utils.js]: it isn't really a validator - more like one of our state mappers (with some normalization)?

Maybe instead call it `assessmentMetadataState` and put it in the `core/state` directory?

File: kolibri/core/assets/src/content/utils.js (hunk 2 above)
Comment (rtibbles) [reply kolibri/core/assets/src/content/utils.js]: Right.

File: kolibri/core/assets/src/content/utils.js (hunk 1 above)
Comment (rtibbles) [reply kolibri/core/assets/src/content/utils.js]: Yes, it should be consistent - I thought I had added that. Will make the keys return across the board.

File: kolibri/core/assets/src/content/utils.js (hunk 3 above)
Comment (rtibbles) [reply kolibri/core/assets/src/content/utils.js]: Yeah, I was thinking that as I submitted the PR, will update.

File: kolibri/core/assets/src/exams/utils.js [hunk 4]
```diff
@@ -1,4 +1,5 @@
 const seededShuffle = require('seededshuffle');
+const { assessmentMetaDataState } = require('kolibri.coreVue.vuex.mappers');
```
Comment (DXCanas) [inline kolibri/core/assets/src/exams/utils.js:2]: Fancy

**Comment by indirectlylit** [comment]
looking good - merging in current state of things but still having some issues with #1301 in particular
