### PR TITLE
Move facility name input outside of radio buttons in setup wizard

### LINKED ISSUE #7448: In Setup Wizard, Facility name field can move around because it is inside the label for radio buttons
### Observed behavior

the two radio buttons have an "internal" text field that gets hidden and shown:

### Expected behavior

Normal radio buttons, with a static facility name field

@jonboiser : Put the textbox above the radio buttons.

### User-facing consequences

confusing shifting of the UI elements

### Steps to reproduce

go through the advanced setup wizard

### Context

0.14.0

### PR DESCRIPTION
**Pull request by alexMet**
### Summary

Moved facility name input outside of radio buttons in setup wizard.

simplescreenrecorder

### References

#7448 

----

### Contributor Checklist

PR process:

- [x] PR has the correct target branch and milestone
- [x] PR has 'needs review' or 'work-in-progress' label
- [ ] If PR is ready for review, a reviewer has been added. (Don't use 'Assignees')
- [ ] If this is an important user-facing change, PR or related issue has a 'changelog' label
- [ ] If this includes an internal dependency change, a link to the diff is provided

Testing:

- [x] Contributor has fully tested the PR manually
- [x] If there are any front-end changes, before/after screenshots are included
- [ ] Critical user journeys are covered by Gherkin stories
- [x] Critical and brittle code paths are covered by unit tests

### Reviewer Checklist

- Automated test coverage is satisfactory
- PR is fully functional
- PR has been tested for [accessibility regressions](http://kolibri-dev.readthedocs.io/en/develop/manual_testing.html#accessibility-a11y-testing)
- External dependency files were updated if necessary (`yarn` and `pip`)
- Documentation is updated
- Contributor is in AUTHORS.md

### CODE REVIEW

File: kolibri/plugins/setup_wizard/assets/src/views/onboarding-forms/FacilityPermissionsForm.vue [hunk 1]
```diff
@@ -90,11 +83,7 @@
     },
     methods: {
       focusOnTextbox() {
-        if (this.nonformalIsSelected) {
-          return this.$refs['facility-name-nonformal'].focus();
-        } else if (this.formalIsSelected) {
-          return this.$refs['facility-name-formal'].focus();
-        }
+        return this.$refs['facility-name'].focus();
```
Comment (jonboiser) [inline kolibri/plugins/setup_wizard/assets/src/views/onboarding-forms/FacilityPermissionsForm.vue:79]: Could you remove the `watch.selected` handler calling `focusOnTextbox` on line 74? Otherwise, everytime you change between formal/non-formal, the Facility Name field gets focused.

Comment (alexMet) [reply kolibri/plugins/setup_wizard/assets/src/views/onboarding-forms/FacilityPermissionsForm.vue:79]: Done

**Review by jonboiser — APPROVED** [review]
Looks good, thank you!
