### PR TITLE
Fix checkbox label click

### LINKED ISSUE #2233: clicking label for k-checkbox does not trigger 'change' event
Don't know if it's being used wrong in 'facilities-config-page', but expected clicking label to work the same as clicking the actual checkbox.
```
            <k-checkbox
              :label="$tr(setting)"
              :checked="settings[setting]"
              @change="toggleSetting(setting)"
            />

```
label click

### PR DESCRIPTION
**Pull request by christianmemije**
The issue was that clicking on the label was triggering a change which would cause the toggle/selection to be called twice. Preventing the default behavior of label clicks fixes this. Fixes #2233

### CODE REVIEW

File: kolibri/plugins/coach/assets/src/views/groups-page/group-section.vue [hunk 1]
```diff
@@ -68,7 +68,7 @@
               :showLabel="false"
               :checked="isSelected(user.id)"
               @change="toggleSelection(user.id)"
-              @click.stop
+              @click.native.stop
```
Comment (jonboiser) [inline kolibri/plugins/coach/assets/src/views/groups-page/group-section.vue:71]: Cool. What does `native` do here?

Comment (christianmemije) [reply kolibri/plugins/coach/assets/src/views/groups-page/group-section.vue:71]: Catches the native click event of the component, since the k-checkbox does not actually emit a click event. https://vuejs.org/v2/guide/components.html#Binding-Native-Events-to-Components

File: kolibri/plugins/management/assets/src/views/class-enroll-page/index.vue [hunk 2]
```diff
@@ -91,6 +91,7 @@
                 :checked="isSelected(learner.id)"
                 @change="toggleSelection(learner.id)"
                 class="inline-block check"
+                 @click.native.stop
```
Comment (jonboiser) [inline kolibri/plugins/management/assets/src/views/class-enroll-page/index.vue]: extra space here

File: kolibri/plugins/coach/assets/src/views/groups-page/group-section.vue (hunk 1 above)
Comment (jonboiser) [reply kolibri/plugins/coach/assets/src/views/groups-page/group-section.vue:71]: Do you think it would be possible to make `@change` on the `k-checkbox` a no-op because the outer div also has `toggleSelection(user.id)` as its on-click callback too? Or does the outer div not register a click when you hit the checkbox exactly?

Comment (christianmemije) [reply kolibri/plugins/coach/assets/src/views/groups-page/group-section.vue:71]: The input element of the k-checkbox has ` @click.stop="toggleCheck"` to stop the event propagation and prevent the checkbox container from also triggering `toggleCheck`. So clicking directly on on the checkbox, stops the click event from bubbling up and ever making reaching `@click="toggleSelection(user.id)"`

Comment (christianmemije) [reply kolibri/plugins/coach/assets/src/views/groups-page/group-section.vue:71]: So not possible.
