### PR TITLE
Restore superuser's access to coach pages

### LINKED ISSUE #2151: Coach section not accessible to superusers
Something might have gone wrong in a merge, since the coach plugin was opened up to superusers in #2118, but is not longer at the moment.

### PR DESCRIPTION
**Pull request by jonboiser**
Fixes #2151

### CODE REVIEW

File: kolibri/plugins/coach/assets/src/views/index.vue [hunk 1]
```diff
@@ -22,8 +22,8 @@
 <script>
 
   import store from '../state/store';
-  import * as Constants from '../constants';
-  import * as coreGetters from 'kolibri.coreVue.vuex.getters';
+  import { PageNames } from '../constants';
```
Comment (rtibbles) [inline kolibri/plugins/coach/assets/src/views/index.vue:25]: Much clean.

File: kolibri/plugins/coach/assets/src/views/index.vue [hunk 2]
```diff
@@ -8,7 +8,7 @@
         <top-nav/>
       </template>
 
-      <div v-if="isCoach || isAdmin || isSuperuser">
+      <div v-if="userCanAccessPage">
         <component :is="currentPage"/>
       </div>
       <auth-message v-else authorizedRole="adminOrCoach" />
```
Comment (rtibbles) [inline kolibri/plugins/coach/assets/src/views/index.vue:14]: @indirectlylit note that the auth-message component will need to be cleaned up wrt `superuser`, but as you want to do that in one sweep, I think we'll leave this as is for now.

File: kolibri/plugins/coach/assets/src/views/index.vue [hunk 3]
```diff
@@ -8,7 +8,7 @@
         <top-nav/>
       </template>
 
-      <div v-if="isCoach || isAdmin || isSuperuser">
```
Comment (rtibbles) [inline kolibri/plugins/coach/assets/src/views/index.vue:11]: Kind of confused why this isn't working as is.
