### PR TITLE
Fix creating a quiz without having imported resources or users enrolled in the class

### LINKED ISSUE #12330: Issues when creating a quiz without having imported resources or users enrolled in the class
## Observed behavior

Observed while testing https://github.com/learningequality/kolibri/pull/12312 - if there are no imported channels and/or no imported users then we are not showing appropriate messages to the coach:

Videos:

https://github.com/learningequality/kolibri/assets/79847249/6aa47f65-773c-4a32-86f1-20ded1c5d6f2

https://github.com/learningequality/kolibri/assets/79847249/454e450d-3ebe-4285-962b-7644f0549bd8

## Expected behavior

1. If there are no imported channels, when attempting to add questions users should see a modal informing them that there are no imported resources.
2. If there are no learners enrolled in the class that should also be explicitly stated.

## Steps to reproduce the issue

1. Install the build from https://github.com/learningequality/kolibri/pull/12312
2. Attempt to add questions to a quiz without having imported any channels with exercises before that.
3. Attempt to assign the quiz to a learner without having enrolled learners in the class.

## Usage Details
Windows 11, Ubuntu 22  - Chrome

### PR DESCRIPTION
**Pull request by AllanOXDi**
## Summary

This pull request adds warning messages for scenarios in which there are no imported channels and/or users associated with the class when a coach attempts to create a quiz.

## References
[#12330](https://github.com/learningequality/kolibri/issues/12330)
## Reviewer guidance

1. Please review the slack conversations for some decisions made whether to use a model or not [here ](https://learningequality.slack.com/archives/CB37UM23A/p1729271450496829)and[ here](https://learningequality.slack.com/archives/CTG8XDTCL/p1729629998736479)
2. Does the changes makes sense ?

## Testing checklist

- [x] Contributor has fully tested the PR manually
- [ ] If there are any front-end changes, before/after screenshots are included
- [ ] Critical user journeys are covered by Gherkin stories
- [ ] Critical and brittle code paths are covered by unit tests

## PR process

- [ ] PR has the correct target branch and milestone
- [ ] PR has 'needs review' or 'work-in-progress' label
- [ ] If PR is ready for review, a reviewer has been added. (Don't use 'Assignees')
- [ ] If this is an important user-facing change, PR or related issue has a 'changelog' label
- [ ] If this includes an internal dependency change, a link to the diff is provided

## Reviewer checklist

- PR is fully functional
- PR has been tested for [accessibility regressions](http://kolibri-dev.readthedocs.io/en/develop/manual_testing.html#accessibility-a11y-testing)
- External dependency files were updated if necessary (`yarn` and `pip`)
- Documentation is updated
- Contributor is in AUTHORS.md

### CODE REVIEW

File: kolibri/plugins/coach/assets/src/views/plan/CoachExamsPage/index.vue [hunk 1]
```diff
@@ -7,6 +7,29 @@
...
+          <div>
+            <KIcon
+              icon="warning"
+              class="warning-icon"
+              :color="$themePalette.yellow.v_1100"
+            />
+          </div>
+
+          <div class="error-message">
+            <p v-if="channels.length === 0">{{ noResourcesAvailable$() }}</p>
```
Comment (marcellamaki) [inline kolibri/plugins/coach/assets/src/views/plan/CoachExamsPage/index.vue]: [improvement, non-blocking] To simplify this, you could put the condition on message container div here, rather than on the `<p>` tag and on the link separately. (But keep the `v-if="deviceContentUrl` on the link)

File: kolibri/plugins/coach/assets/src/views/plan/CoachExamsPage/index.vue [hunk 2]
```diff
@@ -353,8 +385,25 @@
...
+      deviceContentUrl() {
+        const deviceContentUrl = urls['kolibri:kolibri.plugins.device:device_management'];
+        if (deviceContentUrl && this.canManageContent) {
+          return `${deviceContentUrl()}#/content`;
+        }
+
+        return '';
+      },
+      hasNoChannels() {
+        return !this.channels || this.channels.length === 0;
```
Comment (marcellamaki) [inline kolibri/plugins/coach/assets/src/views/plan/CoachExamsPage/index.vue]: [blocking, small cleanup] Doing this type of check is typically a good idea when fetching data, but it's unnecessary here. Since you have set up `channels` in `data` to be an empty array, `this.channels` will always exist, even if the channels haven't loaded yet. That means, the critical piece here is the "`this.channels.length === 0`"

[improvement, non-blocking] In your template code, you are using `channels.length === 0` on the banner and then you use this `hasNoChannels` computed prop for the button. I think it would be easier to see when reading the code that these are always "opposite" conditions, meaning that if one shows up, the other doesn't, if your code is more clearly referencing the same condition in both places. 

You could either update this computed prop to just be checking if `this.channels.length` and not worry about the existence check, and use `hasNoChannels` in both places, or you could delete this computed prop entirely and just use a length check in both places.

File: kolibri/plugins/coach/assets/src/views/plan/CoachExamsPage/index.vue [hunk 3]
```diff
@@ -408,6 +457,17 @@
         nextRoute.name = nextRouteName;
         this.$router.push(nextRoute);
       },
+      fetchResources() {
+        ChannelResource.fetchCollection({
+          getParams: {
+            contains_exercise: true,
+            available: true,
+            contains_quiz: true,
```
Comment (marcellamaki) [inline kolibri/plugins/coach/assets/src/views/plan/CoachExamsPage/index.vue]: [blocking] `contains_quiz` is not the most intuitive, because this isn't actually about for being able to create a quiz, but rather, whether or not a channel contains practice quizzes. Including this as `true` therefore is more restriction than you want. 

`contains_exercise: true` is definitely always required for a channel to be able to be used to create a quiz, but `contains_quiz` is not required. 

To see more specifically what I mean, you can use the Kolibri QA channel. Importing a few exercises, but no practice quizzes means that this fetch will return an empty array.

https://github.com/user-attachments/assets/15396efc-8336-4b38-baa4-44db4cd39334

File: kolibri/plugins/coach/assets/src/views/plan/assignments/IndividualLearnerSelector.vue [hunk 4]
```diff
@@ -32,7 +32,7 @@
         <template #default="{ items }">
           <CoreTable
             :selectable="true"
-            :emptyMessage="$tr('noUsersMatch')"
+            :emptyMessage="noLearnersEnrolled$({ className: className })"
```
Comment (marcellamaki) [inline kolibri/plugins/coach/assets/src/views/plan/assignments/IndividualLearnerSelector.vue]: [blocking] what happens here if you do have learners [learner_a, learner_b] enrolled in the class, and you search in the learners table for "learner_c"?

Screenshot 2024-10-24 at 4 07 24 PM

File: kolibri/plugins/coach/assets/src/views/plan/CoachExamsPage/index.vue [hunk 5]
```diff
@@ -353,8 +385,25 @@
         }
         return '--';
       },
+      deviceContentUrl() {
+        const deviceContentUrl = urls['kolibri:kolibri.plugins.device:device_management'];
+        if (deviceContentUrl && this.canManageContent) {
```
Comment (marcellamaki) [inline kolibri/plugins/coach/assets/src/views/plan/CoachExamsPage/index.vue:503]: nice work with this!

**Review by marcellamaki — DISMISSED** [review]
Hi @AllanOXDi - overall, this is very close to being done, and the changes I'm requesting hopefully should be more of a little bit of tidying up than anything. 

[blocking] This PR deletes the `yarn.lock` file which I think is maybe an unintended side effect of your rebasing. This is also causing a problem with the checks - you can see there's an issue in the dependencies that's preventing the whl from building which prevents the other build assets from running as well. If you update this, hopefully that should resolve the problem! If after you update this, the checks are still failing, let me know so we can troubleshoot further.

[improvement, non-blocking] can you think of a way to add some `loading` or state management logic to help prevent the potential for a flash of the banner? Not required - there are a lot of pre-existing loading state challenges in Coach.

https://github.com/user-attachments/assets/39160cbe-2d43-44a2-9d55-b3568604aa7c

**Review by pcenov — APPROVED** [review]
Hi @AllanOXDi, on my end I confirm that the 2 issues described in https://github.com/learningequality/kolibri/issues/12330 are now fixed so if there's nothing else in terms of code cleanup this should be good to go!

File: kolibri/plugins/coach/assets/src/views/plan/assignments/IndividualLearnerSelector.vue (hunk 4 above)
Comment (AllanOXDi) [reply kolibri/plugins/coach/assets/src/views/plan/assignments/IndividualLearnerSelector.vue]: I miss this. I think we will still see `noLearnerEnrolled` string. Which does not make sense. Should  we haddled that with` noUsersMatch' string?

Comment (marcellamaki) [reply kolibri/plugins/coach/assets/src/views/plan/assignments/IndividualLearnerSelector.vue]: Yes, I think handling that with the `noUsersMatch` string, and using one or the other based on the condition, would be the way to go

**Comment by marcellamaki** [comment]
Hi @AllanOXDi - this is ready to go, but can you please remove the `yarn.lock` file as it is not related to this changes? Then we can merge

**Review by rtibbles — APPROVED** [review]
Have done a small rebase to get this mergeable. Confirmed that the fix is still in place after rebase.
