### PR TITLE
Fix search box on IE

### LINKED ISSUE #2670: Search button position in IE11
(no blocker, feel free to push forward)

### Observed behavior

Search button in IE11 displays  a white line on top, but seems OK in Edge. 
Not sure if it has something to do with the vertical alignment of the placeholder, which seems top aligned in IE11 and bottom in Edge.

#### IE11 in Windows 7

win7 start running - oracle vm virtualbox_067

#### IE11 in Windows 8.1

win8 1 running - oracle vm virtualbox_068

#### MS Edge in Windows 10

win10 start running - oracle vm virtualbox_069

### Expected behavior

Button to display in IE11 same as in Edge.

### Context

* Kolibri version: 0.6 on demo servers (https://instantschools-v2.learningequality.org)
* Operating system: Windows 7 & 8.1
* Browser: IE11

### PR DESCRIPTION
**Pull request by christianmemije**
### Summary

Fixes search box on IE.
Fixes #2670 

#### Before

before

#### After

after

### Reviewer guidance

Open on IE11 and test.

### References

Fixes #2670 

----

### Contributor Checklist

- [x] PR has the correct target branch and milestone
- [x] PR has 'needs review' or 'work-in-progress' label
- [x] Contributor has fully tested the PR manually
- [x] Screenshots of any front-end changes are in the PR description
- [x] If PR is ready for review, a reviewer has been added. (Don't use 'Assignees')

### Reviewer Checklist

- [ ] Automated test coverage is satisfactory
- [ ] Reviewer has fully tested the PR manually
- [ ] PR has been tested for [accessibility regressions](http://kolibri-dev.readthedocs.io/en/develop/manual_testing.html#accessibility-a11y-testing)
- [ ] External dependencies files were updated (`yarn` and `pip`)
- [ ] Documentation is updated
- [ ] Link to diff of internal dependency change is included
- [ ] CHANGELOG.rst is updated for high-level changes
- [ ] Contributor is in AUTHORS.rst

### CODE REVIEW

File: kolibri/plugins/learn/assets/src/views/search-box/index.vue [hunk 1]
```diff
@@ -132,10 +133,15 @@
     &::placeholder
       color: $core-text-annotation
 
+    &::-ms-clear
+      display: none
```
Comment (indirectlylit) [inline kolibri/plugins/learn/assets/src/views/search-box/index.vue]: mind adding a code comment explaining what this does?

Comment (christianmemije) [reply kolibri/plugins/learn/assets/src/views/search-box/index.vue]: Comment added :+1:
