### PR TITLE
Fix missing device name in SelectDeviceForm

### LINKED ISSUE #12896: 0.18 - Select device modal - The device name is not displayed
## Observed behavior
Observed some regressions on that modal, namely the device name is not automatically displayed and there's a scroll-bar:

Image

If I manually add the device, then the device name is shown correctly:

Image

## Expected behavior

Correctly displayed device name and no scroll-bar when it's not necessary

## Steps to reproduce the issue

1. Install the build asset from https://github.com/learningequality/kolibri/releases/tag/v0.18.0-alpha0
2. Attempt to import a facility while going through the Setup Wizard or at Device > Facilities

## Usage Details
https://github.com/learningequality/kolibri/releases/tag/v0.18.0-alpha0
Ubuntu 22  - Chrome

### PR DESCRIPTION
**Pull request by AlexVelezLl**
## Summary

* In the `SelectDeviceForm` component we were still using the depecrated `device.dynamic`  property to determine if the devices were dynamic or not. This PR updates this to use the new field `location_type`.
* Fixed vertical scrollbar being shown although it was not needed.

## References
Closes #12896.

## Reviewer guidance
Follow instructions in #12896 and check that devices names are present in the modal.

### CODE REVIEW

File: packages/kolibri-common/components/syncComponentSet/SelectDeviceModalGroup/SelectDeviceForm.vue [hunk 1]
```diff
@@ -120,7 +120,7 @@
       </KFixedGrid>
     </template>
 
-    <KButtonGroup class="under-buttons">
+    <div class="under-buttons">
```
Comment (AlexVelezLl) [inline packages/kolibri-common/components/syncComponentSet/SelectDeviceModalGroup/SelectDeviceForm.vue:123]: KButtonGroup was introducing a weird `margin-bottom: -8px` that was making the scrollbar appear. And, as per [KButtonGroup docs](https://design-system.learningequality.org/kbuttongroup) this component is just used to provide buttons spacing.

**Review by pcenov — APPROVED** [review]
Hi @AlexVelezLl - I confirm that now the the device name is displayed correctly in the modal and I didn't observe any regressions while regression testing.

**Review by rtibbles — APPROVED** [review]
