### PR TITLE
Remove unnecessary uses of $computedClass

### LINKED ISSUE #8910: remove unnecessary uses of $computedClass
## Observed behavior

`$computedClass` is available for specifying colors in pseudo-elements such as `:hover` or `:focus`. For example, this is a necessary use:

```vue
<input :class="$computedClass({ '::placeholder': { color: $themeTokens.annotation } })" />
```

## Expected behavior

For most styles it is not necessary to use `$computedClass` and elements can be styled directly:

```vue
<div :style="{ color: $themeTokens.error }">This is an error</div>
```

In situations where the style gets complex, computed props can be used:

```vue
<div :style="labelStyle">This is an error</div>
```

```js
computed {
  labelStyle() {
    return { color: $themeTokens.textInverted, backgroundColor: $themeTokens.primaryDark };
  }
}
```

## User-facing consequences

For developers, code is more complex than it needs to be

## Steps to reproduce

Search codebase for `$computedClass` and identify unnecessary usages. For example:

https://github.com/learningequality/kolibri/blob/4c1eca4e4e68945a4733382100013c07baaebb9f/kolibri/plugins/user_auth/assets/src/views/AuthBase.vue#L23

https://github.com/learningequality/kolibri/blob/4c1eca4e4e68945a4733382100013c07baaebb9f/kolibri/plugins/user_auth/assets/src/views/AuthBase.vue#L45

https://github.com/learningequality/kolibri/blob/4c1eca4e4e68945a4733382100013c07baaebb9f/kolibri/core/assets/src/views/CoreMenu/CoreMenuOption.vue#L83-L88

https://github.com/learningequality/kolibri/blob/4c1eca4e4e68945a4733382100013c07baaebb9f/kolibri/plugins/coach/assets/src/views/plan/LessonResourceSelectionPage/SearchTools/LessonsSearchBox.vue#L73-L77

https://github.com/learningequality/kolibri/blob/4c1eca4e4e68945a4733382100013c07baaebb9f/kolibri/plugins/learn/assets/src/views/cards/BaseCard.vue#L116-L123

https://github.com/learningequality/kolibri/blob/4c1eca4e4e68945a4733382100013c07baaebb9f/kolibri/plugins/learn/assets/src/views/thumbnails/Thumbnail.vue#L51-L60

## Context

0.15.0

### PR DESCRIPTION
**Pull request by MisRob**
## Summary

Replaces `$computedClass` by computed styles whenever possible.

## References

Closes #8910

## Reviewer guidance

Can you see any style regressions in the following areas?

| Sign-in title | Sign-in title | Card progress | Menu options | Search box | Thumbnail |
| -------------- | ---------------- | ------------------ | ------------------ | --------------- | --------------- |
| AuthBase-title-01 | AuthBase-title-02 | BaseCard-label | CoreMenuOption-icons | LessonsSearchBox-border | Thumbnail |

## Testing checklist

- [x] Contributor has fully tested the PR manually
- [x] If there are any front-end changes, before/after screenshots are included
- [ ] Critical user journeys are covered by Gherkin stories
- [ ] Critical and brittle code paths are covered by unit tests

## PR process

- [x] PR has the correct target branch and milestone
- [x] PR has 'needs review' or 'work-in-progress' label
- [x] If PR is ready for review, a reviewer has been added. (Don't use 'Assignees')
- [ ] If this is an important user-facing change, PR or related issue has a 'changelog' label
- [ ] If this includes an internal dependency change, a link to the diff is provided

## Reviewer checklist

- Automated test coverage is satisfactory
- PR is fully functional
- PR has been tested for [accessibility regressions](http://kolibri-dev.readthedocs.io/en/develop/manual_testing.html#accessibility-a11y-testing)
- External dependency files were updated if necessary (`yarn` and `pip`)
- Documentation is updated
- Contributor is in AUTHORS.md

### CODE REVIEW

**Review by nucleogenesis — APPROVED** [review]
All looks good to me!

File: kolibri/plugins/learn/assets/src/views/thumbnails/Thumbnail.vue [hunk 1]
```diff
@@ -2,9 +2,11 @@
 
   <span
     class="thumbnail"
-    :class="thumbnailComputedClass"
+    :style="thumbnailStyles"
   >
-    <span class="icon">
+    <span
+      class="icon"
+    >
```
Comment (indirectlylit) [inline kolibri/plugins/learn/assets/src/views/thumbnails/Thumbnail.vue]: trivial cleanup

```suggestion
    <span class="icon">
```

File: kolibri/plugins/user_auth/assets/src/views/AuthBase.vue [hunk 2]
```diff
@@ -42,8 +41,7 @@
             <h1
               v-if="themeConfig.signIn.showTitle"
               class="kolibri-title"
-              :class="$computedClass({ color: $themeBrand.primary.v_300 })"
-              :style="themeConfig.signIn.titleStyle"
+              :style="[ themeConfig.signIn.titleStyle, { color: $themeBrand.primary.v_300 }]"
```
Comment (indirectlylit) [inline kolibri/plugins/user_auth/assets/src/views/AuthBase.vue]: I believe this (and the other instance on line 23) would need to be reversed to allow the theme to override the default style:

```suggestion
              :style="[ { color: $themeBrand.primary.v_300 }, themeConfig.signIn.titleStyle ]"
```

This is how it would have worked before since `style` takes precedence over `class`

**Review by indirectlylit — COMMENTED** [review]
quick note on ensuring theme overrides continue to work

**Comment by MisRob** [comment]
Thank you both, I've pushed all updates
