### PR TITLE
Fixes for exam log saving

### LINKED ISSUE #1246: After submitting the exam the learner is still allowed to start the exam.
## Summary
After submitting the exam the learner is still allowed to start the exam. Where as it should show the **Completed** and the learner should not be allowed to retake.

## System information

 - Version: Kolibri 0.4.0aplha2
 - Operating system: Ubuntu 14.04 LTS
 - Browser: Chrome browser and Firefox

## How to reproduce

1. Login as a learner
2. Start giving an exam.
3. Enter all the answers.
4. Click on submit exam.
5. Ideally the learner should be given completed exam status.

## Screenshots
Before Exam
before

mid

After Exam
after

### LINKED ISSUE #1340: coach exam report doesn't reflect actual status
I completed an exam, but it still shows it as 'in progress' with only one question answered:

image

### LINKED ISSUE #1343: On reviewing the previous questions after entering the answers, the answers disappear for exam.
## Summary
On reviewing the previous questions after entering their answers, the answers disappears for those questions that a user is reviewing.

## System information
 - Version: Kolibri 0.4.0alpha5
 - Operating system: Ubuntu 14.04 LTS
 - Browser: Chrome browser and Firefox

## How to reproduce

1. Login as learner.
2. Click on Exams tab and select any exam.
3. Attempt all questions.
4. Go back and start reviewing each questions.

**Actual results:**
 The answers starts disappearing and the question highlighter on the left also disappears as you continue to review.

**Expected results:**
The previous recorded answers should be present and the question highlighter should be purple.

## Screenshots
Attempted all the questions:
attempted all question answer_1

Start reviewing the questions from the beginning:
(The answers starts disappearing with the question highlighter) 
attempted all question answer_2

### PR DESCRIPTION
**Pull request by rtibbles**
## Summary

Updates ExamLogSerializer to properly update the model.
Updates frontend to properly parse exam data for reports.
Waits for API attempt update before navigation on learner exam page.

Fixes #1246, resolves #1340, and closes #1343.

### CODE REVIEW

File: kolibri/plugins/coach/assets/src/views/exam-report-detail-page/index.vue [hunk 1]
```diff
@@ -10,8 +10,8 @@
           :contentName="exam.title"
           :userName="userName"
           :questions="examAttempts"
-          :completionTimeStamp="completionTimeStamp"
-          :completed="exam.closed"/>
+          :completionTimestamp="new Date(completionTimestamp)"
```
Comment (DXCanas) [inline kolibri/plugins/coach/assets/src/views/exam-report-detail-page/index.vue:13]: Might be better to set an explicit property in the pageState?

File: kolibri/plugins/coach/assets/src/views/exam-report-detail-page/page-status.vue [hunk 2]
```diff
@@ -19,12 +19,18 @@
...
+        <span v-if="completed">
+          <strong> {{ $tr('completed') }} </strong>
+          <br />
+          <elapsed-time :date="completionTimestamp"/>
+        </span>
+        <span v-else-if="completed !== null">
+          <strong> {{ $tr('inProgress') }} </strong>
+        </span>
+        <span v-else>
+          <strong> {{ $tr('notStarted') }} </strong>
```
Comment (DXCanas) [inline kolibri/plugins/coach/assets/src/views/exam-report-detail-page/page-status.vue:32]: Nice

File: kolibri/plugins/learn/assets/src/state/actions.js [hunk 3]
```diff
@@ -706,7 +706,7 @@ function setAndSaveCurrentExamAttemptLog(store, contentId, itemId, currentAttemp
 }
 
 function closeExam(store) {
```
Comment (DXCanas) [inline kolibri/plugins/learn/assets/src/state/actions.js:708]: This function is only ever used here https://github.com/learningequality/kolibri/blob/develop/kolibri/plugins/learn/assets/src/views/exam-page/index.vue#L153

Maybe stop returning a promise and redirect from here?

side note: how was that line ^ working when we weren't returning a promise? What was the `thenable`?

File: kolibri/plugins/learn/assets/src/state/actions.js [hunk 4]
```diff
@@ -706,7 +706,7 @@ function setAndSaveCurrentExamAttemptLog(store, contentId, itemId, currentAttemp
...
-  const examLog = store.state.examLog;
+  const examLog = Object.assign({}, store.state.examLog);
```
Comment (DXCanas) [inline kolibri/plugins/learn/assets/src/state/actions.js:709]: Also, was manipulating the pageState directly causing any of the issues? Or are we doing this just cause

File: kolibri/plugins/coach/assets/src/views/exam-report-detail-page/page-status.vue (hunk 2 above)
Comment (rtibbles) [reply kolibri/plugins/coach/assets/src/views/exam-report-detail-page/page-status.vue:32]: copied from yours....

File: kolibri/plugins/learn/assets/src/state/actions.js (hunk 3 above)
Comment (rtibbles) [reply kolibri/plugins/learn/assets/src/state/actions.js:708]: I prefer to leave the state modification in the action for now, and routing the component, but I think it's a matter of taste.

The above one was not working before :)

File: kolibri/plugins/learn/assets/src/state/actions.js (hunk 4 above)
Comment (rtibbles) [reply kolibri/plugins/learn/assets/src/state/actions.js:709]: I don't think it was, but we shouldn't do it!

File: kolibri/plugins/coach/assets/src/views/exam-report-detail-page/page-status.vue (hunk 2 above)
Comment (DXCanas) [reply kolibri/plugins/coach/assets/src/views/exam-report-detail-page/page-status.vue:32]: ... I forgot
