### PR TITLE
Second batch of string corrections

### LINKED ISSUE #7647: When the user clicks the "go back" button while creating a quiz, it takes them back too far
### Observed behavior

When the user clicks the "go back" button while creating a quiz, it does not take them to the previous screen, but instead takes them to the quizzes tab on the lessons page.

Screen recording:

https://drive.google.com/file/d/1JnKsjm7k36cpDcvAL2aHb7oYcj7vl5f0/view

…

### Expected behavior

When the user clicks the "go back" button, they will likely expect to be taken to the previous screen (following the breadcrumbs seen under the search bar.)

Note: This isn't in the gherkin scenarios, and I'm not sure if it's intentional or not. But it results in a frustrating user experience.

…

### User-facing consequences

A user may lose their work by clicking the "go back" button intending to see the previous page. 
…

### Errors and logs

N/A
…

### Steps to reproduce

1. Open Kolibiri desktop app and log in to Coach account
2. Click on the "Plan" tab at the top of the page.
3. Click on the "Quizzes" tab
4. Click the "New Quiz" button
5. Click on a channel.
6. Click on a topic. 
7. Click on a subtopic (if applicable). 
8. Click on an exercise (if applicable). 
9. Observe the breadcrumbs under the search bar indicating the channel, the chosen topic, subtopic(s), and exercise. 
10. Click the "go back" button.
11. Observe that the user is returned to the "Quizzes" tab on the "Plan" page.

…

### Context

macOS Catalina 12.15.7 - Kolibri version 0.14
…

### LINKED ISSUE #8392: incorrect message shown to learner with import permission
## Observed behavior

"As an administrator..." shown to learner

image

## Expected behavior

messaging appropriate for any user with content management permission

## User-facing consequences

confusing messaging

## Steps to reproduce

import a single learner on a SOUD

## Context

latest `develop`

### PR DESCRIPTION
**Pull request by radinamatic**
## Summary
More string corrections and improvements (reducing the duplicates, etc).

## References
Fixes #8392
Fixes #7647
[Slack convo](https://learningequality.slack.com/archives/C0LKG14NL/p1630943526007200?thread_ts=1630682232.006200&cid=C0LKG14NL)

## Reviewer guidance

----

## Testing checklist

- [x] Contributor has fully tested the PR manually
- [ ] If there are any front-end changes, before/after screenshots are included
- [ ] Critical user journeys are covered by Gherkin stories
- [ ] Critical and brittle code paths are covered by unit tests

## PR process

- [x] PR has the correct target branch and milestone
- [x] PR has 'needs review' or 'work-in-progress' label
- [x] If PR is ready for review, a reviewer has been added. (Don't use 'Assignees')
- [ ] If this is an important user-facing change, PR or related issue has a 'changelog' label
- [ ] If this includes an internal dependency change, a link to the diff is provided

## Reviewer checklist

- Automated test coverage is satisfactory
- PR is fully functional
- PR has been tested for [accessibility regressions](http://kolibri-dev.readthedocs.io/en/develop/manual_testing.html#accessibility-a11y-testing)
- External dependency files were updated if necessary (`yarn` and `pip`)
- Documentation is updated
- Contributor is in AUTHORS.md

### CODE REVIEW

**Comment by pcenov** [comment]
Here's a screenshot showing what the learner is seeing after playing through this scenario:
1. Setup a full device
2. Setup a learn-only device and import a learner
3. Don't import any channels from the full device
4. Go to the Learn page and observe the strings displayed under the 'No resources available' heading?

**Comment by radinamatic** [comment]
Thank you for testing @pcenov!

@jtamiace The way conditionals are set up currently, users who can manage content (which includes imported learners on Learn-only devices) in above workflow will see just the link `Import channels to your device`, while those who do not manage content will just see the `Ask your coaches or admins for assistance` phrase under the **No resources available** heading (and no link). Are we Ok with presenting just that, or we need to change the condition so learners on Learn-only devices can see both (as proposed in #8308)?

**Comment by jtamiace** [comment]
I think it's sufficient as is, but adding in the condition for the `Ask your coaches or admins for assistance` phrase could be a nice to have. Not at all blocking if the condition can't be added.

File: kolibri/core/assets/src/mixins/commonCoreStrings.js [hunk 1]
```diff
@@ -426,10 +449,6 @@ export const coreStrings = createTranslator('CommonCoreStrings', {
     message: 'Female',
     context: "Female is an option in the 'Gender' drop down menu on the 'Create new user' page.",
   },
-  genderOptionOther: {
```
Comment (radinamatic) [inline kolibri/core/assets/src/mixins/commonCoreStrings.js:429]: String replaced with `Not specified`.

File: kolibri/plugins/coach/assets/src/csv/fields.js [hunk 2]
```diff
@@ -62,7 +62,7 @@ function padTime(interval) {
 export function avgScore(quiz = false) {
   return [
     {
-      name: coachStrings.$tr(quiz ? 'avgQuizScoreLabel' : 'avgScoreLabel'),
```
Comment (radinamatic) [inline kolibri/plugins/coach/assets/src/csv/fields.js:65]: @jredrejo No errors found in my testing, could you confirm that this edit is kosher? Thank you!

File: kolibri/plugins/coach/assets/src/views/TopNavbar.vue [hunk 3]
```diff
@@ -2,7 +2,7 @@
 
   <Navbar v-if="classId">
     <NavbarLink
-      :title="$tr('home')"
```
Comment (radinamatic) [inline kolibri/plugins/coach/assets/src/views/TopNavbar.vue:5]: `Class home` is now in the `commonCoreStrings`.

File: kolibri/plugins/coach/assets/src/views/common/LessonStatus.vue [hunk 4]
```diff
@@ -129,13 +129,6 @@
         });
       },
     },
-    $trs: {
```
Comment (radinamatic) [inline kolibri/plugins/coach/assets/src/views/common/LessonStatus.vue:132]: `Visible to learners` is now in the `commonCoachStrings`.

File: kolibri/plugins/coach/assets/src/views/common/commonCoachStrings.js [hunk 5]
```diff
@@ -217,7 +212,6 @@ const coachStrings = createTranslator('CommonCoachStrings', {
     context:
       "Coaches can choose between 'Randomized' and 'Fixed' question order when they create quizzes.\n\nThis text is a description of the 'Randomized' question order.",
   },
-  overallLabel: 'Overall',
```
Comment (radinamatic) [inline kolibri/plugins/coach/assets/src/views/common/commonCoachStrings.js:220]: String used in old designs, [not useful anymore](https://learningequality.slack.com/archives/C0LKG14NL/p1631145468008100).

File: kolibri/plugins/coach/assets/src/views/plan/CreateExamPage/CreateExamPreview.vue [hunk 6]
```diff
@@ -103,7 +103,7 @@
         <KButtonGroup>
           <KRouterLink
             appearance="flat-button"
-            :text="coreString('goBackAction')"
```
Comment (radinamatic) [inline kolibri/plugins/coach/assets/src/views/plan/CreateExamPage/CreateExamPreview.vue:106]: Ref: https://github.com/learningequality/kolibri/issues/7647

File: kolibri/plugins/coach/assets/src/views/plan/CreateExamPage/index.vue [hunk 7]
```diff
@@ -129,11 +129,6 @@
       </BottomAppBar>
       <BottomAppBar v-else>
         <KButtonGroup>
-          <KRouterLink
```
Comment (radinamatic) [inline kolibri/plugins/coach/assets/src/views/plan/CreateExamPage/index.vue:162]: Ref: https://github.com/learningequality/kolibri/issues/7647

File: kolibri/plugins/facility/assets/src/views/ClassEditPage/index.vue [hunk 8]
```diff
@@ -17,7 +17,6 @@
         :text="$tr('renameButtonLabel')"
         appearance="basic-link"
         :primary="true"
-        :ariaLabel="$tr('edit')"
```
Comment (radinamatic) [inline kolibri/plugins/facility/assets/src/views/ClassEditPage/index.vue:20]: Links do not need `aria-label`.

File: kolibri/plugins/facility/assets/src/views/ClassEditPage/index.vue [hunk 9]
```diff
@@ -198,12 +197,11 @@
         context:
           'This text displays in the edit class page if there are no learners enrolled in a class.',
       },
-      edit: 'Edit class name',
       documentTitle: 'Edit Class',
       renameButtonLabel: {
-        message: 'Edit',
```
Comment (radinamatic) [inline kolibri/plugins/facility/assets/src/views/ClassEditPage/index.vue:207]: Changed for consistency, since the modal that opens says `Rename class`.

File: kolibri/plugins/facility/assets/src/views/CsvInfoModal.vue [hunk 10]
```diff
@@ -314,7 +314,6 @@
       },
       /* eslint-disable kolibri/vue-no-unused-translations */
       // stub out some extra strings
```
Comment (radinamatic) [inline kolibri/plugins/facility/assets/src/views/CsvInfoModal.vue]: @jredrejo Let me know if any of these other _stubbed_ strings can be safely deleted at this point.

File: kolibri/plugins/facility/assets/src/views/FacilityConfigPage/index.vue [hunk 11]
```diff
@@ -261,7 +261,6 @@
         message: 'Allow learners to create accounts',
         context: "Option on 'Facility settings' page.",
       },
-      learnerCanLoginWithNoPassword: 'Allow learners to sign in with no password',
```
Comment (radinamatic) [inline kolibri/plugins/facility/assets/src/views/FacilityConfigPage/index.vue:264]: This option is in Device Settings page.

File: kolibri/plugins/facility/assets/src/views/FacilityConfigPage/index.vue [hunk 12]
```diff
@@ -291,7 +289,7 @@
         context: 'Button that resets the facility to its default settings.',
       },
       documentTitle: {
-        message: 'Configure Facility',
```
Comment (radinamatic) [inline kolibri/plugins/facility/assets/src/views/FacilityConfigPage/index.vue:294]: Changed to be consistent with the main heading.

File: kolibri/plugins/facility/assets/src/views/ManageClassPage/index.vue [hunk 13]
```diff
@@ -42,7 +42,7 @@
         <th>{{ coreString('learnersLabel') }}</th>
         <th>
           <span class="visuallyhidden">
-            {{ $tr('actions') }}
```
Comment (radinamatic) [inline kolibri/plugins/facility/assets/src/views/ManageClassPage/index.vue:45]: `Actions` is now a `commonCoreString`.

File: kolibri/plugins/facility/assets/src/views/UserCreatePage.vue [hunk 14]
```diff
@@ -48,14 +48,14 @@
             v-model="classCoachIsSelected"
             :disabled="busy"
             :label="coreString('classCoachLabel')"
-            :description="$tr('classCoachDescription')"
```
Comment (radinamatic) [inline kolibri/plugins/facility/assets/src/views/UserCreatePage.vue:51]: Moved to `commonCoreString`.

File: kolibri/plugins/facility/assets/src/views/UserPage/__test__/UserPage.spec.js [hunk 15]
```diff
@@ -31,11 +31,10 @@ describe('UserPage component', () => {
     });
 
     const testCases = [
-      ['learner', 'No learners exist'],
```
Comment (radinamatic) [inline kolibri/plugins/facility/assets/src/views/UserPage/__test__/UserPage.spec.js:34]: This wording always steered a sensation of dread in me... 😨

File: kolibri/plugins/learn/assets/src/views/ContentUnavailablePage.vue [hunk 16]
```diff
@@ -47,11 +47,11 @@
           'Message displayed when there are no learning resources available for the learner to view.',
       },
       adminLink: {
-        message: 'As an administrator, you can import channels',
```
Comment (radinamatic) [inline kolibri/plugins/learn/assets/src/views/ContentUnavailablePage.vue:50]: Ref: https://github.com/learningequality/kolibri/issues/8392

File: kolibri/plugins/learn/assets/src/views/LearningActivityBar.vue [hunk 17]
```diff
@@ -269,7 +269,7 @@
     $trs: {
       goBack: 'Go back',
       moreOptions: 'More options',
-      viewLessonPlan: 'View lesson plan',
```
Comment (radinamatic) [inline kolibri/plugins/learn/assets/src/views/LearningActivityBar.vue]: Ref: [Slack convo](https://learningequality.slack.com/archives/C0LKG14NL/p1630943526007200?thread_ts=1630682232.006200&cid=C0LKG14NL)

File: kolibri/plugins/learn/assets/src/views/classes/LessonPlaylistPage.vue [hunk 18]
```diff
@@ -52,20 +52,22 @@
...
   import { getContentNodeThumbnail } from 'kolibri.utils.contentNode';
   import ContentCard from '../ContentCard';
+  import { coachStringsMixin } from '../../../../../coach/assets/src/views/common/commonCoachStrings';
   import { lessonResourceViewerLink } from './classPageLinks';
 
   export default {
     name: 'LessonPlaylistPage',
     metaInfo() {
       return {
-        title: this.$tr('documentTitle'),
```
Comment (radinamatic) [inline kolibri/plugins/learn/assets/src/views/classes/LessonPlaylistPage.vue:61]: @indirectlylit Did we have guidelines for combinations of user-generated and our strings?

File: kolibri/plugins/media_player/assets/src/views/MediaPlayerCaptions/TranscriptMenuItem.vue [hunk 19]
```diff
@@ -3,7 +3,7 @@
   <li class="vjs-menu-item" role="menuitem">
     <KCheckbox
       ref="kCheckbox"
-      :label="$tr('transcript')"
```
Comment (radinamatic) [inline kolibri/plugins/media_player/assets/src/views/MediaPlayerCaptions/TranscriptMenuItem.vue:6]: `Transcript` is now in `commonCoreStrings`.

File: kolibri/plugins/coach/assets/src/csv/fields.js (hunk 2 above)
Comment (radinamatic) [reply kolibri/plugins/coach/assets/src/csv/fields.js:65]: The point was to unify `Average quiz score` and `Average score` (see below): they were used in several places interchangeably, and only quizzes can have scores, so the word `quiz` was redundant. 

Table column header in printed reports generally use just the word `Score`, so no formatting should be affected by this change.

File: kolibri/plugins/facility/assets/src/views/CsvInfoModal.vue (hunk 10 above)
Comment (jredrejo) [reply kolibri/plugins/facility/assets/src/views/CsvInfoModal.vue]: sorry, I'm not sure if I understand your question. For this one, yes, it can be deleted, but I don't know how to detect all of them

File: kolibri/plugins/facility/assets/src/views/FacilityConfigPage/index.vue (hunk 11 above)
Comment (jredrejo) [reply kolibri/plugins/facility/assets/src/views/FacilityConfigPage/index.vue:264]: it's not used in the code

**Review by jredrejo — COMMENTED** [review]
@radinamatic  I don't see any string related to the setup wizard, is it because they all were included in the first batch?

**Comment by radinamatic** [comment]
> I don't see any string related to the setup wizard, is it because they all were included in the first batch?

@jredrejo Setup wizard strings were reviewed and merged some time ago, so they could be translated for S2S installer.

File: kolibri/plugins/facility/assets/src/views/FacilityConfigPage/index.vue (hunk 11 above)
Comment (radinamatic) [reply kolibri/plugins/facility/assets/src/views/FacilityConfigPage/index.vue:264]: Perfect, safe to delete then! 👍🏽

File: kolibri/plugins/facility/assets/src/views/CsvInfoModal.vue (hunk 10 above)
Comment (radinamatic) [reply kolibri/plugins/facility/assets/src/views/CsvInfoModal.vue]: Ok, so `downloadSample` is safe to delete, and I will do one more search to see if  `exampleUser`, `exampleUsername` and `exampleClass` are used elsewhere. 👍🏽

Comment (jredrejo) [reply kolibri/plugins/facility/assets/src/views/CsvInfoModal.vue]: Those three `example*` are not use anywhere , it's safe to delete them

Comment (radinamatic) [reply kolibri/plugins/facility/assets/src/views/CsvInfoModal.vue]: Yey, thank you, three more unused strings out! 💥

File: kolibri/plugins/learn/assets/src/views/classes/LessonPlaylistPage.vue (hunk 18 above)
Comment (indirectlylit) [reply kolibri/plugins/learn/assets/src/views/classes/LessonPlaylistPage.vue:61]: When strings are used in a phrase, they [should be wrapped](https://design-system.learningequality.org/writing/#notes) in 'single quotes'.

```
Would you like to delete the lesson '{lesson_name}'?
```

If a user-generated string is being labeled, I think colons are more typical than dashes:

```
Lesson: {lesson_name}
```

If this is being used to show a page hierarchy, we do concatenate with dashes - for example using the dash-separated pair (which behaves correctly in RTL):

https://github.com/learningequality/kolibri/blob/3ffe703e46aa952bcacbc7b95b3169e1f9a94419/kolibri/core/assets/src/mixins/commonCoreStrings.js#L393-L396

Or programmatic concatenation (which will not behave correctly in RTL):

https://github.com/learningequality/kolibri/blob/60cd4eb6338bef0151fbc7739ee0641049f07d76/kolibri/plugins/coach/assets/src/views/common.js#L42-L80

This relates to the [thread started in Slack](https://learningequality.slack.com/archives/C59J8FEPN/p1631207348030200) where @rtibbles suggested looking at [`Intl.ListFormat`](https://formatjs.io/docs/polyfills/intl-listformat/)

Comment (radinamatic) [reply kolibri/plugins/learn/assets/src/views/classes/LessonPlaylistPage.vue:61]: Thank you! My idea was to use this string for the page title, so I was thinking of some hierarchy... However, since we decided with @rtibbles to hold off on working on #8417 for 0.15, we can't have the programmatic concatenation, yet.

So let's settle on the simplest solution for the moment:

`title: this.currentLesson.title,`

File: kolibri/plugins/coach/assets/src/csv/fields.js [hunk 20]
```diff
@@ -62,7 +62,7 @@ function padTime(interval) {
...
+      name: coachStrings.$tr(quiz ? 'avgScoreLabel' : 'avgScoreLabel'),
```
Comment (rtibbles) [inline kolibri/plugins/coach/assets/src/csv/fields.js]:
```suggestion
      name: coachStrings.$tr('avgScoreLabel'),
```

**Review by rtibbles — APPROVED** [review]
Looks good, one cleanup.

File: kolibri/plugins/coach/assets/src/csv/fields.js [hunk 21]
```diff
@@ -62,7 +62,7 @@ function padTime(interval) {
 export function avgScore(quiz = false) {
   return [
     {
-      name: coachStrings.$tr(quiz ? 'avgScoreLabel' : 'avgScoreLabel'),
```
Comment (radinamatic) [inline kolibri/plugins/coach/assets/src/csv/fields.js]: Thank you, I had an inkling there was a better way to do that!
