### PR TITLE
Adjusting scroll behavior in content card when description is long.

### LINKED ISSUE #3281: thumbnail scrolls inside of card
### Observed behavior

the thumbnail and content icon scroll inside the card

image

### Expected behavior

Only the text scrolls, and the thumbnail stays fixed

### User-facing consequences

not much, but layout looks a bit broken

### Context

0.8

-----

cc @DXCanas @jonboiser

### PR DESCRIPTION
**Pull request by DXCanas**
### Summary

Could have sworn I submitted this PR last week
image

### References

resolves #3281 
----

### Contributor Checklist

- [x] PR has the correct target branch and milestone
- [x] PR has 'needs review' or 'work-in-progress' label
- [x] Contributor has fully tested the PR manually
- [x] Screenshots of any front-end changes are in the PR description
- [x] If PR is ready for review, a reviewer has been added. (Don't use 'Assignees')

### Reviewer Checklist

- [ ] Automated test coverage is satisfactory
- [ ] Reviewer has fully tested the PR manually
- [ ] PR has been tested for [accessibility regressions](http://kolibri-dev.readthedocs.io/en/develop/manual_testing.html#accessibility-a11y-testing)
- [ ] External dependencies files were updated (`yarn` and `pip`)
- [ ] Documentation is updated
- [ ] Link to diff of internal dependency change is included
- [ ] CHANGELOG.rst is updated for high-level changes
- [ ] Contributor is in AUTHORS.rst

### CODE REVIEW

File: kolibri/plugins/coach/assets/src/views/lessons/LessonResourceSelectionPage/content-card/index.vue [hunk 1]
```diff
@@ -1,34 +1,37 @@
...
+        :class="{'has-message': Boolean(message)}"
+        dir="auto"
+      >
+        {{ title }}
+      </h3>
       <div v-if="message" class="message">
         {{ message }}
       </div>
+      <p class="description">
+        <!-- eslint-disable -->
```
Comment (indirectlylit) [inline kolibri/plugins/coach/assets/src/views/lessons/LessonResourceSelectionPage/content-card/index.vue:24]: mind adding a comment explaining why eslint needed to be disabled?

File: kolibri/plugins/coach/assets/src/views/lessons/LessonResourceSelectionPage/content-card/index.vue [hunk 2]
```diff
@@ -144,13 +144,28 @@
 
   .text
     color: $core-text-default
-    height: 100%
+    position: absolute
+    top: 0
+    bottom: 0
+    left: $thumb-width
+    width: 'calc(100% - %s)' % $thumb-width // stylus exlusive
```
Comment (indirectlylit) [inline kolibri/plugins/coach/assets/src/views/lessons/LessonResourceSelectionPage/content-card/index.vue:151]: a comment describing what this does might be helpful
