### PR TITLE
Try to prevent accessing objects from undefined content objects in contentMap

### LINKED ISSUE #6552: Unable to access Learners tab in Coach > Reports
### Observed behavior

When in Coach > Reports, and after clicking the "Learners" subtab, the page goes blank

learners

### Errors and logs

Screen Shot 2020-02-13 at 11 28 33 AM

### Context

http://kolibribeta.learningequality.org/en/coach/#/f6e7f562bb0ea654340c726e1f81bbe9/reports/quizzes
Kolibri 0.13.1b2
MacOS Mojave
Chrome

### PR DESCRIPTION
**Pull request by jonboiser**
### Summary

Replaces a potentially unsafe object access `this.contentMap[id].kind` in various page (see screen shot for which files this happens).

Screen Shot 2020-02-13 at 12 21 34 PM

Fixes #6552 

### Reviewer guidance
In the code,

1. make sure there were no typos
1. make sure commonCoach mixin is in all the components

I'm not sure how to reproduce this. It's possible, for the Kolibribeta server, the lesson that causes this breakage was never "cleaned" up by the fix implemented in #5140 because the channel was deleted before that PR was merged.

For manual testing, you can manually add bad ids into the code and confirm that the page still works, example: in LearnerListPage.vue.

```diff
      exercisesCompleted(contentStatuses) {
        const statuses = contentStatuses.filter(
          status =>
-            this.contentIdIsForExercise(status.content_id) &&
+            this.contentIdIsForExercise(status.content_id + "!") &&
            status.status === this.STATUSES.completed
        );
        return statuses.length;
      },

```

### References

…

----

### Contributor Checklist

PR process:

- [x] PR has the correct target branch and milestone
- [x] PR has 'needs review' or 'work-in-progress' label
- [x] If PR is ready for review, a reviewer has been added. (Don't use 'Assignees')
- [ ] If this is an important user-facing change, PR or related issue has a 'changelog' label
- [ ] If this includes an internal dependency change, a link to the diff is provided

Testing:

- [ ] Contributor has fully tested the PR manually
- [ ] If there are any front-end changes, before/after screenshots are included
- [ ] Critical user journeys are covered by Gherkin stories
- [ ] Critical and brittle code paths are covered by unit tests

### Reviewer Checklist

- Automated test coverage is satisfactory
- PR is fully functional
- PR has been tested for [accessibility regressions](http://kolibri-dev.readthedocs.io/en/develop/manual_testing.html#accessibility-a11y-testing)
- External dependency files were updated if necessary (`yarn` and `pip`)
- Documentation is updated
- Contributor is in AUTHORS.md

### CODE REVIEW

File: kolibri/plugins/coach/assets/src/views/common.js [hunk 1]
```diff
@@ -219,6 +220,10 @@ export default {
     },
   },
   methods: {
+    // This is a safer way to get the content kind to quickly patch #6552
+    contentIdIsForExercise(contentId) {
+      return get(this.contentMap, [contentId, 'kind']) === 'exercise';
+    },
```
Comment (indirectlylit) [inline kolibri/plugins/coach/assets/src/views/common.js:226]: This works, but seems highly specific. Maybe a more generally useful function would be 

```javascript
    getContentKind(contentId) {
      return get(this.contentMap, [contentId, 'kind']);
    },
```

This will return `undefined` when the ID doesn't exist, and then below you can write e.g.

```javascript
this.getContentKind(status.content_id) === 'exercise' && //...
```

**Review by indirectlylit — COMMENTED** [review]
Besides the cases you found, I see a few other instances where we assume that the item exists:

```
Searching 2731 files for "contentMap\[.+?\]\." (regex, case sensitive)

/Users/d/Projects/le/k013x/kolibri/plugins/coach/assets/src/modules/exerciseDetail/handlers.js:
   39    // Passed in exerciseId is the content_id of the contentNode
   40    // Map this to the id of the content node to do this fetch
   41:   exerciseId = store.state.classSummary.contentMap[exerciseId].node_id;
   42    return ContentNodeResource.fetchModel({ id: exerciseId }).then(
   43      exercise => {

/Users/d/Projects/le/k013x/kolibri/plugins/coach/assets/src/modules/questionDetail/handlers.js:
   49      // Passed in exerciseId is the content_id of the contentNode
   50      // Map this to the id of the content node to do this fetch
   51:     exerciseNodeId = store.state.classSummary.contentMap[exerciseId].node_id;
   52      promise = Promise.resolve();
   53    }

/Users/d/Projects/le/k013x/kolibri/plugins/coach/assets/src/modules/questionList/actions.js:
   22      resource = ExerciseDifficulties;
   23      itemPromise = ContentNodeResource.fetchModel({
   24:       id: store.rootState.classSummary.contentMap[exerciseId].node_id,
   25      });
   26    }

/Users/d/Projects/le/k013x/kolibri/plugins/coach/assets/src/views/common.js:
   64            return classSummary.examMap[params.quizId].title;
   65          case 'EXERCISE_NAME':
   66:           return classSummary.contentMap[params.exerciseId].title;
   67          case 'RESOURCE_NAME':
   68:           return classSummary.contentMap[params.resourceId].title;
   69          default:
   70            return coachStrings.$tr(part);

5 matches across 4 files
```

File: kolibri/plugins/coach/assets/src/views/common.js (hunk 1 above)
Comment (jonboiser) [reply kolibri/plugins/coach/assets/src/views/common.js:226]: Yeah, it's pretty specific because the coach reports make a pretty fundamental divide between exercises and non-exercises.

**Comment by jonboiser** [comment]
I'm not sure if it's worth trying to fix the other possible `contentMap[X] = undefined` sites right now. I think we should maybe replace the contentMap with a different object like a function that can handle invalid IDs. Hopefully, since these handlers go to detail-type pages, these pages will be theoretically inaccessible if their underlying content is deleted.

**Review by indirectlylit — APPROVED** [review]
