### PR TITLE
learner name in title

### LINKED ISSUE #3307: In the Coach -> Learners view, when you have selected a learner, it does not show you which learner you are viewing data for
### Observed behavior
When clicking on a learner's name in the Coach -> Learners view, you can no longer see which learner you just selected.

image

### Expected behavior
We should see some indication of which learner's data we are currently looking at.

### User-facing consequences
Coach faces greater cognitive load by having to remember which learner they clicked on way back when.

### Steps to reproduce
* Have some learner data
* Go to Coach
* Click on 'Learners'
* Click on a Learner
* See a list of channels, but no learner name

### PR DESCRIPTION
**Pull request by indirectlylit**
### Summary

PR to add learner to title and remove the class drop-down.

This change should be a stop-gap until we have an opportunity to redesign the coach information architecture and navigation.

I have tested the PR, but it required changes in a few places and carries some risk of regression. I think we should discuss the trade-offs of this risk before merging in, and do a bit more regression testing.

| Before | After |
|--|--|
| image | image |
| image | image |
| image | image |

### Reviewer guidance

This could potentially have regressions in a range of report pages. Please check all report pages for issues.

### References

fixes #3307

----

### Contributor Checklist

- [x] PR has the correct target branch and milestone
- [x] PR has 'needs review' or 'work-in-progress' label
- [x] Contributor has fully tested the PR manually
- [x] Screenshots of any front-end changes are in the PR description
- [x] If PR is ready for review, a reviewer has been added. (Don't use 'Assignees')

### Reviewer Checklist

- [ ] Automated test coverage is satisfactory
- [ ] Reviewer has fully tested the PR manually
- [ ] PR has been tested for [accessibility regressions](http://kolibri-dev.readthedocs.io/en/develop/manual_testing.html#accessibility-a11y-testing)
- [ ] External dependencies files were updated (`yarn` and `pip`)
- [ ] Documentation is updated
- [ ] Link to diff of internal dependency change is included
- [ ] CHANGELOG.rst is updated for high-level changes
- [ ] Contributor is in AUTHORS.rst

### CODE REVIEW

File: kolibri/core/assets/src/views/buttons-and-links/k-button.vue [hunk 1]
```diff
@@ -6,9 +6,7 @@
     :type="type"
     :disabled="disabled"
     @click="handleClick"
-  >
-    {{ text }}
-  </button>
+  ><!-- no whitespace -->{{ text }}<!-- no whitespace --></button>
```
Comment (christianmemije) [inline kolibri/core/assets/src/views/buttons-and-links/k-button.vue:9]: Curious what was the reasoning behind this, since [this rule](https://github.com/learningequality/kolibri/blob/release-v0.8.x/frontend_build/src/webpack.config.base.js#L101) should be taking care of that. And I cannot see the whitespace in the buttons when I inspect the element in FF.

**Comment by christianmemije** [comment]
Having the username at the top, above the top-nav, does not quite make sense to me. It would make more sense to have `All learners - > little_bobby` under the Learners tab.

File: kolibri/plugins/coach/assets/src/views/index.vue [hunk 2]
```diff
@@ -31,6 +32,8 @@
 <script>
 
   import { PageNames } from '../constants';
+  import * as ReportConstants from '../reportConstants';
```
Comment (christianmemije) [inline kolibri/plugins/coach/assets/src/views/index.vue]: Can just import `UserScopes`?

**Comment by indirectlylit** [comment]
> For the last screen (bottom right), "some class" shouldn't be a hyperlink and should be styled the same way as "little_bobby" learner ID

Okay - I put that there as a link to go to the default root for class (learners) but agreed that it looks weird and they can just click the learners tab

File: kolibri/core/assets/src/views/buttons-and-links/k-button.vue (hunk 1 above)
Comment (indirectlylit) [reply kolibri/core/assets/src/views/buttons-and-links/k-button.vue:9]: I'm not sure, but I ran into a bug where there were underlined spaces around a link...

**Comment by indirectlylit** [comment]
> Having the username at the top, above the top-nav, does not quite make sense to me. It would make more sense to have All learners - > little_bobby under the Learners tab.

Agreed, this doesn't make sense. Just going based on this comment: https://github.com/learningequality/kolibri/issues/3307#issuecomment-371651689

**Comment by indirectlylit** [comment]
ready for another look

**Comment by indirectlylit** [comment]
self-merging
