### PR TITLE
IE is not a modern browser

### LINKED ISSUE #5939: All noto-full Non-Latin Families are downloaded on IE11
### Observed behavior

When viewing Kolibri on IE11, a large number of Noto Sans Families are downloaded, when only a subset should be downloaded.

log:

```
NFO     "GET /static/kolibri.core.default_frontend/kolibri.core.default_frontend-0.13.0.dev0%2Bgit.20190916195927.js HTTP/1.1" 200 1681183
INFO     "GET /static/assets/fonts/noto-full.en.modern.css?v=0.13.0.dev0+git.20190916195927 HTTP/1.1" 200 17848
INFO     "GET /static/assets/fonts/noto-full.NotoSans.700.woff HTTP/1.1" 200 433488
INFO     "GET /static/assets/fonts/noto-full.NotoSansArabic.400.woff HTTP/1.1" 200 163056
INFO     "GET /static/assets/fonts/noto-full.NotoSans.400.woff HTTP/1.1" 200 432828
INFO     "GET /static/assets/fonts/noto-full.NotoSansArabic.700.woff HTTP/1.1" 200 176396
INFO     "GET /static/assets/fonts/noto-full.NotoSansBengali.400.woff HTTP/1.1" 200 181168
INFO     "GET /static/assets/fonts/noto-full.NotoSansBengali.700.woff HTTP/1.1" 200 190484
INFO     "GET /static/assets/fonts/noto-full.NotoSansGujarati.400.woff HTTP/1.1" 200 186112
INFO     "GET /static/assets/fonts/noto-full.NotoSansGujarati.700.woff HTTP/1.1" 200 187244
INFO     "GET /static/assets/fonts/noto-full.NotoSansDevanagari.400.woff HTTP/1.1" 200 181776
INFO     "GET /static/assets/fonts/noto-full.NotoSansDevanagari.700.woff HTTP/1.1" 200 190804
INFO     "GET /static/assets/fonts/noto-full.NotoSansMyanmar.400.woff HTTP/1.1" 200 183340
INFO     "GET /static/assets/fonts/noto-full.NotoSansMyanmar.700.woff HTTP/1.1" 200 194876
INFO     "GET /static/assets/fonts/noto-full.NotoSansTelugu.400.woff HTTP/1.1" 200 170496
INFO     "GET /static/assets/fonts/noto-full.NotoSansTelugu.700.woff HTTP/1.1" 200 174208
INFO     "GET /static/assets/fonts/noto-full.NotoSansArmenian.400.woff HTTP/1.1" 200 28176
INFO     "GET /static/assets/fonts/noto-full.NotoSansArmenian.700.woff HTTP/1.1" 200 28340
INFO     "GET /static/assets/fonts/noto-full.NotoSansCanadianAboriginal.400.woff HTTP/1.1" 200 78960
INFO     "GET /static/assets/fonts/noto-full.NotoSansCanadianAboriginal.700.woff HTTP/1.1" 200 79944
INFO     "GET /static/assets/fonts/noto-full.NotoSansCham.400.woff HTTP/1.1" 200 28500
INFO     "GET /static/assets/fonts/noto-full.NotoSansCham.700.woff HTTP/1.1" 200 29184
INFO     "GET /static/assets/fonts/noto-full.NotoSansEthiopic.400.woff HTTP/1.1" 200 269988
INFO     "GET /static/assets/fonts/noto-full.NotoSansCherokee.400.woff HTTP/1.1" 200 90848
INFO     "GET /static/assets/fonts/noto-full.NotoSansCherokee.700.woff HTTP/1.1" 200 104848
INFO     "GET /static/assets/fonts/noto-full.NotoSansEthiopic.700.woff HTTP/1.1" 200 269096
INFO     "GET /static/assets/fonts/noto-full.NotoSansGeorgian.400.woff HTTP/1.1" 200 37332
INFO     "GET /static/assets/fonts/noto-full.NotoSansGeorgian.700.woff HTTP/1.1" 200 38536
INFO     "GET /static/assets/fonts/noto-full.NotoSansGurmukhi.400.woff HTTP/1.1" 200 52744
INFO     "GET /static/assets/fonts/noto-full.NotoSansKannada.700.woff HTTP/1.1" 200 121952
INFO     "GET /static/assets/fonts/noto-full.NotoSansHebrew.700.woff HTTP/1.1" 200 23876
INFO     "GET /static/assets/fonts/noto-full.NotoSansJavanese.700.woff HTTP/1.1" 200 114300
INFO     "GET /static/assets/fonts/noto-full.NotoSansGurmukhi.700.woff HTTP/1.1" 200 55064
INFO     "GET /static/assets/fonts/noto-full.NotoSansJavanese.400.woff HTTP/1.1" 200 121184
INFO     "GET /static/assets/fonts/noto-full.NotoSansHebrew.400.woff HTTP/1.1" 200 23544
INFO     "GET /static/assets/fonts/noto-full.NotoSansKannada.400.woff HTTP/1.1" 200 117668
INFO     "GET /static/assets/fonts/noto-full.NotoSansKhmer.400.woff HTTP/1.1" 200 125392
INFO     "GET /static/assets/fonts/noto-full.NotoSansKhmer.700.woff HTTP/1.1" 200 125628
INFO     "GET /static/assets/fonts/noto-full.NotoSansLao.700.woff HTTP/1.1" 200 31244
INFO     "GET /static/assets/fonts/noto-full.NotoSansLao.400.woff HTTP/1.1" 200 29916
INFO     "GET /static/assets/fonts/noto-full.NotoSansMalayalam.400.woff HTTP/1.1" 200 103456
INFO     "GET /static/assets/fonts/noto-full.NotoSansMalayalam.700.woff HTTP/1.1" 200 108868
INFO     "GET /static/assets/fonts/noto-full.NotoSansOriya.400.woff HTTP/1.1" 200 142616
INFO     "GET /static/assets/fonts/noto-full.NotoSansSinhala.400.woff HTTP/1.1" 200 296612
INFO     "GET /static/assets/fonts/noto-full.NotoSansOriya.700.woff HTTP/1.1" 200 137940
INFO     "GET /static/assets/fonts/noto-full.NotoSansSinhala.700.woff HTTP/1.1" 200 328332
INFO     "GET /static/assets/fonts/noto-full.NotoSansSymbols.400.woff HTTP/1.1" 200 232468
INFO     "GET /static/assets/fonts/noto-full.NotoSansSymbols.700.woff HTTP/1.1" 200 233360
INFO     "GET /static/assets/fonts/noto-full.NotoSansTamil.400.woff HTTP/1.1" 200 68416
INFO     "GET /static/assets/fonts/noto-full.NotoSansTamil.700.woff HTTP/1.1" 200 71480
INFO     "GET /static/assets/fonts/noto-full.NotoSansThaana.400.woff HTTP/1.1" 200 18000
INFO     "GET /static/assets/fonts/noto-full.NotoSansThaana.700.woff HTTP/1.1" 200 17812
INFO     "GET /static/assets/fonts/noto-full.NotoSansThai.400.woff HTTP/1.1" 200 35712
INFO     "GET /static/assets/fonts/noto-full.NotoSansThai.700.woff HTTP/1.1" 200 36640
INFO     "GET /static/assets/fonts/noto-full.NotoSansTibetan.400.woff HTTP/1.1" 200 689432
INFO     "GET /static/assets/fonts/noto-full.NotoSansTibetan.700.woff HTTP/1.1" 200 648320
```
### Expected behavior

Only the minimal set of noto sans families are downloaded.

### User-facing consequences

Extra font files are downloaded

### Errors and logs

…

### Steps to reproduce

Load Kolibri in an IE11 browser, like in browserstack. If you can view the logs, you will see something similar as above.

### Context

Kolibri 0.13.1

### PR DESCRIPTION
**Pull request by indirectlylit**
## Summary

The `passesRequirements` function was returning `true` because IE was not included in the requirements.

## References

fixes https://github.com/learningequality/kolibri/issues/5939

## Reviewer guidance

The behavior of `passesRequirements` was surprising at first, but it makes sense.

That said, the solution feels like a hack. Is there a better way?

----

## Testing checklist

- [x] Contributor has fully tested the PR manually
- [ ] If there are any front-end changes, before/after screenshots are included
- [ ] Critical user journeys are covered by Gherkin stories
- [ ] Critical and brittle code paths are covered by unit tests

## PR process

- [x] PR has the correct target branch and milestone
- [x] PR has 'needs review' or 'work-in-progress' label
- [x] If PR is ready for review, a reviewer has been added. (Don't use 'Assignees')
- [ ] If this is an important user-facing change, PR or related issue has a 'changelog' label
- [ ] If this includes an internal dependency change, a link to the diff is provided

## Reviewer checklist

- Automated test coverage is satisfactory
- PR is fully functional
- PR has been tested for [accessibility regressions](http://kolibri-dev.readthedocs.io/en/develop/manual_testing.html#accessibility-a11y-testing)
- External dependency files were updated if necessary (`yarn` and `pip`)
- Documentation is updated
- Contributor is in AUTHORS.md

### CODE REVIEW

File: kolibri/core/assets/src/utils/setupAndLoadFonts.js [hunk 1]
```diff
@@ -30,6 +30,9 @@ const modernFontBrowsers = {
     major: 11,
     minor: 4,
   },
+  IE: {
+    major: 100, // specify impossible IE version, forcing passesRequirements to fail
```
Comment (rtibbles) [inline kolibri/core/assets/src/utils/setupAndLoadFonts.js:34]: Hrm, maybe the alternative is to cause `passesRequirements` to return false as the `else` to this clause?
https://github.com/learningequality/kolibri/blob/release-v0.15.x/kolibri/core/assets/src/utils/browserInfo.js#L21

Comment (indirectlylit) [reply kolibri/core/assets/src/utils/setupAndLoadFonts.js:34]: that's what I did at first, until I read that the docstring which says

> It does this in a permissive way, whereby if no specification is made for a particular browser name, then it will return true.

Comment (rtibbles) [reply kolibri/core/assets/src/utils/setupAndLoadFonts.js:34]: Yeah, I think the guy who wrote might have meant it to, because of this use of the same function: https://github.com/learningequality/kolibri/blob/b87f9da274a6a9218419cf9f858be695aa04304a/kolibri/core/assets/src/utils/minimumBrowserRequirements.js#L15

Comment (indirectlylit) [reply kolibri/core/assets/src/utils/setupAndLoadFonts.js:34]: this makes sense to handle unknown or strange new browsers

Comment (rtibbles) [reply kolibri/core/assets/src/utils/setupAndLoadFonts.js:34]: I think this is probably fine for now, but we can update the behaviour of `passesRequirements` when we move to using this explicit allowed list of supported browsers: https://github.com/learningequality/kolibri/blob/release-v0.15.x/packages/browserslist-config-kolibri/index.js#L1

**Review by rtibbles — APPROVED** [review]

**Comment by indirectlylit** [comment]
@radinamatic would you mind verifying this fix for the IE font loading issue  #5939? It should be present in the latest force-pushed version of https://github.com/learningequality/kolibri/pull/8756

**Comment by radinamatic** [comment]
True, I can confirm in the build from this PR that non-Latin fonts are not loading anymore by default on every refresh, and all language labels are present in IE11.

Win7 (start)  Running  - Oracle VM VirtualBox_002


These issues were still extant in the latest build from #8756 that I tested yesterday, but I could repeat the test to be sure 👍🏽

**Comment by indirectlylit** [comment]
>  all language labels are present in IE11

nice! I did not expect that to be addressed yet 😅
