### PR TITLE
Fix inconsistent naming/terminology - users vs. learners #3021

### LINKED ISSUE #3021: Inconsistent naming/terminology - users vs. learners
### Observed behavior

Enroll users to a class: base page and modal mention `users` all over, just the button names `learners`.

selection_172

### Expected behavior

Role names in one same flow of steps should be consistent. 

### User-facing consequences

Inconsistency might create confusion for both Kolibri end users and translators.

### PR DESCRIPTION
**Pull request by christianmemije**
### Summary

Fix inconsistent naming/terminology - users vs. learners #3021

localhost_8000_facility_
localhost_8000_facility_ 1
localhost_8000_facility_ 2
localhost_8000_facility_ 3
localhost_8000_facility_ 4

### Reviewer guidance

View UI and make sure strings are correct.

### References

Fixes #3021 

----

### Contributor Checklist

- [x] PR has the correct target branch and milestone
- [x] PR has 'needs review' or 'work-in-progress' label
- [x] Contributor has fully tested the PR manually
- [x] Screenshots of any front-end changes are in the PR description
- [x] If PR is ready for review, a reviewer has been added. (Don't use 'Assignees')

### Reviewer Checklist

- [ ] Automated test coverage is satisfactory
- [ ] Reviewer has fully tested the PR manually
- [ ] PR has been tested for [accessibility regressions](http://kolibri-dev.readthedocs.io/en/develop/manual_testing.html#accessibility-a11y-testing)
- [ ] External dependencies files were updated (`yarn` and `pip`)
- [ ] Documentation is updated
- [ ] Link to diff of internal dependency change is included
- [ ] CHANGELOG.rst is updated for high-level changes
- [ ] Contributor is in AUTHORS.rst

### CODE REVIEW

File: kolibri/plugins/facility_management/assets/src/views/class-edit-page/index.vue [hunk 1]
```diff
@@ -118,15 +118,13 @@
...
-      tableTitle: 'Manage learners in this class',
-      searchText: 'Find a learner or coach...',
+      enrollUsers: 'Enroll users ',
+      tableTitle: 'Manage users in this class',
+      searchText: 'Find a user...',
       users: 'Users',
       fullName: 'Full name',
       username: 'Username',
       role: 'Role',
-      learner: 'Learner',
```
Comment (christianmemije) [inline kolibri/plugins/facility_management/assets/src/views/class-edit-page/index.vue:128]: These 2 strings were not being used anywhere.

File: kolibri/plugins/facility_management/assets/src/views/class-enroll-page/confirm-enrollment-modal.vue [hunk 2]
```diff
@@ -42,7 +42,7 @@
       confirmEnrollment: 'Confirm enrollment of selected users',
       areYouSure: 'Are you sure you want to enroll the following users into {className}?',
```
Comment (radinamatic) [inline kolibri/plugins/facility_management/assets/src/views/class-enroll-page/confirm-enrollment-modal.vue]: This would be an instance where the user-generated text (class name) should be [inside single quotes](https://github.com/learningequality/kolibri/issues/3021#issuecomment-367513435).

Does not fall strictly into the scope of this PR, but could be fixed easily. :slightly_smiling_face:

**Comment by christianmemije** [comment]
@radinamatic Updated!

localhost_8000_facility_ 5
