### PR TITLE
Remove class title in favour of class name in class copy form

### LINKED ISSUE #13559: Copy class - "Class title" should be renamed to "Class name"
❌ **This issue is not open for contribution. Visit <a href="https://learningequality.org/contributing-to-our-open-code-base/" target="_blank">Contributing guidelines</a>** to learn about the contributing process and how to find suitable issues.

## Observed behavior

When copying a class I noticed that the first field is called "Class title".

Image

## Expected behavior

The "Class title" field should be renamed to "Class name" for consistency with the "Create new class" and "Rename class" forms.
 
## Steps to reproduce the issue

1. Install the build from https://github.com/learningequality/kolibri/releases/tag/v0.19.0-alpha0
2. Go to Facility > Classes and try to copy a class

## Usage Details
https://github.com/learningequality/kolibri/releases/tag/v0.19.0-alpha0
Windows 11, Ubuntu 22, Mac OS 15.5  - Chrome, Firefox

### PR DESCRIPTION
**Pull request by AllanOXDi**
## Summary
This PR changes "Class title" to "Class name" in copy class sidepanel

#### Before
Screenshot 2025-08-04 at 22 19 06

#### After
Screenshot 2025-08-04 at 22 18 35

Closes #13559

## References
#13559

## Reviewer guidance
Go to Facility > Classes and try to copy a class

### CODE REVIEW

**Review by pcenov — APPROVED** [review]
Thanks @AllanOXDi - I confirm that "Class title" is changed to "Class name".

File: packages/kolibri-common/strings/bulkUserManagementStrings.js [hunk 1]
```diff
@@ -270,6 +270,10 @@ export const bulkUserManagementStrings = createTranslator('BulkUserManagementStr
     message: 'Class name already exists',
     context: 'Error message shown when trying to copy a class with a name that already exists',
   },
+  className: {
+    message: ' Class name',
```
Comment (LianaHarris360) [inline packages/kolibri-common/strings/bulkUserManagementStrings.js]: There's an extra space before Class that should be removed

File: packages/kolibri-common/strings/bulkUserManagementStrings.js [hunk 2]
```diff
@@ -270,6 +270,10 @@ export const bulkUserManagementStrings = createTranslator('BulkUserManagementStr
     message: 'Class name already exists',
     context: 'Error message shown when trying to copy a class with a name that already exists',
   },
+  className: {
```
Comment (AlexVelezLl) [inline packages/kolibri-common/strings/bulkUserManagementStrings.js]: Just fyi: There is already a class name string in the [commonCoreStrings module](https://github.com/learningequality/kolibri/blob/58e345439b496a851906c4ae782049955f6ffd59/packages/kolibri/uiText/commonCoreStrings.js#L273), so we should use that instead :)

**Review by AlexVelezLl — COMMENTED** [review]
lgtm!
