### PR TITLE
Lesson completion modal

### LINKED ISSUE #8749: When finishing a resource in a lesson, the completion modal does not move you on to the next item in the lesson
## Observed behavior
When finishing a resource in a lesson, the completion modal does not move you on to the next item in the lesson.

First it doesn't render the content, but when I refresh, it does.

## Expected behavior
Should just move the learner on to the next resource in the lesson.

### PR DESCRIPTION
**Pull request by rtibbles**
## Summary
* Updates completion modal to be context aware with a lesson prop
* Tweaks the lesson learner viewset in Learn to match the data returned by the learner classroom viewset
* Adds a fetchLesson method to the useLearnerResources composable and matches the behaviour there for reusing content node and progress data returned
* Conditionally loads either the next content if not in a lesson or the next content in a lesson if in a lesson
* Adds restrictions based on the no unassigned content device setting to prevent display of non-lesson next content and recommended content if the device setting is active
* Adds loading a loading state to the completion modal
* Updates data loading for the LearnImmersiveLayout component that is used by the AlsoInThis component to use the new fetchLesson composable method

## References
Fixes #8749

## Reviewer guidance
If engaging with a resource in a lesson, does the move on section take you to the next resource in a lesson?
lessonmoveon

If engaging with a resource in a lesson, and learners cannot engage with unassigned content, does it not show the recommended content section?
nounassignedmoveon

If using a slow connection (e.g. switching to Slow 3G on the network tab before completing the resource) does a loading state display?
completionmodalloading

Do the contents of the lesson properly display in the also in this side panel? (note that some links in there may still be broken, pending merge of #8754)
alsointhislesson

----

## Testing checklist

- [x] Contributor has fully tested the PR manually
- [x] If there are any front-end changes, before/after screenshots are included
- [ ] Critical user journeys are covered by Gherkin stories
- [ ] Critical and brittle code paths are covered by unit tests

## PR process

- [x] PR has the correct target branch and milestone
- [x] PR has 'needs review' or 'work-in-progress' label
- [x] If PR is ready for review, a reviewer has been added. (Don't use 'Assignees')
- [ ] If this is an important user-facing change, PR or related issue has a 'changelog' label
- [ ] If this includes an internal dependency change, a link to the diff is provided

## Reviewer checklist

- Automated test coverage is satisfactory
- PR is fully functional
- PR has been tested for [accessibility regressions](http://kolibri-dev.readthedocs.io/en/develop/manual_testing.html#accessibility-a11y-testing)
- External dependency files were updated if necessary (`yarn` and `pip`)
- Documentation is updated
- Contributor is in AUTHORS.md

### CODE REVIEW

**Comment by radinamatic** [comment]
Tested on EXE asset from this PR on Windows 7, and working well in both lessons and folders! 💯 

`Move on` in a lesson | `Move on` in a folder
--- | ---
move-on | Win7 (start)  Running  - Oracle VM VirtualBox_003

No recommendation for unassigned content | Next in lesson | Loading
--- | --- | ---
Win7 (start)  Running  - Oracle VM VirtualBox_004 | Win7 (start)  Running  - Oracle VM VirtualBox_005 | load2 </br> Seeing a lot of loaders, but not one in the completion modal 🤷🏽‍♀️ 


One hickup: when another resource is added to an active lesson, **Next in lesson** for learner displays the resources from the originating folder, and not those for the lesson itself.

Win7 (start)  Running  - Oracle VM VirtualBox_006

**Review by radinamatic — APPROVED** [review]
One hickup, but the original issue is solved, :shipit: 👏🏽!

File: kolibri/plugins/learn/assets/src/views/CompletionModal/index.vue [hunk 1]
```diff
@@ -472,4 +508,9 @@
     }
   }
 
+  .loader {
+    margin-top: 16px;
+    margin-bottom: 16px;
```
Comment (MisRob) [inline kolibri/plugins/learn/assets/src/views/CompletionModal/index.vue]: A minor note - are there designs for the loading state? I thought it could be nice to have more space below the loader. Right now it seems to be very close to the bottom border to me:
Screenshot from 2021-11-29 09-54-27

cc @jtamiace

**Review by MisRob — APPROVED** [review]
Thank you @rtibbles, code is looking good to me. I only added one note on design but it's nothing blocking.

File: kolibri/plugins/learn/assets/src/views/CompletionModal/index.vue (hunk 1 above)
Comment (rtibbles) [reply kolibri/plugins/learn/assets/src/views/CompletionModal/index.vue]: There was not a design for this - which I think was an oversight, happy to get some additional direction on its precise look and feel.

Comment (jtamiace) [reply kolibri/plugins/learn/assets/src/views/CompletionModal/index.vue]: Circular loader is the right component for this. A little more space would be nice - 56px both above and below?

Comment (rtibbles) [reply kolibri/plugins/learn/assets/src/views/CompletionModal/index.vue]: Screenshot from 2021-11-29 11-29-05

**Review by marcellamaki — APPROVED** [review]
