### PR TITLE
Make Plan > Group/Lesson look more like Report > Group/Lesson

### LINKED ISSUE #5089: On Profile page, there is no error when trying to change username to one that already is used
### Observed behavior
When facility Allow learners and coaches to edit their username is checked. Learner is able to change the username but when it change it with existing username, it must show a error.

### Expected behavior
It must show a error when we are changing username with existing username.

### Steps to reproduce
1. Login with learner.
2. Go to the profile.
3. Change the username with existing username and checked.

### Context
 * Kolibri version : Kolibri 0.12.0b4
 * Operating system : Ubuntu 14.04
 * Browser : Chrome

### Screenshots
When changing username with existing username, it must show a error. But here it is not showing any error.

### LINKED ISSUE #5143: Plan tab and Reports tab information architecture/page layout mismatch
### Observed behavior
Lesson page and quiz pages in the PLAN tab don't match the information architecture and page layout seen on their counterparts over in the REPORTS tab and in the mocks.

**(in the plan tab)**
screen shot 2019-02-22 at 4 04 06 pm

**(in the reports tab)**
screen shot 2019-02-22 at 4 12 51 pm

### Expected behavior
- The same above-the-fold page layout. See screenshot attached
screen shot 2019-02-22 at 4 10 17 pm

### User-facing consequences
- Lack of consistency between the information architecture of both tabs
- Looks like nothing changed/you're still on the same page after creating the details of a lesson
- Redundant information appearing twice, such as 'Plan your class' header and its following paragraph text

### Context
…

### LINKED ISSUE #5156: User menu label not automatically updated
### Observed behavior
After I updated the username of the admin account, the user menu label still the same. But when I refresh the page, The user menu will update.
### Expected behavior
It should update automatically. 

### User-facing consequences

…

### Errors and logs
gif-temp

### Steps to reproduce
* Log in as admin
* Navigate at the profile page
* Rename your  profile username and click the `save changes`
* See the user menu label
### Context

Tell us about your environment, including:
 * Kolibri version: 0.12.x-beta9
 * Operating system: macOS 10.13
 * Browser: Safari 11.0.3

### PR DESCRIPTION
**Pull request by jonboiser**
### Summary

1. Makes the layout of Plan > Group/Lesson look more like counterparts in Report
1. Removes the h1s in the Plan top-level pages (since the report counterparts don't have them)
1. Adds an empty state message to the ReportsGroupReportPage
1. Fixes #5156 
1. Fixes #5089
screen shot 2019-02-26 at 10 08 56 am
screen shot 2019-02-26 at 10 08 32 am

### Reviewer guidance

…

### References

Fixes #5143 

----

### Contributor Checklist

PR process:

- [ ] PR has the correct target branch and milestone
- [ ] PR has 'needs review' or 'work-in-progress' label
- [ ] If PR is ready for review, a reviewer has been added. (Don't use 'Assignees')
- [ ] If this is an important user-facing change, PR or related issue has a 'changelog' label
- [ ] If this includes an internal dependency change, a link to the diff is provided

Testing:

- [ ] Contributor has fully tested the PR manually
- [ ] If there are any front-end changes, before/after screenshots are included
- [ ] Critical user journeys are covered by Gherkin stories
- [ ] Critical and brittle code paths are covered by unit tests

### Reviewer Checklist

- Automated test coverage is satisfactory
- PR is fully functional
- PR has been tested for [accessibility regressions](http://kolibri-dev.readthedocs.io/en/develop/manual_testing.html#accessibility-a11y-testing)
- External dependency files were updated if necessary (`yarn` and `pip`)
- Documentation is updated
- Contributor is in AUTHORS.rst

### CODE REVIEW

File: kolibri/plugins/user/assets/src/modules/profile/actions.js [hunk 1]
```diff
@@ -36,7 +36,7 @@ export function updateUserProfile(store, { edits, session }) {
     exists: true,
   }).then(
     () => {
-      store.dispatch('getCurrentSession', true, { root: true });
+      store.commit('CORE_SET_SESSION', changedValues, { root: true });
```
Comment (rtibbles) [inline kolibri/plugins/user/assets/src/modules/profile/actions.js:39]: This looks right!

**Review by rtibbles — APPROVED** [review]
