### PR TITLE
Small tweaks to exam detail report

### LINKED ISSUE #1430: <Enhancement> The over all score displayed within the exam report for a learner shows in decimal
## Summary

<Enhancement> The over all score displayed within the exam report for a learner shows in decimal.

Instead the score could be in percentages.

## System information
 - Version: Kolibri 0.4.0alpha4
 - Operating system: Ubuntu 14.04 LTS
 - Browser: Chrome

## How to reproduce
1. Give an exam.
2. Open up the exam report. 
3. Observe the top left corner which reads "Overall score"

## Screenshots
over all score

### PR DESCRIPTION
**Pull request by rtibbles**
## Summary

Changes score to percentage.
Allows endless overflow of interactions.

Fixes #1430 

image

### CODE REVIEW

**Comment by DXCanas** [comment]
I thought the actual mock up specified pagination, and I tried to do side scrolling.

I like this better than both of those options, though.

File: kolibri/plugins/coach/assets/src/views/exam-report-detail-page/page-status.vue [hunk 1]
```diff
@@ -44,7 +44,7 @@
     $trNameSpace: 'coachExamReportDetailPageStatus',
     $trs: {
       title: '{name} - Exam Performance',
-      overallScore: 'Overall Score: <strong>{ score, number, plural }</strong>',
+      overallScore: 'Overall Score: <strong>{ score, number, percent }</strong>',
```
Comment (DXCanas) [inline kolibri/plugins/coach/assets/src/views/exam-report-detail-page/page-status.vue:47]: nice

**Comment by rtibbles** [comment]
It may well have done - but it just hid things for now.
