### PR TITLE
Fixes for bugs in tag v0.14.0- beta3

### LINKED ISSUE #7066: setup wizard regressions
### Observed behavior

missing margins

image 

language switcher responsiveness was made for different resize behaviors:

### Expected behavior

* standard margin behavior
* languages fill only a single line

### User-facing consequences

regression in layout 

### Context

0.14

### LINKED ISSUE #7068: router errors and warnings in setup wizard
### Observed behavior

image

### Errors and logs

```
router.js:51 [vue-router] Named Route 'UngroupedSetupSteps' has a default child route. When navigating to this named route (:to="{name: 'UngroupedSetupSteps'"), the default child route will not be rendered. Remove the name from this route and use the name of the default child route for named links instead.
SetupWizardIndex.vue:53 Uncaught (in promise) Error: Avoided redundant navigation to current location: "/".
    at HashHistory.confirmTransition (vue-router.esm.js:2185)
    at HashHistory.transitionTo (vue-router.esm.js:2126)
    at HashHistory.replace (vue-router.esm.js:2601)
    at vue-router.esm.js:2916
    at new Promise (<anonymous>)
    at VueRouter.replace (vue-router.esm.js:2915)
    at Vue.beforeMount (SetupWizardIndex.vue:53)
    at invokeWithErrorHandling (vue.runtime.esm.js:1854)
```

### Steps to reproduce

open setup wizard

### Context
0.14

### LINKED ISSUE #7070: misaligned info icon
### Observed behavior

info icon:

image

### Expected behavior

properly aligned

### Steps to reproduce

go through setup wizard

### Context

0.14

### LINKED ISSUE #7081: Filter controls are hidden when there are no results.
### Observed behavior
While testing [learner-find-content-item.feature](https://github.com/learningequality/kolibri/blob/release-v0.14.x/integration_testing/features/learner/learner-find-content-item.feature) - the filter controls are hidden when there are no results.

2020-06-18-thu--v0 14 x-b2--search filter bug

### Expected behavior
The filter controls must still show even when there are no results to let the user reset their filters.

### User-facing consequences
No way for user to reset the filter but to close the dialog.

### Errors and logs
[2020-06-18-thu--filter bug--127.0.0.1-1592533149325.log](https://github.com/learningequality/kolibri/files/4799157/2020-06-18-thu--filter.bug--127.0.0.1-1592533149325.log)
[daemon.txt](https://github.com/learningequality/kolibri/files/4799160/daemon.txt)
[kolibri.txt](https://github.com/learningequality/kolibri/files/4799162/kolibri.txt)

### Steps to reproduce

1. Install Kolibri v0.14.x-b2 using the [build artifact](https://buildkite.com/organizations/learningequality/pipelines/kolibri-python-package/builds/1137/jobs/495a1f23-0cbd-47cb-b134-129fc51b740d/artifacts/0833a0dd-4263-4d48-ae5e-226afb249aa8) at BuildKite
1. Import 2 channels:
    1. import using the `nakav-mafak` token for first channel
    1. use "Touchable Earth (en)" for second channel
1. After import is done, go to the Learn > Channels page and do a search: use `te`
1. In the search dialog, select the filter dropdowns for `Type` and `Channels`:
    1. Type == "Apps"
    1. Channels == "Touchable Earth (en)"
1. Notice the "No results for 'te'" text and that the filter controls are now gone.

### Context
* Kolibri version: [release-0.14.x-beta2](https://buildkite.com/learningequality/kolibri-python-package/builds/1137)
* Operating system: Windows 7 VM
* Browser: Firefox v75 and Chrome v81

### LINKED ISSUE #7112: duplicate i18n namespace
### Observed behavior

```
Kolibri: Duplicate namespace TaskPanel found in /Users/d/Projects/le/develop/kolibri/plugins/device/assets/src/views/FacilitiesPage/TaskPanel.vue?vue&type=script&lang=js&
```

### Expected behavior

no duplicate namespaces

### User-facing consequences

potential issues with translations

### Steps to reproduce

run Kolibri devserver

### Context

0.14 beta 3

### LINKED ISSUE #7120: facility import modal issues
### Observed behavior

When importing a facility it shows a message of the form `(ID), url` instead of, for example, `url (ID)`:

image

On the next step there is an empty string:

image

### Steps to reproduce

begin to import a new facility from `kolibri-beta`

### Context

0.14 beta 3

### LINKED ISSUE #7121: 'Back to facilities' link missing arrow
### Observed behavior

No arrow:

image

### Expected behavior

Same styling as task manager back link for import and back links in coach

### Steps to reproduce

import a facility

### Context

0.14 beta 3

### LINKED ISSUE #7122: initiating import of a facility goes to facility page instead of task manager
### Observed behavior

After triggering an import, the user sees:

| Initial landing page | After clicking "view task manager" |
|--|--|
|image|image|

### Expected behavior

To be consistent with the content import flow, they should be directed to the task manager:

| Initial landing page | After clicking "Back to facilities" |
|--|--|
|image |image|

### User-facing consequences

users not familiar with background tasks might be confused about what just happened and where the facility they tried to import is

### Steps to reproduce

import a faciity

### Context

0.14 beta 3

### LINKED ISSUE #7124: apply KButtonGroup component to error page
### Observed behavior

add inner margin using `KButtonGroup`

image

### Context

0.14.0 beta 3

### PR DESCRIPTION
**Pull request by jonboiser**
### Summary
Fixes for bugs in tag https://github.com/learningequality/kolibri/tree/v0.14.0-
beta3

* Redirect to Tasks page after succesfully starting a facility import (Fixes #7122)
* Fix status message for running DELETEFACILITY tasks
* Display ’n of 4’ message for (instead of 'n of 7') for "import/peer-pull" tasks
* If search term + filters yields no results, don’t clear out filters in state (Fixes #7081)
* Use address nickname in ImportFacilityModalGroup if using static address (Fixes #7120)
* Use KButtonGroup in AppError (Fixes #7124)
* Use BackLink in FacilityTasksPage (Fixes #7121(
* Fix positioning of “info” icon in CoreInfoIcon (Fixes #7070)
* Fix DeviceNameForm
* Silently handle “redundant navigation” error (Fixes #7068)
* Make 0 the lower bound for visible languages in LanguageSwitcherList
* Adjust box properties for SetupWizard pages (Fixes #7066)
* Rename TaskPanel.vue to FacilityTaskPanelDetails.vue (Fixes #7112)
* Move TaskTypes to constants file
* Use ‘facility’ icon in DeviceTopNav

### Reviewer guidance

…

### References

…

----

### Contributor Checklist

PR process:

- [x] PR has the correct target branch and milestone
- [x] PR has 'needs review' or 'work-in-progress' label
- [ ] If PR is ready for review, a reviewer has been added. (Don't use 'Assignees')
- [ ] If this is an important user-facing change, PR or related issue has a 'changelog' label
- [ ] If this includes an internal dependency change, a link to the diff is provided

Testing:

- [ ] Contributor has fully tested the PR manually
- [ ] If there are any front-end changes, before/after screenshots are included
- [ ] Critical user journeys are covered by Gherkin stories
- [ ] Critical and brittle code paths are covered by unit tests

### Reviewer Checklist

- Automated test coverage is satisfactory
- PR is fully functional
- PR has been tested for [accessibility regressions](http://kolibri-dev.readthedocs.io/en/develop/manual_testing.html#accessibility-a11y-testing)
- External dependency files were updated if necessary (`yarn` and `pip`)
- Documentation is updated
- Contributor is in AUTHORS.md

### CODE REVIEW

File: kolibri/core/assets/src/views/CoreInfoIcon/index.vue [hunk 1]
```diff
@@ -58,6 +58,13 @@
     cursor: pointer;
   }
 
+  // Overwrite KICon styles to make it compatible with UIIcon
```
Comment (MisRob) [inline kolibri/core/assets/src/views/CoreInfoIcon/index.vue:61]: This is a question out of scope of the review, just as a matter of interest - what's the reason for wrapping _KIcon_ in _UIIcon_?

File: kolibri/plugins/device/assets/src/views/FacilitiesPage/FacilityTaskPanel.vue [hunk 2]
```diff
@@ -25,7 +25,8 @@
     removeFacilityTaskDisplayInfo,
     importFacilityTaskDisplayInfo,
   } from '../syncTaskUtils';
-  import TaskPanel from './TaskPanel';
+  import { TaskTypes } from '../../constants';
+  import TaskPanel from './FacilityTaskPanelDetails';
```
Comment (MisRob) [inline kolibri/plugins/device/assets/src/views/FacilitiesPage/FacilityTaskPanel.vue]: For the sake of consistency I would expect
`import FacilityTaskPanelDetails from './FacilityTaskPanelDetails';` (though I am not sure what are Kolibri naming conventions in this regard)

File: kolibri/plugins/setup_wizard/assets/src/views/SetupWizardIndex.vue [hunk 3]
```diff
@@ -50,7 +50,7 @@
     // and loses saved state
     beforeMount() {
       if (!this.$store.state.started) {
-        this.$router.replace('/');
+        this.$router.replace('/').catch(() => {});
```
Comment (MisRob) [inline kolibri/plugins/setup_wizard/assets/src/views/SetupWizardIndex.vue]: I saw this [comment](https://github.com/learningequality/kolibri/issues/7068#issuecomment-647754948)

> This is caused by the router.js wrapper assigning the component name as a the route name. E.g. The parent route is given a name of UngroupedSetupSteps, even though it's not set in the routes array.
> 
> In the SetupWizard, we don't don't make the mistake of using to: {name: 'UngroupedSetupSteps'}, so we can ignore the warnings for now.

It's true that
```
Named Route 'UngroupedSetupSteps' has a default child route..
```
warning is caused by using a component name as a route name in our [router wrapper](https://github.com/learningequality/kolibri/blob/develop/kolibri/core/assets/src/router.js#L37). The `catch` introduced here doesn't remove the warning though (I suppose that it's reported even earlier) but I think it makes sense to leave the warning displayed so we are careful about potential problematic use-cases of the router wrapper in this regard.

The subsequent error
```
Uncaught (in promise) Error: Avoided redundant navigation to current location: "/".
```
should be actually displayed when you arrive on `setup_wizard/#/` because redundant navigation is happening (you visit `setup_wizard/#/` and then, because of the logic in `beforeMount` hook, you are redirected again to `setup_wizard/#/`). I would suggest avoiding swallowing errors in this way unless there is no other option so we won't run into unexpected issues not being reported. In this case it can be also solved by
```
if (!this.$store.state.started && this.$route.path !== '/') {
  this.$router.replace('/');
}
```

**Review by MisRob — CHANGES_REQUESTED** [review]
Hi JB, I've tested all the linked issues and everything works like charm :)! Regarding code I have only one suggestion to be addressed before merging this PR and that's the router error on setup wizard page.

File: kolibri/core/assets/src/views/CoreInfoIcon/index.vue (hunk 1 above)
Comment (jonboiser) [reply kolibri/core/assets/src/views/CoreInfoIcon/index.vue:61]: I believe that `UiIcon` gives the the `KIcon` a button-like appearance and functionality. We use it in different places, like the `<-` (back) button on some AppBars

File: kolibri/plugins/setup_wizard/assets/src/views/SetupWizardIndex.vue (hunk 3 above)
Comment (jonboiser) [reply kolibri/plugins/setup_wizard/assets/src/views/SetupWizardIndex.vue]: Cool, that extra guard removes the error!

**Comment by jonboiser** [comment]
@MisRob I edited the two relevant commits


2bbc6d3 (change `TaskPanel` to `FacilityTaskPanelDetails`)

f7232fe (add a stricter guard in `beforeMount)`

and force-pushed them.

File: kolibri/core/assets/src/views/CoreInfoIcon/index.vue (hunk 1 above)
Comment (indirectlylit) [reply kolibri/core/assets/src/views/CoreInfoIcon/index.vue:61]: cc @nucleogenesis thoughts?
