### PR TITLE
Multi facilities facility icon

### LINKED ISSUE #7262: In Device Settings page for multi-facility devices, cross-links to Facility Settings should be shown as `KLabeledIcon` with "facility" icon
### Observed behavior

under device settings and the facility list name facilities but don't use the icon:

image

image

### Expected behavior

should use the `KLabeledIcon` component with the facility icon similar to other lists of objects with a defined icon:

image

### User-facing consequences

iconography isn't used to help people understand object types

### Context

0.14.0 beta 8

### PR DESCRIPTION
**Pull request by sairina**
#### **Description of Change**
Added "facility" icons to lists in **Device Settings** and **Facilities**

Screen Shot 2020-11-09 at 5 17 36 PM
Screen Shot 2020-11-09 at 5 07 59 PM
…

### Reviewer guidance
Please manually test these changes with different browsers.
…

### References
Fixes learningequality/kolibri#7262

----

### Contributor Checklist

PR process:

- [x] PR has the correct target branch and milestone
- [x] PR has 'needs review' or 'work-in-progress' label
- [x] If PR is ready for review, a reviewer has been added. (Don't use 'Assignees')
- [ ] If this is an important user-facing change, PR or related issue has a 'changelog' label
- [ ] If this includes an internal dependency change, a link to the diff is provided

Testing:

- [ ] Contributor has fully tested the PR manually
- [ ] If there are any front-end changes, before/after screenshots are included
- [ ] Critical user journeys are covered by Gherkin stories
- [ ] Critical and brittle code paths are covered by unit tests

### Reviewer Checklist

- Automated test coverage is satisfactory
- PR is fully functional
- PR has been tested for [accessibility regressions](http://kolibri-dev.readthedocs.io/en/develop/manual_testing.html#accessibility-a11y-testing)
- External dependency files were updated if necessary (`yarn` and `pip`)
- Documentation is updated
- Contributor is in AUTHORS.md

### CODE REVIEW

File: kolibri/plugins/device/assets/src/views/FacilitiesPage/index.vue [hunk 1]
```diff
@@ -33,12 +33,16 @@
...
         <tr v-for="(facility, idx) in facilities" :key="idx">
           <td>
-            <FacilityNameAndSyncStatus
-              :facility="facility"
-              :isSyncing="facilityIsSyncing(facility)"
-              :isDeleting="facilityIsDeleting(facility)"
-              :syncHasFailed="facility.syncHasFailed"
-            />
+            <span>
+              <KLabeledIcon icon="facility" style="vertical-align: top; top: 8px" />
```
Comment (jonboiser) [inline kolibri/plugins/device/assets/src/views/FacilitiesPage/index.vue]: Move the `KLabeledIcon` into the `FacilityNameAndSyncStatus.vue` component so it appears also on the Facility > Data page.

That is, on this line

https://github.com/learningequality/kolibri/blob/8e40f093569e1a6374fc8b536b523aa2fb267716/kolibri/core/assets/src/views/sync/FacilityNameAndSyncStatus.vue#L6

Add code like this

```
        <KLabeledIcon icon="facility">
          {{ facility.name }}
        </KLabeledIcon>

```

Notice, that the `facility.name` is placed in the "default" slot of `KLabeledComponent`, so it appears next to the icon.

File: kolibri/plugins/device/assets/src/views/DeviceSettingsPage/index.vue [hunk 2]
```diff
@@ -103,6 +103,7 @@
       <ul class="ul-reset">
         <template v-for="(facility, idx) in facilities">
           <li :key="idx">
+            <KLabeledIcon icon="facility" />
```
Comment (jonboiser) [inline kolibri/plugins/device/assets/src/views/DeviceSettingsPage/index.vue]: The `KExternalLink` actually supports an `icon` prop, so I think you can just add something like `icon="facility"` as a prop. See this code

https://github.com/learningequality/kolibri-design-system/blob/v0.2.x/lib/buttons-and-links/KExternalLink.vue

File: kolibri/plugins/device/assets/src/views/FacilitiesPage/index.vue [hunk 3]
```diff
@@ -295,4 +299,8 @@
     }
   }
 
+  .facility-col {
```
Comment (jonboiser) [inline kolibri/plugins/device/assets/src/views/FacilitiesPage/index.vue]: I don't see this class used in this component, so it should be removed.

**Review by jonboiser — CHANGES_REQUESTED** [review]

**Review by jonboiser — APPROVED** [review]
