### PR TITLE
fixes error raised when the folder button is clicked

### LINKED ISSUE #10517: "Folders" button in libraries raise Vue warnings in small screen mode
## Observed behavior

Click on the "Folders" button to view the folders inside a library [in small screens] raises a bunch of Vue warnings. (Refer to the GIF)

folder-button-issue

## Errors and logs

image

## Expected behavior

no Vue warning in the browser console

## User-facing consequences

…

## Steps to reproduce

1. Import the Kolibri QA Channel by using `nakav-mafak` token.
2. Change the resolution to a smaller screen (I used 412x915 - Samsung Galaxy S20 Ultra).
3. Navigate to "Learn" -> "Library" -> "Kolibri QA Channel".
4. Click on the "Folders" button to view the folders inside of Kolibri QA Channel.
5. Observe the console for the Vue warnings.

## Context

- Kolibri verison : Kolibri 0.16.0a12.dev0+git.173.gf4fd6e25
- Kolibri QA Channel version : Version 112
- Browser : Brave Browser Version 1.48.171 Chromium: 110.0.5481.177 (Official Build) (x86_64)
- OS : MacOS Monterey 12.6.5

### PR DESCRIPTION
**Pull request by AllanOXDi**
## Summary
Clean vue errors on the console when a folder is clicked
closes #10517

## References

#10517

## Reviewer guidance

-  Navigate to "Learn" -> "Library" -> "Kolibri QA Channel".
- Change the resolution to a smaller screen.
-  Open the console and click on the "Folders" 

## Testing checklist

- [ ] Contributor has fully tested the PR manually
- [ ] If there are any front-end changes, before/after screenshots are included
- [ ] Critical user journeys are covered by Gherkin stories
- [ ] Critical and brittle code paths are covered by unit tests

## PR process

- [ ] PR has the correct target branch and milestone
- [ ] PR has 'needs review' or 'work-in-progress' label
- [ ] If PR is ready for review, a reviewer has been added. (Don't use 'Assignees')
- [ ] If this is an important user-facing change, PR or related issue has a 'changelog' label
- [ ] If this includes an internal dependency change, a link to the diff is provided

## Reviewer checklist

- Automated test coverage is satisfactory
- PR is fully functional
- PR has been tested for [accessibility regressions](http://kolibri-dev.readthedocs.io/en/develop/manual_testing.html#accessibility-a11y-testing)
- External dependency files were updated if necessary (`yarn` and `pip`)
- Documentation is updated
- Contributor is in AUTHORS.md

### CODE REVIEW

File: kolibri/plugins/learn/assets/src/views/TopicsPage/index.vue [hunk 1]
```diff
@@ -380,6 +380,8 @@
         topicMoreLoading: false,
         mobileSearchActive: false,
         currentSearchCardViewStyle: 'card',
+        closeCategoryModal: '',
+        sidePanelOverlayWidth: '',
```
Comment (nucleogenesis) [inline kolibri/plugins/learn/assets/src/views/TopicsPage/index.vue]: I'm wondering if these are values that should not exist? They're not referenced in any meaningful way (ie, if you initialize them here, there is no place where they are then updated to a meaningful value) -- so I think we either need to identify if these values need to be set on some condition or if we can just remove them altogether instead of just adding them into the scope of the component to suppress error messages

**Review by nucleogenesis — DISMISSED** [review]
2/3 of the changes lgtm - but one seems to just suppress the errors rather than addressing them more thoroughly - if they're useless in the given context, then I'd suggest removing them altogether. However, if the components we pass the values to _need_ them, then we should identify how to properly initialize the two values added in the TopicsPage/index.

File: kolibri/plugins/learn/assets/src/views/TopicsPage/index.vue (hunk 1 above)
Comment (marcellamaki) [reply kolibri/plugins/learn/assets/src/views/TopicsPage/index.vue]: My thought here is that some of the errors and values are leftover from refactoring that happened here over the course of some of the 0.15 patch release, so yes, agree with @nucleogenesis that making sure we have clarity about whether or not some more cleanup should happen is key. If you need some help sorting through that, @AllanOXDi, just let us know!

**Review by nucleogenesis — COMMENTED** [review]
Thanks for the latest updates @AllanOXDi -- I think that with a quick QA pass from @pcenov this will be good to go.

**Comment by pcenov** [comment]
Hi @AllanOXDi I am getting an error while trying to install the [.deb build](https://github.com/learningequality/kolibri/suites/12533565951/artifacts/669267249) from the build artefacts. Could you take a look and make sure that the build is OK?

**Comment by pcenov** [comment]
@AllanOXDi nevermind, I tested it with the Windows build instead - there are no longer errors displayed in the console, LGTM! :)

**Review by radinamatic — APPROVED** [review]
Manual QA passed, good to go! 👏🏽 💯 :shipit:
