### PR TITLE
Add some other fixes to increment reactivity in vue store

### LINKED ISSUE #4823: regression: 'select all' in quiz creation no longer works
### Observed behavior

'select all' checkbox has no effect:

image

### Expected behavior

either:

should select all items below

### User-facing consequences

confusion

### Errors and logs

…

### Steps to reproduce

* new quiz
* navigate to a topic
* select all

### Context

0.12

### PR DESCRIPTION
**Pull request by jredrejo**
### Summary
This PR changes the way selectedExercises are updated and deleted in the vue store to make these changes reactive.

### Reviewer guidance
1. As a coach or an admin, go to Coach- Plan - New quiz
2. Select one channel
3. Click on 'Select all' checkbox
4. All the resources in the channel must be selected
5. Click again on 'Select all' checkbox
6. All the resources in the channel must be unselected

### References
* Closes #4823 
* Related to #4841 

### Contributor Checklist

PR process:

- [x] PR has the correct target branch and milestone
- [x] PR has 'needs review' or 'work-in-progress' label
- [x] If PR is ready for review, a reviewer has been added. (Don't use 'Assignees')
- [ ] If this is an important user-facing change, PR or related issue has a 'changelog' label
- [ ] If this includes an internal dependency change, a link to the diff is provided

Testing:

- [x] Contributor has fully tested the PR manually
- [ ] If there are any front-end changes, before/after screenshots are included
- [ ] Gherkin stories have been updated
- [ ] Unit tests have been updated

### Reviewer Checklist

- Automated test coverage is satisfactory
- PR is fully functional
- PR has been tested for [accessibility regressions](http://kolibri-dev.readthedocs.io/en/develop/manual_testing.html#accessibility-a11y-testing)
- External dependency files were updated if necessary (`yarn` and `pip`)
- Documentation is updated
- Contributor is in AUTHORS.rst

### CODE REVIEW

**Review by rtibbles — APPROVED** [review]
Code looks good - manual testing shows it works. Excellent!

Hrm, I wonder if we could implement a linting rule to catch these gotchas?

**Comment by jredrejo** [comment]
> Hrm, I wonder if we could implement a linting rule to catch these gotchas?

In the pre-commit hooks, what level is used for the vue style guide? Point 10 of https://vuejs.org/v2/style-guide/#Component-instance-options-order-recommended is related to this kind of issues.

**Comment by rtibbles** [comment]
I guess they don't currently have a style guide for Vuex? And hence no linting rules - can see if there are any.

**Comment by rtibbles** [comment]
Hrm, didn't find any in a quick google search. Might be relatively simple to create ones that work for our codebase though.

**Comment by indirectlylit** [comment]
>  what level is used for the vue style guide? 

We also have a number of rules disabled. I believe some stuff seemed like too much work at the time to refactor, but I don't know the details.

File: kolibri/plugins/coach/assets/src/modules/examCreation/index.js [hunk 1]
```diff
@@ -78,12 +79,12 @@ export default {
...
     REMOVE_FROM_SELECTED_EXERCISES(state, exercises) {
       exercises.forEach(exercise => {
-        delete state.selectedExercises[exercise.id];
+        Vue.delete(state.selectedExercises, exercise.id);
       });
     },
     UPDATE_SELECTED_EXERCISES(state, exercises) {
       exercises.forEach(newExercise => {
-        Object.assign(state.selectedExercises[newExercise.id], newExercise);
+        Vue.set(state.selectedExercises, newExercise.id, newExercise);
```
Comment (indirectlylit) [inline kolibri/plugins/coach/assets/src/modules/examCreation/index.js:87]: cc @jonboiser this may relate to what you were working on earlier?
