### PR TITLE
Make exercise attempts component support RTL

### LINKED ISSUE #1850: RTL: Exercise progress moves right, should move left
## Summary

Checks and X's are still moving right on exercise performance

## System information

RTL Demo Server

 - Operating system: Mac OSX
 - Browser: Chrome

## How to reproduce

Complete an exercise question and click next question

## Screenshots

image

### PR DESCRIPTION
**Pull request by christianmemije**
### Summary

As stated in the title

image

### Reviewer guidance

Go through an exercise in RTL mode.

### References

Fixes #1850

----

### Contributor Checklist

- [x] PR has the correct target milestone
- [x] PR has 'needs review' or 'work-in-progress' label
- [x] If PR is ready for review, it has been assigned or requests review from someone and labeled as 'needs review'
- [x] PR has been fully tested manually
- [ ] Documentation is updated
- [ ] External dependencies files were updated (`yarn` and `pip`)
- [ ] Link to diff of internal dependency change is included
- [x] Screenshots of any front-end changes are in the PR description
- [x] PR does not introduce [accessibility regressions](http://kolibri.readthedocs.io/en/develop/dev/manual_testing.html#accessibility-a11y-testing)
- [ ] CHANGELOG.rst is updated for high-level changes
- [ ] You've added yourself to AUTHORS.rst if you're not there

### Reviewer Checklist

- [ ] Automated test coverage is satisfactory
- [ ] PR has been fully tested manually

### CODE REVIEW

File: kolibri/plugins/learn/assets/src/views/assessment-wrapper/exercise-attempts/index.vue [hunk 1]
```diff
@@ -73,10 +73,13 @@
         if (this.waitingForAttempt) {
           xPos += ANSWER_WIDTH;
         }
+        if (this.isRtl) {
+          xPos *= -1;
+        }
         const style = {};
         // translateZ(0) is there to try and force GPU-acceleration.
         // (see e.g. http://blog.teamtreehouse.com/increase-your-sites-performance-with-hardware-accelerated-css)
-        style.transform = `translate(${xPos}px) translateZ(0)`;
```
Comment (christianmemije) [inline kolibri/plugins/learn/assets/src/views/assessment-wrapper/exercise-attempts/index.vue:79]: Removed the `translateZ(0)` because it was unnecessary since it never changed.

Comment (indirectlylit) [reply kolibri/plugins/learn/assets/src/views/assessment-wrapper/exercise-attempts/index.vue:79]: see the comment directly above

Comment (christianmemije) [reply kolibri/plugins/learn/assets/src/views/assessment-wrapper/exercise-attempts/index.vue:79]: D'oh

Comment (christianmemije) [reply kolibri/plugins/learn/assets/src/views/assessment-wrapper/exercise-attempts/index.vue:79]: @indirectlylit  Added back in, but I doubt it makes any noticeable difference.

Comment (indirectlylit) [reply kolibri/plugins/learn/assets/src/views/assessment-wrapper/exercise-attempts/index.vue:79]: True. just trying to save the kids a little battery
