### PR TITLE
Remove `_blank` in favor of `openInNewTab` in KExternalLink.

### LINKED ISSUE #7712: Leverage new `openInNewTab` prop of `KExternalLink`
### Observed behavior

We're adding a new prop which allows external links to set whether or not they open in a new tab: https://github.com/learningequality/kolibri-design-system/pull/137

`KExternalLink` is slightly misnamed: it really means "not a Vue router link". It is used for both "internal links" e.g. "Explore without account" on the sign-in page as well truly external links such as to _learningequality.org_ from the privacy policy.

### Expected behavior

We should audit our use of `KExternalLink` and set `openInNewTab=true` when appropriate.

### User-facing consequences

Internal links should stay on the same tab, and truly external links should open in a new tab.

### Context

0.14.4

### PR DESCRIPTION
**Pull request by YashJipkate**
### Summary

This PR removes `target="_blank"` in `KExternalLink` to make use of the `openInNewTab` prop of `KExternalLink`.

### Reviewer guidance

The external links (as in the Privacy modal) should appear with an iconographic representation of the "new tab" behavior.

### References

Fixes #7712.

----

### Contributor Checklist

PR process:

- [x] PR has the correct target branch and milestone
- [ ] PR has 'needs review' or 'work-in-progress' label
- [ ] If PR is ready for review, a reviewer has been added. (Don't use 'Assignees')
- [ ] If this is an important user-facing change, PR or related issue has a 'changelog' label
- [ ] If this includes an internal dependency change, a link to the diff is provided

Testing:

- [x] Contributor has fully tested the PR manually
- [ ] If there are any front-end changes, before/after screenshots are included
- [ ] Critical user journeys are covered by Gherkin stories
- [ ] Critical and brittle code paths are covered by unit tests

### Reviewer Checklist

- Automated test coverage is satisfactory
- PR is fully functional
- PR has been tested for [accessibility regressions](http://kolibri-dev.readthedocs.io/en/develop/manual_testing.html#accessibility-a11y-testing)
- External dependency files were updated if necessary (`yarn` and `pip`)
- Documentation is updated
- Contributor is in AUTHORS.md

### CODE REVIEW

**Comment by nucleogenesis** [comment]
Hey @YashJipkate thank you so much for this contribution! 

Over here: https://github.com/learningequality/kolibri/issues/7712#issuecomment-797373073 you mentioned that this is a "working PR" - do you plan on committing more changes to this PR?

**Comment by YashJipkate** [comment]
@nucleogenesis sorry for the misunderstanding. By working PR I meant that this is fully functional and can be tested by the reviewer without any breakage.

**Comment by YashJipkate** [comment]
Hey @jonboiser @nucleogenesis any updates on this? It would be great if I could get some guidance on how to fix those tests.

File: kolibri/core/assets/src/views/PrivacyInfoModal.vue [hunk 1]
```diff
@@ -38,7 +38,7 @@
         <KExternalLink
           text="https://learningequality.org"
           href="https://learningequality.org"
-          target="_blank"
+          openInNewTab="true"
```
Comment (jonboiser) [inline kolibri/core/assets/src/views/PrivacyInfoModal.vue]: For each of these, could you change it to
```suggestion
          :openInNewTab="true"
```
?

Otherwise, what is passed into the `openInNewTab` prop is the string literal `"true"` and not the Boolean value `true`.

Comment (YashJipkate) [reply kolibri/core/assets/src/views/PrivacyInfoModal.vue]: Done.

**Review by jonboiser — APPROVED** [review]
Looks good, thanks!
