### PR TITLE
Fixes assigned lessons and quizzes are not visible to the learner

### LINKED ISSUE #12955: 0.18 - Home > Class - The assigned lessons and quizzes are not visible to the learner
## Observed behavior

Observed on latest `develop `- when I sing in as a Learner and I go to Home > Class > <class> then I don't see any of my assigned lessons and quizzes. I can see the following error in the console:

```
TypeError: Cannot read properties of undefined (reading '$router')
    at setup (ClassAssignmentsPage.vue:64:1)
    at Ke (vue.runtime.common.prod.js:11:19108)
    at vue.runtime.common.prod.js:11:37000
    at _o (vue.runtime.common.prod.js:11:36904)
    at e._init (vue.runtime.common.prod.js:11:41637)
    at new i (vue.runtime.common.prod.js:11:39089)
    at vue.runtime.common.prod.js:11:29493
    at init (vue.runtime.common.prod.js:11:29336)
    at n (vue.runtime.common.prod.js:11:33371)
    at vue.runtime.common.prod.js:11:62186
```

https://github.com/user-attachments/assets/9ed5ffac-0b33-44ac-b34a-828aa703896c

Logs: [logs.zip](https://github.com/user-attachments/files/18165279/logs.zip)

## Expected behavior

All assigned lessons and quizzes should be visible.

## Steps to reproduce the issue

1. Install the latest develop build
2. As a Coach assign lessons and quizzes to a learner
3. As a Learner sign in and attempt to see the assigned lessons and resources

## Usage Details
Windows 11, Ubuntu 22  - Chrome

### PR DESCRIPTION
**Pull request by AllanOXDi**
## Summary
This PR fixes quizes and lessons not being visible to learners

https://github.com/user-attachments/assets/cecc1c33-2fa9-43f7-9c27-b4477b46cf36

Closes  #12955

## References
 #12955

## Reviewer guidance
1. Login as a coach
2. Create lesson and quizzes
3. Login as a learner to view

### CODE REVIEW

File: kolibri/plugins/learn/assets/src/routes/classesRoutes.js [hunk 1]
```diff
@@ -36,6 +36,12 @@ export default [
   {
     name: ClassesPageNames.CLASS_ASSIGNMENTS,
     path: '/classes/:classId',
+    props: route => {
+      const classId = route.params.classId;
```
Comment (AllanOXDi) [inline kolibri/plugins/learn/assets/src/routes/classesRoutes.js:40]: I thought of passing classId as a prop to make it accessible in the component which was not possible with `this.$route.params.classId`

File: kolibri/plugins/learn/assets/src/views/classes/ClassAssignmentsPage.vue [hunk 2]
```diff
@@ -57,15 +56,15 @@
...
         useLearnerResources();
 
-      const classId = root.$router.currentRoute.params.classId;
-      const classroom = computed(() => getClass(classId));
+      const classId = computed(() => props.classId);
+      const classroom = computed(() => getClass(classId.value));
       const className = computed(() => (get(classroom) ? get(classroom).name : ''));
-      const activeLessons = computed(() => getClassActiveLessons(get(classId)));
-      const activeQuizzes = computed(() => getClassActiveQuizzes(get(classId)));
+      const activeLessons = computed(() => getClassActiveLessons(get(classId.value)));
```
Comment (rtibbles) [inline kolibri/plugins/learn/assets/src/views/classes/ClassAssignmentsPage.vue]: Shouldn't have to call `get` and use the `.value` accessor - only one or the other is needed.

Comment (AllanOXDi) [reply kolibri/plugins/learn/assets/src/views/classes/ClassAssignmentsPage.vue]: Fixed! thank you

**Review by pcenov — APPROVED** [review]
Thanks @AllanOXDi - no issues observed while manually testing.

**Review by rtibbles — APPROVED** [review]
Changes all make sense, and QA checks out. Passing route props is something we have under used as a mechanism, makes a lot of sense to use it more!
