### PR TITLE
Webpack 5 upgrade

### LINKED ISSUE #8960: Build error did not break the build.
## Observed behavior
Frontend build for a plugin broke, but the build still exited with a 0 error code.

## Errors and logs
```
Kolibri Build: Failed to compile 'kolibri.plugins.coach.app' bundle!
./kolibri/plugins/coach/assets/src/views/plan/LessonResourceSelectionPage/index.vue?vue&type=style&index=0&id=7c60ddb1&lang=scss&scoped=true&)
Module build failed (from ./node_modules/mini-css-extract-plugin/dist/loader.js):
ModuleBuildError: Module build failed (from ./node_modules/sass-loader/dist/cjs.js):
SassError: Undefined variable: "$core-time".
        on line 590 of /home/richard/github/kolibri/kolibri/plugins/coach/assets/src/views/plan/LessonResourceSelectionPage/index.vue
>>     transition: all $core-time;

   --------------------^

Kolibri Production Build: There was a build error for kolibri.plugins.coach.app
Kolibri Production Build: 
ERROR in ./kolibri/plugins/coach/assets/src/views/plan/LessonResourceSelectionPage/index.vue?vue&type=style&index=0&id=7c60ddb1&lang=scss&scoped=true& (./node_modules/mini-css-extract-plugin/dist/loader.js!./node_modules/css-loader/dist/cjs.js??ref--3-1!./node_modules/vue-loader/lib/loaders/stylePostLoader.js!./node_modules/postcss-loader/dist/cjs.js??ref--3-2!./node_modules/sass-loader/dist/cjs.js!./node_modules/vue-loader/lib??vue-loader-options!./kolibri/plugins/coach/assets/src/views/plan/LessonResourceSelectionPage/index.vue?vue&type=style&index=0&id=7c60ddb1&lang=scss&scoped=true&)
Module build failed (from ./node_modules/mini-css-extract-plugin/dist/loader.js):
ModuleBuildError: Module build failed (from ./node_modules/sass-loader/dist/cjs.js):
SassError: Undefined variable: "$core-time".
        on line 590 of /home/richard/github/kolibri/kolibri/plugins/coach/assets/src/views/plan/LessonResourceSelectionPage/index.vue
>>     transition: all $core-time;

   --------------------^

    at runLoaders (/home/richard/github/kolibri/node_modules/webpack/lib/NormalModule.js:316:20)
    at /home/richard/github/kolibri/node_modules/loader-runner/lib/LoaderRunner.js:367:11
    at /home/richard/github/kolibri/node_modules/loader-runner/lib/LoaderRunner.js:233:18
    at context.callback (/home/richard/github/kolibri/node_modules/loader-runner/lib/LoaderRunner.js:111:13)
    at Object.render [as callback] (/home/richard/github/kolibri/node_modules/sass-loader/dist/index.js:73:7)
    at Object.done [as callback] (/home/richard/github/kolibri/node_modules/neo-async/async.js:8067:18)
    at options.error (/home/richard/github/kolibri/node_modules/node-sass/lib/index.js:294:32)
 @ ./kolibri/plugins/coach/assets/src/views/plan/LessonResourceSelectionPage/index.vue?vue&type=style&index=0&id=7c60ddb1&lang=scss&scoped=true& 1:0-531 1:547-550 1:552-1080 1:552-1080
 @ ./kolibri/plugins/coach/assets/src/views/plan/LessonResourceSelectionPage/index.vue
 @ ./kolibri/plugins/coach/assets/src/routes/planLessonsRoutes.js
 @ ./kolibri/plugins/coach/assets/src/routes/planRoutes.js
 @ ./kolibri/plugins/coach/assets/src/routes/index.js
 @ ./kolibri/plugins/coach/assets/src/app.js
```

And yet still showed:
```
Kolibri Build: Initial build complete in 51.808 seconds
```

## Expected behavior
Build failure should result in non-zero exit code.

### LINKED ISSUE #9005: Upgrade Webpack to version 5
Upgrade Webpack to version 5, and update all associated dependencies.

### LINKED ISSUE #9006: Upgrade kolibri-tools to use NodeJS 16
Upgrade to latest LTS.

### LINKED ISSUE #9007: Simplify webpack dev server
Use a single dev server instance to serve all bundles by using a multi-configuration setup instead of multiple independent devservers.

We did this due to a historic limitation in webpack dev server that now seems to have been resolved. More details here: https://github.com/webpack/webpack-dev-server/issues/641#issuecomment-444055379

The basic approach involves serving each configuration from a separate sub-path from the same port.

### PR DESCRIPTION
**Pull request by rtibbles**
## Summary
* Upgrades NodeJS to 16.x LTS
* Changes all references to NodeJS in CI flows and documentation to v16.13.2
* Upgrades Webpack and all associated plugins, loaders to latest compatible with our stack.
* Switches our plugin building pipeline to a Webpack multicompiler setup to reduce overhead and improve build times.
* Adds build caching by default in development builds to reduce cold restart times.
* Removes complex bundle stats analyzer code and replaces with simple webpack JSON stats export
* Updates stylelint configuration to handle the fact that stylelint no longer automatically recognizes sass and less
* Adds additional ignores to stylelint configuration to limit linting diff

## References
Fixes #8960
Fixes #9005 
Fixes #9006 
Fixes #9007

## Reviewer guidance
Check that the frontend builds and runs as expected.

Check that all imported SVGs are properly rendering.

Check that hot devserver mode functions as expected.

----

## Testing checklist

- [ ] Contributor has fully tested the PR manually
- [ ] If there are any front-end changes, before/after screenshots are included
- [ ] Critical user journeys are covered by Gherkin stories
- [ ] Critical and brittle code paths are covered by unit tests

## PR process

- [ ] PR has the correct target branch and milestone
- [ ] PR has 'needs review' or 'work-in-progress' label
- [ ] If PR is ready for review, a reviewer has been added. (Don't use 'Assignees')
- [ ] If this is an important user-facing change, PR or related issue has a 'changelog' label
- [ ] If this includes an internal dependency change, a link to the diff is provided

## Reviewer checklist

- Automated test coverage is satisfactory
- PR is fully functional
- PR has been tested for [accessibility regressions](http://kolibri-dev.readthedocs.io/en/develop/manual_testing.html#accessibility-a11y-testing)
- External dependency files were updated if necessary (`yarn` and `pip`)
- Documentation is updated
- Contributor is in AUTHORS.md

### CODE REVIEW

**Comment by nucleogenesis** [comment]
C

**Comment by nucleogenesis** [comment]
lol

File: kolibri/core/assets/src/views/Backdrop.vue [hunk 1]
```diff
@@ -41,7 +41,7 @@
     z-index: 11;
     width: 100%;
     height: 100%;
-    background: rgba(0, 0, 0, 0.7);
+    background: rgba(0, 0, 0, 70%);
```
Comment (nucleogenesis) [inline kolibri/core/assets/src/views/Backdrop.vue]: I think maybe there is something off w/ the CSS processing. This `rgba` value is processed into `black` .

In this particular case, this results in the semi-opaque mask under the side nav to be fully black (and the line under the Kolibri title there is black too when it shouldn't be):

image

It also affects FullScreenSidePanel but that's all I've found. KModal uses the same style and is not affected during the processing likely because it's in KDS.

I did try reverting the change locally just in case and it doesn't fix the issue.

Comment (nucleogenesis) [reply kolibri/core/assets/src/views/Backdrop.vue]: Found another on Profile dropdown and another on the "resource completed" modal (not screenshotted, the background is black)
image

**Review by nucleogenesis — CHANGES_REQUESTED** [review]
The only thing I noticed about hot reload was that it feels a little slower to reflect my changes than it did previously. Not the hugest deal in any case.

:heart: :heart_eyes: :heart:
It takes a minute for the server to start down from 2-3 mins - then restarts take 10-15 seconds.
:heart: :heart_eyes: :heart:

Otherwise - the only issues I noted were related to the CSS processor converting rgba colors to solid colors.

File: kolibri/core/assets/src/views/Backdrop.vue (hunk 1 above)
Comment (rtibbles) [reply kolibri/core/assets/src/views/Backdrop.vue]: Hrm, this is probably Stylelint applying SCSS function styling to CSS functions - will revert these changes and try to exclude the linting rule that is making this happen.

**Review by nucleogenesis — APPROVED** [review]
LGTM! I look forward to setting my Node to version 16 by default from now on after I rebase :)

**Comment by indirectlylit** [comment]
exciting!
