### PR TITLE
Signup Fix

### LINKED ISSUE #1327: signup is broken
image

### PR DESCRIPTION
**Pull request by DXCanas**
Changing UI to match behavior from vf. Must have gotten lost somewhere, because these changes were merged at some point.

Fixes #1327? Allows users to sign up now, but the `id` error shown comes from a core action. We don't need that data to sign up.

### CODE REVIEW

File: kolibri/plugins/user/assets/src/views/sign-up-page/index.vue [hunk 1]
```diff
@@ -136,22 +135,26 @@
...
       },
     },
     methods: {
       signUp() {
-        this.signUpAction({
-          full_name: this.name,
-          username: this.username,
-          password: this.password,
-        });
+        const canSubmit =
```
Comment (christianmemije) [inline kolibri/plugins/user/assets/src/views/sign-up-page/index.vue:146]: you can make `canSubmit` a computed prop?

Comment (DXCanas) [reply kolibri/plugins/user/assets/src/views/sign-up-page/index.vue:146]: It actually used to be https://github.com/fle-internal/kolibri-instant-schools-plugin/pull/24/files

Changed it due to verbal suggestion from @indirectlylit a while back, iirc. But it's not used anywhere, and it doesn't need `this`, so I'm not sure what the purpose would be

Comment (indirectlylit) [reply kolibri/plugins/user/assets/src/views/sign-up-page/index.vue:146]: I don't recall - sorry :) Either way makes sense to me...
