### PR TITLE
pr/7473 Login flow looks like it accepts any username despite the error validation

### LINKED ISSUE #7473: Login flow looks like it accepts any username despite the error validation
### Observed behavior
I am able to enter any kind of special characters I want for the username and am allowed to press the "NEXT" button which makes it look like my username was acccepted

character bug

Screen Shot 2020-08-12 at 1 01 43 PM

### Expected behavior
I should not be able to press press the next button until I resolved the error

### User-facing consequences
Misleading error messaging, weird characters entered.

### Steps to reproduce
- Go to login form
- Enter anything for the username

### Context
Tell us about your environment, including:
 * Kolibri version: kolibribeta
 * Operating system: MacOS
 * Browser: Chrome, firefox

### PR DESCRIPTION
**Pull request by mdctleo**
Issue #7473 

Now next button is disabled when entering invalid characters

Screen Shot 2020-08-24 at 7 06 16 PM

### CODE REVIEW

File: kolibri/plugins/user/assets/src/views/SignInPage/index.vue [hunk 1]
```diff
@@ -91,7 +91,7 @@
               class="login-btn"
               :text="$tr('nextLabel')"
               :primary="true"
-              :disabled="busy"
+              :disabled="!isNextValid"
```
Comment (jonboiser) [inline kolibri/plugins/user/assets/src/views/SignInPage/index.vue]: The button should be disabled if `busy` or `!isNextValid`
```suggestion
              :disabled="busy || !isNextValid"
```

File: kolibri/plugins/user/assets/src/views/SignInPage/index.vue [hunk 2]
```diff
@@ -335,6 +335,9 @@
           this.hasMultipleFacilities || get(this.selectedFacility, 'dataset.preset') !== 'informal'
         );
       },
+      isNextValid() {
```
Comment (jonboiser) [inline kolibri/plugins/user/assets/src/views/SignInPage/index.vue]: Related to the above comment, I think I would just keep the `busy` part out of this property, or maybe rename it so it's more general, something  to the effect of "next button is enabled"

File: kolibri/plugins/user/assets/src/views/SignInPage/index.vue [hunk 3]
```diff
@@ -91,7 +91,7 @@
               class="login-btn"
               :text="$tr('nextLabel')"
               :primary="true"
-              :disabled="busy"
+              :disabled="!isNextButtonEnabled"
```
Comment (jonboiser) [inline kolibri/plugins/user/assets/src/views/SignInPage/index.vue:94]: You'll need to put a guard in the `signIn` method as well to prevent a submit event on the kwyboard. Even though the "next" button is disabled, I can still press "Enter" on my keyboard and move forward with an invalid username like `jb!!`

File: kolibri/plugins/user/assets/src/views/SignInPage/index.vue [hunk 4]
```diff
@@ -484,6 +487,10 @@
           this.$refs.username.focus();
         }
       },
+      handleUsernameInput() {
```
Comment (jonboiser) [inline kolibri/plugins/user/assets/src/views/SignInPage/index.vue:490]: I added this so that the `invalidText` under the textbox would appear immediately, since the only other way would be to blur the textbox now that the form and next button are disabled..

**Review by jonboiser — APPROVED** [review]
Looks good! Thank you!

File: kolibri/plugins/user/assets/src/views/SignInPage/index.vue (hunk 4 above)
Comment (mdctleo) [reply kolibri/plugins/user/assets/src/views/SignInPage/index.vue:490]: alright make sense, thank you for the help!
