### PR TITLE
Fix string to be Learn more rather than just learn

### LINKED ISSUE #10237: Profile > Change facility - Only the 'Learn' part of the string is displayed
## Observed behavior
While testing https://github.com/learningequality/kolibri/pull/10233 I noticed that only the 'Learn' part of the 'Learn more' string is displayed

## Expected behavior
Show 'Learn more' instead

## Steps to reproduce the issue
1. Install the the [following build ](https://buildkite.com/learningequality/kolibri-debian/builds/6281) 
2.  Select the 'On my own' flow in the Setup Wizard and create a facility
3. Navigate to Profile
4. Observe the 'Change learning facility' section of the page

## Usage Details
Windows 10, Ubuntu 22  - Chrome

### PR DESCRIPTION
**Pull request by marcellamaki**
and cleanup a string mis-match in setup wizard along the way

## References
Fixes #10237 

----

## Testing checklist

- [ ] Contributor has fully tested the PR manually
- [ ] If there are any front-end changes, before/after screenshots are included
- [ ] Critical user journeys are covered by Gherkin stories
- [ ] Critical and brittle code paths are covered by unit tests

## PR process

- [ ] PR has the correct target branch and milestone
- [ ] PR has 'needs review' or 'work-in-progress' label
- [ ] If PR is ready for review, a reviewer has been added. (Don't use 'Assignees')
- [ ] If this is an important user-facing change, PR or related issue has a 'changelog' label
- [ ] If this includes an internal dependency change, a link to the diff is provided

## Reviewer checklist

- Automated test coverage is satisfactory
- PR is fully functional
- PR has been tested for [accessibility regressions](http://kolibri-dev.readthedocs.io/en/develop/manual_testing.html#accessibility-a11y-testing)
- External dependency files were updated if necessary (`yarn` and `pip`)
- Documentation is updated
- Contributor is in AUTHORS.md

### CODE REVIEW

File: kolibri/plugins/user_profile/assets/src/views/ProfilePage/index.vue [hunk 1]
```diff
@@ -301,8 +301,8 @@
         message: 'Move your account and progress data to another learning facility.',
         context: 'Explanation of what change a learning facility means',
       },
-      learn: {
-        message: 'Learn',
+      learnMore: {
```
Comment (rtibbles) [inline kolibri/plugins/user_profile/assets/src/views/ProfilePage/index.vue:304]: This string is also used in the MissingResourceAlert component, but I don't think there's much value in consolidating this just yet.

**Review by rtibbles — APPROVED** [review]

File: kolibri/plugins/user_profile/assets/src/views/ProfilePage/index.vue (hunk 1 above)
Comment (radinamatic) [reply kolibri/plugins/user_profile/assets/src/views/ProfilePage/index.vue:304]: Ok, just 2 words, we can let it slip for now.

**Review by radinamatic — APPROVED** [review]
Good to go! 💯 👍🏽 :shipit:
