### PR TITLE
pr/7456 In `LearnerClassEnrollmentPage` and `CoachClassAssignmentPage`, place "Confirm" button in fixed bottom bar

### LINKED ISSUE #7456: In `LearnerClassEnrollmentPage` and `CoachClassAssignmentPage`, place "Confirm" button in fixed bottom bar
### Observed behavior

"Confirm" button in the learner/coach enrollment pages is at the bottom of the table.

image

### Expected behavior

See annotations in screenshot

To save users from having to scroll down for the confirm button, place the "Confirm" button in a fixed bottom bar. And also add a message like "5 selected" that is maintained even wile users page through the lists.

Example from channel management workflow:

Screen Shot 2020-08-07 at 2 02 43 PM

### User-facing consequences

Saves users from having to scroll down for "Confirm" button

### Errors and logs

…

### Steps to reproduce

…

### Context

…

### PR DESCRIPTION
**Pull request by mdctleo**
issue #7456 

changes: 
Screen Shot 2020-08-18 at 12 19 39 PM
Screen Shot 2020-08-18 at 12 19 52 PM

Added a SelectionBottomBar component in facility. The component is a fixed bottom bar for LearnerClassEnrollmentPage and CoachClassAssignmentPage

### CODE REVIEW

**Comment by mdctleo** [comment]
@jonboiser  ready for review

File: kolibri/plugins/facility/assets/src/views/ClassEnrollForm.vue [hunk 1]
```diff
@@ -1,6 +1,6 @@
-<template>
+<template xmlns:v-slot="http://www.w3.org/1999/XSL/Transform">
```
Comment (jonboiser) [inline kolibri/plugins/facility/assets/src/views/ClassEnrollForm.vue]: Could you undo this change?

```suggestion
<template>
```

File: kolibri/plugins/facility/assets/src/views/SelectionBottomBar.vue [hunk 2]
```diff
@@ -0,0 +1,67 @@
...
+  </BottomAppBar>
+
+</template>
+
+
+<script>
+
+  import commonCoreStrings from 'kolibri.coreVue.mixins.commonCoreStrings';
+  import BottomAppBar from 'kolibri.coreVue.components.BottomAppBar';
+  import responsiveWindowMixin from 'kolibri.coreVue.mixins.responsiveWindowMixin';
```
Comment (jonboiser) [inline kolibri/plugins/facility/assets/src/views/SelectionBottomBar.vue]: I don't think anything in the component is using this mixin so this import can be removed

```suggestion
```

File: kolibri/plugins/facility/assets/src/views/SelectionBottomBar.vue [hunk 3]
```diff
@@ -0,0 +1,67 @@
...
+
+  export default {
+    name: 'SelectionBottomBar',
+    components: {
+      BottomAppBar,
+    },
+    mixins: [commonCoreStrings, responsiveWindowMixin],
```
Comment (jonboiser) [inline kolibri/plugins/facility/assets/src/views/SelectionBottomBar.vue]:
```suggestion
    mixins: [commonCoreStrings],
```

File: kolibri/plugins/facility/assets/src/views/SelectionBottomBar.vue [hunk 4]
```diff
@@ -0,0 +1,67 @@
...
+      },
+      selectedMessage() {
+        return this.counts === 0
+          ? this.$tr('zeroSelectedMessage', { type: this.type })
+          : this.$tr('selectedMessage', { counts: this.counts, type: this.type });
+      },
+    },
+    $trs: {
+      zeroSelectedMessage: '0 {type} selected',
+      selectedMessage: '{counts} {type} selected',
```
Comment (jonboiser) [inline kolibri/plugins/facility/assets/src/views/SelectionBottomBar.vue]: We'll need two separate localizations for coaches and learners since they need to be translated differently. Here is an example from a different component

https://github.com/learningequality/kolibri/blob/91c4f2ae06cd73e3d6ad24ae305f1877b7d53f4f/kolibri/plugins/device/assets/src/views/ManageContentPage/SelectionBottomBar.vue#L151-L153

So the coaches version would be something like
```
        '{count, number} {count, plural, one {coach} other {coaches}} selected',

```

**Comment by mdctleo** [comment]
Thank you for the feedback @jonboiser ! I've applied the changes

**Review by jonboiser — APPROVED** [review]
Looks good, thanks!
