### PR TITLE
Resource selection preview: Include metadata for all resource kinds

### LINKED ISSUE #13075: Manage lesson resources > Exercises - Missing metadata
## Observed behavior

Currently there's no metadata displayed for any of the practice resources:

https://github.com/user-attachments/assets/2b1a0984-feda-4e3a-8fb2-c5d258985e8f

## Expected behavior

Since we are showing the metadata for all the other resources it should be investigated why we are not showing it for the practice resources too.

## Steps to reproduce the issue

1. Install the [Kolibri 0.18 alpha1](https://github.com/learningequality/kolibri/releases/tag/v0.18.0-alpha1) build
2. Navigate to Class > Lessons > Lesson and click "Manage resources"
3. Click to view the details of an exercise

## Usage Details
[Kolibri 0.18 alpha1](https://github.com/learningequality/kolibri/releases/tag/v0.18.0-alpha1)
Windows 11, Ubuntu 22  - Chrome, Firefox

### PR DESCRIPTION
**Pull request by nucleogenesis**
## Summary

When the accordion UI was used to show exercise previews, it resulted in the table of metadata information at the bottom of the previews only being shown for non-Exercises. This moves that structure to its own component and it is rendered for all resource kinds at the bottom of the preview.

**NOTE** that I also added conditionals to hide null values (ie, if there is no duration, it doesn't just show a label)

[Screencast_20250321_155121.webm](https://github.com/user-attachments/assets/00c32312-455c-4c29-bb9c-fa00eaf5b09f)

## References

Fixes #13075 

## Reviewer guidance

Do all resource-types show the metadata correctly at the bottom?

### CODE REVIEW

**Review by pcenov — APPROVED** [review]
Thanks @nucleogenesis - I confirm that the metadata values are displayed now.

File: kolibri/plugins/coach/assets/src/views/common/resourceSelection/subPages/PreviewSelectedResources/PreviewMetadata.vue [hunk 1]
```diff
@@ -0,0 +1,94 @@
...
+  <HeaderTable
+    v-if="content"
+    class="license-detail-style"
+  >
+    <HeaderTableRow
+      v-if="content.duration"
+      :keyText="coreString('suggestedTime')"
+    >
+      <template #value>
+        {{ content.duration ? getTime(content.duration) : notAvailableLabel$() }}
```
Comment (AlexVelezLl) [inline kolibri/plugins/coach/assets/src/views/common/resourceSelection/subPages/PreviewSelectedResources/PreviewMetadata.vue:12]: If this node is not rendered if !content.duration. We shouldnt take care of this ternary here?

**Review by AlexVelezLl — APPROVED** [review]
Lgtm! Just a non-blocking comment, but it doesnt actually affect anything :)

**Review by AllanOXDi — APPROVED** [review]
code changes looks good to me
