### PR TITLE
Filter out channels + topics with no available exercises in Exam Creation

### LINKED ISSUE #3940: hide topics and channels with no exercises during exam creation
### Observed behavior

reported by @khangmach 

Channels and topics with no exercises available are still showing and are disabled

### Expected behavior

They should be taken out of the UI list completely

### User-facing consequences

extra visual noise

### Steps to reproduce

Create new exam, look at channel list, see disabled channel names. Navigate to available channel, see disabled topics

### Context

0.10.0

### PR DESCRIPTION
**Pull request by jonboiser**
### Summary

1. Fix `ChannelMetadataViewset` `has_exercises` filter (was checking unavailable Exercises)
1. Update `goToTopic` action to filter out subtopics with zero exercise-type descendants before inserting them into the Exam Creation table.
1. Remove dead code that presents exercise-less topics as disabled (since these should not be shown).
1. DRY up repeated code in topic-row

### Reviewer guidance

**Channels with Exercises appear on top level**

1. Import a channel with Exercises (include Exercises in import)
1. Channel should appear on top level of Exam Creation workflow

**Channels with no install Exercises do not appear on top level**

1. Import a channel that has exercise, but _do not_ import any of those exercises. (e.g. osmosis.org)
1. Channel should not appear on top level of Exam Creation workflow

**Topics with Exercises appear**

1. Import a channel with Exercises (include Exercises in import)
1. Channel + topic should appear in Exam Creation workflow

**Topics without Exercises do not appear**

1. Import a channel with Exercises. Include topics with and without exercises.
1. Topics that do not have exercises _should not appear_ in workflow

### References

Fixes #3940 

----

### Contributor Checklist

- [x] Contributor has fully tested the PR manually
- [x] PR has the correct target branch and milestone
- [x] PR has 'needs review' or 'work-in-progress' label
- [ ] If PR is ready for review, a reviewer has been added. (Don't use 'Assignees')
- [ ] If there are any front-end changes, before/after screenshots are included
- [ ] If this is an important user-facing change, PR or related issue has a 'changelog' label

### Reviewer Checklist

- [ ] Automated test coverage is satisfactory
- [ ] Reviewer has fully tested the PR manually
- [ ] PR has been tested for [accessibility regressions](http://kolibri-dev.readthedocs.io/en/develop/manual_testing.html#accessibility-a11y-testing)
- [ ] External dependencies files were updated (`yarn` and `pip`)
- [ ] Documentation is updated
- [ ] Link to diff of internal dependency change is included
- [ ] CHANGELOG.rst is updated for high-level changes
- [ ] Contributor is in AUTHORS.rst

### CODE REVIEW

File: kolibri/plugins/coach/assets/src/views/exams/create-exam-page/topic-row.vue [hunk 1]
```diff
@@ -7,17 +7,15 @@
...
     </th>
     <td class="core-table-main-col">
       <div class="topic-title">
-        <content-icon :kind="topic" :class="{ disabled: !topicHasExercises }" />
-        <button v-if="topicHasExercises" class="title" @click="$emit('goToTopic', topicId)">
+        <content-icon :kind="topic" />
+        <button class="title" @click="$emit('goToTopic', topicId)">
           {{ topicTitle }}
         </button>
-        <span v-else class="disabled">{{ topicTitle }}</span>
```
Comment (indirectlylit) [inline kolibri/plugins/coach/assets/src/views/exams/create-exam-page/topic-row.vue:20]: can delete the `disabled` class below

**Review by indirectlylit — APPROVED** [review]
tested and works for me. Feel free to merge after deleting the unused class
