### PR TITLE
Gives indication of user having permission to join the facility not showing the devices that don't have sign up enabled.

### LINKED ISSUE #10313: Setup Wizard > LOD > Create a new user - No indication that the user doesn't have permission to join the facility
## Observed behavior
If on my facility the option 'Allow learners to create accounts' is disabled, when a user attempts to join the facility through the 'LOD > Create a new user account for an existing facility' workflow then the user is not being notified that they don't have permission to join the facility.

## Expected behavior
The user should not be allowed to select that facility in the first place. As specified in [Figma](https://www.figma.com/file/MpCG7r5PULOCJsEvnTSti8/Android-Designs-2022?node-id=0-1), in that case the facility should be grayed out and stating: You don't have permission to join this facility

## Steps to reproduce the issue
1. Install the the latest `develop` build.
2.  Setup a full facility and disable 'Allow learners to create accounts' at Facility > Settings
3. On another device attempt to create a Learn-only device by going through the setup wizard and selecting the 'Create a new user account for an existing facility' option

## Video

https://user-images.githubusercontent.com/79847249/227554314-9bf49e04-3505-46be-ae26-b4835de1bfe4.mp4

## Console error

`{"status":403,"data":"[{\"id\":\"PERMISSION_DENIED\",\"metadata\":{\"view\":\"Public Sign Up List\"}}]"}`

## Usage Details
Windows 10, Ubuntu 22  - Chrome, Firefox

### PR DESCRIPTION
**Pull request by Wck-iipi**
## Summary

This does it by copying the logic for getting facility's information from SelectFacility and shows the devices accordingly. If the sign up is allowed, only then device is shown.

## References

Fixes #10313 

## Reviewer guidance

Please test whether devices are not shown when permission to sign up is not given. 

----

## Testing checklist

- [ ] Contributor has fully tested the PR manually
- [ ] If there are any front-end changes, before/after screenshots are included
- [ ] Critical user journeys are covered by Gherkin stories
- [ ] Critical and brittle code paths are covered by unit tests

## PR process

- [ ] PR has the correct target branch and milestone
- [ ] PR has 'needs review' or 'work-in-progress' label
- [ ] If PR is ready for review, a reviewer has been added. (Don't use 'Assignees')
- [ ] If this is an important user-facing change, PR or related issue has a 'changelog' label
- [ ] If this includes an internal dependency change, a link to the diff is provided

## Reviewer checklist

- Automated test coverage is satisfactory
- PR is fully functional
- PR has been tested for [accessibility regressions](http://kolibri-dev.readthedocs.io/en/develop/manual_testing.html#accessibility-a11y-testing)
- External dependency files were updated if necessary (`yarn` and `pip`)
- Documentation is updated
- Contributor is in AUTHORS.md

### CODE REVIEW

File: kolibri/core/assets/src/views/sync/SelectDeviceModalGroup/SelectDeviceForm.vue [hunk 1]
```diff
@@ -356,6 +435,30 @@
           this.$emit('removed_address');
         });
       },
+      canLearnerSignUp(id) {
+        for (const facility of this.availableFacilities) {
+          if (facility.address_id === id) {
+            return facility.learner_can_sign_up;
+          }
+        }
+        return true;
```
Comment (nucleogenesis) [inline kolibri/core/assets/src/views/sync/SelectDeviceModalGroup/SelectDeviceForm.vue]: I'm wondering if we should return false here if we can't find a matching facility - if we're asking "can I sign up for this facility" and we're not finding it in the list of `avaialbleFacilities` then I think it'd be safer to return false here.

File: kolibri/core/assets/src/views/sync/SelectDeviceModalGroup/SelectDeviceForm.vue [hunk 2]
```diff
@@ -186,6 +196,74 @@
...
+                base_url: device.base_url,
+                address_id: device.id,
+                learner_can_sign_up: facility.learner_can_sign_up,
+                learner_can_login_with_no_password: facility.learner_can_login_with_no_password,
+                kolibri_version: device.kolibri_version,
+              };
+            });
+          } catch (e) {
+            return [];
+          }
```
Comment (nucleogenesis) [inline kolibri/core/assets/src/views/sync/SelectDeviceModalGroup/SelectDeviceForm.vue]: You could use [this from](https://github.com/learningequality/kolibri/blob/545ceaedb682e694f830233fd3ed7ba442391df0/kolibri/core/assets/src/mixins/commonSyncElements.js#L91-L101) `commonSyncElements` here I think to get the facilities for the device which already handles the try/catch stuff.

@rtibbles curious thought if we should replace the call to `client` in `commonSyncElements` I linked to above with this `NetworkLocationResource.fetchFacilities` call?

**Review by nucleogenesis — CHANGES_REQUESTED** [review]
I'll hold approval until @pcenov / @radinamatic has a chance to do some manual QA here to be sure everything works as expected.

Overall, the code looks good. I added one thought about seemingly duplicitous code in how you're fetching facilities -- but I may be misreading there (cc @rtibbles @akolson ?) - so let's see what the outcome of some discussion around this brings us in the mean time.

**Comment by nucleogenesis** [comment]
@Wck-iipi I'm not seeing why the tests are failing in the Github Actions output - can you run `yarn test` locally to see if things fail there? If tests pass locally, then it's likely an issue with the Github Action or something.

**Comment by Wck-iipi** [comment]
@nucleogenesis Sorry about the test cases failing, I ran tests on my branch and then on develop and both were failing day before yesterday so I thought my code didn't break anything. 
The reason for the tests failing was that it was expecting more `KRadioButton` whereas I had set the condition to only show the KRadioButton if you could sign up through them. Therefore, it expected 6 and got 0 KRadioButtons.
Therefore, I now have disabled the KRadioButton instead of hiding it so that it can pass the tests, and removed the unnecessary code.
The continue button, however, still is taking us to the sign up page irrespective of whether we have selected KRadioButton or not. This hasn't been fixed yet and I can fix it if you want to.
Regarding `commonSyncElements`, I tried to await and pass `device.id` to `fetchNetworkLocationFacilities` but it is not working at all and is giving no output. I couldn't even debug the error, it just doesn't respond. Thanks again for guiding me.

**Review by nucleogenesis — CHANGES_REQUESTED** [review]
@Wck-iipi  I learned in a follow-up discussion with @bjester that the logic used here is duplicitous of code already available between `useDevices` and the `SelectDeviceModalGroup/api.js`.

This logic I believe should instead implement a filtering function which checks if a device has a facility with sign-ups allowed. This would be akin to the [`facilityIsAvailableAtDevice`](https://github.com/learningequality/kolibri/blob/545ceaedb682e694f830233fd3ed7ba442391df0/kolibri/core/assets/src/views/sync/SelectDeviceModalGroup/api.js#L31-L35) function.

However, the new function would just take the `deviceId` and return if any of the facilities have the ability to allow sign ups like this (I've not tested this):

```
export function deviceFacilityCanSignUp(deviceId) {
    return NetworkLocationResource.fetchFacilities(deviceId)
        .then(({ facilities }) => {
             return facilities.some(f => f.learner_can_sign_up));
        });
}
```

In this case then, we can get the list of devices using `useDevicesForLearnOnlyDevice` from `useDevices` to get a pre-filtered list of devices which is necessary for this particular case. Then iterate over these devices, calling the new function above for each device, and you can then know which devices should be shown in this case.

In this case now the `SelectDeviceForm` doesn't have to worry about maintaining a list of facilities, but rather can just hone in on which devices are useful in a particular case.

---

The change requests here are substantial -- essentially reworking most of what you've added. This issue is also a relatively urgent fix in our pipeline, which I want to share because we don't expect that your contributions will necessarily align with our plans.

If you'd like to take another shot this week, please let me know along with any questions and I'll do my best to clarify. If not, then I totally understand and greatly appreciate the work you've put in on this. It opened up a greater discussion around keeping our code extensible which is invaluable in any case.

**Comment by Wck-iipi** [comment]
@nucleogenesis I would love to continue to work on this.

**Comment by Wck-iipi** [comment]
@nucleogenesis I have made some changes. Is this in the right direction?
Also, I don't know how to filter `LODDevicesWithSignUpFacility` with promise in `deviceFacilityCanSignUp` in 
```
const LODDevicesWithSignUpFacility = computed(() =>
  get(devices).filter(async (d) => {
    await deviceFacilityCanSignUp(d.id)
  })
);
```
and would love your guidance. Thanks.

**Comment by nucleogenesis** [comment]
I wonder if maybe `computedAsync` would help out in this case?

In any case, perhaps if `deviceFacilityCanSignUp` returned an object w/ the device ID like `{ deviceId: uuid, canSignUp: bool }` then you could map the devices and use Promise.all:

```
Promise.all(
    get(devices).map(d => deviceFacilityCanSignUp(d.id)
).then(resolvedValues => {
    // resolvedValues would be a list of those objects with the `deviceId` and `canSignUp` keys
    // so then now we have a list of deviceIds which match what we care about so we can return get(devices) filtered by that
});
```

... _I think_ ... I hope that helps :sweat_smile: 

---

The latest commit looks like you're headed in the right direction :slightly_smiling_face: :rocket:

**Comment by Wck-iipi** [comment]
@nucleogenesis I have added the required code. However, this won't pass 2 tests. The first one
```
 {
    id: '1',
    instance_id: '1',
    nickname: 'Available Server',
    base_url: 'http://localhost:8000',
    application: 'kolibri',
    available: true,
},
```
sends above data and expects the KRadioButton to be enabled. But it is disabled as no information about the SignUp is provided([this](https://github.com/learningequality/kolibri/pull/10703/commits/3e1e158910fe2ce17018891f1a64bda9e7673c06#:~:text=%3Adisabled%3D%22!canLearnerSignUp(d.id)%20%7C%7C%20formDisabled%20%7C%7C%20!isDeviceAvailable(d.id)%22) line to be exact is causing the KRadioButton of dynamic device to be disabled). I can update the test case if you want to.

About the second test case failing, I have absolutely no idea why it is failing, `LearningActivityBar` is not even related to my commit. I ran tests on develop branch as well but it gave same test as wrong. Can you please check if the second test `LearningActivityBar › on a large screen › download › doesn't show the downloading loader by default` is failing due to my commit or not. Thanks again for your guidance.

File: kolibri/core/assets/src/views/sync/SelectDeviceModalGroup/SelectDeviceForm.vue [hunk 3]
```diff
@@ -356,6 +379,14 @@
...
         });
       },
+      canLearnerSignUp(id) {
+        if (this.LODDevicesWithSignUpFacility) {
+          if (id in this.LODDevicesWithSignUpFacility) {
+            return true;
+          }
+        }
+        return false;
+      },
```
Comment (akolson) [inline kolibri/core/assets/src/views/sync/SelectDeviceModalGroup/SelectDeviceForm.vue:394]: Non blocking, but I would reduce the nesting in this function to;

```
canLearnerSignUp(id) {
    return this.LODDevicesWithSignUpFacility && id in this.LODDevicesWithSignUpFacility;
},
```
and probably use `lodsWithSignupFacility` as variable instead of  `LODDevicesWithSignUpFacility`(because LOD-Learn-only Device(s) :))

File: kolibri/core/assets/src/views/sync/SelectDeviceModalGroup/SelectDeviceForm.vue [hunk 4]
```diff
@@ -186,6 +190,24 @@
       const discoveredDevices = computed(() => get(devices).filter(d => d.dynamic));
       const savedDevices = computed(() => get(devices).filter(d => !d.dynamic));
 
+      const isLoading = ref(false);
```
Comment (nucleogenesis) [inline kolibri/core/assets/src/views/sync/SelectDeviceModalGroup/SelectDeviceForm.vue:203]: @Wck-iipi 

> Is it okay to show "There are no devices yet" when there are devices but there are none that can sign up or should I use another string?

I'm not seeing anywhere that this ref's value is being read back. This could be used to conditionally put a `<KCircularLoader />` component (which is globally available, no need to import it from anywhere) in place of where either the data or the "no data" message should go?

File: kolibri/core/assets/src/views/sync/SelectDeviceModalGroup/SelectDeviceForm.vue [hunk 5]
```diff
@@ -356,6 +379,14 @@
           this.$emit('removed_address');
         });
       },
+      canLearnerSignUp(id) {
+        if (this.LODDevicesWithSignUpFacility) {
```
Comment (nucleogenesis) [inline kolibri/core/assets/src/views/sync/SelectDeviceModalGroup/SelectDeviceForm.vue]: Because this is an `asyncComputed` property I think you should be using `isLoading` here as well because if the async operation hasn't resolved then we can just return false.

This is a place where managing tests can get really tough because you'll need to be sure that the async data is available, so I suspect that in the failing test you'll need to be sure that this new method is represented properly.

**Review by nucleogenesis — APPROVED** [review]
@Wck-iipi 

I apologize for my delay in re-reviewing your work here I should have come back to this much sooner.

I have tested it and it works as expected and the code updates all look great to me. 

I'm going to approve and merge this. From our whole team, thank you so much for taking this complex and critical issue and being patient with our feedback here as I know you have gone through your exams during this time. Your work is greatly appreciated and I hope we get to work with you again!

Please feel free to submit another PR adding your name and Github username to the AUTHORS.md file in the root of the repo if you'd like to be included there ❤️

**Comment by nucleogenesis** [comment]
Actually I'll fix the tests and push to your remote so we can get this merged 😄
