### PR TITLE
Keyboard navigation focus outline

### LINKED ISSUE #7651: keyboard focus outline is not visible on cards in Learn page
### Observed behavior

In this video [from this link](https://kolibri-beta.learningequality.org/en/learn/#/classes), I shift-tab until I am focused on the skip-link, hit enter, hit tab once, then am focused on the first card "Jessica's class" (I can confirm this because I keypress "Enter" and am taken to the right page). Yet, there is no green outline on the card. 

(Notice that some elements on the top nav aren't outlined either while back tabbing)

CleanShot 2020-10-29 at 11 42 56

(This happens in a lot of other areas, but fixing this in Learn will probably fix it globally)

### Expected behavior

Cards (which are anchor tags under the hood) get a green focus outline while in the keyboard modality.

### User-facing consequences

It's hard for keyboard-only users to know where they are focusing.

### Errors and logs

…

### Steps to reproduce

…

### Context

…

### PR DESCRIPTION
**Pull request by alexMet**
## Summary

Added keyboard focus outline to Channel card, Content cards and core menu links, removed the extra tab key press after the Navbar.

Removed an extra tab key press in the sign in page.

Before:

After:

### References

#7651 

----

### Contributor Checklist

PR process:

- [x] PR has the correct target branch and milestone
- [x] PR has 'needs review' or 'work-in-progress' label
- [ ] If PR is ready for review, a reviewer has been added. (Don't use 'Assignees')
- [x] If this is an important user-facing change, PR or related issue has a 'changelog' label
- [ ] If this includes an internal dependency change, a link to the diff is provided

Testing:

- [ ] Contributor has fully tested the PR manually
- [ ] If there are any front-end changes, before/after screenshots are included
- [ ] Critical user journeys are covered by Gherkin stories
- [ ] Critical and brittle code paths are covered by unit tests

### Reviewer Checklist

- Automated test coverage is satisfactory
- PR is fully functional
- PR has been tested for [accessibility regressions](http://kolibri-dev.readthedocs.io/en/develop/manual_testing.html#accessibility-a11y-testing)
- External dependency files were updated if necessary (`yarn` and `pip`)
- Documentation is updated
- Contributor is in AUTHORS.md

### CODE REVIEW

**Comment by jonboiser** [comment]
@alexMet , this is great! The focus outline was something we used to get without having to add classes and styles to individual elements, but your solution here is something we can apply to other parts of the code until we figure out how to fix that more global issue.

**Comment by alexMet** [comment]
@jonboiser It took me a while to figure out how this all works. Yes, this is a quick fix, a global one would be much better. I tried changing `<router-link>` to `<KRouterLink>` since the latter always handles the outline, but that didn't work. :)

**Comment by jonboiser** [comment]
> I tried changing `<router-link>` to `<KRouterLink>` since the latter always handles the outline, but that didn't work. :)

Oh, really? Why didn't that work?

**Comment by alexMet** [comment]
The outline works fine, but couldn't make the content inside the card show.

**Comment by jonboiser** [comment]
Ah, okay. I think `KRouterLink` usually works best with simple text only links, but I'll need to double-check if that's true or if there's something special about the Classes card links.

File: kolibri/core/assets/src/views/SideNav.vue [hunk 1]
```diff
@@ -1,6 +1,12 @@
 <template>
 
-  <div ref="sideNav" class="side-nav-wrapper" tabindex="0" @keyup.esc="toggleNav">
+  <div
+    v-show="navShown"
```
Comment (jonboiser) [inline kolibri/core/assets/src/views/SideNav.vue:4]: What does this `v-show` do?

Comment (alexMet) [reply kolibri/core/assets/src/views/SideNav.vue:4]: In a previous issue, I added the tabindex in order to close the side menu with the escape button. Because of that, you have to press the tab key 2 times in order to go from the navbar to the main content. So with the navShow the div can be hidden until you open the menu.
