### PR TITLE
Fix side panel alignment

### LINKED ISSUE #8827: [Regression] Side panel alignment updates have not be applied in all cases
Double check all places where the sidepanel is used: 
- ensure spacing is accurate on large medium and small screens
- ensure alignment is correct for both LTR and RTL languages
- ensure "X" is visible in all cases 
- focus trap is working in all cases 

https://www.notion.so/learningequality/REGRESSION-Learn-Viewing-Content-Workflow-29-a828497ca3354a3aa497f2b6aed8a5af
https://www.notion.so/learningequality/REGRESSION-Learn-Content-renderer-search-browse-29-Broken-fba0b651cd1c4260a1d3dea6d20310eb
https://www.notion.so/learningequality/REGRESSION-29-Learn-Content-Renderer-8e336fabdc564369be509254c9005e2e
https://www.notion.so/learningequality/FEATURE-BUG-folder-resources-side-bar-issues-a501b5d425714e548da183719bbb1c51

### PR DESCRIPTION
**Pull request by nucleogenesis**
## Summary

The side panel now shows on the correct sides per designs - the right in LTR - for the AlsoInThis, BrowseMetadata and CurrentlyViewed metadata side panels.

**Does not include fixed headers** - this will require more substantial reworking than we should try to get in today - will be done - along with some a11y improvements, this week. 

Also note @marcellamaki did most of the work here I just finished up a few things and tested it. I was hoping to combine her work on this bug with the fixed header but time ran out.

## References

Fixes #8827 

## Reviewer guidance

Check the side panels in RTL and LTR languages.

----

## Testing checklist

- [x] Contributor has fully tested the PR manually
- [ ] If there are any front-end changes, before/after screenshots are included
- [ ] Critical user journeys are covered by Gherkin stories
- [ ] Critical and brittle code paths are covered by unit tests

## PR process

- [x] PR has the correct target branch and milestone
- [x] PR has 'needs review' or 'work-in-progress' label
- [ ] If PR is ready for review, a reviewer has been added. (Don't use 'Assignees')
- [ ] If this is an important user-facing change, PR or related issue has a 'changelog' label
- [ ] If this includes an internal dependency change, a link to the diff is provided

## Reviewer checklist

- Automated test coverage is satisfactory
- PR is fully functional
- PR has been tested for [accessibility regressions](http://kolibri-dev.readthedocs.io/en/develop/manual_testing.html#accessibility-a11y-testing)
- External dependency files were updated if necessary (`yarn` and `pip`)
- Documentation is updated
- Contributor is in AUTHORS.md

### CODE REVIEW

File: kolibri/plugins/learn/assets/src/views/TopicsPage.vue [hunk 1]
```diff
@@ -285,6 +285,7 @@
       <FullScreenSidePanel
         v-if="!windowIsLarge && sidePanelIsOpen"
         class="full-screen-side-panel"
+        alignment="right"
```
Comment (marcellamaki) [inline kolibri/plugins/learn/assets/src/views/TopicsPage.vue]:
```suggestion
        alignment="left"
```

**Review by marcellamaki — CHANGES_REQUESTED** [review]
The only thing is to update the search panel to be left aligned, but other than that looks good to me!

**Review by marcellamaki — APPROVED** [review]
