### PR TITLE
Handle errored loading states better

### LINKED ISSUE #10124: Displaying English as an option for UI when it's *not* available
## Observed behavior

When English is not an option for the UI (e.g. because a language list was hard-coded as envars), it seems that English still shows up as an option. 

Furthermore, clicking on it returns that the resource is not found. I've confirmed with @rtibbles that English should not be an option if it's not available, so it seems the front-end should not include it as an option. 

Here are screenshots of the UI when only French was passed as an envar for languages/the UI setting:

image
image

## Errors and logs

N/A

## Expected behavior

Expected behavior per @rtibbles is that English **not** be displayed if it's not actually available/passed as an option

## User-facing consequences

User sees superfluous UI/language options; user could also be misled about options in which the app's UI is available in

## Steps to reproduce

I passed `["fr-fr"]` as an envar (via Terraform/BCK) to test the new UI language filter and noticed that English was always present as an option, even when not loaded/passed as an envar.

## Context

* Kolibri version
 0.15
 
 * Operating system
 Linux Mint 20.3 x86_64
 
 * Browser
 Firefox for Linux Mint: V 109.0.1 (64 bit)

### LINKED ISSUE #10393: Manage error handling, loading, disconnection, and download bugs on remote content browsing
## Observed behavior
During the dev bug bash for remote content browsing, the following issues were reported: 

- [x] Not declaring encoding, which will cause issues in python2
         <details>
             ```
             kolibri/plugins/user_profile/viewsets.py SyntaxError: Non-ASCII character '\xc3' in file /home/richard/.pex/install/kolibri- 
             0.16.0.dev0+git.20230203154327-py2.py3-none-any.whl.f6ac28c417e5b00600b838c204060fc99b67c6df/kolibri- 
             0.16.0.dev0+git.20230203154327-py2.py3-none-any.whl/kolibri/plug on line 16, but no encoding declared;
             ```
          </details>

- [x] FileDownload object has no attribute _content_iterator
          <details>
             ```
            Traceback (most recent call last):
             File "/home/bjester/.pex/install/kolibri-0.16.0.dev0+git.20230203154327-py2.py3-none- 
             any.whl.f6ac28c417e5b00600b838c204060fc99b67c6df/kolibri-0.16.0.dev0+git.20230203154327-py2.py3-none- 
             any.whl/kolibri/dist/cheroot/server.py", line 1300, in communicate
             req.respond()
             File "/home/bjester/.pex/install/kolibri-0.16.0.dev0+git.20230203154327-py2.py3-none- 
             any.whl.f6ac28c417e5b00600b838c204060fc99b67c6df/kolibri-0.16.0.dev0+git.20230203154327-py2.py3-none- 
             any.whl/kolibri/dist/cheroot/server.py", line 1090, in respond
             self.server.gateway(self).respond()
            File "/home/bjester/.pex/install/kolibri-0.16.0.dev0+git.20230203154327-py2.py3-none- 
            any.whl.f6ac28c417e5b00600b838c204060fc99b67c6df/kolibri-0.16.0.dev0+git.20230203154327-py2.py3-none- 
            any.whl/kolibri/dist/cheroot/wsgi.py", line 150, in respond
            response.close()
            File "/home/bjester/.pex/install/kolibri-0.16.0.dev0+git.20230203154327-py2.py3-none-a 
            ny.whl.f6ac28c417e5b00600b838c204060fc99b67c6df/kolibri-0.16.0.dev0+git.20230203154327-py2.py3-none- 
            any.whl/kolibri/utils/file_transfer.py", line 438, in close
            self.read()
              File "/home/bjester/.pex/install/kolibri-0.16.0.dev0+git.20230203154327-py2.py3-none-            
             any.whl.f6ac28c417e5b00600b838c204060fc99b67c6df/kolibri-0.16.0.dev0+git.20230203154327-py2.py3-none-            
            any.whl/kolibri/utils/file_transfer.py", line 426, in read
             data += next(self.transfer)
              File "/home/bjester/.pex/install/kolibri-0.16.0.dev0+git.20230203154327-py2.py3-none-             
             any.whl.f6ac28c417e5b00600b838c204060fc99b67c6df/kolibri-0.16.0.dev0+git.20230203154327-py2.py3-none- 
             any.whl/kolibri/utils/file_transfer.py", line 311, in next
             chunk = super(FileDownload, self).next()
             File "/home/bjester/.pex/install/kolibri-0.16.0.dev0+git.20230203154327-py2.py3-none- 
             any.whl.f6ac28c417e5b00600b838c204060fc99b67c6df/kolibri-0.16.0.dev0+git.20230203154327-py2.py3-none- 
             any.whl/kolibri/utils/file_transfer.py", line 172, in next
              chunk = next(self._content_iterator)
              AttributeError: 'FileDownload' object has no attribute '_content_iterator'
             ```
         </details>

- [ ] Possibly related to the content iterator bug: When loading a video the first unbounded range request errors, but the second bounded range request succeeds.
- [x] Redirect in topic navigation fails to preserve device id, and as a result the back button in content renderer doesn’t seem to be working consistently
- [ ] Blank screen on browsing through a resource in a network: There is about a 3-5 second lag between a clicking a resource item and it being displayed. A Blank screen is presented during this lag
- [ ] Error management when devices are going on and off the shared network or when a stream is interrupted, particularly for video
         <details>
         image (19)
         Screenshot 2023-04-06 at 9 08 57 AM
         Screenshot 2023-04-06 at 9 09 24 AM
         Screenshot 2023-04-06 at 9 09 41 AM
         Screenshot 2023-02-03 at 12 38 40 PM
         </details>

- [ ] Cannot load channel metadata when trying to import from remote (from Allan) - I can get to listing his channels but cannot get to where it lists (task status stuff inside)
<details>
```
[{"status":"COMPLETED","type":"kolibri.core.content.tasks.remotecontentimport","exception":null,"traceback":"","percentage":1.0,"id":"1812028d98ab4b42bcbcba16dd96cf69","cancellable":true,"clearable":true,"facility_id":null,"extra_metadata":{"channel_name":"a","channel_id":"6d998135795c4c93ad46001bd0736da3","peer_id":null,"started_by":"12a6d3e46eada069a592cebfbd5e2fbc","started_by_username":"a","file_size":1009174,"total_resources":6,"transferred_file_size":1009174,"transferred_resources":6}},{"status":"FAILED","type":"kolibri.core.content.tasks.remotechannelimport","exception":"DatabaseError","traceback":"Traceback (most recent call last):\n  File \"/home/jacob/.pex/install/kolibri-0.16.0.dev0+git.20230203154327-py2.py3-none-any.whl.f6ac28c417e5b00600b838c204060fc99b67c6df/kolibri-0.16.0.dev0+git.20230203154327-py2.py3-none-any.whl/kolibri/dist/sqlalchemy/engine/base.py\", line 1900, in _execute_context\n    self.dialect.do_execute(\n  File \"/home/jacob/.pex/install/kolibri-0.16.0.dev0+git.20230203154327-py2.py3-none-any.whl.f6ac28c417e5b00600b838c204060fc99b67c6df/kolibri-0.16.0.dev0+git.20230203154327-py2.py3-none-any.whl/kolibri/dist/sqlalchemy/engine/default.py\", line 736, in do_execute\n    cursor.execute(statement, parameters)\nsqlite3.DatabaseError: database disk image is malformed\n\nThe above exception was the direct cause of the following exception:\n\nTraceback (most recent call last):\n  File \"/home/jacob/.pex/install/kolibri-0.16.0.dev0+git.20230203154327-py2.py3-none-any.whl.f6ac28c417e5b00600b838c204060fc99b67c6df/kolibri-0.16.0.dev0+git.20230203154327-py2.py3-none-any.whl/kolibri/core/tasks/job.py\", line 270, in execute\n    result = func(*args, **kwargs)\n  File \"/home/jacob/.pex/install/kolibri-0.16.0.dev0+git.20230203154327-py2.py3-none-any.whl.f6ac28c417e5b00600b838c204060fc99b67c6df/kolibri-0.16.0.dev0+git.20230203154327-py2.py3-none-any.whl/kolibri/core/tasks/registry.py\", line 223, in __call__\n    return self.func(*args, **kwargs)\n  File \"/home/jacob/.pex/install/kolibri-0.16.0.dev0+git.20230203154327-py2.py3-none-any.whl.f6ac28c417e5b00600b838c204060fc99b67c6df/kolibri-0.16.0.dev0+git.20230203154327-py2.py3-none-any.whl/kolibri/core/content/tasks.py\", line 176, in remotechannelimport\n    call_command(\n  File \"/home/jacob/.pex/install/kolibri-0.16.0.dev0+git.20230203154327-py2.py3-none-any.whl.f6ac28c417e5b00600b838c204060fc99b67c6df/kolibri-0.16.0.dev0+git.20230203154327-py2.py3-none-any.whl/kolibri/dist/django/core/management/__init__.py\", line 131, in call_command\n    return command.execute(*args, **defaults)\n  File \"/home/jacob/.pex/install/kolibri-0.16.0.dev0+git.20230203154327-py2.py3-none-any.whl.f6ac28c417e5b00600b838c204060fc99b67c6df/kolibri-0.16.0.dev0+git.20230203154327-py2.py3-none-any.whl/kolibri/dist/django/core/management/base.py\", line 330, in execute\n    output = self.handle(*args, **options)\n  File \"/home/jacob/.pex/install/kolibri-0.16.0.dev0+git.20230203154327-py2.py3-none-any.whl.f6ac28c417e5b00600b838c204060fc99b67c6df/kolibri-0.16.0.dev0+git.20230203154327-py2.py3-none-any.whl/kolibri/core/tasks/management/commands/base.py\", line 28, in handle\n    return self.handle_async(*args, **options)\n  File \"/home/jacob/.pex/install/kolibri-0.16.0.dev0+git.20230203154327-py2.py3-none-any.whl.f6ac28c417e5b00600b838c204060fc99b67c6df/kolibri-0.16.0.dev0+git.20230203154327-py2.py3-none-any.whl/kolibri/core/content/management/commands/importchannel.py\", line 229, in handle_async\n    self.download_channel(\n  File \"/home/jacob/.pex/install/kolibri-0.16.0.dev0+git.20230203154327-py2.py3-none-any.whl.f6ac28c417e5b00600b838c204060fc99b67c6df/kolibri-0.16.0.dev0+git.20230203154327-py2.py3-none-any.whl/kolibri/core/content/management/commands/importchannel.py\", line 106, in download_channel\n    self._transfer(\n  File \"/home/jacob/.pex/install/kolibri-0.16.0.dev0+git.20230203154327-py2.py3-none-any.whl.f6ac28c417e5b00600b838c204060fc99b67c6df/kolibri-0.16.0.dev0+git.20230203154327-py2.py3-none-any.whl/kolibri/core/content/management/commands/importchannel.py\", line 169, in _transfer\n    self._start_file_transfer(\n  File \"/home/jacob/.pex/install/kolibri-0.16.0.dev0+git.20230203154327-py2.py3-none-any.whl.f6ac28c417e5b00600b838c204060fc99b67c6df/kolibri-0.16.0.dev0+git.20230203154327-py2.py3-none-any.whl/kolibri/core/content/management/commands/importchannel.py\", line 214, in _start_file_transfer\n    import_ran = import_channel_by_id(\n  File \"/home/jacob/.pex/install/kolibri-0.16.0.dev0+git.20230203154327-py2.py3-none-any.whl.f6ac28c417e5b00600b838c204060fc99b67c6df/kolibri-0.16.0.dev0+git.20230203154327-py2.py3-none-any.whl/kolibri/core/content/management/commands/importchannel.py\", line 26, in import_channel_by_id\n    return channel_import.import_channel_from_local_db(\n  File \"/home/jacob/.pex/install/kolibri-0.16.0.dev0+git.20230203154327-py2.py3-none-any.whl.f6ac28c417e5b00600b838c204060fc99b67c6df/kolibri-0.16.0.dev0+git.20230203154327-py2.py3-none-any.whl/kolibri/core/content/utils/channel_import.py\", line 1199, in import_channel_from_local_db\n    channel_metadata = read_channel_metadata_from_db_file(source)\n  File \"/home/jacob/.pex/install/kolibri-0.16.0.dev0+git.20230203154327-py2.py3-none-any.whl.f6ac28c417e5b00600b838c204060fc99b67c6df/kolibri-0.16.0.dev0+git.20230203154327-py2.py3-none-any.whl/kolibri/core/content/utils/channels.py\", line 85, in read_channel_metadata_from_db_file\n    source = Bridge(sqlite_file_path=channeldbpath)\n  File \"/home/jacob/.pex/install/kolibri-0.16.0.dev0+git.20230203154327-py2.py3-none-any.whl.f6ac28c417e5b00600b838c204060fc99b67c6df/kolibri-0.16.0.dev0+git.20230203154327-py2.py3-none-any.whl/kolibri/core/content/utils/sqlalchemybridge.py\", line 296, in __init__\n    db_matches_schema(BASES[self.schema_version], self.engine)\n  File \"/home/jacob/.pex/install/kolibri-0.16.0.dev0+git.20230203154327-py2.py3-none-any.whl.f6ac28c417e5b00600b838c204060fc99b67c6df/kolibri-0.16.0.dev0+git.20230203154327-py2.py3-none-any.whl/kolibri/core/content/utils/check_schema_db.py\", line 22, in db_matches_schema\n    tables = iengine.get_table_names()\n  File \"/home/jacob/.pex/install/kolibri-0.16.0.dev0+git.20230203154327-py2.py3-none-any.whl.f6ac28c417e5b00600b838c204060fc99b67c6df/kolibri-0.16.0.dev0+git.20230203154327-py2.py3-none-any.whl/kolibri/dist/sqlalchemy/engine/reflection.py\", line 266, in get_table_names\n    return self.dialect.get_table_names(\n  File \"<string>\", line 2, in get_table_names\n  File \"/home/jacob/.pex/install/kolibri-0.16.0.dev0+git.20230203154327-py2.py3-none-any.whl.f6ac28c417e5b00600b838c204060fc99b67c6df/kolibri-0.16.0.dev0+git.20230203154327-py2.py3-none-any.whl/kolibri/dist/sqlalchemy/engine/reflection.py\", line 55, in cache\n    ret = fn(self, con, *args, **kw)\n  File \"/home/jacob/.pex/install/kolibri-0.16.0.dev0+git.20230203154327-py2.py3-none-any.whl.f6ac28c417e5b00600b838c204060fc99b67c6df/kolibri-0.16.0.dev0+git.20230203154327-py2.py3-none-any.whl/kolibri/dist/sqlalchemy/dialects/sqlite/base.py\", line 1992, in get_table_names\n    rs = connection.exec_driver_sql(s)\n  File \"/home/jacob/.pex/install/kolibri-0.16.0.dev0+git.20230203154327-py2.py3-none-any.whl.f6ac28c417e5b00600b838c204060fc99b67c6df/kolibri-0.16.0.dev0+git.20230203154327-py2.py3-none-any.whl/kolibri/dist/sqlalchemy/engine/base.py\", line 1760, in exec_driver_sql\n    return self._exec_driver_sql(\n  File \"/home/jacob/.pex/install/kolibri-0.16.0.dev0+git.20230203154327-py2.py3-none-any.whl.f6ac28c417e5b00600b838c204060fc99b67c6df/kolibri-0.16.0.dev0+git.20230203154327-py2.py3-none-any.whl/kolibri/dist/sqlalchemy/engine/base.py\", line 1669, in _exec_driver_sql\n    ret = self._execute_context(\n  File \"/home/jacob/.pex/install/kolibri-0.16.0.dev0+git.20230203154327-py2.py3-none-any.whl.f6ac28c417e5b00600b838c204060fc99b67c6df/kolibri-0.16.0.dev0+git.20230203154327-py2.py3-none-any.whl/kolibri/dist/sqlalchemy/engine/base.py\", line 1943, in _execute_context\n    self._handle_dbapi_exception(\n  File \"/home/jacob/.pex/install/kolibri-0.16.0.dev0+git.20230203154327-py2.py3-none-any.whl.f6ac28c417e5b00600b838c204060fc99b67c6df/kolibri-0.16.0.dev0+git.20230203154327-py2.py3-none-any.whl/kolibri/dist/sqlalchemy/engine/base.py\", line 2124, in _handle_dbapi_exception\n    util.raise_(\n  File \"/home/jacob/.pex/install/kolibri-0.16.0.dev0+git.20230203154327-py2.py3-none-any.whl.f6ac28c417e5b00600b838c204060fc99b67c6df/kolibri-0.16.0.dev0+git.20230203154327-py2.py3-none-any.whl/kolibri/dist/sqlalchemy/util/compat.py\", line 210, in raise_\n    raise exception\n  File \"/home/jacob/.pex/install/kolibri-0.16.0.dev0+git.20230203154327-py2.py3-none-any.whl.f6ac28c417e5b00600b838c204060fc99b67c6df/kolibri-0.16.0.dev0+git.20230203154327-py2.py3-none-any.whl/kolibri/dist/sqlalchemy/engine/base.py\", line 1900, in _execute_context\n    self.dialect.do_execute(\n  File \"/home/jacob/.pex/install/kolibri-0.16.0.dev0+git.20230203154327-py2.py3-none-any.whl.f6ac28c417e5b00600b838c204060fc99b67c6df/kolibri-0.16.0.dev0+git.20230203154327-py2.py3-none-any.whl/kolibri/dist/sqlalchemy/engine/default.py\", line 736, in do_execute\n    cursor.execute(statement, parameters)\nsqlalchemy.exc.DatabaseError: (sqlite3.DatabaseError) database disk image is malformed\n[SQL: SELECT name FROM sqlite_master WHERE type='table' ORDER BY name]\n(Background on this error at: https://sqlalche.me/e/14/4xp6)\n","percentage":0,"id":"d415dff2e7f4499cb05375f0cfb884f9","cancellable":true,"clearable":true,"facility_id":null,"extra_metadata":{"channel_name":"Global Digital Library - Book Catalog","channel_id":"0e173fca6e9052f8a474a2fb84055faf","peer_id":"650bdd48dc0cfc6b2ef8e0f2b09f5dcc","started_by":"12a6d3e46eada069a592cebfbd5e2fbc","started_by_username":"a"}},{"status":"FAILED","type":"kolibri.core.content.tasks.remotechannelimport","exception":"DatabaseError","traceback":"Traceback (most recent call last):\n  File \"/home/jacob/.pex/install/kolibri-0.16.0.dev0+git.20230203154327-py2.py3-none-any.whl.f6ac28c417e5b00600b838c204060fc99b67c6df/kolibri-0.16.0.dev0+git.20230203154327-py2.py3-none-any.whl/kolibri/dist/sqlalchemy/engine/base.py\", line 1900, in _execute_context\n    self.dialect.do_execute(\n  File \"/home/jacob/.pex/install/kolibri-0.16.0.dev0+git.20230203154327-py2.py3-none-any.whl.f6ac28c417e5b00600b838c204060fc99b67c6df/kolibri-0.16.0.dev0+git.20230203154327-py2.py3-none-any.whl/kolibri/dist/sqlalchemy/engine/default.py\", line 736, in do_execute\n    cursor.execute(statement, parameters)\nsqlite3.DatabaseError: database disk image is malformed\n\nThe above exception was the direct cause of the following exception:\n\nTraceback (most recent call last):\n  File \"/home/jacob/.pex/install/kolibri-0.16.0.dev0+git.20230203154327-py2.py3-none-any.whl.f6ac28c417e5b00600b838c204060fc99b67c6df/kolibri-0.16.0.dev0+git.20230203154327-py2.py3-none-any.whl/kolibri/core/tasks/job.py\", line 270, in execute\n    result = func(*args, **kwargs)\n  File \"/home/jacob/.pex/install/kolibri-0.16.0.dev0+git.20230203154327-py2.py3-none-any.whl.f6ac28c417e5b00600b838c204060fc99b67c6df/kolibri-0.16.0.dev0+git.20230203154327-py2.py3-none-any.whl/kolibri/core/tasks/registry.py\", line 223, in __call__\n    return self.func(*args, **kwargs)\n  File \"/home/jacob/.pex/install/kolibri-0.16.0.dev0+git.20230203154327-py2.py3-none-any.whl.f6ac28c417e5b00600b838c204060fc99b67c6df/kolibri-0.16.0.dev0+git.20230203154327-py2.py3-none-any.whl/kolibri/core/content/tasks.py\", line 176, in remotechannelimport\n    call_command(\n  File \"/home/jacob/.pex/install/kolibri-0.16.0.dev0+git.20230203154327-py2.py3-none-any.whl.f6ac28c417e5b00600b838c204060fc99b67c6df/kolibri-0.16.0.dev0+git.20230203154327-py2.py3-none-any.whl/kolibri/dist/django/core/management/__init__.py\", line 131, in call_command\n    return command.execute(*args, **defaults)\n  File \"/home/jacob/.pex/install/kolibri-0.16.0.dev0+git.20230203154327-py2.py3-none-any.whl.f6ac28c417e5b00600b838c204060fc99b67c6df/kolibri-0.16.0.dev0+git.20230203154327-py2.py3-none-any.whl/kolibri/dist/django/core/management/base.py\", line 330, in execute\n    output = self.handle(*args, **options)\n  File \"/home/jacob/.pex/install/kolibri-0.16.0.dev0+git.20230203154327-py2.py3-none-any.whl.f6ac28c417e5b00600b838c204060fc99b67c6df/kolibri-0.16.0.dev0+git.20230203154327-py2.py3-none-any.whl/kolibri/core/tasks/management/commands/base.py\", line 28, in handle\n    return self.handle_async(*args, **options)\n  File \"/home/jacob/.pex/install/kolibri-0.16.0.dev0+git.20230203154327-py2.py3-none-any.whl.f6ac28c417e5b00600b838c204060fc99b67c6df/kolibri-0.16.0.dev0+git.20230203154327-py2.py3-none-any.whl/kolibri/core/content/management/commands/importchannel.py\", line 229, in handle_async\n    self.download_channel(\n  File \"/home/jacob/.pex/install/kolibri-0.16.0.dev0+git.20230203154327-py2.py3-none-any.whl.f6ac28c417e5b00600b838c204060fc99b67c6df/kolibri-0.16.0.dev0+git.20230203154327-py2.py3-none-any.whl/kolibri/core/content/management/commands/importchannel.py\", line 106, in download_channel\n    self._transfer(\n  File \"/home/jacob/.pex/install/kolibri-0.16.0.dev0+git.20230203154327-py2.py3-none-any.whl.f6ac28c417e5b00600b838c204060fc99b67c6df/kolibri-0.16.0.dev0+git.20230203154327-py2.py3-none-any.whl/kolibri/core/content/management/commands/importchannel.py\", line 169, in _transfer\n    self._start_file_transfer(\n  File \"/home/jacob/.pex/install/kolibri-0.16.0.dev0+git.20230203154327-py2.py3-none-any.whl.f6ac28c417e5b00600b838c204060fc99b67c6df/kolibri-0.16.0.dev0+git.20230203154327-py2.py3-none-any.whl/kolibri/core/content/management/commands/importchannel.py\", line 214, in _start_file_transfer\n    import_ran = import_channel_by_id(\n  File \"/home/jacob/.pex/install/kolibri-0.16.0.dev0+git.20230203154327-py2.py3-none-any.whl.f6ac28c417e5b00600b838c204060fc99b67c6df/kolibri-0.16.0.dev0+git.20230203154327-py2.py3-none-any.whl/kolibri/core/content/management/commands/importchannel.py\", line 26, in import_channel_by_id\n    return channel_import.import_channel_from_local_db(\n  File \"/home/jacob/.pex/install/kolibri-0.16.0.dev0+git.20230203154327-py2.py3-none-any.whl.f6ac28c417e5b00600b838c204060fc99b67c6df/kolibri-0.16.0.dev0+git.20230203154327-py2.py3-none-any.whl/kolibri/core/content/utils/channel_import.py\", line 1199, in import_channel_from_local_db\n    channel_metadata = read_channel_metadata_from_db_file(source)\n  File \"/home/jacob/.pex/install/kolibri-0.16.0.dev0+git.20230203154327-py2.py3-none-any.whl.f6ac28c417e5b00600b838c204060fc99b67c6df/kolibri-0.16.0.dev0+git.20230203154327-py2.py3-none-any.whl/kolibri/core/content/utils/channels.py\", line 85, in read_channel_metadata_from_db_file\n    source = Bridge(sqlite_file_path=channeldbpath)\n  File \"/home/jacob/.pex/install/kolibri-0.16.0.dev0+git.20230203154327-py2.py3-none-any.whl.f6ac28c417e5b00600b838c204060fc99b67c6df/kolibri-0.16.0.dev0+git.20230203154327-py2.py3-none-any.whl/kolibri/core/content/utils/sqlalchemybridge.py\", line 296, in __init__\n    db_matches_schema(BASES[self.schema_version], self.engine)\n  File \"/home/jacob/.pex/install/kolibri-0.16.0.dev0+git.20230203154327-py2.py3-none-any.whl.f6ac28c417e5b00600b838c204060fc99b67c6df/kolibri-0.16.0.dev0+git.20230203154327-py2.py3-none-any.whl/kolibri/core/content/utils/check_schema_db.py\", line 22, in db_matches_schema\n    tables = iengine.get_table_names()\n  File \"/home/jacob/.pex/install/kolibri-0.16.0.dev0+git.20230203154327-py2.py3-none-any.whl.f6ac28c417e5b00600b838c204060fc99b67c6df/kolibri-0.16.0.dev0+git.20230203154327-py2.py3-none-any.whl/kolibri/dist/sqlalchemy/engine/reflection.py\", line 266, in get_table_names\n    return self.dialect.get_table_names(\n  File \"<string>\", line 2, in get_table_names\n  File \"/home/jacob/.pex/install/kolibri-0.16.0.dev0+git.20230203154327-py2.py3-none-any.whl.f6ac28c417e5b00600b838c204060fc99b67c6df/kolibri-0.16.0.dev0+git.20230203154327-py2.py3-none-any.whl/kolibri/dist/sqlalchemy/engine/reflection.py\", line 55, in cache\n    ret = fn(self, con, *args, **kw)\n  File \"/home/jacob/.pex/install/kolibri-0.16.0.dev0+git.20230203154327-py2.py3-none-any.whl.f6ac28c417e5b00600b838c204060fc99b67c6df/kolibri-0.16.0.dev0+git.20230203154327-py2.py3-none-any.whl/kolibri/dist/sqlalchemy/dialects/sqlite/base.py\", line 1992, in get_table_names\n    rs = connection.exec_driver_sql(s)\n  File \"/home/jacob/.pex/install/kolibri-0.16.0.dev0+git.20230203154327-py2.py3-none-any.whl.f6ac28c417e5b00600b838c204060fc99b67c6df/kolibri-0.16.0.dev0+git.20230203154327-py2.py3-none-any.whl/kolibri/dist/sqlalchemy/engine/base.py\", line 1760, in exec_driver_sql\n    return self._exec_driver_sql(\n  File \"/home/jacob/.pex/install/kolibri-0.16.0.dev0+git.20230203154327-py2.py3-none-any.whl.f6ac28c417e5b00600b838c204060fc99b67c6df/kolibri-0.16.0.dev0+git.20230203154327-py2.py3-none-any.whl/kolibri/dist/sqlalchemy/engine/base.py\", line 1669, in _exec_driver_sql\n    ret = self._execute_context(\n  File \"/home/jacob/.pex/install/kolibri-0.16.0.dev0+git.20230203154327-py2.py3-none-any.whl.f6ac28c417e5b00600b838c204060fc99b67c6df/kolibri-0.16.0.dev0+git.20230203154327-py2.py3-none-any.whl/kolibri/dist/sqlalchemy/engine/base.py\", line 1943, in _execute_context\n    self._handle_dbapi_exception(\n  File \"/home/jacob/.pex/install/kolibri-0.16.0.dev0+git.20230203154327-py2.py3-none-any.whl.f6ac28c417e5b00600b838c204060fc99b67c6df/kolibri-0.16.0.dev0+git.20230203154327-py2.py3-none-any.whl/kolibri/dist/sqlalchemy/engine/base.py\", line 2124, in _handle_dbapi_exception\n    util.raise_(\n  File \"/home/jacob/.pex/install/kolibri-0.16.0.dev0+git.20230203154327-py2.py3-none-any.whl.f6ac28c417e5b00600b838c204060fc99b67c6df/kolibri-0.16.0.dev0+git.20230203154327-py2.py3-none-any.whl/kolibri/dist/sqlalchemy/util/compat.py\", line 210, in raise_\n    raise exception\n  File \"/home/jacob/.pex/install/kolibri-0.16.0.dev0+git.20230203154327-py2.py3-none-any.whl.f6ac28c417e5b00600b838c204060fc99b67c6df/kolibri-0.16.0.dev0+git.20230203154327-py2.py3-none-any.whl/kolibri/dist/sqlalchemy/engine/base.py\", line 1900, in _execute_context\n    self.dialect.do_execute(\n  File \"/home/jacob/.pex/install/kolibri-0.16.0.dev0+git.20230203154327-py2.py3-none-any.whl.f6ac28c417e5b00600b838c204060fc99b67c6df/kolibri-0.16.0.dev0+git.20230203154327-py2.py3-none-any.whl/kolibri/dist/sqlalchemy/engine/default.py\", line 736, in do_execute\n    cursor.execute(statement, parameters)\nsqlalchemy.exc.DatabaseError: (sqlite3.DatabaseError) database disk image is malformed\n[SQL: SELECT name FROM sqlite_master WHERE type='table' ORDER BY name]\n(Background on this error at: https://sqlalche.me/e/14/4xp6)\n","percentage":0,"id":"99d0b4af37874555af4818a0a1bfbdec","cancellable":true,"clearable":true,"facility_id":null,"extra_metadata":{"channel_name":"Global Digital Library - Book Catalog","channel_id":"0e173fca6e9052f8a474a2fb84055faf","peer_id":"650bdd48dc0cfc6b2ef8e0f2b09f5dcc","started_by":"12a6d3e46eada069a592cebfbd5e2fbc","started_by_username":"a"}}]
```
</details> 

## Expected behavior
- Error and loading states should be handled gracefully within the UI
- videojs and HTML5 content areas will probably need different handling, based on the rendering of those file types and how that interacts with the current remote browsing mechanism (HTML5 needs to be downloaded in order to unpack and work, videojs should be doing some chunk diffing to check for things going wrong)

## Context
Across browsers and OSes, `develop`

### LINKED ISSUE #10603: Progress on content is still being tracked when the resource does not load
## Observed behavior
Reported by @nucleogenesis[ in the alpha 13 bug bash ](https://www.notion.so/learningequality/Progress-on-content-is-still-being-tracked-when-the-resource-does-not-load-42291a7d67b74f308a54e8686d75ef9d?pvs=4)

> Related to the[ “resource not available” bug ](https://github.com/learningequality/kolibri/issues/10602)I noted above — despite the content not loading, I can see that I have 25% of progress because I was writing up my bug with the content renderer still open

## Expected behavior
Resource should load, and progress should only occur for a resource that the user is actively interacting with

## User-facing consequences
Could incorrectly reflect progress - which would be confusing to coaches and learners

## Steps to reproduce
Access a remote zip content resource, and allow the browser 

## Context
v0.16.0-a13

### PR DESCRIPTION
**Pull request by rtibbles**
## Summary
* Rehomes KContentRenderer in Kolibri from KDS
* Simplifies its implementation which had been made more complex for the abstraction into KDS
* Set language globals in the module scope, as there's no longer a need to defer them, and it could negatively affect the languageDirection used in the pluginMediator
* Updates ContentPage.vue to stop tracking progress when content renderer errors
* Fixes long standing bug where activity in renderers was not properly toggling on learner activity for the session
* Updates the zip content backend to return HTML pages with embedded meta to allow reading for error reports once the iframe has loaded
* Defines a LOADING_ERROR constant and uses it to emit loading errors from all the content renderers
* Handles these loading errors in TopicsContentPage when there is a defined deviceId and shows a modal inviting the user to return to all libraries
* Adds additional error alerts with a 'report this problem' pop up to allow users to more easily report errors with specific resources
* Adds a short expiry to the locks used for reserving downloads in the ChunkedFile implementation to ensure that range requests for videos don't get permanently stalled (final resolution of video streaming to follow in subsequent PRs).

## References
Fixes [#10393](https://github.com/learningequality/kolibri/issues/10393)
Fixes [#10603](https://github.com/learningequality/kolibri/issues/10603)
Fixes https://github.com/learningequality/kolibri/issues/10124

## Reviewer guidance
Browse HTML5 apps and Videos on remote Kolibris to confirm that the error modal properly displays.

Screenshot from 2023-05-24 11-33-04

----

## Testing checklist

- [x] Contributor has fully tested the PR manually
- [x] If there are any front-end changes, before/after screenshots are included
- [ ] Critical user journeys are covered by Gherkin stories
- [ ] Critical and brittle code paths are covered by unit tests

## PR process

- [x] PR has the correct target branch and milestone
- [x] PR has 'needs review' or 'work-in-progress' label
- [x] If PR is ready for review, a reviewer has been added. (Don't use 'Assignees')
- [ ] If this is an important user-facing change, PR or related issue has a 'changelog' label
- [ ] If this includes an internal dependency change, a link to the diff is provided

## Reviewer checklist

- Automated test coverage is satisfactory
- PR is fully functional
- PR has been tested for [accessibility regressions](http://kolibri-dev.readthedocs.io/en/develop/manual_testing.html#accessibility-a11y-testing)
- External dependency files were updated if necessary (`yarn` and `pip`)
- Documentation is updated
- Contributor is in AUTHORS.md

### CODE REVIEW

File: kolibri/core/assets/src/views/ContentRenderer/ContentRendererError.vue [hunk 1]
```diff
@@ -1,21 +1,52 @@
 <template>
 
-  <UiAlert :dismissible="false" type="error">
-    {{ $tr('rendererNotAvailable') }}
-  </UiAlert>
+  <div>
+    <UiAlert :dismissible="false" class="alert" type="error">
```
Comment (nucleogenesis) [inline kolibri/core/assets/src/views/ContentRenderer/ContentRendererError.vue:4]: This gets me wondering if I should use [`UiAlert`](https://josephuspaye.github.io/Keen-UI/#/ui-alert) in #10739 (and then also for the `StorageNotificationBanner`) rather than applying styling ourselves?

Alternatively, perhaps we should just wrap and extend `UiAlert` in KDS as a "Banner" component.

Just a couple thoughts probably worth chatting through in an upcoming KDS Tactical

File: kolibri/plugins/perseus_viewer/assets/src/views/PerseusRendererIndex.vue [hunk 2]
```diff
@@ -91,7 +91,7 @@
   import client from 'kolibri.client';
   import urls from 'kolibri.urls';
   import responsiveWindowMixin from 'kolibri.coreVue.mixins.responsiveWindowMixin';
-  import scriptLoader from 'kolibri.utils.scriptLoader';
+  import scriptLoader from 'kolibri-common//utils/scriptLoader';
```
Comment (nucleogenesis) [inline kolibri/plugins/perseus_viewer/assets/src/views/PerseusRendererIndex.vue]: `kolibri-common//` are the double slashes intended? Any chance this could cause some kind of issue?

File: kolibri/plugins/learn/assets/src/views/TopicsContentPage.vue [hunk 3]
```diff
@@ -134,7 +135,16 @@
         :missingLessonResources="missingLessonResources"
       />
     </SidePanelModal>
-
+    <KModal
+      v-if="showConnectionErrorModal"
+      :title="deviceFormTranslator.$tr('errorCouldNotConnect')"
+      :submitText="coreString('goBackAction')"
+      @submit="goToAllLibraries"
```
Comment (nucleogenesis) [inline kolibri/plugins/learn/assets/src/views/TopicsContentPage.vue:142]: Is there a case where one piece of content doesn't work but others might from this remote device -- or is this an indication that the remote device cannot serve content to you right now in general?

File: kolibri/core/assets/src/views/ContentRenderer/ContentRendererError.vue (hunk 1 above)
Comment (nucleogenesis) [reply kolibri/core/assets/src/views/ContentRenderer/ContentRendererError.vue:4]: The UiAlert is getting mushed w/ the Video player and it looks similar on the PDF renderer so might need some margin there.

image

**Review by nucleogenesis — DISMISSED** [review]
I triggered the error by blocking the URL in dev-tools for the media request and got the modal as expected. Just have a few style notes re: the ContentError component. 

Just a minor style note on the change request front.

Also -- I had to grep Studio because I was convinced we used KContentRenderer there. I feel like there was some good reason and plan for it living in KDS but it's lost to the ether.

---

Before this merges think I should pull and link your corresponding KDS draft PR and make sure the transplant is as seamless as it appears?

File: kolibri/core/assets/src/views/ContentRenderer/ContentRendererError.vue (hunk 1 above)
Comment (rtibbles) [reply kolibri/core/assets/src/views/ContentRenderer/ContentRendererError.vue:4]: I did deliberately set the margin-bottom to 0 to make it flush to the renderer below, but seems that might not be desirable.

File: kolibri/plugins/learn/assets/src/views/TopicsContentPage.vue (hunk 3 above)
Comment (rtibbles) [reply kolibri/plugins/learn/assets/src/views/TopicsContentPage.vue:142]: If Kolibri is operating correctly, it should be the latter. At the moment, this is not the case, but I'll be hopefully fixing that in other PRs!

File: kolibri/plugins/perseus_viewer/assets/src/views/PerseusRendererIndex.vue (hunk 2 above)
Comment (rtibbles) [reply kolibri/plugins/perseus_viewer/assets/src/views/PerseusRendererIndex.vue]: Apparently my right pinky got carried away. Weirdly, I think this isn't causing an issue, but worth cleaning up regardless.

**Comment by rtibbles** [comment]
> Also -- I had to grep Studio because I was convinced we used KContentRenderer there. I feel like there was some good reason and plan for it living in KDS but it's lost to the ether.

The original plan for moving it first into `kolibri-components` and then into KDS was to make KContentRenderer a truly portable component. However, there's no good way to use the renderer plugins outside of Kolibri itself, so it ended up not being a helpful migration.

Keeping it a core part of Kolibri seems like the best path forward, and instead, we will turn Studio into a Kolibri plugin in order to be able to leverage the renderer.

**Comment by rtibbles** [comment]
> Before this merges think I should pull and link your corresponding KDS draft PR and make sure the transplant is as seamless as it appears?

I think that would be helpful, yes. If it is smooth, we can merge the KDS PR and I can do the KDS upgrade within this PR.

File: kolibri/core/assets/src/views/ContentRenderer/ContentRendererError.vue (hunk 1 above)
Comment (rtibbles) [reply kolibri/core/assets/src/views/ContentRenderer/ContentRendererError.vue:4]: I consulted with @jtamiace and have now updated this to an 8px margin all around the UIAlert. To ensure that it showed consistently, I also overrode the default UIAlert width to account for the extra margin on either side.

File: kolibri/plugins/perseus_viewer/assets/src/views/PerseusRendererIndex.vue (hunk 2 above)
Comment (rtibbles) [reply kolibri/plugins/perseus_viewer/assets/src/views/PerseusRendererIndex.vue]: Fixed!

**Comment by marcellamaki** [comment]
> we will turn Studio into a Kolibri plugin

😄

**Review by marcellamaki — CHANGES_REQUESTED** [review]
The changes within the content renderer seem to be handled well, but one scenario I encountered while testing this is going back to the topics page if the disconnect happens during content but before the popup happens, or after the content is completed. 

I just see a blank screen and get a 410 when going back without the modal prompt

Here is an example where much of the video has loaded, so though the "disconnected" state displays, the buffered video is able to continue. But if I navigate out, I am not able to go back.

https://github.com/learningequality/kolibri/assets/17235236/d94b1bf6-2266-4c5f-94f6-09af600bd251

**Comment by rtibbles** [comment]
@marcellamaki I have added some additional handling for the 410 status code specifically, which will redirect to the Library page in the edge case you have described. It would probably be better to display some sort of overlay alert or somesuch to the user after this has happened, but that may be something for a future patch (and will need a little design).

**Comment by rtibbles** [comment]
Added some additional handling here to prevent error requests being cached for a long time. Allowed successful requests to be cached for a short time regardless of whether the content cache key is set. I also added a simple error catch for updating the search labels. I hope this should resolve the remaining issues. I decided against shortening the request timeout, as I think that would be better handled by showing appropriate loading states.

**Review by marcellamaki — APPROVED** [review]
After chatting a bit more with @rtibbles - I feel good to approve this. 

Additional UI updates around loading state and UI messaging can be handled in follow up, and the error handling itself is managed here, so good to merge.
