### PR TITLE
Prevent downloading usage data on Android

### LINKED ISSUE #1894: downloading usage data doesn't work on android
Reported during 0.5.x bug bash, on Android 7:

Unable to export usage data (detail or summary logs) as Device Owner or Facility Admin.

1. Have learner generate data
2. Login as facility admin/device owner
3. Try to download logs

Nothing happens when clicking the button.

### PR DESCRIPTION
**Pull request by indirectlylit**
* moves `isAndroidWebView` to core utils
* addresses #1894 by disabling the 'download' button and showing a message indicating why:

localhost-8000-management-

resolves #1894

### CODE REVIEW

**Comment by rtibbles** [comment]
@christianmemije could you give this a spin on Android to verify?

File: kolibri/plugins/management/assets/src/views/data-page/index.vue [hunk 1]
```diff
@@ -61,9 +65,13 @@
         'A user may visit the same piece of content multiple times. This file records the total time and progress each user has achieved for each piece of content, summarized across possibly more than one visit. Anonymous usage is not included.',
       download: 'Download',
       note: 'Note',
+      noDownload: 'Download is not supported on Android',
     },
     components: { kButton },
     computed: {
+      cannotDownload() {
+        return !isAndroidWebView();
```
Comment (christianmemije) [inline kolibri/plugins/management/assets/src/views/data-page/index.vue]: Should be `return isAndroidWebView()`

**Comment by radinamatic** [comment]
Tried the `apk` from [Buildkite](https://buildkite.com/learningequality/kolibri/builds/2327#28c1ab0a-1232-4bab-abd6-1544a6e28025) on my phone (Android 6.0.1), but I still see the download button, although nothing happens when pressed (nothing to download, maybe?):

**Comment by indirectlylit** [comment]
> I still see the download button, although nothing happens when pressed 

Unfortunately, that's exactly the bug this was meant to address

**Comment by indirectlylit** [comment]
any chance you got the APK more than 8 minutes ago, before the last commit?

**Comment by radinamatic** [comment]
I tried both @indirectlylit.

**Comment by christianmemije** [comment]
@radinamatic What version does it say in the UI?

**Comment by radinamatic** [comment]
@christianmemije

**Comment by christianmemije** [comment]
Looks like it's using the incorrect kolibri version. There is an open issue about the apk build and a version issue. https://github.com/learningequality/kolibri-kivy/issues/11

**Comment by indirectlylit** [comment]
@christianmemije - apart from the version info, would you mind seeing if you reproduce what radina mentioned?

**Comment by DXCanas** [comment]
@indirectlylit confirmed still broken in 0.6, taking a look

**Comment by indirectlylit** [comment]
sorry, just rebased to resolve merge conflicts

recommend doing a hard reset to the latest

**Comment by DXCanas** [comment]
Manually tested, spoofing my desktop's user agent to every configuration listed on the page linked. Works every time. Going to need to do some more work to figure out what the _actual_ useragent is!

**Comment by DXCanas** [comment]
Updated UA tests to reflect suggestions in [the chrome docs)[https://developer.chrome.com/multidevice/user-agent#webview_user_agent]

Note that this might effect the native browsers on older android devices, though I'm not entirely sure Kolibri even runs on those. Going to test after the WHL file is built, will post updates here.

**Comment by radinamatic** [comment]
Installed the [APK from Buildkite](https://buildkite.com/learningequality/kolibri/builds/2595#0e6d1c63-da0c-4e78-a474-8dd5abb1ff2d), I'm still seeing the `Download` button, and it's active as before.
Same phone as above.

**Comment by radinamatic** [comment]
Any reason why the `Import` wouldn't work on this same build? Seemed to get started OK, but then got stuck, and when I re-tried, I got 500 server error:

**Comment by DXCanas** [comment]
@radinamatic 

> Installed the APK from Buildkite, I'm still seeing an active Download button as before.
Same phone as above.

Seems like the APK on buildkite are out of data or not building properly. I tested them too, and had a moment of dismay while I debugged. 

Decided to build it myself (manually) using the latest version of `kolibri-kivy` and it works as expected!
screenshot_20170920-115921

[You can download the apk here if you'd like to try it yourself](https://drive.google.com/a/learningequality.org/file/d/0B2IMyKvMs6rANU5XS2ZKa28yVEk/view?usp=sharing)

**Comment by DXCanas** [comment]
@indirectlylit Seems to be working ok for me on a manual build. Any styling suggestions? I can have it go below the button to prevent the line from breaking

**Comment by radinamatic** [comment]
@DXCanas sorry about the moment of dismay... :stuck_out_tongue: 

I'll test the `APK` you uploaded, but is there hope we can fix the Android builds on Buildkite?

**Comment by DXCanas** [comment]
@radinamatic 
> Any reason why the Import wouldn't work on this same build? Seemed to get started OK, but then got stuck, and when I re-tried, I got 500 server error

Not seeing that  in the manually-built APK!
screenshot_20170920-124127
screenshot_20170920-124124

Seems I might need to consult whoever set up the build process. Likely need to wait for [this PR]() to be merged though.
