### PR TITLE
More exam updates

### LINKED ISSUE #2607: Invalid prop: type check failed for prop "completionTimestamp"
### Observed behavior

When viewing an exam report in Coach at this URL:

```
http://localhost:8000/coach/#/eba8f3c694d0d9cb3a9170c81f7e076d/fb51dae6df7545af8455aa3a0c32048d/exams/1d271e1a668d735b254de7a52920f01c/users/d98b14a36191d92a0e85b277a54c3d62/0/0
```

saw this error a few times;

```
Invalid prop: type check failed for prop "completionTimestamp". Expected Date, got String.
```

### Steps to reproduce

* create and activate exam
* take and submit exam without answering any questions
* deactivate exam and view report

### Context

* Kolibri version: 0.7

### PR DESCRIPTION
**Pull request by christianmemije**
###  Summary

Implement update details and copy exam

Fixes #2607

### Reviewer guidance

Test those modals.

### Contributor Checklist

- [x] Contributor has fully tested the PR manually
- [x] PR has the correct target branch and milestone
- [x] PR has 'needs review' or 'work-in-progress' label
- [x] If PR is ready for review, a reviewer has been added. (Don't use 'Assignees')
- [ ] If there are any front-end changes, before/after screenshots are included
- [ ] If this is an important user-facing change, PR or related issue has a 'changelog' label

### Reviewer Checklist

- [ ] Automated test coverage is satisfactory
- [ ] Reviewer has fully tested the PR manually
- [ ] PR has been tested for [accessibility regressions](http://kolibri-dev.readthedocs.io/en/develop/manual_testing.html#accessibility-a11y-testing)
- [ ] External dependencies files were updated (`yarn` and `pip`)
- [ ] Documentation is updated
- [ ] Link to diff of internal dependency change is included
- [ ] CHANGELOG.rst is updated for high-level changes
- [ ] Contributor is in AUTHORS.rst

### CODE REVIEW

File: kolibri/plugins/coach/assets/src/views/exams/create-exam-page/index.vue [hunk 1]
```diff
@@ -415,20 +401,16 @@
...
-            numQuestions: this.inputNumQuestions,
-            questionSources: this.questionSources,
+            question_count: this.inputNumQuestions,
+            question_sources: this.questionSources,
             seed: this.seed,
-            channelId: this.dummyChannelId,
+            assignments: [{ collection: this.classId }],
           };
-          this.createExam(classCollection, examObj);
+          this.createExamAndRoute(exam);
```
Comment (jonboiser) [inline kolibri/plugins/coach/assets/src/views/exams/create-exam-page/index.vue:419]: it looks you could inline `exam` here

File: kolibri/plugins/coach/assets/src/views/exams/exam-report-page/ManageExamModals.vue [hunk 2]
```diff
@@ -100,12 +101,53 @@
           this.deactivateExam(this.exam.id);
         }
       },
+      handleUpdateExamDetails(details) {
+        const payload = {};
+        const assignmentsAreSame =
```
Comment (jonboiser) [inline kolibri/plugins/coach/assets/src/views/exams/exam-report-page/ManageExamModals.vue:106]: could you use something like `lodash/xor` to see if the symmetric difference of the two assignments arrays is non-empty (implying they are different, considered as sets).

File: kolibri/core/exams/api.py [hunk 3]
```diff
@@ -29,10 +29,27 @@ class Meta:
...
         fields = ['collection', ]
 
+def _ensure_raw_dict(d):
+    if hasattr(d, "dict"):
+        d = d.dict()
+    return dict(d)
+
+
+class ExamPermissions(KolibriAuthPermissions):
+    # Overrides the default validator to sanitize the Lesson POST Payload
```
Comment (jonboiser) [inline kolibri/core/exams/api.py]: You should update or remove these comments, since they refer to 'Lessons'

File: kolibri/plugins/coach/assets/src/views/index.vue [hunk 4]
```diff
@@ -152,19 +153,29 @@
           if (resourceUserPages.includes(this.pageName)) {
             return this.$tr('resourceUserPageToolbarHeader');
           }
+          if (resourceUserPages.includes(this.pageName)) {
```
Comment (christianmemije) [inline kolibri/plugins/coach/assets/src/views/index.vue:156]: Oops
