### PR TITLE
Radio button descriptions + cleanup

### LINKED ISSUE #3401: Font sizes and spacing of radio text on "Add new account"
### Observed behavior

image

### Expected behavior

- Would expect explanation text to be smaller/less prominent than the title (or that they were combined somehow, e.g. with a colon, rather than linebreak).
- The explanation for "Class coach" is closer to the "Facility coach" radio button than its own button, which feels messy/misleading.

### Context

Kolibri 0.9.0 beta demo site

### PR DESCRIPTION
**Pull request by DXCanas**
### Summary

setup wizard
create user modal
edit user modal

Allows for descriptions to be added to radio button labels in a uniform way across the app.
- [x] Add new `description` prop
- [x] [Style new `description` prop according to work in setup wizard] (https://github.com/learningequality/kolibri/issues/3401#issuecomment-375490135)
- [x] Use new `description` prop in appropriate intances of `k-radio-button`
- [x] [Clean up class names](https://learningequality.slack.com/archives/C0LE9NLCE/p1518643740000442?thread_ts=1518638722.000471&cid=C0LE9NLCE)
- [x] Fix recurring bug of radio button selection not being directly reflective of the radio buttons's state
    - [x] Clean up logic, which is handling 2 different forms of state for `checked` and `selected` state
- [x] Fix `focus` accessibility issues (unchecked boxes are never highlighted, inconsistent with HTML behavior)
- [x] [Fix `v-model` behavior (cross-compatibility issues with the `@input` event on `<input type="radio">`)](https://developer.mozilla.org/en-US/docs/Web/Events/input#Browser_compatibility)

### Reviewer guidance

First commit has the simplest way to build on top of current `k-radio-button` to include descriptions.

Subsequent commits include cleanup and logic simplifications to address some of the quirks/issues I've ran into while using the radio button.

If you all think it's necessary, I'll break the first commit out for quick merge and continue the radio button work later.

### References

- Fixes #3401
- https://github.com/learningequality/kolibri/issues/3401#issuecomment-375490135
- [Discussion around new CSS class naming standards](https://learningequality.slack.com/archives/C0LE9NLCE/p1518643740000442?thread_ts=1518638722.000471&cid=C0LE9NLCE)
- [MDN docs describing `@input` incompatibility issues](https://developer.mozilla.org/en-US/docs/Web/Events/input#Browser_compatibility)
- [Potential improvements to the API using newer Vue features](https://vuejs.org/v2/guide/components-custom-events.html#Binding-Native-Events-to-Components)

----

### Contributor Checklist

- [x] Contributor has fully tested the PR manually
- [x] PR has the correct target branch and milestone
- [x] PR has 'needs review' or 'work-in-progress' label
- [x] If PR is ready for review, a reviewer has been added. (Don't use 'Assignees')
- [x] If there are any front-end changes, before/after screenshots are included
- [x] If this is an important user-facing change, PR or related issue has a 'changelog' label

### Reviewer Checklist

- [ ] Automated test coverage is satisfactory
- [ ] Reviewer has fully tested the PR manually
- [ ] PR has been tested for [accessibility regressions](http://kolibri-dev.readthedocs.io/en/develop/manual_testing.html#accessibility-a11y-testing)
- [ ] External dependencies files were updated (`yarn` and `pip`)
- [ ] Documentation is updated
- [ ] Link to diff of internal dependency change is included
- [ ] CHANGELOG.rst is updated for high-level changes
- [ ] Contributor is in AUTHORS.rst

### CODE REVIEW

File: kolibri/core/assets/src/views/k-radio-button.vue [hunk 1]
```diff
@@ -62,14 +65,21 @@
...
        */
       value: {
         type: [String, Number, Boolean],
         required: true,
       },
       /**
-       * Unique value of the particular radio
+       * Unique value of the particular radio - the data that this button can assign
        */
       radiovalue: {
```
Comment (DXCanas) [inline kolibri/core/assets/src/views/k-radio-button.vue]: `value` vs `radiovalue` is confusing IMO. 

Down the line, I'd like to use [Vue's `model` API](https://vuejs.org/v2/api/#model) to free up `value` to be used as `radiovalue` while maintaining `v-model` functionality. [The feature exists for this sole purpose](https://vuejs.org/v2/guide/components-custom-events.html#Customizing-Component-v-model).

Anyone have thoughts on this?

File: kolibri/core/assets/src/views/k-radio-button.vue [hunk 2]
```diff
@@ -141,55 +137,47 @@
...
   $radio-height = 24px
 
-  .k-radio-container
-    display: table
+  .k-radio-button
+    // give conditional classes higher priority
+    &.disabled
+      cursor: default
+    position: relative
+    cursor: pointer
```
Comment (christianmemije) [inline kolibri/core/assets/src/views/k-radio-button.vue]: Would be nice if the radios had the pointer cursor and that a disabled radio label did not have the pointer.
current

File: kolibri/core/assets/src/views/k-radio-button.vue (hunk 1 above)
Comment (christianmemije) [reply kolibri/core/assets/src/views/k-radio-button.vue]: I am totally down with that. :pray:  I regret implementing it how I did.

File: kolibri/core/assets/src/views/k-radio-button.vue [hunk 3]
```diff
@@ -62,14 +64,21 @@
         required: true,
       },
       /**
-       * v-model value
+       * Description for Label
```
Comment (christianmemije) [inline kolibri/core/assets/src/views/k-radio-button.vue]: `Description for the label`

File: kolibri/core/assets/src/views/k-radio-button.vue [hunk 4]
```diff
@@ -62,14 +64,21 @@
...
+       */
+      description: {
```
Comment (christianmemije) [inline kolibri/core/assets/src/views/k-radio-button.vue]: We need to also update the radio button guidelines to include this new description.

File: kolibri/core/assets/src/views/k-radio-button.vue [hunk 5]
```diff
@@ -1,47 +1,49 @@
...
+      :class="['unchecked', {disabled, active}]"
+    />
+
+    <span :class="['text', {disabled}]">
+      {{ label }}
+      <span
+        v-if="description"
+        :class="['description', {disabled}]"
+      >
+        <br>
```
Comment (indirectlylit) [inline kolibri/core/assets/src/views/k-radio-button.vue]: minor note - don't need to change...

might have been better if the description and label were implemented as two block-level `div`s

https://developer.mozilla.org/en-US/docs/Web/HTML/Element/br

File: kolibri/core/assets/src/views/k-radio-button.vue (hunk 1 above)
Comment (indirectlylit) [reply kolibri/core/assets/src/views/k-radio-button.vue]: seems reasonable to me, and agree that `value` vs `radiovalue` is confusing

@christianmemije do you recall if there was a specific motivation for the current setup?

**Comment by indirectlylit** [comment]
image

the line height on the small text is the same as the line height on the large text, which looks a bit off

File: kolibri/core/assets/src/views/k-radio-button.vue (hunk 1 above)
Comment (DXCanas) [reply kolibri/core/assets/src/views/k-radio-button.vue]: Can’t speak for Christian, but I have a feeling it had to do with wanted to be v-model compatible, which requires the value prop to hold the assigned value

File: kolibri/core/assets/src/views/k-radio-button.vue (hunk 5 above)
Comment (DXCanas) [reply kolibri/core/assets/src/views/k-radio-button.vue]: This was the case in my first few iterations. Wanted to avoid block level because I wanted <label to be the top level tag and Block level tags within <label aren’t valid HTML. 

https://developer.mozilla.org/en-US/docs/Web/HTML/Element/label

I had display:block on a few of the tags as well, but remembered the discussion we had about mixing online and block elements, opting for this approach. 

Doing it this way ^ is the quickest way to get rid of the <br

Tried using k-grid too, but this seemed simpler after implementing it. Also couldn’t define anything other than a <div, which brought me back to the first point.

Comment (indirectlylit) [reply kolibri/core/assets/src/views/k-radio-button.vue]: Note that using multiple block-level elements might also help with the line-height issue I mentioned below, because you can give each one its own line height.

> I had display:block on a few of the tags as well, but remembered the discussion we had about mixing online and block elements, opting for this approach.

A few `span`s with `display: block` seems like a reasonable workaround if we're getting validation errors putting `div`s inside the `label`. (I didn't know that was the case!)

But yes, within a single parent, all children should either be inline or block-level - not mixed.

> Tried using k-grid 

agreed, `k-grid` doesn't seem like the solution here

Comment (DXCanas) [reply kolibri/core/assets/src/views/k-radio-button.vue]: > ..reasonable workaround if we're getting validation errors putting divs inside the label. (I didn't know that was the case!)

It actually isn't! There aren't any build error or anything, it's just not HTML spec-compliant.

File: kolibri/core/assets/src/views/k-radio-button.vue (hunk 2 above)
Comment (DXCanas) [reply kolibri/core/assets/src/views/k-radio-button.vue]: Should the label also have a pointer?

**Comment by DXCanas** [comment]
Made the v-model change! Pretty clean, using `currentvalue` as the `v-model` prop.

**Comment by indirectlylit** [comment]
looks good! thanks for these changes
