### PR TITLE
No more 1000%

### LINKED ISSUE #4857: users should not be able to get 1000% on an exam, unfortunately
### Observed behavior

reported by @jtamiace re: @radinamatic's apparent good luck:

image

### Expected behavior

exams are scored between 0 and 100

### User-facing consequences

????

### Errors and logs

unknown

### Steps to reproduce

see http://kolibribeta.learningequality.org/coach/#/fa4cbfeda32c0c0fbf1832fc1ddd10c3/reports/learners

### Context

k 0.12.0 alpha 7

### PR DESCRIPTION
**Pull request by rtibbles**
### Summary
Creates average score based on `question_count` rather than the length of `question_sources` on the exam model, to give consistent scoring between v0 and v1 exams.

### Reviewer guidance
Use sample data referenced in the issue.

### References
Fixes #4857

----

### Contributor Checklist

PR process:

- [x] PR has the correct target branch and milestone
- [x] PR has 'needs review' or 'work-in-progress' label
- [x] If PR is ready for review, a reviewer has been added. (Don't use 'Assignees')
- [ ] If this is an important user-facing change, PR or related issue has a 'changelog' label
- [ ] If this includes an internal dependency change, a link to the diff is provided

Testing:

- [ ] Contributor has fully tested the PR manually
- [ ] If there are any front-end changes, before/after screenshots are included
- [ ] Gherkin stories have been updated
- [ ] Unit tests have been updated

### Reviewer Checklist

- Automated test coverage is satisfactory
- PR is fully functional
- PR has been tested for [accessibility regressions](http://kolibri-dev.readthedocs.io/en/develop/manual_testing.html#accessibility-a11y-testing)
- External dependency files were updated if necessary (`yarn` and `pip`)
- Documentation is updated
- Contributor is in AUTHORS.rst

### CODE REVIEW

File: kolibri/plugins/coach/assets/src/modules/classSummary/index.js [hunk 1]
```diff
@@ -39,6 +39,7 @@ function defaultState() {
      *     question_sources: [{exercise_id, question_id}, ...],
      *     groups: [id, ...],
      *     data_model_version,
+     *     question_count,
```
Comment (indirectlylit) [inline kolibri/plugins/coach/assets/src/modules/classSummary/index.js:42]: we're going to want to update the unit tests to have conforming data: 

* https://github.com/learningequality/kolibri/blob/develop/kolibri/plugins/coach/assets/src/modules/classSummary/__test__/sampleServerResponse.js
* https://github.com/learningequality/kolibri/blob/develop/kolibri/plugins/coach/assets/src/modules/classSummary/__test__/sampleState2.js

would you mind either updating those, or opening a new tech debt issue indicating that we should update them?

**Comment by jamalex** [comment]
Looks right to me, from what I saw of the data structures.

**Review by jamalex — APPROVED** [review]

File: kolibri/plugins/coach/assets/src/modules/classSummary/index.js (hunk 1 above)
Comment (rtibbles) [reply kolibri/plugins/coach/assets/src/modules/classSummary/index.js:42]: Looks like I don't have a choice if I want tests to pass!

File: kolibri/plugins/coach/assets/src/modules/classSummary/__test__/sampleState.js [hunk 2]
```diff
@@ -185,6 +191,8 @@ export default {
         { exercise_id: '9baf781e43b0514085cc205176b0ee71', question_id: 'z' },
       ],
       groups: [],
+      data_version_model: 1,
+      question_count: 3,
```
Comment (indirectlylit) [inline kolibri/plugins/coach/assets/src/modules/classSummary/__test__/sampleState.js:195]: https://github.com/learningequality/kolibri/issues/4940
